{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-buildcache-SNAPSHOT/kmock-0.3.0-rc01-fix-buildcache-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-buildcache-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-buildcache-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-buildcache-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "2533a3604245c7d8e2fb4073a791ae50ef19d201fffe0237443c7975597c01719a1624da224460a075126b71d4772e03ba2a9b27dc488ffc19c0e2a8cfc2be8a",
          "sha256": "cb2444e9614a8648f3349aefe826029e0dc2d556be93d290f8c672f1774ff7be",
          "sha1": "8486c7d5288edf4cb790a5e21e9f9508cffa969b",
          "md5": "95402ddb596bba049034e56777528cc4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-buildcache-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-buildcache-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "2533a3604245c7d8e2fb4073a791ae50ef19d201fffe0237443c7975597c01719a1624da224460a075126b71d4772e03ba2a9b27dc488ffc19c0e2a8cfc2be8a",
          "sha256": "cb2444e9614a8648f3349aefe826029e0dc2d556be93d290f8c672f1774ff7be",
          "sha1": "8486c7d5288edf4cb790a5e21e9f9508cffa969b",
          "md5": "95402ddb596bba049034e56777528cc4"
        }
      ]
    }
  ]
}
