{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-change-processor-provider-SNAPSHOT/kmock-0.3.0-rc02-change-processor-provider-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-change-processor-provider-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc02-change-processor-provider-SNAPSHOT.klib",
          "size": 202494,
          "sha512": "e3df69e77657afa1122994eed0f82e84560e47e15b6a03251d00a2ba5953108b91a55a524f8e3d7a2d10a69c52fb16e71fa4674c6de9f96aa451a3d50148cf63",
          "sha256": "42735e49756ccd0c6eb78427af20039e664b69d22bdb2451f618fbe52a8d58c0",
          "sha1": "463022fcbd4d66ad66e5e5239ae6227faeae75e9",
          "md5": "c5c2bb5c4dbf58fcee38949e5f15da53"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc02-change-processor-provider-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc02-change-processor-provider-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "28edcc23043d94be80241f20ce5e7c0e9068c456d535dd4c1794a37d9dd085dfaf34f65000096062cb970e2dea0f904dd0f278dd561e653d562b2de44db55b90",
          "sha256": "e7d6d40dd2fb96c36da3c7989e4d1b6ff9d856f71b4d6a1f477601a06bc0e056",
          "sha1": "0662c66d5cac086bf5d26ba63228bacf6e813755",
          "md5": "dd946bcc5c97d487c759bf2ef1ab676b"
        }
      ]
    }
  ]
}
