{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc05-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT.jar",
          "size": 75456,
          "sha512": "9e89d55fdc626b82a38a7fd2ed1a74c10cd88f0cb92ec0b567c6681f433a19256794e782df8941102c4cca54a992991430e2f7d9119d7032261adcddb44eed80",
          "sha256": "6f6fd845969ddc6119c8773f14fcfbfc55535a4b1eadcdd1284646031e9f9a43",
          "sha1": "e98163f46490a45d99cdbe7b726b9f4d0f8cd08c",
          "md5": "bf7c4ad9a0a3fb96b07e855d3c41b914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.21-1.0.8"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT.jar",
          "size": 75456,
          "sha512": "9e89d55fdc626b82a38a7fd2ed1a74c10cd88f0cb92ec0b567c6681f433a19256794e782df8941102c4cca54a992991430e2f7d9119d7032261adcddb44eed80",
          "sha256": "6f6fd845969ddc6119c8773f14fcfbfc55535a4b1eadcdd1284646031e9f9a43",
          "sha1": "e98163f46490a45d99cdbe7b726b9f4d0f8cd08c",
          "md5": "bf7c4ad9a0a3fb96b07e855d3c41b914"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "8046506c5805fb4a3ab2e2f5310813d36eb6b39ea5d5dae198b6acb6e93a64ad8fe2e9ab0deed88a6f731b0f0c5dff2633e180df643e4e2662569a5a2db530b9",
          "sha256": "65c438760167372bdc7a07114b0584ade5df417af05c63e9b4c6afc0ca644710",
          "sha1": "7e74c5bddbad6778dd59e48866a34b3f07b1ebdb",
          "md5": "5795e897afae9a25ea12d3cfe9c70a44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-setup-SNAPSHOT-sources.jar",
          "size": 14718,
          "sha512": "61e4e8b181801b7da1b22d1f620881494beea496217197bd3d384706785e63e6ff474bbeb4d05e50d7c9dc78acebc68f22487726db8660cf2799f9bf687248ef",
          "sha256": "1a8586b5a20c5c7b579a440b3ed604535c39d12eab99d9952754b538ca7703ff",
          "sha1": "cd7f4398e49c2c9732afb8a0488d35bff6dc975e",
          "md5": "7fa820c2a04334ba9b1a4b9fb099acff"
        }
      ]
    }
  ]
}
