{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203101,
          "sha512": "425a3c9389d5613e06954120459273b4a2972e37a58afc6254246f16e7ac160a48b39df5c6763cea229c1ebbe5be1c9bee0bc81f8a56163da2b7e02d44f2fde0",
          "sha256": "91a8c484815d75c4b96ffa23dd12a487a391c822a21386f9c234b066d602a64e",
          "sha1": "5823df8315cd08473b16b9a5226522e3da7a381f",
          "md5": "7677326ec58b9fec73792041cfc90e88"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bedee541eb30de9823b4a8e369dc13e3918938396ef121867aedcf0d45e15539e680d9ad5028960865126c9dd47f9ac57b15adc0dc316e63660d9e9b0365137c",
          "sha256": "29b76efcee88f5c871ff17025e8d5cf2463948b86def45ac6ed42e033852aa3e",
          "sha1": "4cd4202e29555653de2f58bad2e6fd0e395ee6c1",
          "md5": "67bcbeb3281142d4a16baa0ae2d6a4e3"
        }
      ]
    }
  ]
}
