{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/694b583-change-setup-SNAPSHOT/test-utils-resourceloader-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-macosx64-694b583-change-setup-SNAPSHOT.klib",
          "size": 12866,
          "sha512": "8ad3f1e2876ecb5e87f59a958685c0821682dfed598d87593055fb8bf5f1991b708b5c7af0373b105897d48aeb159c008407cd389ea27020c403aafaa64fa8a1",
          "sha256": "d3526b0860ca683adc91be933bd209cea744cb85720b32decad40ed2297b9afe",
          "sha1": "be622699d30496853132a29aaee77b823fcb6d0a",
          "md5": "9e74148237e38fbf7dc68f1aaf6e2768"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-macosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-macosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "03b29ef49baa451db425a538a0e848d1fde90e9b1eaad13b53c363c7646d5fc0c9a14e7c65fe35f35f02a1561bec8c763730b72db756a2ae9eac96501bec405a",
          "sha256": "aec4b25fed8603ec146cb88aa4fa0aceca7b9a9ddeacf38841a59a41b8219f14",
          "sha1": "dd7870aeed697b505f412c938652e4bef03b782a",
          "md5": "442ec44fd87a68c3155c2d5d489d3308"
        }
      ]
    }
  ]
}
