{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "ec26e5e-add-shared-detekt-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-dependency-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "50a747ceb174f2086f42f25d038390aa1ce25be9ebc33a1a699c579c3a5fba83191248898292ce65d94101231192665ff52a3ba06ec0521d4fcd5e6ede09f784",
          "sha256": "7227f0d5563b788a8356480004d86cab74b4485bc1abcd4291a16d7fc4003c6d",
          "sha1": "2d99f6a4e8294efcfbfc9314b44d6faa602218ad",
          "md5": "cd14afb4fcb6329986372757e9080291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ec26e5e-add-shared-detekt-config-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-dependency-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "50a747ceb174f2086f42f25d038390aa1ce25be9ebc33a1a699c579c3a5fba83191248898292ce65d94101231192665ff52a3ba06ec0521d4fcd5e6ede09f784",
          "sha256": "7227f0d5563b788a8356480004d86cab74b4485bc1abcd4291a16d7fc4003c6d",
          "sha1": "2d99f6a4e8294efcfbfc9314b44d6faa602218ad",
          "md5": "cd14afb4fcb6329986372757e9080291"
        }
      ]
    }
  ]
}
