{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-numeric-api-ubyte-SNAPSHOT/core-0.2.0-change-numeric-api-ubyte-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-numeric-api-ubyte-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-change-numeric-api-ubyte-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-numeric-api-ubyte-SNAPSHOT.jar",
          "size": 113913,
          "sha512": "1b5d15f25d1cd7d67463aa8e9cd6d45c15421120e752c6d154d319e7db31dac186ffaec3222b9f5ab315a34cd0f4a0d6b03ae8220a69beb3c9816f8c08981611",
          "sha256": "746a7d9b209760aeb5089bf09cab71433e4ccac18ab9d90c0fae92dfecff0a8b",
          "sha1": "43ed2c4a7be2335a9678b3d791e81ff9b7c2307c",
          "md5": "e34e21d47bc76c7a59032c4e1ef75929"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-change-numeric-api-ubyte-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-numeric-api-ubyte-SNAPSHOT.jar",
          "size": 113913,
          "sha512": "1b5d15f25d1cd7d67463aa8e9cd6d45c15421120e752c6d154d319e7db31dac186ffaec3222b9f5ab315a34cd0f4a0d6b03ae8220a69beb3c9816f8c08981611",
          "sha256": "746a7d9b209760aeb5089bf09cab71433e4ccac18ab9d90c0fae92dfecff0a8b",
          "sha1": "43ed2c4a7be2335a9678b3d791e81ff9b7c2307c",
          "md5": "e34e21d47bc76c7a59032c4e1ef75929"
        }
      ]
    }
  ]
}
