{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clientSDK/b87036e-add-more-platforms-SNAPSHOT/clientSDK-b87036e-add-more-platforms-SNAPSHOT.module",
    "group": "tech.antibytes.awesomecats",
    "module": "clientSDK",
    "version": "b87036e-add-more-platforms-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK.klib",
          "url": "clientSDK-iosx64-b87036e-add-more-platforms-SNAPSHOT.klib",
          "size": 45913,
          "sha512": "ce461ca3df50d7bc356d402c40bffafe9681f1d02b4f3aa4145eb06006605fbc7910fc8fe91c4bacc0ffb85caf38f0605e7d1d923d734724e833626456af01e2",
          "sha256": "1d2c9625d209e82cb0d1014ed14e5bf275499c54571e83593878113850ffc87c",
          "sha1": "f38baeeb9b3ca103b34301f2d5c65d39468d8580",
          "md5": "faec64a10cfc690a2d299cbe750c3475"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK-iosx64-b87036e-add-more-platforms-SNAPSHOT-metadata.jar",
          "url": "clientSDK-iosx64-b87036e-add-more-platforms-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "41f76eef9a3e7b72f1110a9ada9cf3fd639371af1a6c0152aef00bcb3f655477b981ad809ac145ffaec5651b09882992352f316ea82ae5d69991da3058115f1d",
          "sha256": "814af9527585fb6e13a476d6773093e032181ddc490c7004e6a826095df270cc",
          "sha1": "d415f9d078bc02751154a597f8393dc19d7efa9a",
          "md5": "0f00e0941aa47bc6b85dccd185d92cf3"
        }
      ]
    }
  ]
}
