{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "1c3c48e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-1c3c48e.jar",
          "url": "antibytes-configuration-1c3c48e.jar",
          "size": 33915,
          "sha512": "81c4b272e555f44b1900d558bdd9d3258c3fcdf703c43f1d68be00c2cb8a0a8fdaafd03c6022494695794662e1a968678ac710452d01aa550fc83847962bc83d",
          "sha256": "09ee4ddfe908993e7683110c8e2bd5f1f14c075b3ad1357ac5b5f9367f7b1941",
          "sha1": "32aa4c3417716efd082cafdf4c59ac739fb1f3a5",
          "md5": "94400847566c01a1353d32a77aeae08a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1c3c48e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-1c3c48e.jar",
          "url": "antibytes-configuration-1c3c48e.jar",
          "size": 33915,
          "sha512": "81c4b272e555f44b1900d558bdd9d3258c3fcdf703c43f1d68be00c2cb8a0a8fdaafd03c6022494695794662e1a968678ac710452d01aa550fc83847962bc83d",
          "sha256": "09ee4ddfe908993e7683110c8e2bd5f1f14c075b3ad1357ac5b5f9367f7b1941",
          "sha1": "32aa4c3417716efd082cafdf4c59ac739fb1f3a5",
          "md5": "94400847566c01a1353d32a77aeae08a"
        }
      ]
    }
  ]
}
