{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/30251df-change-workflows-SNAPSHOT/test-utils-ktor-30251df-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "30251df-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-30251df-change-workflows-SNAPSHOT.klib",
          "size": 15009,
          "sha512": "4e93ca692b3d72fbf9a4fdbd794f94a5ec38e33d445f7b94e637b151886b8730c15640e54b415bdfcaec9e1fae201c62d3ed351921ab0b4f73345ca84dc3fe40",
          "sha256": "41f9a94cd7e9c2fcf9efb9701afb93e9a22e5a8a0a0a98efd58d4a6574e3e65b",
          "sha1": "26b1deaf53980bf22abda88f41ca1c851780377d",
          "md5": "32ddceaa1e4e3f1feafdac0a398985f1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-30251df-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosx64-30251df-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9daddea4f067b08941b5ac0580eec41b3da36fc39107d0b223e709b7c24e552710db37a24edbcebde4be158a764fc0def5e24b11414a07610c9d16285fb652bd",
          "sha256": "fb8fc6d2ae2f6c963ddf58f7efc14017c2768afb0cdf9a58953abd2243360c60",
          "sha1": "47b0105ba0dcfa282ce4d4569af941683d9e7b04",
          "md5": "0f8169131d2255ab0af18b3ee09aeba1"
        }
      ]
    }
  ]
}
