{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "053069d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-053069d.jar",
          "url": "antibytes-configuration-053069d.jar",
          "size": 50665,
          "sha512": "35c8408a14a09319341e688f1fb06a1ad7ace994298764832c816f40082be395886c2e61eda1c7981607d57482046f67f5c1e6dbbe6df421e128a30836331e55",
          "sha256": "dfa5f986959bbdb937bfec2a81eb155b6dfbafe557d9bae9cf97dfdc3a883b88",
          "sha1": "2f633432a93f75213fea091604e0c03aae2be23f",
          "md5": "8d017beddeb64af5b9bc443919896bfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "053069d"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-053069d.jar",
          "url": "antibytes-configuration-053069d.jar",
          "size": 50665,
          "sha512": "35c8408a14a09319341e688f1fb06a1ad7ace994298764832c816f40082be395886c2e61eda1c7981607d57482046f67f5c1e6dbbe6df421e128a30836331e55",
          "sha256": "dfa5f986959bbdb937bfec2a81eb155b6dfbafe557d9bae9cf97dfdc3a883b88",
          "sha1": "2f633432a93f75213fea091604e0c03aae2be23f",
          "md5": "8d017beddeb64af5b9bc443919896bfe"
        }
      ]
    }
  ]
}
