{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "f26a416",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-f26a416.jar",
          "url": "antibytes-gradle-utils-f26a416.jar",
          "size": 9580,
          "sha512": "fb7cd4773b1ee73280dc4f70a88555dd63c1d80f5a04982b482151c13b35cf9e028a4944e019e23b10ad83a3a76f3c7cba5a36a87225b50072555602befd5e44",
          "sha256": "666d11909918fb0e23b56c76f83d09d600d6f182d502bf54dbad64fafce1cb2e",
          "sha1": "00f6313bb001a1a8ea5781d3836b32ac096336a5",
          "md5": "1446921153d4f05b678ab61519e9cb8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-f26a416.jar",
          "url": "antibytes-gradle-utils-f26a416.jar",
          "size": 9580,
          "sha512": "fb7cd4773b1ee73280dc4f70a88555dd63c1d80f5a04982b482151c13b35cf9e028a4944e019e23b10ad83a3a76f3c7cba5a36a87225b50072555602befd5e44",
          "sha256": "666d11909918fb0e23b56c76f83d09d600d6f182d502bf54dbad64fafce1cb2e",
          "sha1": "00f6313bb001a1a8ea5781d3836b32ac096336a5",
          "md5": "1446921153d4f05b678ab61519e9cb8c"
        }
      ]
    }
  ]
}
