{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/f8d6e50-bump-workflows-SNAPSHOT/test-utils-coroutine-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 10164,
          "sha512": "2fb7cd776c1660d5648efaa4036c8d7ad1730e862b34b5a4eb64639d32d8c59a59ff868da2212593f9f3058af89d61bae6c82a53fef3093e15760de0d773f88b",
          "sha256": "5a5b0ea09a6a4c57f7123ecd687e777a3e02210e37449d91da11d4996b35a215",
          "sha1": "5d0681f27128c0942d77dc89c08dc2e94b53b672",
          "md5": "7cd70034613cfc6520c2eca14803f014"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1f06b47559ec6fc6971906d7dc32769a58c57e547418e9c23c55ce0b5c38747581ef0190a3b593329f6cbfd014634e339eedf5e8ac5879a33fc9ced1a0746faa",
          "sha256": "1d953caa7cffdc5a460e3af2361809721f8fc8c63d2c570ba52b8625fd0d0865",
          "sha1": "6e7fc49e5c9af75507dec09c77ffd2ec2435ae5c",
          "md5": "613c3971a53a9483636c0f526b44d2be"
        }
      ]
    }
  ]
}
