{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "baa101e-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-baa101e-bump-updates-SNAPSHOT.jar",
          "size": 26844,
          "sha512": "d2031769bba18207d7f529b358d453097ad91124c17644e945b3f9232d4886445d31b1f0aa1dfd10b0167853cdc347bd8f2a8e8b495ef011baa4455f5426a0fe",
          "sha256": "64818dd17d6a2b5d8b275759838dbd5b487cdd34fb65125ad91bf0baac1dd114",
          "sha1": "d14fc55d63ce59aa8e2543d2eb2a61c57daee046",
          "md5": "96d0541bf3f4402526375db550bbb353"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/baa101e-bump-updates-SNAPSHOT/banana-i18n-android-baa101e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "baa101e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/baa101e-bump-updates-SNAPSHOT/banana-i18n-android-baa101e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "baa101e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/baa101e-bump-updates-SNAPSHOT/banana-i18n-jvm-baa101e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "baa101e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/baa101e-bump-updates-SNAPSHOT/banana-i18n-jvm-baa101e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "baa101e-bump-updates-SNAPSHOT"
      }
    }
  ]
}
