{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/333b690-change-workflows-SNAPSHOT/test-utils-333b690-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "333b690-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "ef109c3add7d2682b058f5e515d7c2d15a5c62689a61cb25e127d33f1f22e9ce1f953bff0b9661ff6d906a00e434926db3e5398a20ac2b77a061db50c703d71b",
          "sha256": "37bf4bb5c9e1e7de5663993740bf6bf0568f3c3c9f629380f7ef9be697c6d783",
          "sha1": "8ef0d7bf63de4cbefc60a4fc50515af1a32031e5",
          "md5": "341f7a4a655c13005248195919179108"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "ef109c3add7d2682b058f5e515d7c2d15a5c62689a61cb25e127d33f1f22e9ce1f953bff0b9661ff6d906a00e434926db3e5398a20ac2b77a061db50c703d71b",
          "sha256": "37bf4bb5c9e1e7de5663993740bf6bf0568f3c3c9f629380f7ef9be697c6d783",
          "sha1": "8ef0d7bf63de4cbefc60a4fc50515af1a32031e5",
          "md5": "341f7a4a655c13005248195919179108"
        }
      ]
    }
  ]
}
