{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c660192-change-min-android-version-SNAPSHOT/test-utils-ktor-c660192-change-min-android-version-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c660192-change-min-android-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-c660192-change-min-android-version-SNAPSHOT.klib",
          "size": 14916,
          "sha512": "44c9503557f1028557f210b11c0e3ffe2199994a3aa65b0f141aa311f92a63ea5b3758d995fbeceac150d00f21eb560d1e4e1c78ae05b2ff7bb44c9bc8c4f8ab",
          "sha256": "0a720d1d9e21e0e1430f8c329d88876714f1cb2b72641d6d45e21ee3e8a259b7",
          "sha1": "6ef976ca15d887ac26099f0a5adac08c914a6443",
          "md5": "a815ac17e72c1a64056dd14e3981d3da"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "96c31cdce371295a861a2600eabc6cbe2a7e173173c383a1c0fb0de93f217fd92aaa20779c5abd1eecc050ec9855499f137e04f0f578c4e383f0307cf704c111",
          "sha256": "2c9d6e2ae44b1cf49798fd57a2304e86f5e7b121b53eb493e598edf1955885ad",
          "sha1": "281d6373868eb2229261e384f81d262e50781c96",
          "md5": "3f53fa09a37b6605c1b47022fe3ad83b"
        }
      ]
    }
  ]
}
