{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105931,
          "sha512": "600898463dad44f638d235c4e6b2258dafa25380b1d084ba7f35eb6d3feaf7321ed249b5f0c0f91094f614adc658ae07999389ab94fbd7a4332563cf34fb554a",
          "sha256": "e97db53c38bed7544ab7dd97af682f6cd868c224bbd178bcfca62a049c8ca72a",
          "sha1": "4e0f0825f4657f1063668f60c4b9b34d75573d87",
          "md5": "974957318c35e7ec8399d8ab3331bb50"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-tvossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7ead27d71648d85a28b87c8af7fcca1a90332a3e71ff6d3eb5c98d20c118df53c90fdf23f29ce94d7f561b44c4aa9610c16e58c473d6314b64d7029f017810bd",
          "sha256": "0c2ba2a1eea6c0379e6c293262ac48275618ebf3f4a5b1b90e539b311512cdf0",
          "sha1": "76d2ea3ecf81c8ec014b5aabf0c4195c894b79a2",
          "md5": "33ac3b5a1bbdcbfc44dece6b0411146f"
        }
      ]
    }
  ]
}
