{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-fix-name-resolving-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT.jar",
          "size": 34741,
          "sha512": "5b41790fe049172beabead85f702601e3197146cc9f6637e1ec7122e1e9543722e4de464ade22eff4f8b981487de18d6909f6bd76f1b0fca914029a93b2c2e06",
          "sha256": "b010bd219516cb7aa129ff3801497ccb38859ae45e62544538e643f4e12e6e5a",
          "sha1": "d3517e95eee368a89f9c1ed097343d731926e318",
          "md5": "0b7f1302cfc0fdd953cc0b2aef1ca70d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT.jar",
          "size": 34741,
          "sha512": "5b41790fe049172beabead85f702601e3197146cc9f6637e1ec7122e1e9543722e4de464ade22eff4f8b981487de18d6909f6bd76f1b0fca914029a93b2c2e06",
          "sha256": "b010bd219516cb7aa129ff3801497ccb38859ae45e62544538e643f4e12e6e5a",
          "sha1": "d3517e95eee368a89f9c1ed097343d731926e318",
          "md5": "0b7f1302cfc0fdd953cc0b2aef1ca70d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1e8e5bd9bd7cf9169b9eca86a24ccb6b1568d94215b73c11232d8331915d46b194762e6cb7f7eb78df6b447f65eac9d4e6612032a17a9d661465b412f63785e5",
          "sha256": "cea959e934d2462f33d9a401d692708892567bb0c6939a1b7dd3a4195b0b368d",
          "sha1": "ec5501347f73bd66b948e91995a2e6124920998d",
          "md5": "c2f5e8e5666f8cf1117662fb29e99f30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-fix-name-resolving-SNAPSHOT-sources.jar",
          "size": 9402,
          "sha512": "cfe2afc2f8fe473066f028ae69130250721173b2a0f0124085a0a4eaf7e962223be54f81bd7280d16d8a6185e7352352ab5dfc0c3d9ea3092a3b298f4bffac80",
          "sha256": "1cd6927fb6276083c75715accfa335885ca7e79bdfda1f6a3cc59eec4f0de042",
          "sha1": "2127c0c256db4a56f68ce9305407e10bab36e3e4",
          "md5": "0d9beb653cec7a90e06a521d8fcb44b4"
        }
      ]
    }
  ]
}
