{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "c8719de-fix-detekt-distribution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-publishing-c8719de-fix-detekt-distribution.jar",
          "size": 130775,
          "sha512": "6649bc897b3e4c522cfd1fa581780837e11bf43725661c1c19576c7acd37d50df37207360a52a3788e1e5f0d63a0335adbc9bad8cd7de44e5cc02af974e6c6c5",
          "sha256": "80bddf70b056d6d091562e0e8f9dca8aa833eb14e23849a2d20c2df72c2dfc32",
          "sha1": "58f52a901dea3ea1436699c69a13598be5d65cb4",
          "md5": "bf31bf80b3badc67b5d68158b7d186b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-publishing-c8719de-fix-detekt-distribution.jar",
          "size": 130775,
          "sha512": "6649bc897b3e4c522cfd1fa581780837e11bf43725661c1c19576c7acd37d50df37207360a52a3788e1e5f0d63a0335adbc9bad8cd7de44e5cc02af974e6c6c5",
          "sha256": "80bddf70b056d6d091562e0e8f9dca8aa833eb14e23849a2d20c2df72c2dfc32",
          "sha1": "58f52a901dea3ea1436699c69a13598be5d65cb4",
          "md5": "bf31bf80b3badc67b5d68158b7d186b5"
        }
      ]
    }
  ]
}
