{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-setup-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-setup-SNAPSHOT.jar",
          "size": 173203,
          "sha512": "f6679e3258e04b9cb882f39f013234773fb9b9688114694d78c152c71313fb1f7756738f3e59f46c1058df126778410e7b4dadaac74ef667aaf68cd667a86257",
          "sha256": "0bcaad51ae431c70dae0b316b2936dfb82c82faf760563eb3ef283075a4bb2d7",
          "sha1": "3eacbf89cc6c10e1b4cc6971c9b051f68fd62487",
          "md5": "869b754faf3e9d6cc6379b6d3802dda0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-change-setup-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-setup-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-setup-SNAPSHOT.jar",
          "size": 173203,
          "sha512": "f6679e3258e04b9cb882f39f013234773fb9b9688114694d78c152c71313fb1f7756738f3e59f46c1058df126778410e7b4dadaac74ef667aaf68cd667a86257",
          "sha256": "0bcaad51ae431c70dae0b316b2936dfb82c82faf760563eb3ef283075a4bb2d7",
          "sha1": "3eacbf89cc6c10e1b4cc6971c9b051f68fd62487",
          "md5": "869b754faf3e9d6cc6379b6d3802dda0"
        }
      ]
    }
  ]
}
