{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-db53051-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.jar",
          "size": 5533,
          "sha512": "d8862ea3570dc348389121f2fd3d8832faa5b89f44705094c67f2bd06a2514d4ce75823ff39314ff323b4c83e0b59cf141591e6369f77c757dbfac624b8395a5",
          "sha256": "fb9df3231abd5a5c2be9cb81e27b6099ca461125a7f235844b3e9b296a0b5a95",
          "sha1": "5af9bf9de324a824ac83da0602232248ba59e7ed",
          "md5": "fd4b1aecbdc8965c174645ffaf8b4bf7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.jar",
          "size": 5533,
          "sha512": "d8862ea3570dc348389121f2fd3d8832faa5b89f44705094c67f2bd06a2514d4ce75823ff39314ff323b4c83e0b59cf141591e6369f77c757dbfac624b8395a5",
          "sha256": "fb9df3231abd5a5c2be9cb81e27b6099ca461125a7f235844b3e9b296a0b5a95",
          "sha1": "5af9bf9de324a824ac83da0602232248ba59e7ed",
          "md5": "fd4b1aecbdc8965c174645ffaf8b4bf7"
        }
      ]
    }
  ]
}
