{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/ee9aeba-add-recursive-selector-SNAPSHOT/kmock-ee9aeba-add-recursive-selector-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "ee9aeba-add-recursive-selector-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-ee9aeba-add-recursive-selector-SNAPSHOT.jar",
          "url": "kmock-jvm-ee9aeba-add-recursive-selector-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "efb47141427cb6f1581e1065ac1bd4a932cfc124acdcbddf5e8c199520b237fa9570f8dea0ebc1468eb0712161d861eed7d6197d68cbda1434e6eb405200e585",
          "sha256": "f426059c19dce6c83f227b2b1cda0a5a6a2ca49c6e422873e638708eb5a13fd4",
          "sha1": "680a1e2bf667a0e2ab5c9eb517f405691d160769",
          "md5": "a24be50f5da1c105eae124b68948335b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-ee9aeba-add-recursive-selector-SNAPSHOT.jar",
          "url": "kmock-jvm-ee9aeba-add-recursive-selector-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "efb47141427cb6f1581e1065ac1bd4a932cfc124acdcbddf5e8c199520b237fa9570f8dea0ebc1468eb0712161d861eed7d6197d68cbda1434e6eb405200e585",
          "sha256": "f426059c19dce6c83f227b2b1cda0a5a6a2ca49c6e422873e638708eb5a13fd4",
          "sha1": "680a1e2bf667a0e2ab5c9eb517f405691d160769",
          "md5": "a24be50f5da1c105eae124b68948335b"
        }
      ]
    }
  ]
}
