{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "157e6a8-remove-dep-prop-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-157e6a8-remove-dep-prop-SNAPSHOT.jar",
          "size": 26844,
          "sha512": "f261f8a863bbf797235e7e034b78775a3047709f55453d86205de487441507d67a9af428be3f6b5d6c86a7c40772b6f367f3bfa31189767f46691d140220ae3f",
          "sha256": "e71dad51d90c886bade0c2b0ac584fa1359122f077f8b0d905e8c547a429c411",
          "sha1": "4eb1d81d8323ee99f1fa6e51cbcf10d3931c114a",
          "md5": "722fd16ed4d127926dac0911ae979066"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/157e6a8-remove-dep-prop-SNAPSHOT/banana-i18n-android-157e6a8-remove-dep-prop-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "157e6a8-remove-dep-prop-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/157e6a8-remove-dep-prop-SNAPSHOT/banana-i18n-android-157e6a8-remove-dep-prop-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "157e6a8-remove-dep-prop-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/157e6a8-remove-dep-prop-SNAPSHOT/banana-i18n-jvm-157e6a8-remove-dep-prop-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "157e6a8-remove-dep-prop-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/157e6a8-remove-dep-prop-SNAPSHOT/banana-i18n-jvm-157e6a8-remove-dep-prop-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "157e6a8-remove-dep-prop-SNAPSHOT"
      }
    }
  ]
}
