{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-add-more-sources-SNAPSHOT/ktx-datetime-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvosx64-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 34642,
          "sha512": "51e09da36450b897a2f3dfa890d15b0d7e2bd971d766e6aff2190d6046afbd5f1d9cdc716183387596fad35d2491ccf20f6dae05b2b2420619c149ef8c8edc8b",
          "sha256": "d5a583bbfce7380171ed17526ac30a7166e414fa950dd55928d92145307b8a98",
          "sha1": "413606f9011eb54e769775fdf2320b175736b384",
          "md5": "a176e4fb1a55efb50eb3697d5867f769"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2a7203b7f2cff78ce9669bb4dd9ddd2cca0f93cfb19797e72163cdef0f92c1632b129efab82121afd3826365530242f746e18832268f061d4277a0bb414adf77",
          "sha256": "84c12f7ee26ef355b2873c04455d03b53c86a16d74dbbe756f692f9847b6d04e",
          "sha1": "25b332ea17052ad3da8eb9834f3457140fb7c458",
          "md5": "4034618779bfb105370c8e627cbab808"
        }
      ]
    }
  ]
}
