{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-changelog-SNAPSHOT/core-0.4.0-change-changelog-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-changelog-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.4.0-change-changelog-SNAPSHOT.klib",
          "size": 105817,
          "sha512": "648ebbbc95f90e17229fb0497b919f66b2007adb0eac8f43b251990be669e50e1e5394ca8cc403152eeb4fc6fcfa621dfc4ef5485dfa849b8583b2d32d3353f1",
          "sha256": "0ecea98229a391a98340dfaa8e7bf59e2a1400413bc630864ea82c30c79242ce",
          "sha1": "f44f2724006be0709bd6af40c0241f689785d315",
          "md5": "9f664b2f86cef0e5808460010cf9a48a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.4.0-change-changelog-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.4.0-change-changelog-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "374fb1abf5310ae1ca9443bdf8942984911b22eaf577748b04b88bf87b486e9fba17a3c87ba0449a40749f6a3ea5cada3165aaaf62921748de9d0e706d6d519c",
          "sha256": "2367bb96f5e9268c1163f82b3d63cfb9ed7a8672827782d35e29e10308b1c882",
          "sha1": "7dfb11bdce56cc39b98a25729567fb0371bd813a",
          "md5": "a6a078c845fb78b135e91b9cde8787d4"
        }
      ]
    }
  ]
}
