{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit5-df500e4-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-df500e4-change-docs-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-df500e4-change-docs-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "f6363196e3dce6d401b4d62a57388918d1e9cde2a3a33c5ae650fbccf9291270c5844ec0677be3ad2172c8af8553ad7d73813fb84f9f89ba8d140cc53b50c399",
          "sha256": "6634b09a1e9adaed5601101d25c528b8773c74134e7acebea062816e93beb816",
          "sha1": "170eaa6f56d6c09fe7ce3e49ffac97f7cc7d20b8",
          "md5": "f0769371bcd0224ad9c89a09fcc5fd39"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-df500e4-change-docs-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-df500e4-change-docs-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "f6363196e3dce6d401b4d62a57388918d1e9cde2a3a33c5ae650fbccf9291270c5844ec0677be3ad2172c8af8553ad7d73813fb84f9f89ba8d140cc53b50c399",
          "sha256": "6634b09a1e9adaed5601101d25c528b8773c74134e7acebea062816e93beb816",
          "sha1": "170eaa6f56d6c09fe7ce3e49ffac97f7cc7d20b8",
          "md5": "f0769371bcd0224ad9c89a09fcc5fd39"
        }
      ]
    }
  ]
}
