{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "1b7d88a-change-dependency-helper",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-1b7d88a-change-dependency-helper.jar",
          "url": "antibytes-dependency-node-1b7d88a-change-dependency-helper.jar",
          "size": 20143,
          "sha512": "b5acd211d2b9bbf1da17d79668680e838f6c526c0183fbedd4f04a30cf86de29d9d8c57114e844c58d4f849cf552e92c1d0f607c867573988ea4503b51967c74",
          "sha256": "c4fe6b07a8ec11cde5b3b01ef7ee2cd4cfe15005e7d33828776b10211f3b2e40",
          "sha1": "e1665d63249746854de0895a6db2d1634fda1df6",
          "md5": "9882d1795ac8259192f12b2b8546a6b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-1b7d88a-change-dependency-helper.jar",
          "url": "antibytes-dependency-node-1b7d88a-change-dependency-helper.jar",
          "size": 20143,
          "sha512": "b5acd211d2b9bbf1da17d79668680e838f6c526c0183fbedd4f04a30cf86de29d9d8c57114e844c58d4f849cf552e92c1d0f607c867573988ea4503b51967c74",
          "sha256": "c4fe6b07a8ec11cde5b3b01ef7ee2cd4cfe15005e7d33828776b10211f3b2e40",
          "sha1": "e1665d63249746854de0895a6db2d1634fda1df6",
          "md5": "9882d1795ac8259192f12b2b8546a6b3"
        }
      ]
    }
  ]
}
