{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "d37c383-change-write-preference-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-d37c383-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-d37c383-change-write-preference-SNAPSHOT.jar",
          "size": 105446,
          "sha512": "72d4537d663480e70efe1095e6401d85b752e7023cda47aa0ecb4fa0eeab5823a1661ab31632417358c7c175b379652c720e295d17e313ea7c49930ce20a5d54",
          "sha256": "077fb21aac7893434ae842ac5042c669c05808b17788cd5f0b55714acfa89ca4",
          "sha1": "d5b4d520cd18100a8a245cbfabd1005525e24229",
          "md5": "3c2f3f7b42812376fa40d87037f49590"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "d37c383-change-write-preference-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-d37c383-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-d37c383-change-write-preference-SNAPSHOT.jar",
          "size": 105446,
          "sha512": "72d4537d663480e70efe1095e6401d85b752e7023cda47aa0ecb4fa0eeab5823a1661ab31632417358c7c175b379652c720e295d17e313ea7c49930ce20a5d54",
          "sha256": "077fb21aac7893434ae842ac5042c669c05808b17788cd5f0b55714acfa89ca4",
          "sha1": "d5b4d520cd18100a8a245cbfabd1005525e24229",
          "md5": "3c2f3f7b42812376fa40d87037f49590"
        }
      ]
    }
  ]
}
