{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "87d1edc-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-87d1edc-bump-updates-SNAPSHOT.jar",
          "size": 26844,
          "sha512": "65aa924501a0699bc86d0467e8a07de4ab8bcccac1ca32e2d4be88c2520b1b6162834f2d8c53070a71c9537332bc0c45619a292380246a46de7ef2ed9524e486",
          "sha256": "7bf303cbe201073fb9ec38035d762e3f0b43143944a90f2530f85d16f1639d28",
          "sha1": "e3765bbe1f0e30673cc3a2c419c442807c3f49e2",
          "md5": "96fc32e7e84032d5c693a5add933ed18"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/87d1edc-bump-updates-SNAPSHOT/banana-i18n-android-87d1edc-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "87d1edc-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/87d1edc-bump-updates-SNAPSHOT/banana-i18n-android-87d1edc-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "87d1edc-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/87d1edc-bump-updates-SNAPSHOT/banana-i18n-jvm-87d1edc-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "87d1edc-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/87d1edc-bump-updates-SNAPSHOT/banana-i18n-jvm-87d1edc-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "87d1edc-bump-updates-SNAPSHOT"
      }
    }
  ]
}
