{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "size": 67326,
          "sha512": "0f69dffc29d3fe284d7f0e5fe92c53238fff91122b41275ca13bcd0c5a8b44849fc90f98da34ba4f89fc0f1e3766f11d4af0c93da2d00d71555b419691b10a1b",
          "sha256": "e72f6af13d1de1a51dab36bcc772f18e0162f1296f687e2aaeca8f848d8442b9",
          "sha1": "241d7297627037372a36f6d149516d6370c09998",
          "md5": "1a478e9335b4ff97697f8bd0e1168106"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT.jar",
          "size": 67326,
          "sha512": "0f69dffc29d3fe284d7f0e5fe92c53238fff91122b41275ca13bcd0c5a8b44849fc90f98da34ba4f89fc0f1e3766f11d4af0c93da2d00d71555b419691b10a1b",
          "sha256": "e72f6af13d1de1a51dab36bcc772f18e0162f1296f687e2aaeca8f848d8442b9",
          "sha1": "241d7297627037372a36f6d149516d6370c09998",
          "md5": "1a478e9335b4ff97697f8bd0e1168106"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "f61fb079d10e42fc8bad15e0f2deb5f41d7f0cb70e0dc8897a4ebb0b333bbd1b3ad8e91904431509cf5cd907473b9c7017492ab59a4605b1c8eb3cb72dc17ef1",
          "sha256": "1ef8bb21f66c8bd2437a8fb543209e0c93ee197e9c09be6d6bf821b33afdf2e1",
          "sha1": "4eefb5af0561c1b92253059e064107d87faa429f",
          "md5": "7efe137bb3a7645c36cc1e70dd908f8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc01-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc01-SNAPSHOT-sources.jar",
          "size": 13671,
          "sha512": "8c0ad3d4f7e259c547f360a556d507e5ee69bc01dc3bef69f5f7052139528eac101fb0e59b0c6671632cb8647231340ff661382f7c5998bbf767f7d22ada8434",
          "sha256": "2ed7d1ccebc05de6f985d7d8f2d479ea74b47ecf8cdadf8d0596cd7bcdb1d4fd",
          "sha1": "2352e7e121576c375b29fbcffde2da001c5aac22",
          "md5": "9113f1207a4f2a92fb195ef21b4f3808"
        }
      ]
    }
  ]
}
