{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "e3fda8a-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-e3fda8a-change-plugins.jar",
          "url": "antibytes-versioning-e3fda8a-change-plugins.jar",
          "size": 21893,
          "sha512": "89684456c28da73c778bd8696d94f332b00ad2a5cda59ba6fabfe07de83e92be7f9f0bc6fbb849925c752d9c887200d0d0201977173d2c3b13a7514914c26d47",
          "sha256": "85da1fa8363b762094af8abfc3512f1fa367f2bedc7069e07e94dcebbd7e020f",
          "sha1": "39a4fd752c2752ad60b2a2fdc2bbb8a878116421",
          "md5": "afc76a6a0ded4b138861e3869747606d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-e3fda8a-change-plugins.jar",
          "url": "antibytes-versioning-e3fda8a-change-plugins.jar",
          "size": 21893,
          "sha512": "89684456c28da73c778bd8696d94f332b00ad2a5cda59ba6fabfe07de83e92be7f9f0bc6fbb849925c752d9c887200d0d0201977173d2c3b13a7514914c26d47",
          "sha256": "85da1fa8363b762094af8abfc3512f1fa367f2bedc7069e07e94dcebbd7e020f",
          "sha1": "39a4fd752c2752ad60b2a2fdc2bbb8a878116421",
          "md5": "afc76a6a0ded4b138861e3869747606d"
        }
      ]
    }
  ]
}
