{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/b05828c-add-ios-SNAPSHOT/test-utils-annotations-b05828c-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "b05828c-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-b05828c-add-ios-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ebedf388787be3759f37d9f2a9fe4543d1a347fe63bceee38406230a72f29f30112f5fb2de15f7a5b754b10699602df73d5e16e182e658e3d69cb45384d1bae6",
          "sha256": "0e781da42ec3acd19d4ed3915f3524f9fa3c86c59a146e40d85d9fe20caa8004",
          "sha1": "60e33bd309aa32d417a672e06ae832cab15341f7",
          "md5": "a662f9c2d2fa0dbba8331f838a693a18"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-b05828c-add-ios-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ebedf388787be3759f37d9f2a9fe4543d1a347fe63bceee38406230a72f29f30112f5fb2de15f7a5b754b10699602df73d5e16e182e658e3d69cb45384d1bae6",
          "sha256": "0e781da42ec3acd19d4ed3915f3524f9fa3c86c59a146e40d85d9fe20caa8004",
          "sha1": "60e33bd309aa32d417a672e06ae832cab15341f7",
          "md5": "a662f9c2d2fa0dbba8331f838a693a18"
        }
      ]
    }
  ]
}
