{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/e65a2ff-bump-updates-SNAPSHOT/test-utils-annotations-e65a2ff-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "e65a2ff-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-e65a2ff-bump-updates-SNAPSHOT.klib",
          "size": 11334,
          "sha512": "6af6cbd9eff8184c553b5cec5f703b6616fb50a5a30ed48fe004e17491b3fd6de014821615af26a44897bfcca46085629a3e4d65b3e3d57f62f2041aa6803830",
          "sha256": "2fe3461e8b110c9fbc4f0af49ff00046b9e2b94b085f8d68461a2cdf5c53cb49",
          "sha1": "7fb6dc5db6305619a7fe527055e8cbab8b5103b2",
          "md5": "4e432e4026f3051b27c0faa0f057466c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosarm64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6f17515588c034877bf5f5e92fca93921f1126de4b628394d09f06771630be4756d6e849883654dcf0745cc24722a18c12c6a2dd6a46c2706460f1b03b88b39f",
          "sha256": "30beedab27097e1206221b13180fc4182c4a71c67de28c8c43306740136ead0a",
          "sha1": "9bb412e291d02ad1cf499f186948667767f3027f",
          "md5": "24029cd4c552b8dd66b90a9aa7c09163"
        }
      ]
    }
  ]
}
