{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "1d2e1cf-add-additional-source-configs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-gradle-test-utils-1d2e1cf-add-additional-source-configs.jar",
          "size": 17255,
          "sha512": "6d8fdf3acf0ccf25bb2f33d00e2a34dcb8b713e6b5339a327a3e5f422e9f08d58261f3aa9ca53fca3c82c22fa00a9d7411bf5644ff2742647f441836f8fff648",
          "sha256": "ca037029c5c1466b113b868c67a50cb1f0c33f42865cabbd2a6bfc183442be46",
          "sha1": "047021006b24bb3b2c6bec0626f5e210c8aca053",
          "md5": "086e84f4c995a92e99ac1eab8cb40db6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-gradle-test-utils-1d2e1cf-add-additional-source-configs.jar",
          "size": 17255,
          "sha512": "6d8fdf3acf0ccf25bb2f33d00e2a34dcb8b713e6b5339a327a3e5f422e9f08d58261f3aa9ca53fca3c82c22fa00a9d7411bf5644ff2742647f441836f8fff648",
          "sha256": "ca037029c5c1466b113b868c67a50cb1f0c33f42865cabbd2a6bfc183442be46",
          "sha1": "047021006b24bb3b2c6bec0626f5e210c8aca053",
          "md5": "086e84f4c995a92e99ac1eab8cb40db6"
        }
      ]
    }
  ]
}
