{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-filter-array-signed-SNAPSHOT/core-0.2.0-add-filter-array-signed-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-filter-array-signed-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-add-filter-array-signed-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-add-filter-array-signed-SNAPSHOT.jar",
          "size": 201988,
          "sha512": "94af87bfc332cddaa2784c9b76ac1a1104a83b4499c9acf5cf3443e75dfa94f9e033320fce274d07957ca394fcf1d903fdb9136cf37dba2743db3d6403cbf2b8",
          "sha256": "201483c2290707cdbad5283ec6e8712a14f61aab843421894a3a7eef0a164c1a",
          "sha1": "acaf5947279c3ff4ea8ff2b12efe1c2b879c85ce",
          "md5": "42753e99d786369aa3193d975b1758d4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-add-filter-array-signed-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-add-filter-array-signed-SNAPSHOT.jar",
          "size": 201988,
          "sha512": "94af87bfc332cddaa2784c9b76ac1a1104a83b4499c9acf5cf3443e75dfa94f9e033320fce274d07957ca394fcf1d903fdb9136cf37dba2743db3d6403cbf2b8",
          "sha256": "201483c2290707cdbad5283ec6e8712a14f61aab843421894a3a7eef0a164c1a",
          "sha1": "acaf5947279c3ff4ea8ff2b12efe1c2b879c85ce",
          "md5": "42753e99d786369aa3193d975b1758d4"
        }
      ]
    }
  ]
}
