{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/aba8f9f/core-aba8f9f.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "aba8f9f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-aba8f9f.klib",
          "url": "core-js-aba8f9f.klib",
          "size": 61528,
          "sha512": "942e47cfa6ae3c46f6f38b616ade734dfb12444a5ef8c06410e3ce0910f58d5780c1723ca5bda1a37210deace5e5d0dbb3b822bd44c20271ffdb61b379f9cc13",
          "sha256": "5ebb0c63a8921ac6650674d07366db6306c3bb6ae3f6f7f3309f25ebaa6ef3ab",
          "sha1": "52fad7f3c358cd9a52627125af2c14c1c6a67e0c",
          "md5": "47c0f10e9e4e9490be0eec30bb6469d7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-aba8f9f.klib",
          "url": "core-js-aba8f9f.klib",
          "size": 61528,
          "sha512": "942e47cfa6ae3c46f6f38b616ade734dfb12444a5ef8c06410e3ce0910f58d5780c1723ca5bda1a37210deace5e5d0dbb3b822bd44c20271ffdb61b379f9cc13",
          "sha256": "5ebb0c63a8921ac6650674d07366db6306c3bb6ae3f6f7f3309f25ebaa6ef3ab",
          "sha1": "52fad7f3c358cd9a52627125af2c14c1c6a67e0c",
          "md5": "47c0f10e9e4e9490be0eec30bb6469d7"
        }
      ]
    }
  ]
}
