{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-helper",
    "version": "2c2de1a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-2c2de1a.jar",
          "url": "antibytes-dependency-helper-2c2de1a.jar",
          "size": 44913,
          "sha512": "4be2768285f18e4af586a3ea0f6bdeed5235272ab1601dacdd471479d4243d424859eec2c00541271c4240f9f6afa1649290def1308ab0c149537419db9de97d",
          "sha256": "89dad156bab717847ca71c3b4b44c805efe2f170086f5abee2dd2f9a73b81838",
          "sha1": "d8d225fe79139a2b6740f767a7dd56c18e3586ed",
          "md5": "3ba0992988b8cc6f039a924d624de71d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2c2de1a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-2c2de1a.jar",
          "url": "antibytes-dependency-helper-2c2de1a.jar",
          "size": 44913,
          "sha512": "4be2768285f18e4af586a3ea0f6bdeed5235272ab1601dacdd471479d4243d424859eec2c00541271c4240f9f6afa1649290def1308ab0c149537419db9de97d",
          "sha256": "89dad156bab717847ca71c3b4b44c805efe2f170086f5abee2dd2f9a73b81838",
          "sha1": "d8d225fe79139a2b6740f767a7dd56c18e3586ed",
          "md5": "3ba0992988b8cc6f039a924d624de71d"
        }
      ]
    }
  ]
}
