{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/3f8f5c0-bump-updates-SNAPSHOT/test-utils-3f8f5c0-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "3f8f5c0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-3f8f5c0-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-jvm-3f8f5c0-bump-updates-SNAPSHOT.jar",
          "size": 8846,
          "sha512": "12d5d45bc763843979578bdaae031d703e7da70ef0a538864d7cf2105e8ae845046281b417da221acdbfa437c2d4961e450791a0b867aa48b08192c90769b639",
          "sha256": "20ca7b1413bc06b75786e069324c5211f039c4c692db8679b3a4873366d99ecf",
          "sha1": "4104223f8d56fc4e42ec5a2633c0ec37663f5905",
          "md5": "cb225c8fc4a1fc27e4e602cd19681862"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-3f8f5c0-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-jvm-3f8f5c0-bump-updates-SNAPSHOT.jar",
          "size": 8846,
          "sha512": "12d5d45bc763843979578bdaae031d703e7da70ef0a538864d7cf2105e8ae845046281b417da221acdbfa437c2d4961e450791a0b867aa48b08192c90769b639",
          "sha256": "20ca7b1413bc06b75786e069324c5211f039c4c692db8679b3a4873366d99ecf",
          "sha1": "4104223f8d56fc4e42ec5a2633c0ec37663f5905",
          "md5": "cb225c8fc4a1fc27e4e602cd19681862"
        }
      ]
    }
  ]
}
