{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-change-refinded-names-SNAPSHOT/kmock-0.2.0-rc01-change-refinded-names-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-change-refinded-names-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-rc01-change-refinded-names-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-rc01-change-refinded-names-SNAPSHOT.klib",
          "size": 209685,
          "sha512": "a3082840690b4acb54a58127126032fc92f574e7a4c9059f648abffe6b94a8aefc7630bb1c6df988a5c7f741d965a45d4c63f0573923af93d566ce48d5d75291",
          "sha256": "fcdac5ad7987b6e38e65394577ffb816907dffa53f08122c7ef817c0083b4899",
          "sha1": "71ba467a25e27fc79e719df8fba6d71fb756607d",
          "md5": "653293fc574c200f0ca88ad89a276351"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-rc01-change-refinded-names-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-rc01-change-refinded-names-SNAPSHOT.klib",
          "size": 209685,
          "sha512": "a3082840690b4acb54a58127126032fc92f574e7a4c9059f648abffe6b94a8aefc7630bb1c6df988a5c7f741d965a45d4c63f0573923af93d566ce48d5d75291",
          "sha256": "fcdac5ad7987b6e38e65394577ffb816907dffa53f08122c7ef817c0083b4899",
          "sha1": "71ba467a25e27fc79e719df8fba6d71fb756607d",
          "md5": "653293fc574c200f0ca88ad89a276351"
        }
      ]
    }
  ]
}
