{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/ad479d6-change-workflows-SNAPSHOT/test-utils-annotations-junit4-ad479d6-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "ad479d6-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosx64-ad479d6-change-workflows-SNAPSHOT.klib",
          "size": 11335,
          "sha512": "a2b53caf68a6238f48cb4582555a79eb50d91dc842aa7c144782c1901b31ce7f9bf0d6b81e791a8ff23dd068e3bf2897198e58f008a6bb58779d8995c89dc042",
          "sha256": "0c0bd6ef30e191d9933583a320776bb991623922170cba30ae14477f3e3c90d7",
          "sha1": "c9d01ac9add1320a06ea845bb74746a10fbf870b",
          "md5": "123085bdd3e3489ec2d5e3886fd3710f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosx64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosx64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f915de2eff46c039eba2aa8e7d5d06b931b1bdae6dd508c4fdc8e324bd0b42fe9cf2f5d27e19692b4b0b713a55d12d7eaa4878735d0f627c1db7fd4ea981f757",
          "sha256": "424de17dd8602702c50a4b067ddc422a5cfee003deac4b3ac258e59ea282fd54",
          "sha1": "2f95a396f330c7c1b6d417118fb02c3bbc1fb3e0",
          "md5": "6845a370e7855d64add4b7fd224d75c1"
        }
      ]
    }
  ]
}
