{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "1367684-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-kmp-configuration-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 67704,
          "sha512": "04ffb8a2fe0511d664420195abb566483642cd6619f207f55a01d0263ddf51d5b41a61f7ca30b02b611f0a840cd99f6ce891777960833945f734094ce452a1d8",
          "sha256": "a2d9abf4bf6bc218c26016b6d23725136b4ea9efca7dd3e78cfd148304601764",
          "sha1": "954c0d224e9f36c34eba72fe0a1bcfd5789cb9b3",
          "md5": "b8dfaa724be5d48046e003c3e6c1543e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1367684-add-android-fixture-kmp-sourceset-hook"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-kmp-configuration-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 67704,
          "sha512": "04ffb8a2fe0511d664420195abb566483642cd6619f207f55a01d0263ddf51d5b41a61f7ca30b02b611f0a840cd99f6ce891777960833945f734094ce452a1d8",
          "sha256": "a2d9abf4bf6bc218c26016b6d23725136b4ea9efca7dd3e78cfd148304601764",
          "sha1": "954c0d224e9f36c34eba72fe0a1bcfd5789cb9b3",
          "md5": "b8dfaa724be5d48046e003c3e6c1543e"
        }
      ]
    }
  ]
}
