{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/30769ee-change-setup-SNAPSHOT/test-utils-resourceloader-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchosx64-30769ee-change-setup-SNAPSHOT.klib",
          "size": 12884,
          "sha512": "eb08421c97216bc3001047d88016427a7b72f3aab795d6d86ecac488a1b84807d65cbea24d799d34bbab640bb90d0bcfe5d94a97975c441c5050b4338e0dee79",
          "sha256": "2b8cf28b15a104e20d75835c61ef3afa67faf69653672dcc4bad9a3c5e5ba129",
          "sha1": "6710571c381409fe4c75f2d6a5ec441b90fe1038",
          "md5": "7690c6e0282386ee470026ab9bae7dc3"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchosx64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-watchosx64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7ed562ee40fb9efb27439ae26a841217e91c204455848741d968b4c6e54599953ec71c559bbd195a4e3e39e26ecb26788069f61aa5918e69df16fbd01e5ae15d",
          "sha256": "2df03d3508e01497242ad00d81d7005d608a75687e1761a6f6ac270d8c3959fc",
          "sha1": "61afc7f7cc3cf91548486f61b14e26e84959b3ec",
          "md5": "e1840300180504a96f0575ee1b561067"
        }
      ]
    }
  ]
}
