{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-relaxer-for-reciever-SNAPSHOT/kmock-0.1.1-add-relaxer-for-reciever-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-relaxer-for-reciever-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-relaxer-for-reciever-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-relaxer-for-reciever-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "dd3e2f7cb51a3e80b5efc9ec7fee84c413b6ba72fa1f893771a8e5c386f9468a845682486f027a541db48e0181b4c45dc74934c626182a504c7cdbc4c5e56977",
          "sha256": "f72e5d0c47d133f6d0ff3dbdace609812b0a4dc82a3fb2ba3c8b9457c00e1e8a",
          "sha1": "22b075e4482d988d876852e262a00d9511b43d04",
          "md5": "f7b2273ed56e4540e96b667098d5498e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-relaxer-for-reciever-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-relaxer-for-reciever-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "dd3e2f7cb51a3e80b5efc9ec7fee84c413b6ba72fa1f893771a8e5c386f9468a845682486f027a541db48e0181b4c45dc74934c626182a504c7cdbc4c5e56977",
          "sha256": "f72e5d0c47d133f6d0ff3dbdace609812b0a4dc82a3fb2ba3c8b9457c00e1e8a",
          "sha1": "22b075e4482d988d876852e262a00d9511b43d04",
          "md5": "f7b2273ed56e4540e96b667098d5498e"
        }
      ]
    }
  ]
}
