{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "8bd6452",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-8bd6452.jar",
          "url": "antibytes-runtime-configuration-8bd6452.jar",
          "size": 10350,
          "sha512": "0a2c0b5d5cb7f02fb17122ab83ba7eb49b40f886377c36ed409b7acff602413069915c785cf0daee8d5a9ca678f50f1e667c52a8b1d6ce87e333a9ea11cefbb4",
          "sha256": "1ae1228e3608b0bf2bca634aba8ffab99a2cfc58814cfa617abfba1864a49cb4",
          "sha1": "b0d92aa786822e6c4a22915262cc0d979a00390d",
          "md5": "f0af9199f878e5784c588c48e3893882"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8bd6452"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-8bd6452.jar",
          "url": "antibytes-runtime-configuration-8bd6452.jar",
          "size": 10350,
          "sha512": "0a2c0b5d5cb7f02fb17122ab83ba7eb49b40f886377c36ed409b7acff602413069915c785cf0daee8d5a9ca678f50f1e667c52a8b1d6ce87e333a9ea11cefbb4",
          "sha256": "1ae1228e3608b0bf2bca634aba8ffab99a2cfc58814cfa617abfba1864a49cb4",
          "sha1": "b0d92aa786822e6c4a22915262cc0d979a00390d",
          "md5": "f0af9199f878e5784c588c48e3893882"
        }
      ]
    }
  ]
}
