{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-SNAPSHOT/ktx-datetime-0.3.1-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "size": 39996,
          "sha512": "197a2b3261c96fee43f3b6b997050d5cffe345bcc9a736849a854e903605396c3cfef4993fc54e1da34bffa81be4878f13a29a9468f02928ec7f971c7bcadb6e",
          "sha256": "eb39cafab8225de2714ac599975f6ec6300575c47c7c0201c0367136ea61f4d6",
          "sha1": "bcdc8cf8fa3960f32bec5211731f0a6869ed6bb8",
          "md5": "4e97d041c5188d9d29279745aad3dbaf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.3.1-SNAPSHOT.klib",
          "size": 39996,
          "sha512": "197a2b3261c96fee43f3b6b997050d5cffe345bcc9a736849a854e903605396c3cfef4993fc54e1da34bffa81be4878f13a29a9468f02928ec7f971c7bcadb6e",
          "sha256": "eb39cafab8225de2714ac599975f6ec6300575c47c7c0201c0367136ea61f4d6",
          "sha1": "bcdc8cf8fa3960f32bec5211731f0a6869ed6bb8",
          "md5": "4e97d041c5188d9d29279745aad3dbaf"
        }
      ]
    }
  ]
}
