{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/e930d3d-change-project-setup-SNAPSHOT/test-utils-coroutine-e930d3d-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "e930d3d-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-e930d3d-change-project-setup-SNAPSHOT.klib",
          "size": 10215,
          "sha512": "20f8faf97ffe763f21a5727be08c7cc050477ad101cf5fcf7173e9ddbe61e09ad64024ed4ac84f526406d32dada6786171cb15ed0140b91d8c0099e9b3e42c52",
          "sha256": "b5ee960a0de26f99ed0dae68d0108fc1f8a3ffb5ce966589d0682b49fd80510d",
          "sha1": "b306a632a58df0d61fcd0d72b06743ddc98ed3f8",
          "md5": "d0c2d9c2207c602d76d9a6491b30bff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4d1f07fed73de3460cadf50e57f3a3f0b044115018a016149d806d91c99e12b4fa71ee8e1a7afb04315dd380c7575c888ab33a69b34c8a5f885ab0680c392f73",
          "sha256": "a5d89a03469919e51053e47c128ed65c6ff53130e182f71c99562bbc983f4615",
          "sha1": "7dbe675a41b9778f20f441cb673a3c661eac94ab",
          "md5": "e8428deaf051100992c3cc892f2eefa0"
        }
      ]
    }
  ]
}
