{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "bbef6e4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-bbef6e4.jar",
          "url": "antibytes-grammar-tools-bbef6e4.jar",
          "size": 39373,
          "sha512": "61aaa71e7610dda78911bc2ff3ae999ac73781acfbeb32c9573df977c4850481c16a7c6d1244ec8a085af34da98bdc4ca28bbd7e05aec0b378a96a7bc77dcadd",
          "sha256": "7637e7077741e04c91759dca1cd4189ea45e50621a920d3e4efae7cfdca284e7",
          "sha1": "1c5cedac6b6ae58d07ccc1cceca70ca6bfa3ee3b",
          "md5": "bf7a53c858848c330847cfd0e6c1e74e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-bbef6e4.jar",
          "url": "antibytes-grammar-tools-bbef6e4.jar",
          "size": 39373,
          "sha512": "61aaa71e7610dda78911bc2ff3ae999ac73781acfbeb32c9573df977c4850481c16a7c6d1244ec8a085af34da98bdc4ca28bbd7e05aec0b378a96a7bc77dcadd",
          "sha256": "7637e7077741e04c91759dca1cd4189ea45e50621a920d3e4efae7cfdca284e7",
          "sha1": "1c5cedac6b6ae58d07ccc1cceca70ca6bfa3ee3b",
          "md5": "bf7a53c858848c330847cfd0e6c1e74e"
        }
      ]
    }
  ]
}
