{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "4c324f2-change-quality-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "af2606eec195d09447bc21f60591b659989cfe21a3ce66e1ba8fe56fdd6c00211ce41ea74407de190396edd414bc70bddf855b97585ee52b42fc6fc50029283c",
          "sha256": "e0ecccdad5cae12d44ec90e6945faead048f35945eb4ad84570e4399944df80d",
          "sha1": "9ec15e60e6bb3c99781de3dc1e41c332293fd234",
          "md5": "40964a8e186c78db8d0c8c82c3b0bb45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "af2606eec195d09447bc21f60591b659989cfe21a3ce66e1ba8fe56fdd6c00211ce41ea74407de190396edd414bc70bddf855b97585ee52b42fc6fc50029283c",
          "sha256": "e0ecccdad5cae12d44ec90e6945faead048f35945eb4ad84570e4399944df80d",
          "sha1": "9ec15e60e6bb3c99781de3dc1e41c332293fd234",
          "md5": "40964a8e186c78db8d0c8c82c3b0bb45"
        }
      ]
    }
  ]
}
