{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/15fe97e-add-mockery-SNAPSHOT/kmock-15fe97e-add-mockery-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "15fe97e-add-mockery-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-15fe97e-add-mockery-SNAPSHOT.jar",
          "size": 80841,
          "sha512": "585ea4ec769816ab6558cb90380972230d0c6f47ba9fcfb0494dc8058ddb16f0a9fffebe1c78283e0e5db059be0339a9fb3bfc4aea13ef9f34355910decc78c2",
          "sha256": "7f003012049df82f181662e612597c4805470bb97cce2a1fbfdee69c6da557d4",
          "sha1": "ebf492fdf4898c3288cdbb292f8b2bba1652077a",
          "md5": "61cebc3978c5b6777469f29443f96d8b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "753d329-add-ios-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-15fe97e-add-mockery-SNAPSHOT.jar",
          "size": 80841,
          "sha512": "585ea4ec769816ab6558cb90380972230d0c6f47ba9fcfb0494dc8058ddb16f0a9fffebe1c78283e0e5db059be0339a9fb3bfc4aea13ef9f34355910decc78c2",
          "sha256": "7f003012049df82f181662e612597c4805470bb97cce2a1fbfdee69c6da557d4",
          "sha1": "ebf492fdf4898c3288cdbb292f8b2bba1652077a",
          "md5": "61cebc3978c5b6777469f29443f96d8b"
        }
      ]
    }
  ]
}
