{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/2ad6b15-bump-updates-SNAPSHOT/test-utils-coroutine-2ad6b15-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "2ad6b15-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-2ad6b15-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-2ad6b15-bump-updates-SNAPSHOT.klib",
          "size": 10178,
          "sha512": "0d8a53968af0a94c3d744a6f5fa71383e12c296460cd14ebcf334d53914100ca4278e2753399c39a43b88598231c95ef7ce880bd64d80584040903d3f98c9b8d",
          "sha256": "2245ef1754a2e358f4b716ac5b3ced50539768d21f32c5cae8fe25835ae450c7",
          "sha1": "3f688b4a1769b10d4577bdef652213b558d99c41",
          "md5": "85ce2fbb1f0dd42b39fb24a4f7395e7b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-2ad6b15-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-2ad6b15-bump-updates-SNAPSHOT.klib",
          "size": 10178,
          "sha512": "0d8a53968af0a94c3d744a6f5fa71383e12c296460cd14ebcf334d53914100ca4278e2753399c39a43b88598231c95ef7ce880bd64d80584040903d3f98c9b8d",
          "sha256": "2245ef1754a2e358f4b716ac5b3ced50539768d21f32c5cae8fe25835ae450c7",
          "sha1": "3f688b4a1769b10d4577bdef652213b558d99c41",
          "md5": "85ce2fbb1f0dd42b39fb24a4f7395e7b"
        }
      ]
    }
  ]
}
