{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "7c5b6aa-add-splash-screen",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-grammar-tools-7c5b6aa-add-splash-screen.jar",
          "size": 39394,
          "sha512": "d6cd35ca1a5a74c0abf195bdc92a16413181bf6ca9791668960ea715296089d7259f1416788619a52535971e3bfb901661834e9dadc723d909cda78b7273398b",
          "sha256": "0b08ded1e4a307ee86f8cf5673acbab42c6124daf12aa593b71203778acf2a13",
          "sha1": "3fc1a485465669fd9309450176c301958cde3b06",
          "md5": "b5720232acf37dbe5e2c3b6a47e8c22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-grammar-tools-7c5b6aa-add-splash-screen.jar",
          "size": 39394,
          "sha512": "d6cd35ca1a5a74c0abf195bdc92a16413181bf6ca9791668960ea715296089d7259f1416788619a52535971e3bfb901661834e9dadc723d909cda78b7273398b",
          "sha256": "0b08ded1e4a307ee86f8cf5673acbab42c6124daf12aa593b71203778acf2a13",
          "sha1": "3fc1a485465669fd9309450176c301958cde3b06",
          "md5": "b5720232acf37dbe5e2c3b6a47e8c22d"
        }
      ]
    }
  ]
}
