{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "77b6d1b-add-stable-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-77b6d1b-add-stable-api-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-77b6d1b-add-stable-api-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "9bb5a75ec51b353808f2c73a37b4212f2e3371f2f99224d70bb1134b53a0887e64094d3633efebfe57eb84e58297b975060d2f8a496d210f500068490b82155f",
          "sha256": "1a747723ea035af56f67eb7cdd9c358ab7f02c626ff3eb4f549f3811de8e8577",
          "sha1": "ba9bb05974fd1d9044d224b6c4af57082f179017",
          "md5": "df0c66ef3149e596407a02e0d232ec6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-77b6d1b-add-stable-api-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-77b6d1b-add-stable-api-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "9bb5a75ec51b353808f2c73a37b4212f2e3371f2f99224d70bb1134b53a0887e64094d3633efebfe57eb84e58297b975060d2f8a496d210f500068490b82155f",
          "sha256": "1a747723ea035af56f67eb7cdd9c358ab7f02c626ff3eb4f549f3811de8e8577",
          "sha1": "ba9bb05974fd1d9044d224b6c4af57082f179017",
          "md5": "df0c66ef3149e596407a02e0d232ec6e"
        }
      ]
    }
  ]
}
