{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "f3ac00b-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-f3ac00b-change-node-dependencies.jar",
          "url": "antibytes-dependency-helper-f3ac00b-change-node-dependencies.jar",
          "size": 68382,
          "sha512": "ab5f9c84c2e088e77c46c8a854239cf176037ad2593b1aab6a2213d18f1d943749876d96b032c20d610397cde7acd77fb9c044b9db597763ae0f54b8471734cc",
          "sha256": "05b39a28e038f187340efe4d1dcce94e6798594b195105662f0a8d746b7dba34",
          "sha1": "5689e975431e17053402d89f3ca93ac9c92a373d",
          "md5": "3f89834c0c3b3c82d61185523e9f4edd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f3ac00b-change-node-dependencies"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-f3ac00b-change-node-dependencies.jar",
          "url": "antibytes-dependency-helper-f3ac00b-change-node-dependencies.jar",
          "size": 68382,
          "sha512": "ab5f9c84c2e088e77c46c8a854239cf176037ad2593b1aab6a2213d18f1d943749876d96b032c20d610397cde7acd77fb9c044b9db597763ae0f54b8471734cc",
          "sha256": "05b39a28e038f187340efe4d1dcce94e6798594b195105662f0a8d746b7dba34",
          "sha1": "5689e975431e17053402d89f3ca93ac9c92a373d",
          "md5": "3f89834c0c3b3c82d61185523e9f4edd"
        }
      ]
    }
  ]
}
