{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "a45d388-change-to-selective-buildin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-a45d388-change-to-selective-buildin-SNAPSHOT.jar",
          "url": "kmock-processor-a45d388-change-to-selective-buildin-SNAPSHOT.jar",
          "size": 104826,
          "sha512": "66ed99ec73b20b074789dd7406d63407e9167b7daffe2bff19bb9d425714bcc870b473796cffffce1dd4745a710621e0869b1f211b27820f60cf9a8d71d8b9db",
          "sha256": "dacdbb3d7589c09869477797fa6364b42a386a80ce54a5abdf39a2b8b4066392",
          "sha1": "e1c901c0f797e96a2fde0bfbdce971f55167d300",
          "md5": "0427fb2173616f7d95c15748f49fafd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "a45d388-change-to-selective-buildin-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-a45d388-change-to-selective-buildin-SNAPSHOT.jar",
          "url": "kmock-processor-a45d388-change-to-selective-buildin-SNAPSHOT.jar",
          "size": 104826,
          "sha512": "66ed99ec73b20b074789dd7406d63407e9167b7daffe2bff19bb9d425714bcc870b473796cffffce1dd4745a710621e0869b1f211b27820f60cf9a8d71d8b9db",
          "sha256": "dacdbb3d7589c09869477797fa6364b42a386a80ce54a5abdf39a2b8b4066392",
          "sha1": "e1c901c0f797e96a2fde0bfbdce971f55167d300",
          "md5": "0427fb2173616f7d95c15748f49fafd2"
        }
      ]
    }
  ]
}
