{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-updates-SNAPSHOT/ktx-datetime-0.4.0-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-updates-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-macosarm64-0.4.0-bump-updates-SNAPSHOT.klib",
          "size": 37063,
          "sha512": "86d92335f51cbd569ce9ebd55c5aede9874821e0ee59dfa3a699a98e586dc07c13e8da56bddb337fcbb9dd40a7defaa2f9a1088e6b8b45513df6c5d3c61b84c9",
          "sha256": "2bf871fc01cba408156f1b3e7a0dd37a68dabe703e9f405c95a3a0d1f6832377",
          "sha1": "e020421fd76804f6959ec6fa1ca1aa0784eb8637",
          "md5": "0d2b620c3d68317bebb0b3a906090edc"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ktx-datetime-macosarm64-0.4.0-bump-updates-SNAPSHOT-sources.jar",
          "url": "ktx-datetime-macosarm64-0.4.0-bump-updates-SNAPSHOT-sources.jar",
          "size": 16088,
          "sha512": "2fd1093b4f66fb86460e0e5fc46d3c82d6d649e51f6fa67d86c49ee2405d528475c31f450f406b1a2be2e691d1f52d71036cf571bf342b1c7bbfdb18aacafc58",
          "sha256": "ddfeada0f92e68af51cd57f3ddcf63f5349e6ad12c9b5c93c0313015c5cc3e8e",
          "sha1": "e3f7b5b02498f31f31ff09a28221f9502399b3a2",
          "md5": "b2ce74b02e7d0b4b4cf6bb0c3c064bd4"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-updates-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-macosarm64-0.4.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-macosarm64-0.4.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7ace513403e9b56d5e49b6ff366433dcf469106aad3ced567695d5cf922eced7ac857d6238e0a4d3608d94f4926556d845dddf24c949e390446ca9b478ad91ff",
          "sha256": "65ecc6cbaa93720e5e272ac0b1a6d9f1d191faac049ba8aabb69b4ab4c40d622",
          "sha1": "d42018e7841f1fdd604aef8a0a5623e9616091f3",
          "md5": "ea44417d388cc310a1031d99de65ed19"
        }
      ]
    }
  ]
}
