{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc03-change-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT.jar",
          "size": 391218,
          "sha512": "e9988f9f552e9c555b5d4b27480b2bf96f0841b66d70d9fd8c1db6c18e0af6e2a093c28ace28db0945419e97b336b7e1775ab7c01a32e7cce3957ae2c93f9eba",
          "sha256": "47cb21e8db57086110b9e53bdd6d3dc87cc17cd2d2cefeb5c0f359eee5ebbf02",
          "sha1": "9a20ab94f4cabfaacf82f253f6908203950cfd28",
          "md5": "67fa87a3af944d4c17c4d862ff4dde46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc03-change-dependencies-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT.jar",
          "size": 391218,
          "sha512": "e9988f9f552e9c555b5d4b27480b2bf96f0841b66d70d9fd8c1db6c18e0af6e2a093c28ace28db0945419e97b336b7e1775ab7c01a32e7cce3957ae2c93f9eba",
          "sha256": "47cb21e8db57086110b9e53bdd6d3dc87cc17cd2d2cefeb5c0f359eee5ebbf02",
          "sha1": "9a20ab94f4cabfaacf82f253f6908203950cfd28",
          "md5": "67fa87a3af944d4c17c4d862ff4dde46"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "a688f484e610e6c543b6147b6a6540cfc4887e7775e2a87e04c696655c4ce57dd7faafbaf00c915e52863420350d40cb496bb16da93cf72df3f327859a3ec83e",
          "sha256": "a5cc61042c4bc0213118a13ae701713e0d115c5f9b0d7a45214a133aa72e7ee9",
          "sha1": "a4cfa3bc6405c977b2606669febda9858e4fa5d6",
          "md5": "7bf0131f5153fc0bfa32b5c196f6376a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc03-change-dependencies-SNAPSHOT-sources.jar",
          "size": 81704,
          "sha512": "156131960a4f01fb111d9c4f63c2eb0180759b32b24649fbf86aa5a878b725abf5c6e75235577188c3bf1ebe2fa261d9ef61dc04fdc4bd994987f3ba59c3ee16",
          "sha256": "5d9472e4eae2373562751863eb983865f06ce1490e591414bcda268e39cf3032",
          "sha1": "00d5f8e64dc49aad22afec15b09427a5b4205cfa",
          "md5": "acec3d6378c0d08a5483d93d42c75265"
        }
      ]
    }
  ]
}
