{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "122c96c-add-custom-component-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "675b52201a825ab5fed9ab4aec5e3b83cf4def77e61667922204b701d0379941d0f9bd8e80c31743fd91f5f0cfcded846187cf49b87613b51914299ffc75b7eb",
          "sha256": "d23fca6a4ac41c0c16d495b564f7a4d3d3319be9628967dc48f5161d790f08ed",
          "sha1": "a6c7126eb122b33736fea0d984304d8c96d6cf3f",
          "md5": "e73692c95c3f864a957b94b20d9ea24d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "675b52201a825ab5fed9ab4aec5e3b83cf4def77e61667922204b701d0379941d0f9bd8e80c31743fd91f5f0cfcded846187cf49b87613b51914299ffc75b7eb",
          "sha256": "d23fca6a4ac41c0c16d495b564f7a4d3d3319be9628967dc48f5161d790f08ed",
          "sha1": "a6c7126eb122b33736fea0d984304d8c96d6cf3f",
          "md5": "e73692c95c3f864a957b94b20d9ea24d"
        }
      ]
    }
  ]
}
