{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "93b8a67-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-93b8a67-change-node-dependencies.jar",
          "url": "antibytes-dependency-node-93b8a67-change-node-dependencies.jar",
          "size": 20145,
          "sha512": "742eb84bd7b56fc7c3b754a832de927c3b846ae1c2a3fb8dd26b315a0a15633f5b78d118d1db26d30c53dd28eeff2151e08d017265b4479f469a2b5e0df2b4cd",
          "sha256": "ccabaabbba94bfb2a901babfe88f3e00d3e4e94e72e0c9b2554278ebbb7907b9",
          "sha1": "95a1ffd8c3e5329ffa963efd95ce6bcd3a34da71",
          "md5": "43fd65a41ae40ee4a2810a319f86915c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-93b8a67-change-node-dependencies.jar",
          "url": "antibytes-dependency-node-93b8a67-change-node-dependencies.jar",
          "size": 20145,
          "sha512": "742eb84bd7b56fc7c3b754a832de927c3b846ae1c2a3fb8dd26b315a0a15633f5b78d118d1db26d30c53dd28eeff2151e08d017265b4479f469a2b5e0df2b4cd",
          "sha256": "ccabaabbba94bfb2a901babfe88f3e00d3e4e94e72e0c9b2554278ebbb7907b9",
          "sha1": "95a1ffd8c3e5329ffa963efd95ce6bcd3a34da71",
          "md5": "43fd65a41ae40ee4a2810a319f86915c"
        }
      ]
    }
  ]
}
