{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "54603a4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-54603a4.jar",
          "url": "antibytes-runtime-configuration-54603a4.jar",
          "size": 9073,
          "sha512": "4c2dd4ffad392512ef6c0e45989f5b0949e711807ccd8bf1fc5684386de1baaec904ff60a8364157f67e269baf080ee25dcb13fb0ff16b710b5ebed58bc815ce",
          "sha256": "50e6ddd038331a5fee3f4938b577cf824804b109f1e0b2fe9d05035b42fb3669",
          "sha1": "5aa144d890051efaa478ad1b71f7e530e9e88345",
          "md5": "cf19252afa406429eddf0902ddc99a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "54603a4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-54603a4.jar",
          "url": "antibytes-runtime-configuration-54603a4.jar",
          "size": 9073,
          "sha512": "4c2dd4ffad392512ef6c0e45989f5b0949e711807ccd8bf1fc5684386de1baaec904ff60a8364157f67e269baf080ee25dcb13fb0ff16b710b5ebed58bc815ce",
          "sha256": "50e6ddd038331a5fee3f4938b577cf824804b109f1e0b2fe9d05035b42fb3669",
          "sha1": "5aa144d890051efaa478ad1b71f7e530e9e88345",
          "md5": "cf19252afa406429eddf0902ddc99a8f"
        }
      ]
    }
  ]
}
