{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit5-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvosx64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 7043,
          "sha512": "1c63edc7beff8c107b430a09674c9a667ba69ace1a9f568f10f985c413cdc33d481632a40ef5d0e38dfcca6d01485d99d2c936d31aa1ea1f34ef178857f415a7",
          "sha256": "05b2fbc3bb6638eaacc1657ae62d6e6f3ae7b4ae7d8f82e43a96a9b063fcaa2d",
          "sha1": "a2987b06ed0706c705f5c9b381c121d7da3a580f",
          "md5": "bba78f4957c769222f4b0f86a51e602d"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-tvosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b888f9257b030397b937523f643854ec98f820c9f8afb7e8b03bf52d564494349a5d3e567781833abebb8518948e9d0329eb906acd05534f413d542d4969971f",
          "sha256": "6f4785de7793d2f0e17979460f3767804d9a8a87361ae348a0f95a546f3fb01c",
          "sha1": "49951c4ba7fa06e79c35867439c049625f933fe9",
          "md5": "5d8a14c7053b8c153a37ee2dd90cc564"
        }
      ]
    }
  ]
}
