{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-change-refinded-names-SNAPSHOT/kmock-0.2.0-rc01-change-refinded-names-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-change-refinded-names-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-change-refinded-names-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-change-refinded-names-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "fa271388512b8bfbfed61ffff26bfd9ce0e654f3ea1b2a4ed90ee22a95acc86c7f018555637ce8a1853cbf6bbcdc974c2b518cb49e2756d782f1526e42ad62e0",
          "sha256": "43e21ab276640152679a4fd75e43da9cd9b389083fbf52cfa009bb113bb25dba",
          "sha1": "cb1dd6797f6e16b575b93414dac5811c16603d6d",
          "md5": "542dad44c572875e5876bd1c165d0c32"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-change-refinded-names-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-change-refinded-names-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "fa271388512b8bfbfed61ffff26bfd9ce0e654f3ea1b2a4ed90ee22a95acc86c7f018555637ce8a1853cbf6bbcdc974c2b518cb49e2756d782f1526e42ad62e0",
          "sha256": "43e21ab276640152679a4fd75e43da9cd9b389083fbf52cfa009bb113bb25dba",
          "sha1": "cb1dd6797f6e16b575b93414dac5811c16603d6d",
          "md5": "542dad44c572875e5876bd1c165d0c32"
        }
      ]
    }
  ]
}
