{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency",
    "module": "antibytes-dependency",
    "version": "e3fda8a-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-e3fda8a-change-plugins.jar",
          "url": "antibytes-dependency-e3fda8a-change-plugins.jar",
          "size": 88198,
          "sha512": "aeeea61fd117c658ad5e7d123e35ed19bb02c381c5bcf2cb72e4e64a9efb83a517712aa02e697ffc2c9004480aa592276d70e3ef121a2594763a94f919c1128d",
          "sha256": "7b06e2097ef00d99c0361ea66a872204d1792457f196c8f9ca519eb2d2453180",
          "sha1": "87f9db1cd694b816911d015f350e8c7037bdd9fc",
          "md5": "f8606912b52d43dc1abbc495a4276be8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "e3fda8a-change-plugins"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-e3fda8a-change-plugins.jar",
          "url": "antibytes-dependency-e3fda8a-change-plugins.jar",
          "size": 88198,
          "sha512": "aeeea61fd117c658ad5e7d123e35ed19bb02c381c5bcf2cb72e4e64a9efb83a517712aa02e697ffc2c9004480aa592276d70e3ef121a2594763a94f919c1128d",
          "sha256": "7b06e2097ef00d99c0361ea66a872204d1792457f196c8f9ca519eb2d2453180",
          "sha1": "87f9db1cd694b816911d015f350e8c7037bdd9fc",
          "md5": "f8606912b52d43dc1abbc495a4276be8"
        }
      ]
    }
  ]
}
