{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-change-setup-SNAPSHOT/kmock-0.1.1-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-change-setup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-change-setup-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "8c4dcdf66fd5f27baa0b9a941d705c82dfea61809ce99502172277dee93986a4886b90482a20f3e3ffddf56e1190d179d0859d7fe1146f7c34cba1a6c75df46e",
          "sha256": "4a7e00208640ef27c2948eaa6b5af542ed2b83ae5df68285f5a757819677bea0",
          "sha1": "41b654e2ebfdc6e74c8df0de4a1b91fb097abbd0",
          "md5": "ee05c6d736528a16d6bf4181741475d4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-change-setup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-change-setup-SNAPSHOT.jar",
          "size": 295193,
          "sha512": "8c4dcdf66fd5f27baa0b9a941d705c82dfea61809ce99502172277dee93986a4886b90482a20f3e3ffddf56e1190d179d0859d7fe1146f7c34cba1a6c75df46e",
          "sha256": "4a7e00208640ef27c2948eaa6b5af542ed2b83ae5df68285f5a757819677bea0",
          "sha1": "41b654e2ebfdc6e74c8df0de4a1b91fb097abbd0",
          "md5": "ee05c6d736528a16d6bf4181741475d4"
        }
      ]
    }
  ]
}
