{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/ef3a5b1-bump-updates-SNAPSHOT/test-utils-annotations-junit5-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosx64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 7096,
          "sha512": "972d6e83aa11d40da9700f5af0093ced5502f13365da47c9c7a2d5bbcd5741b38e3e8d174b9f2726ad1a17a6bde354a33d402e16ac9ea33186644950f432183f",
          "sha256": "b8578a0ef4590d49ea01359df9ce75f05652407cb20ff9d5ecb71bf896f313ff",
          "sha1": "5c57c77b32a9bd738445e0b27d5407cbdf658e1c",
          "md5": "82bf85a61fc4d506ea9c379ef003d645"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-annotations-junit5-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e588277c94e913311a4dd187e6f37df9f7f40e631c283bcae7d7b5ee3a80c134d218b2adf88752c00b6ee5ddd362b7c967c41abad91669e4c535536a64019493",
          "sha256": "abdfb0901eed4bdb4f3251f4de511fba90e45b4300d2e4e524bcc7ddaf3127db",
          "sha1": "d872d107ceadc99a4a4ba8b0177b204b6c37abdc",
          "md5": "7786ac6eb3ed9abc81a1ac2bcfbc709e"
        }
      ]
    }
  ]
}
