{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "1d2e1cf-add-additional-source-configs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1d2e1cf-add-additional-source-configs"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-mkdocs-1d2e1cf-add-additional-source-configs.jar",
          "size": 11930,
          "sha512": "9ec903f3a9322cf1d6ecd9cfacf11df3b700544a221104287341871de5c737a05f080ae77216d7ad1be3d52eda1d71ff55af0c2023cc4327d5ebfc489ed7da73",
          "sha256": "320c7e35341c04d0877a6558376742c0398095dff32ed1228f235158105545eb",
          "sha1": "6fb4522c243897bb6f7ed9d8b91e906cbf95b8bf",
          "md5": "c025f728429d3f064da9ceb462e34bee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1d2e1cf-add-additional-source-configs"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1d2e1cf-add-additional-source-configs"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-mkdocs-1d2e1cf-add-additional-source-configs.jar",
          "size": 11930,
          "sha512": "9ec903f3a9322cf1d6ecd9cfacf11df3b700544a221104287341871de5c737a05f080ae77216d7ad1be3d52eda1d71ff55af0c2023cc4327d5ebfc489ed7da73",
          "sha256": "320c7e35341c04d0877a6558376742c0398095dff32ed1228f235158105545eb",
          "sha1": "6fb4522c243897bb6f7ed9d8b91e906cbf95b8bf",
          "md5": "c025f728429d3f064da9ceb462e34bee"
        }
      ]
    }
  ]
}
