{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "328bc65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-328bc65.jar",
          "url": "antibytes-publishing-328bc65.jar",
          "size": 100326,
          "sha512": "262a011ab27181a1edb354b7241e82f1d5709e077d101a1a622cb2a38ced1376072b18ebaa21d233fcbcc63493a623018d8ca866216439a2823279d11cd5c489",
          "sha256": "fd7940b1ab1200bdc94c814a5b6ab5bec6637eff095574139246db5e84196496",
          "sha1": "5b3736da94474204f3ae1a094945c60e762cc155",
          "md5": "feffe81d40a85522174fff974d6a50ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-328bc65.jar",
          "url": "antibytes-publishing-328bc65.jar",
          "size": 100326,
          "sha512": "262a011ab27181a1edb354b7241e82f1d5709e077d101a1a622cb2a38ced1376072b18ebaa21d233fcbcc63493a623018d8ca866216439a2823279d11cd5c489",
          "sha256": "fd7940b1ab1200bdc94c814a5b6ab5bec6637eff095574139246db5e84196496",
          "sha1": "5b3736da94474204f3ae1a094945c60e762cc155",
          "md5": "feffe81d40a85522174fff974d6a50ca"
        }
      ]
    }
  ]
}
