{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-filter-array-SNAPSHOT/core-0.2.0-add-filter-array-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-filter-array-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.2.0-add-filter-array-SNAPSHOT.klib",
          "size": 81791,
          "sha512": "7490b1b8c9a71f828bc6e1c857797690a84c1d1f4c5287100fcef4633cbd658b141c125f66516d5dcad1ebb556e5491d518c826e4fe848a57e099a60ae5351aa",
          "sha256": "5131fb5f5aa93f0f27371b94c3f2a322a1db81235620cadf430596f25c7d207e",
          "sha1": "dc43c1402684983598a8d3cb8c218c4e73223272",
          "md5": "15d08b9db64e23f83ab9aab1e6fd05c3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.2.0-add-filter-array-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.2.0-add-filter-array-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "98cd0d15f88dd2d461bb4d679ba500fee9507437f9141640225976bdf948f80dcc60bf4ac2b6993dff3ea5be512e9c269b69c74919b721fdaf1756419f730877",
          "sha256": "4ec9af9f7b496b7513c6364ef44e18f5610d0306fda13ae74aa045fd5f21160d",
          "sha1": "31d315dcec410d6314406af58922382b7f5243a7",
          "md5": "14b6f9277d5ba50a5327e7ea1f64a0d1"
        }
      ]
    }
  ]
}
