{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/3f83819-change-api-SNAPSHOT/kmock-3f83819-change-api-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "3f83819-change-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-linuxx64-3f83819-change-api-SNAPSHOT.klib",
          "size": 81051,
          "sha512": "1b6582c2017a2af777cce40b1c9b753d6cb34b3336a0bacbf302a5185cee2fa83058351703699341444a142c8c474f17d528c4dbb2d74a7c85c6584e1386a085",
          "sha256": "66df4fb6b122f1b99eebea997be6acb6f0fba4b65f0474f45318cf3d6e1d8a14",
          "sha1": "1e086bee3bd120e7ccd58b390e5fa76abe13584a",
          "md5": "5b3aa45886ba1a674342d257b9bd9e21"
        }
      ]
    }
  ]
}
