{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-fix-kjs-plugin-invocation-SNAPSHOT/kmock-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-fix-kjs-plugin-invocation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.klib",
          "size": 216422,
          "sha512": "f34954d03ba3674d1ffc674a011f04b88f4c079566f42c7120a735c74fd405073bc2494d062e83a8c8c94e1d12dbd806d86ea4727b0ce0fb817ce7fed5055389",
          "sha256": "49b113ff02b3f990de62dd04349b4227a1c17fe1494cf7f0aaff1ec7759f0ed8",
          "sha1": "48ad6c5c2b028b70228f2795c49c4a5913e92ad9",
          "md5": "ae671df4c6820b8b0b9b64eb537efd29"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.klib",
          "size": 216422,
          "sha512": "f34954d03ba3674d1ffc674a011f04b88f4c079566f42c7120a735c74fd405073bc2494d062e83a8c8c94e1d12dbd806d86ea4727b0ce0fb817ce7fed5055389",
          "sha256": "49b113ff02b3f990de62dd04349b4227a1c17fe1494cf7f0aaff1ec7759f0ed8",
          "sha1": "48ad6c5c2b028b70228f2795c49c4a5913e92ad9",
          "md5": "ae671df4c6820b8b0b9b64eb537efd29"
        }
      ]
    }
  ]
}
