{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-periods-SNAPSHOT/ktx-datetime-0.3.1-add-periods-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-periods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-periods-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.3.1-add-periods-SNAPSHOT.klib",
          "size": 20680,
          "sha512": "5aedf4c0f5469a9b29721c51395f2f6fa120eb93db7f38f0b65368b09c8448d976788e40f0438300d7d914746c5f4acffecbc3e5c69a1afa64411b3a17e1a859",
          "sha256": "65b3a0fb0ea78d3fea5e4bc047a1dd9b7c8acb0ebd784a07a4d1d5e4642bbcbe",
          "sha1": "ba8e9f6bcae46915ebf274523939065bfdf5c353",
          "md5": "521954ac6f9d9beb0ac65148fd184455"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-periods-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8d8906c773347d957a6159f355c8dec3f16cb2b221cfb99a134118f780add0cde41950d32dd6b06f4ef66aa42bd6d404ba3fa4cc092880171cfce7af7ef32b79",
          "sha256": "2ec59ea6ecc17a8d617437a24308bd2892e84f84da1b4b73266d0e93be0a6f61",
          "sha1": "633edd9ec04e5513db90783efb76ff5b2e9a066d",
          "md5": "bd00b0e261c9d1916d6cfae2e2ed8e36"
        }
      ]
    }
  ]
}
