{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f8d6e50-bump-workflows-SNAPSHOT/test-utils-annotations-junit4-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosarm64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 11369,
          "sha512": "f3d1d8c3c14cd00a9b40bda19ee1c4e85e2988f93842840ec6446eeb7f44f3824c33040cb12b8bf5c7f3f40fdebaf5821490793c674fa6f0d6833664954fcd09",
          "sha256": "15c7ddea1b33ff42939ea52cb5e1d2089de96f42bee1800623415a5465fd2bbc",
          "sha1": "11ce88bf7e3919d129654db6777eaf690bd4b925",
          "md5": "8d97260bca00467d74df25993a51cd67"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-macosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1f3b20d84491d5fe4b83b46852860a27f4e47966cdcf6974cb4b00c485cc9bf1d90ad7e7d5a96c90a35952e214cf0bf6680a2ba07e6ed178d94d50ad85bfa10d",
          "sha256": "61b68d734fe568d9a8a34b49c841fc04d71b957f082f45a019ef2263f5207fea",
          "sha1": "f1e63d76f2773988be7668fc8d30d5de90d6fac2",
          "md5": "0435ec80e0dba62a895e84919b590f29"
        }
      ]
    }
  ]
}
