{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/c660192-change-min-android-version-SNAPSHOT/test-utils-c660192-change-min-android-version-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "c660192-change-min-android-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-c660192-change-min-android-version-SNAPSHOT.klib",
          "size": 14297,
          "sha512": "b2a60f82d7d49e65182861281bac176425ea6cd314ea6d5734aaa89001fae3876106ae1b1d3fa36318b1cd60a2139736611e4bb12fecab89bdf692cdb8b541a5",
          "sha256": "c8d56e34fbef56e6e988e17cf2efe0223f8ab9966497b527415b25eb7924e0f3",
          "sha1": "71413c7535c784cd5c63450f6a50c7832aee5809",
          "md5": "53dbe616f8bc3fdb80fb577fac10a62c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1ad1171f747692f1e8a3f7c10d63b1f139b189f23cdfc0647cf2b94a80a45ab6d024aee45aaac7c4661631f7c0d5984049ac4a17568a89535addf26635f2cedb",
          "sha256": "06847a4dc6057c7e2ada58aaf39705fbe2d244e2c63f674433175b7d09c120f6",
          "sha1": "712a9751b98f4052e2d8b8b78c1909b744c3e68a",
          "md5": "e61f76d99f2586ff6124b8831c4ab366"
        }
      ]
    }
  ]
}
