{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/ef3a5b1-bump-updates-SNAPSHOT/test-utils-resourceloader-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchosarm64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 14248,
          "sha512": "09bde832c7deee8ba23b03d353bbd10d08b1fddcf8652460e7f3005ac53eb32105dd93e0b104942928934effcd252b30f9a03271356a872c59d7875d33ea289b",
          "sha256": "e5de42e84d2ceb1c2c500d89663fe29f613b1a3598d16019e6d102d62178c48a",
          "sha1": "e895ca151c91c8d5a7a4fe6529a972ce301163a0",
          "md5": "09ad5e77fed1511f48ff6d9e9675b248"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-watchosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-resourceloader-watchosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-watchosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "124cb7a7e458a745a42fd5c974edec88e4da33af241ebe3e8cd1653b6f4fb85815606de25cb04cb9bff4481b33b96df75bf35bf9cab9a8797b9d817d49a021af",
          "sha256": "4740bd2a50f8a20931366e99ba74f479332082bd1c11b4037ec57c1a60d7d26f",
          "sha1": "fac57b73de43810b767e5a6037ad20e744b8c1df",
          "md5": "d6bf0e7acb96dd78446f8b335f575833"
        }
      ]
    }
  ]
}
