{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT/kmock-0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "cbf4c73c24ff9837f0fbd730d819cccb26166c408b99d0dfb57cbd6e8408f18499628fd9766f7419a3677925c806f96cf1aed1ec29b6dc3c01fc81ed3ca09a38",
          "sha256": "96023495ab373b7d93bdef324c13a607b2f2be076baaa6cd06f64707641a51a9",
          "sha1": "4d89c27312375dace3872b03f68b7b00de93e89d",
          "md5": "e9976c5e4129dfe987c6974fb4cb70cb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-fix-artifact-cleanup-bfddcdbf83-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "cbf4c73c24ff9837f0fbd730d819cccb26166c408b99d0dfb57cbd6e8408f18499628fd9766f7419a3677925c806f96cf1aed1ec29b6dc3c01fc81ed3ca09a38",
          "sha256": "96023495ab373b7d93bdef324c13a607b2f2be076baaa6cd06f64707641a51a9",
          "sha1": "4d89c27312375dace3872b03f68b7b00de93e89d",
          "md5": "e9976c5e4129dfe987c6974fb4cb70cb"
        }
      ]
    }
  ]
}
