{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "12ea545-fix-python-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-coverage-12ea545-fix-python-dependencies.jar",
          "size": 135187,
          "sha512": "b8abeeeb828eb7eb6b0077abc2967c9d62909450b48c6fcd66c01b16c4dcacfa13b99b2a71d3c9d18d43237fd276e0bde038acdad9ccff8d198e84394002aadd",
          "sha256": "9014229d1bd2727fd7b3e074dad7f4d8f6d55338f09b0f339657b358cc3ce2b4",
          "sha1": "a506469b58b5f3df1b47feba5ded9ea49787c3bd",
          "md5": "acffca563cdb65506c523ab40ae35bb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "12ea545-fix-python-dependencies"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-coverage-12ea545-fix-python-dependencies.jar",
          "size": 135187,
          "sha512": "b8abeeeb828eb7eb6b0077abc2967c9d62909450b48c6fcd66c01b16c4dcacfa13b99b2a71d3c9d18d43237fd276e0bde038acdad9ccff8d198e84394002aadd",
          "sha256": "9014229d1bd2727fd7b3e074dad7f4d8f6d55338f09b0f339657b358cc3ce2b4",
          "sha1": "a506469b58b5f3df1b47feba5ded9ea49787c3bd",
          "md5": "acffca563cdb65506c523ab40ae35bb8"
        }
      ]
    }
  ]
}
