{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/422ab00-bump-antibytes-SNAPSHOT/test-utils-annotations-422ab00-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "422ab00-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-422ab00-bump-antibytes-SNAPSHOT.klib",
          "size": 11206,
          "sha512": "e9562f03031aa7abee62526f5e739b1858744318b7efbf5e7291e9ae6fa548f953dc83631f1e7dbb0a8bc51fc6252f005a9113601c9698bf609c353c22bce330",
          "sha256": "a5fe8090f5933950ba1733d903ced5a0e277e0cb636ddc304a31159801997823",
          "sha1": "686b666520a4650ae31c0da052e2521774140e78",
          "md5": "a2a22e79f2cafc4d4cbfbde1687a94dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-422ab00-bump-antibytes-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosarm64-422ab00-bump-antibytes-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e469c084eca46f7119815babdca165d7ec4b6857eec517353c66165d6c13fa344d607e844a756650bb57ca7cd0cc2282690671a689527f9e3bee8c47808159d6",
          "sha256": "d99bdb3628691354c77e76b786303cbb0dc8f1467116d6953b9aa2c5cf7a6395",
          "sha1": "e723c7d8e12c560cb547d8d13e4c968e4a8f3fa4",
          "md5": "34ccdf0cbc8a86e13f300dbe53971cd8"
        }
      ]
    }
  ]
}
