{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-numeric-api-SNAPSHOT/core-0.2.0-change-numeric-api-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-numeric-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.2.0-change-numeric-api-SNAPSHOT.klib",
          "size": 59545,
          "sha512": "6ffc347c471a8bd1e348582c38f10ea74a3911651f1dd803fec4143f575a52d84fe7cb427ee83aabaea25cb284c820a5c89b8fbb4df060be2762eff6b2eb59c2",
          "sha256": "879873099660a386b6296ab79ad72c954d6e4cd2c3ed82e0118c49baa31bdcc3",
          "sha1": "63792a6dcb78cc21e17bffb96e0c743df26ec117",
          "md5": "9c4e611cc818db2eae2be998ffd21ee3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.2.0-change-numeric-api-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.2.0-change-numeric-api-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "469e6884b6d5ca6f32f93620d0efd88962b8e129e8ae3c5a821c0458a8b56fec31c01d359cdddec3ee86f4e66dfae143ffcb2f3095fe8eac805313076e3458c5",
          "sha256": "f09bcfb5e684bb4e6fbb7f60343de11fdfb75cd19196af018557c2da9c6f0490",
          "sha1": "3649d1a83dd8090054061f2be6416e2b0630f145",
          "md5": "a6b626d370dceb5e387bc6a50cf9403c"
        }
      ]
    }
  ]
}
