{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/7ed357e-bump-updates-SNAPSHOT/test-utils-ktor-7ed357e-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "7ed357e-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-7ed357e-bump-updates-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "a3687ac5503dc40e70f736b2f69a7c117762bb65a11b09f51c211d24bc4ff9bdf9fa1a0257de48196b608d2ae8c7fdec8b18ec330736b3c5bfd920a7b4967e3a",
          "sha256": "ea28d4a63518f6e547e49cf4bdff4a5e7ba01066089b51e20ee616c0fea15746",
          "sha1": "ccc6accc26fa6ec43dc73973d24a1d2fec126a70",
          "md5": "e96343c132c59b142bbd5e5fd76c70f1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-7ed357e-bump-updates-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "a3687ac5503dc40e70f736b2f69a7c117762bb65a11b09f51c211d24bc4ff9bdf9fa1a0257de48196b608d2ae8c7fdec8b18ec330736b3c5bfd920a7b4967e3a",
          "sha256": "ea28d4a63518f6e547e49cf4bdff4a5e7ba01066089b51e20ee616c0fea15746",
          "sha1": "ccc6accc26fa6ec43dc73973d24a1d2fec126a70",
          "md5": "e96343c132c59b142bbd5e5fd76c70f1"
        }
      ]
    }
  ]
}
