{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/3469f60-add-ios-SNAPSHOT/test-utils-3469f60-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "3469f60-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-3469f60-add-ios-SNAPSHOT.jar",
          "size": 8776,
          "sha512": "a0eb53f6be2082b2a4595d49dbe2ebe16633b5890950277e3f4794250dc18a90b8e256d7dadb740da95cff0f7d77719bc800873ea7f21c77902a5c1d134b0fff",
          "sha256": "dd18d8e308a3b16a7361a7c5f314d80cea9dcdeea0ce7e2ab7f1a7282c928982",
          "sha1": "3559954225b8ff5636b19ce6ea6760a9a5941373",
          "md5": "acf33306ca6ce374b15700e7f9fece07"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-3469f60-add-ios-SNAPSHOT.jar",
          "size": 8776,
          "sha512": "a0eb53f6be2082b2a4595d49dbe2ebe16633b5890950277e3f4794250dc18a90b8e256d7dadb740da95cff0f7d77719bc800873ea7f21c77902a5c1d134b0fff",
          "sha256": "dd18d8e308a3b16a7361a7c5f314d80cea9dcdeea0ce7e2ab7f1a7282c928982",
          "sha1": "3559954225b8ff5636b19ce6ea6760a9a5941373",
          "md5": "acf33306ca6ce374b15700e7f9fece07"
        }
      ]
    }
  ]
}
