{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/d75bc0f-change-coroutines-SNAPSHOT/test-utils-d75bc0f-change-coroutines-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "d75bc0f-change-coroutines-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-d75bc0f-change-coroutines-SNAPSHOT.klib",
          "size": 14316,
          "sha512": "c77850254b2f5394110262f86f71576eaf68e40b44bcd198a3f6c39249036c07a608297345781f2efe32f702335a2bfc440ad4976f0ef653acbcb8e1f52a2c20",
          "sha256": "c4cab3c108c8626ad2e7cf6d1ade158666a8db0735f78f7920f6312e9ff9da6d",
          "sha1": "4d1bd781f2f280911e1f1f302bf2e9cfceddf52d",
          "md5": "3500ffd51405ad1cd1cd2de0d9c2eec7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-d75bc0f-change-coroutines-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-d75bc0f-change-coroutines-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f7ccecf57428fd93b60ae595ac8b9aee56f04a42624f45c414e99109868a7c8ec7c6e9942770db38bfce14f6336112d18911b4f8f0bfac54f36e80161925fc10",
          "sha256": "ba36f2d894ee1cb2005e8323933f9611be0509a27616129b3dc961e5135ad532",
          "sha1": "2e55572b68aae23aebe6120ff8c8b9c563b5e82d",
          "md5": "b6bb9766fcb98ee1df31775f36fa5e15"
        }
      ]
    }
  ]
}
