{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f8d6e50-bump-workflows-SNAPSHOT/test-utils-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 7996,
          "sha512": "1975281765ac841c5fc8b2ec87604946a8db52e9a0dd33fb89ac6cdcbafe7cccdfef54b1c28abd2fc6f2caa325a56727d851d959786b5d6fb00da05a6cd297cd",
          "sha256": "db9db4ac6c5f286d389ab7b463d7dc80be9cfe03ebf0c5449693b222fe5709e6",
          "sha1": "53fef8b61249ddf8eb28e7da09d9e791be091e0d",
          "md5": "5763fb77f879aa8e919947a4be235080"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-watchosarm32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8af835367419745e6fd4dc1d749607636ab572a0834db5697d021658d587b011b8d40aadf69409ec806c4052d7ac0f9aa99d06a7b23c310d4c99d1e02c1a79a0",
          "sha256": "2fd935274c300b0f689e51475739dc43b693185a238390d5536c37b5b2207183",
          "sha1": "75048e8e40fe8ae11f9814521aab2b89f46e47dd",
          "md5": "4a309060e45d6063b459584564a128a0"
        }
      ]
    }
  ]
}
