{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-compiler",
    "version": "5a5166e-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-compiler-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-compiler-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 15890,
          "sha512": "10af7fa807c20ded4381fadbe5bece283fa4185d6e16286d3a5a12c54e70716c6f29c88015de053f17639513bdfe6f966bc8ad91cbd5332ad72fe20871403ef9",
          "sha256": "63494da599a02d51ff22b89f3c60d9a18b4cef6ea02de83d8ddf17ea47e58402",
          "sha1": "34ff177046876fc80da20344df14b2df7516e908",
          "md5": "5e9f0effd933d7d896f6a94a26e5ac8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-compiler-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-compiler-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 15890,
          "sha512": "10af7fa807c20ded4381fadbe5bece283fa4185d6e16286d3a5a12c54e70716c6f29c88015de053f17639513bdfe6f966bc8ad91cbd5332ad72fe20871403ef9",
          "sha256": "63494da599a02d51ff22b89f3c60d9a18b4cef6ea02de83d8ddf17ea47e58402",
          "sha1": "34ff177046876fc80da20344df14b2df7516e908",
          "md5": "5e9f0effd933d7d896f6a94a26e5ac8f"
        }
      ]
    }
  ]
}
