{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/9aec7b7-bump-antibytes-SNAPSHOT/test-utils-ktor-9aec7b7-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "9aec7b7-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "size": 26407,
          "sha512": "38acdfb56df87737aa6c26318c0c5f48260a55933ca778be0b1be7b824f3b97caab79b49e769520ae7c6ba8c97d69074266a9951e532d44d8449cc8bfd44a8ff",
          "sha256": "6c956dc1e1e6b1c1718b2181e9936064df254e42792033dc187e08615830441c",
          "sha1": "5636641db8ea2d55fa801afebf28334be8e677ef",
          "md5": "d277a20c8d7aa5f04cae061f60fcf724"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "size": 26407,
          "sha512": "38acdfb56df87737aa6c26318c0c5f48260a55933ca778be0b1be7b824f3b97caab79b49e769520ae7c6ba8c97d69074266a9951e532d44d8449cc8bfd44a8ff",
          "sha256": "6c956dc1e1e6b1c1718b2181e9936064df254e42792033dc187e08615830441c",
          "sha1": "5636641db8ea2d55fa801afebf28334be8e677ef",
          "md5": "d277a20c8d7aa5f04cae061f60fcf724"
        }
      ]
    }
  ]
}
