{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "2dcaad0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-2dcaad0.jar",
          "url": "antibytes-dependency-2dcaad0.jar",
          "size": 27970,
          "sha512": "a6b1b043ce58ef55762e6fc9de21b3afe2c37f68e2d96bd74bf222a608a790f83a4f0b9380ec78ad840037f9001ccbe25f59d2abafeeb23803c63357f3e50786",
          "sha256": "844da80206fbe721db8461b74c6a8ba9b0a941d8201ad011adf320e682c84b86",
          "sha1": "259f987a9d273050ffd9f4fdfcbdf5b7decf0537",
          "md5": "9635230261cd4a630bd045d416eb101b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-2dcaad0.jar",
          "url": "antibytes-dependency-2dcaad0.jar",
          "size": 27970,
          "sha512": "a6b1b043ce58ef55762e6fc9de21b3afe2c37f68e2d96bd74bf222a608a790f83a4f0b9380ec78ad840037f9001ccbe25f59d2abafeeb23803c63357f3e50786",
          "sha256": "844da80206fbe721db8461b74c6a8ba9b0a941d8201ad011adf320e682c84b86",
          "sha1": "259f987a9d273050ffd9f4fdfcbdf5b7decf0537",
          "md5": "9635230261cd4a630bd045d416eb101b"
        }
      ]
    }
  ]
}
