{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "47d4b73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-47d4b73.jar",
          "url": "antibytes-configuration-47d4b73.jar",
          "size": 49663,
          "sha512": "424d88d57fe7c0342fe65abca36908ed85adaaf196a06c900cb9bf41811400cb003674d4bf9898ab123b921ec6e5715e2cb79c7bf357152b6501dac12496fc34",
          "sha256": "7ee279dac7e768a0311b736ceb4a7ecbe9dac7dd5ae7d7e950325652036c0d5d",
          "sha1": "9b4f98b36eb214ceafd6d692c5db92fe2abd92fb",
          "md5": "853c851c930ffe1165acdf47b6076f49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "47d4b73"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-47d4b73.jar",
          "url": "antibytes-configuration-47d4b73.jar",
          "size": 49663,
          "sha512": "424d88d57fe7c0342fe65abca36908ed85adaaf196a06c900cb9bf41811400cb003674d4bf9898ab123b921ec6e5715e2cb79c7bf357152b6501dac12496fc34",
          "sha256": "7ee279dac7e768a0311b736ceb4a7ecbe9dac7dd5ae7d7e950325652036c0d5d",
          "sha1": "9b4f98b36eb214ceafd6d692c5db92fe2abd92fb",
          "md5": "853c851c930ffe1165acdf47b6076f49"
        }
      ]
    }
  ]
}
