{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-localized-datetime-SNAPSHOT/ktx-datetime-0.3.1-add-localized-datetime-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-localized-datetime-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-add-localized-datetime-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-add-localized-datetime-SNAPSHOT.jar",
          "size": 48203,
          "sha512": "b7a573966b7241aef3de521eadb806b9a2b3c6fff1c887478aed0a33f1fb9f2cf0f969ff12bbed350d69ee3e20efcda80fdbeaa9a079b10458bfcfe4c7385d68",
          "sha256": "36ff7538fbd846761d4c309022e4e12f5223c06feb094f934e5d0109f6220137",
          "sha1": "1e1b9c01ccb898ff50af169cae9b471a638f8f27",
          "md5": "3cbde1c82e2025a819b87e081bfe0bdc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-localized-datetime-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-add-localized-datetime-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-add-localized-datetime-SNAPSHOT.jar",
          "size": 48203,
          "sha512": "b7a573966b7241aef3de521eadb806b9a2b3c6fff1c887478aed0a33f1fb9f2cf0f969ff12bbed350d69ee3e20efcda80fdbeaa9a079b10458bfcfe4c7385d68",
          "sha256": "36ff7538fbd846761d4c309022e4e12f5223c06feb094f934e5d0109f6220137",
          "sha1": "1e1b9c01ccb898ff50af169cae9b471a638f8f27",
          "md5": "3cbde1c82e2025a819b87e081bfe0bdc"
        }
      ]
    }
  ]
}
