{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/5b65d35-bump-updates-SNAPSHOT/test-utils-ktor-5b65d35-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "5b65d35-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-5b65d35-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-5b65d35-bump-updates-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "5083542ff5450beae1a241922a0acb4a4199aebf8f622f383d7bba0591815ceb5ff0858883d3eb7b1aa321f0b08d93754e95f95b78580a3780a589aa51948a46",
          "sha256": "d4bd66f096bbbc32b95369d3ddb997a04b92c7f8cd156de48316ae005bb9f9a9",
          "sha1": "b31290cd6317db234c9325079b8bc275a969080d",
          "md5": "0142b7a80001fa68a9571f66ad009cb8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-5b65d35-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-5b65d35-bump-updates-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "5083542ff5450beae1a241922a0acb4a4199aebf8f622f383d7bba0591815ceb5ff0858883d3eb7b1aa321f0b08d93754e95f95b78580a3780a589aa51948a46",
          "sha256": "d4bd66f096bbbc32b95369d3ddb997a04b92c7f8cd156de48316ae005bb9f9a9",
          "sha1": "b31290cd6317db234c9325079b8bc275a969080d",
          "md5": "0142b7a80001fa68a9571f66ad009cb8"
        }
      ]
    }
  ]
}
