{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/694b583-change-setup-SNAPSHOT/test-utils-ktor-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-tvossimulatorarm64-694b583-change-setup-SNAPSHOT.klib",
          "size": 15121,
          "sha512": "2f5bd7683dc964aac7148995482b8c6f09c6d79e59b395a6d35337c2d0f16d9ece788ba9505790ef714f4fd9e2d1c5c018e3a975cce2f6ff018053878d390f99",
          "sha256": "249bf53a465116948e17a1187f9d7c4c61dd616e69dea857c14dcd397a5c81c5",
          "sha1": "39bb869db1da5eddd7dd6ef8224e55d5590261a4",
          "md5": "4ef00b871b3b2fffd3796ace53eae6b9"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-tvossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-tvossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5c34996e18b0299bd59486d4519540d3153f9f895709c68d96f7b07b20167c0cebdb831eb6abd0a26312050f7acd8ec4f851fd72130b187c80105a17ded9880a",
          "sha256": "bfe09744b96393ecf0168d39cd9e208ca1c85b948e86129e113d4c92b1251a6d",
          "sha1": "5509e1ccf0986d367aa7dd470c594d59314cb04c",
          "md5": "03a5366500556a3d0517a2f3cf559adb"
        }
      ]
    }
  ]
}
