{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "96314ec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-96314ec.jar",
          "url": "antibytes-gradle-utils-96314ec.jar",
          "size": 9471,
          "sha512": "4b83003493e5082ac3724725187f10ae9e0461c7bcbe2f7aa4f1714e01100e0ae58e55bf13bec9724157167e8764a0c0bcdd490c93eff7b1ee3e9f80c1741755",
          "sha256": "3958a9e3ce17cdfe894fb3aadac659948bc4946716377397f94deb955f958479",
          "sha1": "8333b9fd4f58b772d912d2c01f2a585e4ce49bfc",
          "md5": "a93efc5233dd5996dab3ab71718aee17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-96314ec.jar",
          "url": "antibytes-gradle-utils-96314ec.jar",
          "size": 9471,
          "sha512": "4b83003493e5082ac3724725187f10ae9e0461c7bcbe2f7aa4f1714e01100e0ae58e55bf13bec9724157167e8764a0c0bcdd490c93eff7b1ee3e9f80c1741755",
          "sha256": "3958a9e3ce17cdfe894fb3aadac659948bc4946716377397f94deb955f958479",
          "sha1": "8333b9fd4f58b772d912d2c01f2a585e4ce49bfc",
          "md5": "a93efc5233dd5996dab3ab71718aee17"
        }
      ]
    }
  ]
}
