{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/df500e4-change-docs-SNAPSHOT/test-utils-df500e4-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-df500e4-change-docs-SNAPSHOT.klib",
          "url": "test-utils-js-df500e4-change-docs-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "446d1bafa7bbe7646daf173d5ea1d7955d340118a63da04e6dbdd40a581a3ce83c56fcf97dd1e5cf169e112a3652043ed180424d076ff31143c065736f398a96",
          "sha256": "ef42edb0d8a55d2a5352bd4aa154f4f6a4bdf4e5a71022175d4f53021c337b6c",
          "sha1": "7ef1b26308a5d30fab14a732696b7f3e66f988bf",
          "md5": "53e8e091bdb7b845f3f885df5a571b5a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-df500e4-change-docs-SNAPSHOT.klib",
          "url": "test-utils-js-df500e4-change-docs-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "446d1bafa7bbe7646daf173d5ea1d7955d340118a63da04e6dbdd40a581a3ce83c56fcf97dd1e5cf169e112a3652043ed180424d076ff31143c065736f398a96",
          "sha256": "ef42edb0d8a55d2a5352bd4aa154f4f6a4bdf4e5a71022175d4f53021c337b6c",
          "sha1": "7ef1b26308a5d30fab14a732696b7f3e66f988bf",
          "md5": "53e8e091bdb7b845f3f885df5a571b5a"
        }
      ]
    }
  ]
}
