{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/ee3b487-add-constraints-SNAPSHOT/kmock-ee3b487-add-constraints-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "ee3b487-add-constraints-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-ee3b487-add-constraints-SNAPSHOT.klib",
          "url": "kmock-js-ee3b487-add-constraints-SNAPSHOT.klib",
          "size": 103109,
          "sha512": "57097a740064a1b0e9b319292c94a2614198f5258e9b21dfa4c3fec4c15a07eade239ab882d5486620a6984f800780838ccfa8e704bc53b56d256ade68b8edae",
          "sha256": "06efd5b2cf2acf5a24b3e20ca77e92017c69b582aa96d6bcb0523f8ed4fb473f",
          "sha1": "259950bed92c23951e1eaabe9b138e1e727d9505",
          "md5": "7c2c6e244d9aa1fdc91a1d4345a80381"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-ee3b487-add-constraints-SNAPSHOT.klib",
          "url": "kmock-js-ee3b487-add-constraints-SNAPSHOT.klib",
          "size": 103109,
          "sha512": "57097a740064a1b0e9b319292c94a2614198f5258e9b21dfa4c3fec4c15a07eade239ab882d5486620a6984f800780838ccfa8e704bc53b56d256ade68b8edae",
          "sha256": "06efd5b2cf2acf5a24b3e20ca77e92017c69b582aa96d6bcb0523f8ed4fb473f",
          "sha1": "259950bed92c23951e1eaabe9b138e1e727d9505",
          "md5": "7c2c6e244d9aa1fdc91a1d4345a80381"
        }
      ]
    }
  ]
}
