{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "206e82f-add-annotations-module-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-metadata.jar",
          "url": "test-utils-fixture-206e82f-add-annotations-module-SNAPSHOT.jar",
          "size": 13804,
          "sha512": "bcbc1d80a48ef56210645299f31140da634dd2e2605cddcb02155a2075596b7fac736c527697243ae9995dc064d5b7c39c7e77b3b79e6ab824b67ac4f3d3b021",
          "sha256": "5cc93cd9be73aad7e7a761c31c38ff1a3dfdabe6a62959f5e42f37aaccd2aeb3",
          "sha1": "8667142dfd46767c10bdd617581b0b8b0c9d9bae",
          "md5": "7129780f675140324635c0d91132ca7a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/206e82f-add-annotations-module-SNAPSHOT/test-utils-fixture-android-206e82f-add-annotations-module-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "206e82f-add-annotations-module-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/206e82f-add-annotations-module-SNAPSHOT/test-utils-fixture-android-206e82f-add-annotations-module-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "206e82f-add-annotations-module-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/206e82f-add-annotations-module-SNAPSHOT/test-utils-fixture-jvm-206e82f-add-annotations-module-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "206e82f-add-annotations-module-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/206e82f-add-annotations-module-SNAPSHOT/test-utils-fixture-jvm-206e82f-add-annotations-module-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "206e82f-add-annotations-module-SNAPSHOT"
      }
    }
  ]
}
