{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b452879-fix-docs-SNAPSHOT/test-utils-ktor-b452879-fix-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b452879-fix-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-b452879-fix-docs-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-b452879-fix-docs-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "7f176eb1a1a2cd2278a6a7713c90cc6bad2e67c77a7f594c4ac3728d2b343dac0eeda986bf2f8980c02ea282314014137da1031c1e7d7962336afc8b32c6d7bf",
          "sha256": "d81261f48a71de247d61c12bc47c9b25dfec7f3227608eae5ed7204f0d64b75f",
          "sha1": "47db7bcf888d3a5475d4244264da1f801fdc8f77",
          "md5": "95acfccb00acb14619ee5b8ab39bcdf3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-b452879-fix-docs-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-b452879-fix-docs-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "7f176eb1a1a2cd2278a6a7713c90cc6bad2e67c77a7f594c4ac3728d2b343dac0eeda986bf2f8980c02ea282314014137da1031c1e7d7962336afc8b32c6d7bf",
          "sha256": "d81261f48a71de247d61c12bc47c9b25dfec7f3227608eae5ed7204f0d64b75f",
          "sha1": "47db7bcf888d3a5475d4244264da1f801fdc8f77",
          "md5": "95acfccb00acb14619ee5b8ab39bcdf3"
        }
      ]
    }
  ]
}
