{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "4e45abe-change-catalog-copy-task",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-4e45abe-change-catalog-copy-task.jar",
          "url": "antibytes-android-application-configuration-4e45abe-change-catalog-copy-task.jar",
          "size": 56574,
          "sha512": "9896653ed48a02665446b5fc4b68b0c19936dbc2e0ccb00c6b6750463f0e06590e17d8a4d84bf19e6446be14e751a30dd640d801f56d54fa12dd927930228613",
          "sha256": "04d63d80f87f10405d43424027524a687fb39cc6cc97d95504197421606936da",
          "sha1": "8e0f638b8549d02b6df6a91bbe91637eb56e9e77",
          "md5": "c3c79ed08e46dd188d5da860a495f8ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4e45abe-change-catalog-copy-task"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-4e45abe-change-catalog-copy-task.jar",
          "url": "antibytes-android-application-configuration-4e45abe-change-catalog-copy-task.jar",
          "size": 56574,
          "sha512": "9896653ed48a02665446b5fc4b68b0c19936dbc2e0ccb00c6b6750463f0e06590e17d8a4d84bf19e6446be14e751a30dd640d801f56d54fa12dd927930228613",
          "sha256": "04d63d80f87f10405d43424027524a687fb39cc6cc97d95504197421606936da",
          "sha1": "8e0f638b8549d02b6df6a91bbe91637eb56e9e77",
          "md5": "c3c79ed08e46dd188d5da860a495f8ab"
        }
      ]
    }
  ]
}
