{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc01-SNAPSHOT.klib",
          "size": 202838,
          "sha512": "6cf933b9a449621d34b702d08652cc7aa4e8afd4763549b5eecd8d0a377316cfea1d359837fc10612aef923087683e63bf496766696430db0481e97da58c9302",
          "sha256": "c54f2fc0a114e416f26a52c3a0a5cbc0973693ce5003ed2530347d8703e42246",
          "sha1": "dad56645f870e1b5d37a784ce17df81f840c3944",
          "md5": "70549751a64f22aab63da0489ac037da"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc01-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc01-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "98a0d133202e519539a73c74aa9b417e16bcd9ca73779095d540aa90d6253de611f1f34ff9f920d64e445c888220815d53c09c49372c00e8a5474eb164c045a2",
          "sha256": "c1b73c5826d1f5e94e2e3f0d6196cc034f487b81b6d88963b1dd64b33a5a02a1",
          "sha1": "8babd59b010e738e7d0913c4f27041da51d54628",
          "md5": "80cbd217eff612b4cb5820136a67e7c1"
        }
      ]
    }
  ]
}
