{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/12cf284-bump-updates-SNAPSHOT/test-utils-annotations-12cf284-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "12cf284-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-12cf284-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-12cf284-bump-updates-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "ea4e7f43454cdce90b562fcde3cbba24b098986f38d2a6ef2b229dc71917e4305f72c8f5a39f03eb2c4c53c5fadfa6407dd09a2d5bfcb9eec381736c12b7724a",
          "sha256": "9b6edea8ff1e3f236464b61f2db5b11d3592c0f524bb556b5169205fc78ab958",
          "sha1": "93ccfb1410e39a21745e12ee83988525030e7970",
          "md5": "cb9ee9f4abe7c526ed2b39bde92b6176"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-12cf284-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-12cf284-bump-updates-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "ea4e7f43454cdce90b562fcde3cbba24b098986f38d2a6ef2b229dc71917e4305f72c8f5a39f03eb2c4c53c5fadfa6407dd09a2d5bfcb9eec381736c12b7724a",
          "sha256": "9b6edea8ff1e3f236464b61f2db5b11d3592c0f524bb556b5169205fc78ab958",
          "sha1": "93ccfb1410e39a21745e12ee83988525030e7970",
          "md5": "cb9ee9f4abe7c526ed2b39bde92b6176"
        }
      ]
    }
  ]
}
