{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT/kmock-0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "88ba2fd17b4286216befe37f4219ccc19e4e5bee7f0c7b324e12cde9fff32ffe4d70d8d32c0a9b24fda70d352d65db7f6677ae55fa6dbc0399275507bc152f6e",
          "sha256": "131981149aa691e8db26d428b467ebd7ebe7c7a9846558852d972bd87fbba6f7",
          "sha1": "b97af8f8fa2828a02beabddb13bcc3a12e9d401a",
          "md5": "693531d9cb89c436f5d4ac15641ea554"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-f3c1acfe2e-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "88ba2fd17b4286216befe37f4219ccc19e4e5bee7f0c7b324e12cde9fff32ffe4d70d8d32c0a9b24fda70d352d65db7f6677ae55fa6dbc0399275507bc152f6e",
          "sha256": "131981149aa691e8db26d428b467ebd7ebe7c7a9846558852d972bd87fbba6f7",
          "sha1": "b97af8f8fa2828a02beabddb13bcc3a12e9d401a",
          "md5": "693531d9cb89c436f5d4ac15641ea554"
        }
      ]
    }
  ]
}
