{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "a3df5fc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-a3df5fc.jar",
          "url": "antibytes-publishing-a3df5fc.jar",
          "size": 101752,
          "sha512": "dab7ad053d4aa225f001d9950d442891889a87f7ed397cd3faf219deb536fc1dbc0550c3f096f95f29c1089e9d10468e6435ee14b749333a0107d23deb6b1ab9",
          "sha256": "90aabc7ebb238dccb73aec1ef372feea06cf29d7ab4aa94dda1b3a29943a4dab",
          "sha1": "573d48234b2e1e7629952d31769287ce8de2d871",
          "md5": "4bfd037522c3e3a5fa72ce13d2c0b39e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-a3df5fc.jar",
          "url": "antibytes-publishing-a3df5fc.jar",
          "size": 101752,
          "sha512": "dab7ad053d4aa225f001d9950d442891889a87f7ed397cd3faf219deb536fc1dbc0550c3f096f95f29c1089e9d10468e6435ee14b749333a0107d23deb6b1ab9",
          "sha256": "90aabc7ebb238dccb73aec1ef372feea06cf29d7ab4aa94dda1b3a29943a4dab",
          "sha1": "573d48234b2e1e7629952d31769287ce8de2d871",
          "md5": "4bfd037522c3e3a5fa72ce13d2c0b39e"
        }
      ]
    }
  ]
}
