{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-settings-SNAPSHOT/core-0.4.0-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-macosarm64-0.4.0-bump-settings-SNAPSHOT.klib",
          "size": 105853,
          "sha512": "59682954cdcce8ae8bf903c168f3616bfe022737c386899ff953dae5e3ef58c2ae5a0a1688cbf4007905c87ebd3ca6fb1e2f040e55eeef419aa99ece3c4240f7",
          "sha256": "9b86b4b1dc9e1f76700139dd56fcceb647ca299785f2504c72bb5102e63213c5",
          "sha1": "bd98e1bfb5e34d7ce4a6bb54797e4b0b3201bb3a",
          "md5": "c6d497be75c9e8e11a1e3e13f90f9456"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-macosarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "url": "core-macosarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "84086bfb8570fc53668dea4d536d764ed520b5dac866a9f6885784c6c2e23f6aeba24b1e6e84541cd927465c81ab30fce28a5d1cfbb3cf2dc413ca307568699f",
          "sha256": "4378e6923b72dab8730bf05cb50f3707a4c14debf03e7cbbe8ceb53a2a53041f",
          "sha1": "832cd65671655017c76a05b9e23887812e2aae89",
          "md5": "9254e29d2e9228af464cc3ac886d9f2e"
        }
      ]
    }
  ]
}
