{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosx64-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 7032,
          "sha512": "9dd0601834b08678789019a64ee926de7304a3d9d65f4c7a4d2f3a5685f479e843c284e57b8f0e05292678f2eab6a8d9e246e2dd4dc012b9b24408b25f19e584",
          "sha256": "84cc965a8a9abd7548d780843d87b9c3287fc38b4328d2e2f32762eff2805f16",
          "sha1": "7f4df3c700d46b9ca39d41ac50d387e31387c948",
          "md5": "858fedcbae3c0eb53c407f60ed4c5cda"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosx64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosx64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ae59467c2b82023b7bc19b1e881fe5b1dece951c43819fa4b8770d8b144950d07296be4f5cd6cc61ba9790d31c3652a51b81dfba3a0ec3bf534d25b4c4eca46a",
          "sha256": "85e9f1e79b166fb2dbd152921d9a24063ec12dd26ba02c5d68b44057079f088a",
          "sha1": "56868896423151b388ce1926adc2361cffd1cbeb",
          "md5": "f00077dfd0903442e3a5025c24f2b7c7"
        }
      ]
    }
  ]
}
