{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/de45ed1-add-ios-SNAPSHOT/test-utils-fixture-de45ed1-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "de45ed1-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosarm64-de45ed1-add-ios-SNAPSHOT.klib",
          "size": 31128,
          "sha512": "2d12f95b69a361cbe524c6d161603506ff9d7e897e59a37335ed1eded8bc80e3281317d86e78c870731000206fa8934489397c2b0c0c5f676db2e91c9715084c",
          "sha256": "a93a214809d31fd43d743b432fd7439db470817152e984a0bb0df6e1d5d174b1",
          "sha1": "e05eb92b43bffa580c56663cc8ae6b0937d04b88",
          "md5": "d2185f391490eb30b0fc6fc2b28d5fe8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosarm64-de45ed1-add-ios-SNAPSHOT-metadata.jar",
          "url": "test-utils-fixture-iosarm64-de45ed1-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e62c202b9aabfaf68c5031e3160278eba72a09dc31c0ffa6bf181a50de8178dcf60a26af74e46a23497c3a95437260392e07ab5c7b56c6042e9ab479d1ae4244",
          "sha256": "f48dd7cfedd66346e3f6868efdc0895aa862e79bc8d756746072f56d7ffa3bc8",
          "sha1": "1366892cea19975b7c452e28a86a40f3a41883a5",
          "md5": "3ce6a3a40c06f64e3d648e37236561e6"
        }
      ]
    }
  ]
}
