{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-badges-SNAPSHOT/ktx-datetime-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-fix-badges-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-fix-badges-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "42c44d2017f3a0f449ea16eeedb58855dff427061ff7c4a536d073d5992abced51a3a419ee357a7fdc99e84efb4d2d31c672da12ef2f8ae9055c3592d9df2b59",
          "sha256": "22fbd06ac2c9a02cdc4ba18e8694ebd7015fe3a7e7862474fdbb6606a0acfe5a",
          "sha1": "71131cd7d2d841fc6c758e35336a20ce45d21158",
          "md5": "ad226a273ab5d8a1cafdf76b6647bf19"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-fix-badges-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-fix-badges-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "42c44d2017f3a0f449ea16eeedb58855dff427061ff7c4a536d073d5992abced51a3a419ee357a7fdc99e84efb4d2d31c672da12ef2f8ae9055c3592d9df2b59",
          "sha256": "22fbd06ac2c9a02cdc4ba18e8694ebd7015fe3a7e7862474fdbb6606a0acfe5a",
          "sha1": "71131cd7d2d841fc6c758e35336a20ce45d21158",
          "md5": "ad226a273ab5d8a1cafdf76b6647bf19"
        }
      ]
    }
  ]
}
