{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata.jar",
          "url": "test-utils-ktor-dbbd81e-remove-kotlin-fixture-SNAPSHOT.jar",
          "size": 2460,
          "sha512": "4daf30a4bef73a29e546f6f78071cfe2769ddcc33f3ccb69ef51a8b3c4fba039ed1fc75a44a8bbf79921047da789cb60eb567dee8642f88a6f947cea1de19c50",
          "sha256": "9b91b4db02581cfa960c12b42f8c1c661783f5ff603bf109233022943caba67b",
          "sha1": "f3bd0fbac6980b6a4b32b9c4e59d96cc921ac9b5",
          "md5": "517c87ce0e2451c0b0d4ad7066621371"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-ktor-android-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-ktor-android-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-ktor-jvm-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-ktor-jvm-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    }
  ]
}
