{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.4.0-SNAPSHOT-all.jar",
          "url": "ktx-datetime-0.4.0-SNAPSHOT-all.jar",
          "size": 9008,
          "sha512": "82a1beee6f28530480f29ecdf17f09d70ae07484d04c6f6e9ba5f6724dddb653972afa3e36928a599be66062718bafe6df29db929953228f226290e798f9e491",
          "sha256": "acb079b736d20a6df86aaaea28a9626c6d626a31a83e8440ba48465c850ab5f3",
          "sha1": "b62c97cb244fe5d51bc9d76ba1c4be47528dbcf4",
          "md5": "d21dcc6be634f8a158c8b534f59bf326"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-0.4.0-SNAPSHOT.jar",
          "size": 13895,
          "sha512": "2097f3f102480a0792357dec88b0d00c0b724ff1095cf8ca7c263eab3f9c82ab41e8afe7cd3ecb4c36de80a6d1d9d1a9052845c67e922493125e11cd702590cf",
          "sha256": "54664e8ed1b87ce1c0e2f430fd1193fbd8abd46a8fae22f35e23abe82a267cfa",
          "sha1": "17a79885ae55f0f961212fa775549cd4eb37293b",
          "md5": "fcca50d180b1691df11708e61b81469d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-SNAPSHOT/ktx-datetime-android-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-SNAPSHOT/ktx-datetime-android-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-SNAPSHOT/ktx-datetime-iosx64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-SNAPSHOT/ktx-datetime-iosx64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-SNAPSHOT/ktx-datetime-js-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-SNAPSHOT/ktx-datetime-js-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-SNAPSHOT/ktx-datetime-jvm-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-SNAPSHOT/ktx-datetime-jvm-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.4.0-SNAPSHOT/ktx-datetime-linuxx64-0.4.0-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.4.0-SNAPSHOT"
      }
    }
  ]
}
