{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "9f578bf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-9f578bf.jar",
          "url": "antibytes-configuration-9f578bf.jar",
          "size": 39303,
          "sha512": "b6dd0432b28dd6584fdbd8c52e2d8351652bf9f4b40698a0455d57651e10abdcbc32ed9c4888be98e812ad638d77bca0e9486c0e74e6fb3e442787a92e2635e8",
          "sha256": "0b738039208698cdd67c87c16568f8334ab641d35a069314084b1408663de496",
          "sha1": "97ae2bac1def5f86002bcde60f64b66147493821",
          "md5": "048965d4e4b41be23cc9208e33d6d6fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9f578bf"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-9f578bf.jar",
          "url": "antibytes-configuration-9f578bf.jar",
          "size": 39303,
          "sha512": "b6dd0432b28dd6584fdbd8c52e2d8351652bf9f4b40698a0455d57651e10abdcbc32ed9c4888be98e812ad638d77bca0e9486c0e74e6fb3e442787a92e2635e8",
          "sha256": "0b738039208698cdd67c87c16568f8334ab641d35a069314084b1408663de496",
          "sha1": "97ae2bac1def5f86002bcde60f64b66147493821",
          "md5": "048965d4e4b41be23cc9208e33d6d6fa"
        }
      ]
    }
  ]
}
