{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-source-distr-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-0.1.1-fix-source-distr-SNAPSHOT.jar",
          "url": "kmock-0.1.1-fix-source-distr-SNAPSHOT.jar",
          "size": 32833,
          "sha512": "452ef7f5e59c670e803a50ba5145fbdd0a5cb4c47527fb8098090dc63f8e3b505d34fe2889922d71c4728b1712082198d65802a67e27f99a517ac273090d4962",
          "sha256": "de14ac8eaa269a880bfd1932f95a295092ceaa8ba0381042a6c3713cb1d2ad60",
          "sha1": "32566ca84439429c236ae567838c4ff4ae4761c1",
          "md5": "966f19c3069d78731b689ffc0a5321b1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-fix-source-distr-SNAPSHOT/kmock-android-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-fix-source-distr-SNAPSHOT/kmock-android-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.1.1-fix-source-distr-SNAPSHOT/kmock-iosarm64-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.1.1-fix-source-distr-SNAPSHOT/kmock-iossimulatorarm64-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.1.1-fix-source-distr-SNAPSHOT/kmock-iosx64-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-fix-source-distr-SNAPSHOT/kmock-js-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-fix-source-distr-SNAPSHOT/kmock-js-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-fix-source-distr-SNAPSHOT/kmock-jvm-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-fix-source-distr-SNAPSHOT/kmock-jvm-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.1.1-fix-source-distr-SNAPSHOT/kmock-linuxx64-0.1.1-fix-source-distr-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.1.1-fix-source-distr-SNAPSHOT"
      }
    }
  ]
}
