{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-dbbd81e-remove-kotlin-fixture-SNAPSHOT.jar",
          "size": 1609,
          "sha512": "2e709eb71aedbe4b9abcaa56f998cbb350fb592597f2e569ab7c786c4a566ed1c6ba3c6b81f9e9a242a1ba2b772e6a903634404d3cf6314b4c7a28b959fcad07",
          "sha256": "8694c141e86923dceffaa5fc46384a73e26b8826f41d2b8a17c51be0d0160d3f",
          "sha1": "2acfa8707498aff0614baf9ee23008972268d9b2",
          "md5": "7e6622f7e1426372fe05c3bb3d986621"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-coroutine-android-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-coroutine-android-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-coroutine-jvm-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/dbbd81e-remove-kotlin-fixture-SNAPSHOT/test-utils-coroutine-jvm-dbbd81e-remove-kotlin-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "dbbd81e-remove-kotlin-fixture-SNAPSHOT"
      }
    }
  ]
}
