{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-change-code-generator-SNAPSHOT/kmock-0.1.1-change-code-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-change-code-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-change-code-generator-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-change-code-generator-SNAPSHOT.klib",
          "size": 150261,
          "sha512": "47b3503845ee0bb9436a7bb37b6f6e3752fa16f924ed8219e81cde16f5691d474a110a9ce38d4751600f057e1ea8c3d1225e575d2ab9374d81a62625fbaffe45",
          "sha256": "3710d2d1073339b441d1e460926e96ec2d8df854c0f1588fc06c2c719538f698",
          "sha1": "a25a935dc6a846e7f2510f7f4f322d80bcf3acac",
          "md5": "ad99d027275ddbb9fe19eba4652514da"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-change-code-generator-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-change-code-generator-SNAPSHOT.klib",
          "size": 150261,
          "sha512": "47b3503845ee0bb9436a7bb37b6f6e3752fa16f924ed8219e81cde16f5691d474a110a9ce38d4751600f057e1ea8c3d1225e575d2ab9374d81a62625fbaffe45",
          "sha256": "3710d2d1073339b441d1e460926e96ec2d8df854c0f1588fc06c2c719538f698",
          "sha1": "a25a935dc6a846e7f2510f7f4f322d80bcf3acac",
          "md5": "ad99d027275ddbb9fe19eba4652514da"
        }
      ]
    }
  ]
}
