{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-periods-SNAPSHOT/ktx-datetime-0.3.1-add-periods-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-periods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-periods-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm64-0.3.1-add-periods-SNAPSHOT.klib",
          "size": 20697,
          "sha512": "eee73164984a54a2a62edc816ceab89eddbcce393f141f3fe71f9d967cb7b661f7e38ddb7b16ee5b17e2c4627ae6b7bc00821afe7c45cc021d8ac24526cae617",
          "sha256": "c39f4e7acabb35cf4fca878a78aa3b2d63f983f55b17bfae4a885507aaaae5ec",
          "sha1": "37969c2a13019cc1bc4b4e0a3947365effb4f7d9",
          "md5": "017e411602a46aa719f09532c64c8e2b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-periods-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosarm64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8d8906c773347d957a6159f355c8dec3f16cb2b221cfb99a134118f780add0cde41950d32dd6b06f4ef66aa42bd6d404ba3fa4cc092880171cfce7af7ef32b79",
          "sha256": "2ec59ea6ecc17a8d617437a24308bd2892e84f84da1b4b73266d0e93be0a6f61",
          "sha1": "633edd9ec04e5513db90783efb76ff5b2e9a066d",
          "md5": "bd00b0e261c9d1916d6cfae2e2ed8e36"
        }
      ]
    }
  ]
}
