{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "ce6f4b4-add-iphone15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-ce6f4b4-add-iphone15.jar",
          "url": "antibytes-dependency-helper-ce6f4b4-add-iphone15.jar",
          "size": 69711,
          "sha512": "b16fd9248cec99e5d2801fe136553a523050ab04f7ad27b2d399fd1207534c22ef8484254798e24e8b796d709ca533359722e037c3fc6f5b9a5eb6e1a7017b1b",
          "sha256": "0427d354cc80ab7dda360eed57e16fabd046b5040c4bc99eae064db4d8b9e822",
          "sha1": "0bd35251ebf21f5245c7533318bcc5573cfeee81",
          "md5": "87436140ae3468ddb65c642cd5731c07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.49.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ce6f4b4-add-iphone15"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-ce6f4b4-add-iphone15.jar",
          "url": "antibytes-dependency-helper-ce6f4b4-add-iphone15.jar",
          "size": 69711,
          "sha512": "b16fd9248cec99e5d2801fe136553a523050ab04f7ad27b2d399fd1207534c22ef8484254798e24e8b796d709ca533359722e037c3fc6f5b9a5eb6e1a7017b1b",
          "sha256": "0427d354cc80ab7dda360eed57e16fabd046b5040c4bc99eae064db4d8b9e822",
          "sha1": "0bd35251ebf21f5245c7533318bcc5573cfeee81",
          "md5": "87436140ae3468ddb65c642cd5731c07"
        }
      ]
    }
  ]
}
