{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "388756b-fix-js-async-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata-all.jar",
          "url": "test-utils-coroutine-388756b-fix-js-async-SNAPSHOT-all.jar",
          "size": 5087,
          "sha512": "722d163aa55d4a98581c144e7644d5e734ae712407b62cd4be3f9eaee69e6b1e2b7d12475446478d175382dba38fc0840d627c3fb1477129a5444825777aeaf4",
          "sha256": "3b07c681d78ca1523ce8c3a66a377557fd9b99d290b593255ae1363d624b445f",
          "sha1": "63051f7c5a2785ce7ca0b4917f63b657d92d824c",
          "md5": "7945524a3c67b5778673595a5a30f80f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine.jar",
          "url": "test-utils-coroutine-388756b-fix-js-async-SNAPSHOT.jar",
          "size": 3018,
          "sha512": "d494573e37ffbace9320d550afdf68b858f1f0a2f17bc06738cc8469a75c8256ed3c8ca5100403197b7006f6e122da8194987a847cd37e94a4b1539716a45578",
          "sha256": "d496764eb9482e8a7f65ad37a7b1f4ef4de33c54944290bf9c09533dedaa198a",
          "sha1": "7d4b9f602475ca33759ac81539124b2823da7233",
          "md5": "76d5309cd8de217fe4103374f9367897"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-android-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-android-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-js-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-js-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-jvm-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-jvm-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/388756b-fix-js-async-SNAPSHOT/test-utils-coroutine-linuxx64-388756b-fix-js-async-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "388756b-fix-js-async-SNAPSHOT"
      }
    }
  ]
}
