{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/30769ee-change-setup-SNAPSHOT/test-utils-coroutine-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchosx86-30769ee-change-setup-SNAPSHOT.klib",
          "size": 10147,
          "sha512": "c4eda1bd8dc501c862b316719d2f56a7ae65ba0c8e95741fb641dd8ff1f0d892eb87db3e3beb9642b58a92ed706e63bb0589687aacb43a7d3b6ebfdf5c1e4a1e",
          "sha256": "6b5df6cd729914f49d292d1b70c902cffac6989ec24f62813eab4a6f77b18f69",
          "sha1": "aa4b6f09860aa94126c86b2546d633d7fd3a5c16",
          "md5": "7c3b8aca5620a2c7c063bd9f5fa553c5"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchosx86-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-watchosx86-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e9765b087aca8f840891345f56c718d5fe0dd684d8122fd5070da568bb545876fc9651a1111aa656924d5b8fcff6d39ee37a0484f9958f4b558910c92c23117f",
          "sha256": "38252ff8f265ca3ae2fc107540506dd092d69511a1fa51e2a6f4fac33057bbfa",
          "sha1": "739afd2807967b59a3db4b121c14d376f6655de3",
          "md5": "2bd05fa4ff1f8930b2d0a55c9019c960"
        }
      ]
    }
  ]
}
