{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx86-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "e329f0c06611b415fbb9c916977e31b532c8f5c4f57beede067057b181d825beca6b22d347cca42785a3333b842b7ca40a24206b07de24b86cadb4c443c3a267",
          "sha256": "a8f3516fa309affa18f82228abdd015927f6f3cde92eccb4a1f2624fdcc1dfcf",
          "sha1": "c63d8d0b797ce07f3d4b0c4c2c0c9769537db28a",
          "md5": "fe87cbe3887090c412b4e53c685a5873"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx86-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-watchosx86-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d87e9be79fc58362dd988e1a3c1d95d00f546319e148015eca8fb8200f800dfb54da97bda68fd2854c765c1ccd746bfe38ea72653db9b0d2b036e910258eb083",
          "sha256": "6213d4550cf17d14c4b1862dc2445789991b2eee798136968a3add99c361e955",
          "sha1": "5b900366dbe3bef08e23fff7732c45dd6ccdd066",
          "md5": "92b9ec0830584421623b145c7193599e"
        }
      ]
    }
  ]
}
