{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "35c3f0e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-35c3f0e.jar",
          "url": "antibytes-coverage-35c3f0e.jar",
          "size": 128596,
          "sha512": "2640619ea483d4d1ccdf61812f74a2734e1e80242b0962de09407d2c1d2eb4fe21eff0109b5a53c97e665c22585db6ede0ad90b350809992c05ce31f8d3cbcf5",
          "sha256": "3693fb3821cb559fd4d03fedc5d13024fc262f44888270f0ac13cc5b29f5d495",
          "sha1": "264ae622f393c07ae4fe014ea3b4d27a18884db9",
          "md5": "cb8611b524d8140555a6f7982d792062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "35c3f0e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-35c3f0e.jar",
          "url": "antibytes-coverage-35c3f0e.jar",
          "size": 128596,
          "sha512": "2640619ea483d4d1ccdf61812f74a2734e1e80242b0962de09407d2c1d2eb4fe21eff0109b5a53c97e665c22585db6ede0ad90b350809992c05ce31f8d3cbcf5",
          "sha256": "3693fb3821cb559fd4d03fedc5d13024fc262f44888270f0ac13cc5b29f5d495",
          "sha1": "264ae622f393c07ae4fe014ea3b4d27a18884db9",
          "md5": "cb8611b524d8140555a6f7982d792062"
        }
      ]
    }
  ]
}
