{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "72b787f-add-artifact-resolver-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "9fa83b87a4755fd33d2be9c1f7e681fbff1dd44426b5fd72b2992c7cbefcc4f468b4b803ef6f72a0952b0dec344e7cfa07fe7a5db85c9f3eb45817f5c06f5d8b",
          "sha256": "76d59dee68286575ebe764d0ca06bbd1cca9c26b3ed23987af98c27f13030e4d",
          "sha1": "429fc6a43c9b90730f5390c1d825214b2ae88163",
          "md5": "5dda446b79a14d39e7319cdc70ba4bcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "9fa83b87a4755fd33d2be9c1f7e681fbff1dd44426b5fd72b2992c7cbefcc4f468b4b803ef6f72a0952b0dec344e7cfa07fe7a5db85c9f3eb45817f5c06f5d8b",
          "sha256": "76d59dee68286575ebe764d0ca06bbd1cca9c26b3ed23987af98c27f13030e4d",
          "sha1": "429fc6a43c9b90730f5390c1d825214b2ae88163",
          "md5": "5dda446b79a14d39e7319cdc70ba4bcd"
        }
      ]
    }
  ]
}
