{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-0.1.0.jar",
          "url": "antibytes-dependency-0.1.0.jar",
          "size": 19139,
          "sha512": "56d2531d479af7314ca4fa64435cfcce403909e3bddcd07afdfe437a6677e712080c12bd414da786b23521efc427c44d71ef5142ea42097c70f11a07ad6f0853",
          "sha256": "4debbcd0ba440a0c41b11042f6988eca25a2d0e95e7b38a8a4009042c49c8263",
          "sha1": "f3880debb2ebbd4deee0b86a181b4042ffac6e36",
          "md5": "211ea5b6a3cc99af4e87326b36bcabfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-0.1.0.jar",
          "url": "antibytes-dependency-0.1.0.jar",
          "size": 19139,
          "sha512": "56d2531d479af7314ca4fa64435cfcce403909e3bddcd07afdfe437a6677e712080c12bd414da786b23521efc427c44d71ef5142ea42097c70f11a07ad6f0853",
          "sha256": "4debbcd0ba440a0c41b11042f6988eca25a2d0e95e7b38a8a4009042c49c8263",
          "sha1": "f3880debb2ebbd4deee0b86a181b4042ffac6e36",
          "md5": "211ea5b6a3cc99af4e87326b36bcabfb"
        }
      ]
    }
  ]
}
