{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "1bd62e52918b88eccb95149c20fe280aae63dc8682c728fd2eb38df61ffa27edc7c5bce90a25e824fe720f16870366f0fcec9a9cb5d7bd5a3ea6d019a68af8d3",
          "sha256": "89392bbb03126ce5a686509479486ceacb7209bdd11aa22d6490b3c35540d852",
          "sha1": "318da9ebf326c002f355d25e1565418b99738506",
          "md5": "2618ef9792a13614c92cfb6e5d16b07f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "1bd62e52918b88eccb95149c20fe280aae63dc8682c728fd2eb38df61ffa27edc7c5bce90a25e824fe720f16870366f0fcec9a9cb5d7bd5a3ea6d019a68af8d3",
          "sha256": "89392bbb03126ce5a686509479486ceacb7209bdd11aa22d6490b3c35540d852",
          "sha1": "318da9ebf326c002f355d25e1565418b99738506",
          "md5": "2618ef9792a13614c92cfb6e5d16b07f"
        }
      ]
    }
  ]
}
