{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "c1dc15c4ea1b700fb65c59f97f7c915475575fe61cfdb85666fa744b79aba02ce231e3cd7c32dfe0654a2cf12a5d33af8e562a59cc7282532250ababb8a9f59e",
          "sha256": "ae04af8fb611b4103723b371b706c3d88f68c208d52854b7ce83086d46b0e04a",
          "sha1": "3db347070051dc44bd4c63df0854bf77b76d088c",
          "md5": "2f4c7852e239548429ad510e2d42272a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc01-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "c1dc15c4ea1b700fb65c59f97f7c915475575fe61cfdb85666fa744b79aba02ce231e3cd7c32dfe0654a2cf12a5d33af8e562a59cc7282532250ababb8a9f59e",
          "sha256": "ae04af8fb611b4103723b371b706c3d88f68c208d52854b7ce83086d46b0e04a",
          "sha1": "3db347070051dc44bd4c63df0854bf77b76d088c",
          "md5": "2f4c7852e239548429ad510e2d42272a"
        }
      ]
    }
  ]
}
