{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.2-SNAPSHOT/kmock-0.2.2-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.2-SNAPSHOT.klib",
          "url": "kmock-js-0.2.2-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "dd9da7f62ea2e2b9876d2e51a1f2fb741436d2f85e7b37d47836a72024f426bff5577fab7261d72d745885f331a65d640b35cadeedf14c5dcfae20ca9aa78e7f",
          "sha256": "16431f1fe30534aa8bd66c9e2f3375f72399c989447af15528a57968b575689e",
          "sha1": "1ea2f938da2d0b93f761e5c714bbf20bdd620ee3",
          "md5": "fd888b1c547dd4e7e22f5b6413b19da4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.2-SNAPSHOT.klib",
          "url": "kmock-js-0.2.2-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "dd9da7f62ea2e2b9876d2e51a1f2fb741436d2f85e7b37d47836a72024f426bff5577fab7261d72d745885f331a65d640b35cadeedf14c5dcfae20ca9aa78e7f",
          "sha256": "16431f1fe30534aa8bd66c9e2f3375f72399c989447af15528a57968b575689e",
          "sha1": "1ea2f938da2d0b93f761e5c714bbf20bdd620ee3",
          "md5": "fd888b1c547dd4e7e22f5b6413b19da4"
        }
      ]
    }
  ]
}
