{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit5-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosx64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 7069,
          "sha512": "d1d1117c451c6786d37528b8a21cefd98abee62c2eb31e1fe4a60270713fceb50ff4f5815f30d42a3d9becbc956dc683bca142214c5755e3bdc4d738d05b443f",
          "sha256": "672d9b11beb19e1233df5088963e759ab93d97ab004a4e1dd483961f5feba247",
          "sha1": "05f3b5b614824e3a2eb67a5f7d7b89662d267b63",
          "md5": "a45c9569803132ede8e6cc99b8f05a39"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b888f9257b030397b937523f643854ec98f820c9f8afb7e8b03bf52d564494349a5d3e567781833abebb8518948e9d0329eb906acd05534f413d542d4969971f",
          "sha256": "6f4785de7793d2f0e17979460f3767804d9a8a87361ae348a0f95a546f3fb01c",
          "sha1": "49951c4ba7fa06e79c35867439c049625f933fe9",
          "md5": "5d8a14c7053b8c153a37ee2dd90cc564"
        }
      ]
    }
  ]
}
