{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9ea4b3d-change-fixture-SNAPSHOT/test-utils-9ea4b3d-change-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9ea4b3d-change-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-9ea4b3d-change-fixture-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "1787fc3d9a39bbf40f76d0319c3d051719815489dc2b600949885c545da546125dda8d1b69ae32101bfa9c2a2b66e1e3d4fdc802f4fa66da1bd3119d1f76d36f",
          "sha256": "b8e929d9308b2bd340dd07799b07e866491626c076a7c19a17ce01e69dc729b1",
          "sha1": "555d7e84751ed0c770006b31644db0f39b14b549",
          "md5": "ebb546f2a6e5d929d90af8b5e32a7d70"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-9ea4b3d-change-fixture-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "1787fc3d9a39bbf40f76d0319c3d051719815489dc2b600949885c545da546125dda8d1b69ae32101bfa9c2a2b66e1e3d4fdc802f4fa66da1bd3119d1f76d36f",
          "sha256": "b8e929d9308b2bd340dd07799b07e866491626c076a7c19a17ce01e69dc729b1",
          "sha1": "555d7e84751ed0c770006b31644db0f39b14b549",
          "md5": "ebb546f2a6e5d929d90af8b5e32a7d70"
        }
      ]
    }
  ]
}
