{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/df500e4-change-docs-SNAPSHOT/test-utils-resourceloader-df500e4-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-df500e4-change-docs-SNAPSHOT.klib",
          "size": 12865,
          "sha512": "d4354a16ff4e7f671a885afb5bd50aa493618e58eb624522b6443a3e88c75c55809c4c7926e37e528f7ee3db77798347c8dfa0f0dfe19972f3324d577ca388db",
          "sha256": "34d19a0a80dbb12e2b11109e11dc0627ee8514043a2e6e69b536b6dfd94e211a",
          "sha1": "52b6a8fdf6b799f09150e4e5169200bdd7f836c4",
          "md5": "bf93c70f016dce7067f84b5922b6e864"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a53e57de4dcd208ab41b8d1d3dc8565b94ca7ec7991dfcd9066587bedbb1f9af1cec3cb47e3e08d26f8d7b6b36940678bd1ed0ac5ed25e60e4caf0f3e0c08390",
          "sha256": "30dd4f13ee3359a6498afec65efd18f4fd5ba386bcaa4d1373d92fce5bd2a730",
          "sha1": "68b044e1441c70ae43c8b1230be86795bf4e36d1",
          "md5": "048aace9fa336488c0bbeb2308d7101a"
        }
      ]
    }
  ]
}
