{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-settings-SNAPSHOT/ktx-datetime-0.4.0-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-settings-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT.klib",
          "size": 34735,
          "sha512": "7cfd92b026de0784530e54ec149bc4151bed98cd358e27c88a1605cb1a39f879fcbefb6dadd1e83fbde39654020f7c341906bd5c92618919b7cf936656ed5d5f",
          "sha256": "6016ede928cb105c7982af27ae9f49bbaacd82b78c002ef08d130d1eda03b380",
          "sha1": "e7d253954bc0e09e4897ccc551a850e9e788238d",
          "md5": "ba43fcbef624e7375b94f6ec0fa39365"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-settings-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a4b19fb7d513c4a36828ce9a5091e222d9b0fefd7d7a029700bbd818b253456c41f5f37da37a8d96d4cc5d853e05113c8e89c4983bb5ce4e962392797fbeadba",
          "sha256": "70f09f23778a113eee5b7d3e821c6f269e2ae0d0fad5648eda456ed2b4c8fad7",
          "sha1": "2cc1214584b1e858a0d38ebae6600ca222ce1a8b",
          "md5": "32e047e14d975184d6c5f745a57db730"
        }
      ]
    }
  ]
}
