{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c8e7c91-change-workflows-SNAPSHOT/test-utils-ktor-c8e7c91-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c8e7c91-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT.klib",
          "size": 15112,
          "sha512": "f6806f23abd2aa4b59e085a314019581c11a0261c20c1c72efcc189d6e717907ba9b0a368f76813b329bba41404de8f1297be6f879ff788754a6811b99cb181e",
          "sha256": "7864dbddda6682a12e2792d772d1dfc7fe0c401877f4be31cd7772779b5a7e88",
          "sha1": "d91df1894222c777a76efd4e94a09639bd32f957",
          "md5": "a66e376179d5e04d270847e48eba3bcb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fa83cbaeb64195661ed9364003a8d9196bef2e84dd6e549867a064c4da5086cdaa07854f46f2666d6cd5c40a0caa8b637707a3fab494dcd6477e89f9593ea43d",
          "sha256": "883c9ccd6d355f1652d3a36e57ad483dd26ecd82b5127998cb372cff336fdc13",
          "sha1": "8e43dc157ead68684b91b812581aa363bf101273",
          "md5": "8305ce30d46c92acd3e8debb36784aba"
        }
      ]
    }
  ]
}
