{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "d511f16-change-branching",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-d511f16-change-branching.jar",
          "url": "antibytes-dependency-node-d511f16-change-branching.jar",
          "size": 21501,
          "sha512": "96780b416bcfd994f7f9858366f2663f37e32f414fcf941cdb02cffc34cb01e8abf6c427f2e33757c0d70cce76e8d00901166c88fb01e69704b64ff7cca10a22",
          "sha256": "5a69f878fa46193faa57002606d64d3ee41724b5660bf21461254115d572ca2f",
          "sha1": "68c7c5dbb0e356e5357f5759fa0e7666ffdad702",
          "md5": "b54fb4ea180930378770881706746100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-d511f16-change-branching.jar",
          "url": "antibytes-dependency-node-d511f16-change-branching.jar",
          "size": 21501,
          "sha512": "96780b416bcfd994f7f9858366f2663f37e32f414fcf941cdb02cffc34cb01e8abf6c427f2e33757c0d70cce76e8d00901166c88fb01e69704b64ff7cca10a22",
          "sha256": "5a69f878fa46193faa57002606d64d3ee41724b5660bf21461254115d572ca2f",
          "sha1": "68c7c5dbb0e356e5357f5759fa0e7666ffdad702",
          "md5": "b54fb4ea180930378770881706746100"
        }
      ]
    }
  ]
}
