{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "d1fdb04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-d1fdb04.jar",
          "url": "antibytes-dependency-d1fdb04.jar",
          "size": 19257,
          "sha512": "1c8e31f04fa18475bbe92ee11b1c9eebe6066db293685093a05cddd6cd8630d858cd0e1eb3a542202ae864ea96d7b451bda97f851c38429171e2e7b1e1c3fcb0",
          "sha256": "4d084ea05aa76fcb69ffb8967721fe89e924a19a18527e95e6fb5a39abcece2f",
          "sha1": "90c8bc794e77fbbfe50a0f4cf27a212d5b5e1a17",
          "md5": "86290f1b209b4dc7c5acd838d2accbf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-d1fdb04.jar",
          "url": "antibytes-dependency-d1fdb04.jar",
          "size": 19257,
          "sha512": "1c8e31f04fa18475bbe92ee11b1c9eebe6066db293685093a05cddd6cd8630d858cd0e1eb3a542202ae864ea96d7b451bda97f851c38429171e2e7b1e1c3fcb0",
          "sha256": "4d084ea05aa76fcb69ffb8967721fe89e924a19a18527e95e6fb5a39abcece2f",
          "sha1": "90c8bc794e77fbbfe50a0f4cf27a212d5b5e1a17",
          "md5": "86290f1b209b4dc7c5acd838d2accbf4"
        }
      ]
    }
  ]
}
