{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/b05233c-change-write-preference-SNAPSHOT/kmock-b05233c-change-write-preference-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "b05233c-change-write-preference-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b05233c-change-write-preference-SNAPSHOT.klib",
          "url": "kmock-js-b05233c-change-write-preference-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "de40df6c3b32eb3de1fc859fd0d5b08368add9a3228e0a6dfe6445dc83ea360cdbdee192e674a777d0aec9824c09cc32e276a60748860804eccf9d31d0997472",
          "sha256": "2ffbc8fa7405a1bf77a58e6d040967ac19a914a3f342431ee766daa5c8463256",
          "sha1": "2d191fb8e0f284c3e705523b54368bab6bfe15b1",
          "md5": "c50a2fd0ea99b36189db9205749e07d6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-b05233c-change-write-preference-SNAPSHOT.klib",
          "url": "kmock-js-b05233c-change-write-preference-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "de40df6c3b32eb3de1fc859fd0d5b08368add9a3228e0a6dfe6445dc83ea360cdbdee192e674a777d0aec9824c09cc32e276a60748860804eccf9d31d0997472",
          "sha256": "2ffbc8fa7405a1bf77a58e6d040967ac19a914a3f342431ee766daa5c8463256",
          "sha1": "2d191fb8e0f284c3e705523b54368bab6bfe15b1",
          "md5": "c50a2fd0ea99b36189db9205749e07d6"
        }
      ]
    }
  ]
}
