{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-setup-SNAPSHOT/ktx-datetime-0.4.0-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchosarm32-0.4.0-bump-setup-SNAPSHOT.klib",
          "size": 34685,
          "sha512": "94c61cdb8193334beeb782eea0f2b046e68fd47b7e83e6b180ecd3321d9d79c48d1b88f8f24827837dfef5c1f3553134124cec2b09f84f984382cf7dabca85ed",
          "sha256": "83ec2ab78faeaf110e8404029968de74955ca5290448b6079724e57889e07a86",
          "sha1": "e7a1be6b76f56b799fa98970413f672269e76bac",
          "md5": "7c4bc7ee450b45f6ede02fe4d30a771c"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchosarm32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchosarm32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "eb92feb1f8f526c663cda33c8ada0dbb9b944b68f6d438d667dd6a81b41b0c50bc6d8d60151f8b7354f2e4937cfdf5cbddbb237e258cbfbaf13a2d85236488be",
          "sha256": "5dfb06b00a21a6f82ab0e7775273a62327a414c1e7314124b51ee70572a46c1c",
          "sha1": "c08526b51bb99586156b7c0e961428d276abd9d6",
          "md5": "2518d5428ddd3d802a8bbdfb4588be4b"
        }
      ]
    }
  ]
}
