{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/9c0b60b-bump-updates-SNAPSHOT/kmock-9c0b60b-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "9c0b60b-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-9c0b60b-bump-updates-SNAPSHOT.klib",
          "url": "kmock-js-9c0b60b-bump-updates-SNAPSHOT.klib",
          "size": 85736,
          "sha512": "418ce6f9af3aa5c485bbd29c7f493d20a26705dd340b49c1ef45473ecb4d84f68663a1e839f68fe89fb29ff1fb81afce95dfb140477998ce9a401ae792dab658",
          "sha256": "0d283c6e4f9f177a6403218317537b44bff444064c4a0cc622db29bd64b0522b",
          "sha1": "20bc3ab514f1a4ee88aa81988594af109615db82",
          "md5": "adae38058630c700f3638981e5c40b91"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-9c0b60b-bump-updates-SNAPSHOT.klib",
          "url": "kmock-js-9c0b60b-bump-updates-SNAPSHOT.klib",
          "size": 85736,
          "sha512": "418ce6f9af3aa5c485bbd29c7f493d20a26705dd340b49c1ef45473ecb4d84f68663a1e839f68fe89fb29ff1fb81afce95dfb140477998ce9a401ae792dab658",
          "sha256": "0d283c6e4f9f177a6403218317537b44bff444064c4a0cc622db29bd64b0522b",
          "sha1": "20bc3ab514f1a4ee88aa81988594af109615db82",
          "md5": "adae38058630c700f3638981e5c40b91"
        }
      ]
    }
  ]
}
