{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/834cb6f-bump-updates-SNAPSHOT/test-utils-ktor-834cb6f-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "834cb6f-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-834cb6f-bump-updates-SNAPSHOT.klib",
          "size": 15007,
          "sha512": "a8574551127dbecb2bb4acee1f464294509288aaaf68535e0794384177dc2c8435e6725a8b5a182b9f97b376bec5e18f7530d862f2c7dc017f372bb29e70e3e0",
          "sha256": "05cac543827738cab25c67e8b839835581979b34f216c0359407fba6fd0cb94d",
          "sha1": "174d7fe0cd56bcdda3c1610721bd97b430b89c7f",
          "md5": "db0f2441cc04230badc5fd971584edbc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-834cb6f-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosx64-834cb6f-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cbb591637c104052a578bd75fc60f6b9c5fa9134b27aabe90e91c9250e2a355039ff0a2eb4c18719c3dc5baac7e1300ceda47d9607f6bef337eae8b4e1100091",
          "sha256": "94fd7204c9f80b898de75f8a502b48ec74d7683d971bb8b5b28955b041d5074f",
          "sha1": "fa5c30b1e58f9c64b8710f169f7a24897c624280",
          "md5": "af223ffa13a1fd371697e9572695c80b"
        }
      ]
    }
  ]
}
