{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-add-custom-shared-annotation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-add-custom-shared-annotation-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-add-custom-shared-annotation-SNAPSHOT.jar",
          "size": 173203,
          "sha512": "f9990befeb679a0a6fee05d654f74b7d7ee05ebe44cca071d2fd4cfff880b94841106802ad0969443d876475937afbb2064d8f8c9d17bca3bb0f90b3b1d62012",
          "sha256": "76ce781d8246354851b43f8101194b5c59307d92ee8559a6dd89a070fb7dc00e",
          "sha1": "f154853536c96378713f117c885e0ee4a00eac12",
          "md5": "05b6ad8fce22ec9686b232e3697743bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-add-custom-shared-annotation-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-add-custom-shared-annotation-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-add-custom-shared-annotation-SNAPSHOT.jar",
          "size": 173203,
          "sha512": "f9990befeb679a0a6fee05d654f74b7d7ee05ebe44cca071d2fd4cfff880b94841106802ad0969443d876475937afbb2064d8f8c9d17bca3bb0f90b3b1d62012",
          "sha256": "76ce781d8246354851b43f8101194b5c59307d92ee8559a6dd89a070fb7dc00e",
          "sha1": "f154853536c96378713f117c885e0ee4a00eac12",
          "md5": "05b6ad8fce22ec9686b232e3697743bd"
        }
      ]
    }
  ]
}
