{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "46427ea-add-shared-detekt-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "8a50758697777b0a5990b1235c2822dcdcec1e9be99943cb17bab6866ed58a3e272f6cfaf872d3ad3b568cc2623f49e2b136686bfeb28f1975493a9e02134dba",
          "sha256": "49c381275cf697a335d159d5ead1d3050c6b270b08449c7e69f6301957519265",
          "sha1": "4626df10f784b72583b07fa9fc721d1f383ce85a",
          "md5": "beeffab14ee0beaa0d4f03492df43749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "8a50758697777b0a5990b1235c2822dcdcec1e9be99943cb17bab6866ed58a3e272f6cfaf872d3ad3b568cc2623f49e2b136686bfeb28f1975493a9e02134dba",
          "sha256": "49c381275cf697a335d159d5ead1d3050c6b270b08449c7e69f6301957519265",
          "sha1": "4626df10f784b72583b07fa9fc721d1f383ce85a",
          "md5": "beeffab14ee0beaa0d4f03492df43749"
        }
      ]
    }
  ]
}
