{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-badges-SNAPSHOT/ktx-datetime-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-fix-badges-SNAPSHOT.klib",
          "size": 34771,
          "sha512": "9b1fe07b269d9ea4d185c68f78b05e521499eb2e2f24db7851b916514ec3b03b689b6e66e7fd48c9e415455ec007d0ac58f2fd33261239404a1074ee06d52475",
          "sha256": "d3d83e53eda6ea43a28b421416571449556a9dc6a3d518dec3c682d818538b8f",
          "sha1": "0389f39205938a0a108ef4639584204f021ed42c",
          "md5": "f48f217a993871b8c5043787c1d59601"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "505497fb9638cb5de9b81b1dcc0df05d5d328281138206bc81af7af4886a7092b07f05ca3064ef28113072a1bba43a17daf6fad012b1f83a6947b82be0f12198",
          "sha256": "eb56e88790fffce5ca0f2e6814d4ba19d2a55f51217e711f6ede3b5c836210c2",
          "sha1": "e712aa3399f2d370dd85c7ae03ccb6a6ae241756",
          "md5": "d863a77904552af4e601240cd3e4a080"
        }
      ]
    }
  ]
}
