{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "c45a6cd-add-proxy-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-c45a6cd-add-proxy-factory-SNAPSHOT.jar",
          "url": "kmock-c45a6cd-add-proxy-factory-SNAPSHOT.jar",
          "size": 23639,
          "sha512": "9cc1b6c6ae04b7521227e602909bad88bc4ee22c30f5888a5fa44b8eb53d90327e85673b64fce17ebb49e32517a2757cc628c242dc7011dd7c9f59e4a7edfed7",
          "sha256": "d404b2e3376629a932a3a8fea6a5d36476ac344b335fff5304219982c4e04bc6",
          "sha1": "0c37d01e35656d0e20646878cc8767bdf714efd6",
          "md5": "4a4c185241d83db122e5349060eb6a58"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-android-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-android-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-iosarm64-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-iosx64-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-js-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-js-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-jvm-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-jvm-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/c45a6cd-add-proxy-factory-SNAPSHOT/kmock-linuxx64-c45a6cd-add-proxy-factory-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "c45a6cd-add-proxy-factory-SNAPSHOT"
      }
    }
  ]
}
