{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-settings-SNAPSHOT/core-0.4.0-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT.klib",
          "size": 105923,
          "sha512": "f201b335872042436de1ab78e34e9d457a26deb6796f4830318a8f88e93825876284e4e9c59ee2e6672026494e4fc1c15a6d4af9ceae9a27aea40ba32bd2875c",
          "sha256": "9c7a60ba522a6fc2c7595c62f18e9bc937ae555afef5219a86ece7c357a96c43",
          "sha1": "7a04126c30738c5072e1940d17c2192c810366a2",
          "md5": "097fd14063df40d2c8b4e1e3edd9f883"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.4.0-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1bee58543f48c886268b38b8aace5922dc949b45152fe3fd37e61a75e811cb4f14143eb61f35516f3396ded3ab05cdbedd3dfd0ead598717c064fd373f553a9f",
          "sha256": "6e52301d5e19a49ae79c09df02cd94c8d5ffb56d636403d102597aac3544f923",
          "sha1": "762fc08cba1f6a926a95a6ef70f76ae1e49f2e7e",
          "md5": "c517f10c5a8641bfa4234a2546f4d925"
        }
      ]
    }
  ]
}
