{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-change-labler-SNAPSHOT/ktx-datetime-0.3.1-change-labler-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-change-labler-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-change-labler-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-change-labler-SNAPSHOT.klib",
          "size": 34785,
          "sha512": "8f0b1a31f3112809e249c830ea7dc505cd979b549c66f799f854a8c005e456b87cb265a5642b64c9090441f96a1dc355070b088c49f54bb31ee8fe6de75689a6",
          "sha256": "f1a3d0355c51be80e881bd041a1cbb722f80aabcf457e03d3d141b141ce99a23",
          "sha1": "98d8873bffae3b4f6f3e1f2920f94408a0d4de20",
          "md5": "e73173220ddfd62b626eeec87f235a82"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-change-labler-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.3.1-change-labler-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-change-labler-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5d8a6fc851ba6dd5b3a353e7dffbf8122d82d12dced9f045da39eb41cae036a85cd3cc8f2ca3b9ba36504c644df10cc68822296e655b75a606d0db11f6b51809",
          "sha256": "54d2cda557ec88a8160a73241b144035cca71929060ac26cdc7da2413b33c397",
          "sha1": "9e2a265686eebbe7eb22f372a5d4b1f7be4f204e",
          "md5": "8bcddebec5eced1ee5df254b9448c199"
        }
      ]
    }
  ]
}
