{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/ef3a5b1-bump-updates-SNAPSHOT/test-utils-annotations-junit5-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosarm64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 7094,
          "sha512": "6ae0680d1749e7fd9de17e93539689d95be94076a6e020207b342017ba0cea3fe2f3ee48c68d08661533bcba67fa9956914d1c54c73d31f4d135a7e4cc72a782",
          "sha256": "8b41c3037bd7f3e224174fe513688db280cbdd76e269e8e85b3fec38218b2738",
          "sha1": "a589bd0771921fa46d7f0aad89bf57e1c808517c",
          "md5": "d1b39009a380cb764eb7379cb0901710"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-annotations-junit5-macosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-macosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3d09021b4910b1d99a92975b1ec307ba94ba4be9fda2f8d74d65c224240504c1dd100e62ca93fba2eb29facdc61428abe3486eaa8e2431f380e8d54bca710fee",
          "sha256": "425a3d5133bae431673328053fcd35e3d9cff3e53a7377c6a1b6a983a743d610",
          "sha1": "ba3b77da602e1df035cdd1a70469355f35924fa5",
          "md5": "f2b2659f28031947cae3de969087e5b6"
        }
      ]
    }
  ]
}
