{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-periods-SNAPSHOT/core-0.3.1-add-periods-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-periods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.3.1-add-periods-SNAPSHOT.klib",
          "size": 108829,
          "sha512": "7d811eff0759a4d260b0cf257241e6b52a753cc5ec1a0f00bc44d6de93ae1d89a42f05c99671496f63f8b4bda5cd802f7d09d83d20ed243057b3d25a7e9a224a",
          "sha256": "99d08225dbbbf368eac5bc45c93aa9a6bce411c152c88bd1b5fb05feb1d70dd5",
          "sha1": "93c05895db28779411dfef77443bf2937c71a194",
          "md5": "e437e8ff027c12dc7664e8332a637d76"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.3.1-add-periods-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8ef089c13e702f796c79103da8a445e8649b4f708cea26a9aec29c527bffeb9b721a2e90ed2fb12559d1de0cc24428bb03538fbcc7957f0c984b963e76a9abac",
          "sha256": "74989188c868cb73b781d94140b1bf39c8e7c20c271d753805493368e94097e0",
          "sha1": "e30a0900c40276e723cdf2b3aa8010f752051573",
          "md5": "f78d955640188264117d203ec803231f"
        }
      ]
    }
  ]
}
