{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9cb77b2-bump-updates-SNAPSHOT/test-utils-9cb77b2-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9cb77b2-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-9cb77b2-bump-updates-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "b6498a1b4bf698827c4c5425ec73b2442349c3e8c99bcced1b5df6b94433043234d5c5b219dcd4cd6d5037e341c8e65b07b5ee0e60c6d7880a1ff062224cd1de",
          "sha256": "5bffe6ce9e4bd1efa7d07a374dc02d1b9e4385d7f566b269e73001b6bb23d901",
          "sha1": "aafb732ba7037e2725843c371d42a9a826c1a123",
          "md5": "eda4b1546940b21ba07dd7241d111efa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-9cb77b2-bump-updates-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "b6498a1b4bf698827c4c5425ec73b2442349c3e8c99bcced1b5df6b94433043234d5c5b219dcd4cd6d5037e341c8e65b07b5ee0e60c6d7880a1ff062224cd1de",
          "sha256": "5bffe6ce9e4bd1efa7d07a374dc02d1b9e4385d7f566b269e73001b6bb23d901",
          "sha1": "aafb732ba7037e2725843c371d42a9a826c1a123",
          "md5": "eda4b1546940b21ba07dd7241d111efa"
        }
      ]
    }
  ]
}
