{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "0fd7252-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-metadata-0fd7252-change-project-setup-SNAPSHOT-all.jar",
          "url": "test-utils-resourceloader-0fd7252-change-project-setup-SNAPSHOT-all.jar",
          "size": 10390,
          "sha512": "2b0db24d3d686d15c6736250f48d9c2e0548ac786c56f8f3bcfdadd13293d94771ceff77f17f3fa58a42190ce9a8d2f3802e6d027f009f59339bdbc80d63f4ac",
          "sha256": "ecf661704b723cba328a9e9e58d255ce1e1ce62dd77c51497e9c7a48f381a204",
          "sha1": "e2096ba02d49e2618ee06901d5dc017ad4bcf8d9",
          "md5": "662c97f889dd1f244bdade1e5238f7ac"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-0fd7252-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-0fd7252-change-project-setup-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "e07d35275ef2babfdedf6ad8e8a0cac533275fe2f9d59bf7531832c62c07eccc04e3b8988bb0e3795cda8ee476cbdee718513a399bc0f7ef35c3ce77e3ab109d",
          "sha256": "ad037fe7fab4229d3d0daa88c4e897bf04c81671dd1ab6f17b1094cad009811e",
          "sha1": "161007fd4902b610713519e4cfffd559b9d6271c",
          "md5": "66b35b96bd4dba420f81f2a4f2becfed"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-android-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-android-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iosarm64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iosarm64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iosx64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-iosx64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-jvm-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-jvm-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxx64/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-linuxx64-0fd7252-change-project-setup-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxx64",
        "version": "0fd7252-change-project-setup-SNAPSHOT"
      }
    }
  ]
}
