{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/205f7d8-fix-assertions-SNAPSHOT/test-utils-annotations-205f7d8-fix-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "205f7d8-fix-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "d9ec6e34333134b3d8fe7424b80c71eb96859445a1556dd416324fd8204d6c8d02667fbc2af86bf537a457f4290b1762af8274295c7b9bf252a130cc847735e4",
          "sha256": "c99e449eac4cf7c77e342e6f99a4c0cc99e1b16a2796a54493572253ea7f8ca3",
          "sha1": "a12bd05a7507298022d6379226532a0ca5fdac01",
          "md5": "43abd0d6dfde439b01e4d23fd23fa98a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "d9ec6e34333134b3d8fe7424b80c71eb96859445a1556dd416324fd8204d6c8d02667fbc2af86bf537a457f4290b1762af8274295c7b9bf252a130cc847735e4",
          "sha256": "c99e449eac4cf7c77e342e6f99a4c0cc99e1b16a2796a54493572253ea7f8ca3",
          "sha1": "a12bd05a7507298022d6379226532a0ca5fdac01",
          "md5": "43abd0d6dfde439b01e4d23fd23fa98a"
        }
      ]
    }
  ]
}
