{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "c7440c6-update-detekt-setting",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-c7440c6-update-detekt-setting.jar",
          "url": "antibytes-dependency-helper-c7440c6-update-detekt-setting.jar",
          "size": 69711,
          "sha512": "fc7a8d5162189c61fdef4df02f61c9833639f0a432df499ed88f0f359bc463fae56599f0c8378e5b8e1cf73fe6b215e3918b786226ced36e6605791f84f00600",
          "sha256": "2d2567096f03670ed85583ec0c7d48e5210976abb8ccd704eefd285541442371",
          "sha1": "419840b5c9917cabe1605c5b9ce11f0f21666d37",
          "md5": "27a86bbb185d9851ef1e186b8d191216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.49.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c7440c6-update-detekt-setting"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-c7440c6-update-detekt-setting.jar",
          "url": "antibytes-dependency-helper-c7440c6-update-detekt-setting.jar",
          "size": 69711,
          "sha512": "fc7a8d5162189c61fdef4df02f61c9833639f0a432df499ed88f0f359bc463fae56599f0c8378e5b8e1cf73fe6b215e3918b786226ced36e6605791f84f00600",
          "sha256": "2d2567096f03670ed85583ec0c7d48e5210976abb8ccd704eefd285541442371",
          "sha1": "419840b5c9917cabe1605c5b9ce11f0f21666d37",
          "md5": "27a86bbb185d9851ef1e186b8d191216"
        }
      ]
    }
  ]
}
