{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/0f449ed-change-fixture-SNAPSHOT/test-utils-fixture-0f449ed-change-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "0f449ed-change-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-0f449ed-change-fixture-SNAPSHOT.jar",
          "size": 41804,
          "sha512": "db2251b222de76c0fa6bf570fb9d021e9367abdc1bee71e00ebdb7a409b4665f427cdaac5a6ce185e343621b47964c1e484256bad85305ec6b5e12f58ab280a0",
          "sha256": "74a7f69d09c837e44b5029eeda931f6a8099bc72f8640bf45299715153fd06d5",
          "sha1": "6d4e6b5e6617616acf46e2c6a6a4bddab7b8e086",
          "md5": "dcd5717d5bf8c5e63226157b34809c40"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-0f449ed-change-fixture-SNAPSHOT.jar",
          "size": 41804,
          "sha512": "db2251b222de76c0fa6bf570fb9d021e9367abdc1bee71e00ebdb7a409b4665f427cdaac5a6ce185e343621b47964c1e484256bad85305ec6b5e12f58ab280a0",
          "sha256": "74a7f69d09c837e44b5029eeda931f6a8099bc72f8640bf45299715153fd06d5",
          "sha1": "6d4e6b5e6617616acf46e2c6a6a4bddab7b8e086",
          "md5": "dcd5717d5bf8c5e63226157b34809c40"
        }
      ]
    }
  ]
}
