{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/59ae807-change-publishing-SNAPSHOT/fixture-59ae807-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "59ae807-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iossimulatorarm64-59ae807-change-publishing-SNAPSHOT.klib",
          "size": 47247,
          "sha512": "aa5d524afdd908d6c9182c925df7201b66f8edba496adccaec1e0d96b178cd2fce267295da6d65b72f6a8debbefd93d1dace85e513d34c437f0f7e5648981cd0",
          "sha256": "14626b367ae0358a13c8e4956727af1640b699ce4f4cb5aea7b1fac28e49e138",
          "sha1": "81d21ecc0266a869500a14e3396d1fcd83b10e1b",
          "md5": "6e0f91ba4ea675761f1e237c7e50db52"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iossimulatorarm64-59ae807-change-publishing-SNAPSHOT-metadata.jar",
          "url": "fixture-iossimulatorarm64-59ae807-change-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d26791e35dbf4f780f34fa65970d15763a46452e3d0fedfe234e4481f9e10b975006d2b8abf20214fed9428c70c1611498fde5355580ee6eb0b8419c2030a407",
          "sha256": "2d292f6309347d4534e525c36025d7130e37cc933ec885eeb47ad8703899f684",
          "sha1": "a83418481cccb0b1da67d6415aaef83c112fcc87",
          "md5": "0c94c57da1b85de7e2b96b91e7c902e1"
        }
      ]
    }
  ]
}
