{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/30769ee-change-setup-SNAPSHOT/test-utils-annotations-junit4-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosx64-30769ee-change-setup-SNAPSHOT.klib",
          "size": 11335,
          "sha512": "a2b53caf68a6238f48cb4582555a79eb50d91dc842aa7c144782c1901b31ce7f9bf0d6b81e791a8ff23dd068e3bf2897198e58f008a6bb58779d8995c89dc042",
          "sha256": "0c0bd6ef30e191d9933583a320776bb991623922170cba30ae14477f3e3c90d7",
          "sha1": "c9d01ac9add1320a06ea845bb74746a10fbf870b",
          "md5": "123085bdd3e3489ec2d5e3886fd3710f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosx64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosx64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cd7df0153c66e065c7272b228aed5233520b23e854449a8cfdf89cc08fba7b5812166810301cd1ae5d1bff0831fb720d30fafb50fbc58b277ae9391ad095b44d",
          "sha256": "4eb2b44598be65cc0223dcdd66eef39298eec95d5b7e6120512a273d943213f8",
          "sha1": "9158f0e198beae533250b84a1cd4b3d7c24033e7",
          "md5": "e1bd473234630ea2cfb38f41e08a518b"
        }
      ]
    }
  ]
}
