{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "f93098e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-f93098e.jar",
          "url": "antibytes-grammar-tools-f93098e.jar",
          "size": 39373,
          "sha512": "7f54151ad3bc6709d0bc4d4caa173b9ffa1092985985e4e5e62c0d79df72c3240de714550c8593b340084a8d2518ad739fc6e50ce7b479fd0a7cc22fa7cf4110",
          "sha256": "9b17ea7765460246f6a84d65aa79a6a2ab6c6377b632acccaedffe3879147905",
          "sha1": "71afb7f5172f89e676f8c783ba8103341c2457e6",
          "md5": "aa958b197222b882bacdf2d3ad47aee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-f93098e.jar",
          "url": "antibytes-grammar-tools-f93098e.jar",
          "size": 39373,
          "sha512": "7f54151ad3bc6709d0bc4d4caa173b9ffa1092985985e4e5e62c0d79df72c3240de714550c8593b340084a8d2518ad739fc6e50ce7b479fd0a7cc22fa7cf4110",
          "sha256": "9b17ea7765460246f6a84d65aa79a6a2ab6c6377b632acccaedffe3879147905",
          "sha1": "71afb7f5172f89e676f8c783ba8103341c2457e6",
          "md5": "aa958b197222b882bacdf2d3ad47aee9"
        }
      ]
    }
  ]
}
