{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f000bfd-bump-settings-SNAPSHOT/test-utils-ktor-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosx64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 15044,
          "sha512": "f40c8d0937811e2ace0589d2b2cf8aa6846f0f547827a2ff30b82eccea6d5b5381de71ed11e18a13258d4b7756c256a49614b3bcdd15070d25a5e9341a312fcb",
          "sha256": "92aad9ab31b909dad934e1fc085949ac651cdec0cdc40b98bbe134e1e2aa11fa",
          "sha1": "fd6bd39a296f9cfc19c1b1ea5ba165d8bd94d605",
          "md5": "69851541c7a0c862f6218c4a900cc513"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-watchosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e67125a8578deeb12cae52ef49eab4d58a0aa1d51e170dc2eb4e919660a285863ffec6e2ec9f57d0d37826be5df1621e7c1043fc8ff5b8401569f07fb1ff0546",
          "sha256": "1df2588d2171c733536d23bd3423b1ad7463aca32615f911ba8c378b1bdca904",
          "sha1": "b976dc7f556cd6cf4ce42c2cb61e44bc783d22a3",
          "md5": "711edda15d04b503bb6c86af76821b83"
        }
      ]
    }
  ]
}
