{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/e65a2ff-bump-updates-SNAPSHOT/test-utils-ktor-e65a2ff-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "e65a2ff-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-e65a2ff-bump-updates-SNAPSHOT.klib",
          "size": 14939,
          "sha512": "e071df603cf87cbee2954bd31d00c97a3dce9fcabca4a894342af60f35f8d512774fee19fb83b6206256918e51fbc52461968c02789601ab9b5195b86ab9159a",
          "sha256": "25ce97158f05a5506f2d1695fe4597718f634f156b8433c63b968fa160b95426",
          "sha1": "ade7a3d7d63fd651fa72a54c791d271ded601f0b",
          "md5": "210abe10d24509d21f6f5f6682d8b0c7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7f4377d81446606037842b044af4d87828a8e04c93735a07b55cba551fe7913a6567e6ffadd17d88e8d6b4d72b0ac15e3af3401c510071c99264d5d2789e6896",
          "sha256": "ca1600e13508561958b3e93c5c5f3193497ef5edb40a774f695fbbe156d78eb3",
          "sha1": "9db400ebebae62c2ebeea170c0dea5c89c2906c4",
          "md5": "6626417b81aeabadce916f32d001b68c"
        }
      ]
    }
  ]
}
