{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "690cdd3-change-annotation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-metadata.jar",
          "url": "test-utils-fixture-690cdd3-change-annotation-SNAPSHOT.jar",
          "size": 13804,
          "sha512": "40ef1e3c72c53b53c7cdbce9434a0726ff00bd493cf83c0f52a837f6cbc6641692b7eeb143807df6acf389f317f756a140c37e0584a206a58ea1efb497a6a2c7",
          "sha256": "875cc47f2ca9c76da384befd03a70ff6c5584e6c30d28455db3aa969c3fdcbbd",
          "sha1": "ceb37b269211303c55d654811c9ffa4c74ae63d1",
          "md5": "cd495f82cc48075ce50831a0e474afb6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/690cdd3-change-annotation-SNAPSHOT/test-utils-fixture-android-690cdd3-change-annotation-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "690cdd3-change-annotation-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/690cdd3-change-annotation-SNAPSHOT/test-utils-fixture-android-690cdd3-change-annotation-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "690cdd3-change-annotation-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/690cdd3-change-annotation-SNAPSHOT/test-utils-fixture-jvm-690cdd3-change-annotation-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "690cdd3-change-annotation-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/690cdd3-change-annotation-SNAPSHOT/test-utils-fixture-jvm-690cdd3-change-annotation-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "690cdd3-change-annotation-SNAPSHOT"
      }
    }
  ]
}
