{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "size": 14116,
          "sha512": "b3124474bf7b42d609fab5b89c361f46c0679179b846af7f0d867e132dcab0e82c1313d255d9fa75b568399098af8d612c375a7bd705ec230d70849e895f2422",
          "sha256": "06d9ebfa53ab89eab876dfcefec5d6490155342aa5f1513890ae87af01241dce",
          "sha1": "306a398a2931141838e8aaf81b681e81945506e1",
          "md5": "d57406becd2455569532717631be4e51"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6058784e63d842cf270c843e9cd44e4f96fee2c381953b2036100198e4776498edfc1fcaddbf56b4be57d39962d1e9b589f76a79cf56a9209c78278691380606",
          "sha256": "17b758394ce78c9af18bdda4c132de7152e0e9b43d9293a4dfbb9fb7b2a26242",
          "sha1": "d15836f739039fbec9751c05ee17d35ae759bf64",
          "md5": "e10bf2a3ccb90e35274f8cf837978d9c"
        }
      ]
    }
  ]
}
