{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT/kmock-0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT.klib",
          "size": 202838,
          "sha512": "6cf933b9a449621d34b702d08652cc7aa4e8afd4763549b5eecd8d0a377316cfea1d359837fc10612aef923087683e63bf496766696430db0481e97da58c9302",
          "sha256": "c54f2fc0a114e416f26a52c3a0a5cbc0973693ce5003ed2530347d8703e42246",
          "sha1": "dad56645f870e1b5d37a784ce17df81f840c3944",
          "md5": "70549751a64f22aab63da0489ac037da"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc01-fix-relaxer-a896af104e-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "50cbb130bb2033cde37caae0eaac880b1bda3117f65aac6ff12d3c6a914cb9ea19c09600d459a83b85fd3b48c6c43185e38dfd8a0bc4eac77af56b5eccedcfab",
          "sha256": "f0d9aa4e4307eb9aa47034c76531ae77632de788f7a565e2d51228059eccb032",
          "sha1": "93c4f107c2bbe5d95f64f4c08b5b0cf7613e2cc4",
          "md5": "7da86a41cf4a4dcae9e52487f7f5e1c1"
        }
      ]
    }
  ]
}
