{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "72725be",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-72725be.jar",
          "url": "antibytes-runtime-configuration-72725be.jar",
          "size": 10350,
          "sha512": "40508b2fcc38933b1b041ac90d0a21cea3180d0b03476564b541197ade7de1b2b5eef7b4dc409275ce9b8a2d3e769ef1ae1d4183be116c15b041c12f3096b38a",
          "sha256": "ea6020e30452648d6684ab9f7345b921a1ba6bbdd07524d6b32fec9083cb0015",
          "sha1": "4cd4978df9af2530847cfdc7e451b240db5e5e85",
          "md5": "c9032dee4b1c64be14f293e3096290ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "72725be"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-72725be.jar",
          "url": "antibytes-runtime-configuration-72725be.jar",
          "size": 10350,
          "sha512": "40508b2fcc38933b1b041ac90d0a21cea3180d0b03476564b541197ade7de1b2b5eef7b4dc409275ce9b8a2d3e769ef1ae1d4183be116c15b041c12f3096b38a",
          "sha256": "ea6020e30452648d6684ab9f7345b921a1ba6bbdd07524d6b32fec9083cb0015",
          "sha1": "4cd4978df9af2530847cfdc7e451b240db5e5e85",
          "md5": "c9032dee4b1c64be14f293e3096290ee"
        }
      ]
    }
  ]
}
