{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-bridge",
    "version": "72b787f-add-artifact-resolver-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "url": "antibytes-dependency-bridge-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "size": 38501,
          "sha512": "01fb1d8b1fad83adff467aa2c1094e5cfe2151a59013221586c364fb9fed33b86c54f1302d4dad6cf095ea5d929752690c179305e739230d783a38e67bf24890",
          "sha256": "00cae5439fc2111220993c1a11a0837968549f20f2138afdf0ca468e331e6a51",
          "sha1": "099ad7df90a9c07fa1d81e4e7be4030e873649e4",
          "md5": "e6ed2b5b4217ac62c08c23b02bffb42f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "url": "antibytes-dependency-bridge-72b787f-add-artifact-resolver-SNAPSHOT.jar",
          "size": 38501,
          "sha512": "01fb1d8b1fad83adff467aa2c1094e5cfe2151a59013221586c364fb9fed33b86c54f1302d4dad6cf095ea5d929752690c179305e739230d783a38e67bf24890",
          "sha256": "00cae5439fc2111220993c1a11a0837968549f20f2138afdf0ca468e331e6a51",
          "sha1": "099ad7df90a9c07fa1d81e4e7be4030e873649e4",
          "md5": "e6ed2b5b4217ac62c08c23b02bffb42f"
        }
      ]
    }
  ]
}
