{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.2.0-rc01-add-all-covered-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT.jar",
          "size": 56364,
          "sha512": "c7208e6377b76fbf4af5f905ca90c3923b6fe03f5b737b960edbedd209f437324306e933fec0d7f0c2cde698d656e01e4c2c8312d844f62d8ebd4c28b22140e3",
          "sha256": "bdc65f4b437e3362b83f30df4297de55b5e25a07b1cee500501d5a11ccc2fd9d",
          "sha1": "ac9e53374c6e1710d1088842ac6f8b866bab2d46",
          "md5": "37fa0d84bc1ed072c26cf1346217c80b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT.jar",
          "size": 56364,
          "sha512": "c7208e6377b76fbf4af5f905ca90c3923b6fe03f5b737b960edbedd209f437324306e933fec0d7f0c2cde698d656e01e4c2c8312d844f62d8ebd4c28b22140e3",
          "sha256": "bdc65f4b437e3362b83f30df4297de55b5e25a07b1cee500501d5a11ccc2fd9d",
          "sha1": "ac9e53374c6e1710d1088842ac6f8b866bab2d46",
          "md5": "37fa0d84bc1ed072c26cf1346217c80b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "675de5cbcd3b7189ab704f25b61cf08d8be1143daad54f6380c15183be667641f160435eed37b23827188633af2ac0625ca29d000ee293128bd61860986a6ce3",
          "sha256": "8610316645215de142db36f97f2d8d6638a8ee741c210e5db8f2aac5559b849d",
          "sha1": "36bf64dd52e0c7a7ccc50c5eb2bc4548d3432c7f",
          "md5": "1923720dda8c008ae89c13fd69c22752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.2.0-rc01-add-all-covered-SNAPSHOT-sources.jar",
          "size": 11775,
          "sha512": "70f56aa844f75e0832c7bbd6c209a7e016eb08c7bc5e93a29cf4e99880b83c46dc45f6fbaceb8cc94786a5e3f4d40aa9ed67bad57732c366b9d685f418a6779b",
          "sha256": "437d3311a4b1ae9c8d96c9187d9528378c147b6c2e6dcfb575cf40242aebcbdf",
          "sha1": "f6788b171c3befb3a659b86d5b0ab3909c65365d",
          "md5": "8f7eaf51c80784a358432cabcffd9ac8"
        }
      ]
    }
  ]
}
