{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/422ab00-bump-antibytes-SNAPSHOT/test-utils-fixture-422ab00-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "422ab00-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "7a6c58376cb1cbe68a92d2d7b4a9a0a6c868002180348bde9496ec35943279179ff889d75ad6f9cb88e72cc39765a0c27e6232adae654861fee5d9d04915b255",
          "sha256": "e5dce3198901909edb3b21d9fdec8080795571bef16db4bd6f21a370d2cde1ca",
          "sha1": "c829fec18e3b74bcc1b828132b4a51f0036d464f",
          "md5": "802bf35bfbf1b24111970b5bb4ded6a8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "7a6c58376cb1cbe68a92d2d7b4a9a0a6c868002180348bde9496ec35943279179ff889d75ad6f9cb88e72cc39765a0c27e6232adae654861fee5d9d04915b255",
          "sha256": "e5dce3198901909edb3b21d9fdec8080795571bef16db4bd6f21a370d2cde1ca",
          "sha1": "c829fec18e3b74bcc1b828132b4a51f0036d464f",
          "md5": "802bf35bfbf1b24111970b5bb4ded6a8"
        }
      ]
    }
  ]
}
