{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "4aeb6b5-fix-ktor-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-4aeb6b5-fix-ktor-dependencies.jar",
          "url": "antibytes-gradle-test-utils-4aeb6b5-fix-ktor-dependencies.jar",
          "size": 17255,
          "sha512": "01f3a35c9281d1e6c18df9dbf5456dfc5920f6427249699bc711da500b32cf7d96ca8e922d1071126fadd0398ff85724ac9ae0c10644347d177f7543e6b63dfd",
          "sha256": "be82aac1e3ef85daef88f68975e566a099f9269674485f2cfcb44d890c6ceb77",
          "sha1": "1e072f6dab16f5bfcdece08ec0bf20a5f20af100",
          "md5": "7f745ca67021e9efcf457663fdba4b43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-4aeb6b5-fix-ktor-dependencies.jar",
          "url": "antibytes-gradle-test-utils-4aeb6b5-fix-ktor-dependencies.jar",
          "size": 17255,
          "sha512": "01f3a35c9281d1e6c18df9dbf5456dfc5920f6427249699bc711da500b32cf7d96ca8e922d1071126fadd0398ff85724ac9ae0c10644347d177f7543e6b63dfd",
          "sha256": "be82aac1e3ef85daef88f68975e566a099f9269674485f2cfcb44d890c6ceb77",
          "sha1": "1e072f6dab16f5bfcdece08ec0bf20a5f20af100",
          "md5": "7f745ca67021e9efcf457663fdba4b43"
        }
      ]
    }
  ]
}
