{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "dbbf9a6-change-testing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-dbbf9a6-change-testing-SNAPSHOT.jar",
          "url": "antibytes-versioning-dbbf9a6-change-testing-SNAPSHOT.jar",
          "size": 16029,
          "sha512": "dd326caa5c88c1d3cce444ccf9ba8067f36fd19a6ec1f59430aa06c5716bdacfa09a246c1f6ee6dd274174a581fbc1e13801ddf399a4ef0169c9fc48f3b3c26f",
          "sha256": "68f189db5a3a02727551347b86f36dbfabb828aca80d64a303735731ed829d9f",
          "sha1": "b1033b3894a1dc77b46e1da3cfeb81b4f7c32c0f",
          "md5": "eba07a944093ccf20b41809f6617127e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-dbbf9a6-change-testing-SNAPSHOT.jar",
          "url": "antibytes-versioning-dbbf9a6-change-testing-SNAPSHOT.jar",
          "size": 16029,
          "sha512": "dd326caa5c88c1d3cce444ccf9ba8067f36fd19a6ec1f59430aa06c5716bdacfa09a246c1f6ee6dd274174a581fbc1e13801ddf399a4ef0169c9fc48f3b3c26f",
          "sha256": "68f189db5a3a02727551347b86f36dbfabb828aca80d64a303735731ed829d9f",
          "sha1": "b1033b3894a1dc77b46e1da3cfeb81b4f7c32c0f",
          "md5": "eba07a944093ccf20b41809f6617127e"
        }
      ]
    }
  ]
}
