{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/b05828c-add-ios-SNAPSHOT/test-utils-fixture-b05828c-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "b05828c-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosarm64-b05828c-add-ios-SNAPSHOT.klib",
          "size": 30393,
          "sha512": "aa6261e4e1d3c4d34c49381f62eb13a114340f6459020fef871b0eff1508e69866f2eadc76bd64003db8f107dddbb404a914be953ab3fb8ef6b45fd57b9e2459",
          "sha256": "278d8f38126a5f94f22aa3c66a05541bb7bea78049aacca96537a5d31f0830ec",
          "sha1": "21d471e65ae1e9d2bb8900f59f7aba2dcf845844",
          "md5": "2eacf37a6f4f8c88ea290a5a65c681cc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosarm64-metadata.jar",
          "url": "test-utils-fixture-iosarm64-b05828c-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "68fbf19ce9d986132d92b47df25b3d70fefbf510bc7e8a4abde4d1fa73737d2586d98dabaaefcf6052c5b5af1196dddc75aba0a99b58663317cdd012b132ef81",
          "sha256": "bc3d3ca247ad36b18309dce2166e12b7e197705763e58afa77841f4cc5486101",
          "sha1": "3326f2b39bac3ae0863db7134f2566b398d83f90",
          "md5": "679e7adbf6ac80e8f30c70cd10e182cc"
        }
      ]
    }
  ]
}
