{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/7cafd8e-add-mockery-SNAPSHOT/kmock-7cafd8e-add-mockery-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "7cafd8e-add-mockery-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-7cafd8e-add-mockery-SNAPSHOT.jar",
          "size": 114728,
          "sha512": "dc2ff3f95b4a1b26d65206077fb38c37d1e27ee48fd6fcf56bf995093a638d7b2574be4e613286fd752e4de0752817f6e31b0e5a065b0fac5f622a27a2c28999",
          "sha256": "e0b04d933c7ec246e91bb35bf1cd5defba4d95afc508d6d4269d2e7036617821",
          "sha1": "2d0529d2927f37acd18818296b2dec2f39130e60",
          "md5": "d02afeb0b7a2525107ca77c751a1115a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "753d329-add-ios-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm.jar",
          "url": "kmock-jvm-7cafd8e-add-mockery-SNAPSHOT.jar",
          "size": 114728,
          "sha512": "dc2ff3f95b4a1b26d65206077fb38c37d1e27ee48fd6fcf56bf995093a638d7b2574be4e613286fd752e4de0752817f6e31b0e5a065b0fac5f622a27a2c28999",
          "sha256": "e0b04d933c7ec246e91bb35bf1cd5defba4d95afc508d6d4269d2e7036617821",
          "sha1": "2d0529d2927f37acd18818296b2dec2f39130e60",
          "md5": "d02afeb0b7a2525107ca77c751a1115a"
        }
      ]
    }
  ]
}
