{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit5-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-694b583-change-setup-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-694b583-change-setup-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "4d4aff50940c67bfb436e1f65b0c58bf07d7de7e43689611eb8f648bf3a9b6213539923e51dbf954d72e30a9c22c62a947ca1ec15b36e999d01e92f0fa1aa943",
          "sha256": "a188b8543e64e2ff5ed66e85ccceb5f04689df639346028eb7adefc4be095d86",
          "sha1": "be7931b295dc123018bbad5fb41048ca65d9ee58",
          "md5": "e47b4a2cb726ad102f4c85c0673749f5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-694b583-change-setup-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-694b583-change-setup-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "4d4aff50940c67bfb436e1f65b0c58bf07d7de7e43689611eb8f648bf3a9b6213539923e51dbf954d72e30a9c22c62a947ca1ec15b36e999d01e92f0fa1aa943",
          "sha256": "a188b8543e64e2ff5ed66e85ccceb5f04689df639346028eb7adefc4be095d86",
          "sha1": "be7931b295dc123018bbad5fb41048ca65d9ee58",
          "md5": "e47b4a2cb726ad102f4c85c0673749f5"
        }
      ]
    }
  ]
}
