{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/0f449ed-change-fixture-SNAPSHOT/test-utils-ktor-0f449ed-change-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "0f449ed-change-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js.klib",
          "url": "test-utils-ktor-js-0f449ed-change-fixture-SNAPSHOT.klib",
          "size": 11802,
          "sha512": "c4c43cefa627a004231ffd55a038f9984e5781eed8b46959985e1917ce4f4c51b17c0b2eb4a44d9a6c4f78339fcf97aafde327e37c9e5108e60fce13ba2b7450",
          "sha256": "dcef97e946061538307032a3849601cc248743ef656bb619a905a917164e85ee",
          "sha1": "adc6800d96c780d58f9fb07b76ae8ff681320a0d",
          "md5": "54eafc4092fed093458a1fc5254eeaea"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js.klib",
          "url": "test-utils-ktor-js-0f449ed-change-fixture-SNAPSHOT.klib",
          "size": 11802,
          "sha512": "c4c43cefa627a004231ffd55a038f9984e5781eed8b46959985e1917ce4f4c51b17c0b2eb4a44d9a6c4f78339fcf97aafde327e37c9e5108e60fce13ba2b7450",
          "sha256": "dcef97e946061538307032a3849601cc248743ef656bb619a905a917164e85ee",
          "sha1": "adc6800d96c780d58f9fb07b76ae8ff681320a0d",
          "md5": "54eafc4092fed093458a1fc5254eeaea"
        }
      ]
    }
  ]
}
