{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit5-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosx64-694b583-change-setup-SNAPSHOT.klib",
          "size": 7032,
          "sha512": "9dd0601834b08678789019a64ee926de7304a3d9d65f4c7a4d2f3a5685f479e843c284e57b8f0e05292678f2eab6a8d9e246e2dd4dc012b9b24408b25f19e584",
          "sha256": "84cc965a8a9abd7548d780843d87b9c3287fc38b4328d2e2f32762eff2805f16",
          "sha1": "7f4df3c700d46b9ca39d41ac50d387e31387c948",
          "md5": "858fedcbae3c0eb53c407f60ed4c5cda"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "14b87fdda98b7c51e460a8a8e5157d3fe28412e8f8c2af1cc3fa7c72528f225f26a32710c5cd0aeda567c7acf560586164a8f2387d215f5dead30f8994a20a98",
          "sha256": "dd948af23064717610b50f061ad6711066873eedac85d7f62a9075f7e0623a09",
          "sha1": "bc31da94bd9c996719d7e6bd8c43344d2362f55b",
          "md5": "44b6e1a3e3a7ae921c35417900d729c6"
        }
      ]
    }
  ]
}
