{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "6612957",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-6612957.jar",
          "url": "antibytes-coverage-6612957.jar",
          "size": 128596,
          "sha512": "d3902be60855a380aef6f96c75c6173158574104f6a49f6deb79769bc44d935e542354ac585b05587a02cdbff5f8ac6c4b42d77df84945ba339c4054558bc1df",
          "sha256": "ce732f40552803432c36dce7064512477c521065e9a024f7e3ac22d04666669b",
          "sha1": "0be65f600774853e9f87ecb368ba92ad8dbee237",
          "md5": "854e3b40c10232131fc84028fcf3989e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6612957"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-6612957.jar",
          "url": "antibytes-coverage-6612957.jar",
          "size": 128596,
          "sha512": "d3902be60855a380aef6f96c75c6173158574104f6a49f6deb79769bc44d935e542354ac585b05587a02cdbff5f8ac6c4b42d77df84945ba339c4054558bc1df",
          "sha256": "ce732f40552803432c36dce7064512477c521065e9a024f7e3ac22d04666669b",
          "sha1": "0be65f600774853e9f87ecb368ba92ad8dbee237",
          "md5": "854e3b40c10232131fc84028fcf3989e"
        }
      ]
    }
  ]
}
