{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/5b65d35-bump-updates-SNAPSHOT/test-utils-coroutine-5b65d35-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "5b65d35-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT.klib",
          "size": 10205,
          "sha512": "b0bbdbcc6d42494b590f20b544b9b26f1bdaaae2be3930ec9ceebd25835b66bd1d5042009b328532011e5636866eed5dc3a8c61137716a0fe9f578a1f9aae902",
          "sha256": "0caf8ec2dc9ae77da85681027ff91963ba0943f6a381372602af2b2a2718758d",
          "sha1": "0169ff5f6589dd0ce895515bf12e4de588df2543",
          "md5": "6e5ea1acd5f08584ea0052f596de08c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d68f8dbe757ff941d1fca6c47d1e7467ba1ec22fb52dcd072dc5f9c29b32a931dd19da20c5e7b72fe4b529765e69709b1ef9d22b3c5522dba197dc3945ae9e89",
          "sha256": "2d7243448d6bf9f165f818fcff825197d280e0c6e6aa67058c6d9457a082d1ea",
          "sha1": "d42693dbe616e993c72a4ab3616c5c480442db21",
          "md5": "ff3f06f10cd2c3f19ff7f7c56da7d20b"
        }
      ]
    }
  ]
}
