{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05-bump-kotlin-SNAPSHOT/kmock-0.3.0-rc05-bump-kotlin-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05-bump-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc05-bump-kotlin-SNAPSHOT.klib",
          "size": 202582,
          "sha512": "3e2f304d34fc9d957d3d59dcab22153b639732cbc10d9db79f41daf4480520a24033184a78e4ecd90d4c33ec4199005b2c020fc138cf0d8d5762e43d50de337b",
          "sha256": "c1454ea4489fc5cfaef4c8daf419410166e91a3ea05a4065d671f36b072467be",
          "sha1": "c1bc3d93c573761643127c55f61bd8aece21da02",
          "md5": "912722934c1e3b8172fb88cc46600704"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc05-bump-kotlin-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc05-bump-kotlin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8ff468396153636acbac3d2da06f9ee21e58434eaace6f88e528b24b276fa7b81f306aeb228b13241e200b7b935b9168881e629c13365e36ae61505f4533376d",
          "sha256": "5293d4efc37b6a7fb9571f0c61bd1ff1ec264719ce70068c0fdb9c327425471c",
          "sha1": "979bd3f661dd6a777df62c4d7759c3138192221f",
          "md5": "05b3d24dd1d6e87ecf04e2eceaba502c"
        }
      ]
    }
  ]
}
