{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/694b583-change-setup-SNAPSHOT/test-utils-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-tvosx64-694b583-change-setup-SNAPSHOT.klib",
          "size": 7953,
          "sha512": "3d82ea27d4c5c6a68e1679f4492aaa2bfe351b5ac7d90357dd9ec621c85b055c0885eab37cba7572cb94c50b4f20e9ecc5fc84bc827c5f7e2a3002c3f05bfabd",
          "sha256": "ed713709d804a31f096870ea55d494cf1809b8a82f59b4e5a3659fc53ae6a670",
          "sha1": "d8fe66b0dd2daa5273880cf96d1325eaaaea92d0",
          "md5": "48d708cee95c15f61666f0f7b1b5d7da"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-tvosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-tvosx64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "339e27c8ddeeced4a72abfac8883aae13682f1570b0a424fd5d04484ee87573dd240628519eea80a871ef1c82dba1b1d52ef19fc2dac64e9f9daee30b3f17d79",
          "sha256": "68dd252444b591d0acc12f6c41d47ea142c754537286a12d89a84027f740c327",
          "sha1": "c90f36d83ebc42c0572312a82c44f197048d3b74",
          "md5": "d5a610a058bb9540a8803dc8020f08eb"
        }
      ]
    }
  ]
}
