{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "5c0fd27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-5c0fd27.jar",
          "url": "antibytes-coverage-5c0fd27.jar",
          "size": 133706,
          "sha512": "1e5efe5e7ab8dc0346633460fcf096142c43962698d02e9a492c659122f76c94727c0ef1817e9a360b9e8605111f1ffcd99dfa62b6d60e8df3f541802c4e1e58",
          "sha256": "6ad42b87de9ff93dfe9db5861fef8b2eff1d7bd1c9efa1f6dc2b3d1785d91507",
          "sha1": "aeb8708c127405b90b618f5fbf4264f7c1df5217",
          "md5": "5fcdb7673ee420f80ce93e6a73938fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5c0fd27"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-5c0fd27.jar",
          "url": "antibytes-coverage-5c0fd27.jar",
          "size": 133706,
          "sha512": "1e5efe5e7ab8dc0346633460fcf096142c43962698d02e9a492c659122f76c94727c0ef1817e9a360b9e8605111f1ffcd99dfa62b6d60e8df3f541802c4e1e58",
          "sha256": "6ad42b87de9ff93dfe9db5861fef8b2eff1d7bd1c9efa1f6dc2b3d1785d91507",
          "sha1": "aeb8708c127405b90b618f5fbf4264f7c1df5217",
          "md5": "5fcdb7673ee420f80ce93e6a73938fa5"
        }
      ]
    }
  ]
}
