{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-add-more-sources-SNAPSHOT/core-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 105871,
          "sha512": "15f433215238fd539763e12c39180ba6d4467558426b2ec74efd46538eac53aaa2119c4dc7f532f6d67c40c587b8ca233303955a58b57b97ceffbd972d46905b",
          "sha256": "7bb24ab9548c98329cb067d45919be5b024b4d2bcc27c1963e6170be77237746",
          "sha1": "e4ba4d4b9033c5635955248aa46ca1ef9ca7c0fb",
          "md5": "88176f7c5deaa4609744a2c8e1a4ef20"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4fc3cfc84329aec8c13381b7b09bc35f3b23a7bdf19737a447376224142d42fd015ba01a2e0667e81fac0a415cf4d93eb46ad156ca37b52597aace426bc049fd",
          "sha256": "4fcf893586187ba02092a1b808d4071c0a08ea0cbed470f699934e5664357ff1",
          "sha1": "981fed650aae0f71ebd90f172e0c23f13e339279",
          "md5": "03bd75b93715dee911c2448e93f3fcb5"
        }
      ]
    }
  ]
}
