{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-add-more-sources-SNAPSHOT/core-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 105871,
          "sha512": "15f433215238fd539763e12c39180ba6d4467558426b2ec74efd46538eac53aaa2119c4dc7f532f6d67c40c587b8ca233303955a58b57b97ceffbd972d46905b",
          "sha256": "7bb24ab9548c98329cb067d45919be5b024b4d2bcc27c1963e6170be77237746",
          "sha1": "e4ba4d4b9033c5635955248aa46ca1ef9ca7c0fb",
          "md5": "88176f7c5deaa4609744a2c8e1a4ef20"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "91b35f45141670c0207fed3bd73bd9dea568e911bf54d8e81022e3403944cd72fed67721caf4ceb495a39725e996b9898d3aa5d159de73fe638f6196edcb5096",
          "sha256": "66583777c4d686c38c9d6ae8a59f1c6f424a92841510650cfa815d6e09ce56e5",
          "sha1": "c8c1d8cbee6dbb928ca55f46a29b03c9c1350fc3",
          "md5": "08bac078534d17ca31fb8c57dd73845a"
        }
      ]
    }
  ]
}
