{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "72725be",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-72725be.jar",
          "url": "antibytes-configuration-72725be.jar",
          "size": 49663,
          "sha512": "e020bfde1f063d4ae14a77611062fb6bf203a14b12c476f5e3b96fd21cfdaf213efc1f37fae67ff2019de11c150fb8a15ba961d395fec2d61ff570654328891e",
          "sha256": "15d923462f1f5faa0ec0d294b4b45f3ec401280c31d00f341e983bdfcb10a103",
          "sha1": "732be3dab6ba8613ae6487721d9be4136c48e478",
          "md5": "a45238a2db80d230ba5af979f25feb38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "72725be"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-72725be.jar",
          "url": "antibytes-configuration-72725be.jar",
          "size": 49663,
          "sha512": "e020bfde1f063d4ae14a77611062fb6bf203a14b12c476f5e3b96fd21cfdaf213efc1f37fae67ff2019de11c150fb8a15ba961d395fec2d61ff570654328891e",
          "sha256": "15d923462f1f5faa0ec0d294b4b45f3ec401280c31d00f341e983bdfcb10a103",
          "sha1": "732be3dab6ba8613ae6487721d9be4136c48e478",
          "md5": "a45238a2db80d230ba5af979f25feb38"
        }
      ]
    }
  ]
}
