{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-datetime-docs-SNAPSHOT/ktx-datetime-0.3.1-add-datetime-docs-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-datetime-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-datetime-docs-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-add-datetime-docs-SNAPSHOT.klib",
          "size": 34785,
          "sha512": "8f0b1a31f3112809e249c830ea7dc505cd979b549c66f799f854a8c005e456b87cb265a5642b64c9090441f96a1dc355070b088c49f54bb31ee8fe6de75689a6",
          "sha256": "f1a3d0355c51be80e881bd041a1cbb722f80aabcf457e03d3d141b141ce99a23",
          "sha1": "98d8873bffae3b4f6f3e1f2920f94408a0d4de20",
          "md5": "e73173220ddfd62b626eeec87f235a82"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-datetime-docs-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.3.1-add-datetime-docs-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.3.1-add-datetime-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "79f194a7286686b9077106090a90c94f0748f1b833bf3e767fafd46503621f79db1e15d4b4707f60aaa33ba39e4f9cff5e2048bd28229f4af584c5f6fcafecd7",
          "sha256": "b51ee1776dc177a7648b84a95a1041220f859f114664e5a8d01e87beb4755f01",
          "sha1": "43239ad497454daff7543dbf5bd84e93e41e0c79",
          "md5": "ad4ecc4d0ab7c2f3357ea31c20cf7fb4"
        }
      ]
    }
  ]
}
