{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "ba1177d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-ba1177d.jar",
          "url": "antibytes-coverage-ba1177d.jar",
          "size": 133706,
          "sha512": "e64713ed1a4df95ebbc9f1a2043227ea167118ad92d3af902a840760c42196ab4423e91852f8650eb0e3a90402bd6c3305d68154cb410ba9079ee0255db40c4a",
          "sha256": "418a347f0069b18e1866190ff352b9637984a12328438551136ad3687c5e0181",
          "sha1": "2972e4bef593523cb2fcba0777751a106fcbcb1e",
          "md5": "4b825e51bf3ad5538908bddb067727f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ba1177d"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-ba1177d.jar",
          "url": "antibytes-coverage-ba1177d.jar",
          "size": 133706,
          "sha512": "e64713ed1a4df95ebbc9f1a2043227ea167118ad92d3af902a840760c42196ab4423e91852f8650eb0e3a90402bd6c3305d68154cb410ba9079ee0255db40c4a",
          "sha256": "418a347f0069b18e1866190ff352b9637984a12328438551136ad3687c5e0181",
          "sha1": "2972e4bef593523cb2fcba0777751a106fcbcb1e",
          "md5": "4b825e51bf3ad5538908bddb067727f8"
        }
      ]
    }
  ]
}
