{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "1fc88e3-add-quality-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-versioning-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "size": 16029,
          "sha512": "a92ecc16b36306969d7f24cf3433522dc75aa20d2d85f86e9f3763cb5a7c17adc5f60acf2aac8a01085eef889f6178130c81cd70155427d90b5f497bf6f05532",
          "sha256": "993600f4f31aad13c641b27c835b6523613891bbdb174fd82a1614e382433289",
          "sha1": "13e975308fd9b026ace154a9d49f9943cb8ba504",
          "md5": "cfbcc26885720bc0f90dea7b4c87399b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-versioning-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "size": 16029,
          "sha512": "a92ecc16b36306969d7f24cf3433522dc75aa20d2d85f86e9f3763cb5a7c17adc5f60acf2aac8a01085eef889f6178130c81cd70155427d90b5f497bf6f05532",
          "sha256": "993600f4f31aad13c641b27c835b6523613891bbdb174fd82a1614e382433289",
          "sha1": "13e975308fd9b026ace154a9d49f9943cb8ba504",
          "md5": "cfbcc26885720bc0f90dea7b4c87399b"
        }
      ]
    }
  ]
}
