{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-annotations-junit4-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "efb8eff-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 11335,
          "sha512": "a2b53caf68a6238f48cb4582555a79eb50d91dc842aa7c144782c1901b31ce7f9bf0d6b81e791a8ff23dd068e3bf2897198e58f008a6bb58779d8995c89dc042",
          "sha256": "0c0bd6ef30e191d9933583a320776bb991623922170cba30ae14477f3e3c90d7",
          "sha1": "c9d01ac9add1320a06ea845bb74746a10fbf870b",
          "md5": "123085bdd3e3489ec2d5e3886fd3710f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8a2eff165f3216a9ec1383303ac171106f73ccb46939ea5ef65f49f240230111b5038478be07ad3484d269b3eef6c790611487243de8b9df24425e503a8a0444",
          "sha256": "13497c7d0dfd6b7862be808bc045abac8459803cb8449ca4ae321d6e529ca02c",
          "sha1": "76b6437f3fb9daf19fdd105dff5a3a37259fb5e9",
          "md5": "b50c2176ca3e5010d8aa68ef1d754a96"
        }
      ]
    }
  ]
}
