{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-0.4.0-bump-settings-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-settings-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-settings-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.4.0-bump-settings-plugin-SNAPSHOT.klib",
          "size": 34683,
          "sha512": "1dc52bb0058de13a55d58ed8a606ff162390a626a81ab89e3b00cf5ce47dd058161bf547e8124e99a1839e84ae82ffdb206e1cbad0c4213ff9c1c39bfd585388",
          "sha256": "8a29a5e2fcf40a3d852b934eeefc47d7daba8270c31803df600351398c310c0b",
          "sha1": "d0212f8ba21b7440fed51bae6ceee9eff5b147d3",
          "md5": "bb0ba6de1a6a1542c83616eba7374c64"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-settings-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.4.0-bump-settings-plugin-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.4.0-bump-settings-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "aa060ab05d720833467b0ae264a5376b2427ba836ad761891101d6b0e04ef133f5c10f8fd9cebc61f2b94a9b7c58517caf6067830cfaa3189fd0eb792efaa54f",
          "sha256": "cd018c5958f688004359125496e9b0a2e4f85ad73569440ef0b7d25848593fe3",
          "sha1": "d1569ea6aa438ace09cbbf8928cda1ef2ee44d26",
          "md5": "c6eb981189b1cef427b202ab215523a9"
        }
      ]
    }
  ]
}
