{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/bfa7c15-change-publishing-SNAPSHOT/test-utils-coroutine-bfa7c15-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "bfa7c15-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-bfa7c15-change-publishing-SNAPSHOT.klib",
          "size": 10210,
          "sha512": "4e6c8650d52b4ac184d14f704e3a2a119b82315ba8665094297dde817c1c6577a274a1a2e6359a9d6462dfe15d26359db6fd028bf3cc6e44b27ffe56eb1be57b",
          "sha256": "73ed4ced9dd0d433a6e8a1e48b1406ae0a38155c2f9061ee8cf21f5e9dc30343",
          "sha1": "1f2884ffc19bcb91d904ed12d8b018dd5e120388",
          "md5": "fa44c515a7a2019b52cf5c51c692b7f2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-bfa7c15-change-publishing-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-bfa7c15-change-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6f5e7deecc46ae021cafa59656b439df154faaf77c175bd85f60caaecfc11f7aef4cb40f937abd70fe50e0d95a806e5313320f2dad01b02145074dd9ed50d1b8",
          "sha256": "2aa602fea1e616bd16e45f5fc9a95545124d6d716f16481fc4285e59b1414045",
          "sha1": "d9732b26155f611d85c3168a5b397821a3733d17",
          "md5": "6ed12d61c534a5a27bfcf3cbcfa6a45e"
        }
      ]
    }
  ]
}
