{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-bump-updates-SNAPSHOT/core-0.3.1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.1-bump-updates-SNAPSHOT.klib",
          "size": 110285,
          "sha512": "57b10018447255354d0614bb1f51618d4b405b894bbb080e06b0be65e768ef002541654beaf439fa6ffbc3e5a56a2c62b92cc9416f5ac000a9dee06d0ed4ef63",
          "sha256": "8734c366a0a52cd463a7d7d805211f84ca1d92baf9feda5783617bc37e5821cc",
          "sha1": "26c4bbd246f0df0ee52df6a806315e9ee552b1c9",
          "md5": "72689d2ec45abda25026982db85a6489"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3baa58bac8f517bf0e899cee932b3596e41e4e148d364b2b55b74950b1648f261a461c4dccfe5cdfd4214bf57749ae8626a1614137a38ab7e9fb003a5fa6f0e1",
          "sha256": "4b4234f12afb698f4bd93890309ae7ac58aa3efaad6da9e959ab33780dbc1387",
          "sha1": "6285eb155682c0a3191c9327b037cc12026733f8",
          "md5": "19c71cac3d0f4a05c73a5fe4e47e07f8"
        }
      ]
    }
  ]
}
