{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "028221d-bump-iphone16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-028221d-bump-iphone16.jar",
          "url": "antibytes-dependency-node-028221d-bump-iphone16.jar",
          "size": 20149,
          "sha512": "1d65a5bc12e9639adfa6d4b71a77207e27d67d179f825bcb13d8e15e0adf910f8a9d00d5494396db693a6cac7259804ed100b0d0b729c861abfb44bbe028e29a",
          "sha256": "1e9d0d204acab18e79b75eddae2c3b76a1bd48cb313bf264b6661ea15b25bad6",
          "sha1": "d976341ae516ae35b39a50e31d255a270f412c17",
          "md5": "bf1292ff41b47a278626c18f2b7e0143"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-028221d-bump-iphone16.jar",
          "url": "antibytes-dependency-node-028221d-bump-iphone16.jar",
          "size": 20149,
          "sha512": "1d65a5bc12e9639adfa6d4b71a77207e27d67d179f825bcb13d8e15e0adf910f8a9d00d5494396db693a6cac7259804ed100b0d0b729c861abfb44bbe028e29a",
          "sha256": "1e9d0d204acab18e79b75eddae2c3b76a1bd48cb313bf264b6661ea15b25bad6",
          "sha1": "d976341ae516ae35b39a50e31d255a270f412c17",
          "md5": "bf1292ff41b47a278626c18f2b7e0143"
        }
      ]
    }
  ]
}
