{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-ios-simulator-SNAPSHOT/kmock-0.1.1-add-ios-simulator-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-ios-simulator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-ios-simulator-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-ios-simulator-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "f089df79b7eba68fc448dc9f02517202a0f5d115ea844f536d9b76d6ef820cdd605f7afc3aecb4c789b05ad0ffee003f11291fb5785f52972e94b8c8ab93184b",
          "sha256": "694e6104358394b7d7209c29e4cc1681df7856b5acb9d51d9215b2eae08018ad",
          "sha1": "b7255d2fdc07818f35f8ab3a0fb9503565ee11ea",
          "md5": "e8f8527a48c9155a82476c4ae3db50af"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-ios-simulator-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-ios-simulator-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "f089df79b7eba68fc448dc9f02517202a0f5d115ea844f536d9b76d6ef820cdd605f7afc3aecb4c789b05ad0ffee003f11291fb5785f52972e94b8c8ab93184b",
          "sha256": "694e6104358394b7d7209c29e4cc1681df7856b5acb9d51d9215b2eae08018ad",
          "sha1": "b7255d2fdc07818f35f8ab3a0fb9503565ee11ea",
          "md5": "e8f8527a48c9155a82476c4ae3db50af"
        }
      ]
    }
  ]
}
