{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/12cf284-bump-updates-SNAPSHOT/test-utils-coroutine-12cf284-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "12cf284-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-12cf284-bump-updates-SNAPSHOT.klib",
          "size": 10207,
          "sha512": "67a84bd839583a7af04524f84d93a94383b5f07448586e3b08a26ef37aec233d9dec4999032e52bc0fc0ce68df71819d88ab2630980877da78f23b3a285c04dc",
          "sha256": "b0f758b401a0e74b573ff24e92ac80ca7ba1a3f365b783c11a4513472f64904d",
          "sha1": "8607c7cd6c78f8ce9cb948cf6cf2d24b98e72bfe",
          "md5": "504a89ab7cc3d05a9b518b00dd4f4c22"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-12cf284-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-12cf284-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2d982fecbd16cb0c353bf840d97e92f61ae37df604cda116c3dc0b2aa848afef05ef1d822275ec46fcf9e34bb04d776e4441bb3a3407a53d62c9f0d922b6bc49",
          "sha256": "64c61f0ff8b8380056d918fb4824e46edd8ccb0509efb15cb661f13c628af8e9",
          "sha1": "dfb6e6de7d5e1817125f0af99adf0c0614fd9c32",
          "md5": "d61dd31e956a51882c877b6b23a20c2d"
        }
      ]
    }
  ]
}
