{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/205f7d8-fix-assertions-SNAPSHOT/test-utils-annotations-205f7d8-fix-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "205f7d8-fix-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 11190,
          "sha512": "7636affaa2508e0641fd82b7b5312f754be431877d8ba8ccf48ce3e3cbb7c69b2877a3d5968896c05cb85068366fbd8be3d98d4b5d76b24f24e0667ecb15a954",
          "sha256": "600ab0112815257158cd95518792fa5f376bb19b4912b0d02f5d8eb95c43cb00",
          "sha1": "f299b0776b29df3292eefb2000e37152e09dd6f6",
          "md5": "b593084051b99e0e2280d02971e86651"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-205f7d8-fix-assertions-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosx64-205f7d8-fix-assertions-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c535694b0bcdfc7fe17993b9cb302cb2d80c28eebb5d7d2fd22aadba69fdbb76c3b52eb2ced4e4e845b4a79d35e3b1200b48b71d55df93b9d792b7aedc42a4aa",
          "sha256": "f6f814e906bb5375715e4b35915a8e4d6cda9ef79791117c5fea50b04297a83a",
          "sha1": "c41312292e4e411d1d6f68fc7581ef60cb496337",
          "md5": "d38a7b1e6cba688163f55d4928f7e5a9"
        }
      ]
    }
  ]
}
