{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "49cbc80",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-49cbc80.jar",
          "url": "antibytes-grammar-tools-49cbc80.jar",
          "size": 41868,
          "sha512": "26ded6b84a7d0a5a1e25510f8ceb3c8cf4533c120a8b446bfbc974d1a21d0450b47992d5a002cc289a66a5a1923191477f68566d31eaeace054fd8144f4fa3f7",
          "sha256": "89845afabb2f4fa4014651846cf1db2117308e738240b25206b843ba67b0aa3c",
          "sha1": "b775979cad561f9965fa078875b0e0af4d5064dc",
          "md5": "ac1943e9b9778fb453540a507fc564c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-49cbc80.jar",
          "url": "antibytes-grammar-tools-49cbc80.jar",
          "size": 41868,
          "sha512": "26ded6b84a7d0a5a1e25510f8ceb3c8cf4533c120a8b446bfbc974d1a21d0450b47992d5a002cc289a66a5a1923191477f68566d31eaeace054fd8144f4fa3f7",
          "sha256": "89845afabb2f4fa4014651846cf1db2117308e738240b25206b843ba67b0aa3c",
          "sha1": "b775979cad561f9965fa078875b0e0af4d5064dc",
          "md5": "ac1943e9b9778fb453540a507fc564c1"
        }
      ]
    }
  ]
}
