{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-metadata-13f09a8-add-more-sources-SNAPSHOT-all.jar",
          "url": "test-utils-ktor-13f09a8-add-more-sources-SNAPSHOT-all.jar",
          "size": 5337,
          "sha512": "83bf91d531a399dc2f20492a85ef8a4fc246a89cff51d223016147d850aecb6a26dcf5a718a2f2d00d509b494ac7219f5fb277e2d53b4e7762e8f3c0d5e8a7fc",
          "sha256": "86512f4a10e85b495f844896d79c20b716af2a0b05c144016b17a924151e9f77",
          "sha1": "c84aeb903f452ab7a6de69215db23c4b755b30e1",
          "md5": "2bb8448bb6adfc59d64a81c20d37fb78"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-13f09a8-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-ktor-13f09a8-add-more-sources-SNAPSHOT.jar",
          "size": 2502,
          "sha512": "c6d4ed473b4fcc9e258be46814902a57ec17499785658b4e2c71e24d832bf3662d39ec499bf04dbb05b98fe2ae85f7f8397be8c029e154fa3dd632cfacf3c75d",
          "sha256": "0f1d86d707301e83df1c8d099debceda9696b79429fdd463dcbb771c1f4dd363",
          "sha1": "4d56549ec8ddbc9c3da0e3c5127cdcfbebc8941f",
          "md5": "4e1398583ee572469eca89c55bd68e6c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-android-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-android-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm32/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosarm32-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm32",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm32/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosarm32-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm32",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-iosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-js-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-js-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-jvm-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-jvm-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-linuxx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-macosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-macosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-macosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-macosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-macosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-macosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-mingwx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-mingwx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-mingwx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-tvosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-tvosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-tvosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm32/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosarm32-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm32",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm32/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosarm32-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm32",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchossimulatorarm64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchossimulatorarm64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx64/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosx64-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx64",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx86/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosx86-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx86",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-watchosx86/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-watchosx86-13f09a8-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-watchosx86",
        "version": "13f09a8-add-more-sources-SNAPSHOT"
      }
    }
  ]
}
