{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "452cb59-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-452cb59-change-node-dependencies.jar",
          "url": "antibytes-grammar-tools-452cb59-change-node-dependencies.jar",
          "size": 39371,
          "sha512": "18cf2e4de4aad1b5f69b10476002c897e30b44d504a50e3176d12871aad908b4ce734b67b8ba87cf3002cdf391071e16c75c13a87fc6b3bd260ef5a411fb9c04",
          "sha256": "08b8640365bf628f87d62c4112df7bcc4f653fbf612f0ef649d7ff613ba7bac3",
          "sha1": "6cd171292610580c57d657338eaa2d7d5f5a60a4",
          "md5": "966549489855e99924d4e3396d7c0b86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-452cb59-change-node-dependencies.jar",
          "url": "antibytes-grammar-tools-452cb59-change-node-dependencies.jar",
          "size": 39371,
          "sha512": "18cf2e4de4aad1b5f69b10476002c897e30b44d504a50e3176d12871aad908b4ce734b67b8ba87cf3002cdf391071e16c75c13a87fc6b3bd260ef5a411fb9c04",
          "sha256": "08b8640365bf628f87d62c4112df7bcc4f653fbf612f0ef649d7ff613ba7bac3",
          "sha1": "6cd171292610580c57d657338eaa2d7d5f5a60a4",
          "md5": "966549489855e99924d4e3396d7c0b86"
        }
      ]
    }
  ]
}
