{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "5aacabc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-5aacabc.jar",
          "url": "antibytes-gradle-utils-5aacabc.jar",
          "size": 9580,
          "sha512": "9d6a7cb39fedb700e32f2c025affb64fdadc22a4ab69212228dff2b3082ca96b6f98c82297880d7d9b8e18ee8851dad36523a540ac9a654a17f388e2562176ab",
          "sha256": "fbb680d70063b54d9e435d609edd7be0e968ec47c8dd8a5a66447fcd62c59c35",
          "sha1": "44e2a823a5a95df55684fc8d8f530abc006b4a05",
          "md5": "6dbd93de5cd26c1c3b4db781186196db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-5aacabc.jar",
          "url": "antibytes-gradle-utils-5aacabc.jar",
          "size": 9580,
          "sha512": "9d6a7cb39fedb700e32f2c025affb64fdadc22a4ab69212228dff2b3082ca96b6f98c82297880d7d9b8e18ee8851dad36523a540ac9a654a17f388e2562176ab",
          "sha256": "fbb680d70063b54d9e435d609edd7be0e968ec47c8dd8a5a66447fcd62c59c35",
          "sha1": "44e2a823a5a95df55684fc8d8f530abc006b4a05",
          "md5": "6dbd93de5cd26c1c3b4db781186196db"
        }
      ]
    }
  ]
}
