{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-add-integration-tests-SNAPSHOT/kmock-0.3.0-rc04-add-integration-tests-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-add-integration-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "size": 202480,
          "sha512": "a9b7bb5c9b68b1497a1b23b1c3ec2733c094c64dbeafcc9ed02276b8193c2f9abe9a01dcfc042e33c2fdf452999306833b3382d82972a4c6616fd761584ee887",
          "sha256": "409aa2c045cbf367e11265cdc657c7ebaebfc4a46ffe07d4fa527bf20b4b85bf",
          "sha1": "b5ce09c0329dd6c749c5f86dd1ee255490c44ddc",
          "md5": "b203fde22c21670a19904dff468222c6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc04-add-integration-tests-SNAPSHOT-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc04-add-integration-tests-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d4a1beb7959dffa368bc63cb6da860f8b7296777c3d15e7fc08365320815713494773f1c6af66b3bab60d4e8fbe62261ef1dbff1c3b8fe2ea5107e9b4a3c4275",
          "sha256": "c75f31979ab1745eb733036c7c96677f64344cbbce7039f479536666d0703c8f",
          "sha1": "27ba928aecbfd7ba23975223714e75fdbafdf7d7",
          "md5": "72b21b96bc800c93c040f55d2f314188"
        }
      ]
    }
  ]
}
