{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "7b5c888-change-versioning-path",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-7b5c888-change-versioning-path.jar",
          "url": "antibytes-gradle-test-utils-7b5c888-change-versioning-path.jar",
          "size": 17888,
          "sha512": "c8b5e28631f6f21f58727cb390faa7dca6bea39d46bf2e204e9aff93d4ce60b6bd55535fa1c10d0259d9081f06b940561c8b4b9bcec96f0f2d5ce6164d26c73d",
          "sha256": "d1c3450da985791829cc7bc18a4a49d4ad458256257fb2ade77f09cc3835b719",
          "sha1": "0ed0c63ee2685e58cc3696cb59240d331aceff69",
          "md5": "829a43e7cba4efe62cae17a4a851b154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.7"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-7b5c888-change-versioning-path.jar",
          "url": "antibytes-gradle-test-utils-7b5c888-change-versioning-path.jar",
          "size": 17888,
          "sha512": "c8b5e28631f6f21f58727cb390faa7dca6bea39d46bf2e204e9aff93d4ce60b6bd55535fa1c10d0259d9081f06b940561c8b4b9bcec96f0f2d5ce6164d26c73d",
          "sha256": "d1c3450da985791829cc7bc18a4a49d4ad458256257fb2ade77f09cc3835b719",
          "sha1": "0ed0c63ee2685e58cc3696cb59240d331aceff69",
          "md5": "829a43e7cba4efe62cae17a4a851b154"
        }
      ]
    }
  ]
}
