{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "1367684-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-custom-component-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 16172,
          "sha512": "55ccb419e7ac001d86acfeae0bdef8f7b4ae09c668638fb320f84604358d1f152f8604cdba92165a604788c3929f4f62ccb5bba8bf8e11b3a023f50ed2264a93",
          "sha256": "361ca4126121111c229a387e135445c4b2e1cb186f795be4c9a44ebf9e1846ea",
          "sha1": "979cfb607cff82563a4c65e6abf99015d5e56443",
          "md5": "68b21ea64e18adf970c6f91d186bff24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-custom-component-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 16172,
          "sha512": "55ccb419e7ac001d86acfeae0bdef8f7b4ae09c668638fb320f84604358d1f152f8604cdba92165a604788c3929f4f62ccb5bba8bf8e11b3a023f50ed2264a93",
          "sha256": "361ca4126121111c229a387e135445c4b2e1cb186f795be4c9a44ebf9e1846ea",
          "sha1": "979cfb607cff82563a4c65e6abf99015d5e56443",
          "md5": "68b21ea64e18adf970c6f91d186bff24"
        }
      ]
    }
  ]
}
