{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "99eff34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-99eff34.jar",
          "url": "antibytes-publishing-99eff34.jar",
          "size": 105743,
          "sha512": "73885755ef7a02483cf4b65c33204d3e5532d6980e07a1eec79d8659641dfe612cb99a4cf89eabee64fe35fe1fc8abe892f9445257e45702ee3e865f4202fc07",
          "sha256": "e0e32612313b1793c8f020ab152aaf51f52424f415a98f9b05fe9f29c01df81e",
          "sha1": "d21608514a64fa389d3b338983bec6775c94ef76",
          "md5": "25fbcc4ab07b037024679fae6d3364b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.0.0.202111291000-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "99eff34"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-99eff34.jar",
          "url": "antibytes-publishing-99eff34.jar",
          "size": 105743,
          "sha512": "73885755ef7a02483cf4b65c33204d3e5532d6980e07a1eec79d8659641dfe612cb99a4cf89eabee64fe35fe1fc8abe892f9445257e45702ee3e865f4202fc07",
          "sha256": "e0e32612313b1793c8f020ab152aaf51f52424f415a98f9b05fe9f29c01df81e",
          "sha1": "d21608514a64fa389d3b338983bec6775c94ef76",
          "md5": "25fbcc4ab07b037024679fae6d3364b5"
        }
      ]
    }
  ]
}
