{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-change-sideeffect-SNAPSHOT/kmock-0.2.0-rc01-change-sideeffect-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-change-sideeffect-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-change-sideeffect-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-change-sideeffect-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "4c8356924f1466652efcb04f20addc7dd28f0f2274a3a2b7ebf1a21ebc27093c0013e4e3263cdfef1f7db4d7ba19e39b38e6f24ea322e03526186b3ff620dd6d",
          "sha256": "5e293d7fd0060f290f18dee1c8b17c1da31744e810415766cd1cdae8be4b5406",
          "sha1": "664253b93f2d67c06987d21743710b3a43604220",
          "md5": "baf33b24624aef4b1bc4e1dfe8b7e174"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.2.0-rc01-change-sideeffect-SNAPSHOT.jar",
          "url": "kmock-jvm-0.2.0-rc01-change-sideeffect-SNAPSHOT.jar",
          "size": 383636,
          "sha512": "4c8356924f1466652efcb04f20addc7dd28f0f2274a3a2b7ebf1a21ebc27093c0013e4e3263cdfef1f7db4d7ba19e39b38e6f24ea322e03526186b3ff620dd6d",
          "sha256": "5e293d7fd0060f290f18dee1c8b17c1da31744e810415766cd1cdae8be4b5406",
          "sha1": "664253b93f2d67c06987d21743710b3a43604220",
          "md5": "baf33b24624aef4b1bc4e1dfe8b7e174"
        }
      ]
    }
  ]
}
