{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "6ad5323-add-shared-detekt-config",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-6ad5323-add-shared-detekt-config.toml",
          "url": "antibytes-dependency-catalog-6ad5323-add-shared-detekt-config.toml",
          "size": 229267,
          "sha512": "0ebd47edc90f10d490068a6d2ec9118d5c712d3b46a19ea362bb94d1ae359a212cedb564d6e1e970234fe53008b4ae8465a4b64e41c1ee102e516f86b3b4f238",
          "sha256": "5d94362e43151c8c113fdf750a21b370f4d681d018c9800a6c380c82d6b9ff04",
          "sha1": "91ff4224d5b7fef31346f2966d4a0e1426eac8b9",
          "md5": "30a33df21f58f40833fe33edc27d78d9"
        }
      ]
    }
  ]
}
