{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/944b0af-bump-updates-SNAPSHOT/test-utils-annotations-944b0af-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "944b0af-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-944b0af-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-944b0af-bump-updates-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "3626b8d409470ad074c3b2c29a907e420bde3fec66c4b032368124f76a9e11d335836c172f1cb727e928c574700ec4a697aa682444547128eb3a50ae12563dbb",
          "sha256": "3a159c8a9fc2ea822d98b6202707161a4c062773626a92aeda5ba346cb5dace5",
          "sha1": "5b780c8de49a196357e102283a0ec3a9b8ca8220",
          "md5": "8ad0f44779a3d876047aa5518bfcc52b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-944b0af-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-944b0af-bump-updates-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "3626b8d409470ad074c3b2c29a907e420bde3fec66c4b032368124f76a9e11d335836c172f1cb727e928c574700ec4a697aa682444547128eb3a50ae12563dbb",
          "sha256": "3a159c8a9fc2ea822d98b6202707161a4c062773626a92aeda5ba346cb5dace5",
          "sha1": "5b780c8de49a196357e102283a0ec3a9b8ca8220",
          "md5": "8ad0f44779a3d876047aa5518bfcc52b"
        }
      ]
    }
  ]
}
