{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/cd3e534-fix-single-sources-SNAPSHOT/kmock-cd3e534-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "cd3e534-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-cd3e534-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-cd3e534-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "6db4f9acbcfa750fa8ec98c07f00b3c285dac3c24cb47853c88cc1908d089b707c1e0592141a0bc57a8cf4e6c143463086a32055df9e093e1b0525d534516cde",
          "sha256": "c0aea069aa13c4a9a15b310a92883c4ceccdce337e9e0a0004fb2b4e9351761b",
          "sha1": "9623c9e763fef806146b92c47d72821c9296603b",
          "md5": "cc44e6b23f94aecbcdd4a978748170a5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-cd3e534-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-cd3e534-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "6db4f9acbcfa750fa8ec98c07f00b3c285dac3c24cb47853c88cc1908d089b707c1e0592141a0bc57a8cf4e6c143463086a32055df9e093e1b0525d534516cde",
          "sha256": "c0aea069aa13c4a9a15b310a92883c4ceccdce337e9e0a0004fb2b4e9351761b",
          "sha1": "9623c9e763fef806146b92c47d72821c9296603b",
          "md5": "cc44e6b23f94aecbcdd4a978748170a5"
        }
      ]
    }
  ]
}
