{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "c7998a8-fix-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-c7998a8-fix-dependencies-SNAPSHOT.jar",
          "size": 2149,
          "sha512": "b3adde0994aee750acf405c884befb53823e1517c4917d56dfa8d9966d2fb0549c02ebc73f742fc104c4e424fb790d6c0d1c16843dc6aa8608af401700332cfb",
          "sha256": "e1d37a02bc876e5cac2c90223263db63c43fe70825823d3d055f3fb5878a55f7",
          "sha1": "7e61463d5811b3908f57f4c93724380a02f891ac",
          "md5": "593526c3f49487622506666e48abb218"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/c7998a8-fix-dependencies-SNAPSHOT/test-utils-coroutine-android-c7998a8-fix-dependencies-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "c7998a8-fix-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/c7998a8-fix-dependencies-SNAPSHOT/test-utils-coroutine-android-c7998a8-fix-dependencies-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "c7998a8-fix-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/c7998a8-fix-dependencies-SNAPSHOT/test-utils-coroutine-jvm-c7998a8-fix-dependencies-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "c7998a8-fix-dependencies-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/c7998a8-fix-dependencies-SNAPSHOT/test-utils-coroutine-jvm-c7998a8-fix-dependencies-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "c7998a8-fix-dependencies-SNAPSHOT"
      }
    }
  ]
}
