{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "394665c-bump-updates",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-394665c-bump-updates.jar",
          "url": "antibytes-dependency-node-394665c-bump-updates.jar",
          "size": 20149,
          "sha512": "6d97bcf67997a6283823e78a5e7555a7495130bcfc66f59a6c4fb6a6df59c24b8bc108faf08ed7c135c58780dfe96bfb2c54ffd696512f90f037d0b61c8a1af8",
          "sha256": "7dafdc1c8310cc2a958c0973b744fb4cbfbff23fc5527cfb7c68475972641ec4",
          "sha1": "6b4c30473ea370c601db0a8ad2a6a50027543ab9",
          "md5": "1e14d9e18b80139ad6dbfcc51968f983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-394665c-bump-updates.jar",
          "url": "antibytes-dependency-node-394665c-bump-updates.jar",
          "size": 20149,
          "sha512": "6d97bcf67997a6283823e78a5e7555a7495130bcfc66f59a6c4fb6a6df59c24b8bc108faf08ed7c135c58780dfe96bfb2c54ffd696512f90f037d0b61c8a1af8",
          "sha256": "7dafdc1c8310cc2a958c0973b744fb4cbfbff23fc5527cfb7c68475972641ec4",
          "sha1": "6b4c30473ea370c601db0a8ad2a6a50027543ab9",
          "md5": "1e14d9e18b80139ad6dbfcc51968f983"
        }
      ]
    }
  ]
}
