{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-badges-SNAPSHOT/ktx-datetime-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchosarm64-0.4.0-fix-badges-SNAPSHOT.klib",
          "size": 34685,
          "sha512": "f45f3daec865c771a1c6491afd8f8a76689523551f844f907755ee3a0680d6e7242dbe85b2b3594203fddbcc4819f67f7a377c2c65c3eb33e475a67520fb1321",
          "sha256": "d84a3bd386febb62aea33c0f2139b03f45fd9e275e6aed88dc5ffe1810d2b8d9",
          "sha1": "8bba1f799bcb908d529f50fbf6aa671afbc07695",
          "md5": "412664ef746e8d3547e046efbd98e1e5"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchosarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchosarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "63b480c83f5f35ced0e51aa0fbaf2943b5fa4f8c28470d169c95bab8160d34ffcbee73ddaf79dd67efcc7da7e882b7cf71cc0b491886e07749d62706d54ce6a7",
          "sha256": "3a24d0173b38e824a886df1ed7b2b038b5c46b5a870d7afceafda0d7f5d6aac3",
          "sha1": "11afec218978e76912d8667ecc9a85d57441246d",
          "md5": "9857cfb593675d4bfb3c7cc47209ce4c"
        }
      ]
    }
  ]
}
