{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-timezone-picker-SNAPSHOT/ktx-datetime-0.3.1-add-timezone-picker-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-timezone-picker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-timezone-picker-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.3.1-add-timezone-picker-SNAPSHOT.klib",
          "size": 14614,
          "sha512": "7dfc9c9b9df8cf134d256a360ca07024287d955040e50644782d29ab10a63f31770e621ea5693bde7f8e6c4ee3977e2174f0b4a9d0546e89956d910435861b0e",
          "sha256": "59c699b40b6b0d7cc3575de8e93eb22ddd7c5500733532d9ea3e53fcb4d88a03",
          "sha1": "a141d829413f03acc99679384c1fded163f794e4",
          "md5": "142377dd3e935949194507a8dffe5136"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-timezone-picker-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.3.1-add-timezone-picker-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.3.1-add-timezone-picker-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c666fd3b83ddc7764dbfab648f0a37b02a6177efe131ae56c21acfe47929052303b3780071a1d3662e0dfd10c660374d493189c3d57aa271f8ba7e1bf3557f2a",
          "sha256": "025e409fee37ca5a0efde7edaff2d51c38f231bf9633fd5b5bcc1f65b5d407cc",
          "sha1": "1acd208ac0828506a5ae193b3e861db8608d7a5b",
          "md5": "22394604e98583aa690fc3b6c9a3508c"
        }
      ]
    }
  ]
}
