{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "65d3ce3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-65d3ce3.jar",
          "url": "antibytes-gradle-utils-65d3ce3.jar",
          "size": 9568,
          "sha512": "b7aefcfdf501eb25c843b6d0e06bb4c84692c67ca81904016df604c94cad0b24a2f119a1ad51093f32fb3f1de2b5113f0af184992018c8ad546809aba7b1fae7",
          "sha256": "22eb3643807612ac8d4286b8c9c8ac62b0918ef7592e63314840b298a1bbfbe0",
          "sha1": "54434a9b7678a635d02b46cd899aa09218d0593c",
          "md5": "6b327b87a9c70144acaf2b850cfcb0ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-65d3ce3.jar",
          "url": "antibytes-gradle-utils-65d3ce3.jar",
          "size": 9568,
          "sha512": "b7aefcfdf501eb25c843b6d0e06bb4c84692c67ca81904016df604c94cad0b24a2f119a1ad51093f32fb3f1de2b5113f0af184992018c8ad546809aba7b1fae7",
          "sha256": "22eb3643807612ac8d4286b8c9c8ac62b0918ef7592e63314840b298a1bbfbe0",
          "sha1": "54434a9b7678a635d02b46cd899aa09218d0593c",
          "md5": "6b327b87a9c70144acaf2b850cfcb0ae"
        }
      ]
    }
  ]
}
