{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "14970ca-remove-fat-jar",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-14970ca-remove-fat-jar.jar",
          "url": "antibytes-gradle-utils-14970ca-remove-fat-jar.jar",
          "size": 9568,
          "sha512": "d32192c48bce2d127e3107e49ed5b3c02ea566e15ae437af647c8dc59a07026f93e3269d7ce46d9b4389017c406fa31cc4f1cf8b84153ff11967c0f5997bbf70",
          "sha256": "5e6ece2a7e35b2d814c2928a3bad20f880fc3fe89caf958ba07c7b6727a601b6",
          "sha1": "daa40394c7220f77be7b7c907f912689d8331db7",
          "md5": "1bb3b6888d0864de0aacbf65c8a146bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-14970ca-remove-fat-jar.jar",
          "url": "antibytes-gradle-utils-14970ca-remove-fat-jar.jar",
          "size": 9568,
          "sha512": "d32192c48bce2d127e3107e49ed5b3c02ea566e15ae437af647c8dc59a07026f93e3269d7ce46d9b4389017c406fa31cc4f1cf8b84153ff11967c0f5997bbf70",
          "sha256": "5e6ece2a7e35b2d814c2928a3bad20f880fc3fe89caf958ba07c7b6727a601b6",
          "sha1": "daa40394c7220f77be7b7c907f912689d8331db7",
          "md5": "1bb3b6888d0864de0aacbf65c8a146bc"
        }
      ]
    }
  ]
}
