{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "25db6c8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-25db6c8.jar",
          "url": "antibytes-gradle-test-utils-25db6c8.jar",
          "size": 15106,
          "sha512": "e56e41860a0c478f5b3ab29b8b91fbce4e6ce05b105201a4763c5a467a17dd2f08b0c00b25b973118a47e1767e2d619a16b48ea33e504fe36ab67e5098054651",
          "sha256": "6da62f9b3e92bb5a2edcc0e51b52189533d2a60ad5ab235494bfe177ff74cb77",
          "sha1": "ddf83f6f989b822033fca2855e5c357857859690",
          "md5": "bc6ad2d5550e7facd013b3c7ce31f2b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-25db6c8.jar",
          "url": "antibytes-gradle-test-utils-25db6c8.jar",
          "size": 15106,
          "sha512": "e56e41860a0c478f5b3ab29b8b91fbce4e6ce05b105201a4763c5a467a17dd2f08b0c00b25b973118a47e1767e2d619a16b48ea33e504fe36ab67e5098054651",
          "sha256": "6da62f9b3e92bb5a2edcc0e51b52189533d2a60ad5ab235494bfe177ff74cb77",
          "sha1": "ddf83f6f989b822033fca2855e5c357857859690",
          "md5": "bc6ad2d5550e7facd013b3c7ce31f2b7"
        }
      ]
    }
  ]
}
