{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-relaxer-SNAPSHOT/kmock-0.3.0-rc01-fix-relaxer-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-relaxer-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-relaxer-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-relaxer-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "fe5a8f2edfdd67f07fd07985e4918b7429f69f56c5b3c97c82d526163076d38c6a80bae94c98c1260545e498301db3f0fd7514e57f367c167da01c0a52d24b97",
          "sha256": "5336f7218d90d0ff0bd28540a8f813f9d9f665d5e8f74a65a011ac3c47ccda60",
          "sha1": "943dee310969ac95c9a18d26d8277dbb0ff146e9",
          "md5": "cea40c340ed214845b7ccf8d04419f01"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-relaxer-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-relaxer-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "fe5a8f2edfdd67f07fd07985e4918b7429f69f56c5b3c97c82d526163076d38c6a80bae94c98c1260545e498301db3f0fd7514e57f367c167da01c0a52d24b97",
          "sha256": "5336f7218d90d0ff0bd28540a8f813f9d9f665d5e8f74a65a011ac3c47ccda60",
          "sha1": "943dee310969ac95c9a18d26d8277dbb0ff146e9",
          "md5": "cea40c340ed214845b7ccf8d04419f01"
        }
      ]
    }
  ]
}
