{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-fix-stackoverflow-SNAPSHOT/kmock-0.3.0-rc02-fix-stackoverflow-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-fix-stackoverflow-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc02-fix-stackoverflow-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc02-fix-stackoverflow-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "8b9ad2a5f4f128816a6913b9bbdbd338a7d05384501d796cc14ef2885f09aa047f83652bfefa6e9bf26f090be530f6fba519af676fece4887f7f95d4e3f1e0ee",
          "sha256": "93a75dcdf5fa8eea8c06e601d3101666f9a193b61c9211bf1ea86ab61fcc9608",
          "sha1": "090f77cd91cf8a557cfd31b3bd29f5cce8af7477",
          "md5": "1a8c0f19233d1bab57f08a0dcf0a5b8e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc02-fix-stackoverflow-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc02-fix-stackoverflow-SNAPSHOT.klib",
          "size": 216790,
          "sha512": "8b9ad2a5f4f128816a6913b9bbdbd338a7d05384501d796cc14ef2885f09aa047f83652bfefa6e9bf26f090be530f6fba519af676fece4887f7f95d4e3f1e0ee",
          "sha256": "93a75dcdf5fa8eea8c06e601d3101666f9a193b61c9211bf1ea86ab61fcc9608",
          "sha1": "090f77cd91cf8a557cfd31b3bd29f5cce8af7477",
          "md5": "1a8c0f19233d1bab57f08a0dcf0a5b8e"
        }
      ]
    }
  ]
}
