{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT/kmock-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 381472,
          "sha512": "45f89e42abf09a049300d75ec55663497eb46b63ccf56adf003af5fe8e8c82bd98e66c84a20666a95e8a54f3a069129d33b6f25680b52daab803c144e462c2c6",
          "sha256": "ea3c21b33c64373d4cbd9aa17a940dccba7360ded28c0a1e8c686a0f8d17197b",
          "sha1": "81609055b909744651b21e3fd91ac1e479aeae62",
          "md5": "fd4ca01ae4128046d01cb42af98de43b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 381472,
          "sha512": "45f89e42abf09a049300d75ec55663497eb46b63ccf56adf003af5fe8e8c82bd98e66c84a20666a95e8a54f3a069129d33b6f25680b52daab803c144e462c2c6",
          "sha256": "ea3c21b33c64373d4cbd9aa17a940dccba7360ded28c0a1e8c686a0f8d17197b",
          "sha1": "81609055b909744651b21e3fd91ac1e479aeae62",
          "md5": "fd4ca01ae4128046d01cb42af98de43b"
        }
      ]
    }
  ]
}
