{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "a4b666e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-a4b666e.jar",
          "url": "antibytes-gradle-utils-a4b666e.jar",
          "size": 9471,
          "sha512": "91be9447deaf4545f9ec422f150e33fffac9bf624711dd19109e1a9ec8972efebb264bfe771f074b82e0b38c61cada330ff67f365f87e63b58606019ae1fefd9",
          "sha256": "5c69164b4c7468ed47e59d2af7788ab0004e14639673816d3c2a4146ab7197c7",
          "sha1": "6c8f3ea5efff98130210a10c4336975dae081f8e",
          "md5": "dac9bb4672f61eada758247b068cf421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-a4b666e.jar",
          "url": "antibytes-gradle-utils-a4b666e.jar",
          "size": 9471,
          "sha512": "91be9447deaf4545f9ec422f150e33fffac9bf624711dd19109e1a9ec8972efebb264bfe771f074b82e0b38c61cada330ff67f365f87e63b58606019ae1fefd9",
          "sha256": "5c69164b4c7468ed47e59d2af7788ab0004e14639673816d3c2a4146ab7197c7",
          "sha1": "6c8f3ea5efff98130210a10c4336975dae081f8e",
          "md5": "dac9bb4672f61eada758247b068cf421"
        }
      ]
    }
  ]
}
