{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/400858f-add-mock-name-collision-resolver-SNAPSHOT/kmock-400858f-add-mock-name-collision-resolver-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "400858f-add-mock-name-collision-resolver-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-400858f-add-mock-name-collision-resolver-SNAPSHOT.jar",
          "url": "kmock-jvm-400858f-add-mock-name-collision-resolver-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "42bf569adfc05b911ca3b537955c429ed0d6bb7a799de182cbc4c11621380c1e742148057a05df3575260d49b2ccebea654de5a9529e8c7aa4687c258a3366f8",
          "sha256": "7db10da30625881f80eab4c739c1af615840e3df16ee1394e1b16999b101cfe3",
          "sha1": "0e42e5f9d9a01d4a3b2c9ae3d95fa23538077966",
          "md5": "5e72498056b58b7e7f8ab925ab479b97"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-400858f-add-mock-name-collision-resolver-SNAPSHOT.jar",
          "url": "kmock-jvm-400858f-add-mock-name-collision-resolver-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "42bf569adfc05b911ca3b537955c429ed0d6bb7a799de182cbc4c11621380c1e742148057a05df3575260d49b2ccebea654de5a9529e8c7aa4687c258a3366f8",
          "sha256": "7db10da30625881f80eab4c739c1af615840e3df16ee1394e1b16999b101cfe3",
          "sha1": "0e42e5f9d9a01d4a3b2c9ae3d95fa23538077966",
          "md5": "5e72498056b58b7e7f8ab925ab479b97"
        }
      ]
    }
  ]
}
