{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.0-fix-publishing-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.0-fix-publishing-SNAPSHOT.jar",
          "size": 33078,
          "sha512": "e5aa5fe8444a6e75788e18d470bc297b029fcf4b4c9a7cd6f18ec378e0e223bfe200b8fe9f95071d7461d991c11053290c25771480be73e32525c458c9f36776",
          "sha256": "db77b34890430df14af38fc7eca16d956e1934b5e7df3890da62098706935d48",
          "sha1": "8d872af02b21908ac527f815f704be3c64c3b864",
          "md5": "7e95f91fe0dc1324b847e87f60e74d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.0-fix-publishing-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.0-fix-publishing-SNAPSHOT.jar",
          "size": 33078,
          "sha512": "e5aa5fe8444a6e75788e18d470bc297b029fcf4b4c9a7cd6f18ec378e0e223bfe200b8fe9f95071d7461d991c11053290c25771480be73e32525c458c9f36776",
          "sha256": "db77b34890430df14af38fc7eca16d956e1934b5e7df3890da62098706935d48",
          "sha1": "8d872af02b21908ac527f815f704be3c64c3b864",
          "md5": "7e95f91fe0dc1324b847e87f60e74d36"
        }
      ]
    }
  ]
}
