{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-ktor-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "6ce677ebabd81936679ee8b8201389eafa283c463e2961a4f3e2addd874db9a5afe0e8288ab29f7fa7be3f942a439bc894b5d1ac983ca9d658146d2c56b22270",
          "sha256": "0a6a6dc66071f4afc78d5448b6d04fbc3e8ab46bf0af94ac9cfe318c1e449ea9",
          "sha1": "2a470d04dd44d7399d65efed76ac04858e31364d",
          "md5": "4c21dbdeddf71fcae6ccc0ede4f3853e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "6ce677ebabd81936679ee8b8201389eafa283c463e2961a4f3e2addd874db9a5afe0e8288ab29f7fa7be3f942a439bc894b5d1ac983ca9d658146d2c56b22270",
          "sha256": "0a6a6dc66071f4afc78d5448b6d04fbc3e8ab46bf0af94ac9cfe318c1e449ea9",
          "sha1": "2a470d04dd44d7399d65efed76ac04858e31364d",
          "md5": "4c21dbdeddf71fcae6ccc0ede4f3853e"
        }
      ]
    }
  ]
}
