{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-bump-mkdocs-SNAPSHOT/core-0.3.1-bump-mkdocs-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-bump-mkdocs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.3.1-bump-mkdocs-SNAPSHOT.klib",
          "size": 108846,
          "sha512": "df73b13acf79f694fb4b5caf5b546b5297021faa1a9613f0886e41318880f7e43e3fbf6295a58c744c1c80363c46e145a77d0c17fe26009a88313dde51f13fa8",
          "sha256": "76b595c5138e758868916665d81759b31c3e75a8b9ee8a8b220435937ab25b1a",
          "sha1": "77c2094150249f1ca0e677bb15a18f2760f8cedd",
          "md5": "043afbde247a2e5ae3fe083bdb1480e3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.3.1-bump-mkdocs-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.3.1-bump-mkdocs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "34857b640adb5d5dac7570ca9b3970f635a883bea08bcdf3a51ff073b5c39ff2709d60e09a956f3def04f97251fc8ba821d3e33b26ac99b8bbbeefe7a316fbec",
          "sha256": "4f3509f4f36d7f41b9f438577317bebdbee5eb6f68b47fa1d17ec2752152a8cb",
          "sha1": "22c575842b5009ea2104e76d734968cfab7a6236",
          "md5": "7b8321978eac1f4ec04f5d5f85a4b015"
        }
      ]
    }
  ]
}
