{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "2709ef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-2709ef8.jar",
          "url": "antibytes-grammar-tools-2709ef8.jar",
          "size": 39373,
          "sha512": "839b97d54042ad0e88ff0b2f390272f42b8136b556c6d85f3921a4edbe9d2abd7004a126dcba773e8c84ddf5d1630e69f707fe1b7b02d19d7ca5c4b379844aa6",
          "sha256": "fb6c96c167130548c89f63e077c0240a47529ce2134d2c3776c72f5f9b161c64",
          "sha1": "823f7209efbc070a91bde47e572cca78437fdd01",
          "md5": "2efdc9c4b40081e3b9ef333570babd27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-2709ef8.jar",
          "url": "antibytes-grammar-tools-2709ef8.jar",
          "size": 39373,
          "sha512": "839b97d54042ad0e88ff0b2f390272f42b8136b556c6d85f3921a4edbe9d2abd7004a126dcba773e8c84ddf5d1630e69f707fe1b7b02d19d7ca5c4b379844aa6",
          "sha256": "fb6c96c167130548c89f63e077c0240a47529ce2134d2c3776c72f5f9b161c64",
          "sha1": "823f7209efbc070a91bde47e572cca78437fdd01",
          "md5": "2efdc9c4b40081e3b9ef333570babd27"
        }
      ]
    }
  ]
}
