{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "9ea4b3d-change-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-metadata-all.jar",
          "url": "test-utils-annotations-9ea4b3d-change-fixture-SNAPSHOT-all.jar",
          "size": 4917,
          "sha512": "8f6c9da58a9089aabc0d063194c617a91d396bc45fec5b11c1782ac538147a3e22ae9b8b1ee30a34b52bfed3f914ef9db1b23385e1677ea3db3615bc89ebc99c",
          "sha256": "f2dd8bee048a3a8a6f688f4bf6ebd5ea6ebc82745d546e80d355b15e973c47bf",
          "sha1": "e079008952d9c77af4ae9c7495d44dce49df8e16",
          "md5": "097af0d1810c810e3f3ac4cd164a26e4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations.jar",
          "url": "test-utils-annotations-9ea4b3d-change-fixture-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "d1aec3099be949d3d851f4015f26476b0ac9170d490c56b11f8d8c9d4913428b2f47a8248079a3ca0dac368076c9d6411789eb75ded03ae9fed1093ad7c7921a",
          "sha256": "a02481098ab052f4100bc025d877f9d8cffd3cf2843964c5b1274a649a4a5056",
          "sha1": "9edfe2acfcfad07ff2332448ec15b4d079521966",
          "md5": "7fcb2877c12f3ae5bae20227ff4d007d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-android-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-android-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-js-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-js-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-jvm-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-jvm-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/9ea4b3d-change-fixture-SNAPSHOT/test-utils-annotations-linuxx64-9ea4b3d-change-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "9ea4b3d-change-fixture-SNAPSHOT"
      }
    }
  ]
}
