{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/422ab00-bump-antibytes-SNAPSHOT/test-utils-annotations-422ab00-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "422ab00-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "6fdd6ea0298dabb9bcfce4a60d6ac5f20e20e1e0af9603091c6d287b7e835889b1e6d5cbc33a2a563e4e44c6906d39e5f5797cf2f0a49a9d0cea9c5921862321",
          "sha256": "e761286919bf38f793bcc52abbb52fa69fd7dbf9e4d7793a7fc120234ea9c572",
          "sha1": "310081ede7081714344ad4dd828c5eddeeffc854",
          "md5": "3b585051d1e202aa8719d67cf02d125d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-422ab00-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "6fdd6ea0298dabb9bcfce4a60d6ac5f20e20e1e0af9603091c6d287b7e835889b1e6d5cbc33a2a563e4e44c6906d39e5f5797cf2f0a49a9d0cea9c5921862321",
          "sha256": "e761286919bf38f793bcc52abbb52fa69fd7dbf9e4d7793a7fc120234ea9c572",
          "sha1": "310081ede7081714344ad4dd828c5eddeeffc854",
          "md5": "3b585051d1e202aa8719d67cf02d125d"
        }
      ]
    }
  ]
}
