{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/30769ee-change-setup-SNAPSHOT/test-utils-coroutine-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-macosarm64-30769ee-change-setup-SNAPSHOT.klib",
          "size": 10147,
          "sha512": "4a4b143a047f59d96264d5d05d5bf52b7cbaaf5bd23b89980f0026caccb8c88e6a1437953dc3dfe154d961816107268bf4b496c7f842488c7b1071f37ac4d7f9",
          "sha256": "16a4d4623cb52060f0913a982c003f1801268bc32ae22214c56a0753e5f6d04e",
          "sha1": "95c0c2c0ece45d7187e908f02792185b6e1b4163",
          "md5": "75452055926e257bb097177f4545d7bc"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-macosarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-macosarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e9765b087aca8f840891345f56c718d5fe0dd684d8122fd5070da568bb545876fc9651a1111aa656924d5b8fcff6d39ee37a0484f9958f4b558910c92c23117f",
          "sha256": "38252ff8f265ca3ae2fc107540506dd092d69511a1fa51e2a6f4fac33057bbfa",
          "sha1": "739afd2807967b59a3db4b121c14d376f6655de3",
          "md5": "2bd05fa4ff1f8930b2d0a55c9019c960"
        }
      ]
    }
  ]
}
