{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/bff1152-bump-antibytes-SNAPSHOT/test-utils-ktor-bff1152-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "bff1152-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-bff1152-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-bff1152-bump-antibytes-SNAPSHOT.klib",
          "size": 11802,
          "sha512": "17193908c460a914fce39eaa62dc0a775329dfdd8d365ba615712de93bb6ebaf49af0c54a75351afedb5e9d67fe7297c8b5219cde3ef3d4dc2825985bbcae44e",
          "sha256": "be65937cfc658e1a57867d8d80c656ca9a2c09a2ac4d2462561362967d953f17",
          "sha1": "d02594c168c3f525ae0ee9341db9eaccc489dcf6",
          "md5": "03e56a991369a0f0da3079460aca4b8d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-bff1152-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-bff1152-bump-antibytes-SNAPSHOT.klib",
          "size": 11802,
          "sha512": "17193908c460a914fce39eaa62dc0a775329dfdd8d365ba615712de93bb6ebaf49af0c54a75351afedb5e9d67fe7297c8b5219cde3ef3d4dc2825985bbcae44e",
          "sha256": "be65937cfc658e1a57867d8d80c656ca9a2c09a2ac4d2462561362967d953f17",
          "sha1": "d02594c168c3f525ae0ee9341db9eaccc489dcf6",
          "md5": "03e56a991369a0f0da3079460aca4b8d"
        }
      ]
    }
  ]
}
