{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "f08e47d-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-f08e47d-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-gradle-utils-f08e47d-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 9568,
          "sha512": "fb80fded19c58d9f2283394d7d6424ce1b5da81f6776d43dfa0dd1e3430a5a124f9afee6cc4d61c831ab0de51dc7d118fce167bd4332ae749b0194706f69d316",
          "sha256": "9a621337af84bdc79ea718729d8b322044def082dce016bcfbcb00f450dbe9ad",
          "sha1": "e45713e06fd372f452a22e38d63cb741710b07d6",
          "md5": "930a3a7c24b9acc2bb0da71e5be54710"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-f08e47d-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-gradle-utils-f08e47d-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 9568,
          "sha512": "fb80fded19c58d9f2283394d7d6424ce1b5da81f6776d43dfa0dd1e3430a5a124f9afee6cc4d61c831ab0de51dc7d118fce167bd4332ae749b0194706f69d316",
          "sha256": "9a621337af84bdc79ea718729d8b322044def082dce016bcfbcb00f450dbe9ad",
          "sha1": "e45713e06fd372f452a22e38d63cb741710b07d6",
          "md5": "930a3a7c24b9acc2bb0da71e5be54710"
        }
      ]
    }
  ]
}
