{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f8d6e50-bump-workflows-SNAPSHOT/test-utils-annotations-junit4-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 11351,
          "sha512": "eab01ccdc633125109f8844313c375f7821d74fd72713a110dcd21edadaadb67d0f9a4f42aea27872ff5873c6eca1367eabd6516f3e6f718c879785be3d3b229",
          "sha256": "ac318de8cc81066e0b59e7ee3b0d09e9f2fe1fa5288b0f460273a0d91e085660",
          "sha1": "8461e6ece21752696e7b9b24da62772ef6133a3b",
          "md5": "eb05bdc9218caeac1aafb0b1c4779775"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1dc40bb2360798f9404ccae8b6715df632e41ab95d9e5c31f5e87364026ebc778f4f892a80680cb438805dc99daca507967341591a93d7708fccaa067542122e",
          "sha256": "95d0c0e3e1ee3e9d511a52856a835a89b7f39521b3969583e44e1c9a3ea1565c",
          "sha1": "bd71d850de71483f7cb66325d365cedb944efe38",
          "md5": "2a433bb998056bb03d6bb890448e6fc7"
        }
      ]
    }
  ]
}
