{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/ef3a5b1-bump-updates-SNAPSHOT/test-utils-resourceloader-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchosx64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 14231,
          "sha512": "0ab87c5a51b2c96ac46832cb3da91ea1d3f1b8465ebbfea0474f589963de7333591f2d1ef5bceee015ff35107a22be1a1970e7910b7f4aed5e96741e2baee499",
          "sha256": "0ff9cb7f51546c281cb87c396a7462fdfc816fd4828a7a784596b9d38ef9bfc3",
          "sha1": "430e9882ad770ad056a1efc7e7200e0e5770155e",
          "md5": "9b50dc62a3ffde143350f6de470dc7e4"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-resourceloader-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-watchosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9edaa34b070547706188770c2da2f1521866f314820c21cddd0964f6ac57f7b4f6cad3752b8ab3f73578b9037ac17dc0a52ae8681d3811068d373b0c58fd92c2",
          "sha256": "25e7954062341ed1c01243a6de697e5c39f11f7004a6b9cc94ecc3f9eb9b9760",
          "sha1": "9b2db7748881e471783e5e68b1955da5fe84637f",
          "md5": "635aa0d8d546a5886bcbf13c852e592d"
        }
      ]
    }
  ]
}
