{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c448ecb-bump-antibytes-SNAPSHOT/test-utils-ktor-c448ecb-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c448ecb-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-c448ecb-bump-antibytes-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "0aa717060789c7a313105b19719e82694666b8211ca5dfc75800b746c7b6c271e83150058cf561411a08a268ab5a9c0bd736bd394bd7f82550189c63bd41c6d0",
          "sha256": "3fed6ae1198b15875eaebfe33d88cc3c798b1a23895e032d4dc669f5bc410409",
          "sha1": "b3227952a044414d0ae0144177efb78e6df1de21",
          "md5": "3ba382b674049f4f0578a9e182ed143b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-c448ecb-bump-antibytes-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "0aa717060789c7a313105b19719e82694666b8211ca5dfc75800b746c7b6c271e83150058cf561411a08a268ab5a9c0bd736bd394bd7f82550189c63bd41c6d0",
          "sha256": "3fed6ae1198b15875eaebfe33d88cc3c798b1a23895e032d4dc669f5bc410409",
          "sha1": "b3227952a044414d0ae0144177efb78e6df1de21",
          "md5": "3ba382b674049f4f0578a9e182ed143b"
        }
      ]
    }
  ]
}
