{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/13f09a8-add-more-sources-SNAPSHOT/test-utils-ktor-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-watchosarm64-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 15061,
          "sha512": "d91136e0ae8b936f77f4e1f5c15dc114ec73cc2fffc5d93be97eb66df334bb2d8b25ef04b17faec9d61e1c446b07a9628c5338a39474dc5867b68c0d7e416d80",
          "sha256": "d1cdb7e08a69a4ff6cd4a19eec296287510cab4fe503b9fb9e7289ee61bc3c7a",
          "sha1": "18fea3431d6a0c6c4ec22e789c11b1528a0c7589",
          "md5": "69c11fbfaf79b13ff172384dbddb08bf"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-watchosarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-watchosarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b37256a4a9378b9def62fd1d935945157c24443710f5e3fb9ccf0a0e637759c9358e13c2733d82eef8c94475b810c5dcc09da8224ace02d35d781a72ce9528eb",
          "sha256": "48080c9acec91115c5436ee6f023dc2853a76e801b96e70261a590a01ae63b4a",
          "sha1": "ba1f51336c577ee952df6c9f707a1a2b97e49c01",
          "md5": "5636a1b1c061905a3d7bbc85a00edf13"
        }
      ]
    }
  ]
}
