{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-bridge",
    "version": "88c96ec-add-antibytes-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-88c96ec-add-antibytes-settings-plugin.jar",
          "url": "antibytes-dependency-bridge-88c96ec-add-antibytes-settings-plugin.jar",
          "size": 38501,
          "sha512": "aba5494b1422dcc5642966b5f2b6b2a0abc8c0d6916e88df4a640ef8dcda7fc7d3a8bd21dc2ffa7ca8b4d7023f3258b75f48d9e9e9188f04146af2323dc8decd",
          "sha256": "50a6eeafa638345dbd45f73e0ca8ddc6c59d760bbe70c054275242a1cfb2394d",
          "sha1": "1bc9a0a28a9854e2a3e50554aacc0b35ea52d4eb",
          "md5": "f1ddb0f6c9f77d11cdad4e09d594a067"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-88c96ec-add-antibytes-settings-plugin.jar",
          "url": "antibytes-dependency-bridge-88c96ec-add-antibytes-settings-plugin.jar",
          "size": 38501,
          "sha512": "aba5494b1422dcc5642966b5f2b6b2a0abc8c0d6916e88df4a640ef8dcda7fc7d3a8bd21dc2ffa7ca8b4d7023f3258b75f48d9e9e9188f04146af2323dc8decd",
          "sha256": "50a6eeafa638345dbd45f73e0ca8ddc6c59d760bbe70c054275242a1cfb2394d",
          "sha1": "1bc9a0a28a9854e2a3e50554aacc0b35ea52d4eb",
          "md5": "f1ddb0f6c9f77d11cdad4e09d594a067"
        }
      ]
    }
  ]
}
