{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/13d1870-change-api-SNAPSHOT/kmock-13d1870-change-api-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "13d1870-change-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-13d1870-change-api-SNAPSHOT.jar",
          "url": "kmock-jvm-13d1870-change-api-SNAPSHOT.jar",
          "size": 176616,
          "sha512": "fdafa1572ee41c94f08f14b98586a29a3de38718bab81c47d88d37e73b055f2208e94bf8c3e629b4e25e86545040e0639d16dbed1cd468534911656318149409",
          "sha256": "08c92530793796711ddccd702a1cb18ce8941f330e6346fd18f5c743196cf231",
          "sha1": "4877d79b7f2b1a9186350cf9a2e9395456938983",
          "md5": "0b577cedc2a98c648ff1d6e34b260601"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-13d1870-change-api-SNAPSHOT.jar",
          "url": "kmock-jvm-13d1870-change-api-SNAPSHOT.jar",
          "size": 176616,
          "sha512": "fdafa1572ee41c94f08f14b98586a29a3de38718bab81c47d88d37e73b055f2208e94bf8c3e629b4e25e86545040e0639d16dbed1cd468534911656318149409",
          "sha256": "08c92530793796711ddccd702a1cb18ce8941f330e6346fd18f5c743196cf231",
          "sha1": "4877d79b7f2b1a9186350cf9a2e9395456938983",
          "md5": "0b577cedc2a98c648ff1d6e34b260601"
        }
      ]
    }
  ]
}
