{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit5-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-tvosarm64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 7060,
          "sha512": "30138c60d8cf906bd0b6867f306bcffed98fb8fd66811921d40f7c6d5f7453946cc1514be288ae98e5fb549c023fbe6a01461d2bc2a47784dc2fc4c2b8eee0ab",
          "sha256": "8c2a8ad0fd931489c8ba3cdc390065a1fa5e28a46f8135bbff2a1126644025a4",
          "sha1": "1977fce2deb5ee0b3a570f2738af68b9baccef14",
          "md5": "c67929bdcf0c17b85b515f593b2db8a6"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-tvosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-tvosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b888f9257b030397b937523f643854ec98f820c9f8afb7e8b03bf52d564494349a5d3e567781833abebb8518948e9d0329eb906acd05534f413d542d4969971f",
          "sha256": "6f4785de7793d2f0e17979460f3767804d9a8a87361ae348a0f95a546f3fb01c",
          "sha1": "49951c4ba7fa06e79c35867439c049625f933fe9",
          "md5": "5d8a14c7053b8c153a37ee2dd90cc564"
        }
      ]
    }
  ]
}
