{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "58280ee-add-custom-component-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-58280ee-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-58280ee-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "7f60110dffa5bccb2f66faca5bef29ea492c6c3f568f8ca11029cc82cda1cccdac5767292935499b7164837dd89a4b9e9ea479c322738d0914d19081bd357ca3",
          "sha256": "ffcf49db8a43bdb350930bc7a7f22cfb81de3c3def2487aabe153a130fa2aca1",
          "sha1": "bc061a20f140a9dc675ce0d1471486a21540b367",
          "md5": "96e6679693bde33ed521cd91edaa22d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "58280ee-add-custom-component-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-58280ee-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-58280ee-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "7f60110dffa5bccb2f66faca5bef29ea492c6c3f568f8ca11029cc82cda1cccdac5767292935499b7164837dd89a4b9e9ea479c322738d0914d19081bd357ca3",
          "sha256": "ffcf49db8a43bdb350930bc7a7f22cfb81de3c3def2487aabe153a130fa2aca1",
          "sha1": "bc061a20f140a9dc675ce0d1471486a21540b367",
          "md5": "96e6679693bde33ed521cd91edaa22d5"
        }
      ]
    }
  ]
}
