{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/c8e7c91-change-workflows-SNAPSHOT/test-utils-c8e7c91-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "c8e7c91-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-c8e7c91-change-workflows-SNAPSHOT.klib",
          "size": 7962,
          "sha512": "4a9c4a745a177b65290a8b6e1f4e45afc70018250e9ae064673b79e21097a78c70fdbb53a13b425478520c3b96d781a60435d7f3e70860d6cf3e70419e57b82c",
          "sha256": "c231e0f0fe7d17b3c8feebc5684c52f4f2e23e8c895ea9c6ab9bb1bafb5817ae",
          "sha1": "bd56568f4ff847bf496cb11403f05f4758bc54ac",
          "md5": "21bf8685971662cd968ba414c97652e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d8e17d884d6ce14af24238bae86d5fef30632c35ae9c01e642d5a7f5294ff2b46e84c2b11b71ebe9622e8de57240224f35502f14b17364fbe63990205ec80b10",
          "sha256": "4de81c9d55e3423bda87286e45a5f6b7b235824b4da28379d16e4c1554c07ba3",
          "sha1": "6af20d296bbfc669cb2578866772497ef20b64a9",
          "md5": "ed524c71541048811052dd0ff2731cec"
        }
      ]
    }
  ]
}
