{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-5d5a54a-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "5d5a54a-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "0b56cfeb4810870b9937d0c8e05268d1d53856416ce42d6ae4ba33dbbb2b30005d1267448dc7a6a8fb11c996ffd9e63cbc099894ef06bc5666948032068f0b21",
          "sha256": "ed6c1451a716bb71260993bd16c7b5c01d177cfa3544cd61f6c12d601884734a",
          "sha1": "502d5bbae7b67c44be8a6abf5cb32a8fa881c39f",
          "md5": "c96a6166b22bd233ac71f80c4486366b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "0b56cfeb4810870b9937d0c8e05268d1d53856416ce42d6ae4ba33dbbb2b30005d1267448dc7a6a8fb11c996ffd9e63cbc099894ef06bc5666948032068f0b21",
          "sha256": "ed6c1451a716bb71260993bd16c7b5c01d177cfa3544cd61f6c12d601884734a",
          "sha1": "502d5bbae7b67c44be8a6abf5cb32a8fa881c39f",
          "md5": "c96a6166b22bd233ac71f80c4486366b"
        }
      ]
    }
  ]
}
