{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "2ad2632",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-2ad2632.jar",
          "url": "antibytes-grammar-tools-2ad2632.jar",
          "size": 39410,
          "sha512": "39ed932eab9643bbcb338f221d83d25570508b3d3b68650711437f5f7d0390fd4901bef297b30d9e544cf0c85ea5517e33fd16451e71f3032c7f7fe187153c8a",
          "sha256": "e708925cb9d1374618b691ad237cc8313094b9395bc94426af2c305e2338e140",
          "sha1": "453659c812be50299f0329d849dfe32e5fe35ddb",
          "md5": "911d4fd0e9f6c18da4e31a0a88cf2b1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-2ad2632.jar",
          "url": "antibytes-grammar-tools-2ad2632.jar",
          "size": 39410,
          "sha512": "39ed932eab9643bbcb338f221d83d25570508b3d3b68650711437f5f7d0390fd4901bef297b30d9e544cf0c85ea5517e33fd16451e71f3032c7f7fe187153c8a",
          "sha256": "e708925cb9d1374618b691ad237cc8313094b9395bc94426af2c305e2338e140",
          "sha1": "453659c812be50299f0329d849dfe32e5fe35ddb",
          "md5": "911d4fd0e9f6c18da4e31a0a88cf2b1b"
        }
      ]
    }
  ]
}
