{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-helper",
    "version": "bb86acb-add-snapshot-supression-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-helper-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "size": 55371,
          "sha512": "1e022dce4d6684e581c35d06773e03894bb94751628f9a70b904e3a50b755bc3002e21e568d861087f6c13c44ef636b3d2b3f75d973f283b77cf6a58882f27f8",
          "sha256": "890e877e258f9ae197149cbe65cdda4b013d732b3d44f3c39371c8de8db7a453",
          "sha1": "ad5bb3ffe15251d7a8ec1dac56c173e14796dc69",
          "md5": "8c89d42039f33a8bbea1a54d4d50a82f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bb86acb-add-snapshot-supression-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-helper-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "size": 55371,
          "sha512": "1e022dce4d6684e581c35d06773e03894bb94751628f9a70b904e3a50b755bc3002e21e568d861087f6c13c44ef636b3d2b3f75d973f283b77cf6a58882f27f8",
          "sha256": "890e877e258f9ae197149cbe65cdda4b013d732b3d44f3c39371c8de8db7a453",
          "sha1": "ad5bb3ffe15251d7a8ec1dac56c173e14796dc69",
          "md5": "8c89d42039f33a8bbea1a54d4d50a82f"
        }
      ]
    }
  ]
}
