{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-setup-SNAPSHOT/core-0.4.0-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxmipsel32-0.4.0-bump-setup-SNAPSHOT.klib",
          "size": 105878,
          "sha512": "4567013a33e34810fa5333d7f00bd3ebae18b8fe238327ece3ad8ec98aad3018cefae8013df749875e9360344cf8ca77fe0752903a9e0117f0b6821d854fe6b2",
          "sha256": "f8d28eaa89eb4aaf6c1ae3ce098019cdda370a9efba67bdc217369f8896b6d69",
          "sha1": "f3d5dc63998b932dbfa4ddf2b77fd94478f1f216",
          "md5": "147bd13012340fc2ae0ff708fdc5207a"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxmipsel32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "url": "core-linuxmipsel32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "233a8bb1cfada440b563a596c2096a73002b5de152837ab0b94e8265528cea58fe70bd25ab4cfac022d2ede39f2d57d0eb6c82708a1296ea539eb7a13e1b80d2",
          "sha256": "aa69526ec3f6434b3b241bd28d55e517cc64bccce80aa2c0c80d9a71b87f6809",
          "sha1": "ae79c6c7ed1a17bb6ec56634a9748a5f44a591bb",
          "md5": "b6448200d86ac312bccf7f7b8f075cdf"
        }
      ]
    }
  ]
}
