{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "000887d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-000887d.jar",
          "url": "antibytes-gradle-utils-000887d.jar",
          "size": 9472,
          "sha512": "6245e3534614d831d6be63385a92b31ad3b4f6ff02970bfa2fa021b3bba895354385b487fbb8a8e694bcea8ae283abf4a7bc1b074cb281c85e5c62b56b1e1574",
          "sha256": "bb1530eb6930e3cc8b0a0355f31bed3db3fcc52e2bca46654c26e5552312ebf7",
          "sha1": "5778bd4df077005c2c7021b895f72f9702fa4b7c",
          "md5": "f5dfe105c934b2954d52a4223b4d521c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-000887d.jar",
          "url": "antibytes-gradle-utils-000887d.jar",
          "size": 9472,
          "sha512": "6245e3534614d831d6be63385a92b31ad3b4f6ff02970bfa2fa021b3bba895354385b487fbb8a8e694bcea8ae283abf4a7bc1b074cb281c85e5c62b56b1e1574",
          "sha256": "bb1530eb6930e3cc8b0a0355f31bed3db3fcc52e2bca46654c26e5552312ebf7",
          "sha1": "5778bd4df077005c2c7021b895f72f9702fa4b7c",
          "md5": "f5dfe105c934b2954d52a4223b4d521c"
        }
      ]
    }
  ]
}
