{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/5a5166e-add-class-cracker-SNAPSHOT/kmock-5a5166e-add-class-cracker-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "5a5166e-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-5a5166e-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-5a5166e-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "82d6a0f2351f887644faeb4b12c738650417bdef4ba73f05f3e3777eeb32aa25fe8f4aec517262d3e99dbc4f17ff821232d0614a258a5b1762e37401af147996",
          "sha256": "b38248a50b32c6e6da4b167852fd058aa77aba5e142ac33c5a3d98e262607f71",
          "sha1": "fa6f7ac005a3bdb403c40ea932e996290d372a7f",
          "md5": "0bb032a02ea3afe89ee84985a5d7b1cc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-5a5166e-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-5a5166e-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "82d6a0f2351f887644faeb4b12c738650417bdef4ba73f05f3e3777eeb32aa25fe8f4aec517262d3e99dbc4f17ff821232d0614a258a5b1762e37401af147996",
          "sha256": "b38248a50b32c6e6da4b167852fd058aa77aba5e142ac33c5a3d98e262607f71",
          "sha1": "fa6f7ac005a3bdb403c40ea932e996290d372a7f",
          "md5": "0bb032a02ea3afe89ee84985a5d7b1cc"
        }
      ]
    }
  ]
}
