{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "fb3fdb1-add-snapshot-supression-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-fb3fdb1-add-snapshot-supression-SNAPSHOT.toml",
          "url": "antibytes-dependency-catalog-fb3fdb1-add-snapshot-supression-SNAPSHOT.toml",
          "size": 230831,
          "sha512": "92ebf6aebba775d2a6b701d967695c2bee72a22ec080c306ce931053faf2b84466c1d49eed2a7ed45b090dcbc1596a1e6ffd0b6063d007971d82ff8259096b6f",
          "sha256": "58e9d2078e472f76a41e6747157dc9db616fc9097f74b96d7e78409b90af402c",
          "sha1": "a050911e81e9b6555646f14b496c5b18c1fa0e6b",
          "md5": "2330a8428b7d1a53edff7db77e18e0fd"
        }
      ]
    }
  ]
}
