{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "225ca48-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-gradle-utils-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 9568,
          "sha512": "bed25f75400ecc9c5b1a4ee4ab895c0b1c142ee74bfe62b6d96e23788bcead2a93c8e8618df664a470128d882980f3e51ecc7596c9dc02c5e3914f4454e4f5e6",
          "sha256": "4c477d5d03e8fab824e473ccd55bef3cd3ddb1fbe4fa6589818579dd3e935f82",
          "sha1": "027f6918c32a9b32bcc26e68b52e2f03b4a8e862",
          "md5": "ccdc3a1d78fc8965e959d8847396e42f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-gradle-utils-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 9568,
          "sha512": "bed25f75400ecc9c5b1a4ee4ab895c0b1c142ee74bfe62b6d96e23788bcead2a93c8e8618df664a470128d882980f3e51ecc7596c9dc02c5e3914f4454e4f5e6",
          "sha256": "4c477d5d03e8fab824e473ccd55bef3cd3ddb1fbe4fa6589818579dd3e935f82",
          "sha1": "027f6918c32a9b32bcc26e68b52e2f03b4a8e862",
          "md5": "ccdc3a1d78fc8965e959d8847396e42f"
        }
      ]
    }
  ]
}
