{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/0fd7252-change-project-setup-SNAPSHOT/test-utils-annotations-junit5-0fd7252-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "0fd7252-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "42b4d13d5e65d5757e37c8107e00c0b0329c33717a7f3e0c63b2073b0be8f77926c9fc958719704b5cdc4bdeb592321db3639422315ec0e6ebc4d704926bbe92",
          "sha256": "c26beb5dfa7470501e7f4da96386c6e3eb2f04b61219e161640b368de9949767",
          "sha1": "4a9951eab4b19fb9839c5a0d6ec068d56400ee87",
          "md5": "f5b988dfc55813659ecbaa56ebc5fa68"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "42b4d13d5e65d5757e37c8107e00c0b0329c33717a7f3e0c63b2073b0be8f77926c9fc958719704b5cdc4bdeb592321db3639422315ec0e6ebc4d704926bbe92",
          "sha256": "c26beb5dfa7470501e7f4da96386c6e3eb2f04b61219e161640b368de9949767",
          "sha1": "4a9951eab4b19fb9839c5a0d6ec068d56400ee87",
          "md5": "f5b988dfc55813659ecbaa56ebc5fa68"
        }
      ]
    }
  ]
}
