{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-add-integration-tests-SNAPSHOT/kmock-0.3.0-rc04-add-integration-tests-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-add-integration-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "size": 202496,
          "sha512": "b66efb9899840172de9a3d8baf52a4fe06d76a2bb5adf7a0a4f8eea966fee8e8ecb60a8daeaeddccf7f7f013212a5a39dd74acae41baff051846ff3bc79b6196",
          "sha256": "9c982dd5bb009031b2102a11535fe0e7e45c5c5beef39b8483085ee2fcfa8ea6",
          "sha1": "eca4d404db2e784fc5d6bf27724bddcf1dbd54b9",
          "md5": "239740d3942f8c8d3009c51951db7a4e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc04-add-integration-tests-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc04-add-integration-tests-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "43274635578788bcc36f10325e8cc40544adeec2d964988bf12e9670169110a192d1be3caf3f5b91067f89799199d6510d5839c60fa05b003e07016089f4df57",
          "sha256": "97a1c5e11b820131641c120ed072b4c992bf65290fb263771bb196503f68263e",
          "sha1": "57b12399b925f40bf3c4715da9a9473ae345e6c8",
          "md5": "0ed7e2cf6a4ecc316423602803af7752"
        }
      ]
    }
  ]
}
