{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "efb8eff-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "3ece7586ecda17cd1d51bf2c073f586cce10bac37c201508e6a00fac649dff13ede3110bf6fbe0f93901740827a80fc0123120a9818ffffd83480fd93f60a07b",
          "sha256": "70543214778f5d9c5476b07d1d1ad20dd993e460b07c3a8879c3729ae99ded0b",
          "sha1": "2dc1f6c9fb01226f06d39667a9842f4202f3c878",
          "md5": "53dfebb405db305e2e4cbc8510345aff"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "3ece7586ecda17cd1d51bf2c073f586cce10bac37c201508e6a00fac649dff13ede3110bf6fbe0f93901740827a80fc0123120a9818ffffd83480fd93f60a07b",
          "sha256": "70543214778f5d9c5476b07d1d1ad20dd993e460b07c3a8879c3729ae99ded0b",
          "sha1": "2dc1f6c9fb01226f06d39667a9842f4202f3c878",
          "md5": "53dfebb405db305e2e4cbc8510345aff"
        }
      ]
    }
  ]
}
