{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/2025aef-add-more-sources-SNAPSHOT/test-utils-coroutine-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-macosx64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 10130,
          "sha512": "5a6ab194b6c3284be8ad1e4f57767f5c2a525e067c4dfdf6b494bda61ad281a89049559ab581d486e23a1aa2382193effffb2e5af59d56290f56799762431480",
          "sha256": "c6b37ecc31cf890ec079f7b59f41d7c66aeec4dfad2d536ef0b9c1707845395a",
          "sha1": "c3db072fdbde7d1876815c54816d2507a0bdcaaf",
          "md5": "d979b6dc2d9c46e3ea79981ce3e7b7d2"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-macosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-macosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7f7933fa175eb7c5c1631e57d72724f69b77857162b5a22ba61991cf8e18aa9308f1319a8b30f2c69de1e33f96e940daa58c8124db486da40b3192fa4890b3b6",
          "sha256": "de493db4e5ff4764301ded4af92b9455e7fa4aa860996eeb5c7c77148c128910",
          "sha1": "1cd1a3fecbf32f151fcc08a48e1bf970bb9a99c1",
          "md5": "192a7efb9842dee0639ebe7f7cea91a3"
        }
      ]
    }
  ]
}
