{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes",
    "module": "antibytes-grammar-tools",
    "version": "70f6dc9-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-70f6dc9-change-publishing-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-70f6dc9-change-publishing-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "726b1bb24bde4765f22dce68b0d7f31b61c11599a463792e8e2598133af78649364c66f975e119977149d2423f8729e28a2e2f47abf1fced27ac121d2143b46d",
          "sha256": "136f795b3ee2824e1bba9e60589d0861447c0b52885585adae071728199f4a20",
          "sha1": "55e71418bdc03a354bc8ce3edc250e132c5f9c3c",
          "md5": "da4b2b2f8b18975b90440a19fa6c3a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-70f6dc9-change-publishing-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-70f6dc9-change-publishing-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "726b1bb24bde4765f22dce68b0d7f31b61c11599a463792e8e2598133af78649364c66f975e119977149d2423f8729e28a2e2f47abf1fced27ac121d2143b46d",
          "sha256": "136f795b3ee2824e1bba9e60589d0861447c0b52885585adae071728199f4a20",
          "sha1": "55e71418bdc03a354bc8ce3edc250e132c5f9c3c",
          "md5": "da4b2b2f8b18975b90440a19fa6c3a38"
        }
      ]
    }
  ]
}
