{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit4-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosx64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 11352,
          "sha512": "473985b88e223580dfd4d75f0a264b6789032c26f30dda6d14e9b3b6709dc204720668995aaf6a6755c8fa5bd858ba927ac0b50d5fca9eb29b9ac103dbbbbe18",
          "sha256": "79174ef68b01947b495b75bdcc7fc3e580baf006490e8bbbc9ccd76b6c1d337c",
          "sha1": "91997f33ecd8091baa23d5d394c7d1700f644cf4",
          "md5": "3e4b64a7b2fc8b134111b71f9ee61520"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-macosx64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fd5b2ccee81ab5df2f313fe7a7c9d68b93d86b431953d26225eb63a02bcf9d85977a5b077f6086311dbac6431902ce04e88ec56b156f29e0a0846f59d6000bdf",
          "sha256": "3a96345d7279983ca27b4c07049fbfe1efa5bb44dec02ca6f430cd289eb44057",
          "sha1": "cfb17a0854c4e3db83045996393ff39355599bd3",
          "md5": "59a393a7ee369b330ccc0c5f97fbcf34"
        }
      ]
    }
  ]
}
