{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit5-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchosarm32-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 7086,
          "sha512": "c5d5c2e0ddcd59423b43f6632675df93c8e38f515c074e75b7c617e061aa6e076822565e5291ca908eebe0f97dd163b91ce61fb2dbf6beb68f30cefb20bbecfc",
          "sha256": "05a3fe6d887fdf811424d8dbcbe3642c82582bd364f1afad4e28f3f2fd7b6554",
          "sha1": "c3621d0141e4a420f7a442389754b43291541cea",
          "md5": "ff6e61010bbca68472bbafacbbea2083"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchosarm32-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-watchosarm32-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b888f9257b030397b937523f643854ec98f820c9f8afb7e8b03bf52d564494349a5d3e567781833abebb8518948e9d0329eb906acd05534f413d542d4969971f",
          "sha256": "6f4785de7793d2f0e17979460f3767804d9a8a87361ae348a0f95a546f3fb01c",
          "sha1": "49951c4ba7fa06e79c35867439c049625f933fe9",
          "md5": "5d8a14c7053b8c153a37ee2dd90cc564"
        }
      ]
    }
  ]
}
