{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-user-method-names-SNAPSHOT/kmock-0.1.1-add-user-method-names-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-user-method-names-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-user-method-names-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-user-method-names-SNAPSHOT.klib",
          "size": 160516,
          "sha512": "fe9cc03fb81c956ece548f52d1d9eb2d212f1ae77b2dc5154f5bcd31873ea65e4a2a9a7dfebd425c19f1e094019ca7e4df86f2492b1e5eba8716930d5b5e6fac",
          "sha256": "b674cf9ddf35e7a6165380b313187e135cc2deb8756986b39636225199b985ca",
          "sha1": "b5c0e3cdbc251920b1bafcdea38ab8f6d1baea68",
          "md5": "b89cd9a1d1eeb993355b50fef4e683b0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-user-method-names-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-user-method-names-SNAPSHOT.klib",
          "size": 160516,
          "sha512": "fe9cc03fb81c956ece548f52d1d9eb2d212f1ae77b2dc5154f5bcd31873ea65e4a2a9a7dfebd425c19f1e094019ca7e4df86f2492b1e5eba8716930d5b5e6fac",
          "sha256": "b674cf9ddf35e7a6165380b313187e135cc2deb8756986b39636225199b985ca",
          "sha1": "b5c0e3cdbc251920b1bafcdea38ab8f6d1baea68",
          "md5": "b89cd9a1d1eeb993355b50fef4e683b0"
        }
      ]
    }
  ]
}
