{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/757e8dc-bump-updates-SNAPSHOT/banana-i18n-757e8dc-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "757e8dc-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm-757e8dc-bump-updates-SNAPSHOT.jar",
          "url": "banana-i18n-jvm-757e8dc-bump-updates-SNAPSHOT.jar",
          "size": 170941,
          "sha512": "9f80d36e26bbba626fc1f5c0a05b603923b4a2c0dda4300af03f7ce80d901e3ddbbee40759d270a551cee355aa6bcaaeef6ba50ce6dace00bf960569ffbcc0fe",
          "sha256": "d9145255d95f7a30f5f7af20e1e9961b5a79a7afe44fc5033c8e70740a6bd42c",
          "sha1": "a7087ec6508b22472a7af5ef9c12d1cd17e5eba7",
          "md5": "0d3f9d61c370ff0924440f4ccd1d8f5c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "70.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm-757e8dc-bump-updates-SNAPSHOT.jar",
          "url": "banana-i18n-jvm-757e8dc-bump-updates-SNAPSHOT.jar",
          "size": 170941,
          "sha512": "9f80d36e26bbba626fc1f5c0a05b603923b4a2c0dda4300af03f7ce80d901e3ddbbee40759d270a551cee355aa6bcaaeef6ba50ce6dace00bf960569ffbcc0fe",
          "sha256": "d9145255d95f7a30f5f7af20e1e9961b5a79a7afe44fc5033c8e70740a6bd42c",
          "sha1": "a7087ec6508b22472a7af5ef9c12d1cd17e5eba7",
          "md5": "0d3f9d61c370ff0924440f4ccd1d8f5c"
        }
      ]
    }
  ]
}
