{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/ef3a5b1-bump-updates-SNAPSHOT/test-utils-resourceloader-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-tvosx64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 14205,
          "sha512": "14bec35070aff1e18b80315d94c25d04f3d80a5af3da6056b5f25dcedd6d462abf9630ae35e3346a1a6576e56f2f991d22607e5d3f38721d2651bbc5af18257e",
          "sha256": "d7f64602bce4bcd3d0c0696c35634c1da75991c52807b387a5a42c9d7801ddbc",
          "sha1": "1d0c7d5d105c6c704b5b5ef55d1332d85aaf1e8e",
          "md5": "666515a0686733243fd0071432370e62"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-resourceloader-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 4241,
          "sha512": "284172150658cfb9dae6c2bb10bbd5de382a8193d892540a4de60322cb16b05740a160fc4f827c092194ab0e3983419cb75c9d52eee7cf9cf1ac22b32a8f7d7b",
          "sha256": "28c33fb0c5429879a7515dfb1ee5400a354f30a17cda3a32c13cec2fd413b7da",
          "sha1": "e6bc305f912fc8fc1e733215728491f83d594bd4",
          "md5": "935272aedc89d60202c3ad87a167495a"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "08573aad0d7bb058d4ee96f61b285e5dcdf88f36c2c0419180931a34797a2ed1d71db2acaff31c7fcc0401c2b92d1dcf1d204b703cc104b15fcc524edaecde18",
          "sha256": "06d9a0e977c8628ef497e6395a5bd17587c96bb0532bd6153630d5d0f492a8af",
          "sha1": "2ee2294583c181ac755c0395e6f3c9adee3620b0",
          "md5": "56ec4ac0d148a490c46a122fdb2f373e"
        }
      ]
    }
  ]
}
