{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/205f7d8-fix-assertions-SNAPSHOT/test-utils-205f7d8-fix-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "205f7d8-fix-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 14066,
          "sha512": "6b29b9b959bc1aded8d709d74bd9d514eab5f5c7fafd6310ce2c42792785775c21a272c1c6fb56126e6ad6f61e751cb6f8ec93fc326c28f7ac69709474e212d5",
          "sha256": "1f4ee7f95b34d3479001588d9d82d27a80b2b63a30831a3c1d47481cecb12e09",
          "sha1": "070a3d135eabcaf6d051beeb4e014abd97bb0f44",
          "md5": "a2935f11ac1f951ee101c1e4098ae36f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-205f7d8-fix-assertions-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-205f7d8-fix-assertions-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "780b12ac609721c09d72bdf5dbe2da9232a5e1a51101dfdb213310a272254750ad8d51bf4db6ff0f16de8b25e8253726e112f3f0579c62898f3aa15424014d12",
          "sha256": "0260f871ad79e1da2bc4b019c410388037ee2d5bfe7706d03fdefaf1d90a8125",
          "sha1": "e04411ab6b2d5e9e0509226c71ea45a6e21e0538",
          "md5": "332f283e3ae1672b4189b95267d8064f"
        }
      ]
    }
  ]
}
