{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "6c9977a-change-plugin-resolution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-mkdocs-6c9977a-change-plugin-resolution.jar",
          "size": 11951,
          "sha512": "da3a7a88a89259f09d9063415c23673d89590b7c2fa647664d1c055fc53935f018e8f8019e176c6db12f9d6efe473fda3ba4a78d2ecb60516cccbff4aaa0f424",
          "sha256": "1ddb40dec20e4f7321d28457caca305ab10390cb02eaece785186bac6161331b",
          "sha1": "d84b8d1484e894a7a2fdf099cb5fd1deb67094d8",
          "md5": "5e18e908da34ef4fc99b2761d44bebbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-mkdocs-6c9977a-change-plugin-resolution.jar",
          "size": 11951,
          "sha512": "da3a7a88a89259f09d9063415c23673d89590b7c2fa647664d1c055fc53935f018e8f8019e176c6db12f9d6efe473fda3ba4a78d2ecb60516cccbff4aaa0f424",
          "sha256": "1ddb40dec20e4f7321d28457caca305ab10390cb02eaece785186bac6161331b",
          "sha1": "d84b8d1484e894a7a2fdf099cb5fd1deb67094d8",
          "md5": "5e18e908da34ef4fc99b2761d44bebbe"
        }
      ]
    }
  ]
}
