{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/4bb1282-fix-factory-SNAPSHOT/kmock-4bb1282-fix-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "4bb1282-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-4bb1282-fix-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-4bb1282-fix-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "339bfb48bb562e23d9dde258693f1fc06562434b51be812848ee6250e62660f11725bbc6b7de4c099c2903f5ab75786492ec6f80a4dad446239076385326a97b",
          "sha256": "1952f1f274043217fcaf1ec9d0d13140919ca467cff3adeacc99ee12d0a390b0",
          "sha1": "2e8c85b20dc0f81e66cf763b86a42300459ff8fa",
          "md5": "4c8630445828ed21730ee0e0b847fbc0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-4bb1282-fix-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-4bb1282-fix-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "339bfb48bb562e23d9dde258693f1fc06562434b51be812848ee6250e62660f11725bbc6b7de4c099c2903f5ab75786492ec6f80a4dad446239076385326a97b",
          "sha256": "1952f1f274043217fcaf1ec9d0d13140919ca467cff3adeacc99ee12d0a390b0",
          "sha1": "2e8c85b20dc0f81e66cf763b86a42300459ff8fa",
          "md5": "4c8630445828ed21730ee0e0b847fbc0"
        }
      ]
    }
  ]
}
