{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/577fd36-bump-antibytes-SNAPSHOT/test-utils-577fd36-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "577fd36-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "2e7181dd61112bb18c9952df47ff6878e45e03244bc8dc45516cf2c86b9df2877f7c326faa7a085d404ec24ddc4243878ed5cedff9836c1f6a47fae9673355ea",
          "sha256": "385618bb38d5f31fe7254b9c93f8854308e66a0233cedf8abb910b455eba8568",
          "sha1": "05747054f8c5af6278533631e312af9af485d86f",
          "md5": "f7ddcd5dc3654523b5dc658c7a2a0218"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "2e7181dd61112bb18c9952df47ff6878e45e03244bc8dc45516cf2c86b9df2877f7c326faa7a085d404ec24ddc4243878ed5cedff9836c1f6a47fae9673355ea",
          "sha256": "385618bb38d5f31fe7254b9c93f8854308e66a0233cedf8abb910b455eba8568",
          "sha1": "05747054f8c5af6278533631e312af9af485d86f",
          "md5": "f7ddcd5dc3654523b5dc658c7a2a0218"
        }
      ]
    }
  ]
}
