{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/d75bc0f-change-coroutines-SNAPSHOT/test-utils-coroutine-d75bc0f-change-coroutines-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "d75bc0f-change-coroutines-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "4a4e3db5227e4d54a9a5e8118120ed474dc06401b81e736de94b96871efb08f96f54e4bae660e02c8db87178b702b9a0a58d183fadfb33b819527171aa904a3c",
          "sha256": "6a42295491a065734a5040e26b5424138348204b1e1def4b89e850735fbefe68",
          "sha1": "d5a661e0d3d9f3d692282c40b210d26987ca4a58",
          "md5": "8ef0387a3e2e910e7dfe4cd43610d836"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "4a4e3db5227e4d54a9a5e8118120ed474dc06401b81e736de94b96871efb08f96f54e4bae660e02c8db87178b702b9a0a58d183fadfb33b819527171aa904a3c",
          "sha256": "6a42295491a065734a5040e26b5424138348204b1e1def4b89e850735fbefe68",
          "sha1": "d5a661e0d3d9f3d692282c40b210d26987ca4a58",
          "md5": "8ef0387a3e2e910e7dfe4cd43610d836"
        }
      ]
    }
  ]
}
