{
  "formatVersion": "1.1",
  "component": {
    "url": "../../clientSDK/b87036e-add-more-platforms-SNAPSHOT/clientSDK-b87036e-add-more-platforms-SNAPSHOT.module",
    "group": "tech.antibytes.awesomecats",
    "module": "clientSDK",
    "version": "b87036e-add-more-platforms-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK.klib",
          "url": "clientSDK-tvosarm64-b87036e-add-more-platforms-SNAPSHOT.klib",
          "size": 45941,
          "sha512": "8d2078b6cc9717e909efca344bd2a1ad5267076ba0148f9f758931d4f553a95cbee09e84187781857923522875a83d5b9da456d17a5e57dd98953836e3775be2",
          "sha256": "bf4032dfae0e2f1ab9c3454a3eabf56663e1bad71c33c5a82e22d0074f99e288",
          "sha1": "397f9b401e3b4536d6dfd7e863c741654041e4ae",
          "md5": "c6ea9c0f00a6708f98a4491dbbd63153"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "05a4d20-customize-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "clientSDK-tvosarm64-b87036e-add-more-platforms-SNAPSHOT-metadata.jar",
          "url": "clientSDK-tvosarm64-b87036e-add-more-platforms-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3379c39520093212f0e1ec39fe4ce9b74423d46921a80f15a5310d1127044a70c07cd3ee5fde79c43d09129dcac510854a731c3a147f62605304e5a6bc1d9362",
          "sha256": "6c339668d17568c936bda380d14be89b56375b97d4b006c33eaf029890ce1f3c",
          "sha1": "c7d263042f2bb3eb01d1f504f8d2b3df87c59c6a",
          "md5": "1d8d553eb691c5df1aebfd1fd9324e31"
        }
      ]
    }
  ]
}
