{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-badges-SNAPSHOT/core-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT.klib",
          "size": 105923,
          "sha512": "f201b335872042436de1ab78e34e9d457a26deb6796f4830318a8f88e93825876284e4e9c59ee2e6672026494e4fc1c15a6d4af9ceae9a27aea40ba32bd2875c",
          "sha256": "9c7a60ba522a6fc2c7595c62f18e9bc937ae555afef5219a86ece7c357a96c43",
          "sha1": "7a04126c30738c5072e1940d17c2192c810366a2",
          "md5": "097fd14063df40d2c8b4e1e3edd9f883"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4836989e3f2ed416feb9d668c2f04028befdeb2fa1547921511e05fe0def643de0f972e4466c4f1a3af9785da0034b5ae2dda3102f46eeac767a5b264f16803c",
          "sha256": "05daad10266b37c59edd53efa4b908071bdf1e98c18df6501df9dc3d2f9be7f0",
          "sha1": "b75ccbfe01100c62b61a4e41f0e51719b71b7a77",
          "md5": "09cf5b97e1b516650ccee7ffca878696"
        }
      ]
    }
  ]
}
