{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9aec7b7-bump-antibytes-SNAPSHOT/test-utils-9aec7b7-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9aec7b7-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "size": 8848,
          "sha512": "eac62957c8dcc6048c6cdf83740459b470058aa0b60ca8cb808a9e37719577efc529cfe2043e32910a1a8565b49366ef8d3427dea245c7278a87127c115cc292",
          "sha256": "c634c377dcc6a2d3184344d06b5aadcd780b516355d12cf1be189ca3b6aea96d",
          "sha1": "0a7bb08bdb84ecb0601a6a50f030c4be05bc8866",
          "md5": "1b02776c1f468d5eaa21eaf38f48483b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-jvm-9aec7b7-bump-antibytes-SNAPSHOT.jar",
          "size": 8848,
          "sha512": "eac62957c8dcc6048c6cdf83740459b470058aa0b60ca8cb808a9e37719577efc529cfe2043e32910a1a8565b49366ef8d3427dea245c7278a87127c115cc292",
          "sha256": "c634c377dcc6a2d3184344d06b5aadcd780b516355d12cf1be189ca3b6aea96d",
          "sha1": "0a7bb08bdb84ecb0601a6a50f030c4be05bc8866",
          "md5": "1b02776c1f468d5eaa21eaf38f48483b"
        }
      ]
    }
  ]
}
