{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-add-integration-tests-SNAPSHOT/kmock-0.3.0-rc04-add-integration-tests-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-add-integration-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-add-integration-tests-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-add-integration-tests-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "7d71315a7b0080193ca8a3a1796b817469ec1c16c0cadb1f1ea6671725bdd9c3f7d63496e1826a68af3234cbff211437e7ea478a94dab359758144b44061fd63",
          "sha256": "2c1ef50f6a353f773f45d7da9df6b5c0c18ee4ba9f4f4c6131e3cb24d300c5c9",
          "sha1": "9db7ce1e21b3fc6f7bcd9a0fb88d00bac0e46bfd",
          "md5": "d936e72002a317e3f4fb5ad321b35981"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-add-integration-tests-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-add-integration-tests-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "7d71315a7b0080193ca8a3a1796b817469ec1c16c0cadb1f1ea6671725bdd9c3f7d63496e1826a68af3234cbff211437e7ea478a94dab359758144b44061fd63",
          "sha256": "2c1ef50f6a353f773f45d7da9df6b5c0c18ee4ba9f4f4c6131e3cb24d300c5c9",
          "sha1": "9db7ce1e21b3fc6f7bcd9a0fb88d00bac0e46bfd",
          "md5": "d936e72002a317e3f4fb5ad321b35981"
        }
      ]
    }
  ]
}
