{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "f237b2f-add-custom-component-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-f237b2f-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-quality-f237b2f-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 62318,
          "sha512": "c5dd0f74e302cf33258f68756784af4cd654377befcdbe930e4df33437be715714ecff61874b6b202a27d93449ea88b517527518e060de01b224d263e22f5e20",
          "sha256": "b09c96023d38a330a97aa6e201d0f392720e3ee88fa18be31c2dc22c0c6aa759",
          "sha1": "065ec2884845b4e627a13d269c13b0ce75fde9f6",
          "md5": "0827a6811342cacb9c1a1396252ba857"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-f237b2f-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-quality-f237b2f-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 62318,
          "sha512": "c5dd0f74e302cf33258f68756784af4cd654377befcdbe930e4df33437be715714ecff61874b6b202a27d93449ea88b517527518e060de01b224d263e22f5e20",
          "sha256": "b09c96023d38a330a97aa6e201d0f392720e3ee88fa18be31c2dc22c0c6aa759",
          "sha1": "065ec2884845b4e627a13d269c13b0ce75fde9f6",
          "md5": "0827a6811342cacb9c1a1396252ba857"
        }
      ]
    }
  ]
}
