{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-docs-SNAPSHOT/core-0.2.0-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.2.0-change-docs-SNAPSHOT.klib",
          "size": 99968,
          "sha512": "891ea6d6cebdd4e7af99da191f75103606bf25694cee6360fa76a9b19c6d10ffa7e8e4980697d0ac49ce336537cd1c367de525af73f059bd2739b75afb49e076",
          "sha256": "3592a163a695613f0a59c820c2f6cf6c058141f3c2c512fae0924f019a319aeb",
          "sha1": "b200a543e1e1fb6c23bdd18ad8db85d82d5fbac3",
          "md5": "f41f8b0b1ed292fd944c6d8b94979157"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.2.0-change-docs-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.2.0-change-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6417b7851ee244b67c0c6049792bd8ab94aecf4926533b8282cbb5ddda1da2fd1964d9cd584a56e2bee4b752409fe2f96e31d478e7656b4e32bed3f9360ebfc1",
          "sha256": "a0a9b0270479f7714bf7e8637040899b822b1971428aea98fce5e01ff77a0d63",
          "sha1": "98f973127092bd6308e87029607fad5770fc3899",
          "md5": "2820f42080e48ef9b6c22993c87f0621"
        }
      ]
    }
  ]
}
