{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/bff1152-bump-antibytes-SNAPSHOT/test-utils-annotations-bff1152-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "bff1152-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-bff1152-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-bff1152-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "f4d9455416d603361e6779006bf908d70daac8b8a03111a4f540fb04737203883410b359f75b6ecb319219cd52be6e668db76f4f16d6d49d361ed52c3ae931d1",
          "sha256": "efab293913d72f765df1c65f50e739dbb3f2534363f384567807245fbb176e9b",
          "sha1": "4664e6648d890a5ac4e632af7f1c0d0e4bd18d54",
          "md5": "0aa500d92606483f19e151854a82215c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-bff1152-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-bff1152-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "f4d9455416d603361e6779006bf908d70daac8b8a03111a4f540fb04737203883410b359f75b6ecb319219cd52be6e668db76f4f16d6d49d361ed52c3ae931d1",
          "sha256": "efab293913d72f765df1c65f50e739dbb3f2534363f384567807245fbb176e9b",
          "sha1": "4664e6648d890a5ac4e632af7f1c0d0e4bd18d54",
          "md5": "0aa500d92606483f19e151854a82215c"
        }
      ]
    }
  ]
}
