{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "8feebc4-add-github-env-check",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-8feebc4-add-github-env-check.jar",
          "url": "antibytes-grammar-tools-8feebc4-add-github-env-check.jar",
          "size": 39371,
          "sha512": "09d185e1571f1d51086299b03f768d81c672a19fbc95fc20a5ccca68b58f02b619dfcfa29985e94a4b9b36129d362ed3438dc63636be04fe476c0ef6c7430db6",
          "sha256": "d86f4b666d93adcd3584efeda02a22c4e9227bbda7fda79b6872181b4c71fe27",
          "sha1": "054d5821f3730845e2a675861f2e869316ff8e2d",
          "md5": "46788c42db36c865b9b9a2fcd94b8516"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-8feebc4-add-github-env-check.jar",
          "url": "antibytes-grammar-tools-8feebc4-add-github-env-check.jar",
          "size": 39371,
          "sha512": "09d185e1571f1d51086299b03f768d81c672a19fbc95fc20a5ccca68b58f02b619dfcfa29985e94a4b9b36129d362ed3438dc63636be04fe476c0ef6c7430db6",
          "sha256": "d86f4b666d93adcd3584efeda02a22c4e9227bbda7fda79b6872181b4c71fe27",
          "sha1": "054d5821f3730845e2a675861f2e869316ff8e2d",
          "md5": "46788c42db36c865b9b9a2fcd94b8516"
        }
      ]
    }
  ]
}
