{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/ef3a5b1-bump-updates-SNAPSHOT/test-utils-annotations-junit5-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 7077,
          "sha512": "f6f5e7b2c5ddb03d2273c9412c1a9e8aebdb21bd16f9f9e37b4505e5ae6c8b481e0f72c1e311e41bafc209126b2f53fe50ef383b55f7ae494a6cdded9339cd2a",
          "sha256": "1f37720818d71ea29f93f36650cac1640f6510ef7c9db93119e05113e80eb19b",
          "sha1": "79478f7b93e444f4fd7ab96375d802cb38bdba57",
          "md5": "fa409aed9e2baccf08f3071558784fc7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-annotations-junit5-iosarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 3477,
          "sha512": "8910488f2acc4f4c669bf3e6a74835e60ede75d2286f44304a32d7435e9374f50e400ec91ccdc9fcab868fe57ac79f9cc99c5183a87396417d48b059ee008e7f",
          "sha256": "9f2d1a8fe1210ea25bd9b54214171ccdd8f68d07f8c4c7bf4fdaa277b2d059e9",
          "sha1": "c0915589af235519923fb41575cb1d6e37f9dedf",
          "md5": "b993ac9b3bda4583966bb9266ec6da60"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "402ca189ba7a6a073a8309597b3026e3143fccfd16474ddfbdffc27c69e76603f085dd86ea8f70959eed279085bf26500b908d6b3b7b7c2973dabbeab7ec5ee1",
          "sha256": "986211db15843202b919ba316cc160d9188b6f5984655e7c1780ea275f5f2609",
          "sha1": "0a6cd40c007c8c4d5f374b002fb64f2a2273e7c8",
          "md5": "46b93af711165ed77b61d8b38c1ec2f1"
        }
      ]
    }
  ]
}
