{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/048cd7e-change-publishing-SNAPSHOT/test-utils-annotations-048cd7e-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "048cd7e-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-048cd7e-change-publishing-SNAPSHOT.klib",
          "size": 11314,
          "sha512": "ea144cab8ebc3e6a232c1c1081208ff4aea2db5fb442d6bcb6d9b3754e39ba2d43a6abcfa27066b763d682828b688b5f6a4da905fd95ea95dbb680a6467a5f0c",
          "sha256": "a289607ed549dfd78adee106fddbbfd91c226006272d36a194568739015aa316",
          "sha1": "0dc10284a8525b4a96e0bebf51e8748e56529d12",
          "md5": "d84f1f9aebf41f389e54a73509ad0606"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-048cd7e-change-publishing-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosx64-048cd7e-change-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "634bbf47064f2d8c1dd5556590cf368e18f57c97a6bf8ea8c265e206a849a4b6924f536aad0686a227381a7bfb3eeb6c3f7f5322def24255b8d77625275980af",
          "sha256": "f3fa883dd2a4573b1803d53336aa2aa01ede708dd8e151f9fd33f006b263f4fe",
          "sha1": "0cc5641b9056a637c914b18c0fc2687e4e4e81d3",
          "md5": "7b70796dba8405e6c4bd1c2453a60974"
        }
      ]
    }
  ]
}
