{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/df500e4-change-docs-SNAPSHOT/test-utils-coroutine-df500e4-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-df500e4-change-docs-SNAPSHOT.klib",
          "size": 10215,
          "sha512": "20f8faf97ffe763f21a5727be08c7cc050477ad101cf5fcf7173e9ddbe61e09ad64024ed4ac84f526406d32dada6786171cb15ed0140b91d8c0099e9b3e42c52",
          "sha256": "b5ee960a0de26f99ed0dae68d0108fc1f8a3ffb5ce966589d0682b49fd80510d",
          "sha1": "b306a632a58df0d61fcd0d72b06743ddc98ed3f8",
          "md5": "d0c2d9c2207c602d76d9a6491b30bff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "607ab41b29a6e012bace0baaa2a41eb72862dec7fb125ce0022f4f4955cb79696e0d9e46f2781ed0db7d327ed70fe0c9ef21844e6b079133a9bcb2bed205815f",
          "sha256": "d8d7cc17464acf7763148a971ab613c8b0de77134f11bed8206d63026b5b189e",
          "sha1": "ea0a71fb0de25e357751831298c831d97a8c706d",
          "md5": "2c9e686ff777176e59a21109987395ec"
        }
      ]
    }
  ]
}
