{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "2b9fd9e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-2b9fd9e.jar",
          "url": "antibytes-dependency-2b9fd9e.jar",
          "size": 84362,
          "sha512": "27b9f2943bb360530d15c3bc7043b6a5eb596a328b7aa97a7f85a3af76e6c131d79aefb1650a2dc00d38ba76b1dfd275e6f657f4fbfc712a9c49e9f8a4c5ac1b",
          "sha256": "27fd14771709ff2d0d0a4b550eacf1ac06d69519d7d5d50f9f878c3b7cf1bacd",
          "sha1": "91575e8ab945ec019f4eccda3b4f236de1001cd7",
          "md5": "a1203b1af7acfc376ba73974fc3c2691"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2b9fd9e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-2b9fd9e.jar",
          "url": "antibytes-dependency-2b9fd9e.jar",
          "size": 84362,
          "sha512": "27b9f2943bb360530d15c3bc7043b6a5eb596a328b7aa97a7f85a3af76e6c131d79aefb1650a2dc00d38ba76b1dfd275e6f657f4fbfc712a9c49e9f8a4c5ac1b",
          "sha256": "27fd14771709ff2d0d0a4b550eacf1ac06d69519d7d5d50f9f878c3b7cf1bacd",
          "sha1": "91575e8ab945ec019f4eccda3b4f236de1001cd7",
          "md5": "a1203b1af7acfc376ba73974fc3c2691"
        }
      ]
    }
  ]
}
