{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "f891629-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-metadata-f891629-bump-antibytes-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-f891629-bump-antibytes-SNAPSHOT-all.jar",
          "size": 4917,
          "sha512": "c6557f03bde00508c55e8ff59dd45ac5c87b11e2c70baa24d0e81757cb194036cba298ebec1a02fa5e1fe5981df6e29736b57eda2c5303448780fbd646034a6a",
          "sha256": "65003bf60e66d7f416ebc2fda9e54eb59755bf0deb113d5d5ea2289acf5ed68d",
          "sha1": "0f0fa773b457331f13713e3aa83241ea878408ad",
          "md5": "273b218acb1aa9e46467914f8e552bce"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-f891629-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-f891629-bump-antibytes-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "52392901eec2d2f1c5b19f5ada58c7de813adda6f57c76b4da7f9fb12b8099ea560f37d5d15863859cbbf13f180f59a9059c04721c4ccf2393d78ee7b07b187e",
          "sha256": "350b69f8aa24f71826d8018c9ecd3d96ab0a6dd0cce1e7ff2c94080b87ab98a0",
          "sha1": "e46dbff1bf3eee6b4575ae439725bfad1665cce6",
          "md5": "88d7e6d860ac0d7f299aec8757e2e953"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-android-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-android-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-js-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-js-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-jvm-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-jvm-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/f891629-bump-antibytes-SNAPSHOT/test-utils-annotations-linuxx64-f891629-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "f891629-bump-antibytes-SNAPSHOT"
      }
    }
  ]
}
