{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/205f7d8-fix-assertions-SNAPSHOT/test-utils-annotations-205f7d8-fix-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "205f7d8-fix-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-205f7d8-fix-assertions-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-205f7d8-fix-assertions-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "c3076b920cce22a191d5d60ea7f12e4a96a8a1a44ec39f43018af7bd83786aed43825d6a93716b35e6fa2497881c3bca47b377ab43f3fbb6ea4e9be0bbc04613",
          "sha256": "8d3826257828d56c085f0b61ab084216313c6e6ed3419e171ce606656dc24b91",
          "sha1": "21f131993332aff14d641cc09c73458de947c6e2",
          "md5": "bdc427bbec85895859ca153305d37e2b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-205f7d8-fix-assertions-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-205f7d8-fix-assertions-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "c3076b920cce22a191d5d60ea7f12e4a96a8a1a44ec39f43018af7bd83786aed43825d6a93716b35e6fa2497881c3bca47b377ab43f3fbb6ea4e9be0bbc04613",
          "sha256": "8d3826257828d56c085f0b61ab084216313c6e6ed3419e171ce606656dc24b91",
          "sha1": "21f131993332aff14d641cc09c73458de947c6e2",
          "md5": "bdc427bbec85895859ca153305d37e2b"
        }
      ]
    }
  ]
}
