{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-add-more-sources-SNAPSHOT/ktx-datetime-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchosx64-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 34668,
          "sha512": "c7a4671178ad4b362847e35fd6a4919a0b303cda4d2932c97acdd922d0714723b70382b554344c2e99c1aeb2c0f729a6cb0f48e8f13f7ccd5c104275354dd0d5",
          "sha256": "4b270b33a023430dce73bc0508224a712a1619a93e8ddb8802f4ede357b6985a",
          "sha1": "b901658aa892c110c85a711e4f35840c79d4f5f3",
          "md5": "255f5b31e05ae61a0519c27ec5fdb60f"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ba7ee3425bab70350e3dff9e7def429880f4f9fde59a8d59001caf4e7f09da52d3bef968d60316816aa855a3118964b06ed9476ef3771d43d9a8d45b296a52b6",
          "sha256": "c59edb3e949c0937e901c328429439e5ac1048963748e07381540fbc8894e2f0",
          "sha1": "79c214d6ca37ccd507539561a19682bd9893a896",
          "md5": "223dd9fd09f3a2dfc9467ae9b9dea12b"
        }
      ]
    }
  ]
}
