{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-add-assertproxy-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-add-assertproxy-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-add-assertproxy-SNAPSHOT.jar",
          "size": 173194,
          "sha512": "c781837cfca7c0936b4ed9e1b7cb05c9d9b5cf255716843d1426232bbe4a6196ef0b7391c9cb1776d63f280bdb810e22a29007e831cf338c1777571824bbdeae",
          "sha256": "5c098448ffaf4cd09fcdca47e81bcb36fc0a84e2bdc1875666cc5c4c077c11e1",
          "sha1": "151dc743f05a263e3752fb867075a73775669595",
          "md5": "a59f27e43c51bf2d0c83d0358373718c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-add-assertproxy-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-add-assertproxy-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-add-assertproxy-SNAPSHOT.jar",
          "size": 173194,
          "sha512": "c781837cfca7c0936b4ed9e1b7cb05c9d9b5cf255716843d1426232bbe4a6196ef0b7391c9cb1776d63f280bdb810e22a29007e831cf338c1777571824bbdeae",
          "sha256": "5c098448ffaf4cd09fcdca47e81bcb36fc0a84e2bdc1875666cc5c4c077c11e1",
          "sha1": "151dc743f05a263e3752fb867075a73775669595",
          "md5": "a59f27e43c51bf2d0c83d0358373718c"
        }
      ]
    }
  ]
}
