{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 34633,
          "sha512": "c88e5c39cd1d3e436131eac99b36142e79cbc5e0ae602f2587b2ec563cc58d2373dffc114763b6b4450f6d91a98b389002d0abee158d707717cd806b4823c552",
          "sha256": "e0d4b1f27a981f5784e9f1e2b7b2373ad26bc1320683f17d66fe5f539e2df58b",
          "sha1": "2ee6f98d5effa1e56e9ddc3c912b09efb80a7ea2",
          "md5": "876dbe675d595e0b819f4e3e3b9b7f2f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fbef9063a699ea1b6a231dd4a93777d40352d81000a60cf52a50c9028ef87d055add613a54961bbfff5d8f73aca2ab7becbf359badd523189d80f30f8ec8894e",
          "sha256": "5d57315edbfab9e783a78c4eb87db932539d03a987a7878800e28471bbd4d67e",
          "sha1": "d12cb83b67cff8cf3d565e01d6599be06d00c633",
          "md5": "87be104674773fabfd3077264b82cd9b"
        }
      ]
    }
  ]
}
