{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/c018d4a-change-setup-SNAPSHOT/test-utils-coroutine-c018d4a-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "c018d4a-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-c018d4a-change-setup-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-c018d4a-change-setup-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "3ca6f4232e30951127a2e998d2651282fae8f166d65bd7616cd9c5ab0bf21d64a7c6efe232b7245c4bb57c8c47d3cea438a69b834235cfa759a162905413db96",
          "sha256": "6e6524cb28bd49b2f8577d75e9c3ee66285be6f937faeec4612e5ce9fd0ba80d",
          "sha1": "52cd746b9fe27bd11f53f3f7c2705443eb6798d7",
          "md5": "f952f55d6cd2676695fa540d518ef96e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-c018d4a-change-setup-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-c018d4a-change-setup-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "3ca6f4232e30951127a2e998d2651282fae8f166d65bd7616cd9c5ab0bf21d64a7c6efe232b7245c4bb57c8c47d3cea438a69b834235cfa759a162905413db96",
          "sha256": "6e6524cb28bd49b2f8577d75e9c3ee66285be6f937faeec4612e5ce9fd0ba80d",
          "sha1": "52cd746b9fe27bd11f53f3f7c2705443eb6798d7",
          "md5": "f952f55d6cd2676695fa540d518ef96e"
        }
      ]
    }
  ]
}
