{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "8e2572b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-8e2572b.jar",
          "url": "antibytes-gradle-utils-8e2572b.jar",
          "size": 9568,
          "sha512": "27a3869c54bd14e5e1fb8d1ac816d35ab6719517ff518eceda8a04bd3c2ec47e49188cbd75648437a7b181a35fb07e341032c4a703108de8c0743f07d3bc349b",
          "sha256": "164869195b6b9a38c3a034cde99bd25d10b411b22bff3930b8cf3f762b32baea",
          "sha1": "e42d58b47c32f48d6ed9a1c2aaa8f10a715e12ca",
          "md5": "0338b7248502799ac0f8420cc55d535c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-8e2572b.jar",
          "url": "antibytes-gradle-utils-8e2572b.jar",
          "size": 9568,
          "sha512": "27a3869c54bd14e5e1fb8d1ac816d35ab6719517ff518eceda8a04bd3c2ec47e49188cbd75648437a7b181a35fb07e341032c4a703108de8c0743f07d3bc349b",
          "sha256": "164869195b6b9a38c3a034cde99bd25d10b411b22bff3930b8cf3f762b32baea",
          "sha1": "e42d58b47c32f48d6ed9a1c2aaa8f10a715e12ca",
          "md5": "0338b7248502799ac0f8420cc55d535c"
        }
      ]
    }
  ]
}
