{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/30769ee-change-setup-SNAPSHOT/test-utils-annotations-junit4-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "00395bd92b43ac64a357167f2ae84a21a5abcb1df1152e8603a2a1f2a528f50ac1e901ab0ea6fb96be794a290b38efc36ef0f3ef647ea4f6b26102e8ecb76590",
          "sha256": "0ad4f80fe090c572c2553459abb6592970a5cb3bdcbd4be53479af0f41861328",
          "sha1": "e48e328768548b46645dfef7e7b909894f0bc274",
          "md5": "ceffcc9a84c7935d51bc0f999a9e3429"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "00395bd92b43ac64a357167f2ae84a21a5abcb1df1152e8603a2a1f2a528f50ac1e901ab0ea6fb96be794a290b38efc36ef0f3ef647ea4f6b26102e8ecb76590",
          "sha256": "0ad4f80fe090c572c2553459abb6592970a5cb3bdcbd4be53479af0f41861328",
          "sha1": "e48e328768548b46645dfef7e7b909894f0bc274",
          "md5": "ceffcc9a84c7935d51bc0f999a9e3429"
        }
      ]
    }
  ]
}
