{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-quality",
    "version": "122c96c-add-custom-component-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-quality-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 62318,
          "sha512": "8cb8fbe7975b0064da357c51ed0f33f28853d5fe80866a9ec0353109adc48b623bcde14f109934c52c9023f5d56634add86ed1e11c238bfce9bc78d9e29e454d",
          "sha256": "b8a8b5d0ff4cc31f7b81db252e33511f931a48cc079d359e3188341662068656",
          "sha1": "687a6fc89cec4e27094d42da3e0b8ddf8f70ff28",
          "md5": "4c95a6480445f3a5983b3e69cb4e9a89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-quality-122c96c-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 62318,
          "sha512": "8cb8fbe7975b0064da357c51ed0f33f28853d5fe80866a9ec0353109adc48b623bcde14f109934c52c9023f5d56634add86ed1e11c238bfce9bc78d9e29e454d",
          "sha256": "b8a8b5d0ff4cc31f7b81db252e33511f931a48cc079d359e3188341662068656",
          "sha1": "687a6fc89cec4e27094d42da3e0b8ddf8f70ff28",
          "md5": "4c95a6480445f3a5983b3e69cb4e9a89"
        }
      ]
    }
  ]
}
