{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/bbf9894-add-explicit-api-SNAPSHOT/fixture-bbf9894-add-explicit-api-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "bbf9894-add-explicit-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iossimulatorarm64-bbf9894-add-explicit-api-SNAPSHOT.klib",
          "size": 47247,
          "sha512": "aa5d524afdd908d6c9182c925df7201b66f8edba496adccaec1e0d96b178cd2fce267295da6d65b72f6a8debbefd93d1dace85e513d34c437f0f7e5648981cd0",
          "sha256": "14626b367ae0358a13c8e4956727af1640b699ce4f4cb5aea7b1fac28e49e138",
          "sha1": "81d21ecc0266a869500a14e3396d1fcd83b10e1b",
          "md5": "6e0f91ba4ea675761f1e237c7e50db52"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iossimulatorarm64-bbf9894-add-explicit-api-SNAPSHOT-metadata.jar",
          "url": "fixture-iossimulatorarm64-bbf9894-add-explicit-api-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bcca3818307a7146f497f1e70ad7d5eb2dac38c406cbbea063d8230ea1b6e17e60d352c4fe829abdee43f766b8df40115cd18f94ba233b2c1c454d96144f47d6",
          "sha256": "e0bb9be9edff882d01647efef1207a7b03c9583293fd2cf23573c2e233d5a4b6",
          "sha1": "b46baaaa514825094a15b0625b73f0e6887584f7",
          "md5": "8b506daf249503ba28341ff28997765e"
        }
      ]
    }
  ]
}
