{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "46427ea-add-shared-detekt-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "a609b4f0152c0f0640de8698d050cf2fdba65d14bdfc88d147ddc15bf4d8bb065a5c8e0514b471d24b12b71ea6adccd10d3cee6033ceeb9f70b43a35a47ebbaa",
          "sha256": "98f2b1edc24da6dcab7334dc8400ec93e6f05b53acaa4b39ba20db9b6fb68e35",
          "sha1": "e469813931e5db46323cefb8ac8c0f719daeb033",
          "md5": "f92d657bc48fff3ef276a0fbab3b09e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-46427ea-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "a609b4f0152c0f0640de8698d050cf2fdba65d14bdfc88d147ddc15bf4d8bb065a5c8e0514b471d24b12b71ea6adccd10d3cee6033ceeb9f70b43a35a47ebbaa",
          "sha256": "98f2b1edc24da6dcab7334dc8400ec93e6f05b53acaa4b39ba20db9b6fb68e35",
          "sha1": "e469813931e5db46323cefb8ac8c0f719daeb033",
          "md5": "f92d657bc48fff3ef276a0fbab3b09e4"
        }
      ]
    }
  ]
}
