{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/577fd36-bump-antibytes-SNAPSHOT/test-utils-coroutine-577fd36-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "577fd36-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "size": 10133,
          "sha512": "8247de3fa2c34938a2f6a1791b76dbf90dc23cb13476630edd864001cac89e4fc57847768e108790d9baa2e0dc21ef699573bdcac4fcc3516579aeeb12bfb3b5",
          "sha256": "5cf8586e73fde3e53056d8a0c3d410f332211854fbcb4bcf2e936940a7edbfae",
          "sha1": "f407fed0891b89190fdf6516c570a1e092192763",
          "md5": "c8f9f6a37a2eda77273c4a51c888f1a7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-577fd36-bump-antibytes-SNAPSHOT.klib",
          "size": 10133,
          "sha512": "8247de3fa2c34938a2f6a1791b76dbf90dc23cb13476630edd864001cac89e4fc57847768e108790d9baa2e0dc21ef699573bdcac4fcc3516579aeeb12bfb3b5",
          "sha256": "5cf8586e73fde3e53056d8a0c3d410f332211854fbcb4bcf2e936940a7edbfae",
          "sha1": "f407fed0891b89190fdf6516c570a1e092192763",
          "md5": "c8f9f6a37a2eda77273c4a51c888f1a7"
        }
      ]
    }
  ]
}
