{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/c6e91bd-change-link-target-SNAPSHOT/banana-i18n-c6e91bd-change-link-target-SNAPSHOT.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "c6e91bd-change-link-target-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-c6e91bd-change-link-target-SNAPSHOT.jar",
          "size": 58700,
          "sha512": "1f1a56eee724bb39d88c51e605e086051a9864d65a9e46fc346859eb49a4a696ae614b71c6515b8b2d8114d3ab4addea7be9b6efe7abf801e7ff3d48f6c337d1",
          "sha256": "bd91c5de17d7bd9d716adce07e330711b22c164d3f7b980fe070247c5cde17e5",
          "sha1": "2c014121125604ecca4fb12cfac9eeed31bb5b13",
          "md5": "3ced8eef6edd8e6cad61a8cf755ca978"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-c6e91bd-change-link-target-SNAPSHOT.jar",
          "size": 58700,
          "sha512": "1f1a56eee724bb39d88c51e605e086051a9864d65a9e46fc346859eb49a4a696ae614b71c6515b8b2d8114d3ab4addea7be9b6efe7abf801e7ff3d48f6c337d1",
          "sha256": "bd91c5de17d7bd9d716adce07e330711b22c164d3f7b980fe070247c5cde17e5",
          "sha1": "2c014121125604ecca4fb12cfac9eeed31bb5b13",
          "md5": "3ced8eef6edd8e6cad61a8cf755ca978"
        }
      ]
    }
  ]
}
