{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/df500e4-change-docs-SNAPSHOT/test-utils-ktor-df500e4-change-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-df500e4-change-docs-SNAPSHOT.klib",
          "size": 15027,
          "sha512": "3d77c906bbfbef9b570932f79ce659dfd8372364533a1282318539e3a6b529f7ad1e51a039c5c19f06ed055c0e49353475aa1b515163a579d9d817d60153252e",
          "sha256": "5d33d6a5d95e723448f95966317c2016d15552b03ba56509427d96e5a5ed488c",
          "sha1": "89eff951fe5c9199d0e937c1247ba6a3425b460f",
          "md5": "d13c60d06b7b3931e9ab436df2c9a15a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-df500e4-change-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5a83e911278b7ee97140f6343bb0999eb9e26750cf8a5830efd11af3a878c561fa3c967071be71d607131a1d62a3f9ec73099c57a422cf2edc8ad2242a64478b",
          "sha256": "6d36914a191a1eaa57c8a43724990f146a170b4b846f1999d692114f887a14a8",
          "sha1": "b0dc3856e396713b6c2208fb350adcb16d092ba5",
          "md5": "b2a2e36883a61d9b66fbc7ca729210d8"
        }
      ]
    }
  ]
}
