{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/2025aef-add-more-sources-SNAPSHOT/test-utils-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 8057,
          "sha512": "50e8e4d0ff89ad7fbd20d61697fa20126d29cf254bf2f9144fa779edf52309c7dbc424eead829bef7ce7d09839e00d8213463e4609c891c61b86b07475b059c2",
          "sha256": "ed1e3971564a54352b913d76c9b0a1793141311a0a0f2507933ad8dd66c41146",
          "sha1": "5d3d46dbcdbc354f54cab977745ff3c876eb753c",
          "md5": "c2fe8eebaad916bf04504bdb543a3e4a"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "559303c7689e7be70fae8c3a3cc3aad460f1c7f6b6c7afaffe16ad311bab68d497301d8eb25761fa5ca4e89aac568a985471930c4972d5a34970312ae2b90f7e",
          "sha256": "bec426c55d188167d656581989515b58a55c965339a45e00b45ef229b3c6e42b",
          "sha1": "51022d38be092def501bf38d15441b7a8cb48b8f",
          "md5": "885c02bffc35ffc4c34eee64c6fe89db"
        }
      ]
    }
  ]
}
