{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "ceb410b-add-githubuserhome",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "ceb410b-add-githubuserhome"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-ceb410b-add-githubuserhome.jar",
          "url": "antibytes-publishing-ceb410b-add-githubuserhome.jar",
          "size": 136063,
          "sha512": "ac93ce089c832dbf73dbfb99b572bd3985c6f7ed89730c3c34c24113218d01902a9ec2690cbcc3873b8bb92d037f92a2e38b9d2581b48bba471dbf42f3bd9968",
          "sha256": "d1d72a48f6252b5332a5b3a67899e87e5a15cb1a9cf5699abd9e445964de1da0",
          "sha1": "bcfb18460206e2275ad91767b4fb316f9bda4cf5",
          "md5": "1e308508914fb4d3129e2329f82ca4aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "ceb410b-add-githubuserhome"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "ceb410b-add-githubuserhome"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-ceb410b-add-githubuserhome.jar",
          "url": "antibytes-publishing-ceb410b-add-githubuserhome.jar",
          "size": 136063,
          "sha512": "ac93ce089c832dbf73dbfb99b572bd3985c6f7ed89730c3c34c24113218d01902a9ec2690cbcc3873b8bb92d037f92a2e38b9d2581b48bba471dbf42f3bd9968",
          "sha256": "d1d72a48f6252b5332a5b3a67899e87e5a15cb1a9cf5699abd9e445964de1da0",
          "sha1": "bcfb18460206e2275ad91767b4fb316f9bda4cf5",
          "md5": "1e308508914fb4d3129e2329f82ca4aa"
        }
      ]
    }
  ]
}
