{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/422ab00-bump-antibytes-SNAPSHOT/test-utils-annotations-422ab00-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "422ab00-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "bf81ac95082a03e5acc63e239fcddde6308ffa0c86acd0ebe53942189ac66eba6d71d9ca49f17c620abb273be52be34584e7cdfe1e68b475d04a49f633bc0371",
          "sha256": "1630cc79eee6dd85dd4233247e4caa86ad1fadaebcffe7550cdc9a92bf65b8df",
          "sha1": "5f34750c632366fde412287cf5dcb770a191a521",
          "md5": "854a84a01e743da71903aafe246ffd78"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "bf81ac95082a03e5acc63e239fcddde6308ffa0c86acd0ebe53942189ac66eba6d71d9ca49f17c620abb273be52be34584e7cdfe1e68b475d04a49f633bc0371",
          "sha256": "1630cc79eee6dd85dd4233247e4caa86ad1fadaebcffe7550cdc9a92bf65b8df",
          "sha1": "5f34750c632366fde412287cf5dcb770a191a521",
          "md5": "854a84a01e743da71903aafe246ffd78"
        }
      ]
    }
  ]
}
