{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.node",
    "module": "antibytes-dependency-node",
    "version": "1ba4d29-change-gradle-action-runner",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-node-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-dependency-node-1ba4d29-change-gradle-action-runner.jar",
          "size": 20155,
          "sha512": "ad9d139937b391f7d546817d54b3f7be631abb4d465ffdeef1265de2de17ec79c07c55d03062b13e8dd6ae545ae85ed52cf029e37c1efa5a746a809f54ecaecf",
          "sha256": "3693428d00989bb7aade1cce280607839d8e971ff860b660d627e42191dca753",
          "sha1": "85e69be16d62246de47cfa8e57abcad45a64d5bf",
          "md5": "f6ba2ca4b2f653fbf9268443606cce41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-node-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-dependency-node-1ba4d29-change-gradle-action-runner.jar",
          "size": 20155,
          "sha512": "ad9d139937b391f7d546817d54b3f7be631abb4d465ffdeef1265de2de17ec79c07c55d03062b13e8dd6ae545ae85ed52cf029e37c1efa5a746a809f54ecaecf",
          "sha256": "3693428d00989bb7aade1cce280607839d8e971ff860b660d627e42191dca753",
          "sha1": "85e69be16d62246de47cfa8e57abcad45a64d5bf",
          "md5": "f6ba2ca4b2f653fbf9268443606cce41"
        }
      ]
    }
  ]
}
