{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/bc20163-change-danger-SNAPSHOT/test-utils-coroutine-bc20163-change-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "bc20163-change-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-bc20163-change-danger-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-bc20163-change-danger-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "ef9a51964aaede32e2bcc58be456c084fc14152c327cb993fcc7bafc4569da9b41dbfe3c84e289193fb3a36d6fc043b3ce86cf87a0f89be2fa7813e3135922f7",
          "sha256": "5d364fb103dbcde18daa33a8919e9558f5e55819d9a4ef4089ce1e9e4738da3c",
          "sha1": "2c4c7b50ce0e94672fd7d6884d244a8ad933d529",
          "md5": "642dda279f546ccc84a94f65e18c6d21"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-bc20163-change-danger-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-bc20163-change-danger-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "ef9a51964aaede32e2bcc58be456c084fc14152c327cb993fcc7bafc4569da9b41dbfe3c84e289193fb3a36d6fc043b3ce86cf87a0f89be2fa7813e3135922f7",
          "sha256": "5d364fb103dbcde18daa33a8919e9558f5e55819d9a4ef4089ce1e9e4738da3c",
          "sha1": "2c4c7b50ce0e94672fd7d6884d244a8ad933d529",
          "md5": "642dda279f546ccc84a94f65e18c6d21"
        }
      ]
    }
  ]
}
