{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/13f09a8-add-more-sources-SNAPSHOT/test-utils-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm32-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 7996,
          "sha512": "1975281765ac841c5fc8b2ec87604946a8db52e9a0dd33fb89ac6cdcbafe7cccdfef54b1c28abd2fc6f2caa325a56727d851d959786b5d6fb00da05a6cd297cd",
          "sha256": "db9db4ac6c5f286d389ab7b463d7dc80be9cfe03ebf0c5449693b222fe5709e6",
          "sha1": "53fef8b61249ddf8eb28e7da09d9e791be091e0d",
          "md5": "5763fb77f879aa8e919947a4be235080"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm32-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-watchosarm32-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6766adfd73628b16247d57ea9d0b463ce7b997b2266cf9dab1871a8b3605c73f945855df14f6d3d8033a9623b8da0cbd8f4c2f5f002020f7bf7773179f718679",
          "sha256": "7846dc794ce18f63948795564056950e3bc60fc1dbf6e16692ab61bbccd43ebc",
          "sha1": "c5b26df35ec9a474cf161099cf0efe22dc958ab8",
          "md5": "830d3087fafe02fab9ee66fdbfd815d5"
        }
      ]
    }
  ]
}
