{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "802dbbb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-802dbbb.jar",
          "url": "antibytes-coverage-802dbbb.jar",
          "size": 101858,
          "sha512": "575a32e81a9a8ec63c9dfc91d25985de70f88f8ca5d8fe643d09188f35b01a5ed1014df4eca8f6b51e7f7db51ac58446d001a6fcc091ff17a8bd7a0e2bd6b81f",
          "sha256": "9c0676b30833776122d76817664ab7b94cff417c983330cedbb1d21796568e97",
          "sha1": "647d47b379db03cb77f783a2c8765e37fadbdc18",
          "md5": "c90bc45715d86a2e6017af425fc25e84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-802dbbb.jar",
          "url": "antibytes-coverage-802dbbb.jar",
          "size": 101858,
          "sha512": "575a32e81a9a8ec63c9dfc91d25985de70f88f8ca5d8fe643d09188f35b01a5ed1014df4eca8f6b51e7f7db51ac58446d001a6fcc091ff17a8bd7a0e2bd6b81f",
          "sha256": "9c0676b30833776122d76817664ab7b94cff417c983330cedbb1d21796568e97",
          "sha1": "647d47b379db03cb77f783a2c8765e37fadbdc18",
          "md5": "c90bc45715d86a2e6017af425fc25e84"
        }
      ]
    }
  ]
}
