{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration",
    "module": "antibytes-configuration",
    "version": "e3fda8a-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-e3fda8a-change-plugins.jar",
          "url": "antibytes-configuration-e3fda8a-change-plugins.jar",
          "size": 67165,
          "sha512": "cef9c4a28a7dde55f81e04226035695ca7a4ee03e1ba8209d344b6b12d243b1cc2f48d5c186dea7c0120529279248ae85d88d73fcf0cb2890ae7a5fc31cae3e6",
          "sha256": "20fbd9192a8e09946f26f5adf555f1cb154efbd3806c21848e0f1a3acb9767fe",
          "sha1": "e39f1064fad3009d02df6db71b238b1ca6fdba56",
          "md5": "a5b406f753a4b0078c7fc3d973f16be2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "e3fda8a-change-plugins"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-e3fda8a-change-plugins.jar",
          "url": "antibytes-configuration-e3fda8a-change-plugins.jar",
          "size": 67165,
          "sha512": "cef9c4a28a7dde55f81e04226035695ca7a4ee03e1ba8209d344b6b12d243b1cc2f48d5c186dea7c0120529279248ae85d88d73fcf0cb2890ae7a5fc31cae3e6",
          "sha256": "20fbd9192a8e09946f26f5adf555f1cb154efbd3806c21848e0f1a3acb9767fe",
          "sha1": "e39f1064fad3009d02df6db71b238b1ca6fdba56",
          "md5": "a5b406f753a4b0078c7fc3d973f16be2"
        }
      ]
    }
  ]
}
