{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "f6669bd-add-native-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-metadata-all.jar",
          "url": "test-utils-fixture-f6669bd-add-native-SNAPSHOT-all.jar",
          "size": 10202,
          "sha512": "77781e42fc040f4a3b9d139ad587497594b222e7191c3014933166c6af2dd39d4d809cd28d17509f4a33297ba2a50b6c1bc8c46b7a657b6aa1810c6d5d37e132",
          "sha256": "656563caf568072d42fceb68c76377666e823879b508bcfa6e379494dfb7a34d",
          "sha1": "58a50f20110fd6ac5ed75a3e6311b0c59b44fbb0",
          "md5": "db7a16f65d92226459212e1eea92bd80"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture.jar",
          "url": "test-utils-fixture-f6669bd-add-native-SNAPSHOT.jar",
          "size": 13804,
          "sha512": "dfb0676024ef9aeab834848111639b3aeec23e08747a342dd213fc72c1ec82904b818f446ca16c1f0030131e300f33cddfed9a8f5233f8cf21ec10fe35dca53b",
          "sha256": "c48333f3ce44b7ee6dec39f1b91b9c7ae94dc27946e58220ec87be12fbd8e219",
          "sha1": "1ee1c25926c3b17d7da92d7f3e7ad0afa7e76604",
          "md5": "fb07b704e3cc8e2da0f9983ca66ff970"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/f6669bd-add-native-SNAPSHOT/test-utils-fixture-android-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/f6669bd-add-native-SNAPSHOT/test-utils-fixture-android-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/f6669bd-add-native-SNAPSHOT/test-utils-fixture-js-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/f6669bd-add-native-SNAPSHOT/test-utils-fixture-js-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/f6669bd-add-native-SNAPSHOT/test-utils-fixture-jvm-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/f6669bd-add-native-SNAPSHOT/test-utils-fixture-jvm-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/f6669bd-add-native-SNAPSHOT/test-utils-fixture-linuxx64-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    }
  ]
}
