{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-setup-SNAPSHOT/core-0.4.0-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-macosx64-0.4.0-bump-setup-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "d8a2a3dfb5cce07ba44fa9b2a1b621e2b70ba426660ae4412cb3689f772bcbed18f96cc75c67e8edbead46fd3b24b8b64bca5aeab7abc1f883d8895d89759bb2",
          "sha256": "0a357788587658b0d90ab68d3d288700d74f84a8fae96858bd3f9c03f866eca1",
          "sha1": "bb238872439afdd4ba880cb8cf70c046ea4cae3a",
          "md5": "1c34d6f420c2024e1f48c9db6acccbfa"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-macosx64-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "url": "core-macosx64-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "32b792256cca60c6d880bf3b3d28dd7e04f794f65025c0f78f98c2748c1920d0f45ec6c9c9c5611c949799501adf858ba61d141905a89450ed7f92e2238e76ec",
          "sha256": "05d9802760dd8e7c135fb4879932b78e1a993679491d95576d58ae62b5487723",
          "sha1": "94bfba19e5a080ae602481bfc797284a5b8661a3",
          "md5": "ae56803ccc669b0cc47c12e39ba0e698"
        }
      ]
    }
  ]
}
