{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "b93c89f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-b93c89f.jar",
          "url": "antibytes-runtime-configuration-b93c89f.jar",
          "size": 9073,
          "sha512": "778475ea851c787c5ec7c995cd7ba6e74621d456a76e969c9f4b1b253ddc3247d50532ecabe44b77909fe0f7d807f6945493d3731136aa263b5a228621cbad0e",
          "sha256": "2ded2a9aead3dddf45d856e888d60738132296b079343f8abf16d53acc088ab1",
          "sha1": "8e48e19dccaa40bd14885594c0b0bd201b9fdd42",
          "md5": "24cc06007055c26a6d49e80b8026624f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "b93c89f"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-b93c89f.jar",
          "url": "antibytes-runtime-configuration-b93c89f.jar",
          "size": 9073,
          "sha512": "778475ea851c787c5ec7c995cd7ba6e74621d456a76e969c9f4b1b253ddc3247d50532ecabe44b77909fe0f7d807f6945493d3731136aa263b5a228621cbad0e",
          "sha256": "2ded2a9aead3dddf45d856e888d60738132296b079343f8abf16d53acc088ab1",
          "sha1": "8e48e19dccaa40bd14885594c0b0bd201b9fdd42",
          "md5": "24cc06007055c26a6d49e80b8026624f"
        }
      ]
    }
  ]
}
