{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "221cf2d-change-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-221cf2d-change-settings-plugin.toml",
          "url": "antibytes-dependency-catalog-221cf2d-change-settings-plugin.toml",
          "size": 231310,
          "sha512": "d2438f29e9ef24103af5a90d39d6558b340abda00ee10412f9dc5891d01ad81dc6093b66f83f25567dcd0662cea6d8a3858579b8ab5e5fe33f9b297132f47223",
          "sha256": "488955688d9dbee72c8bc52522d76719634c0c2edd565e6beb49c82c6bbd8b48",
          "sha1": "ccd15efe54dc98daa04f9676b0245a174f3667e1",
          "md5": "7087b58ce6e7a15ee067bbf3d42c1367"
        }
      ]
    }
  ]
}
