{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "23ff0db-add-jvm-tool-chain",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-23ff0db-add-jvm-tool-chain.jar",
          "url": "antibytes-quality-23ff0db-add-jvm-tool-chain.jar",
          "size": 64574,
          "sha512": "e6bcbb99d2235a63b02956eae536f1484db80c6ed040194160532eabb3e180c7cd8cb339b45ca3fc4d550ba8f72f67f6eb3fb3358844f9866686c6873382002a",
          "sha256": "4f056af8f1721257d2c9a38988072fe11da100c7c403b780008c79852484fdd6",
          "sha1": "9c224889a896a13f8d06265eb19a8d50d70ebb85",
          "md5": "98d1e851cdf460cc89e11fd0e62096a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.22.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "23ff0db-add-jvm-tool-chain"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "23ff0db-add-jvm-tool-chain"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-23ff0db-add-jvm-tool-chain.jar",
          "url": "antibytes-quality-23ff0db-add-jvm-tool-chain.jar",
          "size": 64574,
          "sha512": "e6bcbb99d2235a63b02956eae536f1484db80c6ed040194160532eabb3e180c7cd8cb339b45ca3fc4d550ba8f72f67f6eb3fb3358844f9866686c6873382002a",
          "sha256": "4f056af8f1721257d2c9a38988072fe11da100c7c403b780008c79852484fdd6",
          "sha1": "9c224889a896a13f8d06265eb19a8d50d70ebb85",
          "md5": "98d1e851cdf460cc89e11fd0e62096a2"
        }
      ]
    }
  ]
}
