{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c660192-change-min-android-version-SNAPSHOT/test-utils-ktor-c660192-change-min-android-version-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c660192-change-min-android-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-c660192-change-min-android-version-SNAPSHOT.klib",
          "size": 14830,
          "sha512": "bd7406a5fca33e6df98a56161cb2582114fa2ced0580821ce46ee5d6a0134cde74ed3a178355b1496937476ebaf2a06a9ceb6b173d76160610e3f64a5c9717b1",
          "sha256": "09acb6a01ff2527865f96fef8a0b70cfe59d6a883497dd9ef0c7e468af63345f",
          "sha1": "15f0ffc3a574aa1fc69d10da1e94b0e60c673b11",
          "md5": "952a7893a3e50a89d44f3dc8de80c713"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-c660192-change-min-android-version-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "96c31cdce371295a861a2600eabc6cbe2a7e173173c383a1c0fb0de93f217fd92aaa20779c5abd1eecc050ec9855499f137e04f0f578c4e383f0307cf704c111",
          "sha256": "2c9d6e2ae44b1cf49798fd57a2304e86f5e7b121b53eb493e598edf1955885ad",
          "sha1": "281d6373868eb2229261e384f81d262e50781c96",
          "md5": "3f53fa09a37b6605c1b47022fe3ad83b"
        }
      ]
    }
  ]
}
