{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-change-workflows-SNAPSHOT/ktx-datetime-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-change-workflows-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 40080,
          "sha512": "702fd5fb1355b5a47025b05f94b1c36175eccb590330f4a615f8aae73e8df9133d48b2147dfea54a06fdd773424feb42ca85c3de28dd17fa7565ffb2d64df879",
          "sha256": "2d1be065dc41c4a52a4ccb60eb7ab134eed9e8ceca80df56e82aee177fcd37a6",
          "sha1": "375108b9a2e1676b650afbb75c31d8d320e700f1",
          "md5": "6993b86b8d1700b30876d6d23af1a976"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-js-0.4.0-change-workflows-SNAPSHOT.klib",
          "url": "ktx-datetime-js-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 40080,
          "sha512": "702fd5fb1355b5a47025b05f94b1c36175eccb590330f4a615f8aae73e8df9133d48b2147dfea54a06fdd773424feb42ca85c3de28dd17fa7565ffb2d64df879",
          "sha256": "2d1be065dc41c4a52a4ccb60eb7ab134eed9e8ceca80df56e82aee177fcd37a6",
          "sha1": "375108b9a2e1676b650afbb75c31d8d320e700f1",
          "md5": "6993b86b8d1700b30876d6d23af1a976"
        }
      ]
    }
  ]
}
