{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "98fcfcc-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-custom-component-98fcfcc-change-node-dependencies.jar",
          "size": 16190,
          "sha512": "5c4c9d1f78de5e95b2d423afae0b7802e925938f7abcb2d4970d15bd41a1af672c5f4295331ea6a2bcf0cb6e2a0dd44853449591df37275ac26d273ea8d994f1",
          "sha256": "4e47445a553eba6c59f887241beb7ae23b1128dd8deb77f75d6d08ab40958562",
          "sha1": "ce776cfb7c78e9a145e9fe2acd1dc04081bbb425",
          "md5": "76b46edf8ac6c5e23816d1cc150fca00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-custom-component-98fcfcc-change-node-dependencies.jar",
          "size": 16190,
          "sha512": "5c4c9d1f78de5e95b2d423afae0b7802e925938f7abcb2d4970d15bd41a1af672c5f4295331ea6a2bcf0cb6e2a0dd44853449591df37275ac26d273ea8d994f1",
          "sha256": "4e47445a553eba6c59f887241beb7ae23b1128dd8deb77f75d6d08ab40958562",
          "sha1": "ce776cfb7c78e9a145e9fe2acd1dc04081bbb425",
          "md5": "76b46edf8ac6c5e23816d1cc150fca00"
        }
      ]
    }
  ]
}
