{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-add-datetime-fixture-SNAPSHOT/ktx-datetime-0.3.1-add-datetime-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-add-datetime-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-datetime-fixture-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.3.1-add-datetime-fixture-SNAPSHOT.klib",
          "size": 34680,
          "sha512": "8e8327273461f2993654bcd8f5a6900b8bcfc27b0fea4d198763ccaf734f54c0d2d3d2d09163a9d99a0c244936aa9056dd9d60f597fe25b336b4016938714d1e",
          "sha256": "4aac8278bd8dd89719bf539738a602ba5387f5b8297ed630602c462283a5da4e",
          "sha1": "20668c57c5470dbf05359bc491fc3c37380a2dad",
          "md5": "30458deb0625d4619cf06ef12e5f5896"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-add-datetime-fixture-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.3.1-add-datetime-fixture-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.3.1-add-datetime-fixture-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3b1702076297e0618c5f28fb472a73b301220bbcc0d192283c4cea30db82cff3644f1f6efbdfcf3afbc26f76b659030bdb271da8481c0c76e34dd72ee5592074",
          "sha256": "ef5dc4d05b0713696ec226a0bee5a150332721f462bf530b07882d436be1a0bd",
          "sha1": "5fc4caf98e990feb10d78b6916fa63035485a64c",
          "md5": "8e711ae369c756d68ba43c340c3ced0f"
        }
      ]
    }
  ]
}
