{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-bump-updates-SNAPSHOT/core-0.2.0-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.2.0-bump-updates-SNAPSHOT.aar",
          "size": 90830,
          "sha512": "4fba50daacfa96c26aa3120041e556dfb57f7124b13924121c8c745aa60f8d741a514dd9e007572fb4204b91909df1caeb9e93dd83b502f689979c647aa79fe0",
          "sha256": "4f09f7e068355530960e0d153df2dd6898c91bae2e994b36c70b44046eb49a51",
          "sha1": "1d2c4c4284ff198628932c75d0db32341996389a",
          "md5": "ff18217fee01e2d2dec7c9f259bcce85"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.2.0-bump-updates-SNAPSHOT.aar",
          "size": 90830,
          "sha512": "4fba50daacfa96c26aa3120041e556dfb57f7124b13924121c8c745aa60f8d741a514dd9e007572fb4204b91909df1caeb9e93dd83b502f689979c647aa79fe0",
          "sha256": "4f09f7e068355530960e0d153df2dd6898c91bae2e994b36c70b44046eb49a51",
          "sha1": "1d2c4c4284ff198628932c75d0db32341996389a",
          "md5": "ff18217fee01e2d2dec7c9f259bcce85"
        }
      ]
    }
  ]
}
