{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "fb3fdb1-add-snapshot-supression-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "78b349c55b63b3060a896397b46e6c1b59478113a0542f6d3fce48c71d6c7e2642b3d755b501f39a222c7fdd49978dc7effb780a451d3143dd640e1c94554b42",
          "sha256": "41667660af01aaa99595fbb7c088184516ff0facbe422dcf6ffdbbaffd68c0b6",
          "sha1": "5e2425551440261816712efb7792513fbd96faac",
          "md5": "4a5cc4623c05801b7871f36aff870148"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "78b349c55b63b3060a896397b46e6c1b59478113a0542f6d3fce48c71d6c7e2642b3d755b501f39a222c7fdd49978dc7effb780a451d3143dd640e1c94554b42",
          "sha256": "41667660af01aaa99595fbb7c088184516ff0facbe422dcf6ffdbbaffd68c0b6",
          "sha1": "5e2425551440261816712efb7792513fbd96faac",
          "md5": "4a5cc4623c05801b7871f36aff870148"
        }
      ]
    }
  ]
}
