{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "a037784-bump-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a037784-bump-dependencies.jar",
          "url": "antibytes-mkdocs-a037784-bump-dependencies.jar",
          "size": 12153,
          "sha512": "9561d5e6ea7b5f9adc9cf98e7db1a7007905c6759f6151d453a3bbc03c7f46fbe1f3292723be71589c29753141a5f8533e5e95828ee3290094b65e13ef9b5cfd",
          "sha256": "91e43fcba5da9d7b09096804b1c32f8d1bb71a39294fe793221092368431f497",
          "sha1": "304b9042227f43ec53b9318bb57898fb303fc3aa",
          "md5": "2a130e098473935daa714f084986842c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a037784-bump-dependencies"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-a037784-bump-dependencies.jar",
          "url": "antibytes-mkdocs-a037784-bump-dependencies.jar",
          "size": 12153,
          "sha512": "9561d5e6ea7b5f9adc9cf98e7db1a7007905c6759f6151d453a3bbc03c7f46fbe1f3292723be71589c29753141a5f8533e5e95828ee3290094b65e13ef9b5cfd",
          "sha256": "91e43fcba5da9d7b09096804b1c32f8d1bb71a39294fe793221092368431f497",
          "sha1": "304b9042227f43ec53b9318bb57898fb303fc3aa",
          "md5": "2a130e098473935daa714f084986842c"
        }
      ]
    }
  ]
}
