{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "4fb7c15-change-write-preference-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-4fb7c15-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-4fb7c15-change-write-preference-SNAPSHOT.jar",
          "size": 105446,
          "sha512": "8b38d44e068f57d58e6136f6f01dbc824391c7965892fb8d1b6150384d2bc2de082e5a90214464d110923f3cc867cde76d9d99af4da89a763f0a325a025c09db",
          "sha256": "e9d6b2e9c2cb615ba2c2105b7e755dd43abc5a16954bd034a76c216db95de41f",
          "sha1": "cf8b11ce5a9ad304659c76638cbadb7f3286a970",
          "md5": "4257ae91b196f6c4192ddafe4d3fa6db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "4fb7c15-change-write-preference-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-4fb7c15-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-4fb7c15-change-write-preference-SNAPSHOT.jar",
          "size": 105446,
          "sha512": "8b38d44e068f57d58e6136f6f01dbc824391c7965892fb8d1b6150384d2bc2de082e5a90214464d110923f3cc867cde76d9d99af4da89a763f0a325a025c09db",
          "sha256": "e9d6b2e9c2cb615ba2c2105b7e755dd43abc5a16954bd034a76c216db95de41f",
          "sha1": "cf8b11ce5a9ad304659c76638cbadb7f3286a970",
          "md5": "4257ae91b196f6c4192ddafe4d3fa6db"
        }
      ]
    }
  ]
}
