{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "7b5c888-change-versioning-path",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-7b5c888-change-versioning-path.jar",
          "url": "antibytes-gradle-utils-7b5c888-change-versioning-path.jar",
          "size": 11416,
          "sha512": "f018415994f71ce501819cace66386ad778f64296ca8349a12a59af86b8288dcc059bb0d684e3b58f46d9fc84b3b244d0f3c6819793b5301f015fb221bd166a1",
          "sha256": "bf434a80eb3985ab18aad14f8ec680399ff38ca15cf405ef2b784ba5243d27f0",
          "sha1": "6881ea3cdbc35aba9706355ed665cb3c0a0e4648",
          "md5": "5dbad9bd31dc9be20a5ea6a30010cc65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-7b5c888-change-versioning-path.jar",
          "url": "antibytes-gradle-utils-7b5c888-change-versioning-path.jar",
          "size": 11416,
          "sha512": "f018415994f71ce501819cace66386ad778f64296ca8349a12a59af86b8288dcc059bb0d684e3b58f46d9fc84b3b244d0f3c6819793b5301f015fb221bd166a1",
          "sha256": "bf434a80eb3985ab18aad14f8ec680399ff38ca15cf405ef2b784ba5243d27f0",
          "sha1": "6881ea3cdbc35aba9706355ed665cb3c0a0e4648",
          "md5": "5dbad9bd31dc9be20a5ea6a30010cc65"
        }
      ]
    }
  ]
}
