{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-filter-array-SNAPSHOT/core-0.2.0-add-filter-array-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-filter-array-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-filter-array-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-filter-array-SNAPSHOT.klib",
          "size": 100604,
          "sha512": "8da87d081552c29e3fc8fef0e39129e88819958b0d5a45b629e1c9bfa5ce21a5243a0737ae0bd9d2a07489da2b1d6590cbf0e15e077b311c58bc69f803fd2cc5",
          "sha256": "c19ff354b67bc43b0a56aee06a70ef44218b0c56317e80f8dd245c027f25b15f",
          "sha1": "d523ffd82a2893bc33af4db1138d3eb3e156546a",
          "md5": "23a173deec904a181e04f83edf2acd6c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-filter-array-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-filter-array-SNAPSHOT.klib",
          "size": 100604,
          "sha512": "8da87d081552c29e3fc8fef0e39129e88819958b0d5a45b629e1c9bfa5ce21a5243a0737ae0bd9d2a07489da2b1d6590cbf0e15e077b311c58bc69f803fd2cc5",
          "sha256": "c19ff354b67bc43b0a56aee06a70ef44218b0c56317e80f8dd245c027f25b15f",
          "sha1": "d523ffd82a2893bc33af4db1138d3eb3e156546a",
          "md5": "23a173deec904a181e04f83edf2acd6c"
        }
      ]
    }
  ]
}
