{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/439f307-change-project-setup-SNAPSHOT/test-utils-resourceloader-439f307-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "439f307-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-439f307-change-project-setup-SNAPSHOT.klib",
          "size": 12849,
          "sha512": "b05d419daa737638e1a68389db45e60bea41be3040a340ff709c504009a3e5ec8c8be71a2b276b3138d910f6f6f7f282daed519f0d7ccd55e01886495d2eb310",
          "sha256": "3c611a4912536b6a5fd7316d6a18b4fd7713a78c6c2c4cebe3d2a73d8d0d005f",
          "sha1": "fc5acdc5e365bcf321e84682b21068d4a0b8cd53",
          "md5": "c294d934ca5be70f140b4cd78fcc592f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-439f307-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-439f307-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f70ba1813fb82792c8190616be6efcd56ea4ac46e15d5962f95e8fa6bd383a17fa7c216896b24f6f04b6be3cf70c1b652a5ab414d4b8768df44f5c3dc277829a",
          "sha256": "5fda5cc4080891c36e709d21b89b42db3cf0247d44d232ebf3ad507d3c25eb92",
          "sha1": "8988e6ec3078f0adde2e8aec126b20a9564026a3",
          "md5": "1aaadc435cfa0d5a6f61b09330965c29"
        }
      ]
    }
  ]
}
