{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "7f39fe5-add-agnostic-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-7f39fe5-add-agnostic-sources-SNAPSHOT.jar",
          "url": "kmock-processor-7f39fe5-add-agnostic-sources-SNAPSHOT.jar",
          "size": 48573,
          "sha512": "22ab79f4f867fda47ca4a27bb54493c91df79e19b98b6117ee1277ba9c2f1f0b6edfdcf89f28b7c4ba0c372be8e8d7fa009959a0cd7dc1af7591cb00a9cc1ad7",
          "sha256": "252e077d6245d13cf5b58fef0565c71ca13db3fb60b3a5c4e374f6a39b52b057",
          "sha1": "c1042cc4825d33be402b13adf50aaec32b76d82a",
          "md5": "5cec95bb66549d5a89705eab3bb811fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "7f39fe5-add-agnostic-sources-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-7f39fe5-add-agnostic-sources-SNAPSHOT.jar",
          "url": "kmock-processor-7f39fe5-add-agnostic-sources-SNAPSHOT.jar",
          "size": 48573,
          "sha512": "22ab79f4f867fda47ca4a27bb54493c91df79e19b98b6117ee1277ba9c2f1f0b6edfdcf89f28b7c4ba0c372be8e8d7fa009959a0cd7dc1af7591cb00a9cc1ad7",
          "sha256": "252e077d6245d13cf5b58fef0565c71ca13db3fb60b3a5c4e374f6a39b52b057",
          "sha1": "c1042cc4825d33be402b13adf50aaec32b76d82a",
          "md5": "5cec95bb66549d5a89705eab3bb811fd"
        }
      ]
    }
  ]
}
