{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/09a0395-fix-tests-SNAPSHOT/kmock-09a0395-fix-tests-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "09a0395-fix-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-09a0395-fix-tests-SNAPSHOT.jar",
          "url": "kmock-jvm-09a0395-fix-tests-SNAPSHOT.jar",
          "size": 249130,
          "sha512": "8c1b4a8ce514cf089d1f7630a91b5b771dfb6ae8360bc31ede06e4ead518ab46fb8e37ff602b745650efc8c2a753ec2746dcb26636cff978061c7e73ee6e6d2c",
          "sha256": "01916aac331ff968e4b2a377625f9323beb682026090da088d1ff220c577702d",
          "sha1": "4eff520cd3516648db88fb916a67a26589821a51",
          "md5": "16ab3748c5245f7c0f6f4b96bd79acd3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-09a0395-fix-tests-SNAPSHOT.jar",
          "url": "kmock-jvm-09a0395-fix-tests-SNAPSHOT.jar",
          "size": 249130,
          "sha512": "8c1b4a8ce514cf089d1f7630a91b5b771dfb6ae8360bc31ede06e4ead518ab46fb8e37ff602b745650efc8c2a753ec2746dcb26636cff978061c7e73ee6e6d2c",
          "sha256": "01916aac331ff968e4b2a377625f9323beb682026090da088d1ff220c577702d",
          "sha1": "4eff520cd3516648db88fb916a67a26589821a51",
          "md5": "16ab3748c5245f7c0f6f4b96bd79acd3"
        }
      ]
    }
  ]
}
