{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "4e39a26-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "size": 96199,
          "sha512": "504c4e0f2e299fd8c98edd16767ed9b7d36c431a0351ea6e06087e1e372b0922e05535df50aeddf33138273b59de3733fab69be1aef319a2c7e174b0ddc80d72",
          "sha256": "7031f16b1c091bca7fd4b408e7fdf109d6d9f039162c191ebb8805b37c9d6104",
          "sha1": "10fecbb151730c5287f54f31022b937f5ff8b1b0",
          "md5": "d98d8d7c6a721a1cd61f7f66a14c31cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "4e39a26-add-class-cracker-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "size": 96199,
          "sha512": "504c4e0f2e299fd8c98edd16767ed9b7d36c431a0351ea6e06087e1e372b0922e05535df50aeddf33138273b59de3733fab69be1aef319a2c7e174b0ddc80d72",
          "sha256": "7031f16b1c091bca7fd4b408e7fdf109d6d9f039162c191ebb8805b37c9d6104",
          "sha1": "10fecbb151730c5287f54f31022b937f5ff8b1b0",
          "md5": "d98d8d7c6a721a1cd61f7f66a14c31cb"
        }
      ]
    }
  ]
}
