{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit4-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchosarm64-694b583-change-setup-SNAPSHOT.klib",
          "size": 11389,
          "sha512": "f4be034dbb42bd935565e1be627fbebfbc8fa468773e93e8dcc0a77b9dcade4a48d16822cf916008e0500bf34a2850ab0c30b18893ed999619372a9e0bcd3376",
          "sha256": "8a14569e16b433145ebcfd2b93f46581ad89e513262e253cc6f9e0e68a2b7341",
          "sha1": "df71ee6a8dddcdd80e35447e57a626eb4cba6cc0",
          "md5": "7a0ca67dae234b58a4a9812a692a2be2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchosarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-watchosarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cc7d792a8023c4cd3fc64aae73a50f6274cd3657e5183bff3bfd391d3aedfdd6817b57f48e2feb45a9118f6f2e89a9c72a740487fba642031ec3810f86457075",
          "sha256": "7d7d5740a5675ed6bdd0fc5b7b3d91888514f9209aa1ee99807eb91ced9afca3",
          "sha1": "bbac3f498fb29ae7a0e13dae7c82a238d7e9a11a",
          "md5": "c202853f7dd3f355e8a64a4b2438aebf"
        }
      ]
    }
  ]
}
