{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "884eb26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-884eb26.jar",
          "url": "antibytes-gradle-utils-884eb26.jar",
          "size": 9568,
          "sha512": "fca87f2dfe1facea2dd5e117f5e56ee783c6890ddb4f04d44c0dc0cd7bcb8ed19e4b2aea67b10c0a0f2a8195de523a44ae7daf5a06098202ab0f9fda86cdb50d",
          "sha256": "189e71f070345b06fbb370080854c9e2f03d38ed6001040d05d9b8864ccaefaa",
          "sha1": "e4f2f0700a6f8b8bf3f52e96c689d11438959b76",
          "md5": "2c4b9351604cb76acfe9476fea693137"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-884eb26.jar",
          "url": "antibytes-gradle-utils-884eb26.jar",
          "size": 9568,
          "sha512": "fca87f2dfe1facea2dd5e117f5e56ee783c6890ddb4f04d44c0dc0cd7bcb8ed19e4b2aea67b10c0a0f2a8195de523a44ae7daf5a06098202ab0f9fda86cdb50d",
          "sha256": "189e71f070345b06fbb370080854c9e2f03d38ed6001040d05d9b8864ccaefaa",
          "sha1": "e4f2f0700a6f8b8bf3f52e96c689d11438959b76",
          "md5": "2c4b9351604cb76acfe9476fea693137"
        }
      ]
    }
  ]
}
