{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "97a7c7a-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-metadata-97a7c7a-bump-antibytes-SNAPSHOT-all.jar",
          "url": "test-utils-coroutine-97a7c7a-bump-antibytes-SNAPSHOT-all.jar",
          "size": 10616,
          "sha512": "284b2e86e481e5e1469c9304b9e19e13a2e492dea00040e12fee2ebf12532cd6c5722fea49c039f67125b0006c8b0e3c6312ea3df6d79c8651f1b5a7810bcfdb",
          "sha256": "68032b32c6d0b431ef1d43018f30a667d9ce84db299f651d234cbbcefcbc78f4",
          "sha1": "8666debab2ce87af2af5059cc48355210d3b086d",
          "md5": "9df68ed5da704c12e9c58fb0a9efe26f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-97a7c7a-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-coroutine-97a7c7a-bump-antibytes-SNAPSHOT.jar",
          "size": 3034,
          "sha512": "f603fd73731ffa03f64238b61419543633d04603b6e0157afbf4c019be8dec9008dae8c6e04b9f3b2cf2b2a89e096af67453554e6b96a5ffd89f017e6bae3554",
          "sha256": "5906faf07f3638b507f25d7b18b00ae8c808863fb06e1902383cf88e24692d24",
          "sha1": "6af3be7e77d5c82907cabc2e506d32afaae26955",
          "md5": "7d9fa6b32f9dc83a16aee64a854b06f0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-android-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-android-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iosarm64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iosarm64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iossimulatorarm64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iossimulatorarm64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iosx64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-iosx64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-js-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-js-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-jvm-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-jvm-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/97a7c7a-bump-antibytes-SNAPSHOT/test-utils-coroutine-linuxx64-97a7c7a-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "97a7c7a-bump-antibytes-SNAPSHOT"
      }
    }
  ]
}
