{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "be90491",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-be90491.jar",
          "url": "antibytes-coverage-be90491.jar",
          "size": 128528,
          "sha512": "f7ee1836cfa293c51ac3fb971464dbb17b4a48d3d6826872455ef7dd31286794f0fb84136b417dd39225113fa794ddc07792383c59bb1eac9fcc77d0fed9d0b2",
          "sha256": "d0a3fd9c64002cb9b9c2f7e404c35f69021262665edc26eccb476e207ab10bd1",
          "sha1": "a346b21470dbb98090469fd093e30c04f461dd41",
          "md5": "11f41f1b2af4ddf7d34fdd69b78053ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "be90491"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-be90491.jar",
          "url": "antibytes-coverage-be90491.jar",
          "size": 128528,
          "sha512": "f7ee1836cfa293c51ac3fb971464dbb17b4a48d3d6826872455ef7dd31286794f0fb84136b417dd39225113fa794ddc07792383c59bb1eac9fcc77d0fed9d0b2",
          "sha256": "d0a3fd9c64002cb9b9c2f7e404c35f69021262665edc26eccb476e207ab10bd1",
          "sha1": "a346b21470dbb98090469fd093e30c04f461dd41",
          "md5": "11f41f1b2af4ddf7d34fdd69b78053ec"
        }
      ]
    }
  ]
}
