{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "413b23f-add-snapshot-supression",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-413b23f-add-snapshot-supression.toml",
          "url": "antibytes-dependency-catalog-413b23f-add-snapshot-supression.toml",
          "size": 230831,
          "sha512": "a9e48e9042ed1f533aa8b9ba70dd98ea097552a260e1c7b536cbbe4393045a94432f9fd17cf6ac4d049a0bcd1368a7aa87ba72f4d134eae35cabc00dff255aac",
          "sha256": "4e0b20274f5e2e0a9ab62b76b3d64e28e868bf5ae39751929bba99b5b29a3406",
          "sha1": "2d057c788ff6f2e65188b497fb77dff3b865814b",
          "md5": "c48bbbb729521a65d706b5134cc5d124"
        }
      ]
    }
  ]
}
