{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/4bb1282-fix-factory-SNAPSHOT/kmock-4bb1282-fix-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "4bb1282-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-4bb1282-fix-factory-SNAPSHOT.klib",
          "url": "kmock-js-4bb1282-fix-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "03ebcfbef8fa5bc8fd91c0bf48d483a5e6cd8cb661272c3cf02769db76ea2a811a0bed30e28e465e8cb4960c6b72b93e435ca9f879c07260a0d5833125a752c1",
          "sha256": "5352820bd05e784bf4ecc0bc1e6a590eafd543f73287f3c1cbc2c7a6cfa82a16",
          "sha1": "7ecbe31fa385e898853fd7ce05d210d0f990412a",
          "md5": "446d17ad59e78ad78abba851c28f347c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-4bb1282-fix-factory-SNAPSHOT.klib",
          "url": "kmock-js-4bb1282-fix-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "03ebcfbef8fa5bc8fd91c0bf48d483a5e6cd8cb661272c3cf02769db76ea2a811a0bed30e28e465e8cb4960c6b72b93e435ca9f879c07260a0d5833125a752c1",
          "sha256": "5352820bd05e784bf4ecc0bc1e6a590eafd543f73287f3c1cbc2c7a6cfa82a16",
          "sha1": "7ecbe31fa385e898853fd7ce05d210d0f990412a",
          "md5": "446d17ad59e78ad78abba851c28f347c"
        }
      ]
    }
  ]
}
