{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203092,
          "sha512": "b15abb3127a442f8114acc5be54c5ace031a66390f5ac17112a00ccca9ab8862f228a62e97730a18a7847fcf6963075c62e781e6723e20e9a94fa5f96f1e2743",
          "sha256": "8101a551a4f4e7eb2792c0ead1bad5c3b9c1043f0b6272bb6b782cc3d0525a5c",
          "sha1": "9004cfe8e4eb570c574361fe813a6910c00dabf1",
          "md5": "629da6c4265ba3ba6b15ea7780cca7e8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-macosarm64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "00b2cd6250490d556dd08d8765bcf95e10c124e9e0721644889f8fbce644c4141ad926afe6c29ed7c567ec0c2447f9796f6214bd0b9cc801319d92e88993de18",
          "sha256": "85fd75b71e7e85ec6ce58b08f5e7ef95666bb4dee73d9a63891d3c6fe7bca6f5",
          "sha1": "7e9bdb06d6c65095c04a2ef9106f374ce37e2882",
          "md5": "43e1447c8045104b8c2c373f9252c3c2"
        }
      ]
    }
  ]
}
