{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "24bad3c-change-write-preference-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-24bad3c-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-24bad3c-change-write-preference-SNAPSHOT.jar",
          "size": 105445,
          "sha512": "1c8ea0311c3616eb3f80b8348dc626156e6367b3eb020489d9b7b610b219bd40fc94dddda7df0c2097c3add9921bb899e0219f3706a7c819fbcffe2faf4bc2f8",
          "sha256": "b90d72874a508933fb245efd672ab763edcbb4d9e8590973a8490041df258464",
          "sha1": "ebc0095cb547f54ae7b2872d071985b938355249",
          "md5": "2240945482a548c947814ed34bbcbb95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "24bad3c-change-write-preference-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-24bad3c-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-processor-24bad3c-change-write-preference-SNAPSHOT.jar",
          "size": 105445,
          "sha512": "1c8ea0311c3616eb3f80b8348dc626156e6367b3eb020489d9b7b610b219bd40fc94dddda7df0c2097c3add9921bb899e0219f3706a7c819fbcffe2faf4bc2f8",
          "sha256": "b90d72874a508933fb245efd672ab763edcbb4d9e8590973a8490041df258464",
          "sha1": "ebc0095cb547f54ae7b2872d071985b938355249",
          "md5": "2240945482a548c947814ed34bbcbb95"
        }
      ]
    }
  ]
}
