{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/db53051-change-workflows-SNAPSHOT/test-utils-db53051-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-db53051-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-js-db53051-change-workflows-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "5b33090e2beac81ad933e8359ff26ba64788a6369158941941d6ba491db9f80ac762b548afe9b4307fbf7b711cf607a1ccb2ea2b9f0f174542a87b02944f41ee",
          "sha256": "67bbbed8a9b6cdf425a55de8abefc3fc31a7349ce9f3b3280d97222169426843",
          "sha1": "76ae6f6ac4386e91a5f805ff6a6739f99f987ab6",
          "md5": "477de83ff243841df4d7f4d0034dcb2e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-db53051-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-js-db53051-change-workflows-SNAPSHOT.klib",
          "size": 5477,
          "sha512": "5b33090e2beac81ad933e8359ff26ba64788a6369158941941d6ba491db9f80ac762b548afe9b4307fbf7b711cf607a1ccb2ea2b9f0f174542a87b02944f41ee",
          "sha256": "67bbbed8a9b6cdf425a55de8abefc3fc31a7349ce9f3b3280d97222169426843",
          "sha1": "76ae6f6ac4386e91a5f805ff6a6739f99f987ab6",
          "md5": "477de83ff243841df4d7f4d0034dcb2e"
        }
      ]
    }
  ]
}
