{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "f93098e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-f93098e.jar",
          "url": "antibytes-runtime-configuration-f93098e.jar",
          "size": 9073,
          "sha512": "f9e3de52ec35600b772f5b663e204cd8955d997836be0d72224afc9e37ce7b5e2807b723189f3ee3feea87b1ced8dee16af7fa0574a92f06a6bedf6c01690466",
          "sha256": "4cc1b84ee1c3ee51e22cc491adbd2e49931af7d70e3f2e8965dfa0206a8d8e11",
          "sha1": "a1ccc1309a9a2da3e1f2d57bc3a1f0fb45e27587",
          "md5": "5e600270bd130fc5aacca8bc5a7fe321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f93098e"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-f93098e.jar",
          "url": "antibytes-runtime-configuration-f93098e.jar",
          "size": 9073,
          "sha512": "f9e3de52ec35600b772f5b663e204cd8955d997836be0d72224afc9e37ce7b5e2807b723189f3ee3feea87b1ced8dee16af7fa0574a92f06a6bedf6c01690466",
          "sha256": "4cc1b84ee1c3ee51e22cc491adbd2e49931af7d70e3f2e8965dfa0206a8d8e11",
          "sha1": "a1ccc1309a9a2da3e1f2d57bc3a1f0fb45e27587",
          "md5": "5e600270bd130fc5aacca8bc5a7fe321"
        }
      ]
    }
  ]
}
