{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/0fd7252-change-project-setup-SNAPSHOT/test-utils-ktor-0fd7252-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "0fd7252-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-0fd7252-change-project-setup-SNAPSHOT.klib",
          "size": 15027,
          "sha512": "3d77c906bbfbef9b570932f79ce659dfd8372364533a1282318539e3a6b529f7ad1e51a039c5c19f06ed055c0e49353475aa1b515163a579d9d817d60153252e",
          "sha256": "5d33d6a5d95e723448f95966317c2016d15552b03ba56509427d96e5a5ed488c",
          "sha1": "89eff951fe5c9199d0e937c1247ba6a3425b460f",
          "md5": "d13c60d06b7b3931e9ab436df2c9a15a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-0fd7252-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-0fd7252-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "31bb2559a6f1c4c6c93f49e2ddcc2ae781dab582abf571e5a9be5c6f6c5251cd94ee11bbfb6ff9a2db8d1a2ed0e894d20841fc11dbbb5f1fce344c246bdde47e",
          "sha256": "1587ded2b10dad845527ce16f7e55a0d24bc4b7447aa2ca08252d8b17fe27d50",
          "sha1": "879e1f5e243a0df4cfac49fa12c71c12a2409bef",
          "md5": "742b52237a3191b80050dd25e3f72aee"
        }
      ]
    }
  ]
}
