{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "763e91a-change-error-handling-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-763e91a-change-error-handling-SNAPSHOT.jar",
          "size": 14182,
          "sha512": "0c8d59debccf1185ee2eaaf6f90a56f7949fa8115d530097f35ac472b3725b4e3439b0a352079f16979071efb05b74f915f2b4d0fe75f8840156921d9c0f2833",
          "sha256": "832e403756515bc56c807e8517b4e21bb4d17e9c31dcbf2dbe214687d7a9308b",
          "sha1": "ffc8315dae75e809fec20b044078b0d2b983d81f",
          "md5": "a4aa3092f91fcc076aebc34c8e3948b2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/763e91a-change-error-handling-SNAPSHOT/banana-i18n-android-763e91a-change-error-handling-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "763e91a-change-error-handling-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/763e91a-change-error-handling-SNAPSHOT/banana-i18n-android-763e91a-change-error-handling-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "763e91a-change-error-handling-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/763e91a-change-error-handling-SNAPSHOT/banana-i18n-jvm-763e91a-change-error-handling-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "763e91a-change-error-handling-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/763e91a-change-error-handling-SNAPSHOT/banana-i18n-jvm-763e91a-change-error-handling-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "763e91a-change-error-handling-SNAPSHOT"
      }
    }
  ]
}
