{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit4-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 11449,
          "sha512": "30fe12f3fcb58af061a1a7c12052c83b3d482b516a724b30e968bde89483cd992ebec186c9de347012c4a17244d4a107a57c7d5b5d1ab2f75dfe63eda253f531",
          "sha256": "6f47b288262026fd1e541035f53831fde90cd0b1f33f9807576bae4ad4e8e733",
          "sha1": "8465619d9b978d601c52a26c003ca17bbbefea5f",
          "md5": "8661f556610006ea77f189ca46dbd25e"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4ca01eadddae04695b973545ffc1f6207533d959420ca9caa54de162640f64758773b4ad8602d2dfa2cb2e37afb4a0ef12f4b9b10cc96fc389c0a562cdb99590",
          "sha256": "c0efb4aa1414ba7c4dbf2a060f124eb77d2081a0223054d9c49b44e740149742",
          "sha1": "7f3e90682102ee99dd6ae941e221835fcb44cba7",
          "md5": "3808fef5755b6197784d5fc2393f9106"
        }
      ]
    }
  ]
}
