{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/628439b-add-spy-flag-SNAPSHOT/kmock-628439b-add-spy-flag-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "628439b-add-spy-flag-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-628439b-add-spy-flag-SNAPSHOT.jar",
          "url": "kmock-jvm-628439b-add-spy-flag-SNAPSHOT.jar",
          "size": 264329,
          "sha512": "d26e2b2cbb55cb341e536ac0dc96ab188a1dd6f1db456a0130782d2fb5c5533afdd71867c3aa5b2054df2510e8c6663af8705fba3c58a024f693f86b337ac713",
          "sha256": "e00c07a2406b68feef28f3774b372bb978a52a4f354d9911f74ce50bbb0462fc",
          "sha1": "c04a66da7412878d897357a98c4ff7ddf392d573",
          "md5": "1bd5066eb58b3201f32182f9ea5eba9d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-628439b-add-spy-flag-SNAPSHOT.jar",
          "url": "kmock-jvm-628439b-add-spy-flag-SNAPSHOT.jar",
          "size": 264329,
          "sha512": "d26e2b2cbb55cb341e536ac0dc96ab188a1dd6f1db456a0130782d2fb5c5533afdd71867c3aa5b2054df2510e8c6663af8705fba3c58a024f693f86b337ac713",
          "sha256": "e00c07a2406b68feef28f3774b372bb978a52a4f354d9911f74ce50bbb0462fc",
          "sha1": "c04a66da7412878d897357a98c4ff7ddf392d573",
          "md5": "1bd5066eb58b3201f32182f9ea5eba9d"
        }
      ]
    }
  ]
}
