{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "2709ef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-2709ef8.jar",
          "url": "antibytes-versioning-2709ef8.jar",
          "size": 16029,
          "sha512": "fe5331806970fbef1f58861079b4e576fbe763ce4ced62476229dc2f7f1e631fec184f5fc15ec53d31362e69d65738eee183b6356006bd4e65bcf9931ecf4f4b",
          "sha256": "e7e151a3e24b8d1ff2d4d8e0a7af04b6d5d427a2fb5a1ecb16778efe3d1c0204",
          "sha1": "09f638dc53480f22ae2d12040c54d71f8f088b52",
          "md5": "0ae63d7c321f205a033924db4fa55d7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-2709ef8.jar",
          "url": "antibytes-versioning-2709ef8.jar",
          "size": 16029,
          "sha512": "fe5331806970fbef1f58861079b4e576fbe763ce4ced62476229dc2f7f1e631fec184f5fc15ec53d31362e69d65738eee183b6356006bd4e65bcf9931ecf4f4b",
          "sha256": "e7e151a3e24b8d1ff2d4d8e0a7af04b6d5d427a2fb5a1ecb16778efe3d1c0204",
          "sha1": "09f638dc53480f22ae2d12040c54d71f8f088b52",
          "md5": "0ae63d7c321f205a033924db4fa55d7d"
        }
      ]
    }
  ]
}
