{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "a037784-bump-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-a037784-bump-dependencies.jar",
          "url": "antibytes-gradle-utils-a037784-bump-dependencies.jar",
          "size": 11416,
          "sha512": "44ed5b8c0be1d2d09dd6338ca2e0f3c4623d9c955a8df6e879285e62c11ee08a7081cf8d3e130b29e25682992c8cda202718e4bcafd545c6bf6ae54827532e4b",
          "sha256": "de316f8097cfe002c3aaf941ca70e962ba4d2d2f6430d492b0d67e772f5c7be6",
          "sha1": "1b5f9603b1c7e76a314398c8e782f46d9ccf6885",
          "md5": "a55537c1d539248bb29d97cd7f015d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-a037784-bump-dependencies.jar",
          "url": "antibytes-gradle-utils-a037784-bump-dependencies.jar",
          "size": 11416,
          "sha512": "44ed5b8c0be1d2d09dd6338ca2e0f3c4623d9c955a8df6e879285e62c11ee08a7081cf8d3e130b29e25682992c8cda202718e4bcafd545c6bf6ae54827532e4b",
          "sha256": "de316f8097cfe002c3aaf941ca70e962ba4d2d2f6430d492b0d67e772f5c7be6",
          "sha1": "1b5f9603b1c7e76a314398c8e782f46d9ccf6885",
          "md5": "a55537c1d539248bb29d97cd7f015d01"
        }
      ]
    }
  ]
}
