{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "36d2831",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-36d2831.jar",
          "url": "antibytes-grammar-tools-36d2831.jar",
          "size": 39371,
          "sha512": "6b02fe573798c52964c7721a6f09c42739730b45a1967a98761e0bf84531cd8ed88baf7fda3484b419ca6f8675925855b0df29e112a8e6b83c4a5263c44d3201",
          "sha256": "fe45d24771f8236d6027d9ce9860ff8486d082f6b89689b75d96607762e94af2",
          "sha1": "82bc435d84f36be73325535b57da0111f0157ed2",
          "md5": "97af2def3eecc5a57f15f682ae8dfe93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-36d2831.jar",
          "url": "antibytes-grammar-tools-36d2831.jar",
          "size": 39371,
          "sha512": "6b02fe573798c52964c7721a6f09c42739730b45a1967a98761e0bf84531cd8ed88baf7fda3484b419ca6f8675925855b0df29e112a8e6b83c4a5263c44d3201",
          "sha256": "fe45d24771f8236d6027d9ce9860ff8486d082f6b89689b75d96607762e94af2",
          "sha1": "82bc435d84f36be73325535b57da0111f0157ed2",
          "md5": "97af2def3eecc5a57f15f682ae8dfe93"
        }
      ]
    }
  ]
}
