{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/3f8f5c0-bump-updates-SNAPSHOT/test-utils-coroutine-3f8f5c0-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "3f8f5c0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-3f8f5c0-bump-updates-SNAPSHOT.klib",
          "size": 10106,
          "sha512": "02ce8f38e420fa08551dd6f5a86c0557b925545a4f67ef44fc75b2daebf71f1e42862750a4ada7e58574620fa6f0f61b0f6549beef912a434a77b438c9d1f38a",
          "sha256": "fc64666e157fe7adae20326767108704b92f84f44b6f68c6c9d50c17d1ba7d3a",
          "sha1": "b220d207ca03b7f1ebd7c0388794a938d0604ac4",
          "md5": "2fb806bedfc31aae958dd62e00ecbe95"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-3f8f5c0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosx64-3f8f5c0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "de496260517edcfd9cc3009af321ae4404b2c007fc743d8bb9cbe013f04632248496f93718b464b9f6399b347387a16da82d2e7059af99fca2db7b7fef0ee7a4",
          "sha256": "4a7557fe5e41aa600184cede7a8033b29801c3b98263231bdb3f227c91b55c40",
          "sha1": "29ed3d42eae0275a7363e38a9e77a922484ca9ed",
          "md5": "6a4d7dacbf27b0daa0558b3df7fb9b1c"
        }
      ]
    }
  ]
}
