{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "6c9977a-change-plugin-resolution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-dependency-bridge-6c9977a-change-plugin-resolution.jar",
          "size": 38501,
          "sha512": "32ad98e12ea37e033a594bd07f9e5208ba9fe1c0bc1932f3568028681b8934670331d362791483d77d4b33abdddb02f7ad16c8c258872f05fbfe0fbbffaa2af7",
          "sha256": "b7c5c3834cb2e3f8fc2bf460bb9b1b3d1ee3314127b7cb376241947992c4e18c",
          "sha1": "b650ab9333a359ec6ef5bcb3d204dd47a4e52b74",
          "md5": "e659a6791563cdaca8b1090e0c957c40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-dependency-bridge-6c9977a-change-plugin-resolution.jar",
          "size": 38501,
          "sha512": "32ad98e12ea37e033a594bd07f9e5208ba9fe1c0bc1932f3568028681b8934670331d362791483d77d4b33abdddb02f7ad16c8c258872f05fbfe0fbbffaa2af7",
          "sha256": "b7c5c3834cb2e3f8fc2bf460bb9b1b3d1ee3314127b7cb376241947992c4e18c",
          "sha1": "b650ab9333a359ec6ef5bcb3d204dd47a4e52b74",
          "md5": "e659a6791563cdaca8b1090e0c957c40"
        }
      ]
    }
  ]
}
