{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "98fcfcc-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-dependency-settings-98fcfcc-change-node-dependencies.jar",
          "size": 11259,
          "sha512": "e86af5011a7fed142631296f975b57715b4e962df0d3423e625c52655795c7382576da458f9ccad8a3752f14525b7da738d86c5fdfe26c7680f1ae6eabe75c1e",
          "sha256": "ed02a4406b706204deb18367412921b7aaa04bf0c6b78339a039fad34706eb7e",
          "sha1": "00dbc7efb4396dc4b6ab900f990d4a0d843ab912",
          "md5": "f736e7254be6a7c5a5664b3c917b1ee5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-dependency-settings-98fcfcc-change-node-dependencies.jar",
          "size": 11259,
          "sha512": "e86af5011a7fed142631296f975b57715b4e962df0d3423e625c52655795c7382576da458f9ccad8a3752f14525b7da738d86c5fdfe26c7680f1ae6eabe75c1e",
          "sha256": "ed02a4406b706204deb18367412921b7aaa04bf0c6b78339a039fad34706eb7e",
          "sha1": "00dbc7efb4396dc4b6ab900f990d4a0d843ab912",
          "md5": "f736e7254be6a7c5a5664b3c917b1ee5"
        }
      ]
    }
  ]
}
