{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "096ba54-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-096ba54-change-node-dependencies.jar",
          "url": "antibytes-grammar-tools-096ba54-change-node-dependencies.jar",
          "size": 39371,
          "sha512": "ce8f8930b6e79b038c75ac286d2e653d511579e34da5650470736a79e51e8c35a2e484985249be59eb36ef583fe9adef610925a62d220facfa2662f937f7a987",
          "sha256": "b1ec2de596b2c0bdac6bc7936f108682a712f058bfc5c7db6fa8ec7c24cb8b15",
          "sha1": "7000155c8915c636681a092958e31fd6073ab989",
          "md5": "62d933d674b53836c0621140f65951f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-096ba54-change-node-dependencies.jar",
          "url": "antibytes-grammar-tools-096ba54-change-node-dependencies.jar",
          "size": 39371,
          "sha512": "ce8f8930b6e79b038c75ac286d2e653d511579e34da5650470736a79e51e8c35a2e484985249be59eb36ef583fe9adef610925a62d220facfa2662f937f7a987",
          "sha256": "b1ec2de596b2c0bdac6bc7936f108682a712f058bfc5c7db6fa8ec7c24cb8b15",
          "sha1": "7000155c8915c636681a092958e31fd6073ab989",
          "md5": "62d933d674b53836c0621140f65951f2"
        }
      ]
    }
  ]
}
