{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/c96854a-add-tokenizer-SNAPSHOT/banana-i18n-c96854a-add-tokenizer-SNAPSHOT.module",
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "c96854a-add-tokenizer-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-c96854a-add-tokenizer-SNAPSHOT.jar",
          "size": 28897,
          "sha512": "5bfa6d633da97ec551f9208c9922cad687e6cedbc6a09a721cb77ca1e1c1ebc93ec8574f8b1d2b65ecee53c55828840cc5f832fe2a4d59c63c9638ad6e7fc924",
          "sha256": "9d663b1391c1ccee3bad98cfafdcd4629471cb2bdda855599073e8a232c0caf6",
          "sha1": "7ce5a0b39e75556fddd7254f189953312e8a68dc",
          "md5": "79080fc30cc35caf6f3793919021280a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-c96854a-add-tokenizer-SNAPSHOT.jar",
          "size": 28897,
          "sha512": "5bfa6d633da97ec551f9208c9922cad687e6cedbc6a09a721cb77ca1e1c1ebc93ec8574f8b1d2b65ecee53c55828840cc5f832fe2a4d59c63c9638ad6e7fc924",
          "sha256": "9d663b1391c1ccee3bad98cfafdcd4629471cb2bdda855599073e8a232c0caf6",
          "sha1": "7ce5a0b39e75556fddd7254f189953312e8a68dc",
          "md5": "79080fc30cc35caf6f3793919021280a"
        }
      ]
    }
  ]
}
