{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/ad28a6d-remove-dependency-plugin-SNAPSHOT/test-utils-ktor-ad28a6d-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "ad28a6d-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 15027,
          "sha512": "3d77c906bbfbef9b570932f79ce659dfd8372364533a1282318539e3a6b529f7ad1e51a039c5c19f06ed055c0e49353475aa1b515163a579d9d817d60153252e",
          "sha256": "5d33d6a5d95e723448f95966317c2016d15552b03ba56509427d96e5a5ed488c",
          "sha1": "89eff951fe5c9199d0e937c1247ba6a3425b460f",
          "md5": "d13c60d06b7b3931e9ab436df2c9a15a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2f69cedacfc2e0c00d28563c37e0f084ed450b859029ea3c920f85a886e0a89941dcbf833e4020218ba64d2a1a0eab80eaaf8479b41d2529ed46b8ce5bf9138d",
          "sha256": "d8a884e0f9c352d708cc6e974ca7b8afd2f107810dc0d3e3bc6bc476f35f8603",
          "sha1": "25be0037c1dd1d3d3ba7bc8763fd2ff6be3ddc8e",
          "md5": "1905e70e845bb7ad4bbbe6cbfa0d305a"
        }
      ]
    }
  ]
}
