{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/7b11c9d-add-ios-SNAPSHOT/test-utils-ktor-7b11c9d-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "7b11c9d-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-7b11c9d-add-ios-SNAPSHOT.klib",
          "size": 14711,
          "sha512": "9df2845dfeb0f472115c49b39c99c7ef48fe1ab493874c8d4bf680ff11e6bf76ebb3e4944e9da5da3f0b08bd210455f385e0b022c45c37a2895357ebb820d3fc",
          "sha256": "28ffe9f01d69cd81f05a969db9015bbbed26324af79b2365661529c549cf6080",
          "sha1": "8d1886ee30a572649b4e568c69c50bc532fdcaa5",
          "md5": "62474f39b90c9fe47a29b329521b2819"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-metadata.jar",
          "url": "test-utils-ktor-iosx64-7b11c9d-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b28112e5421a4864f5eff6f1624396f382701bcb89cafb7b49166d6043d4371c665d7596ef6c5938c2c36a2e4e41dbad527012905cf7fa1e745692063b658f73",
          "sha256": "4ddbc4085160c3997549e900be443b1609b187618d22bafb660c8583228a3c3d",
          "sha1": "7c847e929aea58db75622f58762f5ea4807326c9",
          "md5": "3bd28eafe6f297415aff8edf7a917fbf"
        }
      ]
    }
  ]
}
