{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/d95dfb5-bump-updates-SNAPSHOT/test-utils-resourceloader-d95dfb5-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "d95dfb5-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-tvosx64-d95dfb5-bump-updates-SNAPSHOT.klib",
          "size": 13542,
          "sha512": "a3aaa240cb92ed1ce7c8e1fde37e8e59cb4e0fed6ef51faaaed9925d6f0cdaeb8fc8a88def4a9c6721a94f475374f7fad2ed7d540ce5ab56bdb17be1c3377b96",
          "sha256": "80066b95f97a458c4a83d4e958ba20c206b27f38ed902ac36b51245eec75e78d",
          "sha1": "2eeacca9cc09a9b47de97951eb867cd606c351df",
          "md5": "98049681411dc0f8029f7bbe39b6526a"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-tvosx64-d95dfb5-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-resourceloader-tvosx64-d95dfb5-bump-updates-SNAPSHOT-sources.jar",
          "size": 4204,
          "sha512": "c70fd08cf38ce00e62349843747847484618f84f805329d7b3a96e9da4c5ffa7985a59b7d39451f41378cb78dea05d762f26b9dfe1d746554543c97b1f4536e1",
          "sha256": "5b8fa5be6494196d10ba709b586e0bce719d7bcdb1d650ec2ee204e3bcfbce96",
          "sha1": "4de28980514374a11665737f18c4650b8179ff14",
          "md5": "9813e4a4fbbc0e94af294a4bd3b2196e"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-tvosx64-d95dfb5-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-tvosx64-d95dfb5-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "857d1313f26d7908c38584afd0f9fb8051e84f59d1ccab86089429173faf5fdc7946e815b71cc5c32140013eb430c10300f1149e7a4da0bff3861ae5ee32e83c",
          "sha256": "8dd03712babd5e529c66bcf3393de019a207391a9f3bc6035f7b0b379d383362",
          "sha1": "9367c4525786dbbc6794a41b6b77a11da17b0798",
          "md5": "03a488666238f386dfce4698d5a3969e"
        }
      ]
    }
  ]
}
