{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/30769ee-change-setup-SNAPSHOT/test-utils-resourceloader-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchosx86-30769ee-change-setup-SNAPSHOT.klib",
          "size": 12884,
          "sha512": "97befb07d483da5cfac5fb5cb70f03b5030081940cde7ecdda0a28066efba9ed327a0e1cc75f1e82e795f7cc7e27781b1b5e5b60f3a80a3975e426b7b6257e14",
          "sha256": "e27c793473cd3b807d62f9d04fbe0ae57ebc0be75a2d9d40a9a8b35ce14f1115",
          "sha1": "41054cbf4eaf874ec283cc9214bece684de4c140",
          "md5": "f936d006f3c551607c37ad10502492de"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchosx86-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-watchosx86-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7ed562ee40fb9efb27439ae26a841217e91c204455848741d968b4c6e54599953ec71c559bbd195a4e3e39e26ecb26788069f61aa5918e69df16fbd01e5ae15d",
          "sha256": "2df03d3508e01497242ad00d81d7005d608a75687e1761a6f6ac270d8c3959fc",
          "sha1": "61afc7f7cc3cf91548486f61b14e26e84959b3ec",
          "md5": "e1840300180504a96f0575ee1b561067"
        }
      ]
    }
  ]
}
