{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "2dcaad0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-2dcaad0.jar",
          "url": "antibytes-publishing-2dcaad0.jar",
          "size": 80284,
          "sha512": "3fb7c640b2d4d1fbb4336422e1bc9de6bfe3593b8bfaa64d6da5faac40b7483359ffa5b81225aec491ca814f628b48d14cf857b1710697751d0141356ecc0130",
          "sha256": "1c36b570988e5a58ebf6bb9421a67345ba03b3a7e7e335fa794340844f944b1b",
          "sha1": "94238d2ae5d07d68a8b970614ddb537cb96335d5",
          "md5": "dd5ce812941488bbb19453d70d8bbfea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-2dcaad0.jar",
          "url": "antibytes-publishing-2dcaad0.jar",
          "size": 80284,
          "sha512": "3fb7c640b2d4d1fbb4336422e1bc9de6bfe3593b8bfaa64d6da5faac40b7483359ffa5b81225aec491ca814f628b48d14cf857b1710697751d0141356ecc0130",
          "sha256": "1c36b570988e5a58ebf6bb9421a67345ba03b3a7e7e335fa794340844f944b1b",
          "sha1": "94238d2ae5d07d68a8b970614ddb537cb96335d5",
          "md5": "dd5ce812941488bbb19453d70d8bbfea"
        }
      ]
    }
  ]
}
