{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-metadata-2025aef-add-more-sources-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-junit5-2025aef-add-more-sources-SNAPSHOT-all.jar",
          "size": 9656,
          "sha512": "fdae7e75933235bf7ef03f5cdc0d817dedf7f7155c9348bf21227a0f762a9441cae47f3cde3b116a198ff088843530f35bb263edbc39309aa7bfa91f0d692c51",
          "sha256": "7fa713690ddc8851afb85e60492f996c63610741caca6043da0ed6ac0c5391cc",
          "sha1": "c8ba13f651f80625c6d9ff06baae362f9fcd2626",
          "md5": "aa3c9c1b6b69f4749beda97788e2adfb"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-2025aef-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-2025aef-add-more-sources-SNAPSHOT.jar",
          "size": 3784,
          "sha512": "61a1b5d6c83b4d33df34eb02992cad1eab2c48bbb4d7bf71333da98ef792fa0d27261a4a8ac5ce271fe72fb5531b2fe5f119a3a3b2df0ce611cdedc8822b1766",
          "sha256": "20e8acece801fb9005e6792436cb2b06f842db01391250aac14a7941a7a81988",
          "sha1": "51d06bfcbe925e350a082ce7ed93502b499c3131",
          "md5": "5f3c49c44a898da1be798cb34b2e6e91"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-android/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-android-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-android",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-android/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-android-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-android",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativearm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-androidnativearm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativearm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativearm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-androidnativearm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativearm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativex64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-androidnativex64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativex64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-androidnativex86/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-androidnativex86-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-androidnativex86",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosarm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosarm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-iosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-iosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-iosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-js/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-js-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-js",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-js/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-js-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-js",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-jvm/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-jvm-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-jvm",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-jvm/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-jvm-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-jvm",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxarm32hfp/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxarm32hfp-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxarm32hfp",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmips32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxmips32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmips32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmips32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxmips32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmips32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmipsel32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxmipsel32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmipsel32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxmipsel32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxmipsel32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxmipsel32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-linuxx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-linuxx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-linuxx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-macosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-macosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-macosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-macosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-macosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-macosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-mingwx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-mingwx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-mingwx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-mingwx86/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-mingwx86-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-mingwx86",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-tvosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-tvosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-tvosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "wasm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "wasm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-wasm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-wasm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-wasm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosarm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm32/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosarm32-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm32",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchossimulatorarm64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchossimulatorarm64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx64/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosx64-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx64",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx86/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosx86-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx86",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit5-watchosx86/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-watchosx86-2025aef-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit5-watchosx86",
        "version": "2025aef-add-more-sources-SNAPSHOT"
      }
    }
  ]
}
