{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "8b34813-add-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-8b34813-add-docs-SNAPSHOT.jar",
          "url": "kmock-gradle-8b34813-add-docs-SNAPSHOT.jar",
          "size": 56273,
          "sha512": "c0941267e8cf5eb47180b302a8e77ff3244716813934413a0b0429ffb18df57805c85d34d436cf2c8ff0399d4bd537036e49e0f1a99054673a496d82274b037b",
          "sha256": "65f579a3deff6794dab5db99acb45c1d2eb3c7c24b1efbfa27de181ea45bfa69",
          "sha1": "a549d15fa9b02aa0082a1b394838d9d55cefc4d1",
          "md5": "5027174d15003801bd55da7c4fba33e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-8b34813-add-docs-SNAPSHOT.jar",
          "url": "kmock-gradle-8b34813-add-docs-SNAPSHOT.jar",
          "size": 56273,
          "sha512": "c0941267e8cf5eb47180b302a8e77ff3244716813934413a0b0429ffb18df57805c85d34d436cf2c8ff0399d4bd537036e49e0f1a99054673a496d82274b037b",
          "sha256": "65f579a3deff6794dab5db99acb45c1d2eb3c7c24b1efbfa27de181ea45bfa69",
          "sha1": "a549d15fa9b02aa0082a1b394838d9d55cefc4d1",
          "md5": "5027174d15003801bd55da7c4fba33e7"
        }
      ]
    }
  ]
}
