{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/d95dfb5-bump-updates-SNAPSHOT/test-utils-annotations-junit4-d95dfb5-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "d95dfb5-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosarm64-d95dfb5-bump-updates-SNAPSHOT.klib",
          "size": 11721,
          "sha512": "d59468c3192e0a8200f7a6f534bd42b6f879af34946fb4fdd58ab00d708a1e6fe6d14dcc493a011612ec1a94490ff87cdfdae7082cb880b8c7f54fb72ae5b245",
          "sha256": "a62367bdc2cbf724c113e2d143029549359c33b3c247b33d06bd3621003fc89f",
          "sha1": "d6cabbd8c9ac04af0b3cf6df94840ddfeb27c71f",
          "md5": "8a86ea76deaa1bd84096c81934c29b09"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-d95dfb5-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-annotations-junit4-macosarm64-d95dfb5-bump-updates-SNAPSHOT-sources.jar",
          "size": 4896,
          "sha512": "2fe566b164f18a378d2c2daef090e149e0410a28bce2fd8eb67e9c81f2f2829b88cd4d3144e475fd0e8bd4d1e875624f6a42181ca5c272ee8cb3c5120df576b8",
          "sha256": "ce6588d8cdfe151428ad5243f3789335be34b41a39afba73df51f6509fb505d9",
          "sha1": "b969be4de0cad713d3e23159129ccc7f8256d550",
          "md5": "7378c76f616bc582b49cf2cf7b9d2f0a"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-d95dfb5-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-macosarm64-d95dfb5-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4008777f79d697a1fecda7020043c1d4d17b76f44ec0ad855aa36aae5e6196215913c2352b5f9f127d8fd2dee321b7def56514f4773b546b2a71b2380b591cad",
          "sha256": "52b2d78294f9ab4879a820cbbe261b56961dae404ab0f3eecde4644f6a17858c",
          "sha1": "01eb86882b5f9a0f50a1a45d72888fff518a27fe",
          "md5": "0a7184003a0d484fe30fca75ff1cf812"
        }
      ]
    }
  ]
}
