{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "17c0b63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-17c0b63.jar",
          "url": "antibytes-dependency-17c0b63.jar",
          "size": 27970,
          "sha512": "41c26b41a187a6c4a15c2ddd3bb85efcf7bd0fd298372fb88ab489d5204a5dbf5409b24978bf41d483951493a5fcd068feab55f44bc874f01213273877b6416e",
          "sha256": "c5d7208bbf0bd2c4c630e515563b79b4793f6c085d7b994f9f39291059df5a27",
          "sha1": "eff116d3dd0f1c77a24baa28e321ba4ed7577776",
          "md5": "902314f944a09f5f5c16d6996babad5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-17c0b63.jar",
          "url": "antibytes-dependency-17c0b63.jar",
          "size": 27970,
          "sha512": "41c26b41a187a6c4a15c2ddd3bb85efcf7bd0fd298372fb88ab489d5204a5dbf5409b24978bf41d483951493a5fcd068feab55f44bc874f01213273877b6416e",
          "sha256": "c5d7208bbf0bd2c4c630e515563b79b4793f6c085d7b994f9f39291059df5a27",
          "sha1": "eff116d3dd0f1c77a24baa28e321ba4ed7577776",
          "md5": "902314f944a09f5f5c16d6996babad5d"
        }
      ]
    }
  ]
}
