{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "df500e4-change-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-metadata-df500e4-change-docs-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-junit4-df500e4-change-docs-SNAPSHOT-all.jar",
          "size": 10416,
          "sha512": "d24dd3eb08bf6c47d3c9bc48adb1936adea4d6f2a8544eafa6c0e4c555af8e8922c871908d041f4b91a4c676a45caf90c212cae865131ac48c622222f73cffff",
          "sha256": "be99c46144576a2cb24672543e2c0988137d74d3aa73e98c5ffaf4fdbea372ca",
          "sha1": "0f6abfc1431c99b5445cc928cf7fb9f051a20e79",
          "md5": "2e799f631bcd1fb3ad7c31a0f21154ec"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-df500e4-change-docs-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-df500e4-change-docs-SNAPSHOT.jar",
          "size": 7381,
          "sha512": "385091c06436f2c9e2797dc03f45871e41cfd0bdda314beab6ab75352121d70b1227cc8d86300caf5cd93fe53ff325c5be50862b8e5820d111540e821962c692",
          "sha256": "d3df404b0c76ce067bf98e2845d3678965b926d9d0a18def429edd87bfbef27e",
          "sha1": "6556b632f60fec9da448a984143802153181a184",
          "md5": "b570195d4dd1217b7ff2e0e039c14519"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-android/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-android-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-android",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-android/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-android-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-android",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iosarm64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iosarm64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iosarm64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iosarm64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iosarm64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iosarm64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iossimulatorarm64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iossimulatorarm64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iossimulatorarm64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iossimulatorarm64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iossimulatorarm64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iossimulatorarm64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iosx64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iosx64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iosx64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-iosx64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-iosx64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-iosx64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-js/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-js-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-js",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-js/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-js-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-js",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-jvm/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-jvm-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-jvm",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-jvm/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-jvm-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-jvm",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-junit4-linuxx64/df500e4-change-docs-SNAPSHOT/test-utils-annotations-junit4-linuxx64-df500e4-change-docs-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-junit4-linuxx64",
        "version": "df500e4-change-docs-SNAPSHOT"
      }
    }
  ]
}
