{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "328bc65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-328bc65.jar",
          "url": "antibytes-dependency-328bc65.jar",
          "size": 31361,
          "sha512": "7eb80a48b252b49dc934332a27642df2f8fac3b339a44f56446efa46e4a3449b800afd5eed2aa0bb03721849f6c58fbfb2640675010f40fe37e71124d3a71498",
          "sha256": "21abab08e8e3ff747021e3347a51f354a698b2b03633c55b0000a45b8f877546",
          "sha1": "cbfbde5a105a88601fdd90cf1db91df9400378ef",
          "md5": "ba54c8821d74e920cbe3985db86f06da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-328bc65.jar",
          "url": "antibytes-dependency-328bc65.jar",
          "size": 31361,
          "sha512": "7eb80a48b252b49dc934332a27642df2f8fac3b339a44f56446efa46e4a3449b800afd5eed2aa0bb03721849f6c58fbfb2640675010f40fe37e71124d3a71498",
          "sha256": "21abab08e8e3ff747021e3347a51f354a698b2b03633c55b0000a45b8f877546",
          "sha1": "cbfbde5a105a88601fdd90cf1db91df9400378ef",
          "md5": "ba54c8821d74e920cbe3985db86f06da"
        }
      ]
    }
  ]
}
