{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "f4626cb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-f4626cb.jar",
          "url": "antibytes-runtime-configuration-f4626cb.jar",
          "size": 10324,
          "sha512": "9ea40f7961114ed1ea39ac2ec193485b11c38cb4cef1a16983950c8d8bf8d89f72dc1ed3d5286f8fcf2105fafbc22082ffbe7768f0018957e96dff03fe72accb",
          "sha256": "7a79cb7b27415ad89b9b3e9e5c4362a3199ebf4ad1f7c3be485029cf0022eee8",
          "sha1": "356f0fb7dbb5c121dcbcc059677a49aaf85b14b1",
          "md5": "99ca4cddceb41d7a75992462dece3529"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f4626cb"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-f4626cb.jar",
          "url": "antibytes-runtime-configuration-f4626cb.jar",
          "size": 10324,
          "sha512": "9ea40f7961114ed1ea39ac2ec193485b11c38cb4cef1a16983950c8d8bf8d89f72dc1ed3d5286f8fcf2105fafbc22082ffbe7768f0018957e96dff03fe72accb",
          "sha256": "7a79cb7b27415ad89b9b3e9e5c4362a3199ebf4ad1f7c3be485029cf0022eee8",
          "sha1": "356f0fb7dbb5c121dcbcc059677a49aaf85b14b1",
          "md5": "99ca4cddceb41d7a75992462dece3529"
        }
      ]
    }
  ]
}
