{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-0.1.0.jar",
          "url": "antibytes-coverage-0.1.0.jar",
          "size": 133706,
          "sha512": "5ecd48817be1c3936a497d7be2bda562d55c93623550f3a4e1d2318558b93d7863e82c7fc1af35a700b0eeabf4008b09b3784527a60cec16c722dded6ed431b1",
          "sha256": "bac66fc79bde3b39eef73f25f3b733448d148a423d8b8bf90b110b525a060b1d",
          "sha1": "eec64af394ace0c26ba6f37bcd3e85c64c95d058",
          "md5": "9d21e643a0fba5dd08ded0e1d4616649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "65d3ce3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-0.1.0.jar",
          "url": "antibytes-coverage-0.1.0.jar",
          "size": 133706,
          "sha512": "5ecd48817be1c3936a497d7be2bda562d55c93623550f3a4e1d2318558b93d7863e82c7fc1af35a700b0eeabf4008b09b3784527a60cec16c722dded6ed431b1",
          "sha256": "bac66fc79bde3b39eef73f25f3b733448d148a423d8b8bf90b110b525a060b1d",
          "sha1": "eec64af394ace0c26ba6f37bcd3e85c64c95d058",
          "md5": "9d21e643a0fba5dd08ded0e1d4616649"
        }
      ]
    }
  ]
}
