{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "ec26e5e-add-shared-detekt-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "253bbc222dcbde75aabef5188a9179f95df2407423f47f28d8be460c2a8547dd4c040bbc0bc036f4ea68efae85374039b801187daa606944444cebe2a31d8a46",
          "sha256": "f2e943f52523caecb8315a92e32bbc738d003261d6958e9abab4ca16a82c5f97",
          "sha1": "0f0d6becd05a0c4810172e258e0569bb7138a8eb",
          "md5": "415467f1ff27cc9d4fb9931a2121a9df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-ec26e5e-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "253bbc222dcbde75aabef5188a9179f95df2407423f47f28d8be460c2a8547dd4c040bbc0bc036f4ea68efae85374039b801187daa606944444cebe2a31d8a46",
          "sha256": "f2e943f52523caecb8315a92e32bbc738d003261d6958e9abab4ca16a82c5f97",
          "sha1": "0f0d6becd05a0c4810172e258e0569bb7138a8eb",
          "md5": "415467f1ff27cc9d4fb9931a2121a9df"
        }
      ]
    }
  ]
}
