{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "120720e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-120720e.jar",
          "url": "antibytes-configuration-120720e.jar",
          "size": 50663,
          "sha512": "06a58dbdfd05b6f1634681aff47f57c2a74f842d7b3e78cbcb129f4f28d30efd66b842cfa144cbc68339871a840b063da6c0d48915be5047cf7a28d3fdbc4c52",
          "sha256": "04d4840d55da8af8301d8ad224d05d9593903cb3c820b96212857c8568bf6ecc",
          "sha1": "5428d0ec60d00852000c96e59b4441dc0f7b329d",
          "md5": "e96fb27dafe489c7bf8a87b51d4f2bda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "120720e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-120720e.jar",
          "url": "antibytes-configuration-120720e.jar",
          "size": 50663,
          "sha512": "06a58dbdfd05b6f1634681aff47f57c2a74f842d7b3e78cbcb129f4f28d30efd66b842cfa144cbc68339871a840b063da6c0d48915be5047cf7a28d3fdbc4c52",
          "sha256": "04d4840d55da8af8301d8ad224d05d9593903cb3c820b96212857c8568bf6ecc",
          "sha1": "5428d0ec60d00852000c96e59b4441dc0f7b329d",
          "md5": "e96fb27dafe489c7bf8a87b51d4f2bda"
        }
      ]
    }
  ]
}
