{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-bump-setup-SNAPSHOT/kmock-0.3.0-rc04-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-bump-setup-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-bump-setup-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "8e0be82d92500a0f24cfa8098d4c0227aeaf7c35fddda91acfc7d17771836fb7080966cc9f6da4741b1d720236ff277faf1c1a2c61e734fe2fdf4523b3dcea14",
          "sha256": "ef041f1e7306e3bfab0a9983cb2df26bf47a44867aa5e4793d12ae173e6df38a",
          "sha1": "9928e52649cc618fd5fc13e745338f8ad34d9461",
          "md5": "8dde2adcab34026727c8faa5db73c605"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-bump-setup-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-bump-setup-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "8e0be82d92500a0f24cfa8098d4c0227aeaf7c35fddda91acfc7d17771836fb7080966cc9f6da4741b1d720236ff277faf1c1a2c61e734fe2fdf4523b3dcea14",
          "sha256": "ef041f1e7306e3bfab0a9983cb2df26bf47a44867aa5e4793d12ae173e6df38a",
          "sha1": "9928e52649cc618fd5fc13e745338f8ad34d9461",
          "md5": "8dde2adcab34026727c8faa5db73c605"
        }
      ]
    }
  ]
}
