{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "d03b409-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-metadata-d03b409-change-workflows-SNAPSHOT-all.jar",
          "url": "test-utils-resourceloader-d03b409-change-workflows-SNAPSHOT-all.jar",
          "size": 10390,
          "sha512": "0cd5ad8a659d1d63664367f912accb7a8e76e91eb171c57e0d36fe31fd5b2c36ffe64c9658f0d355f7d0c59b3d99267fee0d4b4a0e051c648a7535f71b8a724c",
          "sha256": "b8a34b49332f94b29ac61b69a5c87a8d2c949589c1f5906dde454b86c8e3c0e9",
          "sha1": "8c8069f5175df5f2485b59880800af7cc05acc45",
          "md5": "3465459fb9e8e140e7143805af9253e4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-d03b409-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-d03b409-change-workflows-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "bc9f5ae2134fe763bea5eccd4cfcec5f301e0bf8b3642ea1c3303b9509baaf9b08fd3ae0eac000efeabe2712c966b2a7142ae29a97beaa077b40676e6a049f09",
          "sha256": "38dfea017bfab6162a2b40607931fdc6289dfe5e456924d46e2cd76ce44d17de",
          "sha1": "d28c6b77efab3254d94f9dd5729e5bda8616634f",
          "md5": "2eb2ef908398a3176e836099ea77a4d1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-android-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-android-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-js-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-js-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxx64/d03b409-change-workflows-SNAPSHOT/test-utils-resourceloader-linuxx64-d03b409-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxx64",
        "version": "d03b409-change-workflows-SNAPSHOT"
      }
    }
  ]
}
