{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "c8e7c91-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-metadata-c8e7c91-change-workflows-SNAPSHOT-all.jar",
          "url": "test-utils-resourceloader-c8e7c91-change-workflows-SNAPSHOT-all.jar",
          "size": 10390,
          "sha512": "7487b6589dba73705098a291b8e179c0d32d91fd06eb1d58fc6a0513619686d7ad8d5bb3f0ce6c49b45829d77fb226325044051505de7143c7710f711c093232",
          "sha256": "901b422e966a0cffcde9f9402b78b87358891aba2f6cd6bbd58905eb0089ac6d",
          "sha1": "79b888d204ab3c787a7c7fbc534dc6ff2544a302",
          "md5": "06839ff5146f9cb7c9f48d0ef738525b"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-c8e7c91-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-c8e7c91-change-workflows-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "6da376925218386234b40843b2fa537af37fb520367232cf3ab4dc77594280161fcfb85ef79374d6a66cd507598794ceda21255a4ca0db24fb348d813f7ab94b",
          "sha256": "0c4687882a1e2f9fbca8e089fcd25699d9629e5c98db9c1b026ac9cdbd0f584d",
          "sha1": "a2883dfaa4ca97d066d084344a83b8a73370f8c0",
          "md5": "e74f25268e780ffc268dd74acceea204"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-android-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-android-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-js-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-js-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxx64/c8e7c91-change-workflows-SNAPSHOT/test-utils-resourceloader-linuxx64-c8e7c91-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxx64",
        "version": "c8e7c91-change-workflows-SNAPSHOT"
      }
    }
  ]
}
