{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit4-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchosarm64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 11389,
          "sha512": "f4be034dbb42bd935565e1be627fbebfbc8fa468773e93e8dcc0a77b9dcade4a48d16822cf916008e0500bf34a2850ab0c30b18893ed999619372a9e0bcd3376",
          "sha256": "8a14569e16b433145ebcfd2b93f46581ad89e513262e253cc6f9e0e68a2b7341",
          "sha1": "df71ee6a8dddcdd80e35447e57a626eb4cba6cc0",
          "md5": "7a0ca67dae234b58a4a9812a692a2be2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-watchosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fd5b2ccee81ab5df2f313fe7a7c9d68b93d86b431953d26225eb63a02bcf9d85977a5b077f6086311dbac6431902ce04e88ec56b156f29e0a0846f59d6000bdf",
          "sha256": "3a96345d7279983ca27b4c07049fbfe1efa5bb44dec02ca6f430cd289eb44057",
          "sha1": "cfb17a0854c4e3db83045996393ff39355599bd3",
          "md5": "59a393a7ee369b330ccc0c5f97fbcf34"
        }
      ]
    }
  ]
}
