{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "33856fd",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-33856fd.jar",
          "url": "antibytes-grammar-tools-33856fd.jar",
          "size": 39410,
          "sha512": "6396d6306e6cba8f9cda905db7566b099e49ce49574e28547c1023d22ba9b2f0431bf12d5f7e75c186e5c6321933b9cc1b1be295b2f1e8eeb486857c5578bd65",
          "sha256": "b6819bd092020b3a93b4eacb5eace5603f87dbabc73058c135ed764933655afa",
          "sha1": "316bef598f08b70cc9dcc713e41f53feec11e59c",
          "md5": "92deaab33ad42e1a6e9fb225d3e84ae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-33856fd.jar",
          "url": "antibytes-grammar-tools-33856fd.jar",
          "size": 39410,
          "sha512": "6396d6306e6cba8f9cda905db7566b099e49ce49574e28547c1023d22ba9b2f0431bf12d5f7e75c186e5c6321933b9cc1b1be295b2f1e8eeb486857c5578bd65",
          "sha256": "b6819bd092020b3a93b4eacb5eace5603f87dbabc73058c135ed764933655afa",
          "sha1": "316bef598f08b70cc9dcc713e41f53feec11e59c",
          "md5": "92deaab33ad42e1a6e9fb225d3e84ae9"
        }
      ]
    }
  ]
}
