{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-danger-SNAPSHOT/core-0.4.0-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-bump-danger-SNAPSHOT.klib",
          "url": "core-js-0.4.0-bump-danger-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "c00469d1582d753349a12153f3a6e03e56a4778330edc8651ce5e5738079a3cea63941e22d77cf6cfc62ab64acacb0f9dd9390780c125e8ad2cf4a98e4ac46e0",
          "sha256": "739378a45fd31d9a8d05ac07b2fb6a0635040a5ffaecea712d7bfcfa6e13223f",
          "sha1": "8a85ade9df121fd2e04ed55947f5ce72c85cd157",
          "md5": "e6c7bf1eee157bcc66ab90eae5bc768a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.4.0-bump-danger-SNAPSHOT.klib",
          "url": "core-js-0.4.0-bump-danger-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "c00469d1582d753349a12153f3a6e03e56a4778330edc8651ce5e5738079a3cea63941e22d77cf6cfc62ab64acacb0f9dd9390780c125e8ad2cf4a98e4ac46e0",
          "sha256": "739378a45fd31d9a8d05ac07b2fb6a0635040a5ffaecea712d7bfcfa6e13223f",
          "sha1": "8a85ade9df121fd2e04ed55947f5ce72c85cd157",
          "md5": "e6c7bf1eee157bcc66ab90eae5bc768a"
        }
      ]
    }
  ]
}
