{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/46c9fa3-change-gradle-props-SNAPSHOT/test-utils-annotations-46c9fa3-change-gradle-props-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "46c9fa3-change-gradle-props-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-46c9fa3-change-gradle-props-SNAPSHOT.jar",
          "size": 9789,
          "sha512": "02ec187754d9ef97f4fb26b58ecb15aa263869ea04af7ffd5fdbc2fb3f59aaed02ecf5b3dbea271ee85fe7dfc03b8f6c42d0b45b83a23c2f0eb6678d2fce4680",
          "sha256": "cee6a0bb394f696f34aa6f76b36e4f777e65a4bdbe39b69552d580374f3caae3",
          "sha1": "c9ebc206c8a41abf609ff9173b4d628490826e8d",
          "md5": "af9ad32bf9950779549e42204d570811"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-46c9fa3-change-gradle-props-SNAPSHOT.jar",
          "size": 9789,
          "sha512": "02ec187754d9ef97f4fb26b58ecb15aa263869ea04af7ffd5fdbc2fb3f59aaed02ecf5b3dbea271ee85fe7dfc03b8f6c42d0b45b83a23c2f0eb6678d2fce4680",
          "sha256": "cee6a0bb394f696f34aa6f76b36e4f777e65a4bdbe39b69552d580374f3caae3",
          "sha1": "c9ebc206c8a41abf609ff9173b4d628490826e8d",
          "md5": "af9ad32bf9950779549e42204d570811"
        }
      ]
    }
  ]
}
