{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-badges-SNAPSHOT/ktx-datetime-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT.klib",
          "size": 34735,
          "sha512": "7cfd92b026de0784530e54ec149bc4151bed98cd358e27c88a1605cb1a39f879fcbefb6dadd1e83fbde39654020f7c341906bd5c92618919b7cf936656ed5d5f",
          "sha256": "6016ede928cb105c7982af27ae9f49bbaacd82b78c002ef08d130d1eda03b380",
          "sha1": "e7d253954bc0e09e4897ccc551a850e9e788238d",
          "md5": "ba43fcbef624e7375b94f6ec0fa39365"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "79ea5342305ca91882a01bb64712b0f6262c8adedd9c766df46aa4eb9172e501ccd978b35259f0d1af38516476ce9f663f97fe7636ecbe1b5d99e24c61c84e4b",
          "sha256": "f0681ea23551f19b17e20c91ce84f872f3af0081170578ccf2fcd69b4f7602d0",
          "sha1": "30af8e882a7d250ef904015c2387f502a94abded",
          "md5": "795e72c190b2d34443739a6e19263994"
        }
      ]
    }
  ]
}
