{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-sonarcloud-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-0.1.1-add-sonarcloud-SNAPSHOT.jar",
          "url": "kmock-0.1.1-add-sonarcloud-SNAPSHOT.jar",
          "size": 44972,
          "sha512": "4ef642f50b744f55574a23e0080af10bf358315fdda771490c7be93d1e5fe74c34b5ca73cbfbbfab327f64fa095c27fbfa73774766abde1bdbb5aa712258e5f5",
          "sha256": "35893eb0059485b04e500f0266a94ac67a0b3febd418fc66e658f5161c6741eb",
          "sha1": "b7a311b2cf875f6d0483ea6120540869e0975d3b",
          "md5": "2d78e669a596d70b550c0269cf35f6c9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-add-sonarcloud-SNAPSHOT/kmock-android-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.1.1-add-sonarcloud-SNAPSHOT/kmock-android-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.1.1-add-sonarcloud-SNAPSHOT/kmock-iosarm64-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.1.1-add-sonarcloud-SNAPSHOT/kmock-iossimulatorarm64-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.1.1-add-sonarcloud-SNAPSHOT/kmock-iosx64-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-add-sonarcloud-SNAPSHOT/kmock-js-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.1.1-add-sonarcloud-SNAPSHOT/kmock-js-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-add-sonarcloud-SNAPSHOT/kmock-jvm-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.1.1-add-sonarcloud-SNAPSHOT/kmock-jvm-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.1.1-add-sonarcloud-SNAPSHOT/kmock-linuxx64-0.1.1-add-sonarcloud-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.1.1-add-sonarcloud-SNAPSHOT"
      }
    }
  ]
}
