{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/e453a55-add-ios-SNAPSHOT/test-utils-coroutine-e453a55-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "e453a55-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-e453a55-add-ios-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-e453a55-add-ios-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "b4aa88ece8310ec1cce30b1be920ec7cb52415c22b56ae2025e45bd30683b45dcd6a258884f8e5af30cef5946ebbd6b40087a8dbd20daac1cb5f0f3b3b9f0e4b",
          "sha256": "c50a70f6ce7b83d98d70460d500ac270a777e278d1d1dd77038dd1df986a96af",
          "sha1": "759015e1230ac860083c47ff55db7d390a2e616f",
          "md5": "71c10c1050183ee213b3afb4a84487b5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-e453a55-add-ios-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-e453a55-add-ios-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "b4aa88ece8310ec1cce30b1be920ec7cb52415c22b56ae2025e45bd30683b45dcd6a258884f8e5af30cef5946ebbd6b40087a8dbd20daac1cb5f0f3b3b9f0e4b",
          "sha256": "c50a70f6ce7b83d98d70460d500ac270a777e278d1d1dd77038dd1df986a96af",
          "sha1": "759015e1230ac860083c47ff55db7d390a2e616f",
          "md5": "71c10c1050183ee213b3afb4a84487b5"
        }
      ]
    }
  ]
}
