{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-refactor-dependency-distribution-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "size": 239161,
          "sha512": "9bba099a57c66ae52837f0c778a85a2164e01c00f25694745754cdfc91c8370ba64bae1d9ec625c43dcd0892a5677e7b102e6e56cf4930b5332e8cd2c7ddcbbd",
          "sha256": "b688b2d2ef7570634fc997d50ffdb443d41720f30290d3a7aaa697e1d9562287",
          "sha1": "ab146772678e680532b4568847c60f3eaa860f3f",
          "md5": "ce38d4628482e61d880acdffab7ed0c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-refactor-dependency-distribution-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "size": 239161,
          "sha512": "9bba099a57c66ae52837f0c778a85a2164e01c00f25694745754cdfc91c8370ba64bae1d9ec625c43dcd0892a5677e7b102e6e56cf4930b5332e8cd2c7ddcbbd",
          "sha256": "b688b2d2ef7570634fc997d50ffdb443d41720f30290d3a7aaa697e1d9562287",
          "sha1": "ab146772678e680532b4568847c60f3eaa860f3f",
          "md5": "ce38d4628482e61d880acdffab7ed0c8"
        }
      ]
    }
  ]
}
