{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b452879-fix-docs-SNAPSHOT/test-utils-ktor-b452879-fix-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b452879-fix-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-b452879-fix-docs-SNAPSHOT.klib",
          "size": 15027,
          "sha512": "3d77c906bbfbef9b570932f79ce659dfd8372364533a1282318539e3a6b529f7ad1e51a039c5c19f06ed055c0e49353475aa1b515163a579d9d817d60153252e",
          "sha256": "5d33d6a5d95e723448f95966317c2016d15552b03ba56509427d96e5a5ed488c",
          "sha1": "89eff951fe5c9199d0e937c1247ba6a3425b460f",
          "md5": "d13c60d06b7b3931e9ab436df2c9a15a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-b452879-fix-docs-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-b452879-fix-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4beb9800d18fd07e0ccbf3adc0768aee19f843be7d665f47d18015ed459c82421a569e36bfb136080c3ad19a68306f505981772109db9d79e5c4d49ecf258cef",
          "sha256": "1437864d9a66a85a0039e15a9a9dcab569d8a5961919afbf791763216a63b6fb",
          "sha1": "31fc168cbc4bc6524296715710ce2ad05c7a319b",
          "md5": "38812a745e1aa78875f5fea554a707a0"
        }
      ]
    }
  ]
}
