{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/34ae4ae-change-generic-factory-SNAPSHOT/kmock-34ae4ae-change-generic-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "34ae4ae-change-generic-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-34ae4ae-change-generic-factory-SNAPSHOT.klib",
          "url": "kmock-js-34ae4ae-change-generic-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "9bd5451e04e9d6ab371dbeb0104546487271946ebe7c2c91f81f294b1342e21484612a82c6de0363c7d3bb5e86739174a89e9a4802bf2ed8e77dbdfc2c187e0c",
          "sha256": "b6b8aaf5f1f63648a1760e310456b2e3001245d6b567964060d154fe50f86932",
          "sha1": "69f78a9271a586fe71bb72be5384a48fba9bde8c",
          "md5": "f9fcc798007530e7ad31467aae67b344"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-34ae4ae-change-generic-factory-SNAPSHOT.klib",
          "url": "kmock-js-34ae4ae-change-generic-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "9bd5451e04e9d6ab371dbeb0104546487271946ebe7c2c91f81f294b1342e21484612a82c6de0363c7d3bb5e86739174a89e9a4802bf2ed8e77dbdfc2c187e0c",
          "sha256": "b6b8aaf5f1f63648a1760e310456b2e3001245d6b567964060d154fe50f86932",
          "sha1": "69f78a9271a586fe71bb72be5384a48fba9bde8c",
          "md5": "f9fcc798007530e7ad31467aae67b344"
        }
      ]
    }
  ]
}
