{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/ad479d6-change-workflows-SNAPSHOT/test-utils-coroutine-ad479d6-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "ad479d6-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-ad479d6-change-workflows-SNAPSHOT.klib",
          "size": 10129,
          "sha512": "35b514c90d7924051f386b713af1db6f3498cce6fff1721b399759427ff4357415a9d0aa60451287fb65cf5eb6a3fa83a443cb12cbc58aa29d29e96b3d703fe6",
          "sha256": "79c8f739a5068e87f92be4c36c30dfda44bd350019e68a21fe54d318bd820c17",
          "sha1": "a93040db971a59d83fe98682380c7998fecec18f",
          "md5": "fef28cc9f42b966eeda32da41ee99aac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bb6f89299f57f76ed0afc1de86d120010879b34f6f979139ca4d3aee12b45eabe257c990a50a41dab4b02c80a4dea4a467363bb05eadcb6ee5eb65698c74226e",
          "sha256": "44d80347c2105c57d21e3f5ba7a8a5c9ee0c2fbdaac166a7164a6814c3eefac6",
          "sha1": "785c969887d36eed617312862f2837d6e6204700",
          "md5": "352ee7fc60d979ebd957271fd05556f5"
        }
      ]
    }
  ]
}
