{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/333b690-change-workflows-SNAPSHOT/test-utils-ktor-333b690-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "333b690-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "d7f511d97d12c2067630f55a81c7469a7e241f4c6512edc24391bb22deb932b19f4883572f2c1b1703109c1c90168317709485d793645313fbbfba261ffa8310",
          "sha256": "d5ad66f5f41b6d36f4820c9b0b8bf3909af3d21015fed070adf34b4a8a2bfd9d",
          "sha1": "1a07cd9a9a5fc275e01aca0d73ed85979cf740a4",
          "md5": "1b2a1da113169983c8264e49962f3825"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-333b690-change-workflows-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "d7f511d97d12c2067630f55a81c7469a7e241f4c6512edc24391bb22deb932b19f4883572f2c1b1703109c1c90168317709485d793645313fbbfba261ffa8310",
          "sha256": "d5ad66f5f41b6d36f4820c9b0b8bf3909af3d21015fed070adf34b4a8a2bfd9d",
          "sha1": "1a07cd9a9a5fc275e01aca0d73ed85979cf740a4",
          "md5": "1b2a1da113169983c8264e49962f3825"
        }
      ]
    }
  ]
}
