{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "c1ca71e-add-kotlin-android-versionCatalog",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "url": "antibytes-publishing-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "size": 136063,
          "sha512": "6cfc4e7ad362c60b7a609286d961cec00b23cee30136021c723d5d58623c5afd537eb3200e5ea5e0fda1f2f2bcfc38b8af4db1b020567e251a09dffc8bb9c4e6",
          "sha256": "d79861f67482286ddeccdb681d491a0686cc738f9d801c9aee4cdbe281dc0479",
          "sha1": "b7ed4bb7feddef9886caf56cd50e79ab611fe47d",
          "md5": "09f907043651fb02e09cba1a3b0a9aeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "url": "antibytes-publishing-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "size": 136063,
          "sha512": "6cfc4e7ad362c60b7a609286d961cec00b23cee30136021c723d5d58623c5afd537eb3200e5ea5e0fda1f2f2bcfc38b8af4db1b020567e251a09dffc8bb9c4e6",
          "sha256": "d79861f67482286ddeccdb681d491a0686cc738f9d801c9aee4cdbe281dc0479",
          "sha1": "b7ed4bb7feddef9886caf56cd50e79ab611fe47d",
          "md5": "09f907043651fb02e09cba1a3b0a9aeb"
        }
      ]
    }
  ]
}
