{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "4172b90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-4172b90.jar",
          "url": "antibytes-grammar-tools-4172b90.jar",
          "size": 39410,
          "sha512": "ff7709e18da3d429e4600700429e3b1a7ffd3d6dda8c300084246208d08f16af58717ea312ab27699d4305e78005992e51c6bc03cf8a3734e52615326e3b2894",
          "sha256": "3f11b5f881be84e11379e1ff960bc8211bc36e3470be89e93b19881bd11c2a35",
          "sha1": "0aacd15c6b82387c6069eb59f97c0fe75866ab4d",
          "md5": "1d145ffd95b7d58e8702c8af8332882b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-4172b90.jar",
          "url": "antibytes-grammar-tools-4172b90.jar",
          "size": 39410,
          "sha512": "ff7709e18da3d429e4600700429e3b1a7ffd3d6dda8c300084246208d08f16af58717ea312ab27699d4305e78005992e51c6bc03cf8a3734e52615326e3b2894",
          "sha256": "3f11b5f881be84e11379e1ff960bc8211bc36e3470be89e93b19881bd11c2a35",
          "sha1": "0aacd15c6b82387c6069eb59f97c0fe75866ab4d",
          "md5": "1d145ffd95b7d58e8702c8af8332882b"
        }
      ]
    }
  ]
}
