{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/5a5166e-add-class-cracker-SNAPSHOT/kmock-5a5166e-add-class-cracker-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "5a5166e-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-jvm-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "4ddd35c2bacd53fb5232e60e66425e13644e4139b885622fc0429c1a208f38315231607b4834388b5cbb450168cf461fbcd598e7e7696f36d25f73ed3d8b149e",
          "sha256": "3cb113556da7ae0441e3fb2d2703d7a779efdb7ea0dc537559318766b766f497",
          "sha1": "d32f3465433736c10a04fba2877f328b71de1b69",
          "md5": "4a74a867273cbc5f434b97927146b5e0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-jvm-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "4ddd35c2bacd53fb5232e60e66425e13644e4139b885622fc0429c1a208f38315231607b4834388b5cbb450168cf461fbcd598e7e7696f36d25f73ed3d8b149e",
          "sha256": "3cb113556da7ae0441e3fb2d2703d7a779efdb7ea0dc537559318766b766f497",
          "sha1": "d32f3465433736c10a04fba2877f328b71de1b69",
          "md5": "4a74a867273cbc5f434b97927146b5e0"
        }
      ]
    }
  ]
}
