{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-metadata-db53051-change-workflows-SNAPSHOT-all.jar",
          "url": "test-utils-resourceloader-db53051-change-workflows-SNAPSHOT-all.jar",
          "size": 10390,
          "sha512": "9c8661d7794f17e5153ba1c6b1fffeb638c5b0f45b4d1c1028f249f9bc92b4dd0b115d2e4580e1767731f261cf20a593f3215f48f767c4ae910dafb0b3fe5cf4",
          "sha256": "24dce34610332557cdd881d1f053f41d6a5111123217c73972da0ba5e8583374",
          "sha1": "7f073e220db0ce36649f9275e32038fbd8cc9dca",
          "md5": "47f68fb06b91558d8540a37a200a2187"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-db53051-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-resourceloader-db53051-change-workflows-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "5c85d6eff654e1ef91930e6d6a89b477e029cc2a66806629ad7d01b5c2c4401eb88e69e887e4f3805a9a374050fcdff347231e047606d7f9800c6c7a415c7688",
          "sha256": "b4b6ab23f44cd6613bcfb0500b142565b66ffa0edb693c720b1b3d9438ed753c",
          "sha1": "21bc408bf3e836e2c75a10aabe805dbe7338e352",
          "md5": "2fe3b169d2f15b735c65c4ef300fb0f0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-android-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-android/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-android-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-android",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosarm64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iosarm64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosarm64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iossimulatorarm64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iossimulatorarm64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iossimulatorarm64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-iosx64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-iosx64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-iosx64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-js-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-js/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-js-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-js",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-jvm/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-jvm-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-jvm",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-resourceloader-linuxx64/db53051-change-workflows-SNAPSHOT/test-utils-resourceloader-linuxx64-db53051-change-workflows-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-resourceloader-linuxx64",
        "version": "db53051-change-workflows-SNAPSHOT"
      }
    }
  ]
}
