{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "b05233c-change-write-preference-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-b05233c-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-gradle-b05233c-change-write-preference-SNAPSHOT.jar",
          "size": 51329,
          "sha512": "3575b6d6059ca02b82a011dccb74ae63d9f6045d3e463568358cf3ec660db3fac1db846db244f38e688df5aff0da91b5b1e7f7a45e404dbd58baa418ae5fb139",
          "sha256": "2b217d513f2094d3859a5732c8bb10e5ee1036433dd4b56467a53773cff0cb34",
          "sha1": "b89fa34f854003792cbfcf46f9766b16b9cc7734",
          "md5": "cc1aef94b2dc9544305b96f108d10d8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-b05233c-change-write-preference-SNAPSHOT.jar",
          "url": "kmock-gradle-b05233c-change-write-preference-SNAPSHOT.jar",
          "size": 51329,
          "sha512": "3575b6d6059ca02b82a011dccb74ae63d9f6045d3e463568358cf3ec660db3fac1db846db244f38e688df5aff0da91b5b1e7f7a45e404dbd58baa418ae5fb139",
          "sha256": "2b217d513f2094d3859a5732c8bb10e5ee1036433dd4b56467a53773cff0cb34",
          "sha1": "b89fa34f854003792cbfcf46f9766b16b9cc7734",
          "md5": "cc1aef94b2dc9544305b96f108d10d8d"
        }
      ]
    }
  ]
}
