{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-add-more-sources-SNAPSHOT/core-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 105931,
          "sha512": "600898463dad44f638d235c4e6b2258dafa25380b1d084ba7f35eb6d3feaf7321ed249b5f0c0f91094f614adc658ae07999389ab94fbd7a4332563cf34fb554a",
          "sha256": "e97db53c38bed7544ab7dd97af682f6cd868c224bbd178bcfca62a049c8ca72a",
          "sha1": "4e0f0825f4657f1063668f60c4b9b34d75573d87",
          "md5": "974957318c35e7ec8399d8ab3331bb50"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "core-tvossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4a8bf409d0ef01eb27eb7188b183c4a346fd8ccec9f2c87785c0b98127425abbc851f2f2e8c799a8bea05eec1973076ef0d22591acf378d36141cdb9c15a95f1",
          "sha256": "b9dcb08e5e1d630d6f23714741c522b217ffa623ecc0b394edc9c1a82acc74a9",
          "sha1": "f431ea1fcbbca6e008eb39ac21742486c9138906",
          "md5": "11ef536ad8e79a390090160ffd1d0f01"
        }
      ]
    }
  ]
}
