{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-refactor-dependency-distribution-SNAPSHOT/kmock-0.1.1-refactor-dependency-distribution-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-refactor-dependency-distribution-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "a027e4ec9de177a90d25033975dac7331f0fd954267a171ffc99b39f7de7d20093793bff226ded193bc29056b48a900ce42048dd342b5e8aceb4a6bb87f4ecbf",
          "sha256": "bf15c6e20053929fa013fc6ec9ae33277d32a2e8e3e241db51509d9abe7d6b56",
          "sha1": "bb3a5f449542c435f0020779076be64bf66602ed",
          "md5": "d4bfbfdaf367641c25e6750a64192f4b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-refactor-dependency-distribution-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "a027e4ec9de177a90d25033975dac7331f0fd954267a171ffc99b39f7de7d20093793bff226ded193bc29056b48a900ce42048dd342b5e8aceb4a6bb87f4ecbf",
          "sha256": "bf15c6e20053929fa013fc6ec9ae33277d32a2e8e3e241db51509d9abe7d6b56",
          "sha1": "bb3a5f449542c435f0020779076be64bf66602ed",
          "md5": "d4bfbfdaf367641c25e6750a64192f4b"
        }
      ]
    }
  ]
}
