{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "028221d-bump-iphone16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "028221d-bump-iphone16"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-028221d-bump-iphone16.jar",
          "url": "antibytes-dependency-settings-028221d-bump-iphone16.jar",
          "size": 15155,
          "sha512": "40b02a3edd816b75e64927bc694ae3b583d806d3a75ac66134e38f3cc5c0bab22bf6c8394c985cb5f4314b03a8e83edce7a5a44c1bdd56f1be03310ad2f42c0c",
          "sha256": "abc1f95579383f95f3fe93eb5c0a12bd5198e6887e7a84651f92a0070aefcd74",
          "sha1": "2a16f328d57db376521d174fe25f51936932f342",
          "md5": "e3f35f2f7734cd6ad61e7c8f719327f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "028221d-bump-iphone16"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-028221d-bump-iphone16.jar",
          "url": "antibytes-dependency-settings-028221d-bump-iphone16.jar",
          "size": 15155,
          "sha512": "40b02a3edd816b75e64927bc694ae3b583d806d3a75ac66134e38f3cc5c0bab22bf6c8394c985cb5f4314b03a8e83edce7a5a44c1bdd56f1be03310ad2f42c0c",
          "sha256": "abc1f95579383f95f3fe93eb5c0a12bd5198e6887e7a84651f92a0070aefcd74",
          "sha1": "2a16f328d57db376521d174fe25f51936932f342",
          "md5": "e3f35f2f7734cd6ad61e7c8f719327f2"
        }
      ]
    }
  ]
}
