{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/18afd01-fix-single-sources-SNAPSHOT/kmock-18afd01-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "18afd01-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-18afd01-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-18afd01-fix-single-sources-SNAPSHOT.jar",
          "size": 123325,
          "sha512": "b817d16a42bbfb1fb57cc48453b080d82895a39a842179ae7a48251e81b11e8ce527558c1c2561a0e0c021b4b770358bf8c6c1e7ea05ea198a59ff3d9dc4a1ba",
          "sha256": "b248944ebfbedda02209fcb4660da798d5a6e687a100b0ce0381170db34b2071",
          "sha1": "80ff051aa30ae115c30cdd843d3e0284ab2cd254",
          "md5": "4265c0b3659a2a91bdf5ce2f27d47dfe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-18afd01-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-18afd01-fix-single-sources-SNAPSHOT.jar",
          "size": 123325,
          "sha512": "b817d16a42bbfb1fb57cc48453b080d82895a39a842179ae7a48251e81b11e8ce527558c1c2561a0e0c021b4b770358bf8c6c1e7ea05ea198a59ff3d9dc4a1ba",
          "sha256": "b248944ebfbedda02209fcb4660da798d5a6e687a100b0ce0381170db34b2071",
          "sha1": "80ff051aa30ae115c30cdd843d3e0284ab2cd254",
          "md5": "4265c0b3659a2a91bdf5ce2f27d47dfe"
        }
      ]
    }
  ]
}
