{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/bfa7c15-change-publishing-SNAPSHOT/test-utils-annotations-bfa7c15-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "bfa7c15-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "b976a9a75f129b51e1945d89243e4aad4b3ce3a24e0ca667f1a072370626d80b471514709faa8da4034c4000074e0d5c70747c9ec97e2f8ddf854031d778c79f",
          "sha256": "933c78598993fc01a09501382dd552a20b112e962ace340528a5e6b7c7694792",
          "sha1": "352585602b0b4ce35c604b43dec451584b6e9b97",
          "md5": "6faff2821364bad7655e64dcf0885eb9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "b976a9a75f129b51e1945d89243e4aad4b3ce3a24e0ca667f1a072370626d80b471514709faa8da4034c4000074e0d5c70747c9ec97e2f8ddf854031d778c79f",
          "sha256": "933c78598993fc01a09501382dd552a20b112e962ace340528a5e6b7c7694792",
          "sha1": "352585602b0b4ce35c604b43dec451584b6e9b97",
          "md5": "6faff2821364bad7655e64dcf0885eb9"
        }
      ]
    }
  ]
}
