{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-byteArray-generator-SNAPSHOT/core-0.2.0-change-byteArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-byteArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-change-byteArray-generator-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-byteArray-generator-SNAPSHOT.jar",
          "size": 143609,
          "sha512": "ff33680948d6f84d4c51cd1bd2dc8549e65d20829067a4f27569bae9581199a0df60358161bbc3529501a032ba2a769b2b436c49e782d5d211eba1e1e819bf10",
          "sha256": "6de7ea91a5a1f6a8de62a405e2a3f6bfa5eb0ae7fce0abc5eb761d003a726458",
          "sha1": "e02bb83192353160659083825548a39ff7b25806",
          "md5": "24ef3eddfcfd1c1423f7f6c15079255c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-change-byteArray-generator-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-byteArray-generator-SNAPSHOT.jar",
          "size": 143609,
          "sha512": "ff33680948d6f84d4c51cd1bd2dc8549e65d20829067a4f27569bae9581199a0df60358161bbc3529501a032ba2a769b2b436c49e782d5d211eba1e1e819bf10",
          "sha256": "6de7ea91a5a1f6a8de62a405e2a3f6bfa5eb0ae7fce0abc5eb761d003a726458",
          "sha1": "e02bb83192353160659083825548a39ff7b25806",
          "md5": "24ef3eddfcfd1c1423f7f6c15079255c"
        }
      ]
    }
  ]
}
