{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/88b1dde-bump-antibytes-SNAPSHOT/test-utils-fixture-88b1dde-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "88b1dde-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosarm64-88b1dde-bump-antibytes-SNAPSHOT.klib",
          "size": 32832,
          "sha512": "7fe6ef6bc2cf9e6974c6beb95a44df0b7cdcd56affe7d34956aa7ddd8ce8ee98c7f53a0f32e137cd5524fc4a252dd7f8d62c267dcad2b5defdbf80cd8f661094",
          "sha256": "2767a1291f6b0e75624eb854bd6af15718fc74a53555f6635760ca4b3b2c7f18",
          "sha1": "bd18e8ef92b1e6cc6d0088bf3cc1cccc7fe652ac",
          "md5": "15f35e361e2c65b029f047f1db8796c9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosarm64-88b1dde-bump-antibytes-SNAPSHOT-metadata.jar",
          "url": "test-utils-fixture-iosarm64-88b1dde-bump-antibytes-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "414a4780030c6d034fb7b25731f5f8abfa1187a66410019e51b360ccebbfa64341b006c360321a1cd61ac393276b1ece9b144b982b3e18079b8a13ba77150fdb",
          "sha256": "6801a3224288afc3b5938b43db5fa14cbc80100a139a2107542508d9b3f11d9a",
          "sha1": "c2833ac30011a545c6af761b9df5076a997a14f7",
          "md5": "5eaa4744df5dc36dc156575ab019fa8b"
        }
      ]
    }
  ]
}
