{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "c8719de-fix-detekt-distribution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-android-application-configuration-c8719de-fix-detekt-distribution.jar",
          "size": 56574,
          "sha512": "fd9bf102e1c48779ebd9bf05be5c18a7c26a69e39575de550c7e5d6b6c2395c8e901869eee0e0b0bf23f8c1266566f10fa23252ea089a0299b255774b837674c",
          "sha256": "ec2aeb131c88662741c4fa168b8d969b0a178ccaa85a60a0a363fcf65ebcb912",
          "sha1": "2e99d30e9c2ea99c290d4080cfcb613e65976568",
          "md5": "237f52f3bbd163d854f01f242d8623f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-android-application-configuration-c8719de-fix-detekt-distribution.jar",
          "size": 56574,
          "sha512": "fd9bf102e1c48779ebd9bf05be5c18a7c26a69e39575de550c7e5d6b6c2395c8e901869eee0e0b0bf23f8c1266566f10fa23252ea089a0299b255774b837674c",
          "sha256": "ec2aeb131c88662741c4fa168b8d969b0a178ccaa85a60a0a363fcf65ebcb912",
          "sha1": "2e99d30e9c2ea99c290d4080cfcb613e65976568",
          "md5": "237f52f3bbd163d854f01f242d8623f2"
        }
      ]
    }
  ]
}
