{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f000bfd-bump-settings-SNAPSHOT/test-utils-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-macosarm64-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 7979,
          "sha512": "15e92c13a1d1ae285f45bf1ea47a10e833b2d6f12612e4c9e502c433f0a8c52ff4903b3a18630036724c80daac130514ab51d38be91075450c34bf8ba5c65986",
          "sha256": "b994feb1ea8fbb7cb457946a928be9c906e127d48dc0f20bfe08793f76275e2d",
          "sha1": "d3cd45bb90e4a83ca73866fd990a312ae3714d34",
          "md5": "6e7b509f66492f0a753db72e822f5918"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-macosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-macosarm64-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ea1eeb5a9a77c2f5b0d4180997a3e671180420dd7412f9b6909742c73c55aa1139a4c949d7565e8cdd5e57f638a1908a23adf25642ffef90941d34202ec3f83a",
          "sha256": "fbb64d0d1d3e9616672e7829bac08bcbf9edbc30e01f9d1d17dccbdbfb7550a1",
          "sha1": "b26814bdd1e2a349efb371c03f9744aa487758e5",
          "md5": "daef4651121fce72b200a9507c68e1e6"
        }
      ]
    }
  ]
}
