{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "602dec9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-602dec9.jar",
          "url": "antibytes-coverage-602dec9.jar",
          "size": 133730,
          "sha512": "2042a74809ea884003f58b44419625e2758b5c0de52e0cb453ab00884209068bd3bcac928a74dd57c253ce022884ee47317be5319186dacbdc71432762a82e94",
          "sha256": "a7b0fbd965b9a7640939bb7843f7777681c5bf53281f024f29d3954692125818",
          "sha1": "5d9e04698b6e5eae6ef24d450e67adbb61e3c1f0",
          "md5": "c45f869491d39f90cb098bcbdb0e55b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "602dec9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-602dec9.jar",
          "url": "antibytes-coverage-602dec9.jar",
          "size": 133730,
          "sha512": "2042a74809ea884003f58b44419625e2758b5c0de52e0cb453ab00884209068bd3bcac928a74dd57c253ce022884ee47317be5319186dacbdc71432762a82e94",
          "sha256": "a7b0fbd965b9a7640939bb7843f7777681c5bf53281f024f29d3954692125818",
          "sha1": "5d9e04698b6e5eae6ef24d450e67adbb61e3c1f0",
          "md5": "c45f869491d39f90cb098bcbdb0e55b2"
        }
      ]
    }
  ]
}
