{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "5cedb25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-5cedb25.jar",
          "url": "antibytes-gradle-utils-5cedb25.jar",
          "size": 9421,
          "sha512": "cab80807e35385781821af86c89dd7091ba0249d17787ef02f682e8aabeac000cdb1cba897e4fbcb68560da3feec26c4315abb337eb951768ba0a52335032a79",
          "sha256": "07dab097dbd8c8d7ec76db3f3485603dfc4aaaf00d8de47c2e399f9385e3d46a",
          "sha1": "6801d974c29335d954b24c6d4a099d641177d007",
          "md5": "9a044c5de8d920881b367b0105e29728"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-5cedb25.jar",
          "url": "antibytes-gradle-utils-5cedb25.jar",
          "size": 9421,
          "sha512": "cab80807e35385781821af86c89dd7091ba0249d17787ef02f682e8aabeac000cdb1cba897e4fbcb68560da3feec26c4315abb337eb951768ba0a52335032a79",
          "sha256": "07dab097dbd8c8d7ec76db3f3485603dfc4aaaf00d8de47c2e399f9385e3d46a",
          "sha1": "6801d974c29335d954b24c6d4a099d641177d007",
          "md5": "9a044c5de8d920881b367b0105e29728"
        }
      ]
    }
  ]
}
