{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "57ea137",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-57ea137.jar",
          "url": "antibytes-dependency-57ea137.jar",
          "size": 82618,
          "sha512": "1775ff32e9559322708814b1933bb991b9f53fb0498a32d70d38d8289a1962c8091aae3ff3efb9a7f5a663d04bd5aec3f02052882f9654abe3d7be18e0d17a44",
          "sha256": "18cefa4b8fa9efd5d12739eb35e8a82500fa4bdd41828386b8e2d7f941d725f4",
          "sha1": "d1348968169a6a86c583a0881929e8f32bc407d6",
          "md5": "f7176af2df8c23514fc01d3024f179eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "57ea137"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-57ea137.jar",
          "url": "antibytes-dependency-57ea137.jar",
          "size": 82618,
          "sha512": "1775ff32e9559322708814b1933bb991b9f53fb0498a32d70d38d8289a1962c8091aae3ff3efb9a7f5a663d04bd5aec3f02052882f9654abe3d7be18e0d17a44",
          "sha256": "18cefa4b8fa9efd5d12739eb35e8a82500fa4bdd41828386b8e2d7f941d725f4",
          "sha1": "d1348968169a6a86c583a0881929e8f32bc407d6",
          "md5": "f7176af2df8c23514fc01d3024f179eb"
        }
      ]
    }
  ]
}
