{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/13f09a8-add-more-sources-SNAPSHOT/test-utils-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "d281227293d049938c05b7cb41e0104d4f5d825b9943d36847a9e081616c13fc9e2e2f30d909623ae7bc890f7a65b676c067409346a91d199b9c4891ba0b3b1c",
          "sha256": "ff1a247f5217725de60c5f77ccb3ec813f98d6cb0e026806a4a660d5b7e3c4ef",
          "sha1": "18176b6dd6b9caf1436bb359be689261fb9fc45c",
          "md5": "8f4a995948988f7544165dcba883d6c1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "d281227293d049938c05b7cb41e0104d4f5d825b9943d36847a9e081616c13fc9e2e2f30d909623ae7bc890f7a65b676c067409346a91d199b9c4891ba0b3b1c",
          "sha256": "ff1a247f5217725de60c5f77ccb3ec813f98d6cb0e026806a4a660d5b7e3c4ef",
          "sha1": "18176b6dd6b9caf1436bb359be689261fb9fc45c",
          "md5": "8f4a995948988f7544165dcba883d6c1"
        }
      ]
    }
  ]
}
