{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "6498584-add-kotlinjs-wrapper",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-6498584-add-kotlinjs-wrapper.jar",
          "url": "antibytes-dependency-helper-6498584-add-kotlinjs-wrapper.jar",
          "size": 70760,
          "sha512": "2a35b6e2395adec836ac870d439231583aed1e36f18a514e4cad9f736af6377751010dd54d93262100e4f7c6ecffd7f2f5bd82d6d86bcbac5918d252c2c5fb10",
          "sha256": "79f5e4867ff52091ac8ea78baee32b3eed34ed44e141acfd1ab99585e10ff45c",
          "sha1": "b7392f2f08d1d6cd0ececdff315177bc1c1c9878",
          "md5": "aac8ddbecd02542a004d2da01f63f530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6498584-add-kotlinjs-wrapper"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-6498584-add-kotlinjs-wrapper.jar",
          "url": "antibytes-dependency-helper-6498584-add-kotlinjs-wrapper.jar",
          "size": 70760,
          "sha512": "2a35b6e2395adec836ac870d439231583aed1e36f18a514e4cad9f736af6377751010dd54d93262100e4f7c6ecffd7f2f5bd82d6d86bcbac5918d252c2c5fb10",
          "sha256": "79f5e4867ff52091ac8ea78baee32b3eed34ed44e141acfd1ab99585e10ff45c",
          "sha1": "b7392f2f08d1d6cd0ececdff315177bc1c1c9878",
          "md5": "aac8ddbecd02542a004d2da01f63f530"
        }
      ]
    }
  ]
}
