{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/ef3a5b1-bump-updates-SNAPSHOT/test-utils-coroutine-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchossimulatorarm64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 11171,
          "sha512": "6c5f7b78e01831ba79f5994e2784dd759f4031f8fb1eb83fc46c3b5a98a0a7843698a83a61be94c942c3e7976c33e941425e9650c6909b124c29d417b11924ba",
          "sha256": "8de6094922cdecfafead8eec7a38e78e525cbacdcd125c3cd1b6d14030a20c43",
          "sha1": "488b57de9a89c702ee9347506c5b70dc96e590ae",
          "md5": "a005907bf316ae736b7bd95915143599"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-coroutine-watchossimulatorarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-coroutine-watchossimulatorarm64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 4432,
          "sha512": "a6473d4ff59cb600f3c0fa9878a35c8f858acacd98510b4befc1e5f35be910c62a88e3b6041f5ba76c050b7c41af13fff93cd8bf60902a249f16b7429faa3ecf",
          "sha256": "cec6c043fde96eb3a674995451dc91cc39b82763e15d04e005be7dc8b426bde6",
          "sha1": "9c071f18ad7900caca2bc6884118c0e6ea620326",
          "md5": "a9e30d3490844e974b0610b29233965f"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchossimulatorarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-watchossimulatorarm64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "de36952aa9452c688394c7e6c18c53e434facb12b4e0d621bf468292d4050b06796adf2659f4c1068018b3ce67c9b0f0d3808a2ca500fef9394724d359db6502",
          "sha256": "761e02875a3aaa343fc5dae5f4ada97ea1bad063a9d24819c509ad791efe234e",
          "sha1": "1740e1470a2c66e2e6e9633b5057b0d882c8cd91",
          "md5": "2c727ffffa7bc13b9f047f299822389c"
        }
      ]
    }
  ]
}
