{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-enum-selector-SNAPSHOT/core-0.2.0-add-enum-selector-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-enum-selector-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.2.0-add-enum-selector-SNAPSHOT.klib",
          "size": 100172,
          "sha512": "6cf22681423019d39e82c84896ec1183fea6336d13210318ddb87b89288fa538e801cff46f846a8ae4894256c39ed8691d3666b3af316ba1eb2d5d8efb342526",
          "sha256": "3d957dfa579069619e869809dbc8282b5ec21c136515f3a6fdaa9d1ed3636449",
          "sha1": "90fb5f8e56798b8e8c4ab5d85985f1363592aa15",
          "md5": "78b9bc2e546bf08e4e8cecb65b293f63"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.2.0-add-enum-selector-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.2.0-add-enum-selector-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "49d712271c28ff22ddee85f7e8340845390377ce322c07443df3295c779f36584126b879f081e48da5a68bbfa0a8078e4ec65752e8f374189a84015b84f791b0",
          "sha256": "5d81d4b76723ae272ead7411b9caea8f79f2ce94f30aaffbec4b3647fb77bcb8",
          "sha1": "cd386be56fa8a2e22f854c4171a1c96a989fa785",
          "md5": "2c25f01e56df3f70cec0b69912b32a1a"
        }
      ]
    }
  ]
}
