{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-fix-null-generics-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT.jar",
          "size": 40769,
          "sha512": "13e8b000b740f2d61b9b74453b2e6ef708da7f460ee00eab00ea6600a6784b651ac11f883a6a3ceef70639e67e09f73e480f83d682c201425aed0122f005b471",
          "sha256": "154357fc6c0305b09c29b80fe7cce249b2fe22a09e675c6f0babcd78fcb7b027",
          "sha1": "be9047d2d1113a2dbb964bb5b1d4cf67a4362a8c",
          "md5": "e7e18d8ff1756812962b1bf763b130ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT.jar",
          "size": 40769,
          "sha512": "13e8b000b740f2d61b9b74453b2e6ef708da7f460ee00eab00ea6600a6784b651ac11f883a6a3ceef70639e67e09f73e480f83d682c201425aed0122f005b471",
          "sha256": "154357fc6c0305b09c29b80fe7cce249b2fe22a09e675c6f0babcd78fcb7b027",
          "sha1": "be9047d2d1113a2dbb964bb5b1d4cf67a4362a8c",
          "md5": "e7e18d8ff1756812962b1bf763b130ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "888acfb95c868350aad739f01f4310154187b09b31d4b335e841cb87911b9a1acafea4f96c5b01b7d05c4720e52dbbd14c7b3b364e372c3f7c268139f4d47ee1",
          "sha256": "0c547a6b996489f2999ba9c3c8eb3468b1122ec5c66b9b15ad2024927e288c72",
          "sha1": "27e373623d39bb7765cb8dde3d0d6bd88d6bb516",
          "md5": "f4bbe1b5d4fd3ea217d9adf3d9f57170"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-fix-null-generics-SNAPSHOT-sources.jar",
          "size": 10232,
          "sha512": "b44b42f5b2a006a80802e14a3a1f772b324eb9c8dcf7e2085403671819c880bf76f6952d95569ec8f9b4718c0f2064bb3ebc7bcccfb811f88e77ca05f772b9d8",
          "sha256": "5d7933a298d7c5e2aed22d1345ec811c43df8fa11c2c7a3e27830ab8a81d18f7",
          "sha1": "cb0307c96da9c66fd89e71b52a3a23e154712187",
          "md5": "aac162f56c8ab1bcc474256b9515c2b5"
        }
      ]
    }
  ]
}
