{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "e943b87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-e943b87.jar",
          "url": "antibytes-grammar-tools-e943b87.jar",
          "size": 39410,
          "sha512": "fe426432f54569047db0e8ebfc24aaa6e4104b1caf79b0d0b4806f311918692e6581512d95095ed42f418666c58ba160020cd55d61b6b3faf0860f162ea4e1f7",
          "sha256": "de5aa0c0072dba47283f5c34265dcc4bfc4ee469be86663687e298fc5d5bdd2c",
          "sha1": "8d38267fb9d824cf99bacd86d401eddf6d738fd5",
          "md5": "05a5530ef327de0098604a9ec7c395c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-e943b87.jar",
          "url": "antibytes-grammar-tools-e943b87.jar",
          "size": 39410,
          "sha512": "fe426432f54569047db0e8ebfc24aaa6e4104b1caf79b0d0b4806f311918692e6581512d95095ed42f418666c58ba160020cd55d61b6b3faf0860f162ea4e1f7",
          "sha256": "de5aa0c0072dba47283f5c34265dcc4bfc4ee469be86663687e298fc5d5bdd2c",
          "sha1": "8d38267fb9d824cf99bacd86d401eddf6d738fd5",
          "md5": "05a5530ef327de0098604a9ec7c395c9"
        }
      ]
    }
  ]
}
