{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/422ab00-bump-antibytes-SNAPSHOT/test-utils-fixture-422ab00-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "422ab00-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "fa8f67073cd4d7c2f95eac3a8f9cb2c6b30ac5428fad029e650880debc08b2b4dc91a047f0af4dd017fc3e7b42e23110c9b656d2e042f922cfe5594dffd37b08",
          "sha256": "a10149c0a1ff0541ec388a4e1ced18124b71a93abf267d7ebfd667401a6a0692",
          "sha1": "9d2449cc8a414c5c78e2a69f611e6575b83bf328",
          "md5": "887d409ea6e96eba051e0c9dc9acd52f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-422ab00-bump-antibytes-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "fa8f67073cd4d7c2f95eac3a8f9cb2c6b30ac5428fad029e650880debc08b2b4dc91a047f0af4dd017fc3e7b42e23110c9b656d2e042f922cfe5594dffd37b08",
          "sha256": "a10149c0a1ff0541ec388a4e1ced18124b71a93abf267d7ebfd667401a6a0692",
          "sha1": "9d2449cc8a414c5c78e2a69f611e6575b83bf328",
          "md5": "887d409ea6e96eba051e0c9dc9acd52f"
        }
      ]
    }
  ]
}
