{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/e65a2ff-bump-updates-SNAPSHOT/test-utils-e65a2ff-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "e65a2ff-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-e65a2ff-bump-updates-SNAPSHOT.klib",
          "size": 14287,
          "sha512": "ab1f7bffd3643ae76b1e4eade7d42247ce5d7243a533bc54ed18f5a21f38702e91d66fa5dc27c4e46e6d31c6ad5068c2feeab8d611182f34164286f999d9d251",
          "sha256": "a58f9d230b43d4b6c75d095f787659ab28d594ecc434b9304ce779ea0b721def",
          "sha1": "81593c30d9e1a0168528ab2eed7e2088b2d9e713",
          "md5": "245fe6389550cf387a1522770d007583"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-e65a2ff-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b47319b26683c13634ae336a71cb4159e4bca6fa3016c60ca6aed6009eec544b77c8a3b5093a9016e868096c54684111599de96296bb84045ee762b1a09b2203",
          "sha256": "844b3fed5c8a0402d3b1c1da786d8ac473cf90bd06a091242a424c96e8d85b75",
          "sha1": "661b01a907cc3a7dc68bf3d4cb21bcbc18fdc7bd",
          "md5": "7f1a74c4856272f2350cf4dcbb1859ac"
        }
      ]
    }
  ]
}
