{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f8d6e50-bump-workflows-SNAPSHOT/test-utils-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosarm64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 7996,
          "sha512": "8fa29f0999a367ed4df6615ae31701f92d09c21ea4c17958558ff4dc935c0ec5abdbca611f1309f5e4f46dfd35e721e62e943e95a8d1f4b5b676bc85b1f4577c",
          "sha256": "cdc8c0d961a2d6e556d1eacc09f17946eafa18270e396572b12384959400939d",
          "sha1": "83525002d754f49c22ffc0d89339cbac8e3233f0",
          "md5": "cd8ffed8b46e43d23334cc62562b6bc9"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-watchosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bb0493242741e7ae6a1f4f655c07296a58c70e085d6ea4738cd71f95eaaf34a354db4202697dfdb7df9da883c2856e442bc625501049a259da9b9a2eba3e8b34",
          "sha256": "49e3f31224bdc234b43225f247e98edeaddfa1aa9eff0918e8abb93ca5391ffe",
          "sha1": "38ad501a39ac84b6f8fcdaae8201b8d22fd9e15b",
          "md5": "3f5d90a4bb400e9bb72dbf38cc675925"
        }
      ]
    }
  ]
}
