{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-0.1.0.jar",
          "url": "antibytes-configuration-0.1.0.jar",
          "size": 59750,
          "sha512": "26a5b4c88440356883881a1586a4d0ebf291e909fe37b125888bb25c1e8d91507a1631d479a06d2f6f096a451aa46718c2b4d14a8dba6b1b3525bff1008cf8ed",
          "sha256": "d18bdffa4dbddb5c69061df55c75c09dd8d413410fa89c94c8b1986947c9b3e9",
          "sha1": "455558979e9ea7d8d745b20a4354b096bf349513",
          "md5": "93180fe55edc35c8f9877268da7eedb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9bbf153"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-0.1.0.jar",
          "url": "antibytes-configuration-0.1.0.jar",
          "size": 59750,
          "sha512": "26a5b4c88440356883881a1586a4d0ebf291e909fe37b125888bb25c1e8d91507a1631d479a06d2f6f096a451aa46718c2b4d14a8dba6b1b3525bff1008cf8ed",
          "sha256": "d18bdffa4dbddb5c69061df55c75c09dd8d413410fa89c94c8b1986947c9b3e9",
          "sha1": "455558979e9ea7d8d745b20a4354b096bf349513",
          "md5": "93180fe55edc35c8f9877268da7eedb0"
        }
      ]
    }
  ]
}
