{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/65fa311-bump-gradle-SNAPSHOT/test-utils-fixture-65fa311-bump-gradle-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "65fa311-bump-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-65fa311-bump-gradle-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-65fa311-bump-gradle-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "26a4fa87635b385459f026352a731349713ecad288ad9eab9bf410a58ed08f4b9689f4646816eee4cd7b6616cd04710d64c35bbcc7e46d7db6260e731031374e",
          "sha256": "4bf119315b36092c53bff563ac9830a7aa200072e3617d740f075bbb757cf519",
          "sha1": "0e168821950dd17e04fc8d87e51d245d922c19f4",
          "md5": "eed89bab4f70f1f4eb8fa67938c1684b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-65fa311-bump-gradle-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-65fa311-bump-gradle-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "26a4fa87635b385459f026352a731349713ecad288ad9eab9bf410a58ed08f4b9689f4646816eee4cd7b6616cd04710d64c35bbcc7e46d7db6260e731031374e",
          "sha256": "4bf119315b36092c53bff563ac9830a7aa200072e3617d740f075bbb757cf519",
          "sha1": "0e168821950dd17e04fc8d87e51d245d922c19f4",
          "md5": "eed89bab4f70f1f4eb8fa67938c1684b"
        }
      ]
    }
  ]
}
