{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "bff1152-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata-bff1152-bump-antibytes-SNAPSHOT-all.jar",
          "url": "test-utils-coroutine-bff1152-bump-antibytes-SNAPSHOT-all.jar",
          "size": 5087,
          "sha512": "5f80420493b9496e1aa464bb24dcf4b890f431412ea3eae526a5b9feb525cd0c82f48b2e67f32d3f5d416341d3ee881bbe0ab3bcabb84fbfb2864171e2534b36",
          "sha256": "56ad981e7a2645741ca01aa5dbfa4d01e5699629baeb3fc338e4f8af786122b1",
          "sha1": "d6c2cd23e34555965160fdee2d03e1766f691418",
          "md5": "22116eb95a0014c7ff12f1091bacbb92"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-bff1152-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-coroutine-bff1152-bump-antibytes-SNAPSHOT.jar",
          "size": 3018,
          "sha512": "1e3b637cfffc6888702a2abb635df4cfc1a61484f1122c53ba456c629263cf1b586488ce4e61b1e9d241080cd758202846ca91e674144a0dd994b880bb3e4651",
          "sha256": "b5dc320965896cafddd1618377c274c08e9d69cb8dea3e71b02031fae137cea1",
          "sha1": "1a5569c85ecc7c7269dd70aed557a8eacc5ca2cc",
          "md5": "2bfb6cda43ee9c99376d72c3b09105ac"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-android-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-android-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-js-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-js-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-jvm-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-jvm-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/bff1152-bump-antibytes-SNAPSHOT/test-utils-coroutine-linuxx64-bff1152-bump-antibytes-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "bff1152-bump-antibytes-SNAPSHOT"
      }
    }
  ]
}
