{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/834cb6f-bump-updates-SNAPSHOT/test-utils-ktor-834cb6f-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "834cb6f-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "8f3f031750cdf8d876cb56dfe34c89d00b86530c4ac364baef489ef1ebaaa909a5e360bce9182268a23d4d613b68807beb80571b6ec4b868658c260fddd83d6d",
          "sha256": "fc1680793bf97e68ce40580217595ad862ab64195d6fba790c168cfb51fe6ba2",
          "sha1": "64cf7f05e4083afddf5b6831ab56618df4a4fce0",
          "md5": "777458e0782aaacc1f87a7f21dc88977"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "8f3f031750cdf8d876cb56dfe34c89d00b86530c4ac364baef489ef1ebaaa909a5e360bce9182268a23d4d613b68807beb80571b6ec4b868658c260fddd83d6d",
          "sha256": "fc1680793bf97e68ce40580217595ad862ab64195d6fba790c168cfb51fe6ba2",
          "sha1": "64cf7f05e4083afddf5b6831ab56618df4a4fce0",
          "md5": "777458e0782aaacc1f87a7f21dc88977"
        }
      ]
    }
  ]
}
