{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/3d31034-change-settings-SNAPSHOT/test-utils-annotations-junit5-3d31034-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "3d31034-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosx64-3d31034-change-settings-SNAPSHOT.klib",
          "size": 7032,
          "sha512": "9dd0601834b08678789019a64ee926de7304a3d9d65f4c7a4d2f3a5685f479e843c284e57b8f0e05292678f2eab6a8d9e246e2dd4dc012b9b24408b25f19e584",
          "sha256": "84cc965a8a9abd7548d780843d87b9c3287fc38b4328d2e2f32762eff2805f16",
          "sha1": "7f4df3c700d46b9ca39d41ac50d387e31387c948",
          "md5": "858fedcbae3c0eb53c407f60ed4c5cda"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosx64-3d31034-change-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosx64-3d31034-change-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9771d3d1ddb3356930cc6e47a26b631a581fa6210459561becd0dcae4b832ceb216c7f1d18927378d357e50225d68ecf09207d585abd92c64c345df5a0da92b7",
          "sha256": "00d84d3beb597491def650356c5ad90c1b304516aaf0a3034857437a49382784",
          "sha1": "81b960fdb6dd1e77a0b1a499af1bfeae58b9bad6",
          "md5": "cac9ef77eb500de0a09da5b021e84930"
        }
      ]
    }
  ]
}
