{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/15fe97e-add-mockery-SNAPSHOT/kmock-15fe97e-add-mockery-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "15fe97e-add-mockery-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "753d329-add-ios-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-15fe97e-add-mockery-SNAPSHOT.klib",
          "size": 55795,
          "sha512": "828146a4bc7ffb92d53db4ea0fc72389c8a64b8dcd566dfb01856cba378c8b685a7ec63ccf3199ea90e0523bd9d4c2732327b39e8f700f5216b02b57b3617e59",
          "sha256": "6edf17b1975197e5caf5d0b312945047796fe72458eece45f970019bcff2fb01",
          "sha1": "2a20fc72b322429dc6a3929a0b93b1074069249a",
          "md5": "0735fe04a9ffaa1ca7c1950223087257"
        }
      ]
    }
  ]
}
