{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT.jar",
          "size": 391222,
          "sha512": "fa32b39fe84fbee4c60258d92f63d3b01486b37bb06267ed32765f897444d9f84e0d22b26ee626f8298c1fb6a4f520708c61c7fece46f6549b279e4f488910fd",
          "sha256": "190138c0eaec1100c91a960bf65383a6e8bf9f04993f9354f0f03c4ab29b5f8e",
          "sha1": "7f0598f7d7f403d965510a893c71b5ff5f67fe84",
          "md5": "b44b8fb12c4a8092c781ef78aaf4d42e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.0-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT.jar",
          "size": 391222,
          "sha512": "fa32b39fe84fbee4c60258d92f63d3b01486b37bb06267ed32765f897444d9f84e0d22b26ee626f8298c1fb6a4f520708c61c7fece46f6549b279e4f488910fd",
          "sha256": "190138c0eaec1100c91a960bf65383a6e8bf9f04993f9354f0f03c4ab29b5f8e",
          "sha1": "7f0598f7d7f403d965510a893c71b5ff5f67fe84",
          "md5": "b44b8fb12c4a8092c781ef78aaf4d42e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "71f7d3fb511af90e88210b3d19fb3c0660987eddadd998312ed6e5b666a2a84983cc0fd84930b9142281a418c50d6b59e97873952778f68ba693812eaa303fec",
          "sha256": "c20c50362bbb3681c2c3e90a6f36916a1a783c62554661100ad35d63832a10aa",
          "sha1": "13307268940ec0daac0bae5f3ee344e04c296429",
          "md5": "5ceb4353ef171916d67ceebd36995fc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc02-fix-non-exiting-test-task-chaining-SNAPSHOT-sources.jar",
          "size": 81705,
          "sha512": "250f8654a91bf2b0b1af6aaaee20226e6aaa8fce986b0441e76ade315ff990952ad8d5715c0b9835b91947276ca6919491d73fee5049d5bbbaafb3b3488473e6",
          "sha256": "1d9f2666d71efe6fce94d4cacbf248fbd1293c9d514f2f25899393816590f83f",
          "sha1": "cf8952c54b42975e471d0eb2cee20cf614f735c9",
          "md5": "d83163e1c9724f607856dfe45d7618d8"
        }
      ]
    }
  ]
}
