{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/43575a8-add-iossimlator-SNAPSHOT/test-utils-ktor-43575a8-add-iossimlator-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "43575a8-add-iossimlator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "98b55597fd5874eed61689fef1728ec5f01d6c1549da376f30bc1324a8d307d2debfe591a8604931057a123d7f875ba95c5fd205946bb1dbf2d3c98efb02a665",
          "sha256": "7d422298f10b35fa4518fba49db2c918d04c9698781b3e8bb7b8fbd1b92b3ea7",
          "sha1": "9913aeb0d6701c849ad3b46a77a3256384c20304",
          "md5": "dcb83a6b0b753cffe45ac7fa5d5098b9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "98b55597fd5874eed61689fef1728ec5f01d6c1549da376f30bc1324a8d307d2debfe591a8604931057a123d7f875ba95c5fd205946bb1dbf2d3c98efb02a665",
          "sha256": "7d422298f10b35fa4518fba49db2c918d04c9698781b3e8bb7b8fbd1b92b3ea7",
          "sha1": "9913aeb0d6701c849ad3b46a77a3256384c20304",
          "md5": "dcb83a6b0b753cffe45ac7fa5d5098b9"
        }
      ]
    }
  ]
}
