{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/ebcd7e9-bump-antibytes-SNAPSHOT/test-utils-annotations-ebcd7e9-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "ebcd7e9-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "f0658ca855257a521e8bd6f94fe8af21390bd1d1ad5c83cbc15d46be56b41ed4f0752602060082aae931c2c094d9590a2630643b552ed7162fe2bcbcdc120bf3",
          "sha256": "12a4b85be8eea706f7fce8972b85b2d8425d9ad726a30614d15cdb85ea209364",
          "sha1": "182e91b4f544a52320f84dd740298c72b112373f",
          "md5": "d5e9a5c9a9890eb18e3782278989a16c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "f0658ca855257a521e8bd6f94fe8af21390bd1d1ad5c83cbc15d46be56b41ed4f0752602060082aae931c2c094d9590a2630643b552ed7162fe2bcbcdc120bf3",
          "sha256": "12a4b85be8eea706f7fce8972b85b2d8425d9ad726a30614d15cdb85ea209364",
          "sha1": "182e91b4f544a52320f84dd740298c72b112373f",
          "md5": "d5e9a5c9a9890eb18e3782278989a16c"
        }
      ]
    }
  ]
}
