{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "35c3f0e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-35c3f0e.jar",
          "url": "antibytes-grammar-tools-35c3f0e.jar",
          "size": 41868,
          "sha512": "60d4c2bf4759106ecfd7dfeef08cb2bdbc3ba36cb11e53efe85b098b3457acc931402e4aab47d02df74477d94571a6f17102770e4df7dc778e74f786015b6f2d",
          "sha256": "b4001205ed394e2e07fe7d3aba77f08cd8adb05798750d82d6091c173c78c4d8",
          "sha1": "4a43cbf4d0b808d41235f1363871c4d2150e83c1",
          "md5": "5ed9029ae74fd0aae9ca40961fb5c4eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-35c3f0e.jar",
          "url": "antibytes-grammar-tools-35c3f0e.jar",
          "size": 41868,
          "sha512": "60d4c2bf4759106ecfd7dfeef08cb2bdbc3ba36cb11e53efe85b098b3457acc931402e4aab47d02df74477d94571a6f17102770e4df7dc778e74f786015b6f2d",
          "sha256": "b4001205ed394e2e07fe7d3aba77f08cd8adb05798750d82d6091c173c78c4d8",
          "sha1": "4a43cbf4d0b808d41235f1363871c4d2150e83c1",
          "md5": "5ed9029ae74fd0aae9ca40961fb5c4eb"
        }
      ]
    }
  ]
}
