{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-filter-array-range-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.2.0-add-filter-array-range-SNAPSHOT-all.jar",
          "url": "core-0.2.0-add-filter-array-range-SNAPSHOT-all.jar",
          "size": 18930,
          "sha512": "76609b9f46db7510d98532394ea434d91c3388d13dbd397158210eb51d2a7ef24d0d1c9511d10771373f7d5051b7ebb5ae205f12ab3c4cd62839a88296f0cdc7",
          "sha256": "73c1b42c8fa844fc38291ea4fc87293a53e4231d8253fab0a3b0b88a6049ded3",
          "sha1": "cff46ada8e3b60f26813f58809dcd57f97712715",
          "md5": "4a794db494636ac6ff55b35dc4ee2945"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-0.2.0-add-filter-array-range-SNAPSHOT.jar",
          "url": "core-0.2.0-add-filter-array-range-SNAPSHOT.jar",
          "size": 32742,
          "sha512": "6698793e65e6039b4b345041c8c39068ef8ad84812c0875e9eeebc48b1856fc30a761789bdf5cd61c3b84c59cbda96de41bf46ac57b1054a0e8954290fc92532",
          "sha256": "e02f38fb38f8d9b9146faadbb04e93c8b2f87303ea8116b6638af441411ef6d7",
          "sha1": "e15052c5f83a1ee76bec02e54c2b658582ff1f24",
          "md5": "41bf1581696e940d1eaf463498225229"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.2.0-add-filter-array-range-SNAPSHOT/core-android-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.2.0-add-filter-array-range-SNAPSHOT/core-android-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.2.0-add-filter-array-range-SNAPSHOT/core-iosarm64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.2.0-add-filter-array-range-SNAPSHOT/core-iosarm64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.2.0-add-filter-array-range-SNAPSHOT/core-iossimulatorarm64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.2.0-add-filter-array-range-SNAPSHOT/core-iossimulatorarm64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.2.0-add-filter-array-range-SNAPSHOT/core-iosx64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.2.0-add-filter-array-range-SNAPSHOT/core-iosx64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.2.0-add-filter-array-range-SNAPSHOT/core-js-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.2.0-add-filter-array-range-SNAPSHOT/core-js-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.2.0-add-filter-array-range-SNAPSHOT/core-jvm-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.2.0-add-filter-array-range-SNAPSHOT/core-jvm-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.2.0-add-filter-array-range-SNAPSHOT/core-linuxx64-0.2.0-add-filter-array-range-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "0.2.0-add-filter-array-range-SNAPSHOT"
      }
    }
  ]
}
