{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-remove-android-studio-workaround-SNAPSHOT/core-0.4.0-remove-android-studio-workaround-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-remove-android-studio-workaround-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.4.0-remove-android-studio-workaround-SNAPSHOT.jar",
          "url": "core-jvm-0.4.0-remove-android-studio-workaround-SNAPSHOT.jar",
          "size": 273618,
          "sha512": "da0ebc0576850d622d4ea3770119ff9f1952a78e7a9051d03d576818a581d2e77b2eac0b19dfe0e713d83ef828cb3b6da79b5eabed5f324f107b8515ee1b93ab",
          "sha256": "aa8e3be7210e9b4ce357c88db32a02eff785f0195e24b5244e2041e2178a93e9",
          "sha1": "9e5c01d18a6cd4024214a8873e6e2fbefa924b56",
          "md5": "239187d96251daf212158f8d67951d31"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.4.0-remove-android-studio-workaround-SNAPSHOT.jar",
          "url": "core-jvm-0.4.0-remove-android-studio-workaround-SNAPSHOT.jar",
          "size": 273618,
          "sha512": "da0ebc0576850d622d4ea3770119ff9f1952a78e7a9051d03d576818a581d2e77b2eac0b19dfe0e713d83ef828cb3b6da79b5eabed5f324f107b8515ee1b93ab",
          "sha256": "aa8e3be7210e9b4ce357c88db32a02eff785f0195e24b5244e2041e2178a93e9",
          "sha1": "9e5c01d18a6cd4024214a8873e6e2fbefa924b56",
          "md5": "239187d96251daf212158f8d67951d31"
        }
      ]
    }
  ]
}
