{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/af57116-add-unit-and-any-fixture-SNAPSHOT/test-utils-fixture-af57116-add-unit-and-any-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "af57116-add-unit-and-any-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js.klib",
          "url": "test-utils-fixture-js-af57116-add-unit-and-any-fixture-SNAPSHOT.klib",
          "size": 35971,
          "sha512": "0cc3c2b4b5abdc1ffee847f11c92ce9f8e30c9b764171e19adbe13c4a47688d12f004e199f4c75c5d74b41d1d628bd3bf6001d493efa65fec52cb3c2091495c6",
          "sha256": "3be906317ad963bbb99510d2a7927139a46420c7224a6823647647275f686498",
          "sha1": "a8884399fd79ff0bc83cfcb4d34291ce780f03a4",
          "md5": "cb00782f4cce0ecf0702d97d9058986e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js.klib",
          "url": "test-utils-fixture-js-af57116-add-unit-and-any-fixture-SNAPSHOT.klib",
          "size": 35971,
          "sha512": "0cc3c2b4b5abdc1ffee847f11c92ce9f8e30c9b764171e19adbe13c4a47688d12f004e199f4c75c5d74b41d1d628bd3bf6001d493efa65fec52cb3c2091495c6",
          "sha256": "3be906317ad963bbb99510d2a7927139a46420c7224a6823647647275f686498",
          "sha1": "a8884399fd79ff0bc83cfcb4d34291ce780f03a4",
          "md5": "cb00782f4cce0ecf0702d97d9058986e"
        }
      ]
    }
  ]
}
