{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "696f60c-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-696f60c-bump-updates-SNAPSHOT.jar",
          "size": 26844,
          "sha512": "d64731dba924772ad001099e9f2a8e9d1e4ab749e50d861cc95a6d9e84f5914235a944668ddec0acb320587c79cc286fa022c2237437937fda8fe41e447bbcde",
          "sha256": "9e7aa7b7e9e7542567e7f8d72f5b2c9c9e5c8f16e6ca71e6553c790f60a235ff",
          "sha1": "3be7a28447fafd2d634421f3ccbeb7082aafc757",
          "md5": "583b49a9de9faf954f466040bee42671"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/696f60c-bump-updates-SNAPSHOT/banana-i18n-android-696f60c-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "696f60c-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/696f60c-bump-updates-SNAPSHOT/banana-i18n-android-696f60c-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "696f60c-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/696f60c-bump-updates-SNAPSHOT/banana-i18n-jvm-696f60c-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "696f60c-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/696f60c-bump-updates-SNAPSHOT/banana-i18n-jvm-696f60c-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "696f60c-bump-updates-SNAPSHOT"
      }
    }
  ]
}
