{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "93b8a67-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "93b8a67-change-node-dependencies"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-93b8a67-change-node-dependencies.jar",
          "url": "antibytes-dependency-settings-93b8a67-change-node-dependencies.jar",
          "size": 11347,
          "sha512": "73ce30928f580ec7123530be8bb3728fe1163a48489ef7889c6b6ed85117a83e70fede5349dfffd67f828b27abd1ded2e6bcf30bc98921bc6cdc78ce0052cd76",
          "sha256": "d5fb246daf9a7b9631d8a78278197bf0a48f2cd5e420367421c6e484e3d55764",
          "sha1": "e73d4cbd713e4895f3322c8807f5582f34cef0a2",
          "md5": "643e73f6d771b51117c4c299982bdcd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "93b8a67-change-node-dependencies"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-93b8a67-change-node-dependencies.jar",
          "url": "antibytes-dependency-settings-93b8a67-change-node-dependencies.jar",
          "size": 11347,
          "sha512": "73ce30928f580ec7123530be8bb3728fe1163a48489ef7889c6b6ed85117a83e70fede5349dfffd67f828b27abd1ded2e6bcf30bc98921bc6cdc78ce0052cd76",
          "sha256": "d5fb246daf9a7b9631d8a78278197bf0a48f2cd5e420367421c6e484e3d55764",
          "sha1": "e73d4cbd713e4895f3322c8807f5582f34cef0a2",
          "md5": "643e73f6d771b51117c4c299982bdcd7"
        }
      ]
    }
  ]
}
