{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "856c77e-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-metadata-856c77e-bump-updates-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-856c77e-bump-updates-SNAPSHOT-all.jar",
          "size": 10363,
          "sha512": "51f50e530af5f9809d525a97ff700719ab12d01d689af0ebce523623e4e0c9b4e6ae5210cfa86d2fae1913d5b24993e3fb91908759b0d3003888d8599a36e77b",
          "sha256": "8efb1e2dd6dc999d85df975353d8bf4f792a35d40936bf2a89508142128fc2f4",
          "sha1": "574fcb2d814186dde2cb04e58135dbf06dac1af9",
          "md5": "c4967fa924001aa7ea42ff530216afc1"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-856c77e-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-856c77e-bump-updates-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "6824c47924f70873b5002d82d4b2dc82c1094c3de36983d929ae150785619260578497a9f2cdb4fe7a14d2772595f3cada10171afdc50a81c121e4a179622630",
          "sha256": "e231a437168bfd23b4dec8529aae95838c3f64cafe76ccbf31bb507ca296bd12",
          "sha1": "59f718e75e5c78188e4d1fb1f1ca5c1db89ca71e",
          "md5": "3e423011887774e91ac71ba76380f396"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-android-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-android-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-iosarm64-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-iosarm64-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-iosx64-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-iosx64-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-jvm-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-jvm-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-linuxx64-856c77e-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "856c77e-bump-updates-SNAPSHOT"
      }
    }
  ]
}
