{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6625865384e88ed8d24a8979e20efff076cd81f3caeaf0ee48f4ff5e4c14a3ed552ac3f1dfb8fa6f76f5db4ce8b581fedcdb9397e1e3de4c1d716bfc863ed88a",
          "sha256": "181a8e345eea8ab892fcf200da8178858375c986ec12839a796ed6afd01b660c",
          "sha1": "1439197197d899aae457ddb7e22cf2722fcc7958",
          "md5": "ee548eaadebbfa11e4797d2aff67659f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6625865384e88ed8d24a8979e20efff076cd81f3caeaf0ee48f4ff5e4c14a3ed552ac3f1dfb8fa6f76f5db4ce8b581fedcdb9397e1e3de4c1d716bfc863ed88a",
          "sha256": "181a8e345eea8ab892fcf200da8178858375c986ec12839a796ed6afd01b660c",
          "sha1": "1439197197d899aae457ddb7e22cf2722fcc7958",
          "md5": "ee548eaadebbfa11e4797d2aff67659f"
        }
      ]
    }
  ]
}
