{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-SNAPSHOT/ktx-datetime-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "977485b2fc37139a041c919cc837aa089a3ec868e54acaf9631b45cf63209acebad498adac47c1f2c271fa06ba65036a46becb2c114faa79d6960248f75dd008",
          "sha256": "396443fa79776d069d4602047fa93c34353f08000d1e7e57af1b225b96d3285b",
          "sha1": "f2bcc853fc4fe80f66f4c5b7975ad268eeafd61b",
          "md5": "1c5fd411b00620593d4aecfb155371bd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "977485b2fc37139a041c919cc837aa089a3ec868e54acaf9631b45cf63209acebad498adac47c1f2c271fa06ba65036a46becb2c114faa79d6960248f75dd008",
          "sha256": "396443fa79776d069d4602047fa93c34353f08000d1e7e57af1b225b96d3285b",
          "sha1": "f2bcc853fc4fe80f66f4c5b7975ad268eeafd61b",
          "md5": "1c5fd411b00620593d4aecfb155371bd"
        }
      ]
    }
  ]
}
