{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "dcdfb75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-dcdfb75.jar",
          "url": "antibytes-dependency-catalog-dcdfb75.jar",
          "size": 261,
          "sha512": "d5464e951000c747130213ef7822fc3fdaec446279d4a0e896edb5a99f60227ef47fa24d73c80392a960d6027e4ae2160016924138eb39397bb9a0aee732e3a5",
          "sha256": "8def6b2c1e3ff95c30eea4e1a5799d89cf99bc68ab8cf4f00bc7020406609c6c",
          "sha1": "c76792155373756308745be2950bf1e96ee052fe",
          "md5": "3e307eee522f408f36d1932937c15da8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-dcdfb75.jar",
          "url": "antibytes-dependency-catalog-dcdfb75.jar",
          "size": 261,
          "sha512": "d5464e951000c747130213ef7822fc3fdaec446279d4a0e896edb5a99f60227ef47fa24d73c80392a960d6027e4ae2160016924138eb39397bb9a0aee732e3a5",
          "sha256": "8def6b2c1e3ff95c30eea4e1a5799d89cf99bc68ab8cf4f00bc7020406609c6c",
          "sha1": "c76792155373756308745be2950bf1e96ee052fe",
          "md5": "3e307eee522f408f36d1932937c15da8"
        }
      ]
    }
  ]
}
