{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/a6b7ead-change-resource-loader-SNAPSHOT/test-utils-a6b7ead-change-resource-loader-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "a6b7ead-change-resource-loader-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-a6b7ead-change-resource-loader-SNAPSHOT.klib",
          "size": 7962,
          "sha512": "4a9c4a745a177b65290a8b6e1f4e45afc70018250e9ae064673b79e21097a78c70fdbb53a13b425478520c3b96d781a60435d7f3e70860d6cf3e70419e57b82c",
          "sha256": "c231e0f0fe7d17b3c8feebc5684c52f4f2e23e8c895ea9c6ab9bb1bafb5817ae",
          "sha1": "bd56568f4ff847bf496cb11403f05f4758bc54ac",
          "md5": "21bf8685971662cd968ba414c97652e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-a6b7ead-change-resource-loader-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-a6b7ead-change-resource-loader-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ba92751b57e6e4cdfcc0b21e280f5defc345c74312c7c6f09e79f33c02832faed65d1b1d8a3b55198e5b81970e6494779dc5bcd778b48e5842f4afbb8bad9d32",
          "sha256": "596ebaf4787452d8e19225253a77ab4407882eed18a4dd5b17dd59b8496f3980",
          "sha1": "cb45c43eadd46c920a0808fa5871f5fb2dbace5e",
          "md5": "17987dc608926eb8237b76a40ee8e4bc"
        }
      ]
    }
  ]
}
