{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-change-android-min-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-android-min-sdk-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-android-min-sdk-SNAPSHOT.jar",
          "size": 173194,
          "sha512": "12a2eff2be697c87ec2011981b01b2245b2a6aa259060e0f460d5175fd3cf94f178af23e4f49eaad7486a881a4f8b83ec13f0aefc92ce80e2621b71253b7ab3d",
          "sha256": "be35e5a175cd35af2dd3657da79c1b4e6bbfd0b9a8b3e25ccd7388920075c9b4",
          "sha1": "60170f389ad14e0ed5561a8b067fed4825da6507",
          "md5": "54044bf3decd798dd7d228216b59784f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-change-android-min-sdk-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-android-min-sdk-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-android-min-sdk-SNAPSHOT.jar",
          "size": 173194,
          "sha512": "12a2eff2be697c87ec2011981b01b2245b2a6aa259060e0f460d5175fd3cf94f178af23e4f49eaad7486a881a4f8b83ec13f0aefc92ce80e2621b71253b7ab3d",
          "sha256": "be35e5a175cd35af2dd3657da79c1b4e6bbfd0b9a8b3e25ccd7388920075c9b4",
          "sha1": "60170f389ad14e0ed5561a8b067fed4825da6507",
          "md5": "54044bf3decd798dd7d228216b59784f"
        }
      ]
    }
  ]
}
