{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "f23ac2f-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-f23ac2f-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-gradle-f23ac2f-fix-single-sources-SNAPSHOT.jar",
          "size": 32343,
          "sha512": "1566c5d8acc75017b07a9a542133a1467f04635740fca1342104c912d429556fe63a325a78f89f91142df0aec9f2fcbcfb9c2c048e303fe511d1cddc70748f7e",
          "sha256": "7200b9a379ec6117862dd171b315edc647e3bccd3747f727c3752ea09b4dc371",
          "sha1": "78b01367e1a365cc539aba5b074f1fbae47f08ce",
          "md5": "ada9d8b0b26fd84e60cc3a6dd9060f76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bb22160"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-f23ac2f-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-gradle-f23ac2f-fix-single-sources-SNAPSHOT.jar",
          "size": 32343,
          "sha512": "1566c5d8acc75017b07a9a542133a1467f04635740fca1342104c912d429556fe63a325a78f89f91142df0aec9f2fcbcfb9c2c048e303fe511d1cddc70748f7e",
          "sha256": "7200b9a379ec6117862dd171b315edc647e3bccd3747f727c3752ea09b4dc371",
          "sha1": "78b01367e1a365cc539aba5b074f1fbae47f08ce",
          "md5": "ada9d8b0b26fd84e60cc3a6dd9060f76"
        }
      ]
    }
  ]
}
