{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/f8d6e50-bump-workflows-SNAPSHOT/test-utils-resourceloader-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 12849,
          "sha512": "b05d419daa737638e1a68389db45e60bea41be3040a340ff709c504009a3e5ec8c8be71a2b276b3138d910f6f6f7f282daed519f0d7ccd55e01886495d2eb310",
          "sha256": "3c611a4912536b6a5fd7316d6a18b4fd7713a78c6c2c4cebe3d2a73d8d0d005f",
          "sha1": "fc5acdc5e365bcf321e84682b21068d4a0b8cd53",
          "md5": "c294d934ca5be70f140b4cd78fcc592f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8a8134902df18a01a3d442882a04d4e377a65ca5dd1ece4b3af08143feeed736475029e912fd6ce54856b69269551b5552f23e03c411faf6d86519fa37b740cb",
          "sha256": "38b24f1a4346d7d1a49b53c1eb3767596edeafe81223bed28831e346d7657576",
          "sha1": "fcc025442e707ae75c7afe8b7a1b28c2273a40c4",
          "md5": "57e452986871645a4a64d8a906fb2d43"
        }
      ]
    }
  ]
}
