{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-bump-updates-SNAPSHOT/core-0.1.0-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.1.0-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.1.0-bump-updates-SNAPSHOT.klib",
          "size": 50835,
          "sha512": "ffdb2ee5e3404d8333524a877033cfdba33931b6afc3d1f99ebfefeab22e5513f8b3512bc3340d11f6cba96119fa4d64c8e670a535ea893d48bb6e118882e51f",
          "sha256": "01024c899e0048adfc073b661158732ef5966110f63993f42e5223d43b6c30a2",
          "sha1": "c61487b949ec8bb745b4d71b1dc9cb2b6e772428",
          "md5": "5d69bd62741f2800cb1c095105b84245"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.1.0-bump-updates-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.1.0-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "588dda94e47a0a9561716e7e26a35712c814aa1392483b9791687e5a5b05c224bbfc241bd4fee82bf2810f437c4f5159262a5de8541eb008e5e0c6304a5a28ac",
          "sha256": "d18677e175b247de08b0ff23153762d80defac4457776183758f07493d3baf2e",
          "sha1": "834e78c4d856221c02d932e0c9c0bacf9894ce34",
          "md5": "95fb08f3c89648b3ef78cb5972a43bb6"
        }
      ]
    }
  ]
}
