{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit4-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-694b583-change-setup-SNAPSHOT.klib",
          "size": 11438,
          "sha512": "5700ba1a32678fc80c38f747337de30ce4835055c7169a46ec00940499756eae4190bdb9378de5deb02e77521a13a55900c2cdc615d1a53e28932fd92b9ffc70",
          "sha256": "c839fe2faf3ddf73845d5dcdff0c9c283a6e2bfc9cf05544ff8e35cbc1107a5f",
          "sha1": "1cecf9b278f26825878551578a6ce863a1497ab4",
          "md5": "5a4768817d18ac1138b6e5e9f61ba9cb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "afcb3d2b458a32d0e827a7ddf56e16fda3c5da27c22d2cb7a3c31654a5437ff433a6feb2939611afcdaee1d296fbcd96d701055393e1aa0fbd52c3c82e85bf20",
          "sha256": "dbbb299807bd840da9787c0d8648a543c7cf01df89824bdc3a5ba686fe9b20a1",
          "sha1": "c6acce49171bac61995cc2d53612222dde5ef2d8",
          "md5": "2fe78291ded7aa5fbe3910a63acffd02"
        }
      ]
    }
  ]
}
