{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/5d5a54a-change-settings-SNAPSHOT/test-utils-coroutine-5d5a54a-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "5d5a54a-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 10186,
          "sha512": "25edd4a3e048cee52d5759f409abb154cc93e52d05c1170649385f6a01237d7b2c9abd4562ad66081b3b756afbfc889469ffea3c94571c99f000dfcd8062c807",
          "sha256": "0ac9e8e8ecd9f2ff3334b4c4c8a91067627dbb10c60ec565a82aef0b8110f4b7",
          "sha1": "640bbf425f7b687028397f29ecdf8b9cbd77316e",
          "md5": "431e015cc33bb688c140ef79380ac55f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "url": "test-utils-coroutine-js-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 10186,
          "sha512": "25edd4a3e048cee52d5759f409abb154cc93e52d05c1170649385f6a01237d7b2c9abd4562ad66081b3b756afbfc889469ffea3c94571c99f000dfcd8062c807",
          "sha256": "0ac9e8e8ecd9f2ff3334b4c4c8a91067627dbb10c60ec565a82aef0b8110f4b7",
          "sha1": "640bbf425f7b687028397f29ecdf8b9cbd77316e",
          "md5": "431e015cc33bb688c140ef79380ac55f"
        }
      ]
    }
  ]
}
