{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit4-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 11449,
          "sha512": "30fe12f3fcb58af061a1a7c12052c83b3d482b516a724b30e968bde89483cd992ebec186c9de347012c4a17244d4a107a57c7d5b5d1ab2f75dfe63eda253f531",
          "sha256": "6f47b288262026fd1e541035f53831fde90cd0b1f33f9807576bae4ad4e8e733",
          "sha1": "8465619d9b978d601c52a26c003ca17bbbefea5f",
          "md5": "8661f556610006ea77f189ca46dbd25e"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-tvossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "96f956fdc1fafcc61e9af8572b671fa85f877ffe86a12058e18dbada57ef5f72be15e5d6d7499f0103f629a98364df2a2c7dba9250ea64ff549ba8162ff87a99",
          "sha256": "e565978cf462328ad0a02d6b10880bf9aa550c6b0ab4f85c820086152df567ef",
          "sha1": "be37c53def0096c35e5409a314b75ed9bea008a4",
          "md5": "35a9a442f7e31b342f55c4c0435d48fa"
        }
      ]
    }
  ]
}
