{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "7df38df-add-kapt",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-7df38df-add-kapt.jar",
          "url": "antibytes-grammar-tools-7df38df-add-kapt.jar",
          "size": 39394,
          "sha512": "c4fc7af39566ffd20b5aa9818420910ee3e95db0597815f51b7fd71c7adcdb7676772f53bc73054a890bc474e19a29787cc2c09919f5172b18786a062fa77f05",
          "sha256": "897d9515784803b5dba231def39d7f689d724159745da301bae4ad1558bb6717",
          "sha1": "858c86b8089813314ab0b9b0251da778eb33e0c7",
          "md5": "9df0d27d375310a5fe91cf9fd9ae94c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-7df38df-add-kapt.jar",
          "url": "antibytes-grammar-tools-7df38df-add-kapt.jar",
          "size": 39394,
          "sha512": "c4fc7af39566ffd20b5aa9818420910ee3e95db0597815f51b7fd71c7adcdb7676772f53bc73054a890bc474e19a29787cc2c09919f5172b18786a062fa77f05",
          "sha256": "897d9515784803b5dba231def39d7f689d724159745da301bae4ad1558bb6717",
          "sha1": "858c86b8089813314ab0b9b0251da778eb33e0c7",
          "md5": "9df0d27d375310a5fe91cf9fd9ae94c3"
        }
      ]
    }
  ]
}
