{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-numeric-api-char-SNAPSHOT/core-0.2.0-change-numeric-api-char-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-numeric-api-char-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.2.0-change-numeric-api-char-SNAPSHOT.klib",
          "size": 64938,
          "sha512": "7cb1e3aa0985d8df313238d4649028ff413c0a2aa72370b6743a42754636fedbfc401debf6340ca881f48bcdab54799c356810f8045b8a9505f5331faffd6413",
          "sha256": "30f03429c17dc48a46d5106c2fb924b6c97ebee622ced3b7842d48a513e1e60f",
          "sha1": "515c7d7b2082eb11b579909a062b24e14483809a",
          "md5": "a41768178bfed3937b94c705acc83c5f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.2.0-change-numeric-api-char-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.2.0-change-numeric-api-char-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "26a86096c9affb978edf97bc11f3a5d2dfb58a1b8b7731790b2c253adacf6ffcece3282959ec853753ce6cf08b6b8aa085d6a9a5ec55c04db3a8f53d1a81b6ea",
          "sha256": "b3f292033d43cea3455d33247b9222a303aa8c51e5fcd865075dbd3c5c9f7de4",
          "sha1": "6de5d4cc46c40816a3c6701dca7e7cc4de485ca8",
          "md5": "b562a1fb727e17e032aaf57063a26a04"
        }
      ]
    }
  ]
}
