{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/4ce71dc-add-selective-spies-SNAPSHOT/kmock-4ce71dc-add-selective-spies-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "4ce71dc-add-selective-spies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-4ce71dc-add-selective-spies-SNAPSHOT.jar",
          "url": "kmock-jvm-4ce71dc-add-selective-spies-SNAPSHOT.jar",
          "size": 264329,
          "sha512": "36afb094deb037aea6734d119e606487268b8594e55875a3241e892a16e38aff2ded56c48b2309f85d980c79df70e9dbb8c76d7c5d5a810fffa8730240bbf0c5",
          "sha256": "a0d35174effade22a82601d77f0ce97173c24eee2b2f8d5762dd5aa01cb5f963",
          "sha1": "fa9875aab6bd020f705274531f4a56c8d2d735f8",
          "md5": "64788274e4d634ae39d1d7bb405569d3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-4ce71dc-add-selective-spies-SNAPSHOT.jar",
          "url": "kmock-jvm-4ce71dc-add-selective-spies-SNAPSHOT.jar",
          "size": 264329,
          "sha512": "36afb094deb037aea6734d119e606487268b8594e55875a3241e892a16e38aff2ded56c48b2309f85d980c79df70e9dbb8c76d7c5d5a810fffa8730240bbf0c5",
          "sha256": "a0d35174effade22a82601d77f0ce97173c24eee2b2f8d5762dd5aa01cb5f963",
          "sha1": "fa9875aab6bd020f705274531f4a56c8d2d735f8",
          "md5": "64788274e4d634ae39d1d7bb405569d3"
        }
      ]
    }
  ]
}
