{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "c414c01-remove-classifier-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-c414c01-remove-classifier-SNAPSHOT.jar",
          "url": "antibytes-configuration-c414c01-remove-classifier-SNAPSHOT.jar",
          "size": 59750,
          "sha512": "6e3ee9ea2e5f59c503e153e274adaaac87729023a169fbbb103fdb337e6ab4605c2e6a1483130bfba08cd7ee73e57b6b6c5ebdd431e070adf58a8131272fd67a",
          "sha256": "a1855257a77bedef09fa9be37beaf7f0e9fe06a03299edbc7dab6faf15d4dff0",
          "sha1": "d925f5ccba8db056cecec43ed80ecbf3b64601e7",
          "md5": "6622860fd0f8b1133ebc8b0d6f54358b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c414c01-remove-classifier-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-c414c01-remove-classifier-SNAPSHOT.jar",
          "url": "antibytes-configuration-c414c01-remove-classifier-SNAPSHOT.jar",
          "size": 59750,
          "sha512": "6e3ee9ea2e5f59c503e153e274adaaac87729023a169fbbb103fdb337e6ab4605c2e6a1483130bfba08cd7ee73e57b6b6c5ebdd431e070adf58a8131272fd67a",
          "sha256": "a1855257a77bedef09fa9be37beaf7f0e9fe06a03299edbc7dab6faf15d4dff0",
          "sha1": "d925f5ccba8db056cecec43ed80ecbf3b64601e7",
          "md5": "6622860fd0f8b1133ebc8b0d6f54358b"
        }
      ]
    }
  ]
}
