{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "a037784-bump-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-a037784-bump-dependencies.jar",
          "url": "antibytes-quality-a037784-bump-dependencies.jar",
          "size": 64565,
          "sha512": "711d04b1a629873bf14a1a3d37e0d9e9c522dffcf106584e38fd0e7283d7d8025235a2a022d467902e1246f6422545a832240589514fbbdb464dce6ff2bf8f46",
          "sha256": "8d5af7eac56ccd8a8e49b1496a811ce7ccdbfb31ab1f2a6181bec2221ecab878",
          "sha1": "26b08761c64b8e076a24cb9bae82afe0e088e0a3",
          "md5": "6b7c641d72f2dd2c182dfd4d0629eccd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.22.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a037784-bump-dependencies"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "a037784-bump-dependencies"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-a037784-bump-dependencies.jar",
          "url": "antibytes-quality-a037784-bump-dependencies.jar",
          "size": 64565,
          "sha512": "711d04b1a629873bf14a1a3d37e0d9e9c522dffcf106584e38fd0e7283d7d8025235a2a022d467902e1246f6422545a832240589514fbbdb464dce6ff2bf8f46",
          "sha256": "8d5af7eac56ccd8a8e49b1496a811ce7ccdbfb31ab1f2a6181bec2221ecab878",
          "sha1": "26b08761c64b8e076a24cb9bae82afe0e088e0a3",
          "md5": "6b7c641d72f2dd2c182dfd4d0629eccd"
        }
      ]
    }
  ]
}
