{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c018d4a-change-setup-SNAPSHOT/test-utils-ktor-c018d4a-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c018d4a-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-c018d4a-change-setup-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-c018d4a-change-setup-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "941a93ab0bdf67b92cb4a2036f3bcb72761f6beabe3e1bd8e895e6b8a75ab5bd683f535f5dcf777d61c197d4a982d7553ac7942bbadcac96ce34cb46656ccf23",
          "sha256": "e163aaf5ed479fa950f5afe22da5dba3ead0dce1ad2bd9e4c1f31ba2532f3b42",
          "sha1": "b1d098f323c2b940c4bdf994ab1f9933818c6d8b",
          "md5": "a708e65b84ee667c1043c47d9e00393d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-c018d4a-change-setup-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-c018d4a-change-setup-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "941a93ab0bdf67b92cb4a2036f3bcb72761f6beabe3e1bd8e895e6b8a75ab5bd683f535f5dcf777d61c197d4a982d7553ac7942bbadcac96ce34cb46656ccf23",
          "sha256": "e163aaf5ed479fa950f5afe22da5dba3ead0dce1ad2bd9e4c1f31ba2532f3b42",
          "sha1": "b1d098f323c2b940c4bdf994ab1f9933818c6d8b",
          "md5": "a708e65b84ee667c1043c47d9e00393d"
        }
      ]
    }
  ]
}
