{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/205f7d8-fix-assertions-SNAPSHOT/test-utils-fixture-205f7d8-fix-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "205f7d8-fix-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "21c634ff3cd5b7f64389c0acae864f2187d9a82d2ce2bf244c235d5b2e91995e06aa9d07d169053c03d0c5f70d6394ec05b6ea0e02549bfa74c5c633852d5c35",
          "sha256": "6b6387b249bc51af7f79181a358bfe3bcedb6ac44a03b90109330e80f523a808",
          "sha1": "8927bc1fca81483dbba3152d734bab3e454f8514",
          "md5": "27dd536b00aac62573bb08086f7364a4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-205f7d8-fix-assertions-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "21c634ff3cd5b7f64389c0acae864f2187d9a82d2ce2bf244c235d5b2e91995e06aa9d07d169053c03d0c5f70d6394ec05b6ea0e02549bfa74c5c633852d5c35",
          "sha256": "6b6387b249bc51af7f79181a358bfe3bcedb6ac44a03b90109330e80f523a808",
          "sha1": "8927bc1fca81483dbba3152d734bab3e454f8514",
          "md5": "27dd536b00aac62573bb08086f7364a4"
        }
      ]
    }
  ]
}
