{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/59ae807-change-publishing-SNAPSHOT/fixture-59ae807-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "59ae807-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosarm64-59ae807-change-publishing-SNAPSHOT.klib",
          "size": 47162,
          "sha512": "73a561d7a54feded408e72a7f0c4631cff13579cfacf5b85cb296874461e830591cff6007f84901d2b2d6c6a29e7b35fa08143bf1501d4482ea8f4f523aa4ef8",
          "sha256": "466143d0eb193abcfac883309b5dc4de53d9dd88f9cf0d55ce48b211bc57c99e",
          "sha1": "3a41e6ef323b3a78e454d7da0ff9635979ade7ef",
          "md5": "e609bbc37ab05f1d4221b6dcc6342467"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosarm64-59ae807-change-publishing-SNAPSHOT-metadata.jar",
          "url": "fixture-iosarm64-59ae807-change-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d26791e35dbf4f780f34fa65970d15763a46452e3d0fedfe234e4481f9e10b975006d2b8abf20214fed9428c70c1611498fde5355580ee6eb0b8419c2030a407",
          "sha256": "2d292f6309347d4534e525c36025d7130e37cc933ec885eeb47ad8703899f684",
          "sha1": "a83418481cccb0b1da67d6415aaef83c112fcc87",
          "md5": "0c94c57da1b85de7e2b96b91e7c902e1"
        }
      ]
    }
  ]
}
