{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-kmock-annotation-multi-SNAPSHOT/kmock-0.1.1-add-kmock-annotation-multi-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-kmock-annotation-multi-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "size": 382957,
          "sha512": "50389930120c4730318db8f85874fce5c92910742c1e67b63e343438872d7de9015e34804cbbf183e6d41ad455c29d0ed5a80657dfd2b6dbd50d4bf6180aeccb",
          "sha256": "ef6bf99a63ebaacbd54469625fb8d14df51e55ae93ca04d4abc5f2ea66c3abfc",
          "sha1": "95da14f4e9d23347589ff16e6be1f81941961725",
          "md5": "47f80ba32a9af651474d1b042c6cfaed"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "size": 382957,
          "sha512": "50389930120c4730318db8f85874fce5c92910742c1e67b63e343438872d7de9015e34804cbbf183e6d41ad455c29d0ed5a80657dfd2b6dbd50d4bf6180aeccb",
          "sha256": "ef6bf99a63ebaacbd54469625fb8d14df51e55ae93ca04d4abc5f2ea66c3abfc",
          "sha1": "95da14f4e9d23347589ff16e6be1f81941961725",
          "md5": "47f80ba32a9af651474d1b042c6cfaed"
        }
      ]
    }
  ]
}
