{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "5aacabc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-5aacabc.jar",
          "url": "antibytes-dependency-5aacabc.jar",
          "size": 59502,
          "sha512": "76101ba77d9e885fadecb392ca667702383a559a2d355c0f20d04a8034cd825bc6f499754cb2e7e04b26a2685273f012d3c88a284e0ae1315442f7cafd5522d5",
          "sha256": "4ec07e6f82aadf73e213bb02e4aeb1498919bb07c4237a9d5d8b52dada51f973",
          "sha1": "457039a35068a6ba252cb016a218ea7228c4d6bf",
          "md5": "4c88f74fc32cf599123c900005682dad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.3"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5aacabc"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-5aacabc.jar",
          "url": "antibytes-dependency-5aacabc.jar",
          "size": 59502,
          "sha512": "76101ba77d9e885fadecb392ca667702383a559a2d355c0f20d04a8034cd825bc6f499754cb2e7e04b26a2685273f012d3c88a284e0ae1315442f7cafd5522d5",
          "sha256": "4ec07e6f82aadf73e213bb02e4aeb1498919bb07c4237a9d5d8b52dada51f973",
          "sha1": "457039a35068a6ba252cb016a218ea7228c4d6bf",
          "md5": "4c88f74fc32cf599123c900005682dad"
        }
      ]
    }
  ]
}
