{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "fc38960",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-fc38960.jar",
          "url": "antibytes-grammar-tools-fc38960.jar",
          "size": 39410,
          "sha512": "84b9d3dd4452bf9a87d5a33311f415b15f7f39e509a44f9e55a879ffe2e73534e0ca50b6c0a011f55d80b46a08ac8e852344343b840e2a510dc83f7aaeadc550",
          "sha256": "d4d4ce7f01cd977d2587d531c6451ae7a39d2fd0c3e7b0ba6253092936c29c09",
          "sha1": "88846636d05cb51b9edf9ad46000e6418b02717b",
          "md5": "5095a021d011aab8d2c9ba24310a238c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-fc38960.jar",
          "url": "antibytes-grammar-tools-fc38960.jar",
          "size": 39410,
          "sha512": "84b9d3dd4452bf9a87d5a33311f415b15f7f39e509a44f9e55a879ffe2e73534e0ca50b6c0a011f55d80b46a08ac8e852344343b840e2a510dc83f7aaeadc550",
          "sha256": "d4d4ce7f01cd977d2587d531c6451ae7a39d2fd0c3e7b0ba6253092936c29c09",
          "sha1": "88846636d05cb51b9edf9ad46000e6418b02717b",
          "md5": "5095a021d011aab8d2c9ba24310a238c"
        }
      ]
    }
  ]
}
