{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "5828445",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-5828445.jar",
          "url": "antibytes-publishing-5828445.jar",
          "size": 123912,
          "sha512": "500ec275455c7111abd14441f780d892e7d7afabd35920331d59b7d73ff6bba600376a0959d1cc553266811a90aeabbd5adba0a6b9223b5169cdfcb4cf25df6a",
          "sha256": "ceeca4b501f8e1c7b5cc78dc2a8e6d60d3ba9a10e2c80ed85d396b5ae852aa60",
          "sha1": "9848a213a1099b06098620ebe1f677f1d3d3b332",
          "md5": "980dc44079f6486a1243b106cf136584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.1.0.202203080745-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5828445"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-5828445.jar",
          "url": "antibytes-publishing-5828445.jar",
          "size": 123912,
          "sha512": "500ec275455c7111abd14441f780d892e7d7afabd35920331d59b7d73ff6bba600376a0959d1cc553266811a90aeabbd5adba0a6b9223b5169cdfcb4cf25df6a",
          "sha256": "ceeca4b501f8e1c7b5cc78dc2a8e6d60d3ba9a10e2c80ed85d396b5ae852aa60",
          "sha1": "9848a213a1099b06098620ebe1f677f1d3d3b332",
          "md5": "980dc44079f6486a1243b106cf136584"
        }
      ]
    }
  ]
}
