{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "aaeb97b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-aaeb97b.jar",
          "url": "antibytes-coverage-aaeb97b.jar",
          "size": 133706,
          "sha512": "8be5af18f50a683d839387441a7f52b47f258c3ec48bcce8383ae58371868648e8160c3f5f373fc74f8dbdf898952b45f8271a16279706fbb00c39cafcfc4545",
          "sha256": "47bc8c22accaca97e5e5183ff0020d90e03a0b267d7342ee1470eccd528c1cef",
          "sha1": "a4b025cb67d4ec741e764c3403332fde86cf1ebc",
          "md5": "be67f1798e82365a551f44c3fdf29cfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "aaeb97b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-aaeb97b.jar",
          "url": "antibytes-coverage-aaeb97b.jar",
          "size": 133706,
          "sha512": "8be5af18f50a683d839387441a7f52b47f258c3ec48bcce8383ae58371868648e8160c3f5f373fc74f8dbdf898952b45f8271a16279706fbb00c39cafcfc4545",
          "sha256": "47bc8c22accaca97e5e5183ff0020d90e03a0b267d7342ee1470eccd528c1cef",
          "sha1": "a4b025cb67d4ec741e764c3403332fde86cf1ebc",
          "md5": "be67f1798e82365a551f44c3fdf29cfb"
        }
      ]
    }
  ]
}
