{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "225ca48-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-dependency-bridge-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 38501,
          "sha512": "8df8996bdc33fe643a6e8e1f1f0d4faef9ea50cc0214016f7cc667a9745f6861ffe9532e25fc5faa4a34f4a80c003a8fddb07fb3cea192bf38151dd4ada9737d",
          "sha256": "f781ddf9fe70ba74e4197cfb4b543cd317e9cc36bcd0c48dd98c3775ab9afe2b",
          "sha1": "cca9bf064b0947daeb732983a7a59800277f4f43",
          "md5": "46a32d96459d199180f984dbee7662ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-dependency-bridge-225ca48-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 38501,
          "sha512": "8df8996bdc33fe643a6e8e1f1f0d4faef9ea50cc0214016f7cc667a9745f6861ffe9532e25fc5faa4a34f4a80c003a8fddb07fb3cea192bf38151dd4ada9737d",
          "sha256": "f781ddf9fe70ba74e4197cfb4b543cd317e9cc36bcd0c48dd98c3775ab9afe2b",
          "sha1": "cca9bf064b0947daeb732983a7a59800277f4f43",
          "md5": "46a32d96459d199180f984dbee7662ef"
        }
      ]
    }
  ]
}
