{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0ad3fd5-add-class-cracker-SNAPSHOT/kmock-0ad3fd5-add-class-cracker-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0ad3fd5-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0ad3fd5-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-0ad3fd5-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "9b04f784c09e41f58618d15988ad04d6d7389d17fbfe8f9aa6df7b487320ee683f0961916e11629df5342f3d7c216383996c5a797b0b1afca4e809379612ab80",
          "sha256": "b443380ca32aad6e78162c2b4130aea8b28b4d9938a8de3cf2dd9f376e716c95",
          "sha1": "f9797b1741e9df66a84fe8aad64316e2594b6ef5",
          "md5": "fb4e696ee099f65a9e7f9eb17907886a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0ad3fd5-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-0ad3fd5-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "9b04f784c09e41f58618d15988ad04d6d7389d17fbfe8f9aa6df7b487320ee683f0961916e11629df5342f3d7c216383996c5a797b0b1afca4e809379612ab80",
          "sha256": "b443380ca32aad6e78162c2b4130aea8b28b4d9938a8de3cf2dd9f376e716c95",
          "sha1": "f9797b1741e9df66a84fe8aad64316e2594b6ef5",
          "md5": "fb4e696ee099f65a9e7f9eb17907886a"
        }
      ]
    }
  ]
}
