{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "8feebc4-add-github-env-check",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-8feebc4-add-github-env-check.jar",
          "url": "antibytes-versioning-8feebc4-add-github-env-check.jar",
          "size": 21893,
          "sha512": "5e11c43a91d55dee2c021b0075943d71790ff649b07a53a20fcb9a64413ed6668f4d800800a516689b6b64e1691a4d845d341fd5ee3a9968dec7a5316f3e4f56",
          "sha256": "3a85e16b430f92c0a99fe0812974cf3513e3952d725b1bb657f2ca877edc020e",
          "sha1": "3b1025cbbb9610acf13a8fd42e74a19f4039e2ce",
          "md5": "122718e0fbc236cdc6bbf091c838fd73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-8feebc4-add-github-env-check.jar",
          "url": "antibytes-versioning-8feebc4-add-github-env-check.jar",
          "size": 21893,
          "sha512": "5e11c43a91d55dee2c021b0075943d71790ff649b07a53a20fcb9a64413ed6668f4d800800a516689b6b64e1691a4d845d341fd5ee3a9968dec7a5316f3e4f56",
          "sha256": "3a85e16b430f92c0a99fe0812974cf3513e3952d725b1bb657f2ca877edc020e",
          "sha1": "3b1025cbbb9610acf13a8fd42e74a19f4039e2ce",
          "md5": "122718e0fbc236cdc6bbf091c838fd73"
        }
      ]
    }
  ]
}
