{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-enum-selector-SNAPSHOT/core-0.2.0-add-enum-selector-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-enum-selector-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-0.2.0-add-enum-selector-SNAPSHOT.klib",
          "size": 100155,
          "sha512": "96cb0e59e9cbad4f778085cd4e9dd99117c307e597613ae1969aff0bf60be0152ef94bd79d514961b76e126c321ab2195d33ef1e7fe62d54ac037e7c25e06db4",
          "sha256": "6816b8e11b14ea557250400ee7f715a17971bad537bbdc64f8113f9650e53e94",
          "sha1": "735a4f2cbc1dda93a74b96f2d6e462bf00dbf113",
          "md5": "059b67f9bc3a2d52810ffa653a70ae06"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.2.0-add-enum-selector-SNAPSHOT-metadata.jar",
          "url": "core-iosx64-0.2.0-add-enum-selector-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "49d712271c28ff22ddee85f7e8340845390377ce322c07443df3295c779f36584126b879f081e48da5a68bbfa0a8078e4ec65752e8f374189a84015b84f791b0",
          "sha256": "5d81d4b76723ae272ead7411b9caea8f79f2ce94f30aaffbec4b3647fb77bcb8",
          "sha1": "cd386be56fa8a2e22f854c4171a1c96a989fa785",
          "md5": "2c25f01e56df3f70cec0b69912b32a1a"
        }
      ]
    }
  ]
}
