{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "a2e620b-fix-isnot-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-a2e620b-fix-isnot-SNAPSHOT.jar",
          "url": "kmock-processor-a2e620b-fix-isnot-SNAPSHOT.jar",
          "size": 40556,
          "sha512": "4611c19a4d073bd19e17e715206e5ab7952902dbf990fab913fc949a08f139cd82e44a8003b74fa7765f9799e06b1cccbccec2cf710a35d5048882291ddcbeb8",
          "sha256": "78735dee9df55f6b3c731ec06bafd20a73de06d2afb6e0fc834abc9449b737a8",
          "sha1": "6f82879a99f0f887d76c302b93d86f44b8fb0085",
          "md5": "5d9bb58f182599d7749bee7ea29f6d3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "a2e620b-fix-isnot-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-a2e620b-fix-isnot-SNAPSHOT.jar",
          "url": "kmock-processor-a2e620b-fix-isnot-SNAPSHOT.jar",
          "size": 40556,
          "sha512": "4611c19a4d073bd19e17e715206e5ab7952902dbf990fab913fc949a08f139cd82e44a8003b74fa7765f9799e06b1cccbccec2cf710a35d5048882291ddcbeb8",
          "sha256": "78735dee9df55f6b3c731ec06bafd20a73de06d2afb6e0fc834abc9449b737a8",
          "sha1": "6f82879a99f0f887d76c302b93d86f44b8fb0085",
          "md5": "5d9bb58f182599d7749bee7ea29f6d3d"
        }
      ]
    }
  ]
}
