{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/449d891-bump-updates-SNAPSHOT/test-utils-annotations-449d891-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "449d891-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-449d891-bump-updates-SNAPSHOT.klib",
          "size": 11328,
          "sha512": "139a1df39a4e87c57b226458c3f51eaa692324fa78134a1bb48ab51abd2c7914c027c864aa5a49d1f5f93566d868cabea5b0e4f543a1d8768ac47fae6bc65bbc",
          "sha256": "167078fceafef4d7b12aa1246194b22e2f64c21b6857db5ecdb79fe34a416ff5",
          "sha1": "840af79c504cffa448a9a408ad2cc5136c0fa2bc",
          "md5": "7682e0404c38c1fab5c4d35970f7ad44"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-449d891-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosarm64-449d891-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "28ae946de6a0bd3e4959e09d58e2d773e0b79394b062f85a29843164a97cad1dcc2c0be0f8b54c661403985d33765ebd3349adb99ed19384d044ba6f24dbdab9",
          "sha256": "247a1019ad8d1550eed0253fece4157cfba43a27a4650fd372ff4b7d54fa69c2",
          "sha1": "df609d7e4252cdb76fce6eda0e4a7d8f9eb156aa",
          "md5": "a19e7c17a18ee4dec8be7bf930ae326e"
        }
      ]
    }
  ]
}
