{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-coroutine-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "9a9fde9068df2bf62a03d0964aa8ac7939d54cad2652c2a5966a212fe72b9dd2a7898b541c130e2cf4f21601804fa265d199e805cdce7ac3f6cf7b09f3f9b935",
          "sha256": "e6ee8af4c3a91231ae52cfd8095fab4d5b25515e5a0a1a1810b39b9385785e52",
          "sha1": "4785ae666c357f321f379cf71673c7a3deb7e63c",
          "md5": "3db0282ed88cdf695e5eed9612ca0231"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "size": 12013,
          "sha512": "9a9fde9068df2bf62a03d0964aa8ac7939d54cad2652c2a5966a212fe72b9dd2a7898b541c130e2cf4f21601804fa265d199e805cdce7ac3f6cf7b09f3f9b935",
          "sha256": "e6ee8af4c3a91231ae52cfd8095fab4d5b25515e5a0a1a1810b39b9385785e52",
          "sha1": "4785ae666c357f321f379cf71673c7a3deb7e63c",
          "md5": "3db0282ed88cdf695e5eed9612ca0231"
        }
      ]
    }
  ]
}
