{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "34ae4ae-change-generic-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-34ae4ae-change-generic-factory-SNAPSHOT.jar",
          "url": "kmock-gradle-34ae4ae-change-generic-factory-SNAPSHOT.jar",
          "size": 52035,
          "sha512": "88d66486aaff66745658da329f649bd0ed48b4aa0f238c1381f80bfa445b94dde909947401fe74899c01ed67bdf19b214a67b95f08a911c9ef877e6c87e6d431",
          "sha256": "f23cd7dd73671966eb5d6d31ba3f6f11b5e1f258663e68defa08d95d73e9ae07",
          "sha1": "2e5e1f904d08e1c81a92be28620d5b58181942f4",
          "md5": "e18c894e25c18b1ad2bdb67fe50ad922"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-34ae4ae-change-generic-factory-SNAPSHOT.jar",
          "url": "kmock-gradle-34ae4ae-change-generic-factory-SNAPSHOT.jar",
          "size": 52035,
          "sha512": "88d66486aaff66745658da329f649bd0ed48b4aa0f238c1381f80bfa445b94dde909947401fe74899c01ed67bdf19b214a67b95f08a911c9ef877e6c87e6d431",
          "sha256": "f23cd7dd73671966eb5d6d31ba3f6f11b5e1f258663e68defa08d95d73e9ae07",
          "sha1": "2e5e1f904d08e1c81a92be28620d5b58181942f4",
          "md5": "e18c894e25c18b1ad2bdb67fe50ad922"
        }
      ]
    }
  ]
}
