{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "6c9977a-change-plugin-resolution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-publishing-6c9977a-change-plugin-resolution.jar",
          "size": 130790,
          "sha512": "369e1426d8ba22e848cd6b5d5674c082749235828d3c202bde852baf4604c19f1c4c97c789055d2288cf906b888210a153e5a93dfa26d43f8fb31f2764153b28",
          "sha256": "0676acaae6f3ff6e212dabf39cd3b63361a4ff0683870d9cffffd7ceb452436a",
          "sha1": "edee721c89f799a85ffb55a43a8833c823de8ade",
          "md5": "81da6dd24deed9ff2d2fa38f60454dda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "6c9977a-change-plugin-resolution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-6c9977a-change-plugin-resolution.jar",
          "url": "antibytes-publishing-6c9977a-change-plugin-resolution.jar",
          "size": 130790,
          "sha512": "369e1426d8ba22e848cd6b5d5674c082749235828d3c202bde852baf4604c19f1c4c97c789055d2288cf906b888210a153e5a93dfa26d43f8fb31f2764153b28",
          "sha256": "0676acaae6f3ff6e212dabf39cd3b63361a4ff0683870d9cffffd7ceb452436a",
          "sha1": "edee721c89f799a85ffb55a43a8833c823de8ade",
          "md5": "81da6dd24deed9ff2d2fa38f60454dda"
        }
      ]
    }
  ]
}
