{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-offset-SNAPSHOT/core-0.3.1-add-offset-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-offset-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-offset-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-offset-SNAPSHOT.klib",
          "size": 133186,
          "sha512": "89da9c8cbd6500f5442a66a4a211ad3fdc324c0a93f00696b2b032b025c2cb8dc773bd05ea48fededd81abd02b3de48f97bf21e356c5ce77709b1209eb314775",
          "sha256": "8eee893e24d234c6dffa7cd61a1d79a030e02e28ecee67cd4c92597389bc0ef7",
          "sha1": "30294fd5125fbc121968e6d54d5079df798d41b1",
          "md5": "4baa86b2c1f645e14c8ec3d0f29cc1cb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-offset-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-offset-SNAPSHOT.klib",
          "size": 133186,
          "sha512": "89da9c8cbd6500f5442a66a4a211ad3fdc324c0a93f00696b2b032b025c2cb8dc773bd05ea48fededd81abd02b3de48f97bf21e356c5ce77709b1209eb314775",
          "sha256": "8eee893e24d234c6dffa7cd61a1d79a030e02e28ecee67cd4c92597389bc0ef7",
          "sha1": "30294fd5125fbc121968e6d54d5079df798d41b1",
          "md5": "4baa86b2c1f645e14c8ec3d0f29cc1cb"
        }
      ]
    }
  ]
}
