{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "1fdf1dafb711c53cbd202d2d5d485972a30a2587d3c5b75d6da6c5d799ba182f12fd448e730f1c60d7f691b14f18e392f0b3523f8b87595b6456c2944de81ad7",
          "sha256": "57bf6223691c6c45d5ed1bc7e7bff2b30c8baccc7f47ff9ea729a4404acd96d9",
          "sha1": "d2c4a3c7ad38622c1387232b9f0600ee36b154f2",
          "md5": "b6987494581aab0c50d3f6dd5c1dbb8b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "1fdf1dafb711c53cbd202d2d5d485972a30a2587d3c5b75d6da6c5d799ba182f12fd448e730f1c60d7f691b14f18e392f0b3523f8b87595b6456c2944de81ad7",
          "sha256": "57bf6223691c6c45d5ed1bc7e7bff2b30c8baccc7f47ff9ea729a4404acd96d9",
          "sha1": "d2c4a3c7ad38622c1387232b9f0600ee36b154f2",
          "md5": "b6987494581aab0c50d3f6dd5c1dbb8b"
        }
      ]
    }
  ]
}
