{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-SNAPSHOT/kmock-0.3.0-rc01-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "14a1b69c2af43353d663376fa2425267f558fc4e44c4bf39992940832d2b101cfc269548e90cd22f430a7950a5a5562b2d370c6f9d7f3220b1d1d4f6881d3f48",
          "sha256": "851bdbf4baeaa36a300d2a11fafe5049e74ee5ac45ed1afba96d0ebeaf6a666f",
          "sha1": "76d59d16db8ba0521bd89be0239600a06c76af68",
          "md5": "1d05f4af9a7fdf3af48beb350a1dd10c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "14a1b69c2af43353d663376fa2425267f558fc4e44c4bf39992940832d2b101cfc269548e90cd22f430a7950a5a5562b2d370c6f9d7f3220b1d1d4f6881d3f48",
          "sha256": "851bdbf4baeaa36a300d2a11fafe5049e74ee5ac45ed1afba96d0ebeaf6a666f",
          "sha1": "76d59d16db8ba0521bd89be0239600a06c76af68",
          "md5": "1d05f4af9a7fdf3af48beb350a1dd10c"
        }
      ]
    }
  ]
}
