{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-settings",
    "version": "c7c9150-change-detekt-config",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-c7c9150-change-detekt-config.jar",
          "url": "antibytes-dependency-settings-c7c9150-change-detekt-config.jar",
          "size": 8748,
          "sha512": "8269044847bd8d8e346d9452029e9691647222592d02fdd45e1a113e2e4cdc1b482cfafb754b2be34e5c3e7fa8c8a9614a4c606a16444b794cdecabb5a4cb25b",
          "sha256": "b86ea840feb2744682727e0dde2b3532c3aee08781aad3ca89e89551362d561b",
          "sha1": "4eb42249c29d7d862881a13e16f6eb8c6af96c3c",
          "md5": "49fbf795b1709354e5df571fbe21db7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-c7c9150-change-detekt-config.jar",
          "url": "antibytes-dependency-settings-c7c9150-change-detekt-config.jar",
          "size": 8748,
          "sha512": "8269044847bd8d8e346d9452029e9691647222592d02fdd45e1a113e2e4cdc1b482cfafb754b2be34e5c3e7fa8c8a9614a4c606a16444b794cdecabb5a4cb25b",
          "sha256": "b86ea840feb2744682727e0dde2b3532c3aee08781aad3ca89e89551362d561b",
          "sha1": "4eb42249c29d7d862881a13e16f6eb8c6af96c3c",
          "md5": "49fbf795b1709354e5df571fbe21db7a"
        }
      ]
    }
  ]
}
