{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "1ba4d29-change-gradle-action-runner",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-gradle-test-utils-1ba4d29-change-gradle-action-runner.jar",
          "size": 17243,
          "sha512": "73b44e5bd96680c6ea69e367a7ff1ffe5b9214741816c0ff61f66ed26040d222b5e4120a78411f55443b588e3c94d1f59bbe31f79cb23449bd58755f459f81ca",
          "sha256": "981e1a93859bc00dcc1b719612be06396cd9ea882f772ebf414d7099de0b2ff4",
          "sha1": "a9e968e0626ca6681792a10e1f6a3cb7b7858aab",
          "md5": "02c3baa109b1b6d0a9569eba319d4a94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-gradle-test-utils-1ba4d29-change-gradle-action-runner.jar",
          "size": 17243,
          "sha512": "73b44e5bd96680c6ea69e367a7ff1ffe5b9214741816c0ff61f66ed26040d222b5e4120a78411f55443b588e3c94d1f59bbe31f79cb23449bd58755f459f81ca",
          "sha256": "981e1a93859bc00dcc1b719612be06396cd9ea882f772ebf414d7099de0b2ff4",
          "sha1": "a9e968e0626ca6681792a10e1f6a3cb7b7858aab",
          "md5": "02c3baa109b1b6d0a9569eba319d4a94"
        }
      ]
    }
  ]
}
