{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/577fd36-bump-antibytes-SNAPSHOT/test-utils-annotations-577fd36-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "577fd36-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-577fd36-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-577fd36-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ca016f86a7a787d6c808fef95242242a4d765a5e4651c744f162cbb9808fac47cc92244dec5ddf462949dd801247ccd17da2617b7b9913e5251802210e282bb7",
          "sha256": "387aae823cdd65cd9c53950ba86b25606a159fe9ce5249cf7d80fd64ce233d79",
          "sha1": "08f5f1461abd026d960f01d60ea97becec7561ea",
          "md5": "de071c5743e5fa35ceac1086e3143fb0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-577fd36-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-577fd36-bump-antibytes-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ca016f86a7a787d6c808fef95242242a4d765a5e4651c744f162cbb9808fac47cc92244dec5ddf462949dd801247ccd17da2617b7b9913e5251802210e282bb7",
          "sha256": "387aae823cdd65cd9c53950ba86b25606a159fe9ce5249cf7d80fd64ce233d79",
          "sha1": "08f5f1461abd026d960f01d60ea97becec7561ea",
          "md5": "de071c5743e5fa35ceac1086e3143fb0"
        }
      ]
    }
  ]
}
