{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-bump-min-ios-version-SNAPSHOT/ktx-datetime-0.3.1-bump-min-ios-version-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-bump-min-ios-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-bump-min-ios-version-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-bump-min-ios-version-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6d183af5cd78c5f9a4ba951e3965882c9201f0fba0bbdf96c27d55a79304fbdb1c4e49ca6a58f4d469875619b5434725fa35aa1a1083ea550c35c7b967e9a146",
          "sha256": "7a692a5d6c351b96811c2c4f176b1da628238514fe8b85f6d3f7fa1e13ed6c10",
          "sha1": "98532942d7aaba79a6c878a0ea53a347896ffc95",
          "md5": "79d04d2d679dc43115b40a3a9c5ea46e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-bump-min-ios-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.3.1-bump-min-ios-version-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.3.1-bump-min-ios-version-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6d183af5cd78c5f9a4ba951e3965882c9201f0fba0bbdf96c27d55a79304fbdb1c4e49ca6a58f4d469875619b5434725fa35aa1a1083ea550c35c7b967e9a146",
          "sha256": "7a692a5d6c351b96811c2c4f176b1da628238514fe8b85f6d3f7fa1e13ed6c10",
          "sha1": "98532942d7aaba79a6c878a0ea53a347896ffc95",
          "md5": "79d04d2d679dc43115b40a3a9c5ea46e"
        }
      ]
    }
  ]
}
