{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "4bb1282-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-4bb1282-fix-factory-SNAPSHOT.jar",
          "url": "kmock-gradle-4bb1282-fix-factory-SNAPSHOT.jar",
          "size": 49492,
          "sha512": "4dd5d21a92bd132333b4ae1631344af0d31c0c66aa592988c8da6b0e283667baae63e9e3c178f678621541dabc82305d24cda98bccdc0f016a93ff0f3634e041",
          "sha256": "56d0144f1821962389e141ec8568187ddf92b6c85a6306481d59e600b83659a6",
          "sha1": "0e8882b7de32c6963774b054a90d75ab70add50c",
          "md5": "36aa0731aff32b1cec59cfd6c8b1d3ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-4bb1282-fix-factory-SNAPSHOT.jar",
          "url": "kmock-gradle-4bb1282-fix-factory-SNAPSHOT.jar",
          "size": 49492,
          "sha512": "4dd5d21a92bd132333b4ae1631344af0d31c0c66aa592988c8da6b0e283667baae63e9e3c178f678621541dabc82305d24cda98bccdc0f016a93ff0f3634e041",
          "sha256": "56d0144f1821962389e141ec8568187ddf92b6c85a6306481d59e600b83659a6",
          "sha1": "0e8882b7de32c6963774b054a90d75ab70add50c",
          "md5": "36aa0731aff32b1cec59cfd6c8b1d3ef"
        }
      ]
    }
  ]
}
