{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/4bf7bd2-change-mocks-SNAPSHOT/kmock-4bf7bd2-change-mocks-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "4bf7bd2-change-mocks-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-4bf7bd2-change-mocks-SNAPSHOT.jar",
          "url": "kmock-jvm-4bf7bd2-change-mocks-SNAPSHOT.jar",
          "size": 195714,
          "sha512": "41d6209cc099b5252ca440804393ace9183300242579200947b5d2bf1f4e55fd2c5628a0ebd2e708d9290b47d1eb843e328216558aed811d1e090cb3d1d8a8cf",
          "sha256": "a26d9ec394e9fa4b00f23ed11920f263cdb3c3664cbde317a474aa723816a312",
          "sha1": "2dde3d296d9320d6642104cf376dd21933dc6de5",
          "md5": "790a668fdcce488bf1dd7cc4fd5ce7ef"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-4bf7bd2-change-mocks-SNAPSHOT.jar",
          "url": "kmock-jvm-4bf7bd2-change-mocks-SNAPSHOT.jar",
          "size": 195714,
          "sha512": "41d6209cc099b5252ca440804393ace9183300242579200947b5d2bf1f4e55fd2c5628a0ebd2e708d9290b47d1eb843e328216558aed811d1e090cb3d1d8a8cf",
          "sha256": "a26d9ec394e9fa4b00f23ed11920f263cdb3c3664cbde317a474aa723816a312",
          "sha1": "2dde3d296d9320d6642104cf376dd21933dc6de5",
          "md5": "790a668fdcce488bf1dd7cc4fd5ce7ef"
        }
      ]
    }
  ]
}
