{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-fix-publishing-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-fix-publishing-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "0429a636424e32b3a37c4f62e5154fee771b3ff92c01af273b6093cf97527c2c49b1aae25c5b30187a4697b9044600904ce7eda2be30e878c11b48973998c27a",
          "sha256": "978e9e1caa530ddcaf39fa6b3e76e29289d5a85675f2e708d093865c7242ed41",
          "sha1": "27a43ab44d4ef2a37f89f7142010804c082d23eb",
          "md5": "792a3bd08ef5da77d1381f1dd68a53b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.0-fix-publishing-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.0-fix-publishing-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.0-fix-publishing-SNAPSHOT.jar",
          "size": 114685,
          "sha512": "0429a636424e32b3a37c4f62e5154fee771b3ff92c01af273b6093cf97527c2c49b1aae25c5b30187a4697b9044600904ce7eda2be30e878c11b48973998c27a",
          "sha256": "978e9e1caa530ddcaf39fa6b3e76e29289d5a85675f2e708d093865c7242ed41",
          "sha1": "27a43ab44d4ef2a37f89f7142010804c082d23eb",
          "md5": "792a3bd08ef5da77d1381f1dd68a53b1"
        }
      ]
    }
  ]
}
