{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit5-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-linuxmipsel32-694b583-change-setup-SNAPSHOT.klib",
          "size": 7093,
          "sha512": "1312dac30fa4de1a6a41adbd52e026ce6c11609f90f21c0f5a23c089fd7e541704978dd70fe734f52a24a4025d0b7e0fdfd28b022c09b15945f88639ef0b8211",
          "sha256": "c8e9369ca3b1ccaba4c70d546b71a7fd086c09cf7f93af30bc4bef034fb34f82",
          "sha1": "b144bbe7fc38c1a6d894e9840ed7ead9ed08efa5",
          "md5": "d042f328ced2b4e4dcec8f5821ed14eb"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-linuxmipsel32-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-linuxmipsel32-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "439ef7e1873ad579f612341c65e401a647a3072b32d88f8703640ec4985dfbf4a7f08bfcc711684dd3d3e5e44e923e4a9cf8fa64d7073c60ef4138c4b5e2cfb5",
          "sha256": "738fa42918bba11cac72a94cfcb458d7982e8d3b2fed3f725a8a06af56ad6d5a",
          "sha1": "ef62524c802800cd0acb4c7cc96b540cdf228bbb",
          "md5": "e12400674263a1ab45303db93324a197"
        }
      ]
    }
  ]
}
