{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-workflows-SNAPSHOT/core-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvossimulatorarm64-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 105931,
          "sha512": "600898463dad44f638d235c4e6b2258dafa25380b1d084ba7f35eb6d3feaf7321ed249b5f0c0f91094f614adc658ae07999389ab94fbd7a4332563cf34fb554a",
          "sha256": "e97db53c38bed7544ab7dd97af682f6cd868c224bbd178bcfca62a049c8ca72a",
          "sha1": "4e0f0825f4657f1063668f60c4b9b34d75573d87",
          "md5": "974957318c35e7ec8399d8ab3331bb50"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "core-tvossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9517690dc5a90861801dc6c59a83bc608e7c024e37027ec71f8432a7a4612c94e1934990abcffb4a6a2da25e2e25a3f91759fe2198cceacba1250a24b2e2046b",
          "sha256": "5185d7ccba0d15173cfd944c8277afbd0e130960d57bcb7ff84d4723bfa8e23f",
          "sha1": "78468018653d61306efe480589ed38d59f7fe322",
          "md5": "e2c2b4199ba5ed485385f776d7fd4583"
        }
      ]
    }
  ]
}
