{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/db53051-change-workflows-SNAPSHOT/test-utils-coroutine-db53051-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-db53051-change-workflows-SNAPSHOT.klib",
          "size": 10112,
          "sha512": "0c9109497ef5116df57d780fb9927fa9a211b8c342a4a7fbb3461b555cfc0a69658dd4d762d29aeb47083f1264b99df98abe9ca148acfe1f7227ae8e67041ad7",
          "sha256": "2da8c8de1522ad369562f0bd2b838eba30fdb3b2eefa319776aab12fff1d9c69",
          "sha1": "3d1c065ed2929a8a21b7209b42256a163e080647",
          "md5": "6e8825ff0ee058c6b2a9aeeefd714a50"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-db53051-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosx64-db53051-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2812bf182ba3e29f6fd151b926f20c98bac1d0c2841e382b0099e91fb85c38d916b9239cd8b667962e0b8e90c53e35ce52d5fef30e14088bebcfb412a0cc8a79",
          "sha256": "8ffd65db0f4b37e8854690e3537791f858dcdae23100397ed4ff476ab3558110",
          "sha1": "74e903460269ec79ce88c20d264a1991b1a0ac2d",
          "md5": "b95cfceaca5762a57ff4295b92b3d91c"
        }
      ]
    }
  ]
}
