{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/dccc533-change-project-setup-SNAPSHOT/test-utils-annotations-junit5-dccc533-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "dccc533-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-dccc533-change-project-setup-SNAPSHOT.klib",
          "size": 7049,
          "sha512": "e82644416b7480c0e1e297e8b55903278dd59dcbe80a4aba35c969a5d55202c1b0fcb1a6cf5fac3b3cee4945a57f44ba15fcfdd82d726015f92482799375c2a1",
          "sha256": "cf3ab81b6becab5c1e36f156abf3ed0cac8ea12777f2a8d7242ca76b377c13df",
          "sha1": "f2399643618d581a8b56df40dbfe051f03472ef1",
          "md5": "8e92a1493a8e1a501e163317c9ffd25e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-dccc533-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-dccc533-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0e9884ba131e5caf38dd96e98b3583382ad0ccb3a3e74d007dc66d600ac7930939eeea5d3ce3b33c6061711d2da3978b43412d6c5be4017f1d97c1bfaac521d7",
          "sha256": "0578b817c3a22e032c744b7fb3252ff974c24aceedb2788fddde08b82bc0e5b7",
          "sha1": "7628d9b3bc0abdc4b217d229070c30c518ae8983",
          "md5": "9569e76c37ab24176998ab65db474ef2"
        }
      ]
    }
  ]
}
