{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "6498584-add-kotlinjs-wrapper",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-6498584-add-kotlinjs-wrapper.jar",
          "url": "antibytes-quality-6498584-add-kotlinjs-wrapper.jar",
          "size": 62639,
          "sha512": "48ebdb8d1107d5c131f3d2e79298f65edb09d144c6c55cc23f37e6707654401ca6d37c34c7cc7d46de94ee4420d84af8c9f9bdad111dbc6f7e9753334319798e",
          "sha256": "8b3af722e84c93ae68ece28372ea73ce0c05a72cea04e6c810f7e388d5993c88",
          "sha1": "77b5c275dd0e611b620229829b490cd152c81c9e",
          "md5": "e43cf071a68d4568cb1ee43b16b57798"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.22.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6498584-add-kotlinjs-wrapper"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "6498584-add-kotlinjs-wrapper"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-6498584-add-kotlinjs-wrapper.jar",
          "url": "antibytes-quality-6498584-add-kotlinjs-wrapper.jar",
          "size": 62639,
          "sha512": "48ebdb8d1107d5c131f3d2e79298f65edb09d144c6c55cc23f37e6707654401ca6d37c34c7cc7d46de94ee4420d84af8c9f9bdad111dbc6f7e9753334319798e",
          "sha256": "8b3af722e84c93ae68ece28372ea73ce0c05a72cea04e6c810f7e388d5993c88",
          "sha1": "77b5c275dd0e611b620229829b490cd152c81c9e",
          "md5": "e43cf071a68d4568cb1ee43b16b57798"
        }
      ]
    }
  ]
}
