{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "6099f4a-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-gradle-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "size": 29357,
          "sha512": "5f6fd48417d1c3992407ab9fbda03c4b04993e5bca5ff812000fc7166aa92a975321a3ec47c77353809d60c7821c4f20aa9facab5f1cb34867c46cb114b65526",
          "sha256": "f76437813049e9089e56e9360ec7606240e7373ff9e96e478711ff17bdf1e4d4",
          "sha1": "b5c6dc1016b4c59d0cd03f7253f4038a41ad389b",
          "md5": "3f9d195a9bf69c8055389cf90b201458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5b2583f"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-gradle-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "size": 29357,
          "sha512": "5f6fd48417d1c3992407ab9fbda03c4b04993e5bca5ff812000fc7166aa92a975321a3ec47c77353809d60c7821c4f20aa9facab5f1cb34867c46cb114b65526",
          "sha256": "f76437813049e9089e56e9360ec7606240e7373ff9e96e478711ff17bdf1e4d4",
          "sha1": "b5c6dc1016b4c59d0cd03f7253f4038a41ad389b",
          "md5": "3f9d195a9bf69c8055389cf90b201458"
        }
      ]
    }
  ]
}
