{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-change-changelog-SNAPSHOT/ktx-datetime-0.4.0-change-changelog-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-changelog-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-change-changelog-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-change-changelog-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "552eae031bb8e4f726f3554cf60bcf557cabb95907158e1e1a8a6305b15f6bdbf047115e9a3299200e22956a36d8c0fc213c1ddb2f1a872f0f1e10edb6f73dec",
          "sha256": "9023efb18e57b2cbb575274a105cacc0198d1e925a14d0830f7f7c2d575c8ed9",
          "sha1": "8abb69c35d9447ee4c5e0a78504e6d285684a8e6",
          "md5": "45f45018fcc1c29ef682d0ee7d8e5dc0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-changelog-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-change-changelog-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-change-changelog-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "552eae031bb8e4f726f3554cf60bcf557cabb95907158e1e1a8a6305b15f6bdbf047115e9a3299200e22956a36d8c0fc213c1ddb2f1a872f0f1e10edb6f73dec",
          "sha256": "9023efb18e57b2cbb575274a105cacc0198d1e925a14d0830f7f7c2d575c8ed9",
          "sha1": "8abb69c35d9447ee4c5e0a78504e6d285684a8e6",
          "md5": "45f45018fcc1c29ef682d0ee7d8e5dc0"
        }
      ]
    }
  ]
}
