{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/e930d3d-change-project-setup-SNAPSHOT/test-utils-annotations-junit4-e930d3d-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "e930d3d-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosx64-e930d3d-change-project-setup-SNAPSHOT.klib",
          "size": 11335,
          "sha512": "a2b53caf68a6238f48cb4582555a79eb50d91dc842aa7c144782c1901b31ce7f9bf0d6b81e791a8ff23dd068e3bf2897198e58f008a6bb58779d8995c89dc042",
          "sha256": "0c0bd6ef30e191d9933583a320776bb991623922170cba30ae14477f3e3c90d7",
          "sha1": "c9d01ac9add1320a06ea845bb74746a10fbf870b",
          "md5": "123085bdd3e3489ec2d5e3886fd3710f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosx64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosx64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b31b8c5c23d535d16dc51c73e118563abedf1443c4efda965631045e22f7f81fdc52da11b2670a4da900479a09926607758adeabf94f8907f621776f3f6ff3d8",
          "sha256": "4df7838763ba68685e9f08abde6d794de861e109957f80268ada18a0569af4a7",
          "sha1": "2bc80d491649a379cac23848ca6a7388c7b294ee",
          "md5": "61c983c914ab9e10be0a54a8e4490dc3"
        }
      ]
    }
  ]
}
