{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-SNAPSHOT/core-0.2.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 251480,
          "sha512": "e8f5f6a7658b7bf40abfb731876ff8ceaa6055aa5d49361268b44fe39573218b16d4a1c8bd8fea59fff7ffaa831aa5a4ed66b4cafffad90a32477ba5da820798",
          "sha256": "7f600785b1506798415685f79276aed4cfe4f23e213b32bc017fa5ddff01a873",
          "sha1": "ed1fd2ea83e77ad319294ef98dc391fe518e1023",
          "md5": "fe53fb48f32ebef292484bd51bd67428"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-SNAPSHOT.jar",
          "size": 251480,
          "sha512": "e8f5f6a7658b7bf40abfb731876ff8ceaa6055aa5d49361268b44fe39573218b16d4a1c8bd8fea59fff7ffaa831aa5a4ed66b4cafffad90a32477ba5da820798",
          "sha256": "7f600785b1506798415685f79276aed4cfe4f23e213b32bc017fa5ddff01a873",
          "sha1": "ed1fd2ea83e77ad319294ef98dc391fe518e1023",
          "md5": "fe53fb48f32ebef292484bd51bd67428"
        }
      ]
    }
  ]
}
