{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/e620e63-add-typesafe-argument-retrieval-SNAPSHOT/kmock-e620e63-add-typesafe-argument-retrieval-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "e620e63-add-typesafe-argument-retrieval-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-e620e63-add-typesafe-argument-retrieval-SNAPSHOT.klib",
          "url": "kmock-js-e620e63-add-typesafe-argument-retrieval-SNAPSHOT.klib",
          "size": 121177,
          "sha512": "df17ac262d3fb5e9c34bcfdae92b37a86064dd7fd13f5ff0d2d817ae8ca6d1d93629d827a420985cd8acdd5e5de1f354b5c2dba7ae8ec66138a359c33e2dd1c9",
          "sha256": "f59564c191ff6e0672e4e07605e42fcadfa46504bd404f6cc012e52670914f53",
          "sha1": "52a614cfbe4ac9a2c28b1d1aebe60f5d100ce8ae",
          "md5": "4534dd0deb4fc24ca08355e2b6ae3ff4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-e620e63-add-typesafe-argument-retrieval-SNAPSHOT.klib",
          "url": "kmock-js-e620e63-add-typesafe-argument-retrieval-SNAPSHOT.klib",
          "size": 121177,
          "sha512": "df17ac262d3fb5e9c34bcfdae92b37a86064dd7fd13f5ff0d2d817ae8ca6d1d93629d827a420985cd8acdd5e5de1f354b5c2dba7ae8ec66138a359c33e2dd1c9",
          "sha256": "f59564c191ff6e0672e4e07605e42fcadfa46504bd404f6cc012e52670914f53",
          "sha1": "52a614cfbe4ac9a2c28b1d1aebe60f5d100ce8ae",
          "md5": "4534dd0deb4fc24ca08355e2b6ae3ff4"
        }
      ]
    }
  ]
}
