{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-SNAPSHOT/core-0.4.0-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-mingwx86-0.4.0-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "14ad87874857b47ffcb95be242f9209e06b499596e13f543a133df297099d23985b555a91838a7678aa592c140179f8848d692cf4c21f6e12e5df1960cd04429",
          "sha256": "28637cdde01cd5b413332d190ace3b29f178bf2c2794e40b093a8e9d7d003044",
          "sha1": "bdba9b7d438975294e2fa0a6d63a0519f771a578",
          "md5": "1350e23946dd283a9ef2f0491902614a"
        }
      ]
    }
  ]
}
