{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/cf7c122-change-coroutine-tests-SNAPSHOT/test-utils-cf7c122-change-coroutine-tests-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "cf7c122-change-coroutine-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-cf7c122-change-coroutine-tests-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "149bbc9381a7c3ed7331af9d4efe0d42972b0cdd267650ff0eebe7d593bc9c26bb480ea6487243c2078ca42e07b130a64d6897af5f5271c4f17876312b39cf58",
          "sha256": "223f43f672a8cb6b0d5cb88a87c425f2916a204f37e5cde9d917871db4e64f3d",
          "sha1": "10c83585fb7da5fcf3c3c6ecbba315e9ddae4e32",
          "md5": "80edaa63f0c5a485f2b88bf4685ffd24"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-cf7c122-change-coroutine-tests-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "149bbc9381a7c3ed7331af9d4efe0d42972b0cdd267650ff0eebe7d593bc9c26bb480ea6487243c2078ca42e07b130a64d6897af5f5271c4f17876312b39cf58",
          "sha256": "223f43f672a8cb6b0d5cb88a87c425f2916a204f37e5cde9d917871db4e64f3d",
          "sha1": "10c83585fb7da5fcf3c3c6ecbba315e9ddae4e32",
          "md5": "80edaa63f0c5a485f2b88bf4685ffd24"
        }
      ]
    }
  ]
}
