{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-change-android-source-distribution-SNAPSHOT/kmock-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-change-android-source-distribution-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.klib",
          "size": 202924,
          "sha512": "a3c7fb41fd5a044e3b65a768aa226a2359e2a1e830fdc07f001e399cd8685fc9efecfa9fc01098d938c861cfd95bd8e69ca1d131b42842e1ae3f7e58b6e42778",
          "sha256": "a9914f7acdcd8ce3c68e1fba0a901e73a8f2b9dd1488c0b9901386de489bc94b",
          "sha1": "70bd7022cd54cbe1d0ac3ecc06797be299bb6652",
          "md5": "6727871b0342fcc2ca3285f59a46cd6e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6afcd789a7eeb4ca045069a9867dd1a7cc27c9c8c07c633887765e4f75482e5b530be89abb3f39f262272ed5c46453a9a3e468dac96ab085fbe8e4520435ae1c",
          "sha256": "990d9b7e216f1577801b6fc91861643b1f750f30fc347deda2ff50be1a65ec36",
          "sha1": "4a78bd086f8198a264ed46a5e25ec59eb4a301fd",
          "md5": "3a93e12811b3acaf4dcd8138743285cb"
        }
      ]
    }
  ]
}
