{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-macosx64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 7050,
          "sha512": "a17acbea12d977f4f28ebbf5f18e23c0c27fb354ccbe569e09ad9bbf969431103a66006aef7eaf0ceddaf11828c14b3ca766c2e73f2ff818f30fe751fd396a4b",
          "sha256": "7956f67a59f38a3b3c69dc9748e14bc1d3ca4b48c9b12b61c1f7ea86bf70406a",
          "sha1": "0cda7c8e43b80a838c697be24988c5f8c2d3bc17",
          "md5": "926054f5ad8f619189bcdf19cfef0601"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-macosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-macosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4a9151d84c53093321de3f40fa70f9f4ff51745aa683e3903c4a51172f8102bc47bc4207a3b71a2c979b1da04a07f32986770b4f465867cf8c66fd5fef3233af",
          "sha256": "165e0b8144cf42b0d7da2a54142e5b8f168da2a9b5167f36d3c279c8684c2f07",
          "sha1": "8365a9a459df5817d9486471147fe596b0b5d39b",
          "md5": "e5b066d38b67f46867e2fcc4d54a2702"
        }
      ]
    }
  ]
}
