{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03-change-dependencies-SNAPSHOT/kmock-0.3.0-rc03-change-dependencies-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-change-dependencies-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-change-dependencies-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-change-dependencies-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "46eba54c8f58c8ece9347182873f7d98ab3a20eac914e9e6c99293de7cf248da43a8cf1368bf1ff0b3ded93cd51a59f92ee8b7a29e470c4bb0cf4fc613ac5ca3",
          "sha256": "6c27bd7d97dd8ddc7ef6e8b1a304d0641ff59554274a4706e1426a31f521bd2e",
          "sha1": "66e8ee8b446ca33583f0b87071e98a2aff8a550d",
          "md5": "516b9fd07778fd948bd43d0f2ba82a2b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-change-dependencies-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-change-dependencies-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "46eba54c8f58c8ece9347182873f7d98ab3a20eac914e9e6c99293de7cf248da43a8cf1368bf1ff0b3ded93cd51a59f92ee8b7a29e470c4bb0cf4fc613ac5ca3",
          "sha256": "6c27bd7d97dd8ddc7ef6e8b1a304d0641ff59554274a4706e1426a31f521bd2e",
          "sha1": "66e8ee8b446ca33583f0b87071e98a2aff8a550d",
          "md5": "516b9fd07778fd948bd43d0f2ba82a2b"
        }
      ]
    }
  ]
}
