{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "8a9ec9b-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-8a9ec9b-change-node-dependencies.toml",
          "url": "antibytes-dependency-catalog-8a9ec9b-change-node-dependencies.toml",
          "size": 233445,
          "sha512": "d937f2fa73ec7cd6e85d907447175b65f8dc3e9db7a94d5a03bf88554e0d377cc7d6098d4925ef11c10c1e88a1289836120797d3888e940a472758e39283254f",
          "sha256": "4908aaef72dfed91f4fa4c68b0986a407e2ce94b96a5c99cdf7f7a843be71fd3",
          "sha1": "7fd6f12115e718510855902472c04f3eb1a57098",
          "md5": "07f1c8c722307b680c550da1a2773294"
        }
      ]
    }
  ]
}
