{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-13f09a8-add-more-sources-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "f4e14c53dcf257aae4ed15e87216f16d274d13dce334736f4e9debd9b3140389d8ee87adebca458c74831da9bfa3b3bcb80421bafbe5837b5db4d2a19944ad07",
          "sha256": "996861474a873fb06facd903e3146b4ef99a2723a0b0e30bb151ebbe4766dc52",
          "sha1": "fcb53afcb3a9ca7d8d85ef9243c681a03f169ecb",
          "md5": "bf36b31ea8f5080c32c58f76f4bad242"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-js-13f09a8-add-more-sources-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit5-js-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 4798,
          "sha512": "f4e14c53dcf257aae4ed15e87216f16d274d13dce334736f4e9debd9b3140389d8ee87adebca458c74831da9bfa3b3bcb80421bafbe5837b5db4d2a19944ad07",
          "sha256": "996861474a873fb06facd903e3146b4ef99a2723a0b0e30bb151ebbe4766dc52",
          "sha1": "fcb53afcb3a9ca7d8d85ef9243c681a03f169ecb",
          "md5": "bf36b31ea8f5080c32c58f76f4bad242"
        }
      ]
    }
  ]
}
