{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/ad28a6d-remove-dependency-plugin-SNAPSHOT/test-utils-annotations-junit4-ad28a6d-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "ad28a6d-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "7071a9d40b2d41651b0c42a34eeb12ca9de96cc18d938a0cc5a1e837a7ced9977d6c6fd8a02a97a75c152bdcedc366de435cdb5b569d4e48babc2c3360131117",
          "sha256": "d5ab51f2c7f13ad7447fa3f0d6a77a462e7b635858080cabdb4f3cafe3ccf2bd",
          "sha1": "67950b59f17379c2565790cfe4f4494db9eb2bbc",
          "md5": "016da243d8cfec99c5b59f7e2ac5eb95"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "7071a9d40b2d41651b0c42a34eeb12ca9de96cc18d938a0cc5a1e837a7ced9977d6c6fd8a02a97a75c152bdcedc366de435cdb5b569d4e48babc2c3360131117",
          "sha256": "d5ab51f2c7f13ad7447fa3f0d6a77a462e7b635858080cabdb4f3cafe3ccf2bd",
          "sha1": "67950b59f17379c2565790cfe4f4494db9eb2bbc",
          "md5": "016da243d8cfec99c5b59f7e2ac5eb95"
        }
      ]
    }
  ]
}
