{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT/kmock-0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm32-0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT.klib",
          "size": 203016,
          "sha512": "a393f423952685a0792885404d70a3578ec08122a77292c5670cbcff98ac2606807fac80c73d59cf4ac62faf084654ec0a715ed6d3dd791a34b3c652a48933d9",
          "sha256": "43e1f2b5f8dd786427c158a73e6c0eda2bb58a3b91a4090adee93b99e1d6671f",
          "sha1": "51d7e980345e29aacfb518849def6f99165d95d7",
          "md5": "fe0c9cc38e1bdaa6e40c96b6e784ef74"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm32-0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm32-0.3.0-rc05-bump-updates-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "987884fd332647a0f5431bb305f4fc2a8528f8c87eebf0c17bcd05ace7a78b52acf2616f7c1081f850a5e04927ec9f6f6237134cc30d34f70915becd6c2caee3",
          "sha256": "4f1bed105c8cd6abc19719453bf2be419ec74f2c5ac64082f627a913ca329ce1",
          "sha1": "859a27c4b1bee3766bc1b249e4798057e05c6501",
          "md5": "c21daf1c7cc9ed7f700caa2e76c5bed7"
        }
      ]
    }
  ]
}
