{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/0fd7252-change-project-setup-SNAPSHOT/test-utils-coroutine-0fd7252-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "0fd7252-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-0fd7252-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-0fd7252-change-project-setup-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "629880f82bb6e3863b9d24edaffa754e264668c52d919d691e7a3885f30879642bc29e118130888ce8dfdf8676ba83b46caa2165e1f42fea13e61b3e732c211a",
          "sha256": "c3c1b97cfa2b1dcebc567cd3d28b023f3e0e0d91d13808544aa601dffc3d6a99",
          "sha1": "d2b4d4b4f06d91d6fbcaa39f56e3dfa74abf815c",
          "md5": "5e3b6c81885372b42344621fa327d8a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-0fd7252-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-0fd7252-change-project-setup-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "629880f82bb6e3863b9d24edaffa754e264668c52d919d691e7a3885f30879642bc29e118130888ce8dfdf8676ba83b46caa2165e1f42fea13e61b3e732c211a",
          "sha256": "c3c1b97cfa2b1dcebc567cd3d28b023f3e0e0d91d13808544aa601dffc3d6a99",
          "sha1": "d2b4d4b4f06d91d6fbcaa39f56e3dfa74abf815c",
          "md5": "5e3b6c81885372b42344621fa327d8a5"
        }
      ]
    }
  ]
}
