{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "5f644d5-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-5f644d5-add-plattform-hooks.jar",
          "url": "antibytes-custom-component-5f644d5-add-plattform-hooks.jar",
          "size": 16172,
          "sha512": "88374440c29ba05531a84d756e9779996f1d45fa93ea2288229cdfefb90049198b6a115bcaf0770e34848f8f89a1c296a30e6dd7b15c6679ebf32932ca5cfd25",
          "sha256": "9b5cad64111603e3ce30e61132711200736824b49d626b0528b55f73fa44c203",
          "sha1": "97e1f5cf352e8a139165a359cbccbee617b69bfc",
          "md5": "10e1a866d72f72ffb371ca94716e306f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-5f644d5-add-plattform-hooks.jar",
          "url": "antibytes-custom-component-5f644d5-add-plattform-hooks.jar",
          "size": 16172,
          "sha512": "88374440c29ba05531a84d756e9779996f1d45fa93ea2288229cdfefb90049198b6a115bcaf0770e34848f8f89a1c296a30e6dd7b15c6679ebf32932ca5cfd25",
          "sha256": "9b5cad64111603e3ce30e61132711200736824b49d626b0528b55f73fa44c203",
          "sha1": "97e1f5cf352e8a139165a359cbccbee617b69bfc",
          "md5": "10e1a866d72f72ffb371ca94716e306f"
        }
      ]
    }
  ]
}
