{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/206e82f-add-annotations-module-SNAPSHOT/test-utils-206e82f-add-annotations-module-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "206e82f-add-annotations-module-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-206e82f-add-annotations-module-SNAPSHOT.jar",
          "size": 8776,
          "sha512": "82e253e8758f048392cdef2193eceb3c6c8e5379e21cb411a130c3115010f24d3ff33e98aa37a42dd5e06eb5b30aa7c1038d9de456f12aeab3aea9ce85a984ba",
          "sha256": "05bc2b5af51a646db2b82d158e2bc639ef6496e1f267b2ebc2186b7f40050cf1",
          "sha1": "5fbed158bca9c55c86297e9a95f270aa51df8cba",
          "md5": "ddf7b71b8b78c8a4f161b7a8f960bead"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-206e82f-add-annotations-module-SNAPSHOT.jar",
          "size": 8776,
          "sha512": "82e253e8758f048392cdef2193eceb3c6c8e5379e21cb411a130c3115010f24d3ff33e98aa37a42dd5e06eb5b30aa7c1038d9de456f12aeab3aea9ce85a984ba",
          "sha256": "05bc2b5af51a646db2b82d158e2bc639ef6496e1f267b2ebc2186b7f40050cf1",
          "sha1": "5fbed158bca9c55c86297e9a95f270aa51df8cba",
          "md5": "ddf7b71b8b78c8a4f161b7a8f960bead"
        }
      ]
    }
  ]
}
