{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "028221d-bump-iphone16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-028221d-bump-iphone16.jar",
          "url": "antibytes-custom-component-028221d-bump-iphone16.jar",
          "size": 16177,
          "sha512": "25a4d3d6a7fcf2f6e821dd3879402891d6d04ff79ff58db8404b0f00c1c970225fffa4f5f35e0ace35460023b5d5a38f3eeb2d0551a1b9e45b7823808f7e1ed7",
          "sha256": "2a5a7d48a9703c9779cc08e8f165bf93d4194ac9128bebe3dc489cae3395b6bb",
          "sha1": "11694075d1103b4926c0044f3b8f5273fcf20951",
          "md5": "5bd2f2ac1a9bc3401b6b6754de5f13de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-028221d-bump-iphone16.jar",
          "url": "antibytes-custom-component-028221d-bump-iphone16.jar",
          "size": 16177,
          "sha512": "25a4d3d6a7fcf2f6e821dd3879402891d6d04ff79ff58db8404b0f00c1c970225fffa4f5f35e0ace35460023b5d5a38f3eeb2d0551a1b9e45b7823808f7e1ed7",
          "sha256": "2a5a7d48a9703c9779cc08e8f165bf93d4194ac9128bebe3dc489cae3395b6bb",
          "sha1": "11694075d1103b4926c0044f3b8f5273fcf20951",
          "md5": "5bd2f2ac1a9bc3401b6b6754de5f13de"
        }
      ]
    }
  ]
}
