{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/944b0af-bump-updates-SNAPSHOT/test-utils-944b0af-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "944b0af-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-944b0af-bump-updates-SNAPSHOT.klib",
          "size": 14402,
          "sha512": "6ccf77678659d6aa7a19d5804f04f15e1ffbb19da6f07aa411fc20dc8fb1d25a8ae544f9b5c38b895f230349b93bab81bfaa1679d7e96de9aea56cbb9c293f6f",
          "sha256": "2842406ee09b5960ca932349a9dd9f950c7a6972f99b0664f413038235605023",
          "sha1": "f2bdb6636ad7f58af21706f085e0000c009b3b7a",
          "md5": "2653a2e2afd8371c43126d57e0d0ac8a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-944b0af-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-iossimulatorarm64-944b0af-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "38f5cd69f0a668841acf6682333cb83f3d384511f365c336110581ac4357a929e2996ce9ef3c354807580e34ce6513f470ce606dafd07c870a3ca0a5bbdc572d",
          "sha256": "eca01b7729be8b9a664a7641f7d4105b35c18e301e3492530c58acd919ebf82e",
          "sha1": "b7a7c352227dae079088fd98004b575d7cc5ee63",
          "md5": "58bb2c0a717582cc849d7f0cc7cec3c0"
        }
      ]
    }
  ]
}
