{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/048cd7e-change-publishing-SNAPSHOT/test-utils-048cd7e-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "048cd7e-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-048cd7e-change-publishing-SNAPSHOT.klib",
          "url": "test-utils-js-048cd7e-change-publishing-SNAPSHOT.klib",
          "size": 12070,
          "sha512": "36aff9810a3ba67b89f098b4790842e44bdcb83130759835bcc3db15d8a464c60c58f166370a0f7c0b7c5361fd729be538bf5cac0c2a84068b4852e3251fef3a",
          "sha256": "cd7677b54d694ccf026e62e623bf012c7dcdb51114fa44e6fecbdfae6407f5b3",
          "sha1": "469053a3c25933da2dfb32de7a62cd02455e51de",
          "md5": "291c07f2376a5e7d24b9245b0471ad9e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-048cd7e-change-publishing-SNAPSHOT.klib",
          "url": "test-utils-js-048cd7e-change-publishing-SNAPSHOT.klib",
          "size": 12070,
          "sha512": "36aff9810a3ba67b89f098b4790842e44bdcb83130759835bcc3db15d8a464c60c58f166370a0f7c0b7c5361fd729be538bf5cac0c2a84068b4852e3251fef3a",
          "sha256": "cd7677b54d694ccf026e62e623bf012c7dcdb51114fa44e6fecbdfae6407f5b3",
          "sha1": "469053a3c25933da2dfb32de7a62cd02455e51de",
          "md5": "291c07f2376a5e7d24b9245b0471ad9e"
        }
      ]
    }
  ]
}
