{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "834b15a-add-doc-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-834b15a-add-doc-plugin-SNAPSHOT.jar",
          "url": "antibytes-dependency-834b15a-add-doc-plugin-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "0aa77472b99ac87f30e31aae2d6c5d9ab51e6e3841ec6c90f381eb4a3c017d769594efabb2fdfac06db4159777f4a2940f9c716c1632f9d5453608a329551947",
          "sha256": "1ada9cb301dddb0979e7b48010a77d0e9c6f6969561f83b15a8cd1911628e3fb",
          "sha1": "cb11b34d4d7da08f6af55fb705b9a6f020b02ce0",
          "md5": "96bfff76b8e13dc7901a243941865da1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "834b15a-add-doc-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-834b15a-add-doc-plugin-SNAPSHOT.jar",
          "url": "antibytes-dependency-834b15a-add-doc-plugin-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "0aa77472b99ac87f30e31aae2d6c5d9ab51e6e3841ec6c90f381eb4a3c017d769594efabb2fdfac06db4159777f4a2940f9c716c1632f9d5453608a329551947",
          "sha256": "1ada9cb301dddb0979e7b48010a77d0e9c6f6969561f83b15a8cd1911628e3fb",
          "sha1": "cb11b34d4d7da08f6af55fb705b9a6f020b02ce0",
          "md5": "96bfff76b8e13dc7901a243941865da1"
        }
      ]
    }
  ]
}
