{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/3d31034-change-settings-SNAPSHOT/test-utils-annotations-junit5-3d31034-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "3d31034-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-3d31034-change-settings-SNAPSHOT.klib",
          "size": 7049,
          "sha512": "e82644416b7480c0e1e297e8b55903278dd59dcbe80a4aba35c969a5d55202c1b0fcb1a6cf5fac3b3cee4945a57f44ba15fcfdd82d726015f92482799375c2a1",
          "sha256": "cf3ab81b6becab5c1e36f156abf3ed0cac8ea12777f2a8d7242ca76b377c13df",
          "sha1": "f2399643618d581a8b56df40dbfe051f03472ef1",
          "md5": "8e92a1493a8e1a501e163317c9ffd25e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-3d31034-change-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-3d31034-change-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b52fa750c219246461ce636b4040a80c9fe5014bdcc35099731844ff46d49971bf022850dd3ef7bb2044e8d0e8fd6e0b0444fc706aa68af4ee0aaddf5c74d588",
          "sha256": "9fcc8041f5a16f1ac5aee17979a7a722f6f3b7f7f953ab26d4d949c6942efe39",
          "sha1": "6af2c558ea86b148717ecdd4a6160e05e592ec33",
          "md5": "a7e94d749199dcf29fcd2ef7a08709db"
        }
      ]
    }
  ]
}
