{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "23321de-change-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-23321de-change-settings-plugin.jar",
          "url": "antibytes-configuration-23321de-change-settings-plugin.jar",
          "size": 67165,
          "sha512": "459e3125c4f4a14a39ea18708b25ef260bb8d1e65fcab99f1710a6dc9a4adf92dc0dd9ce074a8d380c0f12206f89a3e74c381eca350c02fa54056e7b21362886",
          "sha256": "6e2de961fe7d1fcbd9b9f5c6eab3b5bd33885c1c849ebc1f25c17c9f56a3707a",
          "sha1": "855f2a7677044274c47bcdadde60bfc4f732c0df",
          "md5": "080ea6c60f930b953a499c90de3ecfc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "23321de-change-settings-plugin"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-23321de-change-settings-plugin.jar",
          "url": "antibytes-configuration-23321de-change-settings-plugin.jar",
          "size": 67165,
          "sha512": "459e3125c4f4a14a39ea18708b25ef260bb8d1e65fcab99f1710a6dc9a4adf92dc0dd9ce074a8d380c0f12206f89a3e74c381eca350c02fa54056e7b21362886",
          "sha256": "6e2de961fe7d1fcbd9b9f5c6eab3b5bd33885c1c849ebc1f25c17c9f56a3707a",
          "sha1": "855f2a7677044274c47bcdadde60bfc4f732c0df",
          "md5": "080ea6c60f930b953a499c90de3ecfc6"
        }
      ]
    }
  ]
}
