{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "5bae153-change-api-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-5bae153-change-api-SNAPSHOT.jar",
          "url": "kmock-gradle-5bae153-change-api-SNAPSHOT.jar",
          "size": 42494,
          "sha512": "af3b5d72fbed68628820a349dbae4b650e8f75a2027dee127c2e7df2a66a9caf699ed0681c6fd1028ab903484331ca069364ac941d9c5477d0e53b5a6957c027",
          "sha256": "19366b74ee320b7e5b0fc6919339ed039e5cbee988be19d90a07f29b26994493",
          "sha1": "14fd8bb8733b08659430bcb62903690cd65e92aa",
          "md5": "644c2e3787d97d2bfe36046bd38fe8ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bb22160"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-5bae153-change-api-SNAPSHOT.jar",
          "url": "kmock-gradle-5bae153-change-api-SNAPSHOT.jar",
          "size": 42494,
          "sha512": "af3b5d72fbed68628820a349dbae4b650e8f75a2027dee127c2e7df2a66a9caf699ed0681c6fd1028ab903484331ca069364ac941d9c5477d0e53b5a6957c027",
          "sha256": "19366b74ee320b7e5b0fc6919339ed039e5cbee988be19d90a07f29b26994493",
          "sha1": "14fd8bb8733b08659430bcb62903690cd65e92aa",
          "md5": "644c2e3787d97d2bfe36046bd38fe8ce"
        }
      ]
    }
  ]
}
