{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f3c59f8-change-project-setup-SNAPSHOT/test-utils-ktor-f3c59f8-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f3c59f8-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "f6f81870dfac1413dbf70ae454eeb24f0209bb14ad6d218ee1fcf7ac7fe50933c280f556cbef0608dcd55924f7bc30b80c870e6cd7da6785e27fc7c55277f2f7",
          "sha256": "21595b26245720c90ab90ad9a2308dfdfee1207230ed9280dbdbdbad0b29ab04",
          "sha1": "ebe199924c578695dcd5418d58b5c465ba9c2de7",
          "md5": "e950e06f9e2a165913a0e814f50a939b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "f6f81870dfac1413dbf70ae454eeb24f0209bb14ad6d218ee1fcf7ac7fe50933c280f556cbef0608dcd55924f7bc30b80c870e6cd7da6785e27fc7c55277f2f7",
          "sha256": "21595b26245720c90ab90ad9a2308dfdfee1207230ed9280dbdbdbad0b29ab04",
          "sha1": "ebe199924c578695dcd5418d58b5c465ba9c2de7",
          "md5": "e950e06f9e2a165913a0e814f50a939b"
        }
      ]
    }
  ]
}
