{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "2ac0b7d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-2ac0b7d.jar",
          "url": "antibytes-dependency-catalog-2ac0b7d.jar",
          "size": 261,
          "sha512": "06de392bbae215d26bb83a9f8e1d8779a3f7ffc5937b906a30a7e18a3841e969668b80abcaf40cd006b3a8b9bf07aeb38aa2902ad6842177662c0f182a931f90",
          "sha256": "cfe9c2ea8f6345690688577c53b18681f018ce0e658006d5df705fc0b6665607",
          "sha1": "702ba05ea879e3125cc80650e53d11b6d79b2363",
          "md5": "88f88c046af5846311075f0f8b54632d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-2ac0b7d.jar",
          "url": "antibytes-dependency-catalog-2ac0b7d.jar",
          "size": 261,
          "sha512": "06de392bbae215d26bb83a9f8e1d8779a3f7ffc5937b906a30a7e18a3841e969668b80abcaf40cd006b3a8b9bf07aeb38aa2902ad6842177662c0f182a931f90",
          "sha256": "cfe9c2ea8f6345690688577c53b18681f018ce0e658006d5df705fc0b6665607",
          "sha1": "702ba05ea879e3125cc80650e53d11b6d79b2363",
          "md5": "88f88c046af5846311075f0f8b54632d"
        }
      ]
    }
  ]
}
