{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-setup-SNAPSHOT/ktx-datetime-0.4.0-fix-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosarm32-0.4.0-fix-setup-SNAPSHOT.klib",
          "size": 34649,
          "sha512": "74f96655baaa671df03f409fa4615ee5b56274304c5719df43d32d63b7beb1085580bf213c8f77163c108b2c2b928e771bc5cbfdeeda7088798e4298da51705d",
          "sha256": "63fa859eaa1e7df2c10e041cb769188c617e1c434eb3c344c14745eb2774eafb",
          "sha1": "cca7d15eff7122af3c04812f87dd1bbdc77619dd",
          "md5": "5d840a4a39d4b3507e2ad7efdce05ae4"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosarm32-0.4.0-fix-setup-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosarm32-0.4.0-fix-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "63f6492e1d9665f06c4a044f355c56aa8319d0fcb6a681b6aadcf164b8872045048563e1882987048237e01ec8d6a5b889a3a9823b9ed89da5b54cc13e721992",
          "sha256": "42a65e7b429fa08e84bde63469dd66a8b368dece6b401b9f1fbd59b111ab009f",
          "sha1": "a6edf59a556ac189844d1d5ce5231d278ffe242a",
          "md5": "fa23eb0ee139fb45441aa8d0e8706499"
        }
      ]
    }
  ]
}
