{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-add-reciever-methods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "size": 34744,
          "sha512": "ab6083b4f77fa003e22142e5c41663d6c47b5ef14584fda6f97d7f6b9539c61fb4d60f3c01b0a0b4f6108b9a4da92b327f54b5e1de5fd75e23d3c26e565c3b77",
          "sha256": "5c3175675e2e0b86852ea581150bb387577018c3dff5f9fc40c9536a5578a1d0",
          "sha1": "9ffa0ba544b34502158da1291ff399df978a59b9",
          "md5": "e00ee489aa5c83ae2e987a6e33ba2df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "size": 34744,
          "sha512": "ab6083b4f77fa003e22142e5c41663d6c47b5ef14584fda6f97d7f6b9539c61fb4d60f3c01b0a0b4f6108b9a4da92b327f54b5e1de5fd75e23d3c26e565c3b77",
          "sha256": "5c3175675e2e0b86852ea581150bb387577018c3dff5f9fc40c9536a5578a1d0",
          "sha1": "9ffa0ba544b34502158da1291ff399df978a59b9",
          "md5": "e00ee489aa5c83ae2e987a6e33ba2df5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "984a32b6193bef224201787a3dd2ddb587494cdef72210e49705bf8494e1c10e1e7f9938384fb301645013610b40276e2b6e5e2a54932b443cbec8146343fb51",
          "sha256": "5c34e9a0929a81c80ea3030a034dfe8d673f29035e1d3e1433be117129657853",
          "sha1": "9510515d08c04f3f7071b54e689653fa797676e3",
          "md5": "0870852fdf1b72ae0adb64191c805402"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-add-reciever-methods-SNAPSHOT-sources.jar",
          "size": 9402,
          "sha512": "67aca15a59dd2a4b3bd4c093c47eb2bcec97003533786de778390f17c04aa31a00309d53743b4d593be92e2a546c2c46f8c5b546ea3696e3039ee8291deac3c7",
          "sha256": "6e4c78522df2878979eb04fe12005138dd562ff7b0fb6b5d464381239489d3f5",
          "sha1": "193fac4bda053d892abb75d5bfbb05dc59311c2f",
          "md5": "5b3cfa7ebefd02de702e9ad5619c6e47"
        }
      ]
    }
  ]
}
