{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT/kmock-0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosx64-0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT.klib",
          "size": 202480,
          "sha512": "a9b7bb5c9b68b1497a1b23b1c3ec2733c094c64dbeafcc9ed02276b8193c2f9abe9a01dcfc042e33c2fdf452999306833b3382d82972a4c6616fd761584ee887",
          "sha256": "409aa2c045cbf367e11265cdc657c7ebaebfc4a46ffe07d4fa527bf20b4b85bf",
          "sha1": "b5ce09c0329dd6c749c5f86dd1ee255490c44ddc",
          "md5": "b203fde22c21670a19904dff468222c6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosx64-0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT-metadata.jar",
          "url": "kmock-iosx64-0.3.0-rc02-bump-updates-1.7.10-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b01f3fb00ca3d1ba6a461875d83f42c3eb084b8f29f2acebf9eb2d468b42e4634d4aacd44778501bccf8aca71219e54930ad7afa8a771d9bb8751eadbc33e909",
          "sha256": "da6f9854ee93f5d7e77f0adda7d3887a8487ef9393c977be25b5e2d1fbbe20b5",
          "sha1": "a11c5acb6c9270c922c3c3b3da0cf990d4186edd",
          "md5": "1fa67ed406702f51c9f00372b8d47d5b"
        }
      ]
    }
  ]
}
