{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-kspy-generation-SNAPSHOT/kmock-0.1.1-fix-kspy-generation-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-kspy-generation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-kspy-generation-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-kspy-generation-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "ebc472ee0b2a408be61297367f37268e094bd4850e63ece064424b44cbf6e4de2ffbc79fefee43eb8ce2c380852c3da68f2e9cf565fb6136f421e30adba2d58e",
          "sha256": "7d7998d13411f4ebb75429d407e2db123c48949b6d26fae2e6eb08465d1c26b1",
          "sha1": "f7df53409ac794c99be697fc462b8fc8706dad07",
          "md5": "a317272f494fdc9063fb4b9876d8ced7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-kspy-generation-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-kspy-generation-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "ebc472ee0b2a408be61297367f37268e094bd4850e63ece064424b44cbf6e4de2ffbc79fefee43eb8ce2c380852c3da68f2e9cf565fb6136f421e30adba2d58e",
          "sha256": "7d7998d13411f4ebb75429d407e2db123c48949b6d26fae2e6eb08465d1c26b1",
          "sha1": "f7df53409ac794c99be697fc462b8fc8706dad07",
          "md5": "a317272f494fdc9063fb4b9876d8ced7"
        }
      ]
    }
  ]
}
