{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.2.0-fix-kjs-plugin-invocation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.jar",
          "size": 56563,
          "sha512": "e6df686179f72e43bab288bd1b59641917198bb72302a9f325f52c04fd4e4c233f3807a68f44e7170c1398b7e9d98c3e11218868bc844c7b2219fdc4b359d430",
          "sha256": "341ee49a7b658c21f900948780894f36ae857cc7a262178958083f0a3bdaaa9c",
          "sha1": "d95b8e6b7b3e910453947706d2113492fd4d9e6b",
          "md5": "4e2f2d5c2a14943e0a03061aeb1e6edf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.jar",
          "url": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT.jar",
          "size": 56563,
          "sha512": "e6df686179f72e43bab288bd1b59641917198bb72302a9f325f52c04fd4e4c233f3807a68f44e7170c1398b7e9d98c3e11218868bc844c7b2219fdc4b359d430",
          "sha256": "341ee49a7b658c21f900948780894f36ae857cc7a262178958083f0a3bdaaa9c",
          "sha1": "d95b8e6b7b3e910453947706d2113492fd4d9e6b",
          "md5": "4e2f2d5c2a14943e0a03061aeb1e6edf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "d00585323fd7201acb95193ac23d7538fc13d6ddfaf4c28a70569ce1c565ba11d072c25c59427df88b8fad632f7e5ca8ded02c81c9737c5632c7b2bd18da17d9",
          "sha256": "902cf9f96d8be8127d1bad68456813da139aadad45a06ae6c16191c2ffe5f130",
          "sha1": "394989fdf617ce38f716c13cfa241d1af80b7ce1",
          "md5": "af378722e69b5cce16aec87b108634c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.2.0-fix-kjs-plugin-invocation-SNAPSHOT-sources.jar",
          "size": 11891,
          "sha512": "d3da463f61bead4804ea3f312a018d3092772ef5a45c87ddfa4f741099e1d0ddc6fd7e3386d382ee8026f9280eaf612c1415aa28f655410b902aff486f472952",
          "sha256": "beeae407374c5741ac14ff4eb46dece88a691b0a1f71eedfde1142c0b3e4cc50",
          "sha1": "53059d40b5bf1f7fa6a8a18b96295f59b0425a45",
          "md5": "85cb501dafe99b77e1947259258875aa"
        }
      ]
    }
  ]
}
