{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit4-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "3b5816ef468996f6c3021bf1efb495da26cde2bc962a8072fdfe58124a57199c588f3d7103d98292da0dab76d2945e414cea24b2b936e259995647cb0c8e14c0",
          "sha256": "af5aeeae22a73c34ba237bef720e31b05c9b3010c9d2c68e5188e9afc2096a2b",
          "sha1": "035b2a7567e6edcf434c5596c73b6b8a731aa246",
          "md5": "13f2e4a238de41d5da0437298b8182e2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-13f09a8-add-more-sources-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "3b5816ef468996f6c3021bf1efb495da26cde2bc962a8072fdfe58124a57199c588f3d7103d98292da0dab76d2945e414cea24b2b936e259995647cb0c8e14c0",
          "sha256": "af5aeeae22a73c34ba237bef720e31b05c9b3010c9d2c68e5188e9afc2096a2b",
          "sha1": "035b2a7567e6edcf434c5596c73b6b8a731aa246",
          "md5": "13f2e4a238de41d5da0437298b8182e2"
        }
      ]
    }
  ]
}
