{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/5290833-add-number-SNAPSHOT/fixture-5290833-add-number-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "5290833-add-number-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosx64-5290833-add-number-SNAPSHOT.klib",
          "size": 48935,
          "sha512": "569ebda0d12840ea8c54b8ac4406eaaa6c97c12d968aca148ebeb2898ffb4c23f8ebd94e15395e62f62154491e069cee1b32fd2009a72ca1f9ab1d17aa18b469",
          "sha256": "8a2832044dc4130e2f7b555159651dfd754c2ce3158730b40eac2d374b17d8d1",
          "sha1": "dda74ba69ca9033ed1cee1818803ad6a1f0f5168",
          "md5": "a5f9375f6eaa92e11ddf7ad2eb7f034b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosx64-5290833-add-number-SNAPSHOT-metadata.jar",
          "url": "fixture-iosx64-5290833-add-number-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "132f0e29157c179f262bc344f35ada6834626efc2b26c93c334ea36095b3122328bc2f01feb50c3545dc409c4ee8687ad547c2391c62bf1a23f55c4de3b022eb",
          "sha256": "ce7de73a1a9af2b51012f24f3f83c600dc27291af87c81b51aed6b639a144c31",
          "sha1": "88ae7378a398fb756d46fa11e141a7fc82bf3b34",
          "md5": "6afd7393b263d2dbffec2f425d467019"
        }
      ]
    }
  ]
}
