{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvosarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 34658,
          "sha512": "a07b700413178c5d02f830af717888acc42e643b3efac840d2e0081cb78fc9e687eff024cc2b38cb931944e5519a7ee6181c04cc870b799a924aab6b0afb978d",
          "sha256": "732a4f95f13cf5fc3f9e9b5d58ae1337bf4d51220f1bd5f03ea7286116f33ca0",
          "sha1": "0d50d91e8870a8c7bf241bafb05b531db0d86e0b",
          "md5": "91cadffadf1379e3fd77b1417d3025b1"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e7b08915d05ef7f44731aad9aa7218cb8e8bdca00516091f96f80e3544e81564d07d1bd298019446d92b2e10fd2aa3a15b61cc259c332192c39436a04498b6db",
          "sha256": "364c0cf91793cc155d7e017be62f828d51717303ed13f30267441c867376af40",
          "sha1": "374e601b74688bd64ec83f45f206aca66984dfc5",
          "md5": "33048305d1945fd21ada348daa86232a"
        }
      ]
    }
  ]
}
