{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/f891629-bump-antibytes-SNAPSHOT/test-utils-coroutine-f891629-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "f891629-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-f891629-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-f891629-bump-antibytes-SNAPSHOT.jar",
          "size": 12122,
          "sha512": "18a42e1136d157bbe25d70d2630381196d56ad5c1683db7661badba6a36ed6a8ea776f737e2a581cfb395df8a9b0cb02e70f0f7cd67bbd47094eefd7cb178048",
          "sha256": "8b9c7d3ae60124e6447ac97699ae6d6a1d373e234143fa566c312ae7011a5a87",
          "sha1": "b6c21259af5c08828ebae451130b8c5da764322d",
          "md5": "2152e659bee9abdb970624858cb14a14"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-f891629-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-f891629-bump-antibytes-SNAPSHOT.jar",
          "size": 12122,
          "sha512": "18a42e1136d157bbe25d70d2630381196d56ad5c1683db7661badba6a36ed6a8ea776f737e2a581cfb395df8a9b0cb02e70f0f7cd67bbd47094eefd7cb178048",
          "sha256": "8b9c7d3ae60124e6447ac97699ae6d6a1d373e234143fa566c312ae7011a5a87",
          "sha1": "b6c21259af5c08828ebae451130b8c5da764322d",
          "md5": "2152e659bee9abdb970624858cb14a14"
        }
      ]
    }
  ]
}
