{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f3c59f8-change-project-setup-SNAPSHOT/test-utils-annotations-junit4-f3c59f8-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f3c59f8-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "493d3129abc783f86c145706ab71d76e628086bb674bc20a0a3640738ba511418d7fdc86da66d6173a727a18b4de73e273f729dafc0b0d7bdbe7afdd4c126062",
          "sha256": "395635b8a970b0db382f7657a3f470656490d80a5199990934366ec2dc89a777",
          "sha1": "0e6108cd78f2e7072c0be5bc94e208db8b3e2722",
          "md5": "6e1d1c0cc3b3358e9487b47ff0fabf36"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-f3c59f8-change-project-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "493d3129abc783f86c145706ab71d76e628086bb674bc20a0a3640738ba511418d7fdc86da66d6173a727a18b4de73e273f729dafc0b0d7bdbe7afdd4c126062",
          "sha256": "395635b8a970b0db382f7657a3f470656490d80a5199990934366ec2dc89a777",
          "sha1": "0e6108cd78f2e7072c0be5bc94e208db8b3e2722",
          "md5": "6e1d1c0cc3b3358e9487b47ff0fabf36"
        }
      ]
    }
  ]
}
