{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f8d6e50-bump-workflows-SNAPSHOT/test-utils-annotations-junit4-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 11474,
          "sha512": "3b4b536cdad4219d7b95390a21d49502b432ae1861bf807a154ada16c16c4557cab3ff29354af0f55faa4ae3eba89c359e521c0d29c5ab75aa6b01f4742a00ab",
          "sha256": "0d1644cd3220707f02b9838ee2bc02ecf0e929ef8952b4c1ea419c1a54c6a309",
          "sha1": "5f31a3a8565676168d35d02994ca4751e1294abe",
          "md5": "7f42d9a50c67ea6d3f69543f4298f6d0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-watchossimulatorarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-watchossimulatorarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "73d0faaf929f247804b92836f45354e7cb7d7dd6c94d3c96b4b5522339783b840c3c1e69b9e3e4ec0170c081ae33fa6110a2a6c283d84849a5e669e322dd9f9c",
          "sha256": "ad781dce09989cbb2c9207a72157e7c021cedcae38d9d48ac5cd13eec86f75bf",
          "sha1": "608dc4429b60e36fd61a2135ff853b3d6ba43a0f",
          "md5": "d140a58bbc76bf1f753f7c2a162b5cc0"
        }
      ]
    }
  ]
}
