{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "6941575-add-antibytes-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-6941575-add-antibytes-settings-plugin.jar",
          "url": "antibytes-configuration-6941575-add-antibytes-settings-plugin.jar",
          "size": 67165,
          "sha512": "15c5313ebe6f398af3024f66455940a7d9071b286811c9bae24b5e72dc4d87978a3bf8e5365ffedf5a63a16a0c16663d6f46a0c09e464c833bc366c1dee1329c",
          "sha256": "13527290a13600a8635b573b02f52baa776680dfaa5a464c487c8ea5e901881a",
          "sha1": "0818c1b25a2c1840fe640cc7f1032b33a82a4f15",
          "md5": "f7b53af38224faf44933dc7cbb356b2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6941575-add-antibytes-settings-plugin"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-6941575-add-antibytes-settings-plugin.jar",
          "url": "antibytes-configuration-6941575-add-antibytes-settings-plugin.jar",
          "size": 67165,
          "sha512": "15c5313ebe6f398af3024f66455940a7d9071b286811c9bae24b5e72dc4d87978a3bf8e5365ffedf5a63a16a0c16663d6f46a0c09e464c833bc366c1dee1329c",
          "sha256": "13527290a13600a8635b573b02f52baa776680dfaa5a464c487c8ea5e901881a",
          "sha1": "0818c1b25a2c1840fe640cc7f1032b33a82a4f15",
          "md5": "f7b53af38224faf44933dc7cbb356b2a"
        }
      ]
    }
  ]
}
