{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-project-configuration-SNAPSHOT/core-0.4.0-change-project-configuration-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-project-configuration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0-change-project-configuration-SNAPSHOT.klib",
          "size": 110198,
          "sha512": "73826a3e4475fea307e487074fbe1f069ad0d001c87e48d2d2ecf2bb3cb2399efcb2e35964ee78be1b0ea65d3145273fcb26b9d7a0cff2c6bc6f6a9082e179b5",
          "sha256": "c56da9bb532caf18e1d71687bfdf8b5207a97a716befe0b589092605992580fc",
          "sha1": "25789a733c44b1d763db79f108203694980f1f5c",
          "md5": "2aabc1b5ef9e65eb15ed392f2abca7ec"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-change-project-configuration-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.4.0-change-project-configuration-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "206686637c2c47d292c75b41fcb0febc667f583378589247370e9f7ac565ef71740d28a93932bbce198b415ae304f07113450300022fcb971db0eef16b279dfe",
          "sha256": "d5c9ab31771091447417ee989bcceecd0c31684c92835ca779bbccdeaf3242c1",
          "sha1": "79ec151c1f59fbbfbac9039c4e1f6ba7a526d570",
          "md5": "c76c3b5f46eeea39cdea819810733e6f"
        }
      ]
    }
  ]
}
