{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.klib",
          "size": 32815,
          "sha512": "4fe06d3c62af18070a7cfa5a583d433e3139001bdfee0634759f2173eef59dbdcfeb92cf73874b43fddc05fe0aba5afdd460e8264c26cc9e6345b80bbb02bb16",
          "sha256": "eb9ece9e15ceac3a88e4f105c9b1fe90c496ca0ccc30b7dbc1c80b9768f44505",
          "sha1": "75389e64bb69be17aca362cd9ffd023a84b76238",
          "md5": "fb8e6af45c8838c679174c6b903aa42f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT-metadata.jar",
          "url": "test-utils-fixture-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "75e0c80cdda37ac3305a82d54a4fbf409a9db87da34b80edcbfbc7a952ccd703af15b4329e00d86fed1a054ee63ce66cb737d0c7db33ad62b37ca43b8945a009",
          "sha256": "9c5820ecc39be6ca0aaab6c2e6aa551d4d5755cfbb0cacbe40151cc2a6cda136",
          "sha1": "30c77f48a00e352c8dd2bd3264e029cd1392390c",
          "md5": "f3fcec5432f4bfbdeb6e11d891bac265"
        }
      ]
    }
  ]
}
