{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f27ca7d-bump-danger-SNAPSHOT/test-utils-f27ca7d-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f27ca7d-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-f27ca7d-bump-danger-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "aba150da9063e0cab87134f5657ddc8d946352788c3718d0999cfb2b9547a705bb1db0fdef9422bd447addea193841e555afca65bfa0017c88fde279059629a9",
          "sha256": "f4d2e90e508a88013f7cedb04bc5659075f4e0455e5c2c64f937aaa247942334",
          "sha1": "c428aca5d152271188edbf7d5e04508d6eadc770",
          "md5": "8dee14d4b75308e3a3b5553ba0aa9271"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-f27ca7d-bump-danger-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "aba150da9063e0cab87134f5657ddc8d946352788c3718d0999cfb2b9547a705bb1db0fdef9422bd447addea193841e555afca65bfa0017c88fde279059629a9",
          "sha256": "f4d2e90e508a88013f7cedb04bc5659075f4e0455e5c2c64f937aaa247942334",
          "sha1": "c428aca5d152271188edbf7d5e04508d6eadc770",
          "md5": "8dee14d4b75308e3a3b5553ba0aa9271"
        }
      ]
    }
  ]
}
