{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-multi-type-return-values-SNAPSHOT/kmock-0.1.1-fix-multi-type-return-values-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-multi-type-return-values-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-multi-type-return-values-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-multi-type-return-values-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "a4c6865fba720b53e5039d3c1fc0c4e943da1b8d4cb97b8a41693875072c0a8c8dd4507e5d6a2ccf182e3c47df378256a388f205d872b8f1d2d306fa7295d9ce",
          "sha256": "536d343e56905f969c1c75a7473d8c9dc21db94f431ad7c1c2dfc524b4035190",
          "sha1": "284bff02d105e5513755dc1963ecaa8db3da537e",
          "md5": "821a1c039253046c8f1622ba6f78686a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-multi-type-return-values-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-multi-type-return-values-SNAPSHOT.klib",
          "size": 168254,
          "sha512": "a4c6865fba720b53e5039d3c1fc0c4e943da1b8d4cb97b8a41693875072c0a8c8dd4507e5d6a2ccf182e3c47df378256a388f205d872b8f1d2d306fa7295d9ce",
          "sha256": "536d343e56905f969c1c75a7473d8c9dc21db94f431ad7c1c2dfc524b4035190",
          "sha1": "284bff02d105e5513755dc1963ecaa8db3da537e",
          "md5": "821a1c039253046c8f1622ba6f78686a"
        }
      ]
    }
  ]
}
