{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-booleanArray-generator-SNAPSHOT/core-0.2.0-change-booleanArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-booleanArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-change-booleanArray-generator-SNAPSHOT.klib",
          "size": 73902,
          "sha512": "bdaa0b0b68ca38646ca347cf2811d199bfd6c3256f77aae13ce3e8f9efbc743e0a59fde82606c9180fb45af08cd06785ebecfe95fec89e15a0b74645d789fdc0",
          "sha256": "fbefb82c583950cdecc7172016fc6eabaf3ed1cde451466d4a4ded180231c3a5",
          "sha1": "b31ccd8638e3d533f53d2c66c8a93ec8a767c67e",
          "md5": "c5a900ac2e3e9a1fe02a1ada15a38e28"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-change-booleanArray-generator-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-change-booleanArray-generator-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d882dfb429198b4a67c43b4bddcd92f05d27c9d9a72dd2b9e4634e9a66c4e9fc68edb9a69c2558657cdacf8e9dab587303cd44010944567af89fc15bccc3b081",
          "sha256": "63db910a6140b0d802808f0a47b231aad87f31da81614a6b56fe75decae737a2",
          "sha1": "a95c21c6a18b462800002dd87dd6aea19c035e6e",
          "md5": "bbb6dbb7b17fd9d41057418b0f218c36"
        }
      ]
    }
  ]
}
