{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/d3f31b1-fix-single-sources-SNAPSHOT/kmock-d3f31b1-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "d3f31b1-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-d3f31b1-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-d3f31b1-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "77719dacc956b02b27ac1224b9d00f32ee4ad4a4a72adefbae3a80030868e56aeb6a820b03c6eaff10cad208183801a46233fa4d17d4cc6caf926f7795266efe",
          "sha256": "5e10649fd63d3740cfd547a3418fa6394bd476180e40d4e28d5aa0a706f210b9",
          "sha1": "1ad9b8790eee107adcf48b9bf2ad74bd12e1dd6d",
          "md5": "56b4a76307a489b83e743adf34faa320"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-d3f31b1-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-d3f31b1-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "77719dacc956b02b27ac1224b9d00f32ee4ad4a4a72adefbae3a80030868e56aeb6a820b03c6eaff10cad208183801a46233fa4d17d4cc6caf926f7795266efe",
          "sha256": "5e10649fd63d3740cfd547a3418fa6394bd476180e40d4e28d5aa0a706f210b9",
          "sha1": "1ad9b8790eee107adcf48b9bf2ad74bd12e1dd6d",
          "md5": "56b4a76307a489b83e743adf34faa320"
        }
      ]
    }
  ]
}
