{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "51c1f77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-51c1f77.jar",
          "url": "antibytes-coverage-51c1f77.jar",
          "size": 133730,
          "sha512": "702bddf0df6f0bcc5fec1e8c8bf5a7b793cfbc7ee6a9330262559f5f0b7cebeb1036f7783042525c0b4f33dd4017f300f37891ce55af88dad637f5aea6c4d6ea",
          "sha256": "928463ea592458d6d3ae9d0ecd1ea1d2c46298b217845183d0176761e86a4b5f",
          "sha1": "67a39556aea57a7bf24d33d609878fcb05ad1006",
          "md5": "c324a6b949427bac8bb7cc6625fd6694"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "51c1f77"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-51c1f77.jar",
          "url": "antibytes-coverage-51c1f77.jar",
          "size": 133730,
          "sha512": "702bddf0df6f0bcc5fec1e8c8bf5a7b793cfbc7ee6a9330262559f5f0b7cebeb1036f7783042525c0b4f33dd4017f300f37891ce55af88dad637f5aea6c4d6ea",
          "sha256": "928463ea592458d6d3ae9d0ecd1ea1d2c46298b217845183d0176761e86a4b5f",
          "sha1": "67a39556aea57a7bf24d33d609878fcb05ad1006",
          "md5": "c324a6b949427bac8bb7cc6625fd6694"
        }
      ]
    }
  ]
}
