{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-linuxmipsel32-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 7093,
          "sha512": "a4e139c749557af3a9c0318f16d1472c5194b568a4da255428331a97d6edd1a16dbe1483a10aa76925cd67805fc7f8b54124e05bb19ff2d188c36fd07fd02281",
          "sha256": "d58d0ab28c6285240e261bf662435c7489454f7e4abcdb36d210ce169eadaae1",
          "sha1": "dd5e4e7d7636f0a1da69892386f7ffd46c3531e5",
          "md5": "b535b745b57329f17bf62aff37fb94e5"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-linuxmipsel32-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-linuxmipsel32-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b43af5521e0a7766c739a6903c747ec280f12045199deff8608411455d42549980a943f911940fadbc98b0921b25530b687e6f2c2408a078b1d17e6f9de425ab",
          "sha256": "574e74ecf4dcf3953a2502cdca22915c63434b8af8bc3f2d16355d10a255d483",
          "sha1": "451567b63e418f3cf499980674fb805e5a829c81",
          "md5": "7e2ceb4c340c3ed2c7ec8aa6b1c164ae"
        }
      ]
    }
  ]
}
