{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/ac86912-fix-ktor-publishing-SNAPSHOT/test-utils-ac86912-fix-ktor-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "ac86912-fix-ktor-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-ac86912-fix-ktor-publishing-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "466ebcdb36645a4a2c168440416c6b39e5df3dddac2131de436f51ae2182283aaed23008f92eb4fd1da5150b3c01011c0d21054fb59a627662105d35d76e138f",
          "sha256": "4e222cc99721e4525ec002da0f7e0ba52b2b953ea65f20653a9c4dfe43312851",
          "sha1": "e7c028a084b4bd6cb991a5df37af50c6399aaf9d",
          "md5": "a8885ca36512e429d10e81382a0f150c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-ac86912-fix-ktor-publishing-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "466ebcdb36645a4a2c168440416c6b39e5df3dddac2131de436f51ae2182283aaed23008f92eb4fd1da5150b3c01011c0d21054fb59a627662105d35d76e138f",
          "sha256": "4e222cc99721e4525ec002da0f7e0ba52b2b953ea65f20653a9c4dfe43312851",
          "sha1": "e7c028a084b4bd6cb991a5df37af50c6399aaf9d",
          "md5": "a8885ca36512e429d10e81382a0f150c"
        }
      ]
    }
  ]
}
