{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/b89fd7d-add-array-byte-SNAPSHOT/fixture-b89fd7d-add-array-byte-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "b89fd7d-add-array-byte-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosx64-b89fd7d-add-array-byte-SNAPSHOT.klib",
          "size": 47362,
          "sha512": "3855b3cd1266fb5ce5cbccfbf861b5ae816695cec2a2828ac2de14396fe5c143fe8a3c518fd42ef60ec3e0f7460d3bc1ca1df963b6ecc4192a1938c88d75f3c0",
          "sha256": "afbfcc81a3bd073373b17cb56d3002ecb7009d6fd4eb6e4bffe6756340aed23c",
          "sha1": "15025e6185516f34cf38a90e7975244fc8f4b75e",
          "md5": "139ca3fa78d7926f8ae2ac22726950fa"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosx64-b89fd7d-add-array-byte-SNAPSHOT-metadata.jar",
          "url": "fixture-iosx64-b89fd7d-add-array-byte-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0023b5baa637a9d5ad78f297986487b077dfb2e4046e319da9c467e82e3bdf573b855d1b56602458015807a971d6fbac0d96cacb121de805b30c118093c9d9a3",
          "sha256": "4a40434f9cdf6c25bc4250bf9050877b4945aeb4765ce7cd3c1a6a1d1e5ed340",
          "sha1": "54cbe5fdcf77b6de22a5fcbafa1fb22b1f2da09f",
          "md5": "5941f168bda062dd41c38f380bd0c463"
        }
      ]
    }
  ]
}
