{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-floatArray-generator-SNAPSHOT/core-0.2.0-change-floatArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-floatArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-change-floatArray-generator-SNAPSHOT.klib",
          "size": 74394,
          "sha512": "b77f9f0a6d1a3156549120c599a8259c92f49ff1167caccbe08d52b1e259607a368f92903882b0c571570b71b317fbe9cbd14100f2e3be3caf56d246b5656bda",
          "sha256": "26f648de622252345d480c106bd52c81248836c37ab3e82db493c805eaf402a1",
          "sha1": "e862fa6d3a9b3cf1a51011654787781640289179",
          "md5": "8cd771b6ca12f646fc55dec1a4e6468c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-change-floatArray-generator-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-change-floatArray-generator-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "39a014488642f757cbeca8ded9cb57144ac187bb59b8d38c1d425a7dc980e131a2034543d0e018c58aa93d53cc109938ee1c0f20e287b2bb325ce7633b113ca9",
          "sha256": "b89fc346eaf1358b731aa573b9e9b32273136ab6bc869e9f1e3bd2099dba3795",
          "sha1": "addbf179bec3fd55845e157f2b72aed8addf8c40",
          "md5": "20fda28015bb54b4e5412291b6fd1e7c"
        }
      ]
    }
  ]
}
