{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f6669bd-add-native-SNAPSHOT/test-utils-f6669bd-add-native-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f6669bd-add-native-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-f6669bd-add-native-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "50b72abf261620a6e6f38786e1cbf9d3ba84abc711752592b363c5629916dd700fc42bee7ae0669d0fad1ff33910c61e2a7cc91a36d2e93515bd0f180c84b1a5",
          "sha256": "a234a8e6d5565130ee5966d10cae5d854591c90877d7700456e18ac6ae678f11",
          "sha1": "edd5d82411f47c1f7e80208d27b0cff083d74339",
          "md5": "b29c5332945a91157c338e1ad104a5cd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js.klib",
          "url": "test-utils-js-f6669bd-add-native-SNAPSHOT.klib",
          "size": 11900,
          "sha512": "50b72abf261620a6e6f38786e1cbf9d3ba84abc711752592b363c5629916dd700fc42bee7ae0669d0fad1ff33910c61e2a7cc91a36d2e93515bd0f180c84b1a5",
          "sha256": "a234a8e6d5565130ee5966d10cae5d854591c90877d7700456e18ac6ae678f11",
          "sha1": "edd5d82411f47c1f7e80208d27b0cff083d74339",
          "md5": "b29c5332945a91157c338e1ad104a5cd"
        }
      ]
    }
  ]
}
