{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "c6e91bd-change-link-target-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata.jar",
          "url": "banana-i18n-c6e91bd-change-link-target-SNAPSHOT.jar",
          "size": 13811,
          "sha512": "eae6bac9c5cc29950cbcce38ecdfe6fd3b866c13f733cc9c3824c24f1b044c77c2e6b13c04147635d6bd269ead882449d1c7110c16e1c4c18ee4fc1b0f77edd8",
          "sha256": "10cc4a58effb0d550121216c30fde2b34a8f3515e65d721a7c7f0d9135c6968d",
          "sha1": "45559b2bd079a89f197309fbd444eacf04950449",
          "md5": "ea86267cb511f8a4a86678754a49a6c5"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/c6e91bd-change-link-target-SNAPSHOT/banana-i18n-android-c6e91bd-change-link-target-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "c6e91bd-change-link-target-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/c6e91bd-change-link-target-SNAPSHOT/banana-i18n-android-c6e91bd-change-link-target-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-android",
        "version": "c6e91bd-change-link-target-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/c6e91bd-change-link-target-SNAPSHOT/banana-i18n-jvm-c6e91bd-change-link-target-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "c6e91bd-change-link-target-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/c6e91bd-change-link-target-SNAPSHOT/banana-i18n-jvm-c6e91bd-change-link-target-SNAPSHOT.module",
        "group": "tech.antibytes.banana-i18n-kmp",
        "module": "banana-i18n-jvm",
        "version": "c6e91bd-change-link-target-SNAPSHOT"
      }
    }
  ]
}
