{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "f2ac2eb",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-f2ac2eb.jar",
          "url": "antibytes-coverage-f2ac2eb.jar",
          "size": 128528,
          "sha512": "58945a18627c86854d62df39d52568a6268b121e6be7a31b029f6e107241a87ba948bfc3bb6bdd6e63da5e7c3840fc1c9f939e35d96cbe7fedae84052bcb79d0",
          "sha256": "1b8496a30ffa4ff6cb965692063ca31fedc886db8e32b8e84c829924d76523fe",
          "sha1": "44c5201f972c867c235b78089477eee24167ecd7",
          "md5": "b6ebea4052f155d309596bd9ef074b4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f2ac2eb"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-f2ac2eb.jar",
          "url": "antibytes-coverage-f2ac2eb.jar",
          "size": 128528,
          "sha512": "58945a18627c86854d62df39d52568a6268b121e6be7a31b029f6e107241a87ba948bfc3bb6bdd6e63da5e7c3840fc1c9f939e35d96cbe7fedae84052bcb79d0",
          "sha256": "1b8496a30ffa4ff6cb965692063ca31fedc886db8e32b8e84c829924d76523fe",
          "sha1": "44c5201f972c867c235b78089477eee24167ecd7",
          "md5": "b6ebea4052f155d309596bd9ef074b4f"
        }
      ]
    }
  ]
}
