{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.0-fix-publishing-SNAPSHOT/kmock-0.1.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.0-fix-publishing-SNAPSHOT.klib",
          "url": "kmock-js-0.1.0-fix-publishing-SNAPSHOT.klib",
          "size": 136190,
          "sha512": "a6e54b2d913d803588deeedfc876314b25bf649a39f32f6f5a2d7fbc3708d458dd176751d7d9835ae3e5acd23a85efabdcfcebda76cc361e6a639ccb1e7738f4",
          "sha256": "28a82621e0c084607aa7532d1d96d5558e51e180eed9ebc58c424c08c6f13aba",
          "sha1": "ffdeb8df19a79060c18985110c55b745a76a36dd",
          "md5": "a36c74ceb57941fab33d864334c92586"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.0-fix-publishing-SNAPSHOT.klib",
          "url": "kmock-js-0.1.0-fix-publishing-SNAPSHOT.klib",
          "size": 136190,
          "sha512": "a6e54b2d913d803588deeedfc876314b25bf649a39f32f6f5a2d7fbc3708d458dd176751d7d9835ae3e5acd23a85efabdcfcebda76cc361e6a639ccb1e7738f4",
          "sha256": "28a82621e0c084607aa7532d1d96d5558e51e180eed9ebc58c424c08c6f13aba",
          "sha1": "ffdeb8df19a79060c18985110c55b745a76a36dd",
          "md5": "a36c74ceb57941fab33d864334c92586"
        }
      ]
    }
  ]
}
