{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/bc20163-change-danger-SNAPSHOT/test-utils-fixture-bc20163-change-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "bc20163-change-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "35d3ccf686d56ba17426c559632456148756ea8865232afa790465b89b5dab21df7ee2abb83c63a8cec625d0d79f3fa0bc113af24c426c6c55a68ccf4666c52a",
          "sha256": "3733a8f572fcf40c9942d51d20f639ac092360b01593b2b9d2efe495d1bf6a36",
          "sha1": "3ee289f121a5c45e750b7d63371f5d70172330c4",
          "md5": "670320df5949edbae456c6b6828318cb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.klib",
          "size": 38261,
          "sha512": "35d3ccf686d56ba17426c559632456148756ea8865232afa790465b89b5dab21df7ee2abb83c63a8cec625d0d79f3fa0bc113af24c426c6c55a68ccf4666c52a",
          "sha256": "3733a8f572fcf40c9942d51d20f639ac092360b01593b2b9d2efe495d1bf6a36",
          "sha1": "3ee289f121a5c45e750b7d63371f5d70172330c4",
          "md5": "670320df5949edbae456c6b6828318cb"
        }
      ]
    }
  ]
}
