{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "1ba4d29-change-gradle-action-runner",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-android-application-configuration-1ba4d29-change-gradle-action-runner.jar",
          "size": 51340,
          "sha512": "94e9a97ea6557e3f9c36f44c0f5be807bea805e2db61b9e122311b94244c0e7b81da2978b36c6feed2f38ee08d751dc749e3c9c102bf3ee04c107a4dfeaf9f83",
          "sha256": "ebd88602d819f3a40054c110b2455a497d6d845321b7e7d6a2632a7adb2c0b5c",
          "sha1": "fed6d78dbc551325b53c19069773cb7dddfb860c",
          "md5": "305d3edd70410e4cce8fcdccd65eb3fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1ba4d29-change-gradle-action-runner"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-android-application-configuration-1ba4d29-change-gradle-action-runner.jar",
          "size": 51340,
          "sha512": "94e9a97ea6557e3f9c36f44c0f5be807bea805e2db61b9e122311b94244c0e7b81da2978b36c6feed2f38ee08d751dc749e3c9c102bf3ee04c107a4dfeaf9f83",
          "sha256": "ebd88602d819f3a40054c110b2455a497d6d845321b7e7d6a2632a7adb2c0b5c",
          "sha1": "fed6d78dbc551325b53c19069773cb7dddfb860c",
          "md5": "305d3edd70410e4cce8fcdccd65eb3fb"
        }
      ]
    }
  ]
}
