{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/2025aef-add-more-sources-SNAPSHOT/test-utils-annotations-junit4-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-macosarm64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 11369,
          "sha512": "f3d1d8c3c14cd00a9b40bda19ee1c4e85e2988f93842840ec6446eeb7f44f3824c33040cb12b8bf5c7f3f40fdebaf5821490793c674fa6f0d6833664954fcd09",
          "sha256": "15c7ddea1b33ff42939ea52cb5e1d2089de96f42bee1800623415a5465fd2bbc",
          "sha1": "11ce88bf7e3919d129654db6777eaf690bd4b925",
          "md5": "8d97260bca00467d74df25993a51cd67"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-macosarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-macosarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "01535454d987887e2301a3314bbeb222d7c31b4ee1ebb735dbfeb2c1ea4d064aed837691dbae0cc413907d073a7086accd3da762b60a51464353a12dcf74f1c7",
          "sha256": "1014bfddb7fc9e7787a8e50a0a2869b9b17ff9c2ba7b509f1a492d67b8f1aa28",
          "sha1": "793b6730a86a5e3ee12bdf9cd107604392bda068",
          "md5": "fa5bc29f92a140045b90272d0487f0e7"
        }
      ]
    }
  ]
}
