{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit4-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-linuxmips32-694b583-change-setup-SNAPSHOT.klib",
          "size": 11379,
          "sha512": "227e402b675e1886a20949d4f26aee5e7b70356b097973bc4e6df9d29b2b62785d2646d1ff186d92249ecef0c3182a3c76208d3ae54fce6db4c0195b27918cc4",
          "sha256": "03ccf4c3f48721fc2a839ceef9d98cce4bfa8b5976fc80a7561115a7762ebb7e",
          "sha1": "43a451218c3e448f7522aaf9eb661bd84f270d07",
          "md5": "9bd9e923ec4cc7f02bfc0baf7f716791"
        }
      ]
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-linuxmips32-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-linuxmips32-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "439ef7e1873ad579f612341c65e401a647a3072b32d88f8703640ec4985dfbf4a7f08bfcc711684dd3d3e5e44e923e4a9cf8fa64d7073c60ef4138c4b5e2cfb5",
          "sha256": "738fa42918bba11cac72a94cfcb458d7982e8d3b2fed3f725a8a06af56ad6d5a",
          "sha1": "ef62524c802800cd0acb4c7cc96b540cdf228bbb",
          "md5": "e12400674263a1ab45303db93324a197"
        }
      ]
    }
  ]
}
