{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT/kmock-0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "c0d81ebf67ae1b03c4f51036ff324204ea3cf9b8f4f99efd5f03dcd22768f38341a8dd16f6c44558fd06de6436e937ea7e957a94c4bcd5720f5a328b8af0241d",
          "sha256": "39ded349f865701db76fe3ddc46d53253a29b7f9bcbf5306bc1f564511c20b02",
          "sha1": "7bab983269a1c4cf158ee031a25664ece90029dc",
          "md5": "ece6b4aedf65e91da1148736f4da4e10"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-7c51ea823e-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "c0d81ebf67ae1b03c4f51036ff324204ea3cf9b8f4f99efd5f03dcd22768f38341a8dd16f6c44558fd06de6436e937ea7e957a94c4bcd5720f5a328b8af0241d",
          "sha256": "39ded349f865701db76fe3ddc46d53253a29b7f9bcbf5306bc1f564511c20b02",
          "sha1": "7bab983269a1c4cf158ee031a25664ece90029dc",
          "md5": "ece6b4aedf65e91da1148736f4da4e10"
        }
      ]
    }
  ]
}
