{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/5d5a54a-change-settings-SNAPSHOT/test-utils-annotations-junit4-5d5a54a-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "5d5a54a-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 11351,
          "sha512": "eab01ccdc633125109f8844313c375f7821d74fd72713a110dcd21edadaadb67d0f9a4f42aea27872ff5873c6eca1367eabd6516f3e6f718c879785be3d3b229",
          "sha256": "ac318de8cc81066e0b59e7ee3b0d09e9f2fe1fa5288b0f460273a0d91e085660",
          "sha1": "8461e6ece21752696e7b9b24da62772ef6133a3b",
          "md5": "eb05bdc9218caeac1aafb0b1c4779775"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-5d5a54a-change-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-5d5a54a-change-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6ed177b713b532f3a1a5e87a0c3b187d855d3cc65c21f19bdd5742d18427232423a844f4f0f59abc3a0cfb9c02381febfcdabf3778b833a15c44489d5e325d5d",
          "sha256": "f502b482aac4f993c202aea9cce448040225e8eab65041fe6ebd13e4a685f930",
          "sha1": "c20050e7726303c044abaa32851c1d0f94db92ba",
          "md5": "a986f57b321c83c6df118aa4cc9faaf3"
        }
      ]
    }
  ]
}
