{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/cf4be82-add-fixture-kmp-SNAPSHOT/test-utils-fixture-cf4be82-add-fixture-kmp-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "cf4be82-add-fixture-kmp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-cf4be82-add-fixture-kmp-SNAPSHOT.jar",
          "size": 40993,
          "sha512": "25497fac6ae89e6299cb94d6dccbbc672236b5ec1d75174ed88617072cc07ab6fcf0a0f7eb258212c7fb14b8497f5be07fcc6bb8b8d23a3ebfedcde25ab29027",
          "sha256": "abf29b0efc5dda857651a09225b068a4af0277f1dbd71c004dce3ccc31a077f8",
          "sha1": "1665206214fd2a3bf6f8bc2db1e927338313826f",
          "md5": "fe16b66f02a9d2a9fb67258ad7f1cafa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-cf4be82-add-fixture-kmp-SNAPSHOT.jar",
          "size": 40993,
          "sha512": "25497fac6ae89e6299cb94d6dccbbc672236b5ec1d75174ed88617072cc07ab6fcf0a0f7eb258212c7fb14b8497f5be07fcc6bb8b8d23a3ebfedcde25ab29027",
          "sha256": "abf29b0efc5dda857651a09225b068a4af0277f1dbd71c004dce3ccc31a077f8",
          "sha1": "1665206214fd2a3bf6f8bc2db1e927338313826f",
          "md5": "fe16b66f02a9d2a9fb67258ad7f1cafa"
        }
      ]
    }
  ]
}
