{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "4cc4725",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-4cc4725.jar",
          "url": "antibytes-gradle-utils-4cc4725.jar",
          "size": 9568,
          "sha512": "fd1ec8eef9be0c37af424acb5552e0c1cfc8a2e76d62a727c06bba71cb88ff9845e089c96aa364ad04436833831bb21d987a9e328dbee8349f1e201be3adf2e5",
          "sha256": "67373af8be0068c5cd0cce65a2229a7320cfe922b92594b8c4e6e7a868bc699a",
          "sha1": "fc8467c9bd5806badb993d4ee9aea0d4eb465497",
          "md5": "a109dcdb4b7114e01bb4398baf470471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-4cc4725.jar",
          "url": "antibytes-gradle-utils-4cc4725.jar",
          "size": 9568,
          "sha512": "fd1ec8eef9be0c37af424acb5552e0c1cfc8a2e76d62a727c06bba71cb88ff9845e089c96aa364ad04436833831bb21d987a9e328dbee8349f1e201be3adf2e5",
          "sha256": "67373af8be0068c5cd0cce65a2229a7320cfe922b92594b8c4e6e7a868bc699a",
          "sha1": "fc8467c9bd5806badb993d4ee9aea0d4eb465497",
          "md5": "a109dcdb4b7114e01bb4398baf470471"
        }
      ]
    }
  ]
}
