{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/5290833-add-number-SNAPSHOT/fixture-5290833-add-number-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "5290833-add-number-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosarm64-5290833-add-number-SNAPSHOT.klib",
          "size": 48952,
          "sha512": "d6d25e66828a358f892924571018bb7a05ab55342c67e858b4f8913e3331c3e44a296a9dbcd0a08074e585d28c763a2e16605c37a638373700e10a6778632087",
          "sha256": "4892d29174e4276c1ad73a1e4c432ff587fd6c6eed4a5c60b14c9c8411ebcd8a",
          "sha1": "d62e7ffe37eb9102a725a368e34f101911dc561f",
          "md5": "d6fc392cbff4a454cf56ed19e52cc122"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosarm64-5290833-add-number-SNAPSHOT-metadata.jar",
          "url": "fixture-iosarm64-5290833-add-number-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "132f0e29157c179f262bc344f35ada6834626efc2b26c93c334ea36095b3122328bc2f01feb50c3545dc409c4ee8687ad547c2391c62bf1a23f55c4de3b022eb",
          "sha256": "ce7de73a1a9af2b51012f24f3f83c600dc27291af87c81b51aed6b639a144c31",
          "sha1": "88ae7378a398fb756d46fa11e141a7fc82bf3b34",
          "md5": "6afd7393b263d2dbffec2f425d467019"
        }
      ]
    }
  ]
}
