{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "a5ef8105ba0d245c3bf9446ebe167096065f95385aa967eae1d2fd041b9839db59470ed00d96a200bca7ae98822ad999ba57e14a43fe5124221c7c549af69e0d",
          "sha256": "49147d5d6b63332b0b65087c6e5941f2027d0359a8e4085f51aedbd8b0a8f6f8",
          "sha1": "f8facc4987d066bceed5417864c54e06385159fe",
          "md5": "9836fcf74c881275fcaa67756fa4a37f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "a5ef8105ba0d245c3bf9446ebe167096065f95385aa967eae1d2fd041b9839db59470ed00d96a200bca7ae98822ad999ba57e14a43fe5124221c7c549af69e0d",
          "sha256": "49147d5d6b63332b0b65087c6e5941f2027d0359a8e4085f51aedbd8b0a8f6f8",
          "sha1": "f8facc4987d066bceed5417864c54e06385159fe",
          "md5": "9836fcf74c881275fcaa67756fa4a37f"
        }
      ]
    }
  ]
}
