{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "af6c810",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-af6c810.jar",
          "url": "antibytes-publishing-af6c810.jar",
          "size": 100326,
          "sha512": "69e4efc08c896a1b69c66e64334454cbb59f4e592b5cca4f3bfa3823e6ef2c4bfe578652e8fa4015bb8fde7d908aadeebb394e5bfcb5a1a2fbe4707bbe938792",
          "sha256": "199ead6bc2056c8da2b33f0ad161d00aebfc0ff2ebce87dff003f9a19def357c",
          "sha1": "0fe41cb1c4441f984e9c4d283e7ae60033c668db",
          "md5": "5ccefcd511e26469c65f38e339a8fb36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-af6c810.jar",
          "url": "antibytes-publishing-af6c810.jar",
          "size": 100326,
          "sha512": "69e4efc08c896a1b69c66e64334454cbb59f4e592b5cca4f3bfa3823e6ef2c4bfe578652e8fa4015bb8fde7d908aadeebb394e5bfcb5a1a2fbe4707bbe938792",
          "sha256": "199ead6bc2056c8da2b33f0ad161d00aebfc0ff2ebce87dff003f9a19def357c",
          "sha1": "0fe41cb1c4441f984e9c4d283e7ae60033c668db",
          "md5": "5ccefcd511e26469c65f38e339a8fb36"
        }
      ]
    }
  ]
}
