{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "6f06370-add-custom-component-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-6f06370-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-6f06370-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "149595c15213e3d526c88a50fef382112e4fdad54113c3760a7c4079e00bc74d9832bf5535d9126944cb76c61e095a2ad4cbcd545b92316ee23ff69b24f9cee1",
          "sha256": "b0624dab9a90ee138b4297297025a51a7082b17b045b28b27700fe870f48c293",
          "sha1": "c834784fdac955755bc85a4225006b90c740deac",
          "md5": "7d6ed8ab3262c393716cd1b01c50ad4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6f06370-add-custom-component-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-6f06370-add-custom-component-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-6f06370-add-custom-component-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "149595c15213e3d526c88a50fef382112e4fdad54113c3760a7c4079e00bc74d9832bf5535d9126944cb76c61e095a2ad4cbcd545b92316ee23ff69b24f9cee1",
          "sha256": "b0624dab9a90ee138b4297297025a51a7082b17b045b28b27700fe870f48c293",
          "sha1": "c834784fdac955755bc85a4225006b90c740deac",
          "md5": "7d6ed8ab3262c393716cd1b01c50ad4b"
        }
      ]
    }
  ]
}
