{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit5-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-694b583-change-setup-SNAPSHOT.klib",
          "size": 7135,
          "sha512": "11d345fc64f6e9dec68c63102b2576443704c52100e65b33faaf3b8b08337be245f194456ea51e65cfabe34feef1add181af829ce7885a7977d5d41005286531",
          "sha256": "7aad63ef12408ddf057d9a90d3cd85bbde21ba77747fb5fd197ec32db68a5fd7",
          "sha1": "795460f85c22927d3586a3b92de139e140806fa2",
          "md5": "a422756344bc796618ae9c6a89dd1ed7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "14b87fdda98b7c51e460a8a8e5157d3fe28412e8f8c2af1cc3fa7c72528f225f26a32710c5cd0aeda567c7acf560586164a8f2387d215f5dead30f8994a20a98",
          "sha256": "dd948af23064717610b50f061ad6711066873eedac85d7f62a9075f7e0623a09",
          "sha1": "bc31da94bd9c996719d7e6bd8c43344d2362f55b",
          "md5": "44b6e1a3e3a7ae921c35417900d729c6"
        }
      ]
    }
  ]
}
