{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc04-add-more-platforms-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT.jar",
          "size": 75465,
          "sha512": "dda0e66a21260e2dc22dbb35395ac10982b45f81c4619100b805aa453f4f49ffe1aaaffdbb3edfafaa09186714fb50681b8d188c825707044cb1640b4256db0d",
          "sha256": "af884ba8317beda28233847842fd2431a6c99a6becad138b177f35a94c529323",
          "sha1": "7217bae1bc9dafd2565a49b46b5cc165d2d9531e",
          "md5": "206e5d57319f6d46bed27f0fe973ec6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.20-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT.jar",
          "size": 75465,
          "sha512": "dda0e66a21260e2dc22dbb35395ac10982b45f81c4619100b805aa453f4f49ffe1aaaffdbb3edfafaa09186714fb50681b8d188c825707044cb1640b4256db0d",
          "sha256": "af884ba8317beda28233847842fd2431a6c99a6becad138b177f35a94c529323",
          "sha1": "7217bae1bc9dafd2565a49b46b5cc165d2d9531e",
          "md5": "206e5d57319f6d46bed27f0fe973ec6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "e29b3e613c185c73839af49e5d034c9741b4f666d5509b27216ab6b9df2edaba3835b87b29be3658b006f7226aef3cfbad01ef5a555eccb236f23dff116e5af8",
          "sha256": "6bd70db10835a9b51fe403e1bfebdd6358a1a380ed8027877ca00aba7541f8ff",
          "sha1": "2a0733359af91c1a00f007a75acb758b2773c884",
          "md5": "f71b55dbd1516fb94aa6bb8d307bef2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc04-add-more-platforms-SNAPSHOT-sources.jar",
          "size": 14722,
          "sha512": "0f89f7b5959ac224e89fa5d9e822127054f41e82c5083558266e7e0e52fcf4ac3b0e03883cbfbe594eca0abfd84c047f467bdcb27eb281b29320da3689738adf",
          "sha256": "73798fc7a429b8a4e2ff6da57328f90e1728a994a72b46b705c069e8d51a88d7",
          "sha1": "9f426f01226c99a17345753599373d5d88c748f4",
          "md5": "0f70e767c77dbf75c8435b1df558bc11"
        }
      ]
    }
  ]
}
