{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-change-source-set-indicator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-source-set-indicator-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-source-set-indicator-SNAPSHOT.jar",
          "size": 295075,
          "sha512": "2a3e5895e290a618f4d37a506f8eb4b09cd6feb6908d1a2bb2f12d015ea7e508a25b0b235ad0f5ceb88c9bf64356bafe0d00a93c689b530f949adabc241e3439",
          "sha256": "a2ae90b5491541124d1dfc3c5e145c3852b41d3ddea120f8970ef26b824020e4",
          "sha1": "fc0b61473fc98702f10b9e958ec9b502b32eeca5",
          "md5": "64624b317be276e892fbe207a1d8f71a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-change-source-set-indicator-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-change-source-set-indicator-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-change-source-set-indicator-SNAPSHOT.jar",
          "size": 295075,
          "sha512": "2a3e5895e290a618f4d37a506f8eb4b09cd6feb6908d1a2bb2f12d015ea7e508a25b0b235ad0f5ceb88c9bf64356bafe0d00a93c689b530f949adabc241e3439",
          "sha256": "a2ae90b5491541124d1dfc3c5e145c3852b41d3ddea120f8970ef26b824020e4",
          "sha1": "fc0b61473fc98702f10b9e958ec9b502b32eeca5",
          "md5": "64624b317be276e892fbe207a1d8f71a"
        }
      ]
    }
  ]
}
