{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/2025aef-add-more-sources-SNAPSHOT/test-utils-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm32-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 7962,
          "sha512": "2fc4ccee1addc3cb32356a025da5297edaed25947e4bfac9c334afc2882db9ce82c47607bbe56845bb5c6b570243e373989f2ed0c003c4b3cf346d44548536b4",
          "sha256": "c2b570c058f2f6a9f061c1802776841938a08d50f0d1f7815552290c4290088a",
          "sha1": "3d5c5b4cf5e2b9e21abe9bef700f8d4f3fa0169d",
          "md5": "103fede5a6124eb790461fde2db1573c"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm32-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm32-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "301d7f9a20b50842e29a18a521075e571b9b5900ac690f4b6ac9aad380d3ce7d100e6a4d5ef79eaedd481e3d488007578c8c9e851e9f74e70cd27d3f0beb6485",
          "sha256": "15876e129630f36f2aa32521e3dc27baf61848aabc4af820548da9695f067cce",
          "sha1": "4f1efe2aaa02282f9429bce8db966b57ad06d2cd",
          "md5": "eaefb2fdb2bdaa93bd1037bb587a2da4"
        }
      ]
    }
  ]
}
