{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-charArray-generator-SNAPSHOT/core-0.2.0-change-charArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-charArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-change-charArray-generator-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-charArray-generator-SNAPSHOT.jar",
          "size": 145971,
          "sha512": "eb40b42c02be2c980f17d02050564cf6a4721bb6aa80e23ce5b9fcb1a2323ec058d3094b087908d4eeb2d87ce55f70b6e9f9b0fd148e3bfa05142207c95a4e82",
          "sha256": "a091b41a86cc34a1e491df0fe30a6cc130803a0c978c92feea042e5b254a0476",
          "sha1": "e613c2ef8407637bbc24be3bbe472ec24a407c95",
          "md5": "e65ae73496a5d07b1565d8e1efa5b433"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-change-charArray-generator-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-change-charArray-generator-SNAPSHOT.jar",
          "size": 145971,
          "sha512": "eb40b42c02be2c980f17d02050564cf6a4721bb6aa80e23ce5b9fcb1a2323ec058d3094b087908d4eeb2d87ce55f70b6e9f9b0fd148e3bfa05142207c95a4e82",
          "sha256": "a091b41a86cc34a1e491df0fe30a6cc130803a0c978c92feea042e5b254a0476",
          "sha1": "e613c2ef8407637bbc24be3bbe472ec24a407c95",
          "md5": "e65ae73496a5d07b1565d8e1efa5b433"
        }
      ]
    }
  ]
}
