{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b4fc57b-add-size-to-fixture-SNAPSHOT/test-utils-ktor-b4fc57b-add-size-to-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b4fc57b-add-size-to-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-b4fc57b-add-size-to-fixture-SNAPSHOT.jar",
          "size": 22735,
          "sha512": "dd921ebee1df7e28364416c0d60a417c3361b7ebc4030e6630aa3f78e2b7d4dda0d11826f56a33be7b8a95e2b06e917baaf709b3321c6bdaa8ee36e2fdbec100",
          "sha256": "1c10a30d470da63d2cf1ecf03133048ec0e0cabd10f5ecf51cc3dccf0df81e43",
          "sha1": "ee60daada50e82a46299e1999b28ae0169814287",
          "md5": "28bda60f08fbdc3fc38fb3cdd71e43f9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-b4fc57b-add-size-to-fixture-SNAPSHOT.jar",
          "size": 22735,
          "sha512": "dd921ebee1df7e28364416c0d60a417c3361b7ebc4030e6630aa3f78e2b7d4dda0d11826f56a33be7b8a95e2b06e917baaf709b3321c6bdaa8ee36e2fdbec100",
          "sha256": "1c10a30d470da63d2cf1ecf03133048ec0e0cabd10f5ecf51cc3dccf0df81e43",
          "sha1": "ee60daada50e82a46299e1999b28ae0169814287",
          "md5": "28bda60f08fbdc3fc38fb3cdd71e43f9"
        }
      ]
    }
  ]
}
