{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "70f9286-add-testscope-dispatcher-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata-all.jar",
          "url": "test-utils-ktor-70f9286-add-testscope-dispatcher-SNAPSHOT-all.jar",
          "size": 5014,
          "sha512": "2d70720d91211f94c77ec11d568c37a16091c49a602091bd3bf38c51ec3c6df28fa05ee0cee175b1e37ac7f985f8244dae5c134846529ed3c970f0b2525a8a6b",
          "sha256": "190c8bfd5f16a6d50f866e415f5f6eddf8989416a1462d51ab854e63ccd0f30c",
          "sha1": "a6b546a6a7819ccd5884dc368adf7e8675af1601",
          "md5": "7a78962ba36c085125a7f74ca4dca6f8"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor.jar",
          "url": "test-utils-ktor-70f9286-add-testscope-dispatcher-SNAPSHOT.jar",
          "size": 2522,
          "sha512": "24fb5ead1f8f12e15b94e82db0c542a320adbee50333c9663114cad4e145c5466ae17c602bffcd3763ecf59c5a0fdcd8481d5e7a2faf9af951c3eabf402794fb",
          "sha256": "3f0a487332e6a2ea680be8ed6f42f27ffd8340eb7876c63a32d4cca686dad993",
          "sha1": "9948e9545b0fc357a705eb8488dcb8f9f04ddb44",
          "md5": "da48f69ecf30e963007309f6213db98d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-android-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-android-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-js-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-js-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-jvm-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-jvm-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/70f9286-add-testscope-dispatcher-SNAPSHOT/test-utils-ktor-linuxx64-70f9286-add-testscope-dispatcher-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "70f9286-add-testscope-dispatcher-SNAPSHOT"
      }
    }
  ]
}
