{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT/kmock-0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "76b72e5a8a7a80624863aaaf56161a986a2e584e85a85e8d7b58c0650d1f15de91b0c55e572400e955c0946ca0b2e92aed45feda1fbcd679447857ea89553f21",
          "sha256": "2e939f2ab012b873e55c3a02d849ed58526864885bf2dafa75333fd19f7b6a29",
          "sha1": "fb72574811de689fec344dc02e961cd24df58751",
          "md5": "d272b75962b6aa5c040d5e460cde5d70"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc01-fix-artifact-cleanup-SNAPSHOT.jar",
          "size": 394981,
          "sha512": "76b72e5a8a7a80624863aaaf56161a986a2e584e85a85e8d7b58c0650d1f15de91b0c55e572400e955c0946ca0b2e92aed45feda1fbcd679447857ea89553f21",
          "sha256": "2e939f2ab012b873e55c3a02d849ed58526864885bf2dafa75333fd19f7b6a29",
          "sha1": "fb72574811de689fec344dc02e961cd24df58751",
          "md5": "d272b75962b6aa5c040d5e460cde5d70"
        }
      ]
    }
  ]
}
