{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-db9451a-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "db9451a-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-db9451a-bump-updates-SNAPSHOT.klib",
          "size": 11317,
          "sha512": "1345a457d6b21109252f3e310229bafbda720314b8c4e3f02a45b637da0c8bcd017eb6022b2e2b8840a51c8e893262b62d8707daf9bc9ba3dfab6f750cedd7f4",
          "sha256": "4740762df0317240f4e0f5331d7fa5cc0e3ba21cd03f61ccc737ad9b11367321",
          "sha1": "5df54de0e28c24c32948503573af1a423d924d66",
          "md5": "f5d94d620c48da3955ee28c9f7133bf7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-db9451a-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-iosx64-db9451a-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3cb5514c8fd83721233c5414f3afce3f54e9bede21cd9250f3d617cc891f8dcc0243201739b3ea50803e80f0ec6a3e3dcc3d46688b4384454804eb2d80e3fc0a",
          "sha256": "e9a44d740b6b5d19cce4190a3d475a5109d3fc5cfe44013a988b3bab01115379",
          "sha1": "2bebb924744a0fe959617de430e9abe29aab427f",
          "md5": "7408f614db217b6959209d3406104cbf"
        }
      ]
    }
  ]
}
