{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/dac75a8-change-workflows-SNAPSHOT/test-utils-annotations-junit4-dac75a8-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "dac75a8-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "101a429cb2fb477ba124fe73b945d7a06bcc393a87088d94e0cf8badf46a03a96aa891bc025fbd4af212a2c2b8d4eca47dbb90694a393e74705ec91364631dea",
          "sha256": "e5d92961cdd457577e71ca00a03cc2fd43d7e55a11a46475f85022f6db2332fc",
          "sha1": "2ba7de5a40d72a7023869cd54b0cde10b8553ff8",
          "md5": "4a86f749290f4ab92f96ca6948c38268"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "101a429cb2fb477ba124fe73b945d7a06bcc393a87088d94e0cf8badf46a03a96aa891bc025fbd4af212a2c2b8d4eca47dbb90694a393e74705ec91364631dea",
          "sha256": "e5d92961cdd457577e71ca00a03cc2fd43d7e55a11a46475f85022f6db2332fc",
          "sha1": "2ba7de5a40d72a7023869cd54b0cde10b8553ff8",
          "md5": "4a86f749290f4ab92f96ca6948c38268"
        }
      ]
    }
  ]
}
