{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/dccc533-change-project-setup-SNAPSHOT/test-utils-resourceloader-dccc533-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "dccc533-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosx64-dccc533-change-project-setup-SNAPSHOT.klib",
          "size": 12849,
          "sha512": "b05d419daa737638e1a68389db45e60bea41be3040a340ff709c504009a3e5ec8c8be71a2b276b3138d910f6f6f7f282daed519f0d7ccd55e01886495d2eb310",
          "sha256": "3c611a4912536b6a5fd7316d6a18b4fd7713a78c6c2c4cebe3d2a73d8d0d005f",
          "sha1": "fc5acdc5e365bcf321e84682b21068d4a0b8cd53",
          "md5": "c294d934ca5be70f140b4cd78fcc592f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosx64-dccc533-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iosx64-dccc533-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1d27d43f5de874da00b70f07f858d27795a345634e6cdb93cc123eebc17739f7b631783234ce1f0b3922b9bd2a38cfe839c5690abfd3987c49669d1cbce064da",
          "sha256": "03c14fae9a8c23ff791440d2c587cda7e5e65b7837b44012166dcfc9f9c7eca1",
          "sha1": "50bd1d09e13f060996896d40dc224f3fe370e623",
          "md5": "f2a304c7d5e484b4f7a9af504585c745"
        }
      ]
    }
  ]
}
