{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/f8d6e50-bump-workflows-SNAPSHOT/test-utils-coroutine-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-tvosarm64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 10138,
          "sha512": "0f1ba05bad7ba7acbb3044f0068cf9f365ce09da4c64f055bb3f470cdecd790069f0ec640cb9d597d63fa4649602491b5cdbac972e7a7e5d910e592770a8e92d",
          "sha256": "b46d063c91ad9e0eb76d0d66aef3bb30d4b763be2ec0f0c199945b34af3b976e",
          "sha1": "bcdbfb9507dda41e4bdf630c198b7f5ffdab79a6",
          "md5": "da6988588156b929533767c1dd3eeb35"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-tvosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-tvosarm64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f353e1053290d2b3dc1375331be227350fb3153d42959f63111a0a3de157e20fe7a9b207b7ae2f827da4bd876f865308080b9ed64bf2b1b7d2f597cec7255d57",
          "sha256": "a7c69114c03c912bf966b2e03b7bb3a2390282990e89640287fc4e3b7661d6b8",
          "sha1": "d9b223edc1108ac49ede403709142055cd7db7e9",
          "md5": "8f6a19bc9ac35ee6055e7cb258ea9950"
        }
      ]
    }
  ]
}
