{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-setup-SNAPSHOT/core-0.4.0-fix-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchossimulatorarm64-0.4.0-fix-setup-SNAPSHOT.klib",
          "size": 105958,
          "sha512": "40a7ed20c8ef0df789fafea3720f01d6c7b3d1229622f0c3df71858c0dbd93e1e56ddb78565634dea6106a559789e8f0b5d9a89a12ce257d652b075ccc7f18b7",
          "sha256": "13f4405aa8515bd33c869905cff6352a26d432b659042af57ee86c38c27f7831",
          "sha1": "1346b8c83ae4d3a534e199d2cabdb5d85b3b69a0",
          "md5": "a6a4540c838c864aed2a5feeee9e39de"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchossimulatorarm64-0.4.0-fix-setup-SNAPSHOT-metadata.jar",
          "url": "core-watchossimulatorarm64-0.4.0-fix-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f7113efdef1f6ac0fd1c56054e8c7b505acfcb235848fd9f121eab0e75fb6a264aa275bda66d35f0f5759ecfed7638aae6f576208b199650b518d434d1ba94c5",
          "sha256": "d14e5dc1ad322c3b12e01c441ab6a0b144a6af1eedf43655ddf85c9aa93bd68d",
          "sha1": "77a82281c61bfc5f304ca2fdab1e4dcc14f6ce1d",
          "md5": "d2028e27a06656b1fe274407c06ae862"
        }
      ]
    }
  ]
}
