{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f6669bd-add-native-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata-all.jar",
          "url": "test-utils-ktor-f6669bd-add-native-SNAPSHOT-all.jar",
          "size": 5014,
          "sha512": "90ad81fff4da293d7dcd1787293da027c5e03be1f640ac53775f51b2b9d6c8d32a480d5b46267a042f9e407fd748d410f2101f59a4fbfbe1b8cb70ffb7365579",
          "sha256": "647516ab56537682a7d11249d81f6037d700c13e339479dfe484bc6a97889922",
          "sha1": "71f3c64edd8a549f49c2ba22b7c60b37b5511137",
          "md5": "09282887fd5d026ecbb9e90353e1a850"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor.jar",
          "url": "test-utils-ktor-f6669bd-add-native-SNAPSHOT.jar",
          "size": 2522,
          "sha512": "7509dbd6fcabe3fee86c3b18324abef4067d924f1d3e442ec54e3f809085100742da6e931fd8fd4fca47b9755028d3ace6f0907954665a79f23c336f5ef1a705",
          "sha256": "dc404dc04985a57e33b40d7f26d020b02c03cbbb564a96d3182d545dff4d2659",
          "sha1": "2491c0fc09a0dabd2cb8b95827683f39ce6af25c",
          "md5": "a560819e9f2aa3d3f6ad46f4cd46b9a6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/f6669bd-add-native-SNAPSHOT/test-utils-ktor-android-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/f6669bd-add-native-SNAPSHOT/test-utils-ktor-android-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/f6669bd-add-native-SNAPSHOT/test-utils-ktor-js-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/f6669bd-add-native-SNAPSHOT/test-utils-ktor-js-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/f6669bd-add-native-SNAPSHOT/test-utils-ktor-jvm-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/f6669bd-add-native-SNAPSHOT/test-utils-ktor-jvm-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/f6669bd-add-native-SNAPSHOT/test-utils-ktor-linuxx64-f6669bd-add-native-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "f6669bd-add-native-SNAPSHOT"
      }
    }
  ]
}
