{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/f3c59f8-change-project-setup-SNAPSHOT/test-utils-coroutine-f3c59f8-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "f3c59f8-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-f3c59f8-change-project-setup-SNAPSHOT.klib",
          "size": 10129,
          "sha512": "35b514c90d7924051f386b713af1db6f3498cce6fff1721b399759427ff4357415a9d0aa60451287fb65cf5eb6a3fa83a443cb12cbc58aa29d29e96b3d703fe6",
          "sha256": "79c8f739a5068e87f92be4c36c30dfda44bd350019e68a21fe54d318bd820c17",
          "sha1": "a93040db971a59d83fe98682380c7998fecec18f",
          "md5": "fef28cc9f42b966eeda32da41ee99aac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-f3c59f8-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-f3c59f8-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d636155c05a47aefc9e2fd8a92169ae3c3793affb6c58a4d3466c09a173406878770e70568b1204cfc70cf7841ab6252aac8d844de79d33b6c9cec3ff358b5e9",
          "sha256": "3023b336c9b86dc9091b4f495545564e964ab13693ea9ef20bf7c01d3ca950f7",
          "sha1": "f0fd862c2ee6ee7b4ebebe1b6239d611d7656c95",
          "md5": "dfdebca922eca5e5a1c40a49ef7e8903"
        }
      ]
    }
  ]
}
