{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03-change-labler-SNAPSHOT/kmock-0.3.0-rc03-change-labler-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-change-labler-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-change-labler-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-change-labler-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "ad47fa00442178b25274d096eeabb476f5c27e095d421ba87c4300040f79388b91e3f73a7b84f66ad634f10c790b2cbfa1715df0c2d1cd198da88d44b1df01b1",
          "sha256": "31a0300591e8bd536043455b454a343c383649a89312623ae5e5426c9a8be67c",
          "sha1": "cae6652c58e225b45f9405e7b10c3bc125c5c579",
          "md5": "ddfcc3f40e9baebf6aaf23c594bb4673"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-change-labler-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-change-labler-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "ad47fa00442178b25274d096eeabb476f5c27e095d421ba87c4300040f79388b91e3f73a7b84f66ad634f10c790b2cbfa1715df0c2d1cd198da88d44b1df01b1",
          "sha256": "31a0300591e8bd536043455b454a343c383649a89312623ae5e5426c9a8be67c",
          "sha1": "cae6652c58e225b45f9405e7b10c3bc125c5c579",
          "md5": "ddfcc3f40e9baebf6aaf23c594bb4673"
        }
      ]
    }
  ]
}
