{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "2b9fd9e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "2b9fd9e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-2b9fd9e.jar",
          "url": "antibytes-publishing-2b9fd9e.jar",
          "size": 117663,
          "sha512": "d3c96998c50951cdc2ad3785a94bb886eb63d2de9c3ed0dccc87fb48742e00383fc3209e306432610e023a6d668b229e5d1988ea5fdf87fa0911d1117ff17aad",
          "sha256": "cb6fdab0cb0c415f97cf202f98755cfa195ef87eea772b3793fa4dd3fce8b5d8",
          "sha1": "309edf66f2f12471f8070e49c5fa0712a31ef72e",
          "md5": "3dbf0505c6b5e415a456f6564e196dad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2b9fd9e"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "2b9fd9e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-2b9fd9e.jar",
          "url": "antibytes-publishing-2b9fd9e.jar",
          "size": 117663,
          "sha512": "d3c96998c50951cdc2ad3785a94bb886eb63d2de9c3ed0dccc87fb48742e00383fc3209e306432610e023a6d668b229e5d1988ea5fdf87fa0911d1117ff17aad",
          "sha256": "cb6fdab0cb0c415f97cf202f98755cfa195ef87eea772b3793fa4dd3fce8b5d8",
          "sha1": "309edf66f2f12471f8070e49c5fa0712a31ef72e",
          "md5": "3dbf0505c6b5e415a456f6564e196dad"
        }
      ]
    }
  ]
}
