{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "118f8e7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-118f8e7.jar",
          "url": "antibytes-dependency-118f8e7.jar",
          "size": 40863,
          "sha512": "6f3b64c135e8b64302be91616499ad77063750534650355e12a10cab4a1149d942313925f523c90587ee84773bf6b6005bae75ef2d365166a015eec83e8381e5",
          "sha256": "3615b778e642ecbf42b2928d699fdfa2ba5f77f0e1353a36470bec3e4cf4b239",
          "sha1": "a1c0057f6ba5475eaeb0139ac0e800bb536f3fca",
          "md5": "83c219f088eb71de71858e6a8a66728c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-118f8e7.jar",
          "url": "antibytes-dependency-118f8e7.jar",
          "size": 40863,
          "sha512": "6f3b64c135e8b64302be91616499ad77063750534650355e12a10cab4a1149d942313925f523c90587ee84773bf6b6005bae75ef2d365166a015eec83e8381e5",
          "sha256": "3615b778e642ecbf42b2928d699fdfa2ba5f77f0e1353a36470bec3e4cf4b239",
          "sha1": "a1c0057f6ba5475eaeb0139ac0e800bb536f3fca",
          "md5": "83c219f088eb71de71858e6a8a66728c"
        }
      ]
    }
  ]
}
