{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "f361883",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-f361883.jar",
          "url": "antibytes-runtime-configuration-f361883.jar",
          "size": 10324,
          "sha512": "348b85b2a695d1f4633eb3713e37d7cb1a4e7fe7811ded9d44314c33dba72f19520f68372762af1a39bc03ea691b3466c9fcc0bc219c095ae080fb62638f1772",
          "sha256": "5e3a20606576ab3deb72e36ce890ff047fa2f4e61221821241eb89d9d96ab176",
          "sha1": "ad78dd2b5f95738edcbce9a47becc4e7b6ee9fcb",
          "md5": "c0a34defebd72f5ba4ac0b514dea58c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f361883"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-f361883.jar",
          "url": "antibytes-runtime-configuration-f361883.jar",
          "size": 10324,
          "sha512": "348b85b2a695d1f4633eb3713e37d7cb1a4e7fe7811ded9d44314c33dba72f19520f68372762af1a39bc03ea691b3466c9fcc0bc219c095ae080fb62638f1772",
          "sha256": "5e3a20606576ab3deb72e36ce890ff047fa2f4e61221821241eb89d9d96ab176",
          "sha1": "ad78dd2b5f95738edcbce9a47becc4e7b6ee9fcb",
          "md5": "c0a34defebd72f5ba4ac0b514dea58c7"
        }
      ]
    }
  ]
}
