{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-settings",
    "version": "de75989-change-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-de75989-change-settings-plugin.jar",
          "url": "antibytes-dependency-settings-de75989-change-settings-plugin.jar",
          "size": 8778,
          "sha512": "5b73165860e3acd2a827b7d9230fba144b8e936a2fd040f15d58b9a919f70ea0cd2553e84ae55bed44b398b10435ec00b0d0e502607a0d12187b3b2ec1593286",
          "sha256": "6141e5485c038574893fe4c0e29fd93440a7a664ebc2651219ded0ea64188ecc",
          "sha1": "36b4b8c5000de94aa0a9d0c7bca2d49055bd2e29",
          "md5": "598a87d50b1a1648842695c7de7dac48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-de75989-change-settings-plugin.jar",
          "url": "antibytes-dependency-settings-de75989-change-settings-plugin.jar",
          "size": 8778,
          "sha512": "5b73165860e3acd2a827b7d9230fba144b8e936a2fd040f15d58b9a919f70ea0cd2553e84ae55bed44b398b10435ec00b0d0e502607a0d12187b3b2ec1593286",
          "sha256": "6141e5485c038574893fe4c0e29fd93440a7a664ebc2651219ded0ea64188ecc",
          "sha1": "36b4b8c5000de94aa0a9d0c7bca2d49055bd2e29",
          "md5": "598a87d50b1a1648842695c7de7dac48"
        }
      ]
    }
  ]
}
