{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.3.1-bump-updates-SNAPSHOT/ktx-datetime-0.3.1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.3.1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-bump-updates-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.3.1-bump-updates-SNAPSHOT.klib",
          "size": 34683,
          "sha512": "1dc52bb0058de13a55d58ed8a606ff162390a626a81ab89e3b00cf5ce47dd058161bf547e8124e99a1839e84ae82ffdb206e1cbad0c4213ff9c1c39bfd585388",
          "sha256": "8a29a5e2fcf40a3d852b934eeefc47d7daba8270c31803df600351398c310c0b",
          "sha1": "d0212f8ba21b7440fed51bae6ceee9eff5b147d3",
          "md5": "bb0ba6de1a6a1542c83616eba7374c64"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.3.1-bump-updates-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.3.1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.3.1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cfd2f4ab771d0ce1ca2d194fb67472f5bdbdbc082e13d8eeff7c5066f74ec2cd23f0baa09fedb0ac8a6c07e52f1de51d9c25a843488e4a7fe935690992661dac",
          "sha256": "8ef92ad8e88242bdf135f23c1ba069ee38a46d9f5cea5782c4c0b5088045be2a",
          "sha1": "bc8f615f7abd647fd91ff4cb001867b6f7b29654",
          "md5": "9b1d39a045fc841d5aff3cd56d0d1078"
        }
      ]
    }
  ]
}
