{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/5c5fd4f-add-dokka-SNAPSHOT/kmock-5c5fd4f-add-dokka-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "5c5fd4f-add-dokka-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-5c5fd4f-add-dokka-SNAPSHOT.jar",
          "url": "kmock-jvm-5c5fd4f-add-dokka-SNAPSHOT.jar",
          "size": 252026,
          "sha512": "4725da911ce881a07781438c387b3d2c38cb80e6cd046232858e3b36936441dc23e09fdbe2d1b6d22796c13d5043b6311c88b2299dc0be72418a5f2d8dd3829c",
          "sha256": "fc0579153f8d65435334898aeb9f77b3047129dfa755bf1ba0c5aae53bf419cf",
          "sha1": "84e7eca861a3a1436cd0b273558ca1cb48a25e1c",
          "md5": "cafbfcec2f7e032487eb38a42fb13ff1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-5c5fd4f-add-dokka-SNAPSHOT.jar",
          "url": "kmock-jvm-5c5fd4f-add-dokka-SNAPSHOT.jar",
          "size": 252026,
          "sha512": "4725da911ce881a07781438c387b3d2c38cb80e6cd046232858e3b36936441dc23e09fdbe2d1b6d22796c13d5043b6311c88b2299dc0be72418a5f2d8dd3829c",
          "sha256": "fc0579153f8d65435334898aeb9f77b3047129dfa755bf1ba0c5aae53bf419cf",
          "sha1": "84e7eca861a3a1436cd0b273558ca1cb48a25e1c",
          "md5": "cafbfcec2f7e032487eb38a42fb13ff1"
        }
      ]
    }
  ]
}
