{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/b8215f8-add-ios-SNAPSHOT/test-utils-fixture-b8215f8-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "b8215f8-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-b8215f8-add-ios-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-b8215f8-add-ios-SNAPSHOT.klib",
          "size": 36097,
          "sha512": "2d1ae50731b0353e5e6e7b2199a81d67a68c94007a300ce217c674b1a8b85c8014f61f2d129c212ef53ce091a49ffb5600278ed2a6cc8ed7d4daf6dcdd04388d",
          "sha256": "8414e95b995cd88a3601590b179eea4eb3298b07ba70786f4c603d5c9d232393",
          "sha1": "0be782d2eae74909faeaf35e0c446251a53c4fca",
          "md5": "c62aa64a641020dfc2248534432a182d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-js-b8215f8-add-ios-SNAPSHOT.klib",
          "url": "test-utils-fixture-js-b8215f8-add-ios-SNAPSHOT.klib",
          "size": 36097,
          "sha512": "2d1ae50731b0353e5e6e7b2199a81d67a68c94007a300ce217c674b1a8b85c8014f61f2d129c212ef53ce091a49ffb5600278ed2a6cc8ed7d4daf6dcdd04388d",
          "sha256": "8414e95b995cd88a3601590b179eea4eb3298b07ba70786f4c603d5c9d232393",
          "sha1": "0be782d2eae74909faeaf35e0c446251a53c4fca",
          "md5": "c62aa64a641020dfc2248534432a182d"
        }
      ]
    }
  ]
}
