{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "bc20163-change-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-metadata-bc20163-change-danger-SNAPSHOT-all.jar",
          "url": "test-utils-fixture-bc20163-change-danger-SNAPSHOT-all.jar",
          "size": 15401,
          "sha512": "fdd05e6809a34990f393d39316ad24c67549c4ff69d5de84536c460d4bc00d4fe8554df3cd9635389a979ab5214252d1f822cd24e0bdb9fa186ed3c3e8f51703",
          "sha256": "d5eb0cc62ec017cbd3cfe4ad3fd037cf46e505648ca66922d3085f1d12137dba",
          "sha1": "87fe6bff8d08ec7d92bb0c2e190dfca0911c8837",
          "md5": "79e081188b6f894e246c0a2b6bb04d33"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-bc20163-change-danger-SNAPSHOT.jar",
          "url": "test-utils-fixture-bc20163-change-danger-SNAPSHOT.jar",
          "size": 15466,
          "sha512": "53ab4652cd4d9325d38b536578f018d35b26fccc10e5ae81cb375e54b4bf7bffac54a50fc584291359fff65b18e812e2eeb088f7c159b4535a82546acc80fde9",
          "sha256": "8b0d126d04df44a70b194bec42f93195929778bd592feeb6fc0e2f1ec88d685b",
          "sha1": "508bf1722a2aec871063cd850eefad00af99aa92",
          "md5": "c596ae6bd084dea7506dfdf8e273f918"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/bc20163-change-danger-SNAPSHOT/test-utils-fixture-android-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/bc20163-change-danger-SNAPSHOT/test-utils-fixture-android-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/bc20163-change-danger-SNAPSHOT/test-utils-fixture-iosarm64-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/bc20163-change-danger-SNAPSHOT/test-utils-fixture-iosarm64-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/bc20163-change-danger-SNAPSHOT/test-utils-fixture-iosx64-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/bc20163-change-danger-SNAPSHOT/test-utils-fixture-iosx64-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/bc20163-change-danger-SNAPSHOT/test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/bc20163-change-danger-SNAPSHOT/test-utils-fixture-js-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/bc20163-change-danger-SNAPSHOT/test-utils-fixture-jvm-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/bc20163-change-danger-SNAPSHOT/test-utils-fixture-jvm-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/bc20163-change-danger-SNAPSHOT/test-utils-fixture-linuxx64-bc20163-change-danger-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "bc20163-change-danger-SNAPSHOT"
      }
    }
  ]
}
