{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/5b65d35-bump-updates-SNAPSHOT/test-utils-ktor-5b65d35-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "5b65d35-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT.klib",
          "size": 15108,
          "sha512": "9dd44ad1a2f4466a350eca71f56c06d33f2078ab952f1ef1cadc32e9052fc0b131913308f925352a82528bf995b6b5ea3175014fa6504800f31272574796d428",
          "sha256": "14b35fb0e84dd0411ac54f9856abfb264b6fda50c565ab2edff7525405d5ba83",
          "sha1": "1dec88a7c1a8189da3abf6972f68c1ed447b421c",
          "md5": "1793ff1ab95f79c67b7a2728640fbfbf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-5b65d35-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8fbb63ed01aa49f4697434ca31e897a573acee038d9f2dcef4ddf636107a5cb6d72b3af36d80697a74303b347a95dce111c4ab49a542157a6e779b9ba9777409",
          "sha256": "6aa2692553b243d9e7c2406ecbe9d907eeef8b54ae46a9e0e66a6b276946e3b6",
          "sha1": "36151e1783669c294e2aeeeafc2e26313e74974e",
          "md5": "031fb9ac340d9f04a4daaca2c0f6875f"
        }
      ]
    }
  ]
}
