{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "46c9fa3-change-gradle-props-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-46c9fa3-change-gradle-props-SNAPSHOT.jar",
          "size": 2149,
          "sha512": "83ecb48c4943b0ac61992eb9f6d2f9a3eacaad34ad4a15679aa1baea65040dc75b424be89794aa8b2f7305fb2c1a4e0aab2e87027e17f40c3ab7735af47ae313",
          "sha256": "c0afdede6d4592b7ddc4aba34fef2122e5f901e4e23873f33ed67eb30012ae59",
          "sha1": "79b4a2aa370de2b89426bf87b28b850028248bc2",
          "md5": "17718c4516a757ce8177ea47ef374b11"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/46c9fa3-change-gradle-props-SNAPSHOT/test-utils-coroutine-android-46c9fa3-change-gradle-props-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "46c9fa3-change-gradle-props-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/46c9fa3-change-gradle-props-SNAPSHOT/test-utils-coroutine-android-46c9fa3-change-gradle-props-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "46c9fa3-change-gradle-props-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/46c9fa3-change-gradle-props-SNAPSHOT/test-utils-coroutine-jvm-46c9fa3-change-gradle-props-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "46c9fa3-change-gradle-props-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/46c9fa3-change-gradle-props-SNAPSHOT/test-utils-coroutine-jvm-46c9fa3-change-gradle-props-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "46c9fa3-change-gradle-props-SNAPSHOT"
      }
    }
  ]
}
