{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-change-workflows-SNAPSHOT/ktx-datetime-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 34771,
          "sha512": "9b1fe07b269d9ea4d185c68f78b05e521499eb2e2f24db7851b916514ec3b03b689b6e66e7fd48c9e415455ec007d0ac58f2fd33261239404a1074ee06d52475",
          "sha256": "d3d83e53eda6ea43a28b421416571449556a9dc6a3d518dec3c682d818538b8f",
          "sha1": "0389f39205938a0a108ef4639584204f021ed42c",
          "md5": "f48f217a993871b8c5043787c1d59601"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "77e3d78526b0ebf86b5b796a3cfdb60433489ebb5d479e45bdc3cebdcae5fe0c756ce29c4f20b77ce704d42ea797f9204ff7cd85458cc1d786ae6bab31c65f13",
          "sha256": "d77041758ae5ad95a3be13a9b47faddcd4be6200bbc3c1c447b058df03e662f8",
          "sha1": "24c326a9e529c1f5f83954237729dce25c740b27",
          "md5": "e23822bb2bdce377e50a42b58fd04495"
        }
      ]
    }
  ]
}
