{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-change-workflows-SNAPSHOT/ktx-datetime-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 34771,
          "sha512": "9b1fe07b269d9ea4d185c68f78b05e521499eb2e2f24db7851b916514ec3b03b689b6e66e7fd48c9e415455ec007d0ac58f2fd33261239404a1074ee06d52475",
          "sha256": "d3d83e53eda6ea43a28b421416571449556a9dc6a3d518dec3c682d818538b8f",
          "sha1": "0389f39205938a0a108ef4639584204f021ed42c",
          "md5": "f48f217a993871b8c5043787c1d59601"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-workflows-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d299edaab6b10453820b023e54cc1a7567bd14be0674f9e77b8f98bec17b00e5b26ca76dfb1b48fdce083ada7aa7bdf059b94e0c52ac4ae2114ec6e521673e5f",
          "sha256": "d649a57ef0d6c2a84b6fae018bcf867f76a2a357fe7089da5cd2511005086036",
          "sha1": "92c18e44a8f7d2217c6cfb061a760809e4fcf43f",
          "md5": "2725c3a90957f3d8cd95e192b83823b1"
        }
      ]
    }
  ]
}
