{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/e930d3d-change-project-setup-SNAPSHOT/test-utils-e930d3d-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "e930d3d-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-e930d3d-change-project-setup-SNAPSHOT.klib",
          "size": 7962,
          "sha512": "4a9c4a745a177b65290a8b6e1f4e45afc70018250e9ae064673b79e21097a78c70fdbb53a13b425478520c3b96d781a60435d7f3e70860d6cf3e70419e57b82c",
          "sha256": "c231e0f0fe7d17b3c8feebc5684c52f4f2e23e8c895ea9c6ab9bb1bafb5817ae",
          "sha1": "bd56568f4ff847bf496cb11403f05f4758bc54ac",
          "md5": "21bf8685971662cd968ba414c97652e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-e930d3d-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "764f32ccea92578c5e47438cacf7545a17c8ad4f4f7976cefd295c857e8f3133db78021bfba6b4711135837b5290473263886feab3100bd8793da2fe4006f3f4",
          "sha256": "fa39d59d9cf0c1b74c7a474e4739fb57cf4f544383061d34110517b97c5dce1c",
          "sha1": "2ad90ee259076ad69432af6bac1e751585b203ec",
          "md5": "ed5a53279f8702c30baf531ad2a5cd39"
        }
      ]
    }
  ]
}
