{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "87a9798-add-provider-to-ensureKotlinVersion",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-87a9798-add-provider-to-ensureKotlinVersion.jar",
          "url": "antibytes-kmp-configuration-87a9798-add-provider-to-ensureKotlinVersion.jar",
          "size": 68661,
          "sha512": "8d0100cd14eec68c95098fac86008c64e7da3541907d66835ca62d3303fd6837a4c7408e93c70ff7a40e0106f17abcfd2f119307cda2f769631dc2db0a22c930",
          "sha256": "0f4ce087a72664c6d06aca5c0845e46d0bc752d7f9c902ef3eff0a8b8f1da150",
          "sha1": "5f2513929e038dff9bff95916f0c30bc1b456dc8",
          "md5": "43046d0f83a18df4c81471d4b8cacbc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "87a9798-add-provider-to-ensureKotlinVersion"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-87a9798-add-provider-to-ensureKotlinVersion.jar",
          "url": "antibytes-kmp-configuration-87a9798-add-provider-to-ensureKotlinVersion.jar",
          "size": 68661,
          "sha512": "8d0100cd14eec68c95098fac86008c64e7da3541907d66835ca62d3303fd6837a4c7408e93c70ff7a40e0106f17abcfd2f119307cda2f769631dc2db0a22c930",
          "sha256": "0f4ce087a72664c6d06aca5c0845e46d0bc752d7f9c902ef3eff0a8b8f1da150",
          "sha1": "5f2513929e038dff9bff95916f0c30bc1b456dc8",
          "md5": "43046d0f83a18df4c81471d4b8cacbc8"
        }
      ]
    }
  ]
}
