{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/c8e7c91-change-workflows-SNAPSHOT/test-utils-coroutine-c8e7c91-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "c8e7c91-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT.klib",
          "size": 10215,
          "sha512": "20f8faf97ffe763f21a5727be08c7cc050477ad101cf5fcf7173e9ddbe61e09ad64024ed4ac84f526406d32dada6786171cb15ed0140b91d8c0099e9b3e42c52",
          "sha256": "b5ee960a0de26f99ed0dae68d0108fc1f8a3ffb5ce966589d0682b49fd80510d",
          "sha1": "b306a632a58df0d61fcd0d72b06743ddc98ed3f8",
          "md5": "d0c2d9c2207c602d76d9a6491b30bff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-c8e7c91-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "864d88717f9df62d21c886c299d23fde5469d7998c40590d81cb0cf10f5a60b39e9b359165187cd6c9e7f23637ec33afe51432afc89026119036f2b2a7f97b93",
          "sha256": "d60b768bdce179a66a6ccf5e8c426e33e6e0b99277dacd1f2f52a345d6893763",
          "sha1": "6f06c573afe4fa3b4f05757fbe94c089193086e9",
          "md5": "7c3ea5e64710af3228ae78cc2f9fceca"
        }
      ]
    }
  ]
}
