{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-fix-doc-publishing-SNAPSHOT/kmock-0.3.0-rc04-fix-doc-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-fix-doc-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.3.0-rc04-fix-doc-publishing-SNAPSHOT.klib",
          "size": 202496,
          "sha512": "b66efb9899840172de9a3d8baf52a4fe06d76a2bb5adf7a0a4f8eea966fee8e8ecb60a8daeaeddccf7f7f013212a5a39dd74acae41baff051846ff3bc79b6196",
          "sha256": "9c982dd5bb009031b2102a11535fe0e7e45c5c5beef39b8483085ee2fcfa8ea6",
          "sha1": "eca4d404db2e784fc5d6bf27724bddcf1dbd54b9",
          "md5": "239740d3942f8c8d3009c51951db7a4e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.3.0-rc04-fix-doc-publishing-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.3.0-rc04-fix-doc-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c75258e678e52603429bbf18c104e45d525ad466a8a5ef61c4a232622fdd65e9381a9f7b5103accee16bc1b1a8823348cf25441194f1e15028b26b271ee9659b",
          "sha256": "2ccd4878e5ddacfafe9e23172046b239cb0aeda603b20fd64cf7bdb567385ded",
          "sha1": "64a979df50888abe534aaecdac00da8db5b472a6",
          "md5": "2ca349e3955ee6d3c480340fc04c857c"
        }
      ]
    }
  ]
}
