{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/ad479d6-change-workflows-SNAPSHOT/test-utils-annotations-junit4-ad479d6-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "ad479d6-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-ad479d6-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-ad479d6-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "563eedf722b60165aeb2b03240d6c0fd9661acd33b5a778450d6cc7b1e41ebb8843540ae17f2154718861c1f940125a7b9c312a285594d62d320f0035d260fa7",
          "sha256": "933a05ff141b1ac7ad9a351e58736a46d24e31342eff397ea08aad746069ea62",
          "sha1": "1866e377d53ec1dd39b1e93e9fb2b8b655f743f7",
          "md5": "04e29f395010d39de88f52517dc3e4da"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-ad479d6-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-ad479d6-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "563eedf722b60165aeb2b03240d6c0fd9661acd33b5a778450d6cc7b1e41ebb8843540ae17f2154718861c1f940125a7b9c312a285594d62d320f0035d260fa7",
          "sha256": "933a05ff141b1ac7ad9a351e58736a46d24e31342eff397ea08aad746069ea62",
          "sha1": "1866e377d53ec1dd39b1e93e9fb2b8b655f743f7",
          "md5": "04e29f395010d39de88f52517dc3e4da"
        }
      ]
    }
  ]
}
