{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.0-rc01-change-proxy-apis-SNAPSHOT/kmock-0.2.0-rc01-change-proxy-apis-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.0-rc01-change-proxy-apis-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-rc01-change-proxy-apis-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-rc01-change-proxy-apis-SNAPSHOT.klib",
          "size": 214121,
          "sha512": "63d4ea7239c52c9e4c4f158c1b68d8f468370ff118d9dfbe2d5306bc3efbe21e20c9d89c7fca6a972d7082534706cd88ef5d850f7e54087776992c54f0a31bcf",
          "sha256": "7c30bff96f04c3623b7bbf4b24c722692fc8d4addab8a4b3530b78a6382c6906",
          "sha1": "c9ec1438d5f89f9e4ef4bf8c8ec00d5d51dba809",
          "md5": "6679e41ea35499001e53ca042daf8183"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.2.0-rc01-change-proxy-apis-SNAPSHOT.klib",
          "url": "kmock-js-0.2.0-rc01-change-proxy-apis-SNAPSHOT.klib",
          "size": 214121,
          "sha512": "63d4ea7239c52c9e4c4f158c1b68d8f468370ff118d9dfbe2d5306bc3efbe21e20c9d89c7fca6a972d7082534706cd88ef5d850f7e54087776992c54f0a31bcf",
          "sha256": "7c30bff96f04c3623b7bbf4b24c722692fc8d4addab8a4b3530b78a6382c6906",
          "sha1": "c9ec1438d5f89f9e4ef4bf8c8ec00d5d51dba809",
          "md5": "6679e41ea35499001e53ca042daf8183"
        }
      ]
    }
  ]
}
