{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "cf4be82-add-fixture-kmp-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-metadata.jar",
          "url": "test-utils-coroutine-cf4be82-add-fixture-kmp-SNAPSHOT.jar",
          "size": 1609,
          "sha512": "057bbc88ea351435887a1b4584c966655a2d2e12e0ab87f8af005a31cb3392bebc0ecfacee841beb5148566a38d3d647bcda17ebd6267d030d88eb8c60b0a652",
          "sha256": "496185eb6c07af7519e64cdfe404e5e1f3493411dce3b8c33197def043102f07",
          "sha1": "dd71fefbba8e889e1b95aea7d359f94423b09016",
          "md5": "eb977fef4218396964d7c9ee7b818c20"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/cf4be82-add-fixture-kmp-SNAPSHOT/test-utils-coroutine-android-cf4be82-add-fixture-kmp-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "cf4be82-add-fixture-kmp-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/cf4be82-add-fixture-kmp-SNAPSHOT/test-utils-coroutine-android-cf4be82-add-fixture-kmp-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "cf4be82-add-fixture-kmp-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/cf4be82-add-fixture-kmp-SNAPSHOT/test-utils-coroutine-jvm-cf4be82-add-fixture-kmp-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "cf4be82-add-fixture-kmp-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/cf4be82-add-fixture-kmp-SNAPSHOT/test-utils-coroutine-jvm-cf4be82-add-fixture-kmp-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "cf4be82-add-fixture-kmp-SNAPSHOT"
      }
    }
  ]
}
