{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-fix-badges-SNAPSHOT/ktx-datetime-0.4.0-fix-badges-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-badges-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvossimulatorarm64-0.4.0-fix-badges-SNAPSHOT.klib",
          "size": 34744,
          "sha512": "37b9148236c1a7843a78548d0944fda1639c81ee1d0fa6995c8ced32a2cf644e28f1042ede00b6e94eda9f4161634c01d353898c0cd9e2bb6f10b31790ecedfa",
          "sha256": "046a9659534a7ad2f6d0271d1f1f82307896952d695b80c115d3ba3b52389f50",
          "sha1": "d6823dc4a6036411d38c64c4b7bc55e304820143",
          "md5": "fedf679260fe5e67b618ac2cfa9fe93c"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-badges-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvossimulatorarm64-0.4.0-fix-badges-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9cc6fce83afa41a8fa28c465b520b6dfc7a908e4d5d58c5edf16248635017b8b463f5c34fd6bd2258f1d4fd7fcf7fc92383e03a8caa9b616f88ea7c36190d8da",
          "sha256": "aaabb43ad3e2a7cc700716d3ff702c484ce61eb81fc7ee3322f96dd38a75d7e6",
          "sha1": "988721c002e226ab3ddb5833de9b481687df47f1",
          "md5": "0e39845044f5d8f2a2bfc29d6f3f0ef4"
        }
      ]
    }
  ]
}
