{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/836d98f-add-signing-SNAPSHOT/core-836d98f-add-signing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "836d98f-add-signing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-836d98f-add-signing-SNAPSHOT.klib",
          "url": "core-js-836d98f-add-signing-SNAPSHOT.klib",
          "size": 61533,
          "sha512": "2ff95de05fcc16ba954e469ff60fffde184ec1c604f60daab7c987eff50d40913025c4d7df8e8e1e7936dd3203dc862d8b3cf6538510ac532203f838a0a841f5",
          "sha256": "15b6fe329f0963197a3289ba265fef508d995e661fbbd6363233eb57d04a5bbf",
          "sha1": "b6b91061b989bffaf5fc6fac7d6dc8f9a012e426",
          "md5": "ccb42f95db6864826fc9a8c48b4e34bf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-836d98f-add-signing-SNAPSHOT.klib",
          "url": "core-js-836d98f-add-signing-SNAPSHOT.klib",
          "size": 61533,
          "sha512": "2ff95de05fcc16ba954e469ff60fffde184ec1c604f60daab7c987eff50d40913025c4d7df8e8e1e7936dd3203dc862d8b3cf6538510ac532203f838a0a841f5",
          "sha256": "15b6fe329f0963197a3289ba265fef508d995e661fbbd6363233eb57d04a5bbf",
          "sha1": "b6b91061b989bffaf5fc6fac7d6dc8f9a012e426",
          "md5": "ccb42f95db6864826fc9a8c48b4e34bf"
        }
      ]
    }
  ]
}
