{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0acf509-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0acf509-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-gradle-0acf509-add-class-cracker-SNAPSHOT.jar",
          "size": 63131,
          "sha512": "6cdcd1500e6c50765ff3404c3ddd9c979f13fbd574621986ce2cd7af2a8f2026ddc0a21ecf50e363f45bb38f1e31297519b6252c803ef182663770128a4cb0cd",
          "sha256": "1c0021d79d26c4d824404c02051549a0e1fe3d0956fc23ed1433d1877ea38565",
          "sha1": "62aca2d9ff3cf3c5ccc1bc794f4cab2eb298a9bb",
          "md5": "c21dbf120acea5fc92c1ac01980e87d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0acf509-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-gradle-0acf509-add-class-cracker-SNAPSHOT.jar",
          "size": 63131,
          "sha512": "6cdcd1500e6c50765ff3404c3ddd9c979f13fbd574621986ce2cd7af2a8f2026ddc0a21ecf50e363f45bb38f1e31297519b6252c803ef182663770128a4cb0cd",
          "sha256": "1c0021d79d26c4d824404c02051549a0e1fe3d0956fc23ed1433d1877ea38565",
          "sha1": "62aca2d9ff3cf3c5ccc1bc794f4cab2eb298a9bb",
          "md5": "c21dbf120acea5fc92c1ac01980e87d5"
        }
      ]
    }
  ]
}
