{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "452cb59-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-452cb59-change-node-dependencies.jar",
          "url": "antibytes-kmp-configuration-452cb59-change-node-dependencies.jar",
          "size": 12972,
          "sha512": "afd3978e05e9418ea5365c7029f29c5d048ce31d17c4290592fad99f46f516c34123d3ffb18d7f1b1c755aadcd6520510c8ea462b6c0f6fa9421e27f10b6a5b9",
          "sha256": "0f5e44a7da85ea9c83220059009ba7c033685635cc54489c78baf5c8c53c9915",
          "sha1": "dbac14c054e898b5bab371331b9154c30930ee0e",
          "md5": "ec8a41bba1ab5293b297680413f93556"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "452cb59-change-node-dependencies"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-452cb59-change-node-dependencies.jar",
          "url": "antibytes-kmp-configuration-452cb59-change-node-dependencies.jar",
          "size": 12972,
          "sha512": "afd3978e05e9418ea5365c7029f29c5d048ce31d17c4290592fad99f46f516c34123d3ffb18d7f1b1c755aadcd6520510c8ea462b6c0f6fa9421e27f10b6a5b9",
          "sha256": "0f5e44a7da85ea9c83220059009ba7c033685635cc54489c78baf5c8c53c9915",
          "sha1": "dbac14c054e898b5bab371331b9154c30930ee0e",
          "md5": "ec8a41bba1ab5293b297680413f93556"
        }
      ]
    }
  ]
}
