{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-periods-SNAPSHOT/core-0.3.1-add-periods-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-periods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.3.1-add-periods-SNAPSHOT.jar",
          "url": "core-jvm-0.3.1-add-periods-SNAPSHOT.jar",
          "size": 291292,
          "sha512": "f48033a3da3892674f6ba56a91909e95715cfbde480c742181338f02e6499cf55e422062a80d6a270408d2e7951826ec9d8b60107ba6e446af9963683236923c",
          "sha256": "a6b630b0590e55b690d64839477edab22caeaff06c439c117d230fbd504a8f0c",
          "sha1": "8af52a2591b14060c8ad1bbe70a7ba780a901ebe",
          "md5": "93e5d5425261b202b3a01ca8e498199e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.3.1-add-periods-SNAPSHOT.jar",
          "url": "core-jvm-0.3.1-add-periods-SNAPSHOT.jar",
          "size": 291292,
          "sha512": "f48033a3da3892674f6ba56a91909e95715cfbde480c742181338f02e6499cf55e422062a80d6a270408d2e7951826ec9d8b60107ba6e446af9963683236923c",
          "sha256": "a6b630b0590e55b690d64839477edab22caeaff06c439c117d230fbd504a8f0c",
          "sha1": "8af52a2591b14060c8ad1bbe70a7ba780a901ebe",
          "md5": "93e5d5425261b202b3a01ca8e498199e"
        }
      ]
    }
  ]
}
