{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/e23d1f7-add-setup-SNAPSHOT/banana-i18n-e23d1f7-add-setup-SNAPSHOT.module",
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "e23d1f7-add-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-e23d1f7-add-setup-SNAPSHOT.jar",
          "size": 1394,
          "sha512": "9b5319a5223db6747d7c14cbbe1ba8828e0b08ef1981412240bf2d444f9408c13e0a93d77fb6388b18d21e11a3a270d586dbf0fd7425b315c2020e34d5bbdb1e",
          "sha256": "42e952c223fb9a86e4fa571ca1c42760e7464e5e2b33816e4b2a8a8df2c8daf9",
          "sha1": "fec403f72f24af376a88af6a7c667f0873dbb3d1",
          "md5": "46fbf787284f20061f99144953c37ad0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-e23d1f7-add-setup-SNAPSHOT.jar",
          "size": 1394,
          "sha512": "9b5319a5223db6747d7c14cbbe1ba8828e0b08ef1981412240bf2d444f9408c13e0a93d77fb6388b18d21e11a3a270d586dbf0fd7425b315c2020e34d5bbdb1e",
          "sha256": "42e952c223fb9a86e4fa571ca1c42760e7464e5e2b33816e4b2a8a8df2c8daf9",
          "sha1": "fec403f72f24af376a88af6a7c667f0873dbb3d1",
          "md5": "46fbf787284f20061f99144953c37ad0"
        }
      ]
    }
  ]
}
