{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "98fcfcc-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-gradle-test-utils-98fcfcc-change-node-dependencies.jar",
          "size": 17226,
          "sha512": "2f75fde551daf1f00fb5b12e96423c89f7726b5eb85e124f565c50b54604579fd4993e9d9f949319776ef955de66abcb78e5bc32e45b47e6583e92b5f02ba4e6",
          "sha256": "196c9c3fa56ec176ed6bebace05f5266cbc5167eb3df1383c37b0cd5bd52eb3e",
          "sha1": "275a3c404934e6e63f9f36cc8ecd3096b16ed546",
          "md5": "46668b852bae8adf3f1b6e651140554f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-gradle-test-utils-98fcfcc-change-node-dependencies.jar",
          "size": 17226,
          "sha512": "2f75fde551daf1f00fb5b12e96423c89f7726b5eb85e124f565c50b54604579fd4993e9d9f949319776ef955de66abcb78e5bc32e45b47e6583e92b5f02ba4e6",
          "sha256": "196c9c3fa56ec176ed6bebace05f5266cbc5167eb3df1383c37b0cd5bd52eb3e",
          "sha1": "275a3c404934e6e63f9f36cc8ecd3096b16ed546",
          "md5": "46668b852bae8adf3f1b6e651140554f"
        }
      ]
    }
  ]
}
