{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "2709ef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-2709ef8.jar",
          "url": "antibytes-gradle-utils-2709ef8.jar",
          "size": 9568,
          "sha512": "4631ec21862f6d9d4853db1123d2f4f3583234a09c8a7fecdab82e39e1cc8509e326408ff79b26a90e210d0ee17d5a2c89b029660ae9a460cbf88dce5451186d",
          "sha256": "d7f65f74eeac473a24bea760abeda3633f3e57247b9de24ec225ad8f04e02110",
          "sha1": "d97cf0d5cfc88f00bdfe2b14e4b9866c7bbe6e4d",
          "md5": "72dff432be84428fc246fd91fa1ed952"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-2709ef8.jar",
          "url": "antibytes-gradle-utils-2709ef8.jar",
          "size": 9568,
          "sha512": "4631ec21862f6d9d4853db1123d2f4f3583234a09c8a7fecdab82e39e1cc8509e326408ff79b26a90e210d0ee17d5a2c89b029660ae9a460cbf88dce5451186d",
          "sha256": "d7f65f74eeac473a24bea760abeda3633f3e57247b9de24ec225ad8f04e02110",
          "sha1": "d97cf0d5cfc88f00bdfe2b14e4b9866c7bbe6e4d",
          "md5": "72dff432be84428fc246fd91fa1ed952"
        }
      ]
    }
  ]
}
