{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/43575a8-add-iossimlator-SNAPSHOT/test-utils-annotations-43575a8-add-iossimlator-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "43575a8-add-iossimlator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "b8478a6e89e7465c7423d368d836bd9a9e02504a772616bfddeecd278d42a9f5f82013eee61f2a0c41b21789e978e83a0b2e38a5ca7d1f8ca56dc648363410bc",
          "sha256": "c790a8163767acb84838a1e67c69d360321c2e1b664211dc56db5cf19f3f1924",
          "sha1": "23f8445f84a0d54b23ba6b607c7778fa27d2803a",
          "md5": "c488739d4d829e89343ccd46ae8ddd67"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-43575a8-add-iossimlator-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "b8478a6e89e7465c7423d368d836bd9a9e02504a772616bfddeecd278d42a9f5f82013eee61f2a0c41b21789e978e83a0b2e38a5ca7d1f8ca56dc648363410bc",
          "sha256": "c790a8163767acb84838a1e67c69d360321c2e1b664211dc56db5cf19f3f1924",
          "sha1": "23f8445f84a0d54b23ba6b607c7778fa27d2803a",
          "md5": "c488739d4d829e89343ccd46ae8ddd67"
        }
      ]
    }
  ]
}
