{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-filter-array-signed-SNAPSHOT/core-0.2.0-add-filter-array-signed-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-filter-array-signed-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-filter-array-signed-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-filter-array-signed-SNAPSHOT.klib",
          "size": 101141,
          "sha512": "19a450d91944f28db994fbf038bf54c48350a01170210a8f05cdb2697136c051c686f6bd212f2a63ca7a38059c3be79ba34a5d57c8c3e4d21e182d205f366529",
          "sha256": "30555f54423db707fd43948f1e83103b59c13e24b53d118c2621d2d66a90d9af",
          "sha1": "734f9e016421cf0e6d18c28a03f6158389f817b6",
          "md5": "bc52135b27c9aeb6f497d379b9839d9a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-filter-array-signed-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-filter-array-signed-SNAPSHOT.klib",
          "size": 101141,
          "sha512": "19a450d91944f28db994fbf038bf54c48350a01170210a8f05cdb2697136c051c686f6bd212f2a63ca7a38059c3be79ba34a5d57c8c3e4d21e182d205f366529",
          "sha256": "30555f54423db707fd43948f1e83103b59c13e24b53d118c2621d2d66a90d9af",
          "sha1": "734f9e016421cf0e6d18c28a03f6158389f817b6",
          "md5": "bc52135b27c9aeb6f497d379b9839d9a"
        }
      ]
    }
  ]
}
