{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "ee708e9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-ee708e9.jar",
          "url": "antibytes-dependency-ee708e9.jar",
          "size": 19257,
          "sha512": "aa3798414ef778a4f4e2dc4723fde1e5653e28028022038b4e667de2f26c62575a7866f351e95f02664236e263fe483c19b201901c7620d44367d483d2be8397",
          "sha256": "2789146d922c2544fc373d88eb37dc70775ff0edb3a206c35d67bd66e55a54d4",
          "sha1": "9005bbaaf1708309d98c5ab67a8b4e225993f8d5",
          "md5": "3aad5fcddd35f6cc59e05c6ff57d3cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-ee708e9.jar",
          "url": "antibytes-dependency-ee708e9.jar",
          "size": 19257,
          "sha512": "aa3798414ef778a4f4e2dc4723fde1e5653e28028022038b4e667de2f26c62575a7866f351e95f02664236e263fe483c19b201901c7620d44367d483d2be8397",
          "sha256": "2789146d922c2544fc373d88eb37dc70775ff0edb3a206c35d67bd66e55a54d4",
          "sha1": "9005bbaaf1708309d98c5ab67a8b4e225993f8d5",
          "md5": "3aad5fcddd35f6cc59e05c6ff57d3cf8"
        }
      ]
    }
  ]
}
