{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105958,
          "sha512": "40a7ed20c8ef0df789fafea3720f01d6c7b3d1229622f0c3df71858c0dbd93e1e56ddb78565634dea6106a559789e8f0b5d9a89a12ce257d652b075ccc7f18b7",
          "sha256": "13f4405aa8515bd33c869905cff6352a26d432b659042af57ee86c38c27f7831",
          "sha1": "1346b8c83ae4d3a534e199d2cabdb5d85b3b69a0",
          "md5": "a6a4540c838c864aed2a5feeee9e39de"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-watchossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "22874b34e986481b3c089836e5caf973bce147383fb7c8b906b2f50e001b0ca715b9e0cd76094521f34dc8698c4451fb62b9d1d1cc9e4989a9aaeb0e565f28cb",
          "sha256": "5293350088c9db17e20dc4b4deb5cd325e372f9aa5dce224e21fd716cbe19aa3",
          "sha1": "d1a46dbc0f76c9b8de379bc442bcfcb32ea5d3e6",
          "md5": "0494f71298ba772deccb4ef6b97d393b"
        }
      ]
    }
  ]
}
