{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "af9df43-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-af9df43-add-plattform-hooks.toml",
          "url": "antibytes-dependency-catalog-af9df43-add-plattform-hooks.toml",
          "size": 233300,
          "sha512": "5f4123aa842045247bb84ef67170b0cdafb902681c9346dcc8d51424050c15567d0b19104960054bc7b5018f30dfdcf73f9f7d963b0f914f820ec419e8567211",
          "sha256": "b8f537f236a2c59a3087e8321fc8f964af1268ec035a0109926c3e7a369bf8ae",
          "sha1": "5e0171a2f1fb0b4957c07d82a73e7195f92f60ad",
          "md5": "4b09fd87d29dee40f1c365d7898446d5"
        }
      ]
    }
  ]
}
