{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/c975b6d-change-gradle-props-SNAPSHOT/test-utils-ktor-c975b6d-change-gradle-props-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "c975b6d-change-gradle-props-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-c975b6d-change-gradle-props-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "28a017f6803ad928e1cf5fc16ace85e4423bf2a4f911072202a1f283941e77e60aa92cbec0b8b064dc4ea16f45b8bbeb72582455ca898d89d64fa6b9c3b6b2a0",
          "sha256": "3e2f4efaa9736be63a4811950effbb222677e952bee03a6f43840e5af5dfc079",
          "sha1": "cc7115db462bb049b58a454d41660cd636b8636b",
          "md5": "a96a076d8d736d4719a2c818821038bb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-c975b6d-change-gradle-props-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "28a017f6803ad928e1cf5fc16ace85e4423bf2a4f911072202a1f283941e77e60aa92cbec0b8b064dc4ea16f45b8bbeb72582455ca898d89d64fa6b9c3b6b2a0",
          "sha256": "3e2f4efaa9736be63a4811950effbb222677e952bee03a6f43840e5af5dfc079",
          "sha1": "cc7115db462bb049b58a454d41660cd636b8636b",
          "md5": "a96a076d8d736d4719a2c818821038bb"
        }
      ]
    }
  ]
}
