{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "e6062f2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-e6062f2.jar",
          "url": "kmock-processor-e6062f2.jar",
          "size": 114145,
          "sha512": "fcf3218ece1d465d98f301e8a9c56f8e6723298c27d0239751889c033ad6e7c0d3154df319dba7429f2d3638ee32fd3780efc536ebc25821738640578cd2fda8",
          "sha256": "0945034fc1243af6d07400fabd4b113050617a2b7035bda987a333416ce63277",
          "sha1": "ce3a21aaf757b5dde0785cbccc6f55666cf7ecc4",
          "md5": "90aecf1c0ee2675ee9ab8ee79fa550eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "e6062f2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-e6062f2.jar",
          "url": "kmock-processor-e6062f2.jar",
          "size": 114145,
          "sha512": "fcf3218ece1d465d98f301e8a9c56f8e6723298c27d0239751889c033ad6e7c0d3154df319dba7429f2d3638ee32fd3780efc536ebc25821738640578cd2fda8",
          "sha256": "0945034fc1243af6d07400fabd4b113050617a2b7035bda987a333416ce63277",
          "sha1": "ce3a21aaf757b5dde0785cbccc6f55666cf7ecc4",
          "md5": "90aecf1c0ee2675ee9ab8ee79fa550eb"
        }
      ]
    }
  ]
}
