{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "ec92d02-ease-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-ec92d02-ease-plugin-SNAPSHOT.jar",
          "url": "kmock-gradle-ec92d02-ease-plugin-SNAPSHOT.jar",
          "size": 50016,
          "sha512": "4d977ff0ca9503233aa1c671eeb2d93de09ddcd49de1c6d4fc511a94ff4fdd9e0c1a5f31c78865aa50f86c57fbcb5d4246a92a2853762f94453f5baaa244135e",
          "sha256": "3525d2dc6ab5959f86f52c085aace4766b0215618edec166082f9135fbbbe5c2",
          "sha1": "8ed983c5b088caf814ae0daa57a012b53201f995",
          "md5": "392e7a451d3a1f3c6340b0062701e1d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-ec92d02-ease-plugin-SNAPSHOT.jar",
          "url": "kmock-gradle-ec92d02-ease-plugin-SNAPSHOT.jar",
          "size": 50016,
          "sha512": "4d977ff0ca9503233aa1c671eeb2d93de09ddcd49de1c6d4fc511a94ff4fdd9e0c1a5f31c78865aa50f86c57fbcb5d4246a92a2853762f94453f5baaa244135e",
          "sha256": "3525d2dc6ab5959f86f52c085aace4766b0215618edec166082f9135fbbbe5c2",
          "sha1": "8ed983c5b088caf814ae0daa57a012b53201f995",
          "md5": "392e7a451d3a1f3c6340b0062701e1d5"
        }
      ]
    }
  ]
}
