{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-workflows-SNAPSHOT/core-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-linuxmips32-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 105861,
          "sha512": "1a3b61a6ea3f87be15ae44e19d6827bc2954a54d4c754ed756fb30da5cc1e3549c97883434c9a916d94275f758b5d60adfbf958ce8a7ba28fe776102021c1953",
          "sha256": "7a9fdba5f18e8a8d5527dd3e28f4a0ae32e4f0dab53c75e96c40c07047b7849e",
          "sha1": "5ea11d9f6cef264835a82ce25c7b1184fac7d757",
          "md5": "3aa3574aa6291eb938958459fb92e372"
        }
      ]
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxmips32-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "core-linuxmips32-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a1d92bc177a951e69688982156c2986a0093a19588b79d2964926dee3aaa15fedefa65ebd2838f63fa6645b25bc4758c0f4ed0bde91e970a964597b7d7e0d021",
          "sha256": "106faee1faefafd6cbde8ded6307569bfc3c7b29ed64fb0b6d5eaaba15436e29",
          "sha1": "8f87851cd7cbed5d8e10669357e58f443888383f",
          "md5": "fa99e868ea040235c092ec836bdbc089"
        }
      ]
    }
  ]
}
