{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0252225/core-0252225.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0252225",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0252225.klib",
          "size": 50783,
          "sha512": "321ab32f732497c2f0a0e943e54ad04db7d2ca3cc512b31f93970ed9643c9eb9f1d910203ac574685e0d5b0be28dc5525a06b4227aa1098ca4556944f5b7e671",
          "sha256": "2b3c14f39c7bbb169a92455b1a76a2c5e058dfc41100db8dbdb1e893acb9de27",
          "sha1": "06ce70236fbff251dc14969f2603503f6b3dfdfe",
          "md5": "56c625ee055c32980dada36a349fcbe8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0252225-metadata.jar",
          "url": "core-iossimulatorarm64-0252225-metadata.jar",
          "size": 261,
          "sha512": "532b0e6d1193a371a05710b908a5c5426885641b858803c7df4e160da049d70e7045d281a25656c7ee984f7603dfb6af27a536bd37d974fe742179e10c39017a",
          "sha256": "e2c1f89f88e5bb893a4121ffe8562fde47cf3845d1781af180f85ef177f99b8f",
          "sha1": "2c523fcbbf17b3c1480b603a23056d26b059eb39",
          "md5": "12bc199dfc0964e0d5346d6c53b63d7f"
        }
      ]
    }
  ]
}
