{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-change-buildConfig-SNAPSHOT/kmock-0.3.0-rc04-change-buildConfig-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-change-buildConfig-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-change-buildConfig-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-change-buildConfig-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "2bf1fa12c186e797bb631bf1cf03d216bc64eb467c0f1406a2d7e6936536efe1e14d1e1ce2869c8f701e1a9c29d682100e85681a165db0fc3e28bd7137be2608",
          "sha256": "3071add4c5c4f745fa90640d92fdd7cc63419f6372eb9de65854ceeb7a28dfd0",
          "sha1": "cd3a33bed09a9aa3d9ae14fce7ea2af457b7e3e8",
          "md5": "7c117fa01589ca47714c41865bcb8f60"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-change-buildConfig-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-change-buildConfig-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "2bf1fa12c186e797bb631bf1cf03d216bc64eb467c0f1406a2d7e6936536efe1e14d1e1ce2869c8f701e1a9c29d682100e85681a165db0fc3e28bd7137be2608",
          "sha256": "3071add4c5c4f745fa90640d92fdd7cc63419f6372eb9de65854ceeb7a28dfd0",
          "sha1": "cd3a33bed09a9aa3d9ae14fce7ea2af457b7e3e8",
          "md5": "7c117fa01589ca47714c41865bcb8f60"
        }
      ]
    }
  ]
}
