{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "f4386a0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-f4386a0.jar",
          "url": "antibytes-publishing-f4386a0.jar",
          "size": 94971,
          "sha512": "3d461f8d2eb16f3a47c9851c6ee0e051b26bcc42838d15bdc0cfb51658ecd5b949c27024d5ed64e14aa1f4dce825bdcd0e54f466b33a6d244adadcb8c71299f4",
          "sha256": "2c6f06dc0c39eeb4f67c8a182d7cf78001f376a0cb655b4878c65742dd14fb77",
          "sha1": "4c59d81ee1960f2229f9f34392100ae3d3298482",
          "md5": "88ddace6bd6577871ec675f0613faca2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-f4386a0.jar",
          "url": "antibytes-publishing-f4386a0.jar",
          "size": 94971,
          "sha512": "3d461f8d2eb16f3a47c9851c6ee0e051b26bcc42838d15bdc0cfb51658ecd5b949c27024d5ed64e14aa1f4dce825bdcd0e54f466b33a6d244adadcb8c71299f4",
          "sha256": "2c6f06dc0c39eeb4f67c8a182d7cf78001f376a0cb655b4878c65742dd14fb77",
          "sha1": "4c59d81ee1960f2229f9f34392100ae3d3298482",
          "md5": "88ddace6bd6577871ec675f0613faca2"
        }
      ]
    }
  ]
}
