{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/047a358-add-ios-SNAPSHOT/test-utils-fixture-047a358-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "047a358-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-047a358-add-ios-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-047a358-add-ios-SNAPSHOT.jar",
          "size": 43668,
          "sha512": "4976313b534347873dd5be13544764920af91be5a6527434ee2c4257425a060014f225e8316b02ad6f327376228441bb4c084ecf3f31134d621991869ca3a87a",
          "sha256": "0475cf4972e1e312d6543410fdf542a53334a627345ad1de4a90a04bb600510d",
          "sha1": "1f44b942c4838e2d5b622e657bc2696f7c1d0e82",
          "md5": "3f2c1766653fe600962db3f74dce7614"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-047a358-add-ios-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-047a358-add-ios-SNAPSHOT.jar",
          "size": 43668,
          "sha512": "4976313b534347873dd5be13544764920af91be5a6527434ee2c4257425a060014f225e8316b02ad6f327376228441bb4c084ecf3f31134d621991869ca3a87a",
          "sha256": "0475cf4972e1e312d6543410fdf542a53334a627345ad1de4a90a04bb600510d",
          "sha1": "1f44b942c4838e2d5b622e657bc2696f7c1d0e82",
          "md5": "3f2c1766653fe600962db3f74dce7614"
        }
      ]
    }
  ]
}
