{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "43475c3-change-native-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-43475c3-change-native-hooks.jar",
          "url": "antibytes-gradle-utils-43475c3-change-native-hooks.jar",
          "size": 9577,
          "sha512": "23ea225e49b4700980977ab3f138dcbe523d024b1344b9685439897dfd29faea3bba5ca4b759c8db7faf0481802ef017768b5d94e9725775ab36cb2e58ca84c7",
          "sha256": "2610e164184a2173e7bb42bf0d08a6933e6c30c3628b34f8823dd86fc98818dd",
          "sha1": "97c55c0abe736f8d3e3fc7155f4373a5228a135d",
          "md5": "ff57c2010a32278769b62c91b689f0a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-43475c3-change-native-hooks.jar",
          "url": "antibytes-gradle-utils-43475c3-change-native-hooks.jar",
          "size": 9577,
          "sha512": "23ea225e49b4700980977ab3f138dcbe523d024b1344b9685439897dfd29faea3bba5ca4b759c8db7faf0481802ef017768b5d94e9725775ab36cb2e58ca84c7",
          "sha256": "2610e164184a2173e7bb42bf0d08a6933e6c30c3628b34f8823dd86fc98818dd",
          "sha1": "97c55c0abe736f8d3e3fc7155f4373a5228a135d",
          "md5": "ff57c2010a32278769b62c91b689f0a5"
        }
      ]
    }
  ]
}
