{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/6099f4a-fix-single-sources-SNAPSHOT/kmock-6099f4a-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "6099f4a-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "size": 123325,
          "sha512": "477ff68fd9b22416a88e6f5e19d562aa3dbb7d291ad6a1e52913c2ecd8ae33857065108a64af6584cee0ae8bbe4bcc1ce1c2ffd7eab7642b37fa2dc08307880e",
          "sha256": "0d946142c3912b61eadd445c6e3879156d2a4913c941113b77cafc81b33540a1",
          "sha1": "44f664311547372f9a23c5af7334698635ba8b0f",
          "md5": "051305429e077f54af08c097f1a6bf2b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "56c5f3f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-6099f4a-fix-single-sources-SNAPSHOT.jar",
          "size": 123325,
          "sha512": "477ff68fd9b22416a88e6f5e19d562aa3dbb7d291ad6a1e52913c2ecd8ae33857065108a64af6584cee0ae8bbe4bcc1ce1c2ffd7eab7642b37fa2dc08307880e",
          "sha256": "0d946142c3912b61eadd445c6e3879156d2a4913c941113b77cafc81b33540a1",
          "sha1": "44f664311547372f9a23c5af7334698635ba8b0f",
          "md5": "051305429e077f54af08c097f1a6bf2b"
        }
      ]
    }
  ]
}
