{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "6c63031-change-plugin-cut",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-6c63031-change-plugin-cut.jar",
          "url": "antibytes-android-application-configuration-6c63031-change-plugin-cut.jar",
          "size": 51346,
          "sha512": "bde824220f28d6071ad98949a93e9a7d7cfeed6655eeb3b550aefb0cc920128a056d6c3a6e168a8bcce1be911e2e18d2544898fd906eb457a01b385ccdcab83f",
          "sha256": "c64f8b6b300ec320d48c9e48def7368ec417317d1e63735ff0898ffd378c339b",
          "sha1": "c92e966b2c9be53b56d61a0608784c666f43c22c",
          "md5": "141910d1b5d4ea6584443082c05c08ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "6c63031-change-plugin-cut"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-6c63031-change-plugin-cut.jar",
          "url": "antibytes-android-application-configuration-6c63031-change-plugin-cut.jar",
          "size": 51346,
          "sha512": "bde824220f28d6071ad98949a93e9a7d7cfeed6655eeb3b550aefb0cc920128a056d6c3a6e168a8bcce1be911e2e18d2544898fd906eb457a01b385ccdcab83f",
          "sha256": "c64f8b6b300ec320d48c9e48def7368ec417317d1e63735ff0898ffd378c339b",
          "sha1": "c92e966b2c9be53b56d61a0608784c666f43c22c",
          "md5": "141910d1b5d4ea6584443082c05c08ed"
        }
      ]
    }
  ]
}
