{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 346429,
          "sha512": "ee1bab2e4f21d0e20cebd73aa2e6ec9f02a8e4bb1c192f3034beba8e47064be4135716a80f4b66ed38d467461ebf2077e050d082535db089c81d635053626dff",
          "sha256": "c95a9816af7a6d9a2d8bc285e1e7a4d8d09e9968f983fd89d998fdabd729135c",
          "sha1": "911fd08c7195885c967e2ecfbecc56567b7b9d72",
          "md5": "549c177f3219f35a8736b572cfeaeb6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 346429,
          "sha512": "ee1bab2e4f21d0e20cebd73aa2e6ec9f02a8e4bb1c192f3034beba8e47064be4135716a80f4b66ed38d467461ebf2077e050d082535db089c81d635053626dff",
          "sha256": "c95a9816af7a6d9a2d8bc285e1e7a4d8d09e9968f983fd89d998fdabd729135c",
          "sha1": "911fd08c7195885c967e2ecfbecc56567b7b9d72",
          "md5": "549c177f3219f35a8736b572cfeaeb6f"
        }
      ]
    }
  ]
}
