{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 346429,
          "sha512": "80ddf9f61dfe85752b59ddcb1f8c4e228b91c3b7d28826c3a3a1a8b3644e20bb1ae6b7eb6f9dd2f7d2d2ea0fd3b8f399a7b027fc2bb3be6d3a36b74364067245",
          "sha256": "a2472e22575a2ace0b1295d871f63cdfca61fa14e20b511d5ac7020a4a581108",
          "sha1": "af6500c629c8731131ff9bc6ff0515d67ad2e249",
          "md5": "3b7080557fa23f9b480b53b7c0880f22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-processor-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 346429,
          "sha512": "80ddf9f61dfe85752b59ddcb1f8c4e228b91c3b7d28826c3a3a1a8b3644e20bb1ae6b7eb6f9dd2f7d2d2ea0fd3b8f399a7b027fc2bb3be6d3a36b74364067245",
          "sha256": "a2472e22575a2ace0b1295d871f63cdfca61fa14e20b511d5ac7020a4a581108",
          "sha1": "af6500c629c8731131ff9bc6ff0515d67ad2e249",
          "md5": "3b7080557fa23f9b480b53b7c0880f22"
        }
      ]
    }
  ]
}
