{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/5c5a537-add-runwith-timout-SNAPSHOT/test-utils-5c5a537-add-runwith-timout-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "5c5a537-add-runwith-timout-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5c5a537-add-runwith-timout-SNAPSHOT.jar",
          "size": 17516,
          "sha512": "25e06f9656baf4326ac83e284d1a033807461f57e5c0980b309a0e26fa5fc2a0a9b266cc00902a599a7e1df63c6708a1b34c712fb340dde97d320647b5bc58d9",
          "sha256": "98091d2c336cf1fa79347a7533cafc1433726ba82a0f1675d81a1a9fed497164",
          "sha1": "25025dbafde636864823c0a209b3344ebb613042",
          "md5": "9b703e5f0db6324ab0278b4a22ec39a1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-5c5a537-add-runwith-timout-SNAPSHOT.jar",
          "size": 17516,
          "sha512": "25e06f9656baf4326ac83e284d1a033807461f57e5c0980b309a0e26fa5fc2a0a9b266cc00902a599a7e1df63c6708a1b34c712fb340dde97d320647b5bc58d9",
          "sha256": "98091d2c336cf1fa79347a7533cafc1433726ba82a0f1675d81a1a9fed497164",
          "sha1": "25025dbafde636864823c0a209b3344ebb613042",
          "md5": "9b703e5f0db6324ab0278b4a22ec39a1"
        }
      ]
    }
  ]
}
