{
  "formatVersion": "1.1",
  "component": {
    "url": "../../banana-i18n/763e91a-change-error-handling-SNAPSHOT/banana-i18n-763e91a-change-error-handling-SNAPSHOT.module",
    "group": "tech.antibytes.banana-i18n-kmp",
    "module": "banana-i18n",
    "version": "763e91a-change-error-handling-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-763e91a-change-error-handling-SNAPSHOT.jar",
          "size": 63292,
          "sha512": "151f1dc86f83f5e155b686cfa179ab502d9fd3e6c34c76101ec0df5411f3f2adff72dfe5080aa256cf033c38a53ae6d36ec19bc6d1ff69a5afa92fdf8652537c",
          "sha256": "2aca8a614e5c02dfd4123c128b6d96b0ea46a70ef5d2bf9c5d1f6b42037b1b0e",
          "sha1": "4106d0f689b3ec09309cd2dba98a813157fd9e27",
          "md5": "d54b55fce891f52e5b88e70116e60724"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "banana-i18n-jvm.jar",
          "url": "banana-i18n-jvm-763e91a-change-error-handling-SNAPSHOT.jar",
          "size": 63292,
          "sha512": "151f1dc86f83f5e155b686cfa179ab502d9fd3e6c34c76101ec0df5411f3f2adff72dfe5080aa256cf033c38a53ae6d36ec19bc6d1ff69a5afa92fdf8652537c",
          "sha256": "2aca8a614e5c02dfd4123c128b6d96b0ea46a70ef5d2bf9c5d1f6b42037b1b0e",
          "sha1": "4106d0f689b3ec09309cd2dba98a813157fd9e27",
          "md5": "d54b55fce891f52e5b88e70116e60724"
        }
      ]
    }
  ]
}
