{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-byteArray-generator-SNAPSHOT/core-0.2.0-change-byteArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-byteArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-change-byteArray-generator-SNAPSHOT.klib",
          "url": "core-js-0.2.0-change-byteArray-generator-SNAPSHOT.klib",
          "size": 90247,
          "sha512": "2f191804ef33ede570a5dcaa98e45355e1285170318e459ef2ffe3bfbeee0d88be499fb3d4df6b1648dd75a5e0cbe2b423b4616de9861cdaad349f889df54b0a",
          "sha256": "7adbcf6c5fc83349e6863a48768d59dc86c6bc101d46fe8500644a8715adb354",
          "sha1": "7c0c6e5ac2c9bd7d8cc662189b332612be5e26a1",
          "md5": "f82d622c384691ea290bdfea9ee704ad"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-change-byteArray-generator-SNAPSHOT.klib",
          "url": "core-js-0.2.0-change-byteArray-generator-SNAPSHOT.klib",
          "size": 90247,
          "sha512": "2f191804ef33ede570a5dcaa98e45355e1285170318e459ef2ffe3bfbeee0d88be499fb3d4df6b1648dd75a5e0cbe2b423b4616de9861cdaad349f889df54b0a",
          "sha256": "7adbcf6c5fc83349e6863a48768d59dc86c6bc101d46fe8500644a8715adb354",
          "sha1": "7c0c6e5ac2c9bd7d8cc662189b332612be5e26a1",
          "md5": "f82d622c384691ea290bdfea9ee704ad"
        }
      ]
    }
  ]
}
