{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc07-SNAPSHOT-all.jar",
          "url": "kmock-0.3.0-rc07-SNAPSHOT-all.jar",
          "size": 28226,
          "sha512": "c432946816151b251c42f1da368d505b609d56b139129702712c3984bb89f6362fa1001ad600fff147662431090586253d6a9eaa1cccd8884d1cc2c524b6e65a",
          "sha256": "83396e8eba7ea7c2946d64b48d1743f72e26bf0b662f2adc2256830492e15eb7",
          "sha1": "5a8680d41c9ac3aca47e601ae7c4995f18cae83c",
          "md5": "57970508436ff7f7e8d481337b393ceb"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc07-SNAPSHOT.jar",
          "url": "kmock-0.3.0-rc07-SNAPSHOT.jar",
          "size": 47917,
          "sha512": "f24e31ee0680789097f80340da15709850e91b33d72b610528da2ac6f5b87ee7ad5672d0260ad1f2fc9815d7839ca6ff1cef9942028ec5d4dfe211908fe72668",
          "sha256": "27d03ed80386852f35c3d9a02baa03cfd779e6ada89a7dca4c0eb5c78fcf3f8e",
          "sha1": "8f1337e155d602f4b547c9772ef29331d34e6abb",
          "md5": "2db9a2bb2198d0390a3ed4b89bcc34a9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc07-SNAPSHOT/kmock-android-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc07-SNAPSHOT/kmock-android-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc07-SNAPSHOT/kmock-iosarm32-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm32/0.3.0-rc07-SNAPSHOT/kmock-iosarm32-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm32",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc07-SNAPSHOT/kmock-iosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc07-SNAPSHOT/kmock-iosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc07-SNAPSHOT/kmock-iosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc07-SNAPSHOT/kmock-iosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc07-SNAPSHOT/kmock-js-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc07-SNAPSHOT/kmock-js-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc07-SNAPSHOT/kmock-jvm-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc07-SNAPSHOT/kmock-jvm-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc07-SNAPSHOT/kmock-linuxx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc07-SNAPSHOT/kmock-macosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosarm64/0.3.0-rc07-SNAPSHOT/kmock-macosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc07-SNAPSHOT/kmock-macosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-macosx64/0.3.0-rc07-SNAPSHOT/kmock-macosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-macosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-mingwx64/0.3.0-rc07-SNAPSHOT/kmock-mingwx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-mingwx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc07-SNAPSHOT/kmock-tvosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosarm64/0.3.0-rc07-SNAPSHOT/kmock-tvosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-tvossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-tvossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc07-SNAPSHOT/kmock-tvosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-tvosx64/0.3.0-rc07-SNAPSHOT/kmock-tvosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-tvosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc07-SNAPSHOT/kmock-watchosarm32-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm32/0.3.0-rc07-SNAPSHOT/kmock-watchosarm32-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm32",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc07-SNAPSHOT/kmock-watchosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosarm64/0.3.0-rc07-SNAPSHOT/kmock-watchosarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-watchossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchossimulatorarm64/0.3.0-rc07-SNAPSHOT/kmock-watchossimulatorarm64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchossimulatorarm64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc07-SNAPSHOT/kmock-watchosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx64/0.3.0-rc07-SNAPSHOT/kmock-watchosx64-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx64",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc07-SNAPSHOT/kmock-watchosx86-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-watchosx86/0.3.0-rc07-SNAPSHOT/kmock-watchosx86-0.3.0-rc07-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-watchosx86",
        "version": "0.3.0-rc07-SNAPSHOT"
      }
    }
  ]
}
