{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/048cd7e-change-publishing-SNAPSHOT/test-utils-annotations-048cd7e-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "048cd7e-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-048cd7e-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-048cd7e-change-publishing-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "f4170fae1a7364cefb4f5466838917afa430a62fd8c3ef04abd433468aa17032916180b54315acd827b38342715c4b089639a313c807e89068bce1a684307633",
          "sha256": "0727dc05fe5588037b5a92b5843ad90b06f829d0dce53817a79c4cc57d25681f",
          "sha1": "36fd051a20b38c3edc10883422a765b98fc1e5dc",
          "md5": "e899f5350eb0ed87398b555530797fac"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-048cd7e-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-048cd7e-change-publishing-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "f4170fae1a7364cefb4f5466838917afa430a62fd8c3ef04abd433468aa17032916180b54315acd827b38342715c4b089639a313c807e89068bce1a684307633",
          "sha256": "0727dc05fe5588037b5a92b5843ad90b06f829d0dce53817a79c4cc57d25681f",
          "sha1": "36fd051a20b38c3edc10883422a765b98fc1e5dc",
          "md5": "e899f5350eb0ed87398b555530797fac"
        }
      ]
    }
  ]
}
