{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "5d5a54a-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-metadata-5d5a54a-change-settings-SNAPSHOT-all.jar",
          "url": "test-utils-ktor-5d5a54a-change-settings-SNAPSHOT-all.jar",
          "size": 5199,
          "sha512": "ec548837addd2986d8caa9fe64b4c379b9a014c8fc16c178e51d95bfbf0f01a6141e6448de1cd093719be57c2b3d2433dd300e2ff4b5cf2e672c04da701e754a",
          "sha256": "adbe7b84b210348f8067762d3443e2a4ecc86c93b015917f1ee9645c5652759d",
          "sha1": "17f6ed7f5246db8225b99a3dcc4b112ef77b4de7",
          "md5": "f5dee88aed31fc5f19e1d61e1e339578"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-5d5a54a-change-settings-SNAPSHOT.jar",
          "url": "test-utils-ktor-5d5a54a-change-settings-SNAPSHOT.jar",
          "size": 2502,
          "sha512": "f8f5f87abd95907183fbc6be1e8b393d3a3b3c7e9148695909c3be3823e4781449819e9778838c82e8c797d1cbd947472824dfb8168abe821dba38195d7aa5ae",
          "sha256": "601ad188f8934aaec8191f0efdc0d258cbc8dd1b170f33d0e7362be0cff106d0",
          "sha1": "a2ad43e12d3602be8601c1e6e07dd82424dfa72b",
          "md5": "91d725ad2bf1256155787af1115a69f9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-android-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-android-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iosarm64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosarm64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iosarm64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosarm64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iossimulatorarm64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iossimulatorarm64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iossimulatorarm64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iossimulatorarm64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iosx64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-iosx64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-iosx64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-iosx64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-ktor-js/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-js-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-js",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-jvm-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-jvm-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-ktor-linuxx64/5d5a54a-change-settings-SNAPSHOT/test-utils-ktor-linuxx64-5d5a54a-change-settings-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-linuxx64",
        "version": "5d5a54a-change-settings-SNAPSHOT"
      }
    }
  ]
}
