{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc02-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 75008,
          "sha512": "55eb69f7127e8b905501526bbef97fa5379209a8d43397bd08aebbabd5a21189e459167f0ee0c881f351b6d318bcef03bec95cf323a486c6aff2400af1dd4edc",
          "sha256": "295b7d5e2313fb16968408ae21b1d9b84aebdf21adee3ffb7be1ef0ea6622b14",
          "sha1": "d8f6ea35dd67c24912716163d15a7907194ee80f",
          "md5": "a9bc6db3bc236d4ad3469948915a3760"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.7.0-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT.jar",
          "size": 75008,
          "sha512": "55eb69f7127e8b905501526bbef97fa5379209a8d43397bd08aebbabd5a21189e459167f0ee0c881f351b6d318bcef03bec95cf323a486c6aff2400af1dd4edc",
          "sha256": "295b7d5e2313fb16968408ae21b1d9b84aebdf21adee3ffb7be1ef0ea6622b14",
          "sha1": "d8f6ea35dd67c24912716163d15a7907194ee80f",
          "md5": "a9bc6db3bc236d4ad3469948915a3760"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "f7d44e99ad309b9ce4c90793a00f96ded0092f05cc2ef41545aa39b569dc68409b8d49a215f24d81c1e61e23514c77bba4456141140a4ca11d7cd0a3901337c0",
          "sha256": "17f3479142308f8b82262939cb57b7809c7ad69d6a2d17c1e0dcb642f187c24d",
          "sha1": "2547f72d6280539c78dca6249d96f9c4726237cc",
          "md5": "a12ca309776c550b522777a6a49e18f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc02-SNAPSHOT-sources.jar",
          "size": 15305,
          "sha512": "72e4402c6d9ea1e15ba1a7df42c99b1f3b9ae1d9a439c6c705c27ecbdc50d8a3b7b37b6c67c0a50fbaab1f056b03c197fd6b48d3853aeb74c3cd2f04e244e717",
          "sha256": "481cbdb8781638024cf6c45c44ae93c1110aa44cbcb9ba58da2b35edf9b4d814",
          "sha1": "a42fbe98b32c0df58571398ff116f0675930b53f",
          "md5": "7a45d7110b81b8d32e6f354e98335fe4"
        }
      ]
    }
  ]
}
