{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-d75bc0f-change-coroutines-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "d75bc0f-change-coroutines-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.klib",
          "size": 9733,
          "sha512": "ed6b142ff8b7987cc947fbbeb89a831ab070700edeb84e184352ca8435fa48f97d3863dcaae0d92941b3ce80300b927fc3777baf32e07d20e9f364caa559ba57",
          "sha256": "d7885e373a871635153ea37751a3a54269178aa8203fdd19e92166fc8221e3dd",
          "sha1": "a7b872b3d45add907ef4f261fa81d704cb2457a3",
          "md5": "3f953f83775ade6761629ce30251bfc8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.klib",
          "size": 9733,
          "sha512": "ed6b142ff8b7987cc947fbbeb89a831ab070700edeb84e184352ca8435fa48f97d3863dcaae0d92941b3ce80300b927fc3777baf32e07d20e9f364caa559ba57",
          "sha256": "d7885e373a871635153ea37751a3a54269178aa8203fdd19e92166fc8221e3dd",
          "sha1": "a7b872b3d45add907ef4f261fa81d704cb2457a3",
          "md5": "3f953f83775ade6761629ce30251bfc8"
        }
      ]
    }
  ]
}
