{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-workflows-SNAPSHOT/core-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 105958,
          "sha512": "40a7ed20c8ef0df789fafea3720f01d6c7b3d1229622f0c3df71858c0dbd93e1e56ddb78565634dea6106a559789e8f0b5d9a89a12ce257d652b075ccc7f18b7",
          "sha256": "13f4405aa8515bd33c869905cff6352a26d432b659042af57ee86c38c27f7831",
          "sha1": "1346b8c83ae4d3a534e199d2cabdb5d85b3b69a0",
          "md5": "a6a4540c838c864aed2a5feeee9e39de"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "core-watchossimulatorarm64-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "dd59fb578a415a511d874ae11671eecaaf28bb3f3b3cfdc4228e9f4895426becba2e8c214749df66d170bce17d4c20b0c86ca15a7bb38ac3aaec6b93831935cd",
          "sha256": "22c3ee34181ad51a49a03bca553bc64fe445d3c09e5a73b46a57b776ecf2569e",
          "sha1": "0837ba399bd381274d1e4b26e8e8bb92f6968a7e",
          "md5": "e6967d4e84f1e83ba1e22f257e981781"
        }
      ]
    }
  ]
}
