{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/de45ed1-add-ios-SNAPSHOT/test-utils-coroutine-de45ed1-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "de45ed1-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-de45ed1-add-ios-SNAPSHOT.klib",
          "size": 10106,
          "sha512": "4a9b0d8c6bbf29ff8559ce506c4140361e592a3810e352628bab3fd6f9c249c12dfcb69848e604020a0e587822b6c5f99ade82bdeaec71415f0726a3e008888a",
          "sha256": "c3bea4f9fd5a4e958a9a1b6d1f53c9d203f36f6249be2a6bcca2b1958635377d",
          "sha1": "ab8b1719020ab655506f34a4b6f2ef27d35a9acf",
          "md5": "c00982d032e9baadf7a58f15156d1104"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-de45ed1-add-ios-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosx64-de45ed1-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "71d33ca125aa2a55950b068797b544633172f65686d38ca02287f0e05d112e1ca09569d98b6e5ad6104a3cc671f147c17c6a6924ec3fa1591b5d05fe0d6f5fcb",
          "sha256": "6ddae3252bb6cdfdd467a28d62d76b4f15e2b800a212c864c7d84868a7600d56",
          "sha1": "772853cb59df50a08ac4c9ac9f303a5b5a4126d7",
          "md5": "2576fe201339bbb9adaa4f0074bf13a9"
        }
      ]
    }
  ]
}
