{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/ef3a5b1-bump-updates-SNAPSHOT/test-utils-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 8327,
          "sha512": "631d47512e0a33aff481c24537c727728aaa791abfc44805b8c6c67ddfa7b9063829b9b3dab4228547895d6bd5dc774eafb59e081a67a3e8307d76911744f7fd",
          "sha256": "36e2b3d3a552b41a6b4cec67b8292218c058821d6eef1c66ac7f0600419d476b",
          "sha1": "31e5b24d38939ffaa5c4386dcb8ecf98be650f61",
          "md5": "92cec6aece027a1097bbd228ecb56d46"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-iosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-iosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2775976c5e337ca57923ebd3e7616cceb4c627ee43729c98c285bc701dca14379cee4012f3a6b13f4aea7aed29197048a5d7402416d63920117254404d33df57",
          "sha256": "30da35365381f99f191b157b96124d6cf66fb2e1808bbfb0d91e3203c050433f",
          "sha1": "00bf7e3641ab994cb2aa0a12626cfc40d2c1a99c",
          "md5": "357070f376667af770ec4d6606d06b58"
        }
      ]
    }
  ]
}
