{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "c8719de-fix-detekt-distribution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-coverage-c8719de-fix-detekt-distribution.jar",
          "size": 135187,
          "sha512": "b31dd6821b8b0366647dd9f46e4d205839cd5548d3f7e484a7c727bd51552a7df17bd2cb7dfd0a74e037dff1a7f2b137373f72379207a145f0a1bb285875455c",
          "sha256": "ebcc5100b00ee3bded03797e05d619c91c3c34c190c779e35acb43b05703b03e",
          "sha1": "e34ae414ca987166df5361d4c70cc574c91ad392",
          "md5": "8a2bf13705f09e214449bb13aa7ebbad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-coverage-c8719de-fix-detekt-distribution.jar",
          "size": 135187,
          "sha512": "b31dd6821b8b0366647dd9f46e4d205839cd5548d3f7e484a7c727bd51552a7df17bd2cb7dfd0a74e037dff1a7f2b137373f72379207a145f0a1bb285875455c",
          "sha256": "ebcc5100b00ee3bded03797e05d619c91c3c34c190c779e35acb43b05703b03e",
          "sha1": "e34ae414ca987166df5361d4c70cc574c91ad392",
          "md5": "8a2bf13705f09e214449bb13aa7ebbad"
        }
      ]
    }
  ]
}
