{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/db53051-change-workflows-SNAPSHOT/test-utils-annotations-junit4-db53051-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-db53051-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-db53051-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "9a8a0dd4942997309354cbe8fcb32a337838af9e882f48ad4732913aff778f82da0588c9816cd4dd1d743738ea59d03443b74c3e34fd3b006c60f614dee0b8dc",
          "sha256": "a0d3812c56fc45ed6173a3045f1112e0bf9b391eacc8aea10835cf3aa1f53281",
          "sha1": "7f3dc3b86ac79b45bf2c3c406b21cda5e7be0ca3",
          "md5": "8d8292b91af27b35a704a805490f522a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-db53051-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-db53051-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "9a8a0dd4942997309354cbe8fcb32a337838af9e882f48ad4732913aff778f82da0588c9816cd4dd1d743738ea59d03443b74c3e34fd3b006c60f614dee0b8dc",
          "sha256": "a0d3812c56fc45ed6173a3045f1112e0bf9b391eacc8aea10835cf3aa1f53281",
          "sha1": "7f3dc3b86ac79b45bf2c3c406b21cda5e7be0ca3",
          "md5": "8d8292b91af27b35a704a805490f522a"
        }
      ]
    }
  ]
}
