{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "3cbbc95-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-3cbbc95-add-plattform-hooks.jar",
          "url": "antibytes-quality-3cbbc95-add-plattform-hooks.jar",
          "size": 62601,
          "sha512": "efd3938221492b64a6c0e4e56fdffef3075c5734ce1ffd09ba263dea9b5872634cd0b8ebea2e469f337f101c7e39f965fc05fd653ee4c6984a5ae37fdcc5a433",
          "sha256": "fb4e699dcc4ad6b791afb6cd3f518e3e93840acfd3bf39e99abb9dc51b943b83",
          "sha1": "fd854305f40ad8cffdc8df470cf9ae90aabb2313",
          "md5": "f799cf732609e4effaa4ad8a5410aef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3cbbc95-add-plattform-hooks"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "3cbbc95-add-plattform-hooks"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-3cbbc95-add-plattform-hooks.jar",
          "url": "antibytes-quality-3cbbc95-add-plattform-hooks.jar",
          "size": 62601,
          "sha512": "efd3938221492b64a6c0e4e56fdffef3075c5734ce1ffd09ba263dea9b5872634cd0b8ebea2e469f337f101c7e39f965fc05fd653ee4c6984a5ae37fdcc5a433",
          "sha256": "fb4e699dcc4ad6b791afb6cd3f518e3e93840acfd3bf39e99abb9dc51b943b83",
          "sha1": "fd854305f40ad8cffdc8df470cf9ae90aabb2313",
          "md5": "f799cf732609e4effaa4ad8a5410aef5"
        }
      ]
    }
  ]
}
