{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "838c8d9-add-shared-detekt-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-838c8d9-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-838c8d9-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "dfc931272ef5846f4653925929b82f012454a3a4376456af836dd337a254f995050304cb7b103d9705e2c744dcccde240262039dd19bd047ea3ed83fb24426b3",
          "sha256": "79e4b6727745cd267bd12f876fa7532115977522b9290b40842ddfc262265ca4",
          "sha1": "db5eee6f648ea01da6df2a50fa8e34fdd299b897",
          "md5": "cbd3726fed99f8dc50b62f5783fe7fb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-838c8d9-add-shared-detekt-config-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-838c8d9-add-shared-detekt-config-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "dfc931272ef5846f4653925929b82f012454a3a4376456af836dd337a254f995050304cb7b103d9705e2c744dcccde240262039dd19bd047ea3ed83fb24426b3",
          "sha256": "79e4b6727745cd267bd12f876fa7532115977522b9290b40842ddfc262265ca4",
          "sha1": "db5eee6f648ea01da6df2a50fa8e34fdd299b897",
          "md5": "cbd3726fed99f8dc50b62f5783fe7fb8"
        }
      ]
    }
  ]
}
