{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/30769ee-change-setup-SNAPSHOT/test-utils-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm32-30769ee-change-setup-SNAPSHOT.klib",
          "size": 7962,
          "sha512": "2fc4ccee1addc3cb32356a025da5297edaed25947e4bfac9c334afc2882db9ce82c47607bbe56845bb5c6b570243e373989f2ed0c003c4b3cf346d44548536b4",
          "sha256": "c2b570c058f2f6a9f061c1802776841938a08d50f0d1f7815552290c4290088a",
          "sha1": "3d5c5b4cf5e2b9e21abe9bef700f8d4f3fa0169d",
          "md5": "103fede5a6124eb790461fde2db1573c"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm32-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm32-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bf844fbfdafcf669d16f9e937db6f1a42cc68304d30f0f3febb5b2ed48d333b03651922faafa01d2a51e67cbb96e8f919bc94eb974b4e7df7b178080fd8a459c",
          "sha256": "e0144e82a74b5ee9bf5ad5083f3bb1d623191a659bc0c787f131d5b800edf6c1",
          "sha1": "0c991a1ff50cc03296ef04dfdea43623253e0000",
          "md5": "78028c26108f9231c32fa0aeccf39c37"
        }
      ]
    }
  ]
}
