{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT/kmock-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "2e7e51c106ab093a7fa422f9a32b7893164f0b64280c351b7a0dc12cf697a6c46676cbcb76f02bbbcf14de79e54fc7a4c9b8b288e5ce0aa78a378a6f0194d3b5",
          "sha256": "2a3cc2fc8e2b9ead4c069963c4220233d659fc2982022936f8ff34f1b2e5c133",
          "sha1": "6caaef1c93f5f4c52c932a2af004fc62c8dd7673",
          "md5": "40952084b4f6161b0d34eac98d6a3415"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "2e7e51c106ab093a7fa422f9a32b7893164f0b64280c351b7a0dc12cf697a6c46676cbcb76f02bbbcf14de79e54fc7a4c9b8b288e5ce0aa78a378a6f0194d3b5",
          "sha256": "2a3cc2fc8e2b9ead4c069963c4220233d659fc2982022936f8ff34f1b2e5c133",
          "sha1": "6caaef1c93f5f4c52c932a2af004fc62c8dd7673",
          "md5": "40952084b4f6161b0d34eac98d6a3415"
        }
      ]
    }
  ]
}
