{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT/kmock-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "33fd0020d484fa817769dd6310715d333b6cf634fd51f82657fa3b1c601add7aa6b0ac3d3d00843596c19f8d77fee00bf0857853192c637f6879c8fb610ddc28",
          "sha256": "cc5f737f43e04f2c2c7e007bc5329c17dee8d44ef7159ca45c4f3c7065421a4d",
          "sha1": "96b47a558108b8339303c0605a345b0a002e6585",
          "md5": "09b271c974734fd77326728aa7558183"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.klib",
          "size": 209151,
          "sha512": "33fd0020d484fa817769dd6310715d333b6cf634fd51f82657fa3b1c601add7aa6b0ac3d3d00843596c19f8d77fee00bf0857853192c637f6879c8fb610ddc28",
          "sha256": "cc5f737f43e04f2c2c7e007bc5329c17dee8d44ef7159ca45c4f3c7065421a4d",
          "sha1": "96b47a558108b8339303c0605a345b0a002e6585",
          "md5": "09b271c974734fd77326728aa7558183"
        }
      ]
    }
  ]
}
