{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/856c77e-bump-updates-SNAPSHOT/test-utils-annotations-856c77e-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "856c77e-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "e4107bd74c316b3e2adffdbe6289beea5a28d81a6076354349b853f8a91757182ece80362bdce06351a9bc41a710b0a5af332ca3384dbc8516a6bd620d5cb8cc",
          "sha256": "13a98377c8ae4be68c0b7cb9c928ddbc3eb9384f031745912a057adbc7062b84",
          "sha1": "80310c595f79879b433876ed790cdff1879d83c5",
          "md5": "9bd0bdceb21d91d6df804394ee65bf5b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.klib",
          "url": "test-utils-annotations-js-856c77e-bump-updates-SNAPSHOT.klib",
          "size": 9629,
          "sha512": "e4107bd74c316b3e2adffdbe6289beea5a28d81a6076354349b853f8a91757182ece80362bdce06351a9bc41a710b0a5af332ca3384dbc8516a6bd620d5cb8cc",
          "sha256": "13a98377c8ae4be68c0b7cb9c928ddbc3eb9384f031745912a057adbc7062b84",
          "sha1": "80310c595f79879b433876ed790cdff1879d83c5",
          "md5": "9bd0bdceb21d91d6df804394ee65bf5b"
        }
      ]
    }
  ]
}
