{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/6cf41cd-change-generic-factory-SNAPSHOT/kmock-6cf41cd-change-generic-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "6cf41cd-change-generic-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-6cf41cd-change-generic-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-6cf41cd-change-generic-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "4b3bbc665a9327da722981151072f8a109042d60945cd93dd9e1bb1f96c002f6003bf43b2fdadacc3fd92125d8e3ddfb6661d449fbc872d013dd74dcf4b2f847",
          "sha256": "a00ffc7440e5f7f3dc7addabb632be449ee7de4248eaf3c30f7386a7103d2970",
          "sha1": "958eebd765b5d214161bcff6384c61b7aee99d69",
          "md5": "0890eae6d801bcd8e6bbb52884af4212"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-6cf41cd-change-generic-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-6cf41cd-change-generic-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "4b3bbc665a9327da722981151072f8a109042d60945cd93dd9e1bb1f96c002f6003bf43b2fdadacc3fd92125d8e3ddfb6661d449fbc872d013dd74dcf4b2f847",
          "sha256": "a00ffc7440e5f7f3dc7addabb632be449ee7de4248eaf3c30f7386a7103d2970",
          "sha1": "958eebd765b5d214161bcff6384c61b7aee99d69",
          "md5": "0890eae6d801bcd8e6bbb52884af4212"
        }
      ]
    }
  ]
}
