{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/88e3515-bump-antibytes-SNAPSHOT/test-utils-fixture-88e3515-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "88e3515-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-88e3515-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-88e3515-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "8111b41b3e487ef52ccf2ba23c07245151e3a1bbd44553fd5b002aed84c14a04d3bf8cc64e80f1ca593a7176e70ec7c752cfeadceb23a96928c3a86a1d17e0b7",
          "sha256": "8752fbea5a19f42353f38856d6109f614ed6386c134efd3608c186adfaf0cf03",
          "sha1": "1ef946decc205dec9040b62eb9ec8465ef192376",
          "md5": "fd868c8c1f0a56236b5c81790e58e122"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-88e3515-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-88e3515-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "8111b41b3e487ef52ccf2ba23c07245151e3a1bbd44553fd5b002aed84c14a04d3bf8cc64e80f1ca593a7176e70ec7c752cfeadceb23a96928c3a86a1d17e0b7",
          "sha256": "8752fbea5a19f42353f38856d6109f614ed6386c134efd3608c186adfaf0cf03",
          "sha1": "1ef946decc205dec9040b62eb9ec8465ef192376",
          "md5": "fd868c8c1f0a56236b5c81790e58e122"
        }
      ]
    }
  ]
}
