{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-project-configuration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-project-configuration-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.4.0-change-project-configuration-SNAPSHOT-all.jar",
          "url": "ktx-datetime-0.4.0-change-project-configuration-SNAPSHOT-all.jar",
          "size": 9008,
          "sha512": "156e989bd8bd012d902d526d51f97daa68fb5ab1ae32a7667b37a7f0a08c0e1b4fde06a1c8d1612b2c6fe069e6d258f6726f71354a1547ab372d21fda0d844cb",
          "sha256": "96189d6d9698cd083dfe9c467fda673e71e3ca4d57f7042ef41373900e02b847",
          "sha1": "6a05243efe51c9b5e25e2b8ad766c4ae87a55ef2",
          "md5": "33ec60c969546a52cad53cb6837b5cc8"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "url": "ktx-datetime-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "size": 13895,
          "sha512": "afd2efe6e2ec92ce9069ca3ffd8394b937c3335c767740bcd177a6aace6eed4282acdd4ac78f415882dddf86fefb4f24016f74b01995e74c58fccceb240e0a8e",
          "sha256": "446c73a4ca723c2ca3c851906dde490c5079ff8d5a892caed2fee38f458ceea9",
          "sha1": "c031a910f280bc5e57052176c2f25ff98339f3a4",
          "md5": "55e3af775f42944ef9dfbd91b4c8f53e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-android-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-android-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iosx64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-iosx64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-js-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-js-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-linuxx64-0.4.0-change-project-configuration-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.4.0-change-project-configuration-SNAPSHOT"
      }
    }
  ]
}
