{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.android.application",
    "module": "antibytes-android-application-configuration",
    "version": "1c69a2f-change-android-compile-task",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-android-application-configuration-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-android-application-configuration-1c69a2f-change-android-compile-task.jar",
          "size": 56574,
          "sha512": "8b90cf64f4e1de545f78cd217188ebf936e94898767ee881499f967442bab634ac225e8b1b9b0c56d14b92cc3b3801cb3105d21aaee3358f07a47de159632db4",
          "sha256": "cc17557409462f66681d9c9b76b6ae69035951b1b6c91e534b31797f38cbbf6a",
          "sha1": "1575a1133279371b60862519d7487b588e0dc5ae",
          "md5": "87595955597804d4527ce47dd9a4844a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1c69a2f-change-android-compile-task"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-android-application-configuration-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-android-application-configuration-1c69a2f-change-android-compile-task.jar",
          "size": 56574,
          "sha512": "8b90cf64f4e1de545f78cd217188ebf936e94898767ee881499f967442bab634ac225e8b1b9b0c56d14b92cc3b3801cb3105d21aaee3358f07a47de159632db4",
          "sha256": "cc17557409462f66681d9c9b76b6ae69035951b1b6c91e534b31797f38cbbf6a",
          "sha1": "1575a1133279371b60862519d7487b588e0dc5ae",
          "md5": "87595955597804d4527ce47dd9a4844a"
        }
      ]
    }
  ]
}
