{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "efb8eff-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-metadata-efb8eff-remove-dependency-plugin-SNAPSHOT-all.jar",
          "url": "test-utils-efb8eff-remove-dependency-plugin-SNAPSHOT-all.jar",
          "size": 4542,
          "sha512": "c7f6d6eba43a34d04c37f38c4c4838a16eb38d2df00458b26b761933f085ed530adc8e9ce0d125cf5d75d4b1d5d0cf1b9f218ae7187e023d8f9da2ffb4e69d2c",
          "sha256": "a7848ca1816411a778961ceb0eca0c209736e8f7cda39983c058208621cd14d5",
          "sha1": "6ce9dff0d596b81459ae10828c70a9506df6cdcc",
          "md5": "1f3b8b38d9cf15f7f80d9a6ed7568311"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-efb8eff-remove-dependency-plugin-SNAPSHOT.jar",
          "url": "test-utils-efb8eff-remove-dependency-plugin-SNAPSHOT.jar",
          "size": 2080,
          "sha512": "0234f3e5b53b899fcf38007dc38dafdadfbe2e31971bca3d25a443625713bbbf1b04f848d5b5504ec9444506f697ab726bcc8e75a1fa4a9e14f02e7502ccfd8c",
          "sha256": "ad94041d7b980f8fefe79eb95e0e11e0a0988f47d8a7a9f9f164e41f6870f841",
          "sha1": "cbdbf43c120ecd6495e20d7531eae73a5565a238",
          "md5": "34e028a6ce286daafdfb2553016b3578"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-android-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-android-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iosarm64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosarm64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iosarm64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosarm64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iossimulatorarm64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iossimulatorarm64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iossimulatorarm64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iossimulatorarm64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-iosx64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-iosx64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-js-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-jvm-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-jvm-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-linuxx64-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "efb8eff-remove-dependency-plugin-SNAPSHOT"
      }
    }
  ]
}
