{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/f8d6e50-bump-workflows-SNAPSHOT/test-utils-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 7944,
          "sha512": "25f3a71877f32cf043dac487ebbb53d8da138e0ff58242b257dacc6cf1bffda14f850caf2c5713010be077c95100cdb40bb5033d18e37f52a1886c97a016e47d",
          "sha256": "619be0373b05e0e14ec541377c98618efb15f0cd650e2d89149c0d6ec2a582a7",
          "sha1": "55dd25723d1e0c3bf49f99524aff65c338fdf96a",
          "md5": "8e559a5c6968296c38bd2f011da07083"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "be5dff1e9a51d083b8755ce076a18a6b950c6855d6214543e14218d701c0469695143ab63c5fdc2ab3768d47d8d1685ad3e1fb2ebf7cbec70a2fa4d876e2c3bc",
          "sha256": "fe421ed0e6d1006114df69f34cd6873feaa137142e12740119ec9e11e767726b",
          "sha1": "0d6f555df4b2c0cbc7cd77143e61042bd736c97e",
          "md5": "587adcb54924ed40ef09968faab9c3a9"
        }
      ]
    }
  ]
}
