{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/f27ca7d-bump-danger-SNAPSHOT/test-utils-ktor-f27ca7d-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "f27ca7d-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-f27ca7d-bump-danger-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "6bed5a0106c6e10d29c0cf3ce0df78a4156da155ec197612f520dec850be487f548cb8dd6f33e3c25d515aa2b6593d1ec421ca0c3d2a54439fc75149f1c839bc",
          "sha256": "edc5960b1e09414eb150be7e55d3e076352adb77fe41bb07d6d896f5f432c790",
          "sha1": "b3556c10596b7b3404bd9179e71cb75f7ed848b7",
          "md5": "2e50c8dacb3770d7614bba87a060f39d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm.jar",
          "url": "test-utils-ktor-jvm-f27ca7d-bump-danger-SNAPSHOT.jar",
          "size": 22816,
          "sha512": "6bed5a0106c6e10d29c0cf3ce0df78a4156da155ec197612f520dec850be487f548cb8dd6f33e3c25d515aa2b6593d1ec421ca0c3d2a54439fc75149f1c839bc",
          "sha256": "edc5960b1e09414eb150be7e55d3e076352adb77fe41bb07d6d896f5f432c790",
          "sha1": "b3556c10596b7b3404bd9179e71cb75f7ed848b7",
          "md5": "2e50c8dacb3770d7614bba87a060f39d"
        }
      ]
    }
  ]
}
