{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/e930d3d-change-project-setup-SNAPSHOT/test-utils-e930d3d-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "e930d3d-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-e930d3d-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-jvm-e930d3d-change-project-setup-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "4713d5c41ef779f3436ee3dabe2b3da5372dd2b66046410f1f4d8ffa225742449f31608901adb938036bd8e60159c7319ffaf1b2ce0e87408792aa35ab7084e5",
          "sha256": "59e87166c62694899a932f330d476503409cc58fa9c3c3c44fdcf5ebf5b8007a",
          "sha1": "21fc4dbfb04c49e2c09c8dd23f1c325a857072e3",
          "md5": "bf3db65a24ab266599b7482deac918c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-e930d3d-change-project-setup-SNAPSHOT.jar",
          "url": "test-utils-jvm-e930d3d-change-project-setup-SNAPSHOT.jar",
          "size": 4570,
          "sha512": "4713d5c41ef779f3436ee3dabe2b3da5372dd2b66046410f1f4d8ffa225742449f31608901adb938036bd8e60159c7319ffaf1b2ce0e87408792aa35ab7084e5",
          "sha256": "59e87166c62694899a932f330d476503409cc58fa9c3c3c44fdcf5ebf5b8007a",
          "sha1": "21fc4dbfb04c49e2c09c8dd23f1c325a857072e3",
          "md5": "bf3db65a24ab266599b7482deac918c5"
        }
      ]
    }
  ]
}
