{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/12cf284-bump-updates-SNAPSHOT/test-utils-ktor-12cf284-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "12cf284-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-12cf284-bump-updates-SNAPSHOT.klib",
          "size": 15024,
          "sha512": "3fc74de29cdcfeb51e5f3d088f029442a6394c0ea2c9d69e03d98de2d9b24e8c8062e4ade5b8867fb720307825d41c9f6deee220f2757f7ec03258ae0e5d1390",
          "sha256": "2c9d531555e863a1d053526218e12b434af87dcb03683df053bf5ad2568a6dc8",
          "sha1": "1d2cf4e3f0400e18fd8068af07e463d87ca11339",
          "md5": "ed8c3d163f74fa45075d9eb656c3e273"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-12cf284-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-12cf284-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5b827bd678425d127acc2dcfa7493233464a8f2940cc7db76230e6252e733216d491d2a5d298946e3bd0924efb5922ddc9e7c5b7c6df89eace183f6ff486c076",
          "sha256": "1cefc978c9dd12a4e7e21198c26ddfa32dc2701bd563aa50f6e481dcb8a48c66",
          "sha1": "2a69b49d8cb3b54ff8a78711791e35ce4686479e",
          "md5": "41c7efa8c80718bb951b744ddb53ed5c"
        }
      ]
    }
  ]
}
