{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/d03b409-change-workflows-SNAPSHOT/test-utils-ktor-d03b409-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "d03b409-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-d03b409-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-d03b409-change-workflows-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "5c5f67f51a3d500d8c79f210cb829a81598c16c8307f83213d79b2a955dfb433bd6113f2780de8421dffecef207cbf90f07c6aff62bef56044a75828be803556",
          "sha256": "e7f9a56edef991a626223602252bf9230754b8b7143a75a9abb5dc1a54a3ae11",
          "sha1": "d16f08ea2da8ef75d7ea07a1a5127845bcb4de89",
          "md5": "fb136be0718c53ffa985985c3ad20d67"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-d03b409-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-d03b409-change-workflows-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "5c5f67f51a3d500d8c79f210cb829a81598c16c8307f83213d79b2a955dfb433bd6113f2780de8421dffecef207cbf90f07c6aff62bef56044a75828be803556",
          "sha256": "e7f9a56edef991a626223602252bf9230754b8b7143a75a9abb5dc1a54a3ae11",
          "sha1": "d16f08ea2da8ef75d7ea07a1a5127845bcb4de89",
          "md5": "fb136be0718c53ffa985985c3ad20d67"
        }
      ]
    }
  ]
}
