{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "1367684-add-android-fixture-kmp-sourceset-hook",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "1367684-add-android-fixture-kmp-sourceset-hook"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-dependency-settings-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 15320,
          "sha512": "01095b50b32d9d88ff0f88fbf14f774ee4fe7314e178c40874f7484bc6346e32d414fd31e630f2bed35d1e0b515a6b089d1cdf98b024103fc7fd3133d2902be6",
          "sha256": "c77adae6b40d222966d4c2f80c7698d22a67e08f0949784b931ac48f50938f72",
          "sha1": "65a12338efb7623bdb0940a51bfaf72f84d946e2",
          "md5": "778c0a350fd199058aa6aab247f8e5b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "1367684-add-android-fixture-kmp-sourceset-hook"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "url": "antibytes-dependency-settings-1367684-add-android-fixture-kmp-sourceset-hook.jar",
          "size": 15320,
          "sha512": "01095b50b32d9d88ff0f88fbf14f774ee4fe7314e178c40874f7484bc6346e32d414fd31e630f2bed35d1e0b515a6b089d1cdf98b024103fc7fd3133d2902be6",
          "sha256": "c77adae6b40d222966d4c2f80c7698d22a67e08f0949784b931ac48f50938f72",
          "sha1": "65a12338efb7623bdb0940a51bfaf72f84d946e2",
          "md5": "778c0a350fd199058aa6aab247f8e5b3"
        }
      ]
    }
  ]
}
