{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "f75c91a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-f75c91a.jar",
          "url": "antibytes-publishing-f75c91a.jar",
          "size": 105775,
          "sha512": "69c0730fd3e0be2071bd1410e39490463e5ff533de3deac3ad532e8a00ee04a23d279cd2c36efd978075e594a1095952bf7e30b2efc878c283c9ec63ff685336",
          "sha256": "05823a56465e16811b1c683279fd8b33a7520eb769c19c266b9a983133634f94",
          "sha1": "02eb61748b436cdd33162a9c0549b1aa7ecf0625",
          "md5": "d6f172716db92ab66a960c77f835a835"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.0.0.202111291000-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "f75c91a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-f75c91a.jar",
          "url": "antibytes-publishing-f75c91a.jar",
          "size": 105775,
          "sha512": "69c0730fd3e0be2071bd1410e39490463e5ff533de3deac3ad532e8a00ee04a23d279cd2c36efd978075e594a1095952bf7e30b2efc878c283c9ec63ff685336",
          "sha256": "05823a56465e16811b1c683279fd8b33a7520eb769c19c266b9a983133634f94",
          "sha1": "02eb61748b436cdd33162a9c0549b1aa7ecf0625",
          "md5": "d6f172716db92ab66a960c77f835a835"
        }
      ]
    }
  ]
}
