{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "2dcd1e4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2dcd1e4.jar",
          "url": "antibytes-gradle-test-utils-2dcd1e4.jar",
          "size": 15176,
          "sha512": "a524309b487f9e64271ca54fee997fb59993316be740eb24bbc31f0c64415aa2d240ae4c5962cafc6a3d30b369ace678783b6e8d048de5a96cd2c90f90c7306b",
          "sha256": "1d9df15a3d2d23d9dd669fc7f52c5223a40dd747f12ec645d4631f4eb498bb73",
          "sha1": "c53b2c7f88e764db2fbc277255ec2ae55ea8c666",
          "md5": "772752669385ae927b61ba655046a4dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2dcd1e4.jar",
          "url": "antibytes-gradle-test-utils-2dcd1e4.jar",
          "size": 15176,
          "sha512": "a524309b487f9e64271ca54fee997fb59993316be740eb24bbc31f0c64415aa2d240ae4c5962cafc6a3d30b369ace678783b6e8d048de5a96cd2c90f90c7306b",
          "sha256": "1d9df15a3d2d23d9dd669fc7f52c5223a40dd747f12ec645d4631f4eb498bb73",
          "sha1": "c53b2c7f88e764db2fbc277255ec2ae55ea8c666",
          "md5": "772752669385ae927b61ba655046a4dc"
        }
      ]
    }
  ]
}
