{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b4fc57b-add-size-to-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-ktor-metadata.jar",
          "url": "test-utils-ktor-b4fc57b-add-size-to-fixture-SNAPSHOT.jar",
          "size": 2460,
          "sha512": "a5a8a84918da85679a1978d53ebf4c51c67ada1f9c34bf13ad21fba10f59c622489a231f600a880fc2e35e033a68c2196529f285252d1a428e4c04465bc046c2",
          "sha256": "9a75c5fe0265ab5981d392f292e2699075739fd7628c90f3ad6704f2df409dcf",
          "sha1": "33ba7547b888716b921556c8bd8e0d13dd9e8f38",
          "md5": "4dc07fff09ddd2a5d2681facf963da0e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/b4fc57b-add-size-to-fixture-SNAPSHOT/test-utils-ktor-android-b4fc57b-add-size-to-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "b4fc57b-add-size-to-fixture-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-android/b4fc57b-add-size-to-fixture-SNAPSHOT/test-utils-ktor-android-b4fc57b-add-size-to-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-android",
        "version": "b4fc57b-add-size-to-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/b4fc57b-add-size-to-fixture-SNAPSHOT/test-utils-ktor-jvm-b4fc57b-add-size-to-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "b4fc57b-add-size-to-fixture-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-ktor-jvm/b4fc57b-add-size-to-fixture-SNAPSHOT/test-utils-ktor-jvm-b4fc57b-add-size-to-fixture-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-ktor-jvm",
        "version": "b4fc57b-add-size-to-fixture-SNAPSHOT"
      }
    }
  ]
}
