{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-add-more-sources-SNAPSHOT/ktx-datetime-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-iosx64-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 34633,
          "sha512": "c88e5c39cd1d3e436131eac99b36142e79cbc5e0ae602f2587b2ec563cc58d2373dffc114763b6b4450f6d91a98b389002d0abee158d707717cd806b4823c552",
          "sha256": "e0d4b1f27a981f5784e9f1e2b7b2373ad26bc1320683f17d66fe5f539e2df58b",
          "sha1": "2ee6f98d5effa1e56e9ddc3c912b09efb80a7ea2",
          "md5": "876dbe675d595e0b819f4e3e3b9b7f2f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-add-more-sources-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-iosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-iosx64-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7144e687a8b255117793fe6a9511eaa1f9e929b7d598764d933d5d8cb20536874ebaf360439853207055fdef62dd8bd86b6fb139a4dfb428cb3214ff78a7a491",
          "sha256": "af96ba8092536488b1d74e771f620c13f7ed7de3860652dc997da61f7f67fb28",
          "sha1": "108205f960ad66a1ac4e7735b7f0e827af673c3b",
          "md5": "54e050e2c56e5db546f72a47268d71cc"
        }
      ]
    }
  ]
}
