{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "efb8eff-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 7944,
          "sha512": "25f3a71877f32cf043dac487ebbb53d8da138e0ff58242b257dacc6cf1bffda14f850caf2c5713010be077c95100cdb40bb5033d18e37f52a1886c97a016e47d",
          "sha256": "619be0373b05e0e14ec541377c98618efb15f0cd650e2d89149c0d6ec2a582a7",
          "sha1": "55dd25723d1e0c3bf49f99524aff65c338fdf96a",
          "md5": "8e559a5c6968296c38bd2f011da07083"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "349f318e936f74ded514de6114057e66250148a9f38a8d268913c9256d0237aecd3ffed2a06fc049ba8b7aa5d42177599fdaabb2df63c3caa485c673b6ec74f7",
          "sha256": "1075016217c999254ed4452e3de0d4e906bddbd0a4c7c898131162822647b9c8",
          "sha1": "ad8a1256f684cde7c5a926de538467ce31e2d7d1",
          "md5": "3d2974474a6e274155db32f9852d853c"
        }
      ]
    }
  ]
}
