{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "c8719de-fix-detekt-distribution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-c8719de-fix-detekt-distribution.toml",
          "url": "antibytes-dependency-catalog-c8719de-fix-detekt-distribution.toml",
          "size": 233416,
          "sha512": "47730cca44680ebd59b34f32c7c7800312796e0a61f0fc89c25e04de8fde7189cd18aa965a0102549f9be2b2e93b3f6ace83a693dae53889fb4d37b56bc52e2b",
          "sha256": "312f55c5cd37add9b52b3911148211222f35d2fc275851c88f78a03916c86e3f",
          "sha1": "2c8f8f4b2f93da5f252131f8c34e3b7522c9ea61",
          "md5": "6e79f400e6eb2e4bc509ae6c762cc1d2"
        }
      ]
    }
  ]
}
