{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/6befa46-bump-updates-SNAPSHOT/test-utils-6befa46-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "6befa46-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-6befa46-bump-updates-SNAPSHOT.klib",
          "size": 14299,
          "sha512": "0e804765cf59a9de4515bc61295a685b8f9fdd70190de83af5a2390ce33eff7206dcf8927bd286aef157b7069007ff9406f3a13e7f151543e23caf2ea4ac71b8",
          "sha256": "e9a41232638f5fb5d45085c9a5cc533abf3e5a88fca4f7cc348ee55b0a288aeb",
          "sha1": "c157282ae310c0c389477642217ea5fc2c08aefc",
          "md5": "d682f8ea504b651e47e2f2ea30a4f23a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-6befa46-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-6befa46-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1e9207c1adf78a874e7546e97689bbe549d22729a7fad4f4e5f0018dd704f3b65c2a154010e0761a93cc0f9378ba51921e795a37bdc23e13ba760e25ea8fe40b",
          "sha256": "9403848af666711fd589a77a7f10f2cf08826e477c7311d325f667d19b12bd41",
          "sha1": "cd722ec708d6cb6c03cf665c1574f674bdd59aca",
          "md5": "ee693089bca2e51329e5f16438c38d8a"
        }
      ]
    }
  ]
}
