{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/6367305-change-extensions-SNAPSHOT/fixture-6367305-change-extensions-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "6367305-change-extensions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosarm64-6367305-change-extensions-SNAPSHOT.klib",
          "size": 43576,
          "sha512": "2294f9bf5ffd2554722bfd64de9c13ef36f59c658ec715236428e3a7d3ef2e443c1a04b3653f3ba3dd197da3cc9b8a492257a58dfbdf68bb8d0ae3993b365d9b",
          "sha256": "436e008ffee0945023c089bc1112ce332610d1df2d09931802d97c33b451ba07",
          "sha1": "c15659db3b921b657a37734809c4c27b0dc8c1fa",
          "md5": "14f3fa83dcb555e365887fceb043c1dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosarm64-6367305-change-extensions-SNAPSHOT-metadata.jar",
          "url": "fixture-iosarm64-6367305-change-extensions-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9423afa0c5e2119e49d30f0f45765ee74f82df4283dd1364d76bdc76d8fb9470a5044ab3d698063a4d0258ad315ecd886d64feb31a211ee42cc0bd0c2e58c10d",
          "sha256": "824070bb01329c67106c79eca735f0f15f17fab718be42907ca261dc3e5edde6",
          "sha1": "85a2cea8b4cd7be196727a4379dd020fd86fb85f",
          "md5": "cfaa1dc9759cd31190591feb775bcfec"
        }
      ]
    }
  ]
}
