{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-metadata-6ef02bc-fix-js-runBlockingTest-SNAPSHOT-all.jar",
          "url": "test-utils-6ef02bc-fix-js-runBlockingTest-SNAPSHOT-all.jar",
          "size": 5390,
          "sha512": "fe6a413d1c0564028b23752375cd6c5b651426498ce7a8d67325704417557f69acbb4e5b3d29970f1f4427680499069a6d2faa47d6b680b7ada8e76793640ead",
          "sha256": "a3f8f4ec441cab79dddbde85df20ef95689dfcd6cb2274348765b4e76df8e2fc",
          "sha1": "1edabcfd3a4f35f2f5ecfeb7e8564ae35b16b399",
          "md5": "1b3155497eff45818e42e0a5485fa496"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.jar",
          "url": "test-utils-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.jar",
          "size": 3960,
          "sha512": "ab87c6d6c0092e20e9c8e289e9eb9ff98a36fa2f4dd045c0e56cfb9bee425101b0f7fe33da5ed0b4af0cf080c7b03d463a15dbc74403c9f20b54e02795e9152b",
          "sha256": "c72a037d3350428a962a0c9441c341024bcfc98bcb72e77aca258633b8e02221",
          "sha1": "95af6dd1cb7736d691dea3581e82e8cf4c8d8da4",
          "md5": "0bb4b4599d0c1db92a421eb7e11ff521"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-android-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-android-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-js-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-js-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-jvm-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-jvm-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/6ef02bc-fix-js-runBlockingTest-SNAPSHOT/test-utils-linuxx64-6ef02bc-fix-js-runBlockingTest-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "6ef02bc-fix-js-runBlockingTest-SNAPSHOT"
      }
    }
  ]
}
