{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-instant-fixture-SNAPSHOT/core-0.3.1-add-instant-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-instant-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "size": 110266,
          "sha512": "ed7d4d5abc4c502ca882ff9fa3ae4a5726df75fe1f4e37b1a304e2e7de4f183cf73eac1b05de52be8c1aaeb6d21ccb1bcdf88c497ba4b4ccd2c6f31cdb27ceba",
          "sha256": "1b749d35a0e8dd89b9fd10e210d6e85cdce73607b591147b8173b2940c821db4",
          "sha1": "47c5d4cd88323fae444420d623c4cfd17e3423b1",
          "md5": "4269385a11049814dd25a17d4ff762f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.3.1-add-instant-fixture-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.3.1-add-instant-fixture-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ebb96fe6aedfa07e78f4a8cbd78e4b300d14e6527fdfd185239dfbcf36415e4717dc76cd5699c952261b65f73d24d0326958917d05adc2ac8d271a8899af92fe",
          "sha256": "4106e354cfe53c916fb6fd41617405b0df5ad9eed089d959b8684c042dd81ff9",
          "sha1": "1a688a2fdf924aaa4b036b76d04fe28aa864ad91",
          "md5": "0a7bbfc7116f01ee0898c81721d0be3b"
        }
      ]
    }
  ]
}
