{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/13f09a8-add-more-sources-SNAPSHOT/test-utils-coroutine-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-macosarm64-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 10147,
          "sha512": "4a4b143a047f59d96264d5d05d5bf52b7cbaaf5bd23b89980f0026caccb8c88e6a1437953dc3dfe154d961816107268bf4b496c7f842488c7b1071f37ac4d7f9",
          "sha256": "16a4d4623cb52060f0913a982c003f1801268bc32ae22214c56a0753e5f6d04e",
          "sha1": "95c0c2c0ece45d7187e908f02792185b6e1b4163",
          "md5": "75452055926e257bb097177f4545d7bc"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-macosarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-macosarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d18e1a6ee1c2231e44fc925b085ef6cd87f5352634ed3d27498ed6bb126ad05de0b1a3608e524bc53b75ee224c62e396f6e8c7da7527d486f738768cb81e9266",
          "sha256": "6dc7e9cd6bda457ab2486ddc3091366fd7f0ed1079cd61c67e8fb056f12f54c8",
          "sha1": "7f2e42cd3e5f3d49283773c958b83eadbece3a36",
          "md5": "ba2726d8643858de21edc4a4c10087de"
        }
      ]
    }
  ]
}
