{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/439f307-change-project-setup-SNAPSHOT/test-utils-coroutine-439f307-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "439f307-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-439f307-change-project-setup-SNAPSHOT.klib",
          "size": 10215,
          "sha512": "20f8faf97ffe763f21a5727be08c7cc050477ad101cf5fcf7173e9ddbe61e09ad64024ed4ac84f526406d32dada6786171cb15ed0140b91d8c0099e9b3e42c52",
          "sha256": "b5ee960a0de26f99ed0dae68d0108fc1f8a3ffb5ce966589d0682b49fd80510d",
          "sha1": "b306a632a58df0d61fcd0d72b06743ddc98ed3f8",
          "md5": "d0c2d9c2207c602d76d9a6491b30bff1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-439f307-change-project-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-439f307-change-project-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e0c4116fa7c3df5660ed8b537c3c5c408ad9cf4ad24cf4c03242b581fe501e311f05ab09c2c423e6537140076aae7c9b14d642547f1c4228180d86c26c9a6fed",
          "sha256": "c531820cc4361b788385c049eb95773e49dcecb1283eecc6ae89440837eb903e",
          "sha1": "92c6c7cdc3a687ca45b31215dd0c5bb0f030a3af",
          "md5": "3c7b45763616cca66be43d02f87bf9b8"
        }
      ]
    }
  ]
}
