{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/5d5a54a-change-settings-SNAPSHOT/test-utils-annotations-junit5-5d5a54a-change-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "5d5a54a-change-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-5d5a54a-change-settings-SNAPSHOT.klib",
          "size": 7049,
          "sha512": "e82644416b7480c0e1e297e8b55903278dd59dcbe80a4aba35c969a5d55202c1b0fcb1a6cf5fac3b3cee4945a57f44ba15fcfdd82d726015f92482799375c2a1",
          "sha256": "cf3ab81b6becab5c1e36f156abf3ed0cac8ea12777f2a8d7242ca76b377c13df",
          "sha1": "f2399643618d581a8b56df40dbfe051f03472ef1",
          "md5": "8e92a1493a8e1a501e163317c9ffd25e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-5d5a54a-change-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-5d5a54a-change-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ca1005567d1ab31507fbe5b107114300f17e85330efac4cd26d0b34b94aa7d5507f08e3855a9a2dbfb92eabaefee3ccfc160d49f4c6375cae7b105e46021af09",
          "sha256": "11a3dd196340b57893299c64304cdd8b7a90d5cc057602532e12f04d4c17a53b",
          "sha1": "f42860cc89cf77a93f08135e3b0d917b93a8d480",
          "md5": "595e9c731f0a6e95c0e23d31b9e70746"
        }
      ]
    }
  ]
}
