{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "5aacabc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-5aacabc.jar",
          "url": "antibytes-grammar-tools-5aacabc.jar",
          "size": 39410,
          "sha512": "91454604df6af3d805c5119759cc3bd2e03ac26ded27c426026f0cb1eced7e80d1fb49c9c25962a237910dd30cf48b75d90f61abf1b2076d0cfb011722910cc8",
          "sha256": "f7c7c49bd5221a3eafd383da18c61f124a931788849ed4120712dbe23003de23",
          "sha1": "aa282e49ee1d45459ba9e217bc7030318196f1ce",
          "md5": "2c7350f417f0a7fc5ba8f46183b0af62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-5aacabc.jar",
          "url": "antibytes-grammar-tools-5aacabc.jar",
          "size": 39410,
          "sha512": "91454604df6af3d805c5119759cc3bd2e03ac26ded27c426026f0cb1eced7e80d1fb49c9c25962a237910dd30cf48b75d90f61abf1b2076d0cfb011722910cc8",
          "sha256": "f7c7c49bd5221a3eafd383da18c61f124a931788849ed4120712dbe23003de23",
          "sha1": "aa282e49ee1d45459ba9e217bc7030318196f1ce",
          "md5": "2c7350f417f0a7fc5ba8f46183b0af62"
        }
      ]
    }
  ]
}
