{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/ad28a6d-remove-dependency-plugin-SNAPSHOT/test-utils-resourceloader-ad28a6d-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "ad28a6d-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 12951,
          "sha512": "ef348779e4f1a42ca14d1dd5d6094f4b858a6ef6384c064af86a44b80f149a4a46f326676f3f5393fd964d4ec2669d7f49fdfa989bc2db6cd7a034b165ab10d3",
          "sha256": "31e73ccaffabdf9994f5dc643372a6f48ac9f9a19901d96122bdcf6c17c5f997",
          "sha1": "2999a2a2e1f8572af551acb6600ae6a6aa5eed48",
          "md5": "66321d6a894f9bdf98de4e775614d366"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "db64234173ceb84d0b58539aaaf8d3b525c6a5e5e51d55b7ec064428be595c7c8e7fc9be1cc341327d9076bf51d9a9f2dfd703d380e78c3fb8e911e7a4dc55cf",
          "sha256": "ed5ef1f8b8b524e8116534286df9e954adc6ab5321ea1d057a8e3b3e6dd463e2",
          "sha1": "746e0eeffbbc16f175b340b748c163d8e1a0d4cb",
          "md5": "96f0d7a4d5be3731fe2f4be251afc904"
        }
      ]
    }
  ]
}
