{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/dac75a8-change-workflows-SNAPSHOT/test-utils-coroutine-dac75a8-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "dac75a8-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "bac71fc1fca206a5af763d87f1534abf69dec4f1b9ad5978ed5b67e91044fef06b64f0b148eb7927168a4566e776a595c5287fa43f7788edcbd24c20b04df688",
          "sha256": "ab387c810d05717c0af18b4b725d9f51262b8512c5f4791eb017c1ccbfcbeb67",
          "sha1": "9f3ffb0129db4667e21b57983b8cffee24f23a1b",
          "md5": "ce2e44f9e29a7450ac8d858aa6cd4d87"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "bac71fc1fca206a5af763d87f1534abf69dec4f1b9ad5978ed5b67e91044fef06b64f0b148eb7927168a4566e776a595c5287fa43f7788edcbd24c20b04df688",
          "sha256": "ab387c810d05717c0af18b4b725d9f51262b8512c5f4791eb017c1ccbfcbeb67",
          "sha1": "9f3ffb0129db4667e21b57983b8cffee24f23a1b",
          "md5": "ce2e44f9e29a7450ac8d858aa6cd4d87"
        }
      ]
    }
  ]
}
