{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "db9451a-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-metadata-db9451a-bump-updates-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-db9451a-bump-updates-SNAPSHOT-all.jar",
          "size": 10420,
          "sha512": "1d8de8517d96423a84044e1dfbff8e45baaa49dece6a7c2d6f77b60adc5f4bafc715d1906f503d5d7a75e01355aa575850a54646cab08eb5333733d6ffff4d6c",
          "sha256": "a84bf137d0864c1673db24e5a88263d91dd106ca6803383fd5da93e8df3062dd",
          "sha1": "ad57983abeba9094bf05aa1cc0bf335c00562060",
          "md5": "3d0d206728515adfd5abf0ca8c84b958"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-db9451a-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-db9451a-bump-updates-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "bfa5d3e8983c7a574d814687d33865fe4706fef3da4ccff045ea453b8ec72e8dd79687de76fc6caa992b2d3157e63b4a5be1512a0fcdb22995fb3a0be756646f",
          "sha256": "f0eec1db45d56baa23322196706e000b32565db666c67fcb30532b36cf4b81c2",
          "sha1": "15a2cfa57aee98deafe34f24df5cfa7095d3578e",
          "md5": "ce73b51ec7bc9870ca26ae9d2eb6c97c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-android-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-android-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iosarm64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iosarm64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iossimulatorarm64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iossimulatorarm64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iossimulatorarm64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iossimulatorarm64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iossimulatorarm64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iossimulatorarm64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iosx64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-iosx64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-js-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-js-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-jvm-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-jvm-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/db9451a-bump-updates-SNAPSHOT/test-utils-annotations-linuxx64-db9451a-bump-updates-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "db9451a-bump-updates-SNAPSHOT"
      }
    }
  ]
}
