{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/dac75a8-change-workflows-SNAPSHOT/test-utils-ktor-dac75a8-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "dac75a8-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iossimulatorarm64-dac75a8-change-workflows-SNAPSHOT.klib",
          "size": 15112,
          "sha512": "f6806f23abd2aa4b59e085a314019581c11a0261c20c1c72efcc189d6e717907ba9b0a368f76813b329bba41404de8f1297be6f879ff788754a6811b99cb181e",
          "sha256": "7864dbddda6682a12e2792d772d1dfc7fe0c401877f4be31cd7772779b5a7e88",
          "sha1": "d91df1894222c777a76efd4e94a09639bd32f957",
          "md5": "a66e376179d5e04d270847e48eba3bcb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iossimulatorarm64-dac75a8-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iossimulatorarm64-dac75a8-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "aa4f9bab4ea635af3e46bb80955718333702b8cf25622dcc33800f0ac29a9a7a1e73436b2cc57f4c9c0d255ae618bd4888e2d5f0085137638345025e4ef6f61c",
          "sha256": "5c6116141afae171bc406fde5aa5ea834c83c84b96bb03531af6f2af27f3ad17",
          "sha1": "7fc8d147dd7d3b11a3c5653e74bd268cf4658d27",
          "md5": "40c39fa8af46ff9d5d73290b9094a922"
        }
      ]
    }
  ]
}
