{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit4-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-694b583-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-694b583-change-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "98861af4282a0702aa938c14ca36cb4c7c53c795d8f675914556ac31cde1629603a7804416167bc57e1aff63a2f13c450fd28dbaa8b76c5d03d4d95b8d5b614d",
          "sha256": "1279beb2700571ae74ae5598b3831298042197fdc13189dc178771da485d630c",
          "sha1": "f6135814a763d1fe8a80dce53778e3ddcc329734",
          "md5": "95c80e9a541f06c90957b8a1b6045512"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-jvm-694b583-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit4-jvm-694b583-change-setup-SNAPSHOT.jar",
          "size": 10931,
          "sha512": "98861af4282a0702aa938c14ca36cb4c7c53c795d8f675914556ac31cde1629603a7804416167bc57e1aff63a2f13c450fd28dbaa8b76c5d03d4d95b8d5b614d",
          "sha256": "1279beb2700571ae74ae5598b3831298042197fdc13189dc178771da485d630c",
          "sha1": "f6135814a763d1fe8a80dce53778e3ddcc329734",
          "md5": "95c80e9a541f06c90957b8a1b6045512"
        }
      ]
    }
  ]
}
