{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "1d2e1cf-add-additional-source-configs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-grammar-tools-1d2e1cf-add-additional-source-configs.jar",
          "size": 39394,
          "sha512": "63d9a68d214390c846c05e8876fcdf2252fac746181d7409a18acd285a9c570f8a835972798d965c69cc0a6e95ea8cb21d23271278bd2a73ba84430331cbdd38",
          "sha256": "a0f5a63dc1e291d12afacc5f50925519325d10a068319aa1db740f2a2b007506",
          "sha1": "d755b924319522e61e5daed8a604b091df636672",
          "md5": "8ec4824a3cb724537ae1400da1398b52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-grammar-tools-1d2e1cf-add-additional-source-configs.jar",
          "size": 39394,
          "sha512": "63d9a68d214390c846c05e8876fcdf2252fac746181d7409a18acd285a9c570f8a835972798d965c69cc0a6e95ea8cb21d23271278bd2a73ba84430331cbdd38",
          "sha256": "a0f5a63dc1e291d12afacc5f50925519325d10a068319aa1db740f2a2b007506",
          "sha1": "d755b924319522e61e5daed8a604b091df636672",
          "md5": "8ec4824a3cb724537ae1400da1398b52"
        }
      ]
    }
  ]
}
