{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "1d2e1cf-add-additional-source-configs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-dependency-helper-1d2e1cf-add-additional-source-configs.jar",
          "size": 70760,
          "sha512": "5e6aa79c45b1f9ddf274e0cac71555a83132daf5ee1ecae1099e32333dcaf01acfddd0a49571c36d2345bfd291fea0523b0ab58b5b6ab8fda829f6d0fb013ff4",
          "sha256": "ac6a58e4e86f1a5b07b5c4b38bad47cecc4a71abbd1049eff67b0a19ecb9a83c",
          "sha1": "09d414ae21fa80d13f3a3f11efe3ec2c96850e73",
          "md5": "08d84fef5ff70ae9c2fe43bb7ee74507"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1d2e1cf-add-additional-source-configs"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-1d2e1cf-add-additional-source-configs.jar",
          "url": "antibytes-dependency-helper-1d2e1cf-add-additional-source-configs.jar",
          "size": 70760,
          "sha512": "5e6aa79c45b1f9ddf274e0cac71555a83132daf5ee1ecae1099e32333dcaf01acfddd0a49571c36d2345bfd291fea0523b0ab58b5b6ab8fda829f6d0fb013ff4",
          "sha256": "ac6a58e4e86f1a5b07b5c4b38bad47cecc4a71abbd1049eff67b0a19ecb9a83c",
          "sha1": "09d414ae21fa80d13f3a3f11efe3ec2c96850e73",
          "md5": "08d84fef5ff70ae9c2fe43bb7ee74507"
        }
      ]
    }
  ]
}
