{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03-SNAPSHOT/kmock-0.3.0-rc03-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "842c3a0a70f930fd29dba544158da1b73417c6851cb22460ce3b4858ee1dcbea56de2223b84a0bf5401af53983aebc71292da5e707364e30f6483f0903edc112",
          "sha256": "4d50e8b0beab947a4e4e678f66d06abd98d6ee5b0a8fedc4bb478c5b208b8f13",
          "sha1": "de17d1d062775ba09906284e482266ea79f8e84a",
          "md5": "90ff9606f30ac79b71cf18797861b45d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc03-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc03-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "842c3a0a70f930fd29dba544158da1b73417c6851cb22460ce3b4858ee1dcbea56de2223b84a0bf5401af53983aebc71292da5e707364e30f6483f0903edc112",
          "sha256": "4d50e8b0beab947a4e4e678f66d06abd98d6ee5b0a8fedc4bb478c5b208b8f13",
          "sha1": "de17d1d062775ba09906284e482266ea79f8e84a",
          "md5": "90ff9606f30ac79b71cf18797861b45d"
        }
      ]
    }
  ]
}
