{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "36e6875-add-multiplatform-compose",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-36e6875-add-multiplatform-compose.jar",
          "url": "antibytes-dokka-configuration-36e6875-add-multiplatform-compose.jar",
          "size": 7889,
          "sha512": "d4e06e3f1b741026b60ddad05115dc6485ac7834ef580b8fdef60095d32050a4dda224d8750786f9fc8e5e968c644de38b087560eefc82c11c9da9d325268faa",
          "sha256": "ea1e468427d4360da5c518c2e2fb48993ff5e8d9b1c2a15c8ced8eccd43c4a27",
          "sha1": "b70ddc3435bd71d0cd91d46ae431c13cfdf9378b",
          "md5": "e1fdffa4a84fee8ffb1f25edff5e41b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "36e6875-add-multiplatform-compose"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-36e6875-add-multiplatform-compose.jar",
          "url": "antibytes-dokka-configuration-36e6875-add-multiplatform-compose.jar",
          "size": 7889,
          "sha512": "d4e06e3f1b741026b60ddad05115dc6485ac7834ef580b8fdef60095d32050a4dda224d8750786f9fc8e5e968c644de38b087560eefc82c11c9da9d325268faa",
          "sha256": "ea1e468427d4360da5c518c2e2fb48993ff5e8d9b1c2a15c8ced8eccd43c4a27",
          "sha1": "b70ddc3435bd71d0cd91d46ae431c13cfdf9378b",
          "md5": "e1fdffa4a84fee8ffb1f25edff5e41b1"
        }
      ]
    }
  ]
}
