{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "265550cc4abccf8514cc2010212104828d280c101704ad4790ca486b6f2ed8b91cff578772f80469d92ef5198cd9c80b8d12bb7bbc424a19a29d69f63b189d78",
          "sha256": "332bd314c3afeca78f9427a2573aee921f7272cb0e9b3cbad1f13989f188254d",
          "sha1": "ea23320eaa0eaeab840c0a1d999ededa5612aa8a",
          "md5": "2029b6318fa9a8c26ff80c64a21efbc5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "45e569423ec1a8fd6f5508be3cef4ea198e5d54392e2aab871a94db3935ecc3462331c0ef27f273ec1c02803b65edf08c13d5f557ddf6e1e46ff53f70c5363c7",
          "sha256": "553205db062386cc19cd6794a02d013cc594c2cff18161f24f83d8e55fc1de49",
          "sha1": "625046d535123cc2503195627ac1e6174d493a43",
          "md5": "48a7992dd1879d25f4ee4ad5b8763109"
        }
      ]
    }
  ]
}
