{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/890017b-add-class-cracker-SNAPSHOT/kmock-890017b-add-class-cracker-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "890017b-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-890017b-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-890017b-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "f032fd57071ef81b53c5c3a81a27de41fecb356e4a730ca255e72c5f1446424b12bb311e61a2555a384232b9a492642b1fabf8bd48f3d4909d77fb0d4db7c0e3",
          "sha256": "69f5a67db42091b00284b6b2afed72a0bcdabe286b65e0d986aa3b452290ea5a",
          "sha1": "4af498419465d5fcdf16302c103e4193465cada8",
          "md5": "632f0855da19999bbf1d8ae6fecc5d68"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-890017b-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-890017b-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "f032fd57071ef81b53c5c3a81a27de41fecb356e4a730ca255e72c5f1446424b12bb311e61a2555a384232b9a492642b1fabf8bd48f3d4909d77fb0d4db7c0e3",
          "sha256": "69f5a67db42091b00284b6b2afed72a0bcdabe286b65e0d986aa3b452290ea5a",
          "sha1": "4af498419465d5fcdf16302c103e4193465cada8",
          "md5": "632f0855da19999bbf1d8ae6fecc5d68"
        }
      ]
    }
  ]
}
