{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "4c324f2-change-quality-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-configuration-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 59750,
          "sha512": "9f9da81180548f91013149b8a21770bbaf8a780bf208f4708f643383ade112ca857635a86896041607c85b266b22372423de384400df2519a032c32b356e1e22",
          "sha256": "2c59df71e6ee353a1c93a01fea169bb3f3105f38b0245289823ee5d279b820fb",
          "sha1": "b7bac522a2b9892d94a3b5ce0b681dcd42f263e6",
          "md5": "474e58ee80449035fb0188326fd525f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4c324f2-change-quality-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-configuration-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 59750,
          "sha512": "9f9da81180548f91013149b8a21770bbaf8a780bf208f4708f643383ade112ca857635a86896041607c85b266b22372423de384400df2519a032c32b356e1e22",
          "sha256": "2c59df71e6ee353a1c93a01fea169bb3f3105f38b0245289823ee5d279b820fb",
          "sha1": "b7bac522a2b9892d94a3b5ce0b681dcd42f263e6",
          "md5": "474e58ee80449035fb0188326fd525f4"
        }
      ]
    }
  ]
}
