{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "eb5c018c302040c497855b09ddc9992dbee6beb776786101ac6acf31ca9d359729648ca33093d00a2baa48d263df5f3e5c2510ee58b93cd3d741208d67e79941",
          "sha256": "5720c1db3183b053a34b3d78a9c3a2b35c0d4ee26458eb7e93c225175a726308",
          "sha1": "97acd61ec85443383a460fa1155dfb56bf586487",
          "md5": "841d3784ef0a64c328270fd0ecb6e8ad"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-watchosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "124f4496cc1cc54a239f720c8889549bb6367d9c7c479d899bdebace5040c39360515bc95385b8000ea77b1cb8b4293b210d22e7ff4ecfbd1d7003e58e37bfe7",
          "sha256": "c9fdcb8af6ee96c21dee8ba7c260f0f88025a67ee27ad7f5fea145d73e7b5b32",
          "sha1": "19d3eec911c8e286970ad823f063e9a4d57f87be",
          "md5": "5b5f4dfb7ddd0d40774c958f3c8b9ecd"
        }
      ]
    }
  ]
}
