{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "727d1cf-add-github-local-buildcache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-727d1cf-add-github-local-buildcache.jar",
          "url": "antibytes-gradle-utils-727d1cf-add-github-local-buildcache.jar",
          "size": 9568,
          "sha512": "41e29e33af54f403e1bf8ccee1cf5d5bfeb8c63e8880dab5a14a198d422d2f8dcc3f510709a72f9568b9a09ded8d706c87c42e76539f450cdf62a3c8ef993d55",
          "sha256": "229ae16c91e3691fa398828a62ff244d655bab5fdad585192f9612d6b5717866",
          "sha1": "1b384b492e3ce76de16060114d8595f6dc072b56",
          "md5": "50a261e1f4f48ae3676d0a8a52eb3d51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-727d1cf-add-github-local-buildcache.jar",
          "url": "antibytes-gradle-utils-727d1cf-add-github-local-buildcache.jar",
          "size": 9568,
          "sha512": "41e29e33af54f403e1bf8ccee1cf5d5bfeb8c63e8880dab5a14a198d422d2f8dcc3f510709a72f9568b9a09ded8d706c87c42e76539f450cdf62a3c8ef993d55",
          "sha256": "229ae16c91e3691fa398828a62ff244d655bab5fdad585192f9612d6b5717866",
          "sha1": "1b384b492e3ce76de16060114d8595f6dc072b56",
          "md5": "50a261e1f4f48ae3676d0a8a52eb3d51"
        }
      ]
    }
  ]
}
