{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/d03b409-change-workflows-SNAPSHOT/test-utils-annotations-junit5-d03b409-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "d03b409-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosarm64-d03b409-change-workflows-SNAPSHOT.klib",
          "size": 7049,
          "sha512": "e82644416b7480c0e1e297e8b55903278dd59dcbe80a4aba35c969a5d55202c1b0fcb1a6cf5fac3b3cee4945a57f44ba15fcfdd82d726015f92482799375c2a1",
          "sha256": "cf3ab81b6becab5c1e36f156abf3ed0cac8ea12777f2a8d7242ca76b377c13df",
          "sha1": "f2399643618d581a8b56df40dbfe051f03472ef1",
          "md5": "8e92a1493a8e1a501e163317c9ffd25e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosarm64-d03b409-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosarm64-d03b409-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4f4e054afb48b3b40d3d8d3f1d274de5902e4e0bc080988c2f8118737eb9d094b49435d5af6864da5fe1e205ff909ab01722b6cd590ede3b1db0c7be1657ca32",
          "sha256": "215d37a6683e166a83bd0febc4da20c2947438af312faa4a52ad96b8f4f8f605",
          "sha1": "97bb0afce9f25b324b48c7b8a49a189f101c51c5",
          "md5": "4b08c8b5ced8df3229f5804cdf084950"
        }
      ]
    }
  ]
}
