{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-bump-setup-SNAPSHOT/kmock-0.3.0-rc04-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-bump-setup-SNAPSHOT.klib",
          "size": 202582,
          "sha512": "0926c1b9d60a4eff717d47f56dfaa941668d4b953a01beb174f9750da33bb25909b0b2e27922ff21ea04042dbea97a85ef75201bb848dfa2d865b364d07d70e1",
          "sha256": "54b3fe661c7f4b656ee43f6c787ff0ef6c6f22d39dcbcfa1a17f48ce5fd185e7",
          "sha1": "1a0f32ca28f8d3829b68cf78fbd24035882deaa3",
          "md5": "7a9ba0b9eea295703c7575febdf389f1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iossimulatorarm64-0.3.0-rc04-bump-setup-SNAPSHOT-metadata.jar",
          "url": "kmock-iossimulatorarm64-0.3.0-rc04-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6f99c16591c4e1e54f8fcb4a2a9441bf1ff806cf11709e6d357709b9116d36fe8c5580f616feb039c0e243dd69199b0522e064ea2a27c1675eecfea53039e094",
          "sha256": "115b2d4827b1aa524aae44297070d65b90392a747ef4555cd18087860affa4d9",
          "sha1": "a4db969aab50b7c95382def3e20adfb89fd029b9",
          "md5": "bd963ff05d81dd3eeb2f1e0731e6de2c"
        }
      ]
    }
  ]
}
