{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "9aedebe",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-9aedebe.jar",
          "url": "antibytes-configuration-9aedebe.jar",
          "size": 50694,
          "sha512": "5970087d74ee78f08b70c5408e530977c5d05be5030c3369a46daf9a727640765efb505b1fbc358979a3905d806af06a7c4fee467191a6d1b715e4b3bfd52c7b",
          "sha256": "8ef5dda5c40f3b4a1f6a17102cd7139715121b66c368b248d849381dedc65611",
          "sha1": "b42383bb840afe5fde00f8404f9ecccc41e3a578",
          "md5": "ce61a7168ca6544b3c13788f2c81171d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9aedebe"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-9aedebe.jar",
          "url": "antibytes-configuration-9aedebe.jar",
          "size": 50694,
          "sha512": "5970087d74ee78f08b70c5408e530977c5d05be5030c3369a46daf9a727640765efb505b1fbc358979a3905d806af06a7c4fee467191a6d1b715e4b3bfd52c7b",
          "sha256": "8ef5dda5c40f3b4a1f6a17102cd7139715121b66c368b248d849381dedc65611",
          "sha1": "b42383bb840afe5fde00f8404f9ecccc41e3a578",
          "md5": "ce61a7168ca6544b3c13788f2c81171d"
        }
      ]
    }
  ]
}
