{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105844,
          "sha512": "75142e120f4592350d9c91a34d0f7a540a39c78dc0d68a98b55234cbfd31781f3a1aa6e57d456ed957822be91ae48b840c0365c9133bf28ee9116fd1eb50b4b7",
          "sha256": "8832d9ed391ac8ba823461a18a22046e951b2877e27fd6ec9c63689308cfc42d",
          "sha1": "57a0c8f2431ff9d2557db2736334790e8ae95837",
          "md5": "828bc3ebf5938a0f5022522e352c15e0"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d1890bf4e597fa9075caaf5f7a8ae641514a899fa2df745e7ca622772e64d713c0a0ec5f8190ec155189a63e7fff54342dbad4b48b39007f89f801a477e11ced",
          "sha256": "f7e73eeecaec7910819245df146f4a8644b1eb1c8de67bdba97706a1ba1382a8",
          "sha1": "ddc4dfce05d399b259be82de761999abc6d190df",
          "md5": "e1b65d24bd00b5cf9e43d700f9943675"
        }
      ]
    }
  ]
}
