{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105844,
          "sha512": "75142e120f4592350d9c91a34d0f7a540a39c78dc0d68a98b55234cbfd31781f3a1aa6e57d456ed957822be91ae48b840c0365c9133bf28ee9116fd1eb50b4b7",
          "sha256": "8832d9ed391ac8ba823461a18a22046e951b2877e27fd6ec9c63689308cfc42d",
          "sha1": "57a0c8f2431ff9d2557db2736334790e8ae95837",
          "md5": "828bc3ebf5938a0f5022522e352c15e0"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-tvosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1d90ca8cceedd77d230b54d168787e7d35ac3c31f1ff26ebd3029fe66db680789abfaaee7d8581e0a01b0a78d6873a540d75836f4b14f07d7873a7cb57c8649c",
          "sha256": "714509bfe99d9ab0d53f075b63ffb8ec5174d223ee1541d212f7241567a9c0e2",
          "sha1": "f04c8aeb6543551e35446f0d44a7b95cc470a8d6",
          "md5": "9ada0c87b194c74dea6ca29db01364b6"
        }
      ]
    }
  ]
}
