{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "7824449-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-7824449-fix-factory-SNAPSHOT.jar",
          "url": "kmock-processor-7824449-fix-factory-SNAPSHOT.jar",
          "size": 95814,
          "sha512": "1a3b0782fc3db9885aebea436ffb515fd71c9d3038b55477b783903d1e42486d2358b146086ff59d700df5c31ec3837d372e49934f35d7d57568f79b23c5f94e",
          "sha256": "8889b2b71ef2c83789280341aea12b06bea42751e5e5496cd54240ff2effecde",
          "sha1": "d6b1fc3fc2540b20935c7b1f13e6c03a3acfcd43",
          "md5": "ddb1dea7b078972f16f766ce891b0d78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "7824449-fix-factory-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-7824449-fix-factory-SNAPSHOT.jar",
          "url": "kmock-processor-7824449-fix-factory-SNAPSHOT.jar",
          "size": 95814,
          "sha512": "1a3b0782fc3db9885aebea436ffb515fd71c9d3038b55477b783903d1e42486d2358b146086ff59d700df5c31ec3837d372e49934f35d7d57568f79b23c5f94e",
          "sha256": "8889b2b71ef2c83789280341aea12b06bea42751e5e5496cd54240ff2effecde",
          "sha1": "d6b1fc3fc2540b20935c7b1f13e6c03a3acfcd43",
          "md5": "ddb1dea7b078972f16f766ce891b0d78"
        }
      ]
    }
  ]
}
