{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "1fc88e3-add-quality-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "7ac48abdce54aeec7b11ad57ca0bbb5cee7c97ec91d74d4f35bbbb6f348361346b2c1ba624106693bc5b4f90779374261ce87d915a681992dec50811510a9658",
          "sha256": "4625d248bf8e052712a6fbde78074444949125cd7d85060df93cea95383da734",
          "sha1": "0b2fb04d306d6832fa9e55a4ce7a60f8c4920d51",
          "md5": "7869c7001bf4ca511c5f1a25da6f612c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-grammar-tools-1fc88e3-add-quality-plugin-SNAPSHOT.jar",
          "size": 39371,
          "sha512": "7ac48abdce54aeec7b11ad57ca0bbb5cee7c97ec91d74d4f35bbbb6f348361346b2c1ba624106693bc5b4f90779374261ce87d915a681992dec50811510a9658",
          "sha256": "4625d248bf8e052712a6fbde78074444949125cd7d85060df93cea95383da734",
          "sha1": "0b2fb04d306d6832fa9e55a4ce7a60f8c4920d51",
          "md5": "7869c7001bf4ca511c5f1a25da6f612c"
        }
      ]
    }
  ]
}
