{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/b8215f8-add-ios-SNAPSHOT/test-utils-ktor-b8215f8-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "b8215f8-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-b8215f8-add-ios-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-b8215f8-add-ios-SNAPSHOT.jar",
          "size": 27246,
          "sha512": "15ae2c5be077fd35caa910dd61d4c483d6c8b487bbf39e632aa6e95e46093bf745b115792a73b72f915698e4f45befc9c2d0db12d29c9b6e2e9c58c6af195184",
          "sha256": "e220a6f6844f8a28a3e1449b92ed30bea089b9a189c299819a6e302f4e88f997",
          "sha1": "a62f9614799cf1fa1ae879cb43b1dcce100b476f",
          "md5": "aa9973c999056416285445e7f48f730d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-b8215f8-add-ios-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-b8215f8-add-ios-SNAPSHOT.jar",
          "size": 27246,
          "sha512": "15ae2c5be077fd35caa910dd61d4c483d6c8b487bbf39e632aa6e95e46093bf745b115792a73b72f915698e4f45befc9c2d0db12d29c9b6e2e9c58c6af195184",
          "sha256": "e220a6f6844f8a28a3e1449b92ed30bea089b9a189c299819a6e302f4e88f997",
          "sha1": "a62f9614799cf1fa1ae879cb43b1dcce100b476f",
          "md5": "aa9973c999056416285445e7f48f730d"
        }
      ]
    }
  ]
}
