{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/85b758c-fix-factory-SNAPSHOT/kmock-85b758c-fix-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "85b758c-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-85b758c-fix-factory-SNAPSHOT.klib",
          "url": "kmock-js-85b758c-fix-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "623e8e0d1fb1eba08af6a15124437dc40f9f52ca50a0604a87287cf6b7d7f47aa4c67a2e64df121f0336fe10a7b970549394d85ee814faea5aa9b28b865dad18",
          "sha256": "04581bf8451dab553da0a6c58651ac8219f20d21b3ae72557b0857d9c89d485b",
          "sha1": "b38b9918f8f0f233d0a038f29529abd427db0d54",
          "md5": "86ee3ba93323e2059b4b932c3a6db93c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-85b758c-fix-factory-SNAPSHOT.klib",
          "url": "kmock-js-85b758c-fix-factory-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "623e8e0d1fb1eba08af6a15124437dc40f9f52ca50a0604a87287cf6b7d7f47aa4c67a2e64df121f0336fe10a7b970549394d85ee814faea5aa9b28b865dad18",
          "sha256": "04581bf8451dab553da0a6c58651ac8219f20d21b3ae72557b0857d9c89d485b",
          "sha1": "b38b9918f8f0f233d0a038f29529abd427db0d54",
          "md5": "86ee3ba93323e2059b4b932c3a6db93c"
        }
      ]
    }
  ]
}
