{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/2025aef-add-more-sources-SNAPSHOT/test-utils-resourceloader-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 12951,
          "sha512": "ef348779e4f1a42ca14d1dd5d6094f4b858a6ef6384c064af86a44b80f149a4a46f326676f3f5393fd964d4ec2669d7f49fdfa989bc2db6cd7a034b165ab10d3",
          "sha256": "31e73ccaffabdf9994f5dc643372a6f48ac9f9a19901d96122bdcf6c17c5f997",
          "sha1": "2999a2a2e1f8572af551acb6600ae6a6aa5eed48",
          "md5": "66321d6a894f9bdf98de4e775614d366"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5e40236223c4ae6920e75160a3f4f55445511e8f978a8e54217ec7625b3145bc8b230ce8f13360555c4b769186e67f4c49fe3538c156c3e8538e3826bc30d2e2",
          "sha256": "164ade19923d3c81dd772c655442361cd497aa3fabc89177d83559a5e25e224b",
          "sha1": "4ec11f3b25d61073d64bd08328cbf53f8e125c10",
          "md5": "9d8b2d4cea956b687091d46e47df2ee3"
        }
      ]
    }
  ]
}
