{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-remove-android-studio-workaround-SNAPSHOT/core-0.4.0-remove-android-studio-workaround-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-remove-android-studio-workaround-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.4.0-remove-android-studio-workaround-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "265550cc4abccf8514cc2010212104828d280c101704ad4790ca486b6f2ed8b91cff578772f80469d92ef5198cd9c80b8d12bb7bbc424a19a29d69f63b189d78",
          "sha256": "332bd314c3afeca78f9427a2573aee921f7272cb0e9b3cbad1f13989f188254d",
          "sha1": "ea23320eaa0eaeab840c0a1d999ededa5612aa8a",
          "md5": "2029b6318fa9a8c26ff80c64a21efbc5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a0ae93df813ddc39d68cd2849194e6b79a7e5a28fda3a5e42ecbc021079b961828db23067cf97c84f4284d116008e6c48b83981d5c2fb20264d9781be9687f3b",
          "sha256": "d2b621554c7ffc08c824f7a75f2d81fa12e42e4957ee27fefefc6d1edbd04b39",
          "sha1": "1176eef6d89c7456a14f7e11079d2f3b2f717d5d",
          "md5": "ae5085d39771f8bf39d276747bbe7402"
        }
      ]
    }
  ]
}
