{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "a513fea",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-a513fea.jar",
          "url": "antibytes-publishing-a513fea.jar",
          "size": 97017,
          "sha512": "8898785c78fb70b87552c260e3079a14ab6b6ceba1bed2425f0955421b0081e9d9bd2768c24f0ec4ce90548f745b91fd20b997d6dcb22f4c4270609b130deb07",
          "sha256": "1e8e7f8f3e1cee719831356415372ae04562f8d48259822b4b428258209f5516",
          "sha1": "0ad857bfbcf9251d5adedf84834bda87a95e8813",
          "md5": "c3b100a7c9f55d68b839515747a927f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-a513fea.jar",
          "url": "antibytes-publishing-a513fea.jar",
          "size": 97017,
          "sha512": "8898785c78fb70b87552c260e3079a14ab6b6ceba1bed2425f0955421b0081e9d9bd2768c24f0ec4ce90548f745b91fd20b997d6dcb22f4c4270609b130deb07",
          "sha256": "1e8e7f8f3e1cee719831356415372ae04562f8d48259822b4b428258209f5516",
          "sha1": "0ad857bfbcf9251d5adedf84834bda87a95e8813",
          "md5": "c3b100a7c9f55d68b839515747a927f1"
        }
      ]
    }
  ]
}
