{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-change-code-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT.jar",
          "size": 34076,
          "sha512": "9678a6c3e27629b014788af9fdf01dc2efd30f85832bc2b3bb93af142906b5f0d71b51a942acf7759e8998bb9f8c3fbcc5343e0600c26266d22cfeb1c2c3775e",
          "sha256": "4f2757e89f3bd273a233cfb42f0ddcbc233f8a48d88bbc9fd44d4a700d85cf3e",
          "sha1": "9c8dc9d10f39b7b4e34e90de1489c539398ae09c",
          "md5": "3096fd24cd0340949f0c20261d0fb53a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT.jar",
          "size": 34076,
          "sha512": "9678a6c3e27629b014788af9fdf01dc2efd30f85832bc2b3bb93af142906b5f0d71b51a942acf7759e8998bb9f8c3fbcc5343e0600c26266d22cfeb1c2c3775e",
          "sha256": "4f2757e89f3bd273a233cfb42f0ddcbc233f8a48d88bbc9fd44d4a700d85cf3e",
          "sha1": "9c8dc9d10f39b7b4e34e90de1489c539398ae09c",
          "md5": "3096fd24cd0340949f0c20261d0fb53a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "f50fa006defe121553ffe6efa5ecd1b6d7341c943b2816a5ece71ed911e54d8a5fbb12a61cd516ed7f8992557f97cb1034f7256b04789e301fe11ff8fcea60ff",
          "sha256": "3340b0c73d1940a89d2de3012d40eed062668ae5215d6a40c286c9eaf90e1312",
          "sha1": "10218ff48ee51f3ed2a82281a4ebc02c7a5656a7",
          "md5": "b7c26a17edbe7cfcac674f322c96b4f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-change-code-generator-SNAPSHOT-sources.jar",
          "size": 9068,
          "sha512": "0186f81de4de0a4c3bc4ee1ecf71b5c094ff7abb6ae3b2bf61194537ad8d9165d256fa555e1a84444a5430de443faf0ccb9ee56ea3034b72b1fb4cc99ffef6d9",
          "sha256": "dedffb789efbe19f9bcf3b06ec79d8ff22cbfb9dbd774c2e9be4d2bd7d3e05c2",
          "sha1": "a2f529d7d0306e1ca078972c5942affb1bdb4405",
          "md5": "3c174fa78d867e1b8cde0be013f940b1"
        }
      ]
    }
  ]
}
