{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/c018d4a-change-setup-SNAPSHOT/test-utils-c018d4a-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "c018d4a-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-c018d4a-change-setup-SNAPSHOT.klib",
          "size": 14314,
          "sha512": "48c79b07b706c3ce272a91d2762b9fe7ed355bc45dda37abe73a4a31bee1ebe97326b64b5997014690657d46916593f9dfe0c9f05d0058918016317c289d17eb",
          "sha256": "f6ea5d2df079ee008a8ea65daaad0454e4f375fb57130b017d9164d956c2fafc",
          "sha1": "d326ecf1061a7fa161daa977ae965db9aebde3cd",
          "md5": "ef736f215e450e3f115ecad17d8d4e6b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-c018d4a-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-c018d4a-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "bb2f4acb4334ac981b41bc8cdc3c5ae83ab6041ff86efe4b212156ee2680b5b739dce82b00170992efd95dd5db8b400d652a2045c74ce33789e8432cb3a63e0e",
          "sha256": "41e9513f0752436901a486aa48f1f0f3809154d6eb963c549fce042780491ea9",
          "sha1": "098353425e205da8a813ef9365b626c1610db3ab",
          "md5": "b205787e98d8877b3f4281e36ffd441c"
        }
      ]
    }
  ]
}
