{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/834cb6f-bump-updates-SNAPSHOT/test-utils-annotations-834cb6f-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "834cb6f-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "b4235f565552824a3112ce83319459101eb6751499f4e636123da1cd3e6bb849a9e19ec9c1c491ab95b0fd39e33734d35cd81b64e6af0c1c1672c15ab8bb3afb",
          "sha256": "9d43272c6930ef3098730eaef62d491d41667efea1265d1f8adda9bc73f1c0e3",
          "sha1": "0c7aff0cf4cf0e7e18ce32ff3c72f755b2acf89c",
          "md5": "bb9e8564c83849823c9881ff777bb1a2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-834cb6f-bump-updates-SNAPSHOT.jar",
          "size": 10817,
          "sha512": "b4235f565552824a3112ce83319459101eb6751499f4e636123da1cd3e6bb849a9e19ec9c1c491ab95b0fd39e33734d35cd81b64e6af0c1c1672c15ab8bb3afb",
          "sha256": "9d43272c6930ef3098730eaef62d491d41667efea1265d1f8adda9bc73f1c0e3",
          "sha1": "0c7aff0cf4cf0e7e18ce32ff3c72f755b2acf89c",
          "md5": "bb9e8564c83849823c9881ff777bb1a2"
        }
      ]
    }
  ]
}
