{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/675bf08-bump-updates-SNAPSHOT/test-utils-coroutine-675bf08-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "675bf08-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-675bf08-bump-updates-SNAPSHOT.klib",
          "size": 10123,
          "sha512": "10c9db4f0c9b4635abbaaff580006a3f64bf8194ac79491fc55f3b844fca94679282b33c38e59715b35dd2b35cb9a3af3f1ebda5a4980f0bd78ec2cfc5fca7dd",
          "sha256": "72564496fea31c8d738cff0910d76580b18684e25e71aa3277d7e20ad4334d2b",
          "sha1": "e1f1ffd87962052fd9a1f50fee397285144fcaeb",
          "md5": "dc1e56df809dc42d2927a364000c8274"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-675bf08-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-675bf08-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f0ee916aee9e1edf361c89accc93a8ea792cfc46e8985614d0382ceaf83ee9f795df516470c6749aeb6750556796de08d07b8c1b6f1df17f6c6723167eb53e89",
          "sha256": "47c56345d23290debbafcac27ac9e1bebc47db5203078c4e649d798ad05de488",
          "sha1": "8da7c9e9948b3c7dbdc7fb2f2f116f21b2509474",
          "md5": "1c282dca7c5701a0e090e6813b092622"
        }
      ]
    }
  ]
}
