{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0ad3fd5-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0ad3fd5-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-0ad3fd5-add-class-cracker-SNAPSHOT.jar",
          "size": 96199,
          "sha512": "3c6a6f3e73fd47bc61a0597e0de77d6a0e42b8d9824423ea6d6ef25ac9a9fd877a311604854e91f060a05510e6704a4a8735ecd85febed8ea79a74974bc44006",
          "sha256": "38c52adb215feea8c6c2c71b54b8f3689f2b77950712bd14924dc89f010a2fd9",
          "sha1": "54c9fc5f256a9d9bb2f4dc583b3f4237c8a2171d",
          "md5": "9f14412a76d2bc0cc43eba22f6a5ba3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0ad3fd5-add-class-cracker-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0ad3fd5-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-0ad3fd5-add-class-cracker-SNAPSHOT.jar",
          "size": 96199,
          "sha512": "3c6a6f3e73fd47bc61a0597e0de77d6a0e42b8d9824423ea6d6ef25ac9a9fd877a311604854e91f060a05510e6704a4a8735ecd85febed8ea79a74974bc44006",
          "sha256": "38c52adb215feea8c6c2c71b54b8f3689f2b77950712bd14924dc89f010a2fd9",
          "sha1": "54c9fc5f256a9d9bb2f4dc583b3f4237c8a2171d",
          "md5": "9f14412a76d2bc0cc43eba22f6a5ba3f"
        }
      ]
    }
  ]
}
