{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "de75989-change-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de75989-change-settings-plugin.jar",
          "url": "antibytes-gradle-test-utils-de75989-change-settings-plugin.jar",
          "size": 17226,
          "sha512": "90959daf46e6537f5cf3f560a889a00e765e39fc8fc458d9ae02619cddc5847e3aa28fcf0e77e7e8745dc394eb4701416c42e2b804654f1fe6fa46cf7bf6b053",
          "sha256": "6694a214391e20ae540442c0824c1ccb7cdb86059f46c136196e00680e24ab3c",
          "sha1": "7299c2fa196deb29d56ff7a43feac51816cdc28a",
          "md5": "990ce9ba5f409df4dc671f77b636fbaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-de75989-change-settings-plugin.jar",
          "url": "antibytes-gradle-test-utils-de75989-change-settings-plugin.jar",
          "size": 17226,
          "sha512": "90959daf46e6537f5cf3f560a889a00e765e39fc8fc458d9ae02619cddc5847e3aa28fcf0e77e7e8745dc394eb4701416c42e2b804654f1fe6fa46cf7bf6b053",
          "sha256": "6694a214391e20ae540442c0824c1ccb7cdb86059f46c136196e00680e24ab3c",
          "sha1": "7299c2fa196deb29d56ff7a43feac51816cdc28a",
          "md5": "990ce9ba5f409df4dc671f77b636fbaa"
        }
      ]
    }
  ]
}
