{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "88cdd57-change-visibility-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-metadata-all.jar",
          "url": "test-utils-88cdd57-change-visibility-SNAPSHOT-all.jar",
          "size": 5390,
          "sha512": "97c796ccd43f44da6a7acdac272722dd014ad0063fa38867b351bb0e5937b9a750d284bdba71787e4bb2ac54316ae3e402057d49815337abb2a285661ffb43cc",
          "sha256": "3dfdc468e6e0628145e1476696a784006afc536d1b31be12b0024925f7485f2f",
          "sha1": "22ae3d532b21dee6d166d7f215406fb0ba5cd3b0",
          "md5": "370ddf791322fa098f582d9c9533ed09"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils.jar",
          "url": "test-utils-88cdd57-change-visibility-SNAPSHOT.jar",
          "size": 3960,
          "sha512": "ee3a95c4aa22232689985ef209783eee4c6b667584e78cf74c51f72bcf69ac9b2f28799a14857b2a9b9a330a97df9d9c7983adadb42cbdffc0589f3bdf8f064b",
          "sha256": "77ad8656cd9f1819749a7dcadc4efebfff1c11a0f91a11d01483e7113d1312e2",
          "sha1": "a0ce2f4e7a5ca81d3f9d3d32796574df36e9de78",
          "md5": "d7ef62e54eaf8356cfd566d4dae85754"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/88cdd57-change-visibility-SNAPSHOT/test-utils-android-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-android/88cdd57-change-visibility-SNAPSHOT/test-utils-android-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-android",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/88cdd57-change-visibility-SNAPSHOT/test-utils-js-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-js/88cdd57-change-visibility-SNAPSHOT/test-utils-js-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-js",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/88cdd57-change-visibility-SNAPSHOT/test-utils-jvm-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-jvm/88cdd57-change-visibility-SNAPSHOT/test-utils-jvm-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-jvm",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-linuxx64/88cdd57-change-visibility-SNAPSHOT/test-utils-linuxx64-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-linuxx64",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    }
  ]
}
