{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/c8e7c91-change-workflows-SNAPSHOT/test-utils-annotations-junit4-c8e7c91-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "c8e7c91-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-c8e7c91-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-c8e7c91-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "88f3cb5aec1c8eb7dc75e4b892a895c0dd26de897dff440c63a45c4381af326c70fb9dbc98148e501bba7517f91b745be27257399dc86868ffdd9ec7449e9946",
          "sha256": "3f1f7228424704b63cdc45f8b5a964c84a9468c42fb4c08a1b3341c468d41bf5",
          "sha1": "a45994b3bf892eab1e30cef4b00bc57459f2f24c",
          "md5": "ec7fe90c331853536a7c3fc2ddaffe64"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-js-c8e7c91-change-workflows-SNAPSHOT.klib",
          "url": "test-utils-annotations-junit4-js-c8e7c91-change-workflows-SNAPSHOT.klib",
          "size": 9754,
          "sha512": "88f3cb5aec1c8eb7dc75e4b892a895c0dd26de897dff440c63a45c4381af326c70fb9dbc98148e501bba7517f91b745be27257399dc86868ffdd9ec7449e9946",
          "sha256": "3f1f7228424704b63cdc45f8b5a964c84a9468c42fb4c08a1b3341c468d41bf5",
          "sha1": "a45994b3bf892eab1e30cef4b00bc57459f2f24c",
          "md5": "ec7fe90c331853536a7c3fc2ddaffe64"
        }
      ]
    }
  ]
}
