{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "af9df43-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-af9df43-add-plattform-hooks.jar",
          "url": "antibytes-coverage-af9df43-add-plattform-hooks.jar",
          "size": 135187,
          "sha512": "eecee70ea0d496bec0baab028a4681e0ecc8d6567dd09cccbe0bab8092f7d5081c1b79138a393378bed2eeb3f820513c0201eab98b630fc3911b8ef015692567",
          "sha256": "ace3bbe887ef490346fa36fd6c64d36024833a0035914f6187ec228cd32932dc",
          "sha1": "5f4f1c616e881866903f638dc62473fa9cf96ae4",
          "md5": "d9c482f9dd2d6a30fbf8fce1852ae841"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "af9df43-add-plattform-hooks"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-af9df43-add-plattform-hooks.jar",
          "url": "antibytes-coverage-af9df43-add-plattform-hooks.jar",
          "size": 135187,
          "sha512": "eecee70ea0d496bec0baab028a4681e0ecc8d6567dd09cccbe0bab8092f7d5081c1b79138a393378bed2eeb3f820513c0201eab98b630fc3911b8ef015692567",
          "sha256": "ace3bbe887ef490346fa36fd6c64d36024833a0035914f6187ec228cd32932dc",
          "sha1": "5f4f1c616e881866903f638dc62473fa9cf96ae4",
          "md5": "d9c482f9dd2d6a30fbf8fce1852ae841"
        }
      ]
    }
  ]
}
