{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "16cb12f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-16cb12f.jar",
          "url": "antibytes-dependency-16cb12f.jar",
          "size": 58472,
          "sha512": "da3e976fbeed8ac43802f5a79b6d20b527fc0fce3e7a17151b7858f8f560e428fab1cdf97ca155bf75175e2e4c3266260173d060e8cc2ca585d2aaf1ad770350",
          "sha256": "a24e9989cde696f15c9edb11c6e859b09a1a4b5a8c96d7b1cf6e94790c21bc83",
          "sha1": "ae8372c3405759b853314200343b3f45192f130e",
          "md5": "03d21acd6aaffd23366d70eb2aa40df8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.41.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.3"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "16cb12f"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-16cb12f.jar",
          "url": "antibytes-dependency-16cb12f.jar",
          "size": 58472,
          "sha512": "da3e976fbeed8ac43802f5a79b6d20b527fc0fce3e7a17151b7858f8f560e428fab1cdf97ca155bf75175e2e4c3266260173d060e8cc2ca585d2aaf1ad770350",
          "sha256": "a24e9989cde696f15c9edb11c6e859b09a1a4b5a8c96d7b1cf6e94790c21bc83",
          "sha1": "ae8372c3405759b853314200343b3f45192f130e",
          "md5": "03d21acd6aaffd23366d70eb2aa40df8"
        }
      ]
    }
  ]
}
