{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "602dec9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-602dec9.jar",
          "url": "antibytes-gradle-utils-602dec9.jar",
          "size": 9580,
          "sha512": "b1faa0f9db908d67b41abb091701d2c1627cf9e99081c85866516b6ee5fdf328c299b157f8871632b2f72afe8690104a516a4a55238c44090f8c0e5af7c054fa",
          "sha256": "415f7c3241e876df9eb47294e3692f71c1ed11d02393aabef78048903cbb2877",
          "sha1": "62f331ef91b392d19f8d767393271035d0ff82f1",
          "md5": "f09b00761b4e90f7baef26498106f3cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-602dec9.jar",
          "url": "antibytes-gradle-utils-602dec9.jar",
          "size": 9580,
          "sha512": "b1faa0f9db908d67b41abb091701d2c1627cf9e99081c85866516b6ee5fdf328c299b157f8871632b2f72afe8690104a516a4a55238c44090f8c0e5af7c054fa",
          "sha256": "415f7c3241e876df9eb47294e3692f71c1ed11d02393aabef78048903cbb2877",
          "sha1": "62f331ef91b392d19f8d767393271035d0ff82f1",
          "md5": "f09b00761b4e90f7baef26498106f3cb"
        }
      ]
    }
  ]
}
