{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/2025aef-add-more-sources-SNAPSHOT/test-utils-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-watchosx64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 7980,
          "sha512": "fe1b074608328f7294b5876f0d38c2d5eab9f30def3ad334b2355de26a4d3d3e5d3664a2a305312a0b8d46b694bfe433436787ba9b8cc61ccf78d90b38658e7f",
          "sha256": "9023e9605156cf26ae67e38f1ccb8d218ee4e1b99601af9b44d4573cdb22caec",
          "sha1": "6a7a933ea744a4803077d34d2d91391a0265e8bf",
          "md5": "104b5025a68103b297232205f25072d0"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-watchosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-watchosx64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "852022d903d57a2d57a96fc9a31dc0569d51c0edaa7fad51d9079548b5c5ee8fd67b4ab526638a7c26cc91ae8c54d389f68c60287e0d13124be7263f0f1ab654",
          "sha256": "7ab2e98f0a715fe02c0101b7dc75d73e5b50a108a6be08cba5f3874aeabfc8fa",
          "sha1": "0013494e00cd81a4981ec2aa482356994b167cc7",
          "md5": "10f174dd24ffe190394d41c6fa9d340b"
        }
      ]
    }
  ]
}
