{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "9a3693b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-9a3693b.jar",
          "url": "antibytes-configuration-9a3693b.jar",
          "size": 39303,
          "sha512": "ec362276c5fa8aea772406f4c98baf06f1dc51f66fe1f23c3434ed6636ee958085da38abd6d95452233b74cfaf6fc5468b255ae44b0efa23ddde589213c02cc7",
          "sha256": "ee83fa84d00df32cef51dc544d34c17a4879fe408678b0272488624878f9b54b",
          "sha1": "f506134c0501645a9305ded4f5af24943c2ca870",
          "md5": "4cd1ada0e90fe8fd0ad2e1e80915f1a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9a3693b"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-9a3693b.jar",
          "url": "antibytes-configuration-9a3693b.jar",
          "size": 39303,
          "sha512": "ec362276c5fa8aea772406f4c98baf06f1dc51f66fe1f23c3434ed6636ee958085da38abd6d95452233b74cfaf6fc5468b255ae44b0efa23ddde589213c02cc7",
          "sha256": "ee83fa84d00df32cef51dc544d34c17a4879fe408678b0272488624878f9b54b",
          "sha1": "f506134c0501645a9305ded4f5af24943c2ca870",
          "md5": "4cd1ada0e90fe8fd0ad2e1e80915f1a3"
        }
      ]
    }
  ]
}
