{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "8a962a5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-8a962a5.jar",
          "url": "antibytes-publishing-8a962a5.jar",
          "size": 105775,
          "sha512": "92e56ae8f653909748f0b343f3620cedb45396ba90c7c403d883d5cec68491d7772b7af54adeaa9965c8468732b910d2b6972c28b276fc286515e19a942da24f",
          "sha256": "6df3440fc53634cb2e74450b5cdbdffb312865b119f1fc424463b536c5bf08c7",
          "sha1": "4ae4fdea869891d87ac03602bb639dd50acc4ee5",
          "md5": "bdd8fe0a19ead9c86084c29303c760b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.0.0.202111291000-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "8a962a5"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-8a962a5.jar",
          "url": "antibytes-publishing-8a962a5.jar",
          "size": 105775,
          "sha512": "92e56ae8f653909748f0b343f3620cedb45396ba90c7c403d883d5cec68491d7772b7af54adeaa9965c8468732b910d2b6972c28b276fc286515e19a942da24f",
          "sha256": "6df3440fc53634cb2e74450b5cdbdffb312865b119f1fc424463b536c5bf08c7",
          "sha1": "4ae4fdea869891d87ac03602bb639dd50acc4ee5",
          "md5": "bdd8fe0a19ead9c86084c29303c760b7"
        }
      ]
    }
  ]
}
