{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/e453a55-add-ios-SNAPSHOT/test-utils-e453a55-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "e453a55-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-e453a55-add-ios-SNAPSHOT.klib",
          "size": 14133,
          "sha512": "b464135f837d3757d0900a38a022957b61909c37e263e1c9d013a0db60ad74f9a6a9410b7681016d4afcbce1bbe5b56f548bbd52383059a5960fb73769007ffe",
          "sha256": "84d8604e43e69bd5ecdc3a9ec8aa5fb2dcdc34d8da57aa5c6980d5339169e7a1",
          "sha1": "7518c35fdf19d881d2d08df0c65851d1a1e40a6b",
          "md5": "9567170c18eb748a097a72bd1035935a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-e453a55-add-ios-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-e453a55-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e20263a4b4eb57bbe3bb9a78f1d6b88dbc2ce877d86bf78fa89199f434d70342b889fbf58b1b0bc17e24198c02df9c23be0a0ae472b85a5c51aac28c5523ee73",
          "sha256": "8991e5eda7e769386160fa73f2bfb7cec6391c3e2baf903d6c1e7f7345d1772a",
          "sha1": "386bd8c6eb28690dbb95f863d541d6b80f760f97",
          "md5": "462634184a0b8242a20f5e41cd89de48"
        }
      ]
    }
  ]
}
