{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-change-project-configuration-SNAPSHOT/ktx-datetime-0.4.0-change-project-configuration-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-change-project-configuration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "03619bb6c870d3ef73ba56df5758703b88cb8853e05a32ede4ec772b620820a1722be896f53ba24bb3745f44df5ec9946d23fcab9d91be4746eba6bc5d380ad4",
          "sha256": "eb339b7f631f94996db9b0753c37f3d95df1673dc8aff8cedcecf87246082d4e",
          "sha1": "66b1cf76b5f822897e0e55bcad8b327d08df97f2",
          "md5": "5a0a48fdbe8e664e3210475dda7e4f0d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-change-project-configuration-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-change-project-configuration-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "03619bb6c870d3ef73ba56df5758703b88cb8853e05a32ede4ec772b620820a1722be896f53ba24bb3745f44df5ec9946d23fcab9d91be4746eba6bc5d380ad4",
          "sha256": "eb339b7f631f94996db9b0753c37f3d95df1673dc8aff8cedcecf87246082d4e",
          "sha1": "66b1cf76b5f822897e0e55bcad8b327d08df97f2",
          "md5": "5a0a48fdbe8e664e3210475dda7e4f0d"
        }
      ]
    }
  ]
}
