{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-bridge",
    "version": "fb3fdb1-add-snapshot-supression-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-bridge-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "size": 38501,
          "sha512": "e37840cdbc7a628e0beca5b1ce14108d4e60d3fe4a88358b0379701e76f6c2ccb31693f49e059d882713698eabc4fae6f66ed58bd2894767287b81ae55e716a9",
          "sha256": "8bae38d1d4bcf016ece288405e5e40fbc6b400e8dc2b493580fcbae620aa1a2b",
          "sha1": "adcb4ad21e77e59eeeeaf103999cb72a5909f32e",
          "md5": "55af26bfd000e730c5ba417bb6e051a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-bridge-fb3fdb1-add-snapshot-supression-SNAPSHOT.jar",
          "size": 38501,
          "sha512": "e37840cdbc7a628e0beca5b1ce14108d4e60d3fe4a88358b0379701e76f6c2ccb31693f49e059d882713698eabc4fae6f66ed58bd2894767287b81ae55e716a9",
          "sha256": "8bae38d1d4bcf016ece288405e5e40fbc6b400e8dc2b493580fcbae620aa1a2b",
          "sha1": "adcb4ad21e77e59eeeeaf103999cb72a5909f32e",
          "md5": "55af26bfd000e730c5ba417bb6e051a1"
        }
      ]
    }
  ]
}
