{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-change-workflows-SNAPSHOT/core-0.4.0-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx86-0.4.0-change-workflows-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "e329f0c06611b415fbb9c916977e31b532c8f5c4f57beede067057b181d825beca6b22d347cca42785a3333b842b7ca40a24206b07de24b86cadb4c443c3a267",
          "sha256": "a8f3516fa309affa18f82228abdd015927f6f3cde92eccb4a1f2624fdcc1dfcf",
          "sha1": "c63d8d0b797ce07f3d4b0c4c2c0c9769537db28a",
          "md5": "fe87cbe3887090c412b4e53c685a5873"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx86-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "url": "core-watchosx86-0.4.0-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9fb9c3e81d824f66c25af9112809e00858c6ae63737268f7fedd7b63d5c063fd809d82c6645570c10b7da9134c34eeb7674c38ddbc2bf2ef3f983a63bcbfb913",
          "sha256": "09c4c6c14cc20d391a1418af8e8c8728c349eb9e2723061cab4da2a07f5d4759",
          "sha1": "bf259d2290167a6b166caa2cce694fd301144e19",
          "md5": "4d9b0b726c24230db68e220966857021"
        }
      ]
    }
  ]
}
