{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "818538b-fix-hickup-on-repetitive-execution-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-818538b-fix-hickup-on-repetitive-execution-SNAPSHOT.jar",
          "url": "kmock-processor-818538b-fix-hickup-on-repetitive-execution-SNAPSHOT.jar",
          "size": 105588,
          "sha512": "29e6703fa68439182378a262dff3f2d9d4abcdc0c5839625054090cb1b97a35890e98ca0fe579b3365a162d46d6612b7e6bd3f32877d0307fea8cf05245e6f3e",
          "sha256": "c4dd7bdb70ea0e4d8e89023e633fbce2d7317b6ea66248544b4a57b6c372b34d",
          "sha1": "96ea4293e7103609996c8e92f104ca5ba727ebde",
          "md5": "e7156a915c321b1ffb1bb8811cab6198"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "818538b-fix-hickup-on-repetitive-execution-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-818538b-fix-hickup-on-repetitive-execution-SNAPSHOT.jar",
          "url": "kmock-processor-818538b-fix-hickup-on-repetitive-execution-SNAPSHOT.jar",
          "size": 105588,
          "sha512": "29e6703fa68439182378a262dff3f2d9d4abcdc0c5839625054090cb1b97a35890e98ca0fe579b3365a162d46d6612b7e6bd3f32877d0307fea8cf05245e6f3e",
          "sha256": "c4dd7bdb70ea0e4d8e89023e633fbce2d7317b6ea66248544b4a57b6c372b34d",
          "sha1": "96ea4293e7103609996c8e92f104ca5ba727ebde",
          "md5": "e7156a915c321b1ffb1bb8811cab6198"
        }
      ]
    }
  ]
}
