{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "fab1d15-add-quality-code-analysis-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "a33e9b06c2adc49f358d7d5178d17fb0c6986e9b06558cf2b795add5f5da39c476b70e7577673d7d2f0214f4c9c288732cc4b607fb3eafa0d0762d802c4fcca9",
          "sha256": "af7955ab7402df99096834829ebf930432e22fa5fcae4a1440bf26b6c5cf991a",
          "sha1": "92b09c064bfefd6cf4710e9597be846a56293756",
          "md5": "ee13c55fd2ffc40d864c2e591f0892be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "a33e9b06c2adc49f358d7d5178d17fb0c6986e9b06558cf2b795add5f5da39c476b70e7577673d7d2f0214f4c9c288732cc4b607fb3eafa0d0762d802c4fcca9",
          "sha256": "af7955ab7402df99096834829ebf930432e22fa5fcae4a1440bf26b6c5cf991a",
          "sha1": "92b09c064bfefd6cf4710e9597be846a56293756",
          "md5": "ee13c55fd2ffc40d864c2e591f0892be"
        }
      ]
    }
  ]
}
