{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-bridge",
    "version": "452cb59-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bridge-452cb59-change-node-dependencies.jar",
          "url": "antibytes-dependency-bridge-452cb59-change-node-dependencies.jar",
          "size": 38501,
          "sha512": "f74bda1c9ca61e4ede1bf2544a1665b786d442c45253cd9c742435dbba42679bf8d396b0edb2ccb6ac18b298f3c74a7c299942ed90d99ebcc91f18100a6b2ba1",
          "sha256": "50395d5fab823b41c0b8dc43ed42716688653b9f4413ad2a592516f1f237e607",
          "sha1": "28621a7d32df2c99fba23b9c5e8076a1d091d07f",
          "md5": "b062c4817fb6b94cf2b9959b6ff41bcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bridge-452cb59-change-node-dependencies.jar",
          "url": "antibytes-dependency-bridge-452cb59-change-node-dependencies.jar",
          "size": 38501,
          "sha512": "f74bda1c9ca61e4ede1bf2544a1665b786d442c45253cd9c742435dbba42679bf8d396b0edb2ccb6ac18b298f3c74a7c299942ed90d99ebcc91f18100a6b2ba1",
          "sha256": "50395d5fab823b41c0b8dc43ed42716688653b9f4413ad2a592516f1f237e607",
          "sha1": "28621a7d32df2c99fba23b9c5e8076a1d091d07f",
          "md5": "b062c4817fb6b94cf2b9959b6ff41bcb"
        }
      ]
    }
  ]
}
