{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/2025aef-add-more-sources-SNAPSHOT/test-utils-ktor-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosarm64-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 15027,
          "sha512": "3d77c906bbfbef9b570932f79ce659dfd8372364533a1282318539e3a6b529f7ad1e51a039c5c19f06ed055c0e49353475aa1b515163a579d9d817d60153252e",
          "sha256": "5d33d6a5d95e723448f95966317c2016d15552b03ba56509427d96e5a5ed488c",
          "sha1": "89eff951fe5c9199d0e937c1247ba6a3425b460f",
          "md5": "d13c60d06b7b3931e9ab436df2c9a15a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosarm64-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f5896d45f043be671371699b86efe82527d6c7ca9ce5cebdf62bf264f92c46da928e064f0c98b94e6d22b077798a1c0d67a5a2c63337669f903075dc452f2ab6",
          "sha256": "37f8717ae7ee4b0fd3a6bd70dd5d4005a0934b7e724fffcd8ed5fb1763eb552d",
          "sha1": "6d72880e261f8d3336e6d9a388228a7d12730b00",
          "md5": "1a15f46f70f168a18b4b8b72e098bee6"
        }
      ]
    }
  ]
}
