{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-spy-support-receiver-SNAPSHOT/kmock-0.1.1-add-spy-support-receiver-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-spy-support-receiver-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-spy-support-receiver-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-spy-support-receiver-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "9b4c4346037012e2a66108211c6aa0318761859e1aedfe36a46476cf765a19430300b3e828ea445a2019e0da09da0fc7ebcc3c9f86736358028047427b1f28d6",
          "sha256": "4e404c07d3cda53399f2e792297a5c60051ede2dff1a10b23b5cc8432e7d1926",
          "sha1": "464eeaf1218818ff40014ee45eb1149ae4c042e4",
          "md5": "48f3f87f3567cf5bedf942adbda3e352"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-spy-support-receiver-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-spy-support-receiver-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "9b4c4346037012e2a66108211c6aa0318761859e1aedfe36a46476cf765a19430300b3e828ea445a2019e0da09da0fc7ebcc3c9f86736358028047427b1f28d6",
          "sha256": "4e404c07d3cda53399f2e792297a5c60051ede2dff1a10b23b5cc8432e7d1926",
          "sha1": "464eeaf1218818ff40014ee45eb1149ae4c042e4",
          "md5": "48f3f87f3567cf5bedf942adbda3e352"
        }
      ]
    }
  ]
}
