{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/43575a8-add-iossimlator-SNAPSHOT/test-utils-ktor-43575a8-add-iossimlator-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "43575a8-add-iossimlator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-43575a8-add-iossimlator-SNAPSHOT.klib",
          "size": 14813,
          "sha512": "86c77a4089ecee384d8cf48f18776082c9d37922327d9c1192f9e72061050e56dfdb83b7ad9d88a1faa0a87a296d0db363877333247e9286b9b990f4b60e6a34",
          "sha256": "b125054f056ae8502d48551791e82e2fe3062973f312dc1463203498eb683c76",
          "sha1": "585d386b85fe5f332ca644005c423c6b19118796",
          "md5": "829060541e7fe612e4c6620fa376d394"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-43575a8-add-iossimlator-SNAPSHOT-metadata.jar",
          "url": "test-utils-ktor-iosx64-43575a8-add-iossimlator-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ac4919eb78cb93607c0e7b5f4ad177edafc63d026f93d9fb62db0c67156798d77bb9e210b5477050d3fe266be4b3b4b6ac70c8051bc5cf585ec9ff610e0a74a1",
          "sha256": "766d56984184d178d5c024799238b0de33eb76899de3c049c78dc19aff90a7f6",
          "sha1": "c58356176b41ffa877ab07204d0324e30b80562a",
          "md5": "e87e97ae70c7e07f866aad0257630ea3"
        }
      ]
    }
  ]
}
