{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "4c324f2-change-quality-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "0519391974ee32a2c2acd626b93a2f7a59793ee78ac1fec8901f355345691969b4ba375bf18d2feb8447bfc95c8c2cfb67350cad7dc5f67d06ad0c8906ecabef",
          "sha256": "8f839446cad52de70832842dac4efffd2a491b5ca9d9783a7d82c9c8291812de",
          "sha1": "deb91742733169a96857e822c7390e94d2be5196",
          "md5": "5bbf2b9004f840f13bce22d099a687cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4c324f2-change-quality-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "url": "antibytes-coverage-4c324f2-change-quality-plugin-SNAPSHOT.jar",
          "size": 135215,
          "sha512": "0519391974ee32a2c2acd626b93a2f7a59793ee78ac1fec8901f355345691969b4ba375bf18d2feb8447bfc95c8c2cfb67350cad7dc5f67d06ad0c8906ecabef",
          "sha256": "8f839446cad52de70832842dac4efffd2a491b5ca9d9783a7d82c9c8291812de",
          "sha1": "deb91742733169a96857e822c7390e94d2be5196",
          "md5": "5bbf2b9004f840f13bce22d099a687cb"
        }
      ]
    }
  ]
}
