{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "12ea545-fix-python-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-versioning-12ea545-fix-python-dependencies.jar",
          "size": 21893,
          "sha512": "27b4fc6e535ff438a1b53bafc8706135e9629706a1d45764cdefdefbaacffd65ced9420a38d1c5beef7f0743d9addf68490bdcb17c063fd1fcfca35771ea0a90",
          "sha256": "47938773d1ab17c276d1127d522e7c333ce613bdf5706880bac89025d3be27ae",
          "sha1": "8018f887a188822df017707d3d0e316fafcc9f97",
          "md5": "733f928d6bd0b46ff2fee03eae6dc688"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-versioning-12ea545-fix-python-dependencies.jar",
          "size": 21893,
          "sha512": "27b4fc6e535ff438a1b53bafc8706135e9629706a1d45764cdefdefbaacffd65ced9420a38d1c5beef7f0743d9addf68490bdcb17c063fd1fcfca35771ea0a90",
          "sha256": "47938773d1ab17c276d1127d522e7c333ce613bdf5706880bac89025d3be27ae",
          "sha1": "8018f887a188822df017707d3d0e316fafcc9f97",
          "md5": "733f928d6bd0b46ff2fee03eae6dc688"
        }
      ]
    }
  ]
}
