{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/88b1dde-bump-antibytes-SNAPSHOT/test-utils-fixture-88b1dde-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "88b1dde-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm-88b1dde-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-88b1dde-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "9c3b10a496d79503358e1ddb3ec469f5c0b51b280988e2571382e15dd1798f46a627d757950ddcf9c6abbaeb51b290b2ffddce467bdfb2d2bad39a63f032af7c",
          "sha256": "3b8a4e91e64a89fa7d9f4c5fd8a76832cd96506fa99d9e7e7c8666b2af797360",
          "sha1": "f424090dfc6106cf507de51c9762ecbb03c87d49",
          "md5": "5000e4ab00b004791b316d53fa2a613c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm-88b1dde-bump-antibytes-SNAPSHOT.jar",
          "url": "test-utils-fixture-jvm-88b1dde-bump-antibytes-SNAPSHOT.jar",
          "size": 68983,
          "sha512": "9c3b10a496d79503358e1ddb3ec469f5c0b51b280988e2571382e15dd1798f46a627d757950ddcf9c6abbaeb51b290b2ffddce467bdfb2d2bad39a63f032af7c",
          "sha256": "3b8a4e91e64a89fa7d9f4c5fd8a76832cd96506fa99d9e7e7c8666b2af797360",
          "sha1": "f424090dfc6106cf507de51c9762ecbb03c87d49",
          "md5": "5000e4ab00b004791b316d53fa2a613c"
        }
      ]
    }
  ]
}
