{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "1c3c48e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-1c3c48e.jar",
          "url": "antibytes-dependency-1c3c48e.jar",
          "size": 34476,
          "sha512": "882c9a6634717bf4e57357ea54f4072486ebc6c11e52b240a92b77e5412401f1fc089a29aeab26d510f867031a0172cbdc65395afffa6bef94c8eb5e8c6a263b",
          "sha256": "c9c80f1ebfd80be497921b509444a8ae5add89d9d8149fce5070a5c15b8f124e",
          "sha1": "585cc388e9bb3ba1fe86d6d9f5971cd1920dc466",
          "md5": "8dd5c30136f47b72d581b6fe16804a3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1c3c48e"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-1c3c48e.jar",
          "url": "antibytes-dependency-1c3c48e.jar",
          "size": 34476,
          "sha512": "882c9a6634717bf4e57357ea54f4072486ebc6c11e52b240a92b77e5412401f1fc089a29aeab26d510f867031a0172cbdc65395afffa6bef94c8eb5e8c6a263b",
          "sha256": "c9c80f1ebfd80be497921b509444a8ae5add89d9d8149fce5070a5c15b8f124e",
          "sha1": "585cc388e9bb3ba1fe86d6d9f5971cd1920dc466",
          "md5": "8dd5c30136f47b72d581b6fe16804a3c"
        }
      ]
    }
  ]
}
