{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/4fd5b59-add-class-cracker-SNAPSHOT/kmock-4fd5b59-add-class-cracker-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "4fd5b59-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-4fd5b59-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-4fd5b59-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "836896515623f424563f1ba05c5fb6209d4e4b1f723f546e0313d40e2fb7fc6bd4fef960d184e3dac67f20ed6a36727107a699f5978b14f777786fc5a2f0ed21",
          "sha256": "a5c5cab30d59984c9bfc8325831ca9e2eb21a1acb39ce1871fa73fe7b0c0d907",
          "sha1": "fac8a9702d1e3bb447b2376561cc00ecf75b100c",
          "md5": "7a8690d7dfe85347a3aaa508c46fc5f9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-4fd5b59-add-class-cracker-SNAPSHOT.klib",
          "url": "kmock-js-4fd5b59-add-class-cracker-SNAPSHOT.klib",
          "size": 126181,
          "sha512": "836896515623f424563f1ba05c5fb6209d4e4b1f723f546e0313d40e2fb7fc6bd4fef960d184e3dac67f20ed6a36727107a699f5978b14f777786fc5a2f0ed21",
          "sha256": "a5c5cab30d59984c9bfc8325831ca9e2eb21a1acb39ce1871fa73fe7b0c0d907",
          "sha1": "fac8a9702d1e3bb447b2376561cc00ecf75b100c",
          "md5": "7a8690d7dfe85347a3aaa508c46fc5f9"
        }
      ]
    }
  ]
}
