{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-danger-SNAPSHOT/ktx-datetime-0.4.0-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-bump-danger-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-bump-danger-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6941f5faeeb524da2c4dcfaf185e77c5ca039f5637c6de399081dac5c1d90a123bc6ea18bec52b2f7785f418616a264349da279c53aab09419882025e895591f",
          "sha256": "aa62d756f5e590ede65fcf0db7e3b760d26221f861afab7374b48676ea0bac75",
          "sha1": "4070573c67b0d0a6af3d95c5926cee635eb60ff8",
          "md5": "d6459a80d4d0e50f4d8b2c65abafdd19"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-danger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-jvm-0.4.0-bump-danger-SNAPSHOT.jar",
          "url": "ktx-datetime-jvm-0.4.0-bump-danger-SNAPSHOT.jar",
          "size": 56621,
          "sha512": "6941f5faeeb524da2c4dcfaf185e77c5ca039f5637c6de399081dac5c1d90a123bc6ea18bec52b2f7785f418616a264349da279c53aab09419882025e895591f",
          "sha256": "aa62d756f5e590ede65fcf0db7e3b760d26221f861afab7374b48676ea0bac75",
          "sha1": "4070573c67b0d0a6af3d95c5926cee635eb60ff8",
          "md5": "d6459a80d4d0e50f4d8b2c65abafdd19"
        }
      ]
    }
  ]
}
