{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "a328292",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-a328292.jar",
          "url": "antibytes-dependency-a328292.jar",
          "size": 71470,
          "sha512": "f0161cbc747a67cce219904888e7852ea28abbf79f4a9d455c83abbba89906eb2cbf13bad62dc583973a9ced01e809ba3edbfd00b40050156182e45b72303042",
          "sha256": "14b8ce8ccc1a50b76d2c14d6e0c6e07be40b190c3eccea266ccaa7f5c4eaa4cc",
          "sha1": "19f9274d847bfe2d380a0868d780fdd881f4765b",
          "md5": "07a3f2f2575af62fe3a4477120ffa1e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.44.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a328292"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-a328292.jar",
          "url": "antibytes-dependency-a328292.jar",
          "size": 71470,
          "sha512": "f0161cbc747a67cce219904888e7852ea28abbf79f4a9d455c83abbba89906eb2cbf13bad62dc583973a9ced01e809ba3edbfd00b40050156182e45b72303042",
          "sha256": "14b8ce8ccc1a50b76d2c14d6e0c6e07be40b190c3eccea266ccaa7f5c4eaa4cc",
          "sha1": "19f9274d847bfe2d380a0868d780fdd881f4765b",
          "md5": "07a3f2f2575af62fe3a4477120ffa1e5"
        }
      ]
    }
  ]
}
