{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/15471ae-change-structure-SNAPSHOT/test-utils-15471ae-change-structure-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "15471ae-change-structure-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-15471ae-change-structure-SNAPSHOT.klib",
          "size": 14403,
          "sha512": "b3b3c96d0c53100cd1fe6698cbda3dc77f1b2ce750f1192db68c79082660f41189166767ca53b66b5aac63d8e2619b37cd289c24853fe3d9d2a1834ad0178d84",
          "sha256": "79c069d69cc26ff7b3778cb7c2ff1551b0423fc1b7a51264b516b948ee91fbfa",
          "sha1": "1cb65592a19f507e61a6739b0fc6affd7851f925",
          "md5": "a6d1813b58d436a4142dc25f104cb82a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-15471ae-change-structure-SNAPSHOT-metadata.jar",
          "url": "test-utils-iossimulatorarm64-15471ae-change-structure-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8444a02c880aab356f0a8e61486b4a39298ba03b361eff40a9cea4de28f2b72f2b9e344c675e458c791ab7c0ff6134d23666ce7b7fae0e54fcd58334785cefc1",
          "sha256": "5ca524a5d4c70df8c14ebdd7ceb74b10b39d878f2fe97be8ea8d9cbbaf4c1d22",
          "sha1": "3f75d4871f962c5a867eab78e4de80c8cd566cd7",
          "md5": "b271219ef50e3b41b85396f0b12d4cf0"
        }
      ]
    }
  ]
}
