{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-alternative-proxy-access-SNAPSHOT/kmock-0.1.1-add-alternative-proxy-access-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-alternative-proxy-access-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-alternative-proxy-access-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-alternative-proxy-access-SNAPSHOT.klib",
          "size": 173247,
          "sha512": "41f04a623bf0e334cedf0d14161c7c0fc083f342ec6c030d922a5cb29bc754926bccfca4b26debf6d26e05b268fbdbd6c9476eeb7dc9a32f10e7d47e5a8c883d",
          "sha256": "e1c83cf98ad267425148283361050fe6d23a560a8dade1e9295bfd73798d7a6c",
          "sha1": "299a6361953486c1cffcdedae9a88284d25615f7",
          "md5": "2b255a9c5b2821a624008195d8657571"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-alternative-proxy-access-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-alternative-proxy-access-SNAPSHOT.klib",
          "size": 173247,
          "sha512": "41f04a623bf0e334cedf0d14161c7c0fc083f342ec6c030d922a5cb29bc754926bccfca4b26debf6d26e05b268fbdbd6c9476eeb7dc9a32f10e7d47e5a8c883d",
          "sha256": "e1c83cf98ad267425148283361050fe6d23a560a8dade1e9295bfd73798d7a6c",
          "sha1": "299a6361953486c1cffcdedae9a88284d25615f7",
          "md5": "2b255a9c5b2821a624008195d8657571"
        }
      ]
    }
  ]
}
