{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-fix-kspy-generation-SNAPSHOT/kmock-0.1.1-fix-kspy-generation-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-fix-kspy-generation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-fix-kspy-generation-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-fix-kspy-generation-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "a824b69ca07c03be4ab4416a0a3bdc6f727482fc6ac6b94bb00b549b6be053bb648f0666183a991c9210c7b9c2e325d37a587f866d0235599468e1940f8ae5ad",
          "sha256": "5e7f285e27ff6809fec71f20c8fe89d2065d9ea52675d3c1c89d602915699006",
          "sha1": "3e4abae37c6d5c7b150590764d599acfef2a118f",
          "md5": "9dda2647819e0df199b033a716b86d86"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-fix-kspy-generation-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-fix-kspy-generation-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "a824b69ca07c03be4ab4416a0a3bdc6f727482fc6ac6b94bb00b549b6be053bb648f0666183a991c9210c7b9c2e325d37a587f866d0235599468e1940f8ae5ad",
          "sha256": "5e7f285e27ff6809fec71f20c8fe89d2065d9ea52675d3c1c89d602915699006",
          "sha1": "3e4abae37c6d5c7b150590764d599acfef2a118f",
          "md5": "9dda2647819e0df199b033a716b86d86"
        }
      ]
    }
  ]
}
