{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105870,
          "sha512": "3831b55bd4e198839bf5974c9538f8717086ee971595a3ff3fc4b9e8b12ce3e6fdfc7d26d620e55cef0a5fc3035c23a5d9f445af883cbf773a07d0f7e060e189",
          "sha256": "67bd08a14d36c0fa70e6edbf92c35beee20d9ec0ba9c6ba6ea9538db49b8d522",
          "sha1": "20b75f0e877ce263986352c9fd4600bf98b2a2d5",
          "md5": "0bf37b68051cead45472df08b026bce8"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9eb93b83fc149a2befb64b9ddd7ca359b4e3fdf137df9d05ce094d4fe2662cbe7df82c27cff6359161502ff4def47fb6eb6534dfe772178d192335b8b0340ab6",
          "sha256": "cd08d78ff40c4218103c60b15f54d3c4f7ce56afa823f0c0ebdc66508f02c2e1",
          "sha1": "3cb681223d7e50e238e93625304cfcacfd934d15",
          "md5": "a958b19039c807e3ba6f94d2c146727c"
        }
      ]
    }
  ]
}
