{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-add-more-platforms-SNAPSHOT/kmock-0.3.0-rc04-add-more-platforms-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-add-more-platforms-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc04-add-more-platforms-SNAPSHOT.klib",
          "size": 202515,
          "sha512": "b583253a2919c677a101fb58b16ad327023633d83e81cd0473824aa76044361e73b38d90051cf68cf1a2cfee12f1396d7793beb47ba15e21ba1f9e864ebe09d5",
          "sha256": "8d07c363a5967d463512e69ec9fffd3d98ab6d154fc5508150a89572f5c3bd3b",
          "sha1": "6cbd32be326d36a712bd06355074527d3a753767",
          "md5": "729e42ae8adb9e51ec627c237ea69934"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc04-add-more-platforms-SNAPSHOT-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc04-add-more-platforms-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "de9e9f1c5b99af368afd86e748dbd9922a28efaddb02a4c4040840082d5372ddc9ad1407c5360bf76c9d9791c8d377fd135ff888cce2eece028d357995ecd041",
          "sha256": "ed8c23f96fabd32fed73c985f9c81a6d29ec66c6f05e058bd7ba153e4a8aa469",
          "sha1": "46ad6ef8e4f6962b825253e2865a5fcc60888696",
          "md5": "ad9052bbaf02a3dbb98495810504df53"
        }
      ]
    }
  ]
}
