{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.coverage",
    "module": "antibytes-coverage",
    "version": "669446f-remove-doublets",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-669446f-remove-doublets.jar",
          "url": "antibytes-coverage-669446f-remove-doublets.jar",
          "size": 135187,
          "sha512": "a41a483c6e976f89e2507739aec415fd900e1a1fdd52ea369039588d57e2339737d8095f520baa61ca0adcadd2e502ea3f54a426c31d50381dee21fdde460654",
          "sha256": "93de973adb29ef716b96a36869cd5e70ccadea30e1935944037917bb2feec50d",
          "sha1": "05e4c223412f4f7c3892fac33e58f7237f15d9fc",
          "md5": "e10bf7ef58d9e2c0c6864a60ea263f74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "669446f-remove-doublets"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-669446f-remove-doublets.jar",
          "url": "antibytes-coverage-669446f-remove-doublets.jar",
          "size": 135187,
          "sha512": "a41a483c6e976f89e2507739aec415fd900e1a1fdd52ea369039588d57e2339737d8095f520baa61ca0adcadd2e502ea3f54a426c31d50381dee21fdde460654",
          "sha256": "93de973adb29ef716b96a36869cd5e70ccadea30e1935944037917bb2feec50d",
          "sha1": "05e4c223412f4f7c3892fac33e58f7237f15d9fc",
          "md5": "e10bf7ef58d9e2c0c6864a60ea263f74"
        }
      ]
    }
  ]
}
