{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "c835cc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-c835cc2.jar",
          "url": "antibytes-gradle-utils-c835cc2.jar",
          "size": 9580,
          "sha512": "238cf12d9f0233f358db18ec3d8f788a8753318793af842bf607cc9d7bcff982c7df141f1de24d115625e43c7676ccb62af75ec1cc842c5ff306a93b64a2c95f",
          "sha256": "992c055904a291c6c6ab8c2668c84d070cf8b5a9be577c8229d63c0775bd8278",
          "sha1": "27bda15c4cd6e4c932f239ee8a51a9dd3ff5636a",
          "md5": "a722c724894b07df52634bdaa65fbd70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-c835cc2.jar",
          "url": "antibytes-gradle-utils-c835cc2.jar",
          "size": 9580,
          "sha512": "238cf12d9f0233f358db18ec3d8f788a8753318793af842bf607cc9d7bcff982c7df141f1de24d115625e43c7676ccb62af75ec1cc842c5ff306a93b64a2c95f",
          "sha256": "992c055904a291c6c6ab8c2668c84d070cf8b5a9be577c8229d63c0775bd8278",
          "sha1": "27bda15c4cd6e4c932f239ee8a51a9dd3ff5636a",
          "md5": "a722c724894b07df52634bdaa65fbd70"
        }
      ]
    }
  ]
}
