{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/85b758c-fix-factory-SNAPSHOT/kmock-85b758c-fix-factory-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "85b758c-fix-factory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-85b758c-fix-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-85b758c-fix-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "57b51d3e7dd8c4c21d1e36e24bbf166ac58d8df43e5a368617d6a8e485501fcf03aceacbec5b3624106f31165ed0579c16845877eed6779eef2f3e5e41bd73c1",
          "sha256": "0cf22745e50ca837d4fca31a040c73f6c9f792426e9238326d008ba95c2ca1c0",
          "sha1": "6f151e2ecaa96ae16c4353c35d0b1c67787ad626",
          "md5": "c0433a3eb5c9f6b0e388b2174bff1111"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-85b758c-fix-factory-SNAPSHOT.jar",
          "url": "kmock-jvm-85b758c-fix-factory-SNAPSHOT.jar",
          "size": 255257,
          "sha512": "57b51d3e7dd8c4c21d1e36e24bbf166ac58d8df43e5a368617d6a8e485501fcf03aceacbec5b3624106f31165ed0579c16845877eed6779eef2f3e5e41bd73c1",
          "sha256": "0cf22745e50ca837d4fca31a040c73f6c9f792426e9238326d008ba95c2ca1c0",
          "sha1": "6f151e2ecaa96ae16c4353c35d0b1c67787ad626",
          "md5": "c0433a3eb5c9f6b0e388b2174bff1111"
        }
      ]
    }
  ]
}
