{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-reciever-methods-SNAPSHOT/kmock-0.1.1-add-reciever-methods-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-reciever-methods-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "688adc856a782712d960894986b23dfd151dba618f4fdabba786b0cc9e2364c45d5d5f6c52cb8be2f953b47e1e67ea0cbe0b599470a9adb098a83624fc3d314c",
          "sha256": "102aa6b27fa7ad4e7d9eea112551a82081548dc8a8233a3bc9dc336650379e3c",
          "sha1": "e3c78b9b735a8196a575680659d9da701938a9ce",
          "md5": "dfcb86f9a45615f4d795b6ad887f476f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-reciever-methods-SNAPSHOT.jar",
          "size": 335472,
          "sha512": "688adc856a782712d960894986b23dfd151dba618f4fdabba786b0cc9e2364c45d5d5f6c52cb8be2f953b47e1e67ea0cbe0b599470a9adb098a83624fc3d314c",
          "sha256": "102aa6b27fa7ad4e7d9eea112551a82081548dc8a8233a3bc9dc336650379e3c",
          "sha1": "e3c78b9b735a8196a575680659d9da701938a9ce",
          "md5": "dfcb86f9a45615f4d795b6ad887f476f"
        }
      ]
    }
  ]
}
