{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency-catalog",
    "version": "82651b8-add-remote-detekt-config-to-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-82651b8-add-remote-detekt-config-to-plugin-SNAPSHOT.toml",
          "url": "antibytes-dependency-catalog-82651b8-add-remote-detekt-config-to-plugin-SNAPSHOT.toml",
          "size": 231029,
          "sha512": "67cf2cd14f8ed52584fd9f733cf6223c3daff735d45af323eacf9de1170111ccf5f1467a405cc402242bcbefdf6c55a8963128d4d90c29f1822d743dce0f1cd4",
          "sha256": "aa66e71f21212ea6e5bee0c2b805ee321cf1eebb8063a86f608053bb96e063d0",
          "sha1": "b320eecda2061d8414052cd2fb4fe0722124d9c5",
          "md5": "41b0047087c7f300118951a54853dda3"
        }
      ]
    }
  ]
}
