{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT/kmock-0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "ee8d6c7879024ed95befe567f9ec605ccf62ccb70258488de50d656921c56e36d5cf0c78a6401a84399e07d03b7f4a3d66c32be2ee6bdb7297b316cc90ce6981",
          "sha256": "6372661b83e0056558d6c55f94482c291adaef306fac5dd96b16b46e41e048cf",
          "sha1": "3ac8e68e4432a6c21d1cdeb327c4e60041b813d1",
          "md5": "a12a4c9299f40f990bcc522298b8f5a6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc03-bump-updates-1.7.10-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "ee8d6c7879024ed95befe567f9ec605ccf62ccb70258488de50d656921c56e36d5cf0c78a6401a84399e07d03b7f4a3d66c32be2ee6bdb7297b316cc90ce6981",
          "sha256": "6372661b83e0056558d6c55f94482c291adaef306fac5dd96b16b46e41e048cf",
          "sha1": "3ac8e68e4432a6c21d1cdeb327c4e60041b813d1",
          "md5": "a12a4c9299f40f990bcc522298b8f5a6"
        }
      ]
    }
  ]
}
