{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/ad28a6d-remove-dependency-plugin-SNAPSHOT/test-utils-ktor-ad28a6d-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "ad28a6d-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "1261f3fc410aa3824a7587595e11d6a64a45ba4745c199e9113a1b5e1d6594351779d6f0ed96710b253ac61d2be906807921766522224b5ebccaac55e1a8abb1",
          "sha256": "f7a45257f1b717a1a62681bd13e0bf1fddaf5ff8d6b8e16191afa9a68b3c257e",
          "sha1": "d46553596f53939555619527fe9b6b5ca5d8a7e0",
          "md5": "e3456f6b8bdc93227b75e1f171df39fe"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 12124,
          "sha512": "1261f3fc410aa3824a7587595e11d6a64a45ba4745c199e9113a1b5e1d6594351779d6f0ed96710b253ac61d2be906807921766522224b5ebccaac55e1a8abb1",
          "sha256": "f7a45257f1b717a1a62681bd13e0bf1fddaf5ff8d6b8e16191afa9a68b3c257e",
          "sha1": "d46553596f53939555619527fe9b6b5ca5d8a7e0",
          "md5": "e3456f6b8bdc93227b75e1f171df39fe"
        }
      ]
    }
  ]
}
