{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/65fa311-bump-gradle-SNAPSHOT/test-utils-65fa311-bump-gradle-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "65fa311-bump-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-65fa311-bump-gradle-SNAPSHOT.klib",
          "size": 14314,
          "sha512": "48c79b07b706c3ce272a91d2762b9fe7ed355bc45dda37abe73a4a31bee1ebe97326b64b5997014690657d46916593f9dfe0c9f05d0058918016317c289d17eb",
          "sha256": "f6ea5d2df079ee008a8ea65daaad0454e4f375fb57130b017d9164d956c2fafc",
          "sha1": "d326ecf1061a7fa161daa977ae965db9aebde3cd",
          "md5": "ef736f215e450e3f115ecad17d8d4e6b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-65fa311-bump-gradle-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosarm64-65fa311-bump-gradle-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5f29dde4adc66ced80091dedb15f064c14f0e9078c3460f5b8b40808ba157e696cbfee3a4da09c66fa8b15557443b1a293eacc234eb8511fa55afe6357a68669",
          "sha256": "009c97ee517542ab101f86d2995f4298cb945c385d57ae91f2ee2c322bf9c153",
          "sha1": "315cca63abb4aae79c84644f768441dc9521fc81",
          "md5": "87ddffed93bd1e5b8d5dc658e1b7dd62"
        }
      ]
    }
  ]
}
