{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "7b5dece",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-7b5dece.jar",
          "url": "antibytes-publishing-7b5dece.jar",
          "size": 100982,
          "sha512": "8b365cd8e73943cfd07a8e10b25b7ed9979f72fd58a4a838d5b68dc919e414748c52bb7610bcb2268f58b247d54955ce8f132d1609f4b614a21c5e82cc4182be",
          "sha256": "5b2fbf39b6804010648c01d9398a89d28f7a144ebf1454440dd803a74e678f22",
          "sha1": "bbeb7bd903cbca3c39d3a7b7a5d86e59d66a1412",
          "md5": "74a7917552adca45bef4643f8aebdd0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-7b5dece.jar",
          "url": "antibytes-publishing-7b5dece.jar",
          "size": 100982,
          "sha512": "8b365cd8e73943cfd07a8e10b25b7ed9979f72fd58a4a838d5b68dc919e414748c52bb7610bcb2268f58b247d54955ce8f132d1609f4b614a21c5e82cc4182be",
          "sha256": "5b2fbf39b6804010648c01d9398a89d28f7a144ebf1454440dd803a74e678f22",
          "sha1": "bbeb7bd903cbca3c39d3a7b7a5d86e59d66a1412",
          "md5": "74a7917552adca45bef4643f8aebdd0f"
        }
      ]
    }
  ]
}
