{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/ef3a5b1-bump-updates-SNAPSHOT/test-utils-ef3a5b1-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "ef3a5b1-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-tvosx64-ef3a5b1-bump-updates-SNAPSHOT.klib",
          "size": 8335,
          "sha512": "5df750fd7873b2cd8bad2e127d64c3e577b301f45b102862202c1be4d8c5aed7135e832c53ee3c1210b1b286f29a0fb990004d5a7d38406864592f87ba178cba",
          "sha256": "e1a5fd26179bd76119eb5d321a96e141d66b74c0fa5571620272e908479fc70c",
          "sha1": "f7f66f3faae9246a5d69678206a9bb164a766396",
          "md5": "3a2c56dd2c618b87f986079585400176"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "test-utils-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "url": "test-utils-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-sources.jar",
          "size": 2202,
          "sha512": "200f256b59ba175210138bed146ee54ab58c9bb91f071774698eb6b3f4920f792214d2d44a1cc764422cb2c09da1a0773d4d288080e067e60263b96f2ed68050",
          "sha256": "9e0bd104bc203c511c12aaf2143514ee32a59c775ece92a04e7ee764ee60affa",
          "sha1": "773bcb344a1f6fd820f6ee6e62aea2b59ecfa180",
          "md5": "8b3c7f259a640a3d1e2ffd34b7f29645"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "url": "test-utils-tvosx64-ef3a5b1-bump-updates-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "237f400bcfd3f4e65305acd26b5db082d10d575b829b99ab41dd7d89147bf1b5c0c12545417a782f8d6c0022cd8a28e89f215665e964fd4936e52eddaac174c1",
          "sha256": "07801b1cd06aefec454e66045c96b0f3b7516f8ef7c6c5bd51fe50a3710500b5",
          "sha1": "42b3eac8fab06aaa1f0a4f57d2644de478ae8988",
          "md5": "d5572f7e6824d9764a4833780e4b08f6"
        }
      ]
    }
  ]
}
