{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/ed46cd8-add-js-SNAPSHOT/test-utils-annotations-ed46cd8-add-js-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "ed46cd8-add-js-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-ed46cd8-add-js-SNAPSHOT.jar",
          "size": 10327,
          "sha512": "67341635929d3f06b9b6d12de1fb9653e3c8df6c09d4789377199e73df95f04e4191d0f71ac865dcea7fdde103aeaa361885b5ef7f336f75b5b9c44bb7110401",
          "sha256": "750cc437310ee596640c8338cc530ac43e066ae9649f41c204f7e3aeb655ce6d",
          "sha1": "0e72ccee013ee1e2c7369ac57e73eb108a844331",
          "md5": "686408ef81032cdb01725ff60127ed5f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-ed46cd8-add-js-SNAPSHOT.jar",
          "size": 10327,
          "sha512": "67341635929d3f06b9b6d12de1fb9653e3c8df6c09d4789377199e73df95f04e4191d0f71ac865dcea7fdde103aeaa361885b5ef7f336f75b5b9c44bb7110401",
          "sha256": "750cc437310ee596640c8338cc530ac43e066ae9649f41c204f7e3aeb655ce6d",
          "sha1": "0e72ccee013ee1e2c7369ac57e73eb108a844331",
          "md5": "686408ef81032cdb01725ff60127ed5f"
        }
      ]
    }
  ]
}
