{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-timezone-picker-SNAPSHOT/core-0.3.1-add-timezone-picker-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-timezone-picker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-0.3.1-add-timezone-picker-SNAPSHOT.klib",
          "size": 108846,
          "sha512": "df73b13acf79f694fb4b5caf5b546b5297021faa1a9613f0886e41318880f7e43e3fbf6295a58c744c1c80363c46e145a77d0c17fe26009a88313dde51f13fa8",
          "sha256": "76b595c5138e758868916665d81759b31c3e75a8b9ee8a8b220435937ab25b1a",
          "sha1": "77c2094150249f1ca0e677bb15a18f2760f8cedd",
          "md5": "043afbde247a2e5ae3fe083bdb1480e3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.3.1-add-timezone-picker-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.3.1-add-timezone-picker-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6d5971768a73afdd59807fbce526a5a2a9b6fe6841df311ffeaf1ad58b1f87783e0a8c04b40a54c1982c962735ce1e3194d9343e4dedfb18069e2a5709a58053",
          "sha256": "d8d5ad6b776d880a15028abeb74fa3831c7b09905853ae8e436547e5d8f46cf0",
          "sha1": "9fc17140116d26d4a61527858d78022e504e75d4",
          "md5": "0acae2829be503c0506348ed2f9dcf47"
        }
      ]
    }
  ]
}
