{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "e7343d1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-e7343d1.jar",
          "url": "antibytes-coverage-e7343d1.jar",
          "size": 122599,
          "sha512": "104c19e2777e6197cff6db95a544fa8fef26e383fbdb164422589d47657e872c80b653ff9030035553e9eb4c999572065b19f0cd652fa7798f6e1c8fc7b5b531",
          "sha256": "2cd56c8d1c03e1946557ba50ee26ef6a7d97554e8b4ed29cc54a06fde47127f5",
          "sha1": "35c3e6bb183b96075247508fdf28259b7ae24985",
          "md5": "bdf1f1973324fdb7c7b8b9346086fdac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "e7343d1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-e7343d1.jar",
          "url": "antibytes-coverage-e7343d1.jar",
          "size": 122599,
          "sha512": "104c19e2777e6197cff6db95a544fa8fef26e383fbdb164422589d47657e872c80b653ff9030035553e9eb4c999572065b19f0cd652fa7798f6e1c8fc7b5b531",
          "sha256": "2cd56c8d1c03e1946557ba50ee26ef6a7d97554e8b4ed29cc54a06fde47127f5",
          "sha1": "35c3e6bb183b96075247508fdf28259b7ae24985",
          "md5": "bdf1f1973324fdb7c7b8b9346086fdac"
        }
      ]
    }
  ]
}
