{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-dependency-catalog",
    "version": "e3fda8a-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "antibytes-dependency-catalog-e3fda8a-change-plugins.toml",
          "url": "antibytes-dependency-catalog-e3fda8a-change-plugins.toml",
          "size": 231209,
          "sha512": "200e9fbb53da3d316d05d81e9bcdfee602d4affa94c98ae87eb13e89644a84e6fa42796be21565204b4ab2c1eb55df6b73617297ceacb9706f487c20542b6c0a",
          "sha256": "10564034bc5472ec06afe64a3ff90657b498f456fa0e9d92b4218cf725e3f99d",
          "sha1": "a79dbbae739ff44b8b666d9cabf18c6fb8a37c02",
          "md5": "30db55ce4db671d88be22359271be303"
        }
      ]
    }
  ]
}
