{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-fix-publishing-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.4.0-fix-publishing-SNAPSHOT-all.jar",
          "url": "ktx-datetime-0.4.0-fix-publishing-SNAPSHOT-all.jar",
          "size": 9151,
          "sha512": "1410808d71cf82d6e8d4250c8ef8c426827d31cb90cfb1b0bc4d558e353ac26dd24741b6bf8fd80da4d0e062c070bd2c80c49bf0aa06ba2b4b77d94d16d8482c",
          "sha256": "44eec478750d0afdcc04d62e3441891c53af313f3b9fd67dbca3405d2b437e52",
          "sha1": "6bd0d4af0711a790df8648b0f2035b2b3738dd66",
          "md5": "afecc8e132ec1ca05d6796cf9d7bf477"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.4.0-fix-publishing-SNAPSHOT.jar",
          "url": "ktx-datetime-0.4.0-fix-publishing-SNAPSHOT.jar",
          "size": 13895,
          "sha512": "6218792644cb76a959068c93c5aad2209fc4bef0477ac80f989f177d885d6fa9d6e6d2eee17d1cea134520b3d236e60d3f7ca095c8772b8b2dce7fe490fc1e10",
          "sha256": "908dbc0abf48cedb60d5d130cebf72b48b338b9f2a3a0b28865aa2ac608ec826",
          "sha1": "ebb8afbadb007d71c3fe1f5249e823acfb299ab0",
          "md5": "6e66b7372c71e0aab5a44d728d0970f1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-android-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-android-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm32/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosarm32-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm32",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm32/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosarm32-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm32",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-iosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-js-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-js-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-jvm-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-jvm-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-linuxx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-macosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-macosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-macosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-macosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-macosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-macosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-macosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-macosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-macosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-macosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-macosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-macosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-mingwx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-mingwx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-mingwx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-tvosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-tvosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-tvosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosarm32/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosarm32-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosarm32",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosarm32/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosarm32-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosarm32",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchossimulatorarm64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchossimulatorarm64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchossimulatorarm64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosx64/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosx64-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosx64",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosx86/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosx86-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosx86",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-watchosx86/0.4.0-fix-publishing-SNAPSHOT/ktx-datetime-watchosx86-0.4.0-fix-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-watchosx86",
        "version": "0.4.0-fix-publishing-SNAPSHOT"
      }
    }
  ]
}
