{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/ad479d6-change-workflows-SNAPSHOT/test-utils-resourceloader-ad479d6-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "ad479d6-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iosarm64-ad479d6-change-workflows-SNAPSHOT.klib",
          "size": 12865,
          "sha512": "d4354a16ff4e7f671a885afb5bd50aa493618e58eb624522b6443a3e88c75c55809c4c7926e37e528f7ee3db77798347c8dfa0f0dfe19972f3324d577ca388db",
          "sha256": "34d19a0a80dbb12e2b11109e11dc0627ee8514043a2e6e69b536b6dfd94e211a",
          "sha1": "52b6a8fdf6b799f09150e4e5169200bdd7f836c4",
          "md5": "bf93c70f016dce7067f84b5922b6e864"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iosarm64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-iosarm64-ad479d6-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c2fabc5553887670274196b3fd7f7921bf737c603813dab363ed240ed413080495442685404e8dc52be40b88fb10276160d9e7c075d06be0c06323c6c58a1456",
          "sha256": "aff06345b0a6f7ae6b3b8f6366a9b4df704adef1d62321d508eba611307e0948",
          "sha1": "11329579b1189d99f164e0d9c7817e27f367240f",
          "md5": "52e9d945dba41b0f42b67a8ab8ccb820"
        }
      ]
    }
  ]
}
