{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-compiler",
    "version": "4e39a26-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-compiler-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-compiler-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "size": 15889,
          "sha512": "81157d9296deb768f459882e5302e476edb2bb1be0b78b1d306bb6c6f69257d57566934f8690aa64acaee0afff69303f0dccde4b23bf9410ffa543a3485717a3",
          "sha256": "cc7cc055ec847a7240c5414f0c7347da3ef395dd0fdf60d79830a379e4daed72",
          "sha1": "f19ef01bf0bb79d23b436559f9e43ee6ea3cd500",
          "md5": "1047fe87b7f8cd9c81c3d9007b016db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-compiler-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-compiler-4e39a26-add-class-cracker-SNAPSHOT.jar",
          "size": 15889,
          "sha512": "81157d9296deb768f459882e5302e476edb2bb1be0b78b1d306bb6c6f69257d57566934f8690aa64acaee0afff69303f0dccde4b23bf9410ffa543a3485717a3",
          "sha256": "cc7cc055ec847a7240c5414f0c7347da3ef395dd0fdf60d79830a379e4daed72",
          "sha1": "f19ef01bf0bb79d23b436559f9e43ee6ea3cd500",
          "md5": "1047fe87b7f8cd9c81c3d9007b016db4"
        }
      ]
    }
  ]
}
