{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-fix-publishing-SNAPSHOT/core-0.4.0-fix-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-fix-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-tvosx64-0.4.0-fix-publishing-SNAPSHOT.klib",
          "size": 105826,
          "sha512": "7c96fe4649b351813825ad345d0393d980b57ac7426437a977ce9b9c53739a0f06fa42c9eb5768bbf3a216e747e758209e1531f4bf00455bf59e34c8da83294d",
          "sha256": "a7e846f9ae6e8deb48faf66edb000630da782d13cd2a2c78a28ec6e5022fdfa4",
          "sha1": "092cf759437a00c21badff9bf3e52878af235df6",
          "md5": "52930e08e1753341db938cc862a54a62"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-tvosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "url": "core-tvosx64-0.4.0-fix-publishing-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "124f4496cc1cc54a239f720c8889549bb6367d9c7c479d899bdebace5040c39360515bc95385b8000ea77b1cb8b4293b210d22e7ff4ecfbd1d7003e58e37bfe7",
          "sha256": "c9fdcb8af6ee96c21dee8ba7c260f0f88025a67ee27ad7f5fea145d73e7b5b32",
          "sha1": "19d3eec911c8e286970ad823f063e9a4d57f87be",
          "md5": "5b5f4dfb7ddd0d40774c958f3c8b9ecd"
        }
      ]
    }
  ]
}
