{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "af9df43-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "af9df43-add-plattform-hooks"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-af9df43-add-plattform-hooks.jar",
          "url": "antibytes-mkdocs-af9df43-add-plattform-hooks.jar",
          "size": 11930,
          "sha512": "a0290a8fd2154576535ce8c346ee77a4e5a601af3ae174c75717a86fd7f70f66f3eb7a51902f33dce0f24d95281bc33f0032504aef1413f716350effbf152b92",
          "sha256": "b82bd241bd3a2b7c00aed994b5e1a45ceafb49dde12e3ef26ffff73e8cafe022",
          "sha1": "5bfaa8f2eab7d26f90f1ad44d78f51fa6a45075d",
          "md5": "f9195374a86a0af449bf953b61fa76ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "af9df43-add-plattform-hooks"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "af9df43-add-plattform-hooks"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-af9df43-add-plattform-hooks.jar",
          "url": "antibytes-mkdocs-af9df43-add-plattform-hooks.jar",
          "size": 11930,
          "sha512": "a0290a8fd2154576535ce8c346ee77a4e5a601af3ae174c75717a86fd7f70f66f3eb7a51902f33dce0f24d95281bc33f0032504aef1413f716350effbf152b92",
          "sha256": "b82bd241bd3a2b7c00aed994b5e1a45ceafb49dde12e3ef26ffff73e8cafe022",
          "sha1": "5bfaa8f2eab7d26f90f1ad44d78f51fa6a45075d",
          "md5": "f9195374a86a0af449bf953b61fa76ac"
        }
      ]
    }
  ]
}
