{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "1c69a2f-change-android-compile-task",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-kmp-configuration-1c69a2f-change-android-compile-task.jar",
          "size": 12967,
          "sha512": "b6e06da7e496166a8f93467bd7a6416b261255abe05088504f2d34b6d006c997ec22434ab3acb77d5f6154378f8d2057bcb908c5769bb7017ebf1e178e4b2600",
          "sha256": "cd7b10040a84f5a344425e84de9b7cf584d909ac88fbc1b3ff6f70a8d54f1f54",
          "sha1": "07471f5ca89c78d9f848878dd6eec1dbed91ba57",
          "md5": "ea0f1e0897917c19efdeac1685974bf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1c69a2f-change-android-compile-task"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-kmp-configuration-1c69a2f-change-android-compile-task.jar",
          "size": 12967,
          "sha512": "b6e06da7e496166a8f93467bd7a6416b261255abe05088504f2d34b6d006c997ec22434ab3acb77d5f6154378f8d2057bcb908c5769bb7017ebf1e178e4b2600",
          "sha256": "cd7b10040a84f5a344425e84de9b7cf584d909ac88fbc1b3ff6f70a8d54f1f54",
          "sha1": "07471f5ca89c78d9f848878dd6eec1dbed91ba57",
          "md5": "ea0f1e0897917c19efdeac1685974bf2"
        }
      ]
    }
  ]
}
