{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/700e007-change-assertions-SNAPSHOT/test-utils-700e007-change-assertions-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "700e007-change-assertions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-700e007-change-assertions-SNAPSHOT.jar",
          "size": 17516,
          "sha512": "6aa410d7d65a8269e928e67ea868435ffb0b4cfed447af4e2bc9cb36d7d5e655f6043e6e307a4b685d8b0ee62c72fedde8082e5f35f07a20e1a943e9adf94a00",
          "sha256": "c303f20b7f200969a3e49feae37e90e2d22774d107c70a137bf83cb391baa740",
          "sha1": "ce5c3b3ce8a8004b1454f6769100b14a0749e93a",
          "md5": "833fb9c2fec569a08d8e6641752108bb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-700e007-change-assertions-SNAPSHOT.jar",
          "size": 17516,
          "sha512": "6aa410d7d65a8269e928e67ea868435ffb0b4cfed447af4e2bc9cb36d7d5e655f6043e6e307a4b685d8b0ee62c72fedde8082e5f35f07a20e1a943e9adf94a00",
          "sha256": "c303f20b7f200969a3e49feae37e90e2d22774d107c70a137bf83cb391baa740",
          "sha1": "ce5c3b3ce8a8004b1454f6769100b14a0749e93a",
          "md5": "833fb9c2fec569a08d8e6641752108bb"
        }
      ]
    }
  ]
}
