{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-annotations-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ebd49057be5141a35b261559ffd95ffb8e72e56975bae45647420414e17218bd75596a1213801fe627f5bf5311b52cea756d599872c6e096a8b1702f0c4df55f",
          "sha256": "2c901064772005d665e647ce84fe9e6c1e586120a42d6173f7c1148e91eefc7a",
          "sha1": "aba3571fa3c883d9bfc67c6e3f9143820217aec1",
          "md5": "1e7fb5a411ccc98226e072404c4149f0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "url": "test-utils-annotations-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "ebd49057be5141a35b261559ffd95ffb8e72e56975bae45647420414e17218bd75596a1213801fe627f5bf5311b52cea756d599872c6e096a8b1702f0c4df55f",
          "sha256": "2c901064772005d665e647ce84fe9e6c1e586120a42d6173f7c1148e91eefc7a",
          "sha1": "aba3571fa3c883d9bfc67c6e3f9143820217aec1",
          "md5": "1e7fb5a411ccc98226e072404c4149f0"
        }
      ]
    }
  ]
}
