{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-metadata-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT-all.jar",
          "url": "kmock-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT-all.jar",
          "size": 28436,
          "sha512": "2bd3ce6a345c7ff2d428c4852012406c81d994ee7c5874bc02394c81a575a28ec9f8e0949e67899b34bf40448193f94767d7ed2b620106849134e4342a5e1213",
          "sha256": "8b95672e0b75dfc38e6438d9437738b45146d24aff5ca7a58dda53a1aa6f8bac",
          "sha1": "e2472e9b3ccf41703fa5f728bc4b032965be6921",
          "md5": "fd6e12e1b9b9ad129470fa94a2b89a6c"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "url": "kmock-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.jar",
          "size": 47914,
          "sha512": "7dfffd806c954843e672e2cd9efdd65bf1f32346743515f127cbf8307ba844de1c6be8976355aa5ca2b13511b2e8b22c738606dbd9bc8c9ca6172ad936e9a225",
          "sha256": "32e66d410bad6b21be7d74ac66da7e79624d73c429f83b24b6e9468e7b27f377",
          "sha1": "136d6cd39e255ac70da3746de9ff6b5035f79aee",
          "md5": "d6170289c2986c2333215dfca94e1c09"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-android-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-android-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iosarm64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iosarm64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iossimulatorarm64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iossimulatorarm64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iossimulatorarm64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iosx64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-iosx64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-js-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-js-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-jvm-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT/kmock-linuxx64-0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "0.3.0-rc01-fix-relaxer-7af3657c2a-SNAPSHOT"
      }
    }
  ]
}
