{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.versioning",
    "module": "antibytes-versioning",
    "version": "98fcfcc-change-node-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-versioning-98fcfcc-change-node-dependencies.jar",
          "size": 21893,
          "sha512": "360a42504dc4c19212037e8630ae0997a5fed594eed025a3fca7cef18153b613a57ec1e2f3aeaf8a42a70d2079823a57af5a98acd7380799d93fa75a72a87053",
          "sha256": "66befafc7789d166866e34d64897f2cab86f2a352f345b6298268abfefd48315",
          "sha1": "419c445945f8ea45e425397c8e10e8424496746a",
          "md5": "2ffa234e016cee7f13545c700671a836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-98fcfcc-change-node-dependencies.jar",
          "url": "antibytes-versioning-98fcfcc-change-node-dependencies.jar",
          "size": 21893,
          "sha512": "360a42504dc4c19212037e8630ae0997a5fed594eed025a3fca7cef18153b613a57ec1e2f3aeaf8a42a70d2079823a57af5a98acd7380799d93fa75a72a87053",
          "sha256": "66befafc7789d166866e34d64897f2cab86f2a352f345b6298268abfefd48315",
          "sha1": "419c445945f8ea45e425397c8e10e8424496746a",
          "md5": "2ffa234e016cee7f13545c700671a836"
        }
      ]
    }
  ]
}
