{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "88b6109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-88b6109.jar",
          "url": "antibytes-dependency-88b6109.jar",
          "size": 27970,
          "sha512": "46392ba5492ea815dc8d80c2117db40096c5d16cdace73df66d1f51f0c24f6bb825b5f3487013a4867255037170ce1b10f37fbf9f1651bd4589cf1faebf883ff",
          "sha256": "73dd17d44a4c5331d3faa3dd476c847fb364ded5ba109e5563247301739f90fa",
          "sha1": "fbbc5719162a38b670b9bf0229029c21b0d67b94",
          "md5": "74bf2ed1e942763b38bc1e54c52ca048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-88b6109.jar",
          "url": "antibytes-dependency-88b6109.jar",
          "size": 27970,
          "sha512": "46392ba5492ea815dc8d80c2117db40096c5d16cdace73df66d1f51f0c24f6bb825b5f3487013a4867255037170ce1b10f37fbf9f1651bd4589cf1faebf883ff",
          "sha256": "73dd17d44a4c5331d3faa3dd476c847fb364ded5ba109e5563247301739f90fa",
          "sha1": "fbbc5719162a38b670b9bf0229029c21b0d67b94",
          "md5": "74bf2ed1e942763b38bc1e54c52ca048"
        }
      ]
    }
  ]
}
