{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "d511f16-change-branching",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-d511f16-change-branching.jar",
          "url": "antibytes-quality-d511f16-change-branching.jar",
          "size": 64568,
          "sha512": "dcef2aef37f5b81a77e84d88d075da5d2f87da4e1a5f1550bfd1c6a6d2660f2259ffac33c1945f9727c6a9c616d564570f0f6a91947dddd68f38b226803804ce",
          "sha256": "97f1123ca348371a996805849586ae093a5c882141e7010476387fa5c0861e08",
          "sha1": "395564319e4fe7c04968a183086f7f589f9f89d5",
          "md5": "2603a3dd2c69135ea407a474f5dd140f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.22.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.50.0"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "d511f16-change-branching"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "d511f16-change-branching"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "4.4.1.3373"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-d511f16-change-branching.jar",
          "url": "antibytes-quality-d511f16-change-branching.jar",
          "size": 64568,
          "sha512": "dcef2aef37f5b81a77e84d88d075da5d2f87da4e1a5f1550bfd1c6a6d2660f2259ffac33c1945f9727c6a9c616d564570f0f6a91947dddd68f38b226803804ce",
          "sha256": "97f1123ca348371a996805849586ae093a5c882141e7010476387fa5c0861e08",
          "sha1": "395564319e4fe7c04968a183086f7f589f9f89d5",
          "md5": "2603a3dd2c69135ea407a474f5dd140f"
        }
      ]
    }
  ]
}
