{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-bump-setup-SNAPSHOT/ktx-datetime-0.4.0-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-tvossimulatorarm64-0.4.0-bump-setup-SNAPSHOT.klib",
          "size": 34744,
          "sha512": "37b9148236c1a7843a78548d0944fda1639c81ee1d0fa6995c8ced32a2cf644e28f1042ede00b6e94eda9f4161634c01d353898c0cd9e2bb6f10b31790ecedfa",
          "sha256": "046a9659534a7ad2f6d0271d1f1f82307896952d695b80c115d3ba3b52389f50",
          "sha1": "d6823dc4a6036411d38c64c4b7bc55e304820143",
          "md5": "fedf679260fe5e67b618ac2cfa9fe93c"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-setup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-tvossimulatorarm64-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-tvossimulatorarm64-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "89eda7d9f19c2ae0fc9a48e8502474b27ed522902ac8cc85896116799f7347a0b96b9b4a02734d60e2032759d64cf788baa34e4b5ffd691d32a33bffcdab8a7c",
          "sha256": "fb9b7c30e07ca526020e8d59c298211af58d0e1d8a9cd8d2bb3b70490ced1548",
          "sha1": "af9635afd5f95ccbe93618d6ce607159a3bffd8d",
          "md5": "f003fe03af6f58ea0ca21c09c9fdf2df"
        }
      ]
    }
  ]
}
