{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "5e75dc7-add-agnostic-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmock-metadata-5e75dc7-add-agnostic-sources-SNAPSHOT.jar",
          "url": "kmock-5e75dc7-add-agnostic-sources-SNAPSHOT.jar",
          "size": 17982,
          "sha512": "77a3b651e0badd0f3a3a4dd4150c15f42788ccf878087ec97937cfb47653d8061a4551b7343b0d7ecb1d8748291d41337633ac5da586aa7d8b2d6996a1338c2a",
          "sha256": "cea02730af317563244b5987fd381548801efa8d40f68f875b8c7cff724c9ca8",
          "sha1": "e781a5a7ddb638488cfa0ee6da5bf2e7436a812a",
          "md5": "906c537af3221d2076c9071e699362d7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-android-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmock-android/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-android-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-android",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosarm64/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-iosarm64-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosarm64",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-iosx64/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-iosx64-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-iosx64",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-js-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kmock-js/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-js-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-js",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-jvm-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kmock-jvm/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-jvm-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-jvm",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmock-linuxx64/5e75dc7-add-agnostic-sources-SNAPSHOT/kmock-linuxx64-5e75dc7-add-agnostic-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kmock",
        "module": "kmock-linuxx64",
        "version": "5e75dc7-add-agnostic-sources-SNAPSHOT"
      }
    }
  ]
}
