{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/2053836-bump-danger-SNAPSHOT/test-utils-fixture-2053836-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "2053836-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-2053836-bump-danger-SNAPSHOT.jar",
          "size": 41804,
          "sha512": "2fe02234bfc798ebace4281969b05d7a4e05ea4213d57eb319e9a16673143ebd11dcc6b00ec4c74cdddc28bcec0408ebeaafabb2cfc6c71c9e5d2fd0c85c6fdd",
          "sha256": "be53a1954ab4bed6b8a0247630162a107ea69d6937ada35baa905dec7a29eb71",
          "sha1": "954f6e23c8b2ea320a0d318790867e098904ebb8",
          "md5": "7ae4fa7348d9a0b3fcbf0626b2ff7fdd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-jvm.jar",
          "url": "test-utils-fixture-jvm-2053836-bump-danger-SNAPSHOT.jar",
          "size": 41804,
          "sha512": "2fe02234bfc798ebace4281969b05d7a4e05ea4213d57eb319e9a16673143ebd11dcc6b00ec4c74cdddc28bcec0408ebeaafabb2cfc6c71c9e5d2fd0c85c6fdd",
          "sha256": "be53a1954ab4bed6b8a0247630162a107ea69d6937ada35baa905dec7a29eb71",
          "sha1": "954f6e23c8b2ea320a0d318790867e098904ebb8",
          "md5": "7ae4fa7348d9a0b3fcbf0626b2ff7fdd"
        }
      ]
    }
  ]
}
