{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-metadata-d18f9a2-fix-coroutine-publishing-SNAPSHOT-all.jar",
          "url": "test-utils-fixture-d18f9a2-fix-coroutine-publishing-SNAPSHOT-all.jar",
          "size": 15401,
          "sha512": "f92c70f44f449afc4d1ec131730832e5ac531f45cc7f1850b38dd6745a3d1186daab7289150561f9d1d9a884a50c1c210c437d6dc2f8896e2ac62100190cb252",
          "sha256": "49ae078ce971f803f7333bf6cfe58498f378c5d36b5a054d8d6ab70d2eed6667",
          "sha1": "b6a418f19ce8d3e531a42f130cab7b395ad58e1a",
          "md5": "4162397949ab4f21fd955c53af2dc8a7"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-fixture-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "url": "test-utils-fixture-d18f9a2-fix-coroutine-publishing-SNAPSHOT.jar",
          "size": 15466,
          "sha512": "dd1768121b2066b9e0b1550c92972b2da78abf587a0a306ddf05275dee513f314639e33e1431061fff64d8b04d776cc35720072fbde2e460f7c93cc6caff2b30",
          "sha256": "435b039af57344f06a4ddb6c49fa5e48997af95f51a28fa6c680f15e65ab4d9d",
          "sha1": "e4a5ebe5f00e895521c4be6baad3ce4c982e96e1",
          "md5": "df52253a7d4bcc0139addd72b92b6e22"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-android-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-android/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-android-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-android",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-iosarm64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosarm64/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-iosarm64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosarm64",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-iosx64/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-iosx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-iosx64",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-fixture-js/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-js-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-js",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-fixture-jvm/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-jvm-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-jvm",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-fixture-linuxx64/d18f9a2-fix-coroutine-publishing-SNAPSHOT/test-utils-fixture-linuxx64-d18f9a2-fix-coroutine-publishing-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-fixture-linuxx64",
        "version": "d18f9a2-fix-coroutine-publishing-SNAPSHOT"
      }
    }
  ]
}
