{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-runtime-configuration",
    "version": "5aacabc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-5aacabc.jar",
          "url": "antibytes-runtime-configuration-5aacabc.jar",
          "size": 10324,
          "sha512": "bc6ac1c51836138bce9049ba1f9f118b39383444775fb221c24a6cd75406f4bd14229d9f38cc8f6d68518f91a7e4d8d80af75ff51b45ea8b47fa77ace0310584",
          "sha256": "818bc522160372bff7c459947d004d92bbf0f02eaacec1fc0fff0791e4a08ee4",
          "sha1": "02a6e4d263807d742bd0c9dc807dca949c53a01f",
          "md5": "575c17c5a0a3a79e3b0a524db6ec5760"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "5aacabc"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-5aacabc.jar",
          "url": "antibytes-runtime-configuration-5aacabc.jar",
          "size": 10324,
          "sha512": "bc6ac1c51836138bce9049ba1f9f118b39383444775fb221c24a6cd75406f4bd14229d9f38cc8f6d68518f91a7e4d8d80af75ff51b45ea8b47fa77ace0310584",
          "sha256": "818bc522160372bff7c459947d004d92bbf0f02eaacec1fc0fff0791e4a08ee4",
          "sha1": "02a6e4d263807d742bd0c9dc807dca949c53a01f",
          "md5": "575c17c5a0a3a79e3b0a524db6ec5760"
        }
      ]
    }
  ]
}
