{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes",
    "module": "banana-i18n",
    "version": "4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n-metadata-all.jar",
          "url": "banana-i18n-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT-all.jar",
          "size": 670,
          "sha512": "19ec245548c230aa434d40af37fa8ccec2f6f5b7fabbd8602089701f3bf814317124d1f1a37f5c48261da46be049d7e782dab138742c8ffd72cf098f69ce16d1",
          "sha256": "4d6640a04888215e5bb3e91b8fe44de1e4741990f081d46a88816b38b70e8374",
          "sha1": "45aefef308299f4f1b7ced9f67d038e82ce0eb3d",
          "md5": "17648771d2c6d630ad319459eabacc3d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "banana-i18n.jar",
          "url": "banana-i18n-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT.jar",
          "size": 8072,
          "sha512": "d4473787335209c0bbabb93a99303688fd1c499d18107dc3478f37bf99a318caa1510ef8264f7e6466f7cbade917acdeceaa2181a6b20fd57b7cc3aed5733069",
          "sha256": "e13cc39c23678e61a2683648ff15ceecc7087812b840913013bd6d63ddd329fd",
          "sha1": "1166625f52deaa950419eb0097c0ec3a63437f4b",
          "md5": "d0c9714037387b61644a3b67db387c56"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT/banana-i18n-android-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-android",
        "version": "4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../banana-i18n-android/4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT/banana-i18n-android-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-android",
        "version": "4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT/banana-i18n-jvm-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-jvm",
        "version": "4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../banana-i18n-jvm/4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT/banana-i18n-jvm-4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT.module",
        "group": "tech.antibytes",
        "module": "banana-i18n-jvm",
        "version": "4ffe2e0-remove-tokenizer-rule-delimiters-SNAPSHOT"
      }
    }
  ]
}
