{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/2053836-bump-danger-SNAPSHOT/test-utils-2053836-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "2053836-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-2053836-bump-danger-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "4ec5ce7d61ab2ce82959df8996c6c54b90cb6909c2b8ffb1bf3736fea1414c47b629f64b0da967323e2f4b80ff205f1bd7b43622b437e1ee0297b4f2f2158857",
          "sha256": "a6db5b00b984f7de744c440c05f8796ca6869d1e2c458c5f3d10bb5442f9068d",
          "sha1": "15cd70d598f140062a88dedb19f4305ac356dc00",
          "md5": "3981f2a3bdd0db9fc01a05d2adae9437"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-2053836-bump-danger-SNAPSHOT.jar",
          "size": 17587,
          "sha512": "4ec5ce7d61ab2ce82959df8996c6c54b90cb6909c2b8ffb1bf3736fea1414c47b629f64b0da967323e2f4b80ff205f1bd7b43622b437e1ee0297b4f2f2158857",
          "sha256": "a6db5b00b984f7de744c440c05f8796ca6869d1e2c458c5f3d10bb5442f9068d",
          "sha1": "15cd70d598f140062a88dedb19f4305ac356dc00",
          "md5": "3981f2a3bdd0db9fc01a05d2adae9437"
        }
      ]
    }
  ]
}
