{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/f8d6e50-bump-workflows-SNAPSHOT/test-utils-resourceloader-f8d6e50-bump-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "f8d6e50-bump-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-linuxmipsel32-f8d6e50-bump-workflows-SNAPSHOT.klib",
          "size": 12906,
          "sha512": "710cd04f59fbda72b8830e39b43dc6773e8f93fbae24460531199ae026da213702904eeca0c7489a20e3c669934690510401fcad3881ce934d1b8d30cf3327d8",
          "sha256": "f3a9d19ceae9e9b93b63a9a02a1dcee8fbaaa3ba2e9063f5adc12597e31c9b05",
          "sha1": "90b49e4d0f36d30501b0e79092e011c2945420fb",
          "md5": "3059fe0a013e9ee5f9fbf8108ae0c517"
        }
      ]
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-linuxmipsel32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-linuxmipsel32-f8d6e50-bump-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3a26b640f07f47363b445100e88fc0da194dc9f9e988ba57e80e7cfbe6dd8f16175f6cd0c5d9fcd9883b10573fec096d18b0bfa4131b18177cb5250f427d3d09",
          "sha256": "f3aacb34a483693f5aa5a7faf4d4b4cb373878bebf6265516d28003c104e8075",
          "sha1": "3ca57b71ed9a4ec1855c67a9ccebe583f63db96b",
          "md5": "8d07c0255d2be90f68cacb30ba517c98"
        }
      ]
    }
  ]
}
