{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc02-fix-alias-resolving-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT.jar",
          "size": 68978,
          "sha512": "b5cc468544b1f4d147f979ae4eae2540372c5b07ed42d2e272c506816a75d508df0b740bf6f4bfc511752c6846274906030a369abcd65e9b945ceb64c022f56d",
          "sha256": "bc9d55482241a1ac2d052a864fac4e54adb44d7a1106ad56af12b45b77c2a591",
          "sha1": "94615227ddf072f0f1e2ba7a258677c3db796fe2",
          "md5": "f22efd2aa64c250b2645ed4c46e3cd6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT.jar",
          "size": 68978,
          "sha512": "b5cc468544b1f4d147f979ae4eae2540372c5b07ed42d2e272c506816a75d508df0b740bf6f4bfc511752c6846274906030a369abcd65e9b945ceb64c022f56d",
          "sha256": "bc9d55482241a1ac2d052a864fac4e54adb44d7a1106ad56af12b45b77c2a591",
          "sha1": "94615227ddf072f0f1e2ba7a258677c3db796fe2",
          "md5": "f22efd2aa64c250b2645ed4c46e3cd6d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "99380cb16553c918240afe15e85ddc3784d80e7b25778b2a392cb20174a2eccf26da0fac04761074b065cf91cc0323f3c5dfd03e33ac11bd475aaffc5c75fef7",
          "sha256": "f089b127bb0bf103cd3d352f7af043c17839e1e1ced128c054c65af9eddb0e39",
          "sha1": "3eeba8dd0e302bd071d9d3d547df045de1fbeef0",
          "md5": "c75640ca21bc203f97777e27783365a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc02-fix-alias-resolving-SNAPSHOT-sources.jar",
          "size": 14303,
          "sha512": "de8eecd7ad680817cf776226970136d75c5ae35534b005d09ed9cbf3dcf933543d9aecfedf47bbaa139121833a0d3e8a7a405d68fa7c3c76224b34c679b92666",
          "sha256": "c5adb6ab813a53163dfddf530ce6316ae9b0c077876caf0134bb112cd2bbd03d",
          "sha1": "333c943f368d246493aa5d1bff7c9005806504f6",
          "md5": "4d94d1879778f62c5540b21608b19221"
        }
      ]
    }
  ]
}
