{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "e37ca63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-publishing-e37ca63.jar",
          "url": "antibytes-publishing-e37ca63.jar",
          "size": 100326,
          "sha512": "945ffb4223ef6fa0372bb8a4249ca439ef62ec9f8348f6340ca05dd0df05cb065ca37f347ee43c36c79892eedf1d6f79779ba7db7d94b8abdb6d992e276a986d",
          "sha256": "326792a1ce193b8d48421c0a4287abba5026e2fbcf39ba111996987351d407ea",
          "sha1": "9cfad98d0e944ebefd7ebf768c582eef0c871b4c",
          "md5": "0186e303d3e029cb9b3a81fa3d8f4386"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.11.0.202103091610-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-e37ca63.jar",
          "url": "antibytes-publishing-e37ca63.jar",
          "size": 100326,
          "sha512": "945ffb4223ef6fa0372bb8a4249ca439ef62ec9f8348f6340ca05dd0df05cb065ca37f347ee43c36c79892eedf1d6f79779ba7db7d94b8abdb6d992e276a986d",
          "sha256": "326792a1ce193b8d48421c0a4287abba5026e2fbcf39ba111996987351d407ea",
          "sha1": "9cfad98d0e944ebefd7ebf768c582eef0c871b4c",
          "md5": "0186e303d3e029cb9b3a81fa3d8f4386"
        }
      ]
    }
  ]
}
