{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.4.0-add-more-sources-SNAPSHOT-all.jar",
          "url": "core-0.4.0-add-more-sources-SNAPSHOT-all.jar",
          "size": 22912,
          "sha512": "8e7e76305f76684a885c4af345f99b3d08ec5a2a84ddb1de2185c8e628550457244cdd676a1d5d2df9129d71fd992dfec98bb0676c0db3f571e446dfe193143d",
          "sha256": "6457dc01a435a50e4139edcb677b7f274f800849c929d152d113738a6f1fb1ab",
          "sha1": "a748992df4a1bc146f1c0d1833e2f799603c0d6d",
          "md5": "6c651bc0a949a05cf558241d4dad194a"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-0.4.0-add-more-sources-SNAPSHOT.jar",
          "url": "core-0.4.0-add-more-sources-SNAPSHOT.jar",
          "size": 37939,
          "sha512": "30a6c7faf60d207f2e063125d0d62ca3e46aa806f2afc480db454307ae6a242d3d9657ffa5419eac61efe43440e82352a3228674147667739dfbf7f395a8eb65",
          "sha256": "54a3ed7cb9c2a8e29564ee8c8b2d99f832796c81eb6ccc9d261b92f3afe7abb8",
          "sha1": "0b4c3952a1ce27dea7f5eeaaffa7c4189c0e382b",
          "md5": "74c1b7c091eb3a0991b98a7a48e5f680"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.4.0-add-more-sources-SNAPSHOT/core-android-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.4.0-add-more-sources-SNAPSHOT/core-android-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-android",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-androidnativearm32/0.4.0-add-more-sources-SNAPSHOT/core-androidnativearm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-androidnativearm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-androidnativearm64/0.4.0-add-more-sources-SNAPSHOT/core-androidnativearm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-androidnativearm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-androidnativex64/0.4.0-add-more-sources-SNAPSHOT/core-androidnativex64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-androidnativex64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-androidnativex86/0.4.0-add-more-sources-SNAPSHOT/core-androidnativex86-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-androidnativex86",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm32/0.4.0-add-more-sources-SNAPSHOT/core-iosarm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm32/0.4.0-add-more-sources-SNAPSHOT/core-iosarm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.4.0-add-more-sources-SNAPSHOT/core-iosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.4.0-add-more-sources-SNAPSHOT/core-iosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-iossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-iossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.4.0-add-more-sources-SNAPSHOT/core-iosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.4.0-add-more-sources-SNAPSHOT/core-iosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-iosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.4.0-add-more-sources-SNAPSHOT/core-js-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/0.4.0-add-more-sources-SNAPSHOT/core-js-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-js",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.4.0-add-more-sources-SNAPSHOT/core-jvm-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.4.0-add-more-sources-SNAPSHOT/core-jvm-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-jvm",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxarm32hfp/0.4.0-add-more-sources-SNAPSHOT/core-linuxarm32hfp-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxarm32hfp",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxarm64/0.4.0-add-more-sources-SNAPSHOT/core-linuxarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxmips32/0.4.0-add-more-sources-SNAPSHOT/core-linuxmips32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxmips32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxmips32/0.4.0-add-more-sources-SNAPSHOT/core-linuxmips32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxmips32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMipsel32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxmipsel32/0.4.0-add-more-sources-SNAPSHOT/core-linuxmipsel32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxmipsel32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxMipsel32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mipsel32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxmipsel32/0.4.0-add-more-sources-SNAPSHOT/core-linuxmipsel32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxmipsel32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.4.0-add-more-sources-SNAPSHOT/core-linuxx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-linuxx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-macosarm64/0.4.0-add-more-sources-SNAPSHOT/core-macosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-macosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-macosarm64/0.4.0-add-more-sources-SNAPSHOT/core-macosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-macosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-macosx64/0.4.0-add-more-sources-SNAPSHOT/core-macosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-macosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-macosx64/0.4.0-add-more-sources-SNAPSHOT/core-macosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-macosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-mingwx64/0.4.0-add-more-sources-SNAPSHOT/core-mingwx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-mingwx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-mingwx86/0.4.0-add-more-sources-SNAPSHOT/core-mingwx86-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-mingwx86",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvosarm64/0.4.0-add-more-sources-SNAPSHOT/core-tvosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvosarm64/0.4.0-add-more-sources-SNAPSHOT/core-tvosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-tvossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-tvossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvosx64/0.4.0-add-more-sources-SNAPSHOT/core-tvosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-tvosx64/0.4.0-add-more-sources-SNAPSHOT/core-tvosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-tvosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "wasm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "wasm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-wasm32/0.4.0-add-more-sources-SNAPSHOT/core-wasm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-wasm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosarm32/0.4.0-add-more-sources-SNAPSHOT/core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosarm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosarm32/0.4.0-add-more-sources-SNAPSHOT/core-watchosarm32-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosarm32",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosarm64/0.4.0-add-more-sources-SNAPSHOT/core-watchosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosarm64/0.4.0-add-more-sources-SNAPSHOT/core-watchosarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-watchossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchossimulatorarm64/0.4.0-add-more-sources-SNAPSHOT/core-watchossimulatorarm64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchossimulatorarm64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosx64/0.4.0-add-more-sources-SNAPSHOT/core-watchosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosx64/0.4.0-add-more-sources-SNAPSHOT/core-watchosx64-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosx64",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosx86/0.4.0-add-more-sources-SNAPSHOT/core-watchosx86-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosx86",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-watchosx86/0.4.0-add-more-sources-SNAPSHOT/core-watchosx86-0.4.0-add-more-sources-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "core-watchosx86",
        "version": "0.4.0-add-more-sources-SNAPSHOT"
      }
    }
  ]
}
