{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-add-more-sources-SNAPSHOT/core-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosx86-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 105854,
          "sha512": "e329f0c06611b415fbb9c916977e31b532c8f5c4f57beede067057b181d825beca6b22d347cca42785a3333b842b7ca40a24206b07de24b86cadb4c443c3a267",
          "sha256": "a8f3516fa309affa18f82228abdd015927f6f3cde92eccb4a1f2624fdcc1dfcf",
          "sha1": "c63d8d0b797ce07f3d4b0c4c2c0c9769537db28a",
          "md5": "fe87cbe3887090c412b4e53c685a5873"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosx86-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "core-watchosx86-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4fc3cfc84329aec8c13381b7b09bc35f3b23a7bdf19737a447376224142d42fd015ba01a2e0667e81fac0a415cf4d93eb46ad156ca37b52597aace426bc049fd",
          "sha256": "4fcf893586187ba02092a1b808d4071c0a08ea0cbed470f699934e5664357ff1",
          "sha1": "981fed650aae0f71ebd90f172e0c23f13e339279",
          "md5": "03bd75b93715dee911c2448e93f3fcb5"
        }
      ]
    }
  ]
}
