{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9aec7b7-bump-antibytes-SNAPSHOT/test-utils-9aec7b7-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9aec7b7-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-9aec7b7-bump-antibytes-SNAPSHOT.klib",
          "size": 14297,
          "sha512": "b2a60f82d7d49e65182861281bac176425ea6cd314ea6d5734aaa89001fae3876106ae1b1d3fa36318b1cd60a2139736611e4bb12fecab89bdf692cdb8b541a5",
          "sha256": "c8d56e34fbef56e6e988e17cf2efe0223f8ab9966497b527415b25eb7924e0f3",
          "sha1": "71413c7535c784cd5c63450f6a50c7832aee5809",
          "md5": "53dbe616f8bc3fdb80fb577fac10a62c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-9aec7b7-bump-antibytes-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-9aec7b7-bump-antibytes-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8daf9234a72338a9f8e1a1472479723e20da2642191e3e8f89eeeebc1761062ee9ad2efae14d0162b60b18fca55a117289db4b827596a14c46faa38802d8d4f0",
          "sha256": "f85b4566c65c822dd791c4161aa3728ca8057e99948bebbf4cd7783efdefe58a",
          "sha1": "9aaadfc6dc1f585be1f17f96d7c8d6fd094752b5",
          "md5": "6972a85e3cb739013019e7f6be326622"
        }
      ]
    }
  ]
}
