{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-change-overloaded-names-SNAPSHOT/kmock-0.1.1-change-overloaded-names-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-change-overloaded-names-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-change-overloaded-names-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-change-overloaded-names-SNAPSHOT.klib",
          "size": 160516,
          "sha512": "08f31f74e9b66979be5f09acb5dc69e591e8643725b2f8f2952e07dd35b7e302839a05b8e1c8634e7c10e8f72aa50177b80de0dd3b5a8e5e317676f364d4fe2d",
          "sha256": "5398e593068f0f6ceb565f71f811b78a3c9430f32b4d10234922b018fb32ef55",
          "sha1": "ea623b636b2706ad8cf68c104279bb037642bc54",
          "md5": "c56820c50f75de4caa0c54685948a296"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-change-overloaded-names-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-change-overloaded-names-SNAPSHOT.klib",
          "size": 160516,
          "sha512": "08f31f74e9b66979be5f09acb5dc69e591e8643725b2f8f2952e07dd35b7e302839a05b8e1c8634e7c10e8f72aa50177b80de0dd3b5a8e5e317676f364d4fe2d",
          "sha256": "5398e593068f0f6ceb565f71f811b78a3c9430f32b4d10234922b018fb32ef55",
          "sha1": "ea623b636b2706ad8cf68c104279bb037642bc54",
          "md5": "c56820c50f75de4caa0c54685948a296"
        }
      ]
    }
  ]
}
