{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "88cdd57-change-visibility-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-metadata-all.jar",
          "url": "test-utils-annotations-88cdd57-change-visibility-SNAPSHOT-all.jar",
          "size": 4917,
          "sha512": "1529c1c2cfb5a7757784a73289cc4414f0e7eb0caee0d1e90ae279357c2f7332f86498b659e792fa16587f61413b4d889d5b55868e1548b75f95c9bfbdd835e5",
          "sha256": "a42c4e50fe38f408a861a3f0b6d454e7e5d2c76006718538eaace1fe08b0999b",
          "sha1": "65c81cbb348a703c9ee15edec4889c39e2baf66d",
          "md5": "4c4a701aea8d24a8b668adde1ca4f546"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations.jar",
          "url": "test-utils-annotations-88cdd57-change-visibility-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "f31b06d6de59cec84716c4ab9f5757e5a97cf5738f49c226e3d5112908d98a897efebf477cf405cefd41d2f751bb63b521c409aebcfd973b2f88b8ff5985a833",
          "sha256": "bc0715ba65d490f84b169eb7fc3b1348e05f18b0a94010a8cea72771b5693237",
          "sha1": "7ced7f38d0e79524391da0c8f7163643fd0234b5",
          "md5": "ae7c2e63ddf532bc61fd5cc18a2cdd50"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-android-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-android-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-js-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-js-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-jvm-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-jvm-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/88cdd57-change-visibility-SNAPSHOT/test-utils-annotations-linuxx64-88cdd57-change-visibility-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "88cdd57-change-visibility-SNAPSHOT"
      }
    }
  ]
}
