{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/694b583-change-setup-SNAPSHOT/test-utils-annotations-junit4-694b583-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "694b583-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-694b583-change-setup-SNAPSHOT.klib",
          "size": 11351,
          "sha512": "eab01ccdc633125109f8844313c375f7821d74fd72713a110dcd21edadaadb67d0f9a4f42aea27872ff5873c6eca1367eabd6516f3e6f718c879785be3d3b229",
          "sha256": "ac318de8cc81066e0b59e7ee3b0d09e9f2fe1fa5288b0f460273a0d91e085660",
          "sha1": "8461e6ece21752696e7b9b24da62772ef6133a3b",
          "md5": "eb05bdc9218caeac1aafb0b1c4779775"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-694b583-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "afcb3d2b458a32d0e827a7ddf56e16fda3c5da27c22d2cb7a3c31654a5437ff433a6feb2939611afcdaee1d296fbcd96d701055393e1aa0fbd52c3c82e85bf20",
          "sha256": "dbbb299807bd840da9787c0d8648a543c7cf01df89824bdc3a5ba686fe9b20a1",
          "sha1": "c6acce49171bac61995cc2d53612222dde5ef2d8",
          "md5": "2fe78291ded7aa5fbe3910a63acffd02"
        }
      ]
    }
  ]
}
