{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "55f63ce-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-55f63ce-change-plugins.jar",
          "url": "antibytes-gradle-test-utils-55f63ce-change-plugins.jar",
          "size": 17226,
          "sha512": "d0a37bcc0a8f0ad4839052f46bcd06b07009bc2b55494cfbbced41b981b72ad3a06a260e1cb9cb770099fcb7c02ab009ce5c9e18e9296d9290409607c4a2ad66",
          "sha256": "32e0d06fa921572d52e99de4ebb6808171438c2a2bbc11dd3d6fa7ea1e193ec0",
          "sha1": "e8e180930af9712ba8121c0d20ee205216f39a05",
          "md5": "49840c98ebc3114c1d2161f344eb3592"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-55f63ce-change-plugins.jar",
          "url": "antibytes-gradle-test-utils-55f63ce-change-plugins.jar",
          "size": 17226,
          "sha512": "d0a37bcc0a8f0ad4839052f46bcd06b07009bc2b55494cfbbced41b981b72ad3a06a260e1cb9cb770099fcb7c02ab009ce5c9e18e9296d9290409607c4a2ad66",
          "sha256": "32e0d06fa921572d52e99de4ebb6808171438c2a2bbc11dd3d6fa7ea1e193ec0",
          "sha1": "e8e180930af9712ba8121c0d20ee205216f39a05",
          "md5": "49840c98ebc3114c1d2161f344eb3592"
        }
      ]
    }
  ]
}
