{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/d75bc0f-change-coroutines-SNAPSHOT/test-utils-ktor-d75bc0f-change-coroutines-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "d75bc0f-change-coroutines-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "a28abcf4ea3b534b6522012ae61865a8e1a57e90f7aa9130bd5dcb24172fcd28c5ad1bd98a3a5f2dcfe16914e25b4a924b9d5d024d0fea9f8e87c09a3b8b28b3",
          "sha256": "5d62b59ff27f4e184a665b7411d1213171a19707d45618815efeb2bed576a2d9",
          "sha1": "cc22544b71d84a7274095a00ab21d3943bcfac88",
          "md5": "f199d30fc54941a32e7a4faa80968745"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "url": "test-utils-ktor-jvm-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "size": 26352,
          "sha512": "a28abcf4ea3b534b6522012ae61865a8e1a57e90f7aa9130bd5dcb24172fcd28c5ad1bd98a3a5f2dcfe16914e25b4a924b9d5d024d0fea9f8e87c09a3b8b28b3",
          "sha256": "5d62b59ff27f4e184a665b7411d1213171a19707d45618815efeb2bed576a2d9",
          "sha1": "cc22544b71d84a7274095a00ab21d3943bcfac88",
          "md5": "f199d30fc54941a32e7a4faa80968745"
        }
      ]
    }
  ]
}
