{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/f000bfd-bump-settings-SNAPSHOT/test-utils-annotations-junit4-f000bfd-bump-settings-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "f000bfd-bump-settings-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm32-f000bfd-bump-settings-SNAPSHOT.klib",
          "size": 11352,
          "sha512": "3ad9cb0e72beb24f5b8a1b6e0851dad8d64d1f71079bda7a81588206ec6780f5f42e10dad5312c5bb25ff4bd05adaa1f57c6ec6cffe65b3399e9d45aad272391",
          "sha256": "c8c4dbff304e696658164f74ba6b4eec241104f9df423031a6d3b563ed4c1271",
          "sha1": "619a85e64390d97b73d89f6a06e3be3fbd32f4f1",
          "md5": "323b544f76d35e9a59b34e2ebf611627"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm32-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm32-f000bfd-bump-settings-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ed8469e199790c847da991d9a7aef1737c1dddfa70f7950c43a9f1fe2e8da5758bc3722c380da2b30c6d08adb1c827925c6e9f07a1078f251c7bb8e173508b2e",
          "sha256": "d0e1e5f323f8ceebd42897e86f81460d9984f25ef448ea7eda7e580afae30a89",
          "sha1": "9eecfb262a3d69234cee1743c70542c292f806a0",
          "md5": "958a9b4d275eaa70a74a870469cd3785"
        }
      ]
    }
  ]
}
