{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "c1ca71e-add-kotlin-android-versionCatalog",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "url": "antibytes-mkdocs-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "size": 11930,
          "sha512": "8dd7292dddd7bf72a101729437ae76d995fdc632b49a9acc1d9f19572835b8dfcc899cbb07073495e9100c036af264603542d4a20a9543d12a5d0e267b31714f",
          "sha256": "25fce4b15c0f593fb84c6afdf5404417293a7d72c6bb31ad41876dede53361e3",
          "sha1": "411a6d9c4b0315045c594178fc05eada81fb60aa",
          "md5": "d3af697ecd63a90bed8939d5f87d111b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "c1ca71e-add-kotlin-android-versionCatalog"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "url": "antibytes-mkdocs-c1ca71e-add-kotlin-android-versionCatalog.jar",
          "size": 11930,
          "sha512": "8dd7292dddd7bf72a101729437ae76d995fdc632b49a9acc1d9f19572835b8dfcc899cbb07073495e9100c036af264603542d4a20a9543d12a5d0e267b31714f",
          "sha256": "25fce4b15c0f593fb84c6afdf5404417293a7d72c6bb31ad41876dede53361e3",
          "sha1": "411a6d9c4b0315045c594178fc05eada81fb60aa",
          "md5": "d3af697ecd63a90bed8939d5f87d111b"
        }
      ]
    }
  ]
}
