{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "bb3571d-add-random-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-metadata-bb3571d-add-random-wrapper-SNAPSHOT-all.jar",
          "url": "fixture-bb3571d-add-random-wrapper-SNAPSHOT-all.jar",
          "size": 14799,
          "sha512": "dcfd1d3a3c067587bba6f603e051cffe405f77923e2be7b726acc48e63c12be3dac7a5c1051aa783417f895d838ad6445d896a81ae19c2e9db6d8e808833c1ce",
          "sha256": "616e684f6ef72191f69a007e94722eee5f5d27f88a750567e1b330183beb7367",
          "sha1": "c9c8684824bfec61768d93eb8aa4328701d0edbe",
          "md5": "0e4cda25bb693b03fe62558e11e6f816"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fixture-bb3571d-add-random-wrapper-SNAPSHOT.jar",
          "url": "fixture-bb3571d-add-random-wrapper-SNAPSHOT.jar",
          "size": 20581,
          "sha512": "9d9aafdc6cb8256323eb365716a230679e114d3c5a2331763599695dc3b8017c82ba9a2da546044481a5ba1ecf8301416ea1f6b4f94db10eb675cdf05f7fbb4f",
          "sha256": "ec471b04e48ba200351f624ff4f32c6e21132ce9668d0255e3b035a76799a751",
          "sha1": "1035dfac8dd75be750d1748c0b6259c889b33f76",
          "md5": "ad579976ae998f2c912966a87ef4fce4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/bb3571d-add-random-wrapper-SNAPSHOT/fixture-android-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-android",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fixture-android/bb3571d-add-random-wrapper-SNAPSHOT/fixture-android-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-android",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iosarm64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosarm64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosarm64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iosarm64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosarm64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iossimulatorarm64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iossimulatorarm64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iossimulatorarm64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iossimulatorarm64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iossimulatorarm64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iossimulatorarm64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iosx64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosx64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-iosx64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-iosx64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-iosx64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/bb3571d-add-random-wrapper-SNAPSHOT/fixture-js-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-js",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../fixture-js/bb3571d-add-random-wrapper-SNAPSHOT/fixture-js-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-js",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/bb3571d-add-random-wrapper-SNAPSHOT/fixture-jvm-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-jvm",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fixture-jvm/bb3571d-add-random-wrapper-SNAPSHOT/fixture-jvm-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-jvm",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fixture-linuxx64/bb3571d-add-random-wrapper-SNAPSHOT/fixture-linuxx64-bb3571d-add-random-wrapper-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "fixture-linuxx64",
        "version": "bb3571d-add-random-wrapper-SNAPSHOT"
      }
    }
  ]
}
