{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "2c2de1a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-2c2de1a.jar",
          "url": "antibytes-versioning-2c2de1a.jar",
          "size": 16029,
          "sha512": "458961da2765ba69b2e59ee953ae37e4a3e291027c2d0e77d4b5a3cbe221d9b13ce2fe6db468db5ac3a76d47b16713eb5b57fe827fb1f2cefc08238331035f21",
          "sha256": "dff86fd035ec35d508c3764ca87e2c001a574eff9c1a14a45cf722240b8996ad",
          "sha1": "a55cedc90a9b10a8f7dc689bf3162203dab6dd70",
          "md5": "49a9a3d5a8499108ea1069c6a5b58da5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-2c2de1a.jar",
          "url": "antibytes-versioning-2c2de1a.jar",
          "size": 16029,
          "sha512": "458961da2765ba69b2e59ee953ae37e4a3e291027c2d0e77d4b5a3cbe221d9b13ce2fe6db468db5ac3a76d47b16713eb5b57fe827fb1f2cefc08238331035f21",
          "sha256": "dff86fd035ec35d508c3764ca87e2c001a574eff9c1a14a45cf722240b8996ad",
          "sha1": "a55cedc90a9b10a8f7dc689bf3162203dab6dd70",
          "md5": "49a9a3d5a8499108ea1069c6a5b58da5"
        }
      ]
    }
  ]
}
