{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-configuration",
    "version": "4cc4725",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-configuration-4cc4725.jar",
          "url": "antibytes-configuration-4cc4725.jar",
          "size": 59750,
          "sha512": "c9ff3132c8e76b2a0ec230eb225b07c719e0ce207cf672ff080aac2998064bb1563618242e66cf5fa3d32c6292d1d80c8743ab71274224823cee09fbdb76bf38",
          "sha256": "737a41115430b1f6c6c76c73f0664c55999513eaab6aae3b7e8e1889401160f2",
          "sha1": "f55099607398c129bc1566c282e7c0b13470f386",
          "md5": "a5ebdfbe05bb5636b6db2a5b52c76f04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4cc4725"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-configuration-4cc4725.jar",
          "url": "antibytes-configuration-4cc4725.jar",
          "size": 59750,
          "sha512": "c9ff3132c8e76b2a0ec230eb225b07c719e0ce207cf672ff080aac2998064bb1563618242e66cf5fa3d32c6292d1d80c8743ab71274224823cee09fbdb76bf38",
          "sha256": "737a41115430b1f6c6c76c73f0664c55999513eaab6aae3b7e8e1889401160f2",
          "sha1": "f55099607398c129bc1566c282e7c0b13470f386",
          "md5": "a5ebdfbe05bb5636b6db2a5b52c76f04"
        }
      ]
    }
  ]
}
