{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/dac75a8-change-workflows-SNAPSHOT/test-utils-annotations-junit5-dac75a8-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "dac75a8-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "39408bebe68ebbba20a286fb701053a86674f751402671ad46e53f91d32913e5181e6f09220b7b1526ac382781c5058219d4e35146037c422ede36ac3e59df9e",
          "sha256": "ceeb9ccafa7280990fe1d00dbd83a0b6527162b5a860624345702a7d9f358562",
          "sha1": "36ff025ba164fb5bf61df32cd80345b083060669",
          "md5": "42392e5b50189cd85d61e3f7c25d91cc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-dac75a8-change-workflows-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "39408bebe68ebbba20a286fb701053a86674f751402671ad46e53f91d32913e5181e6f09220b7b1526ac382781c5058219d4e35146037c422ede36ac3e59df9e",
          "sha256": "ceeb9ccafa7280990fe1d00dbd83a0b6527162b5a860624345702a7d9f358562",
          "sha1": "36ff025ba164fb5bf61df32cd80345b083060669",
          "md5": "42392e5b50189cd85d61e3f7c25d91cc"
        }
      ]
    }
  ]
}
