{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/93dc107-fix-single-sources-SNAPSHOT/kmock-93dc107-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "93dc107-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-93dc107-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-93dc107-fix-single-sources-SNAPSHOT.jar",
          "size": 119666,
          "sha512": "1d7ffb78459a59cacd2cd97971a3c9720d23b8df98ccf3ca13be15c7d2e1f2fec2338643b677a2c2c5d7b8dd086fb590e40187c681e06d1f307a3a900bcff6ed",
          "sha256": "3fba6e391ef40c354acd22172d8dcc6c6c2d10361aed60fb628e894efd4114cc",
          "sha1": "9ed8cf3e5ed7aba778fd3a552ed30cf12bbf4e19",
          "md5": "bba9353bc65a414557d5b8a1aca7ddc0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "8b81c5a"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-93dc107-fix-single-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-93dc107-fix-single-sources-SNAPSHOT.jar",
          "size": 119666,
          "sha512": "1d7ffb78459a59cacd2cd97971a3c9720d23b8df98ccf3ca13be15c7d2e1f2fec2338643b677a2c2c5d7b8dd086fb590e40187c681e06d1f307a3a900bcff6ed",
          "sha256": "3fba6e391ef40c354acd22172d8dcc6c6c2d10361aed60fb628e894efd4114cc",
          "sha1": "9ed8cf3e5ed7aba778fd3a552ed30cf12bbf4e19",
          "md5": "bba9353bc65a414557d5b8a1aca7ddc0"
        }
      ]
    }
  ]
}
