{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/30769ee-change-setup-SNAPSHOT/test-utils-annotations-junit5-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT.klib",
          "size": 7172,
          "sha512": "49b0d63fe73f9439f7b0cf47770f20a515acf4b3d9c194b8766961c1e058e24f8967bc4a5af0bbc89006a690e3e7f1535cad6cb18a6eda57eb62bed395156e03",
          "sha256": "bd86a8f9716a1f6f9df903e720dac0a224d2c0e5aad3f36eaaab6aacbb383942",
          "sha1": "d4b90b87c83cabb53a712681d2a5ef850cd0f6c5",
          "md5": "0ce377dc3c797c827ca218973d89be79"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e4231ef880a6fe44b899b069ad3500c600c1e1ac96837cc32133052783480fc913398d73c329222b688207e4f67c1f29876a83197ad07f8e02034b732842d137",
          "sha256": "2763ab84b6d7913498319ad5e000fdf4a613c4157c7ecab7efd9abf035a2135c",
          "sha1": "cf5413590fe0d645da26e08ee6b11817d5e57a40",
          "md5": "f5c2879063f4676713d697dd65fb9987"
        }
      ]
    }
  ]
}
