{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-enum-selector-SNAPSHOT/core-0.2.0-add-enum-selector-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-enum-selector-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.2.0-add-enum-selector-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-add-enum-selector-SNAPSHOT.jar",
          "size": 251506,
          "sha512": "862887c8131ae72e6353c91f2bd1ffb96c4c287c9b44371d677423b21df5d6a2e44697eae6c9bc3582b767452abb1e9cc5768beb3db65acc3ae7e7aad9b52c30",
          "sha256": "c4598755ca42d5074fe6c5a70a6608fbd94cb2354bf43307607647c4ad6bd13b",
          "sha1": "eaa5d0b5d966930064007d4788a84ee7e375fda5",
          "md5": "481a0bd8daf382cace398d36ea297cbb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.2.0-add-enum-selector-SNAPSHOT.jar",
          "url": "core-jvm-0.2.0-add-enum-selector-SNAPSHOT.jar",
          "size": 251506,
          "sha512": "862887c8131ae72e6353c91f2bd1ffb96c4c287c9b44371d677423b21df5d6a2e44697eae6c9bc3582b767452abb1e9cc5768beb3db65acc3ae7e7aad9b52c30",
          "sha256": "c4598755ca42d5074fe6c5a70a6608fbd94cb2354bf43307607647c4ad6bd13b",
          "sha1": "eaa5d0b5d966930064007d4788a84ee7e375fda5",
          "md5": "481a0bd8daf382cace398d36ea297cbb"
        }
      ]
    }
  ]
}
