{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "7c5b6aa-add-splash-screen",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-kmp-configuration-7c5b6aa-add-splash-screen.jar",
          "size": 72745,
          "sha512": "c8ff89430e45b4a90cf15156b27092ad4424b6116312b5542b42d7177284587fc73a8a7d530fda986199e4d4024d9d5396fad9fc9beec49c4d03c3042afc0d84",
          "sha256": "6b0d43fb5fa005fc6db377cad2acb5354b3b0f2ecb135016e661f5ddfd2c7834",
          "sha1": "a7a91d2e61870216a5773ae7817551c3ba310ed9",
          "md5": "9dbc6cca6f773823fab018bfe840a67c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "7c5b6aa-add-splash-screen"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-kmp-configuration-7c5b6aa-add-splash-screen.jar",
          "size": 72745,
          "sha512": "c8ff89430e45b4a90cf15156b27092ad4424b6116312b5542b42d7177284587fc73a8a7d530fda986199e4d4024d9d5396fad9fc9beec49c4d03c3042afc0d84",
          "sha256": "6b0d43fb5fa005fc6db377cad2acb5354b3b0f2ecb135016e661f5ddfd2c7834",
          "sha1": "a7a91d2e61870216a5773ae7817551c3ba310ed9",
          "md5": "9dbc6cca6f773823fab018bfe840a67c"
        }
      ]
    }
  ]
}
