{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/9b1a651-fix-single-sources-SNAPSHOT/kmock-9b1a651-fix-single-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "9b1a651-fix-single-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "56c5f3f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-9b1a651-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-9b1a651-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "d19db7882293cc5e2119b95fe4d512e96ca075db486ef50a1439dffb11ef93c0b8b841a1cd014256e41fd915f87bc968bdf34ba23e3e60514d10aef7f0e37ac7",
          "sha256": "4c41f87d9081a9d8fc41022ed1f21f96d07177de41c424f99b12573d035bfd0c",
          "sha1": "903b2cacd9399d9e482cee989e7ca3e613286e79",
          "md5": "b7ca05dd3ae7009cce67dd58bc278ccd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "56c5f3f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-9b1a651-fix-single-sources-SNAPSHOT.klib",
          "url": "kmock-js-9b1a651-fix-single-sources-SNAPSHOT.klib",
          "size": 74316,
          "sha512": "d19db7882293cc5e2119b95fe4d512e96ca075db486ef50a1439dffb11ef93c0b8b841a1cd014256e41fd915f87bc968bdf34ba23e3e60514d10aef7f0e37ac7",
          "sha256": "4c41f87d9081a9d8fc41022ed1f21f96d07177de41c424f99b12573d035bfd0c",
          "sha1": "903b2cacd9399d9e482cee989e7ca3e613286e79",
          "md5": "b7ca05dd3ae7009cce67dd58bc278ccd"
        }
      ]
    }
  ]
}
