{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/6367305-change-extensions-SNAPSHOT/fixture-6367305-change-extensions-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "6367305-change-extensions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosx64-6367305-change-extensions-SNAPSHOT.klib",
          "size": 43559,
          "sha512": "266085b6eb15be4d995204689634d51309a0686a8fac83e638aaa065e3174875b805c892919ffdb4e2d979060e95b6f9460886b293d4799885a091a433544488",
          "sha256": "2c08a6868f223da74f84cc193c076aebe6f42b2f369e6376fdc1444771cce2bc",
          "sha1": "6fc06922f2d6edfda00ac715285b5aa678af7448",
          "md5": "cab05b61748c6611d226ab73ebadd83b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosx64-6367305-change-extensions-SNAPSHOT-metadata.jar",
          "url": "fixture-iosx64-6367305-change-extensions-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9423afa0c5e2119e49d30f0f45765ee74f82df4283dd1364d76bdc76d8fb9470a5044ab3d698063a4d0258ad315ecd886d64feb31a211ee42cc0bd0c2e58c10d",
          "sha256": "824070bb01329c67106c79eca735f0f15f17fab718be42907ca261dc3e5edde6",
          "sha1": "85a2cea8b4cd7be196727a4379dd020fd86fb85f",
          "md5": "cfaa1dc9759cd31190591feb775bcfec"
        }
      ]
    }
  ]
}
