{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/753d329-add-ios-SNAPSHOT/test-utils-annotations-753d329-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "753d329-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-753d329-add-ios-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "9e54874e64d81a2de4471cca06759702341df20f432acfb53ff25059ca9ae0639277537565c1510503d48f8977be4f4f82210886e05a9b03d36f43fd23136c67",
          "sha256": "e4ed8961e6ec15bf242790bbcb6945fa1f48df4b97c600a109ba00d4e9ab1c6b",
          "sha1": "c9a7b4de2d1db06c5dc5caf3a9379d69caed5e06",
          "md5": "65d0315b86e17a014d51787e3e7f49c8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm.jar",
          "url": "test-utils-annotations-jvm-753d329-add-ios-SNAPSHOT.jar",
          "size": 10872,
          "sha512": "9e54874e64d81a2de4471cca06759702341df20f432acfb53ff25059ca9ae0639277537565c1510503d48f8977be4f4f82210886e05a9b03d36f43fd23136c67",
          "sha256": "e4ed8961e6ec15bf242790bbcb6945fa1f48df4b97c600a109ba00d4e9ab1c6b",
          "sha1": "c9a7b4de2d1db06c5dc5caf3a9379d69caed5e06",
          "md5": "65d0315b86e17a014d51787e3e7f49c8"
        }
      ]
    }
  ]
}
