{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "bb86acb-add-snapshot-supression-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "ca9da704265123741b843aff6f0282b5f8b1f839491458c0d5620830ec7add25f911d5360df7e7f7a0e2ee6fec697547cd05641c10a27bc8837bab0a8a3bad90",
          "sha256": "75acccd6a7fbf3975197b8c0c2a6fe64cd8e86a8bd10f7989e9ef87c0b701713",
          "sha1": "0e6d123571db112571dd398d2172ea9e2e65d062",
          "md5": "1d7d7fe523bae8c64a3c3282e8789317"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "bb86acb-add-snapshot-supression-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "url": "antibytes-dependency-bb86acb-add-snapshot-supression-SNAPSHOT.jar",
          "size": 88198,
          "sha512": "ca9da704265123741b843aff6f0282b5f8b1f839491458c0d5620830ec7add25f911d5360df7e7f7a0e2ee6fec697547cd05641c10a27bc8837bab0a8a3bad90",
          "sha256": "75acccd6a7fbf3975197b8c0c2a6fe64cd8e86a8bd10f7989e9ef87c0b701713",
          "sha1": "0e6d123571db112571dd398d2172ea9e2e65d062",
          "md5": "1d7d7fe523bae8c64a3c3282e8789317"
        }
      ]
    }
  ]
}
