{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "2bc11b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-2bc11b1.jar",
          "url": "antibytes-dependency-2bc11b1.jar",
          "size": 71483,
          "sha512": "4dc1cfbebd8dd99472d5cfbd3074de078245837ba796ed082035f9d3433722f9f8c1ad47d081ee2dd46cc04e6664821c8433fbdbc03f4f5e98edd7eb71a52d0e",
          "sha256": "58104e84684a2e4512522e2166a4cf3ef175c3a76d9423309a8c411b1e4ab8d9",
          "sha1": "737866ec71228005a5972aa1c4e14eb296291e93",
          "md5": "6b156fef818e168b55b8eb90fa54f33f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.17.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.46.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "2bc11b1"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-2bc11b1.jar",
          "url": "antibytes-dependency-2bc11b1.jar",
          "size": 71483,
          "sha512": "4dc1cfbebd8dd99472d5cfbd3074de078245837ba796ed082035f9d3433722f9f8c1ad47d081ee2dd46cc04e6664821c8433fbdbc03f4f5e98edd7eb71a52d0e",
          "sha256": "58104e84684a2e4512522e2166a4cf3ef175c3a76d9423309a8c411b1e4ab8d9",
          "sha1": "737866ec71228005a5972aa1c4e14eb296291e93",
          "md5": "6b156fef818e168b55b8eb90fa54f33f"
        }
      ]
    }
  ]
}
