{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "1ba4d29-change-gradle-action-runner",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-kmp-configuration-1ba4d29-change-gradle-action-runner.jar",
          "size": 12967,
          "sha512": "db05dd3136cc23c4600e0618d7d127ba516a9ec152f64ee140dc7093ab51d3dfede88b287125eb1c7d0aa14bda3b98a60496f13d5aec87e3a16f4aa64d46bd9d",
          "sha256": "f585afe66b663debee2209d847c9df75c697a58b50eb6d7811b87c1bc5854da7",
          "sha1": "c7874eece8c172a9082491d98dcfa944420500b8",
          "md5": "ea496de103c572a91bf96970a5a93861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1ba4d29-change-gradle-action-runner"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-1ba4d29-change-gradle-action-runner.jar",
          "url": "antibytes-kmp-configuration-1ba4d29-change-gradle-action-runner.jar",
          "size": 12967,
          "sha512": "db05dd3136cc23c4600e0618d7d127ba516a9ec152f64ee140dc7093ab51d3dfede88b287125eb1c7d0aa14bda3b98a60496f13d5aec87e3a16f4aa64d46bd9d",
          "sha256": "f585afe66b663debee2209d847c9df75c697a58b50eb6d7811b87c1bc5854da7",
          "sha1": "c7874eece8c172a9082491d98dcfa944420500b8",
          "md5": "ea496de103c572a91bf96970a5a93861"
        }
      ]
    }
  ]
}
