{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "a0bd384",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-a0bd384.jar",
          "url": "antibytes-coverage-a0bd384.jar",
          "size": 122687,
          "sha512": "04a40f4c8e81001696854dcee113ef300252920c28cb10ca217c0c8a64d891f1d2674f36ecbcc0656161ed39cfcedf9a8418a335bc7f055b513e5e07b6d12b1b",
          "sha256": "e7cc4d6b6bc72a9132161a4335e252b012a4163eb586c3a21cb519d12bb2d244",
          "sha1": "f441c9a9ed87926031d3514759da738ccc2e1fe8",
          "md5": "889700d56f0a88fb97ae35252a09bce1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "a0bd384"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-a0bd384.jar",
          "url": "antibytes-coverage-a0bd384.jar",
          "size": 122687,
          "sha512": "04a40f4c8e81001696854dcee113ef300252920c28cb10ca217c0c8a64d891f1d2674f36ecbcc0656161ed39cfcedf9a8418a335bc7f055b513e5e07b6d12b1b",
          "sha256": "e7cc4d6b6bc72a9132161a4335e252b012a4163eb586c3a21cb519d12bb2d244",
          "sha1": "f441c9a9ed87926031d3514759da738ccc2e1fe8",
          "md5": "889700d56f0a88fb97ae35252a09bce1"
        }
      ]
    }
  ]
}
