{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "55f63ce-change-plugins",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-55f63ce-change-plugins.jar",
          "url": "antibytes-dependency-settings-55f63ce-change-plugins.jar",
          "size": 11187,
          "sha512": "a1aa7b00b860fbb2e743feb92239682818f21bb83484ec6ceaf684f2f6dce80b5d4aa06103533f8489d02355cfbbf35a067f10c25708bb1f02613baec2bec137",
          "sha256": "fb3b97d7d07fb7dfabd0edbae8eba80e40735f91e59c88a0940995a0425eca85",
          "sha1": "fc45c35397b4dbf05d3cb1417e1017876b969a3a",
          "md5": "61cd48125e0bb0d4be2026959992d727"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-settings-55f63ce-change-plugins.jar",
          "url": "antibytes-dependency-settings-55f63ce-change-plugins.jar",
          "size": 11187,
          "sha512": "a1aa7b00b860fbb2e743feb92239682818f21bb83484ec6ceaf684f2f6dce80b5d4aa06103533f8489d02355cfbbf35a067f10c25708bb1f02613baec2bec137",
          "sha256": "fb3b97d7d07fb7dfabd0edbae8eba80e40735f91e59c88a0940995a0425eca85",
          "sha1": "fc45c35397b4dbf05d3cb1417e1017876b969a3a",
          "md5": "61cd48125e0bb0d4be2026959992d727"
        }
      ]
    }
  ]
}
