{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-test-utils",
    "version": "966382f-add-doc-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-966382f-add-doc-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-966382f-add-doc-plugin-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "53474db81e73669d53ef0d2e1105e089bb9a7f36b08e0830d9aa1c1139687133cbcc4ad6aab246ddae6c11531c4e662e863ff65d536232e82a285e1a832c8df0",
          "sha256": "efe298e08a383de208dc4c4fb0bba4a4f5ad9f2082e647cd2ff162a4f0cd36dd",
          "sha1": "89f1d531cd126e8ef65f6dfe9880a8ae71553f58",
          "md5": "08f18a0ee67c9fabd5464e63873a9d09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-966382f-add-doc-plugin-SNAPSHOT.jar",
          "url": "antibytes-gradle-test-utils-966382f-add-doc-plugin-SNAPSHOT.jar",
          "size": 17223,
          "sha512": "53474db81e73669d53ef0d2e1105e089bb9a7f36b08e0830d9aa1c1139687133cbcc4ad6aab246ddae6c11531c4e662e863ff65d536232e82a285e1a832c8df0",
          "sha256": "efe298e08a383de208dc4c4fb0bba4a4f5ad9f2082e647cd2ff162a4f0cd36dd",
          "sha1": "89f1d531cd126e8ef65f6dfe9880a8ae71553f58",
          "md5": "08f18a0ee67c9fabd5464e63873a9d09"
        }
      ]
    }
  ]
}
