{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktx-datetime/0.4.0-remove-android-studio-workaround-SNAPSHOT/ktx-datetime-0.4.0-remove-android-studio-workaround-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-remove-android-studio-workaround-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-remove-android-studio-workaround-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime.klib",
          "url": "ktx-datetime-watchosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT.klib",
          "size": 34668,
          "sha512": "c7a4671178ad4b362847e35fd6a4919a0b303cda4d2932c97acdd922d0714723b70382b554344c2e99c1aeb2c0f729a6cb0f48e8f13f7ccd5c104275354dd0d5",
          "sha256": "4b270b33a023430dce73bc0508224a712a1619a93e8ddb8802f4ede357b6985a",
          "sha1": "b901658aa892c110c85a711e4f35840c79d4f5f3",
          "md5": "255f5b31e05ae61a0519c27ec5fdb60f"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-remove-android-studio-workaround-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-watchosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "url": "ktx-datetime-watchosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "82757493e74247331dc8bbf59fc0b1e596c8753c4ffa01eacf914e81ddf69aab04225ccdf07116af389f0c1b158c296e39b0340c29fe55ba4b7119991be0ba92",
          "sha256": "84a8d21f450229d22092b26db28114e4daab44e4bbd12107166d4402dc33fcab",
          "sha1": "c9da811220279156d13aa8c03dc9162439293187",
          "md5": "4806036a86b2367366264a5be854ed7f"
        }
      ]
    }
  ]
}
