{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.2.2-SNAPSHOT/kmock-0.2.2-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-iosarm64-0.2.2-SNAPSHOT.klib",
          "size": 202838,
          "sha512": "6cf933b9a449621d34b702d08652cc7aa4e8afd4763549b5eecd8d0a377316cfea1d359837fc10612aef923087683e63bf496766696430db0481e97da58c9302",
          "sha256": "c54f2fc0a114e416f26a52c3a0a5cbc0973693ce5003ed2530347d8703e42246",
          "sha1": "dad56645f870e1b5d37a784ce17df81f840c3944",
          "md5": "70549751a64f22aab63da0489ac037da"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-iosarm64-0.2.2-SNAPSHOT-metadata.jar",
          "url": "kmock-iosarm64-0.2.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "f84103c5ee76ea8e00b1ea275193fcb7bd4228b22769064fef36fc899a97bdcb38ba1e29ec88d8088ac0214430d0957c3140b19d7365a3889f6395ff8ba6079e",
          "sha256": "9ee74fd4f1d6697515f4396cbdb659c785e00812a8de56dc456de1256188c3f4",
          "sha1": "72a7be9573c6e8a6ec8a29c4dd39ce82583c2db7",
          "md5": "d973cde2ad61b834dc73cdaa4aad50d6"
        }
      ]
    }
  ]
}
