{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-utils",
    "version": "136fb3a-enable-ci-buildcache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-136fb3a-enable-ci-buildcache.jar",
          "url": "antibytes-gradle-utils-136fb3a-enable-ci-buildcache.jar",
          "size": 11392,
          "sha512": "b3e517a2a6bb963be18dadef12236a1a15b88a054d802eb53525632966b82690e9e6e290faa0f11ae3f206d739e678beeb0ed437b37da47f55fff93f5409a605",
          "sha256": "9acdcdf759ebc903245315b249ba5a5948c397fef768f474117f35e3d40cfd3c",
          "sha1": "a3754b1af1ca2ee83ba25cc969ff787d178c26fa",
          "md5": "c397c6c7607f8f7ec3d4dc91679b07a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-136fb3a-enable-ci-buildcache.jar",
          "url": "antibytes-gradle-utils-136fb3a-enable-ci-buildcache.jar",
          "size": 11392,
          "sha512": "b3e517a2a6bb963be18dadef12236a1a15b88a054d802eb53525632966b82690e9e6e290faa0f11ae3f206d739e678beeb0ed437b37da47f55fff93f5409a605",
          "sha256": "9acdcdf759ebc903245315b249ba5a5948c397fef768f474117f35e3d40cfd3c",
          "sha1": "a3754b1af1ca2ee83ba25cc969ff787d178c26fa",
          "md5": "c397c6c7607f8f7ec3d4dc91679b07a3"
        }
      ]
    }
  ]
}
