{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-change-build-config-SNAPSHOT/kmock-0.3.0-rc04-change-build-config-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-change-build-config-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-change-build-config-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-change-build-config-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "a536a5429a447f0bacc9ad6a9aaae582863c30967c4a981bb31bee3b2acca9e11c74dfc1aa445e04ec09cc9ddbb3f6b5258b55ff2397036df4d82b0c33cf6715",
          "sha256": "b42b0c353a74dc70558b2b83d66ee7bc13407e68542f5fe20aa111ff9d6ec76d",
          "sha1": "40b83148565d22a299ebbbdc5cc23296924f719e",
          "md5": "ca68e44ff2e7b28390a50d5ba57cd09a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-change-build-config-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-change-build-config-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "a536a5429a447f0bacc9ad6a9aaae582863c30967c4a981bb31bee3b2acca9e11c74dfc1aa445e04ec09cc9ddbb3f6b5258b55ff2397036df4d82b0c33cf6715",
          "sha256": "b42b0c353a74dc70558b2b83d66ee7bc13407e68542f5fe20aa111ff9d6ec76d",
          "sha1": "40b83148565d22a299ebbbdc5cc23296924f719e",
          "md5": "ca68e44ff2e7b28390a50d5ba57cd09a"
        }
      ]
    }
  ]
}
