{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/efb8eff-remove-dependency-plugin-SNAPSHOT/test-utils-coroutine-efb8eff-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "efb8eff-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 10112,
          "sha512": "0c9109497ef5116df57d780fb9927fa9a211b8c342a4a7fbb3461b555cfc0a69658dd4d762d29aeb47083f1264b99df98abe9ca148acfe1f7227ae8e67041ad7",
          "sha256": "2da8c8de1522ad369562f0bd2b838eba30fdb3b2eefa319776aab12fff1d9c69",
          "sha1": "3d1c065ed2929a8a21b7209b42256a163e080647",
          "md5": "6e8825ff0ee058c6b2a9aeeefd714a50"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-iosx64-efb8eff-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4bfb6d0cf2dfa537cf1222ffb2e74bef40ae96ad2e2887e3a868c8ab410848b1feb074b64021931b81bc6dfd9fd1e98489eeb47da6b42d5f9e4b7fe30aa2f7c6",
          "sha256": "e0df155f72d206cfae1f20f54b56dc3af24b7bcd71f85a76423e992edff62246",
          "sha1": "58f528ff0980d1b5fd31e17b349538dc9b3c4135",
          "md5": "ed2f9340a51fc0d7096beae26c9b93a8"
        }
      ]
    }
  ]
}
