{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "4cc4725",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-4cc4725.jar",
          "url": "antibytes-grammar-tools-4cc4725.jar",
          "size": 39373,
          "sha512": "9e327bfeede7910e4c64c49e7f72457845c284c6584ec93ee2ab98db9a53e193077d2486d73c7d2475f1a1d1d6bec19c93c5d1ceedbb513d4e7f7799caf28d32",
          "sha256": "c765ad6e7a02d5bcb0ae82832a47382f9843b054c7301ea2d6d8b6b3ade07523",
          "sha1": "7b223142cbfd9b4cca71b97457fa701f2e85cffb",
          "md5": "a3809ec8e19ae2365327e56de8e461e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-4cc4725.jar",
          "url": "antibytes-grammar-tools-4cc4725.jar",
          "size": 39373,
          "sha512": "9e327bfeede7910e4c64c49e7f72457845c284c6584ec93ee2ab98db9a53e193077d2486d73c7d2475f1a1d1d6bec19c93c5d1ceedbb513d4e7f7799caf28d32",
          "sha256": "c765ad6e7a02d5bcb0ae82832a47382f9843b054c7301ea2d6d8b6b3ade07523",
          "sha1": "7b223142cbfd9b4cca71b97457fa701f2e85cffb",
          "md5": "a3809ec8e19ae2365327e56de8e461e3"
        }
      ]
    }
  ]
}
