{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/0fd7252-change-project-setup-SNAPSHOT/test-utils-resourceloader-0fd7252-change-project-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "0fd7252-change-project-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "url": "test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "size": 9574,
          "sha512": "7f31ee56040e3416191e0a7033bf0b5c82def07dd3b676cdf90386a4eb8c3095988e790ec39a3063ff04fe523e100565b5a3c57781b4048c1125544bfee9f284",
          "sha256": "f0759f2cb07b2f481adbd73f3de791013f503bf40104928d497da5d70ff008bb",
          "sha1": "bcb9c2bd8fdb8360abdb14822cb9f1d9c2352da5",
          "md5": "62e0a02e4645beafbde53fa9f5cf060f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "url": "test-utils-resourceloader-js-0fd7252-change-project-setup-SNAPSHOT.klib",
          "size": 9574,
          "sha512": "7f31ee56040e3416191e0a7033bf0b5c82def07dd3b676cdf90386a4eb8c3095988e790ec39a3063ff04fe523e100565b5a3c57781b4048c1125544bfee9f284",
          "sha256": "f0759f2cb07b2f481adbd73f3de791013f503bf40104928d497da5d70ff008bb",
          "sha1": "bcb9c2bd8fdb8360abdb14822cb9f1d9c2352da5",
          "md5": "62e0a02e4645beafbde53fa9f5cf060f"
        }
      ]
    }
  ]
}
