{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/30769ee-change-setup-SNAPSHOT/test-utils-coroutine-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT.klib",
          "size": 10251,
          "sha512": "2677ddc6bf842f9e9a0e6730316aaefeb3b29b615e177fca6f9ae76409226749de4da390e0a869bb6527438e09868552e2a1efee35ff6f97586309ec9ae2a360",
          "sha256": "b0b6961753bd92f9eb1b6d6dc9d8ee017f11bf9f49ab2c6df541de4acc5586ed",
          "sha1": "3459a407654355b2fe5ec7bba6916b60ddeb30d6",
          "md5": "e56ef68d99d3d9c8272d8e2dcba8d6b6"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "url": "test-utils-coroutine-watchossimulatorarm64-30769ee-change-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e9765b087aca8f840891345f56c718d5fe0dd684d8122fd5070da568bb545876fc9651a1111aa656924d5b8fcff6d39ee37a0484f9958f4b558910c92c23117f",
          "sha256": "38252ff8f265ca3ae2fc107540506dd092d69511a1fa51e2a6f4fac33057bbfa",
          "sha1": "739afd2807967b59a3db4b121c14d376f6655de3",
          "md5": "2bd05fa4ff1f8930b2d0a55c9019c960"
        }
      ]
    }
  ]
}
