{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "c8719de-fix-detekt-distribution",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-kmp-configuration-c8719de-fix-detekt-distribution.jar",
          "size": 12967,
          "sha512": "31ae4b30c0bba8295dae6588c8a2d75d8971eba40ecf7f5bee594ff0d46243a44890e68127f448308f9baea5a0eb835fda9ff8209987d1b0ae462d260786bec4",
          "sha256": "b720513e2d6f14e0f9210870c2f3f66e2150aabc840a8739344332ccb343e441",
          "sha1": "b32824ab1f8eac10b8c38be7335d763eb16fe44d",
          "md5": "56d6a4f1d20a45e52847270edcad5144"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "c8719de-fix-detekt-distribution"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-c8719de-fix-detekt-distribution.jar",
          "url": "antibytes-kmp-configuration-c8719de-fix-detekt-distribution.jar",
          "size": 12967,
          "sha512": "31ae4b30c0bba8295dae6588c8a2d75d8971eba40ecf7f5bee594ff0d46243a44890e68127f448308f9baea5a0eb835fda9ff8209987d1b0ae462d260786bec4",
          "sha256": "b720513e2d6f14e0f9210870c2f3f66e2150aabc840a8739344332ccb343e441",
          "sha1": "b32824ab1f8eac10b8c38be7335d763eb16fe44d",
          "md5": "56d6a4f1d20a45e52847270edcad5144"
        }
      ]
    }
  ]
}
