{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.settings",
    "module": "antibytes-dependency-settings",
    "version": "cf059d6-remove-material-python",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "cf059d6-remove-material-python"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-cf059d6-remove-material-python.jar",
          "url": "antibytes-dependency-settings-cf059d6-remove-material-python.jar",
          "size": 17194,
          "sha512": "f85a6d7fb79cbfc16d98fc47ea4a6970a2bc58e67f4330c327a30c4624942886385e1069f7de1cac4274836bd9985d553ca048b4415464f6a910c4456f0aa30a",
          "sha256": "954008078f1b81997aedf07e2f58613e957b492b08f5bf8376bb150aaba5747b",
          "sha1": "7c4a95e680245c6ee21f99e017fb5b06c2b6a229",
          "md5": "4d77c3415b19c1d354b4671029afc190"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.node",
          "module": "antibytes-dependency-node",
          "version": {
            "requires": "cf059d6-remove-material-python"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-settings-cf059d6-remove-material-python.jar",
          "url": "antibytes-dependency-settings-cf059d6-remove-material-python.jar",
          "size": 17194,
          "sha512": "f85a6d7fb79cbfc16d98fc47ea4a6970a2bc58e67f4330c327a30c4624942886385e1069f7de1cac4274836bd9985d553ca048b4415464f6a910c4456f0aa30a",
          "sha256": "954008078f1b81997aedf07e2f58613e957b492b08f5bf8376bb150aaba5747b",
          "sha1": "7c4a95e680245c6ee21f99e017fb5b06c2b6a229",
          "md5": "4d77c3415b19c1d354b4671029afc190"
        }
      ]
    }
  ]
}
