{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-add-nested-fixtures-set-SNAPSHOT/core-0.2.0-add-nested-fixtures-set-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-add-nested-fixtures-set-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-nested-fixtures-set-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-nested-fixtures-set-SNAPSHOT.klib",
          "size": 109973,
          "sha512": "3a542afaebc84b9057285dab48952962b38331a9a3a5b4493f8f3511993460eb0ade45843ba7f7aa6532fdd822a57ec3c39a08d9b1d5a6b3c384f67ebf6e4f8e",
          "sha256": "b73976ce6ffe2f570f5b563a7127305ecd136e8ae0e887e06b77b5ad6de51f88",
          "sha1": "20eb9e8b0e5bd4bd241798ca07b18c960795e95e",
          "md5": "5405f93b05aefd45d45878e4b3d59acb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.2.0-add-nested-fixtures-set-SNAPSHOT.klib",
          "url": "core-js-0.2.0-add-nested-fixtures-set-SNAPSHOT.klib",
          "size": 109973,
          "sha512": "3a542afaebc84b9057285dab48952962b38331a9a3a5b4493f8f3511993460eb0ade45843ba7f7aa6532fdd822a57ec3c39a08d9b1d5a6b3c384f67ebf6e4f8e",
          "sha256": "b73976ce6ffe2f570f5b563a7127305ecd136e8ae0e887e06b77b5ad6de51f88",
          "sha1": "20eb9e8b0e5bd4bd241798ca07b18c960795e95e",
          "md5": "5405f93b05aefd45d45878e4b3d59acb"
        }
      ]
    }
  ]
}
