{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-add-kmock-annotation-multi-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "size": 47568,
          "sha512": "c885b6fac3ae1fab69f65ab52cd48f1cd7dbb3a2abc6c8e6453d1a6b0442e38ae5456a0f3e379bd62ee3d3b4dccb0d94a35ca1a88436655e5b2df00a9b7a2e27",
          "sha256": "c29ca1b27ca55d5a4bdc6e1cea90bf7981f23f5fbb479a2abdd05ee975b5e887",
          "sha1": "88ead15ebda062158aa65c2dc7b421296794c579",
          "md5": "ac623e1415d61552015b83687d1c4b3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT.jar",
          "size": 47568,
          "sha512": "c885b6fac3ae1fab69f65ab52cd48f1cd7dbb3a2abc6c8e6453d1a6b0442e38ae5456a0f3e379bd62ee3d3b4dccb0d94a35ca1a88436655e5b2df00a9b7a2e27",
          "sha256": "c29ca1b27ca55d5a4bdc6e1cea90bf7981f23f5fbb479a2abdd05ee975b5e887",
          "sha1": "88ead15ebda062158aa65c2dc7b421296794c579",
          "md5": "ac623e1415d61552015b83687d1c4b3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "20c2848ad66a88a912fddb77970b75ba36ea502d71e9edab11e319ddd5eef568350a9b955fbebbb82cf749fe96234de4e538e3d272713dcc04bb26bbea8ecec1",
          "sha256": "7cc60f3e1453c0f2e2a2ec64a4d9d280a5acd18ea10c25cf9ee681d4237eccd4",
          "sha1": "b2b878cc817ce1cdda816ca29d4edb9b5a7fa8c8",
          "md5": "04e78c195793ffb2df0b7a51d6213e8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-add-kmock-annotation-multi-SNAPSHOT-sources.jar",
          "size": 10934,
          "sha512": "19a9a430848eadf639c4837d3d747395258325e29b49ee18b3b26470c162e8676e6bf29a4adbfcec96820b11c74ef8f06b9ffc4dba2f4fa3d3b030bb0ff26246",
          "sha256": "419218a503e061c92db4640f7e24739f10c82517207e2a2945d68cd581006a8c",
          "sha1": "6c576346f0634f926a2a4721939b107b8c1fae67",
          "md5": "17805384dbec7abff72c0434730449c0"
        }
      ]
    }
  ]
}
