{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/30769ee-change-setup-SNAPSHOT/test-utils-annotations-junit5-30769ee-change-setup-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "30769ee-change-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "e60d2335819857711427ef2bc7b942be43593c49fb40fe2a1f17ad76dbf5bd0767a704fb05700adefc630d568d174e3f1e321679718c0ce8a251e8defeb00e08",
          "sha256": "53a79c81863236dab79acbf66f398f508128d882403cc7fd9b3ce7e404781eea",
          "sha1": "d7ecb34a39fb6757cf2b01f209681bbc4930469f",
          "md5": "057007e64e1f1757da8adea272913fa9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "url": "test-utils-annotations-junit5-jvm-30769ee-change-setup-SNAPSHOT.jar",
          "size": 4271,
          "sha512": "e60d2335819857711427ef2bc7b942be43593c49fb40fe2a1f17ad76dbf5bd0767a704fb05700adefc630d568d174e3f1e321679718c0ce8a251e8defeb00e08",
          "sha256": "53a79c81863236dab79acbf66f398f508128d882403cc7fd9b3ce7e404781eea",
          "sha1": "d7ecb34a39fb6757cf2b01f209681bbc4930469f",
          "md5": "057007e64e1f1757da8adea272913fa9"
        }
      ]
    }
  ]
}
