{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203034,
          "sha512": "39f9da6ab9c1fc60e547122986e11480d2cf0cbbfaa6af925081b262f033d38d3ad627e3a7eefb00b2ff9544f45258299533cf8de825a58ee0cb3d8e3c415af4",
          "sha256": "f816f7575fb25b7e71d67d7ea0b547b525a7c6b922e213efd2873f7fb0a1ee89",
          "sha1": "d5c43cff8e8614748f56828731aac6142648d5e3",
          "md5": "1ca07b1f1f2874413551bc09e194acb2"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c65f9a8140161b80700970eb4d61cfe96e8ad50edb1c8911ae7a858cee15b24de709d9b39b4380eda81df285661f534eef21fd6c485e5c97cb949b8e51f252c9",
          "sha256": "2b9f810201a78acf8293e981cc317bb1c584a14803235611be565e12b4187e5c",
          "sha1": "e76e492b255de85d40af9b6ce49b2b2fb91ffba6",
          "md5": "2abd1d462e5cc4c6926fb927715da60e"
        }
      ]
    }
  ]
}
