{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc07-SNAPSHOT/kmock-0.3.0-rc07-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc07-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock.klib",
          "url": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT.klib",
          "size": 203034,
          "sha512": "39f9da6ab9c1fc60e547122986e11480d2cf0cbbfaa6af925081b262f033d38d3ad627e3a7eefb00b2ff9544f45258299533cf8de825a58ee0cb3d8e3c415af4",
          "sha256": "f816f7575fb25b7e71d67d7ea0b547b525a7c6b922e213efd2873f7fb0a1ee89",
          "sha1": "d5c43cff8e8614748f56828731aac6142648d5e3",
          "md5": "1ca07b1f1f2874413551bc09e194acb2"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "url": "kmock-watchosx64-0.3.0-rc07-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "d287b6a3ed43212de7ef072b7c42bfdd1373cf577efe1030bc1c16ea9534a19611deb02798bbd1636f0415b58e15bbe33f95d5aa83e1e6e2df1877a5ce396fa1",
          "sha256": "ba803ef8ad3a553ddb35b9cd8818297bca9d97c09302235ee818879720118dbf",
          "sha1": "7155aa9b8b6d3a623096a47626280fc21f9e8219",
          "md5": "2816fe58c5a45693e1731887220b413b"
        }
      ]
    }
  ]
}
