{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-remove-android-studio-workaround-SNAPSHOT/core-0.4.0-remove-android-studio-workaround-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-remove-android-studio-workaround-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-macosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "d8a2a3dfb5cce07ba44fa9b2a1b621e2b70ba426660ae4412cb3689f772bcbed18f96cc75c67e8edbead46fd3b24b8b64bca5aeab7abc1f883d8895d89759bb2",
          "sha256": "0a357788587658b0d90ab68d3d288700d74f84a8fae96858bd3f9c03f866eca1",
          "sha1": "bb238872439afdd4ba880cb8cf70c046ea4cae3a",
          "md5": "1c34d6f420c2024e1f48c9db6acccbfa"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-macosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "url": "core-macosx64-0.4.0-remove-android-studio-workaround-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6c5b57dd420b69ee76fda21fbd14dafb240bde8da253dd2269381bba05a5d49aea9aa06dbeee344543c5549e758b268a679409eac6c58eb4e826bee43dcb0c88",
          "sha256": "653e86733ed19c5d5148eaab4b7202fdeb7abbcee7f9fd4f31d4ade98b7c4f57",
          "sha1": "29c4c561dc9771918ff057cfafce4112fbfab6b5",
          "md5": "4073caf90111952852ca40b21a876a97"
        }
      ]
    }
  ]
}
