{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "43475c3-change-native-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-43475c3-change-native-hooks.jar",
          "url": "antibytes-quality-43475c3-change-native-hooks.jar",
          "size": 62644,
          "sha512": "c81b4aeafb325165ffd572f51f57760bccdfbf0a1dd586f3b9699808ed5bfeb4137e3788443c67dd0cca2be2dbb5e040c197a18d5c5bb4fe7aff5cb41d353d43",
          "sha256": "4deda1019f2a00fe1f6234b4ebd5722e773c27465b850fa876f4182f9fa9c569",
          "sha1": "e352e79e0d7231e0a695cd4cf16d2a3e1c8a8cfe",
          "md5": "e8d95b70be1ddc27dbf293a0ec0f029a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.22.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "43475c3-change-native-hooks"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "43475c3-change-native-hooks"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-43475c3-change-native-hooks.jar",
          "url": "antibytes-quality-43475c3-change-native-hooks.jar",
          "size": 62644,
          "sha512": "c81b4aeafb325165ffd572f51f57760bccdfbf0a1dd586f3b9699808ed5bfeb4137e3788443c67dd0cca2be2dbb5e040c197a18d5c5bb4fe7aff5cb41d353d43",
          "sha256": "4deda1019f2a00fe1f6234b4ebd5722e773c27465b850fa876f4182f9fa9c569",
          "sha1": "e352e79e0d7231e0a695cd4cf16d2a3e1c8a8cfe",
          "md5": "e8d95b70be1ddc27dbf293a0ec0f029a"
        }
      ]
    }
  ]
}
