{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/2025aef-add-more-sources-SNAPSHOT/test-utils-resourceloader-2025aef-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "2025aef-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-watchosarm32-2025aef-add-more-sources-SNAPSHOT.klib",
          "size": 12901,
          "sha512": "9e7057ecaac4fea2fe9d85dd1ff6776e802bda9e94b578789cf3a99b525fd6b7f834462e1e8001001b5caeeaae5ff2a3d6cf86d3cf9814804192e130ea37362e",
          "sha256": "dd605996b7df2809cfc73e85d3999f50704d50db6bcf57556d2f2730e0c230d4",
          "sha1": "8a3bd70ee9375656d666dae27bbb83164fa88f2c",
          "md5": "1fb291d1f457a9eab223ef76b5147cb6"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-watchosarm32-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-resourceloader-watchosarm32-2025aef-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "25697674756d479602a11846fd5b63e636fe9616e5103a7eda0fe5e7b890ee6c388abda777d18da8d286fdbf7936648918d85580e903a2ecf86eaeac4919cad4",
          "sha256": "1644fa992f864a0a83b8faa4859e850a4d4c7ad365182dd84ecfb3e86a9be9e7",
          "sha1": "69d15a95d187b6ecf54df2ad2f1a2638072ed24b",
          "md5": "bc8a9afc6bae690a4d4ee99e4843864a"
        }
      ]
    }
  ]
}
