{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "18ec2bf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-18ec2bf.jar",
          "url": "antibytes-dependency-18ec2bf.jar",
          "size": 31361,
          "sha512": "95283adfe3ab94c44c9c138935f52225a7f0fe11bf12b166c06aa8a276bf857a3eb1a096a460262daf2cb035df07b30a617cbb66dba93658135aa743881cd3aa",
          "sha256": "350c54557320add7a0f31eef7132101fcf5be2f3520c41d19eb7b3ca53c04f65",
          "sha1": "f13f6b58bf7788e8a51b58784f1f98b0e14a92ce",
          "md5": "59083ab80c7bc0fb00895d6af0f66045"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-18ec2bf.jar",
          "url": "antibytes-dependency-18ec2bf.jar",
          "size": 31361,
          "sha512": "95283adfe3ab94c44c9c138935f52225a7f0fe11bf12b166c06aa8a276bf857a3eb1a096a460262daf2cb035df07b30a617cbb66dba93658135aa743881cd3aa",
          "sha256": "350c54557320add7a0f31eef7132101fcf5be2f3520c41d19eb7b3ca53c04f65",
          "sha1": "f13f6b58bf7788e8a51b58784f1f98b0e14a92ce",
          "md5": "59083ab80c7bc0fb00895d6af0f66045"
        }
      ]
    }
  ]
}
