{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/9cb77b2-bump-updates-SNAPSHOT/test-utils-coroutine-9cb77b2-bump-updates-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9cb77b2-bump-updates-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm.jar",
          "url": "test-utils-coroutine-jvm-9cb77b2-bump-updates-SNAPSHOT.jar",
          "size": 10822,
          "sha512": "4c412f20e92557f9ad718d8c37229a254c8270dccae75f42018b792be71d730924772e40e5c5c2ccc8c48a60edfab270dbe31d5b1a0201944b2fa895028f444b",
          "sha256": "e0465dfcd365be1bc0c28b02c57ef8f3826d8a0afbbf48634a1c07bd68d844ee",
          "sha1": "95bfd014e7def5f94460a59c125975f56ea960b3",
          "md5": "968bf0c5ea66a54a618342d7ad1f74da"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm.jar",
          "url": "test-utils-coroutine-jvm-9cb77b2-bump-updates-SNAPSHOT.jar",
          "size": 10822,
          "sha512": "4c412f20e92557f9ad718d8c37229a254c8270dccae75f42018b792be71d730924772e40e5c5c2ccc8c48a60edfab270dbe31d5b1a0201944b2fa895028f444b",
          "sha256": "e0465dfcd365be1bc0c28b02c57ef8f3826d8a0afbbf48634a1c07bd68d844ee",
          "sha1": "95bfd014e7def5f94460a59c125975f56ea960b3",
          "md5": "968bf0c5ea66a54a618342d7ad1f74da"
        }
      ]
    }
  ]
}
