{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/1c43298-bump-danger-SNAPSHOT/test-utils-ktor-1c43298-bump-danger-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "1c43298-bump-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-1c43298-bump-danger-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-1c43298-bump-danger-SNAPSHOT.klib",
          "size": 12119,
          "sha512": "580f682f438538aee9b1175b870f6a8afe040799bfda78a1ec2383b4961a3f0ae9eb99e9863be61185486374991c0fa9fb676204777dcb8de8a184fddb4b7579",
          "sha256": "10dbb432e17b775e48df38a93552ad9706fde2c8c0401c5fe5767e05188142e8",
          "sha1": "c4dbe7f13e81e90327ee76b9d4bde322189477a1",
          "md5": "57ae4e9d039e9d963554ab5e394395ae"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-1c43298-bump-danger-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-1c43298-bump-danger-SNAPSHOT.klib",
          "size": 12119,
          "sha512": "580f682f438538aee9b1175b870f6a8afe040799bfda78a1ec2383b4961a3f0ae9eb99e9863be61185486374991c0fa9fb676204777dcb8de8a184fddb4b7579",
          "sha256": "10dbb432e17b775e48df38a93552ad9706fde2c8c0401c5fe5767e05188142e8",
          "sha1": "c4dbe7f13e81e90327ee76b9d4bde322189477a1",
          "md5": "57ae4e9d039e9d963554ab5e394395ae"
        }
      ]
    }
  ]
}
