{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-custom-component",
    "version": "221cf2d-change-settings-plugin",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-221cf2d-change-settings-plugin.jar",
          "url": "antibytes-custom-component-221cf2d-change-settings-plugin.jar",
          "size": 16176,
          "sha512": "195b2f47609d440c0c7489dbb55df61ce7e8f4acc688f1abc237ef3b1b88195d1bbece8e4699b3aeb5b8c2ac84259355ac2fb8c844be3d1ccdbecb46104b90b4",
          "sha256": "adc2363b6e52dd942b67245f99374412548942b0aa6700a71a3cd8912f87718a",
          "sha1": "ac7a056c25b42ef2b5cbf4835883fc00400b36cf",
          "md5": "0ad6b382e87a35ac86e955a75a675e20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-221cf2d-change-settings-plugin.jar",
          "url": "antibytes-custom-component-221cf2d-change-settings-plugin.jar",
          "size": 16176,
          "sha512": "195b2f47609d440c0c7489dbb55df61ce7e8f4acc688f1abc237ef3b1b88195d1bbece8e4699b3aeb5b8c2ac84259355ac2fb8c844be3d1ccdbecb46104b90b4",
          "sha256": "adc2363b6e52dd942b67245f99374412548942b0aa6700a71a3cd8912f87718a",
          "sha1": "ac7a056c25b42ef2b5cbf4835883fc00400b36cf",
          "md5": "0ad6b382e87a35ac86e955a75a675e20"
        }
      ]
    }
  ]
}
