{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.publishing",
    "module": "antibytes-publishing",
    "version": "1c69a2f-change-android-compile-task",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1c69a2f-change-android-compile-task"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-publishing-1c69a2f-change-android-compile-task.jar",
          "size": 130775,
          "sha512": "65fa8c9bc46f6f13fdb815cdef842f8e512a4ec35891baccacd49b5c808b11f6a1db04a0b7b21cc722c07e07c822f817a68de35ca69e45e448b95b311266a8bd",
          "sha256": "96d7f89f7144b68feecd02d9ce0d846c7b2ed320f1d8eb660fd834bc6435dfda",
          "sha1": "5055ca1ce37966d774c3e168059d8bb2a38ef274",
          "md5": "9bc23632a26a327da0af63dc858245f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "1c69a2f-change-android-compile-task"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "1c69a2f-change-android-compile-task"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-1c69a2f-change-android-compile-task.jar",
          "url": "antibytes-publishing-1c69a2f-change-android-compile-task.jar",
          "size": 130775,
          "sha512": "65fa8c9bc46f6f13fdb815cdef842f8e512a4ec35891baccacd49b5c808b11f6a1db04a0b7b21cc722c07e07c822f817a68de35ca69e45e448b95b311266a8bd",
          "sha256": "96d7f89f7144b68feecd02d9ce0d846c7b2ed320f1d8eb660fd834bc6435dfda",
          "sha1": "5055ca1ce37966d774c3e168059d8bb2a38ef274",
          "md5": "9bc23632a26a327da0af63dc858245f4"
        }
      ]
    }
  ]
}
