{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "5828445",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-5828445.jar",
          "url": "antibytes-grammar-tools-5828445.jar",
          "size": 39410,
          "sha512": "7c3344e6582ede13acae9b5645882c5f426b6f481aaee53986237b4a6544aedff8510faf63e9a1a4348e452714ffc88749ab1a849e9bc6ef4432f6d06197c810",
          "sha256": "e7d7a0cf638555a268aebcb12341fba568f392c1fc63243279d3ac0f7a700417",
          "sha1": "0df9f9ba164f393621f93efcc31ad268dce4b1fd",
          "md5": "429fd3c6fa5f999f1b59b98f47810355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-5828445.jar",
          "url": "antibytes-grammar-tools-5828445.jar",
          "size": 39410,
          "sha512": "7c3344e6582ede13acae9b5645882c5f426b6f481aaee53986237b4a6544aedff8510faf63e9a1a4348e452714ffc88749ab1a849e9bc6ef4432f6d06197c810",
          "sha256": "e7d7a0cf638555a268aebcb12341fba568f392c1fc63243279d3ac0f7a700417",
          "sha1": "0df9f9ba164f393621f93efcc31ad268dce4b1fd",
          "md5": "429fd3c6fa5f999f1b59b98f47810355"
        }
      ]
    }
  ]
}
