{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/13f09a8-add-more-sources-SNAPSHOT/test-utils-annotations-junit5-13f09a8-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "13f09a8-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT.klib",
          "size": 7135,
          "sha512": "11d345fc64f6e9dec68c63102b2576443704c52100e65b33faaf3b8b08337be245f194456ea51e65cfabe34feef1add181af829ce7885a7977d5d41005286531",
          "sha256": "7aad63ef12408ddf057d9a90d3cd85bbde21ba77747fb5fd197ec32db68a5fd7",
          "sha1": "795460f85c22927d3586a3b92de139e140806fa2",
          "md5": "a422756344bc796618ae9c6a89dd1ed7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iossimulatorarm64-13f09a8-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e139d4c315d5178a5b2a6573d0bbb8c00c4cfe11374c4c03df39a55273e352d4548d08b616e61c1c9bd144fd9e6fac9e172bf1538a8be2e4953d24b441bb9ed4",
          "sha256": "7d3564fde99673e5551be9fe7b3411ed2ec7e5f74a3a468256d6a237fb891ec8",
          "sha1": "588d847a177c1081e43e5bdf01c68342431c866d",
          "md5": "84b8a1b682b1f2391574a86e5fbe38f0"
        }
      ]
    }
  ]
}
