{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-gradle-test-utils",
    "version": "2d8d343-add-plattform-hooks",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d8d343-add-plattform-hooks.jar",
          "url": "antibytes-gradle-test-utils-2d8d343-add-plattform-hooks.jar",
          "size": 17243,
          "sha512": "46ea79065c4d8b09b9aebcdf9215de9efcfd0e45c37cf1dfa51d5084ef17a57dc8b888d9d1b9da1a48b45de92aa1ae3842343ed863592e09a4d63c2c9fa97161",
          "sha256": "4942b0baf8b60f4ea6cb0f2c23f2b30049d57b5e563fb4156882d8003de053d5",
          "sha1": "c69a1c5d6d811402c5a6d76dfda266d638487686",
          "md5": "33e8abe4b0d6e0e372ba42a252d967e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.8"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-test-utils-2d8d343-add-plattform-hooks.jar",
          "url": "antibytes-gradle-test-utils-2d8d343-add-plattform-hooks.jar",
          "size": 17243,
          "sha512": "46ea79065c4d8b09b9aebcdf9215de9efcfd0e45c37cf1dfa51d5084ef17a57dc8b888d9d1b9da1a48b45de92aa1ae3842343ed863592e09a4d63c2c9fa97161",
          "sha256": "4942b0baf8b60f4ea6cb0f2c23f2b30049d57b5e563fb4156882d8003de053d5",
          "sha1": "c69a1c5d6d811402c5a6d76dfda266d638487686",
          "md5": "33e8abe4b0d6e0e372ba42a252d967e7"
        }
      ]
    }
  ]
}
