{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "11b98fb-change-spying-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-11b98fb-change-spying-SNAPSHOT.jar",
          "url": "kmock-gradle-11b98fb-change-spying-SNAPSHOT.jar",
          "size": 49814,
          "sha512": "dfb13f99fe83ea5c59b0038e7aff2a1bc35c4131cde4d0cf7e8b9a1cfaf5a964c5c555253728d742af405bb55bc926a905efa9f7847a3dcb52d413f877c2419f",
          "sha256": "b4ad44ebbb3ec838c89894d2440df60019d6f8e2466c8def7b5a5b9cb3c0acda",
          "sha1": "5b848493e3b265265cf15d48756648a6c403deec",
          "md5": "9cfc1b229d994a3910e8f6274fb5e3a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-11b98fb-change-spying-SNAPSHOT.jar",
          "url": "kmock-gradle-11b98fb-change-spying-SNAPSHOT.jar",
          "size": 49814,
          "sha512": "dfb13f99fe83ea5c59b0038e7aff2a1bc35c4131cde4d0cf7e8b9a1cfaf5a964c5c555253728d742af405bb55bc926a905efa9f7847a3dcb52d413f877c2419f",
          "sha256": "b4ad44ebbb3ec838c89894d2440df60019d6f8e2466c8def7b5a5b9cb3c0acda",
          "sha1": "5b848493e3b265265cf15d48756648a6c403deec",
          "md5": "9cfc1b229d994a3910e8f6274fb5e3a6"
        }
      ]
    }
  ]
}
