{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-stable-snapshots-SNAPSHOT/kmock-0.1.1-add-stable-snapshots-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-stable-snapshots-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-stable-snapshots-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-stable-snapshots-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "92f360aa195ac52d93bb219afc88ae1a1ed931c06ed762f59dc8e2b916a7bf286823c1d355a0e787f02a659772274858523e399202a41326da4d69f49d4573d9",
          "sha256": "902342d3d0012fad0707e62c870e9a17bee8f3b597b1a1acd89e5870eec0f1cc",
          "sha1": "0dd7b746fd76e96a8c4436a5261fda133a9aa8ad",
          "md5": "a31007dba4862b5e49dd858f5f0eed6e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.1.1-add-stable-snapshots-SNAPSHOT.klib",
          "url": "kmock-js-0.1.1-add-stable-snapshots-SNAPSHOT.klib",
          "size": 167081,
          "sha512": "92f360aa195ac52d93bb219afc88ae1a1ed931c06ed762f59dc8e2b916a7bf286823c1d355a0e787f02a659772274858523e399202a41326da4d69f49d4573d9",
          "sha256": "902342d3d0012fad0707e62c870e9a17bee8f3b597b1a1acd89e5870eec0f1cc",
          "sha1": "0dd7b746fd76e96a8c4436a5261fda133a9aa8ad",
          "md5": "a31007dba4862b5e49dd858f5f0eed6e"
        }
      ]
    }
  ]
}
