{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/4588171-add-array-generators-SNAPSHOT/fixture-4588171-add-array-generators-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "4588171-add-array-generators-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fixture-jvm-4588171-add-array-generators-SNAPSHOT.jar",
          "url": "fixture-jvm-4588171-add-array-generators-SNAPSHOT.jar",
          "size": 107955,
          "sha512": "6dd9f5ef8724fadb32b8b7919e9e5180139d8ac6f945566777e8dbbae3d08dfe4b2a05f789ff4a3b4e468555be83716da85773ae3197362fb1e0e520a55f0236",
          "sha256": "75c7ebe4231f18594293d5def59ca144b1cc9dd97c02fed0be1026b4420510ca",
          "sha1": "389097074d9e9c1d74ecf20d0b337c6067dc5f80",
          "md5": "a17c258cf7f4d3bf89d6d024c4f72c1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-jvm-4588171-add-array-generators-SNAPSHOT.jar",
          "url": "fixture-jvm-4588171-add-array-generators-SNAPSHOT.jar",
          "size": 107955,
          "sha512": "6dd9f5ef8724fadb32b8b7919e9e5180139d8ac6f945566777e8dbbae3d08dfe4b2a05f789ff4a3b4e468555be83716da85773ae3197362fb1e0e520a55f0236",
          "sha256": "75c7ebe4231f18594293d5def59ca144b1cc9dd97c02fed0be1026b4420510ca",
          "sha1": "389097074d9e9c1d74ecf20d0b337c6067dc5f80",
          "md5": "a17c258cf7f4d3bf89d6d024c4f72c1f"
        }
      ]
    }
  ]
}
