{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "d75bc0f-change-coroutines-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-metadata-d75bc0f-change-coroutines-SNAPSHOT-all.jar",
          "url": "test-utils-annotations-d75bc0f-change-coroutines-SNAPSHOT-all.jar",
          "size": 10390,
          "sha512": "09a775d41269e963d4d42df13ae79494e59c5ebf85e6b0bfbacecf00b5b09f5fda72890e09725e1c671743ce5994c55f81853990eb57d057f4c6c6f310d13bce",
          "sha256": "640d73cc3a9308a66ae38c31924b1b6374a581b6eec7af5c8748219e2223f73a",
          "sha1": "5ced3335080538d1dda19b4771a44314bf5c8221",
          "md5": "db06ac0aae10c3f5b89474cf1db236f5"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-annotations-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "url": "test-utils-annotations-d75bc0f-change-coroutines-SNAPSHOT.jar",
          "size": 7367,
          "sha512": "3360b2c4a812fd0c95897ca4d4f64d6e4ba0b3d0a8e5370d7104ca56ad1cb03d8591f635174d825876154cf5df2bbff93bf4eabde7966a3e8ad94e6b93119222",
          "sha256": "3a398afd4b53b7d5e2d5cb333448e90b2b7702bc3750c2916fb8398c1524b81f",
          "sha1": "0008edc21d86c6a887b3fe74512620203be9d501",
          "md5": "f2c2fb1ed8287c293af15322b0caa386"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-android-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-android/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-android-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-android",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iosarm64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosarm64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iosarm64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosarm64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iossimulatorarm64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iossimulatorarm64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iossimulatorarm64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iossimulatorarm64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iossimulatorarm64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iossimulatorarm64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iosx64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-iosx64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-iosx64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-iosx64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-annotations-js/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-js-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-js",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-jvm-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-annotations-jvm/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-jvm-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-jvm",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-annotations-linuxx64/d75bc0f-change-coroutines-SNAPSHOT/test-utils-annotations-linuxx64-d75bc0f-change-coroutines-SNAPSHOT.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-annotations-linuxx64",
        "version": "d75bc0f-change-coroutines-SNAPSHOT"
      }
    }
  ]
}
