{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-bump-setup-SNAPSHOT/core-0.4.0-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-watchosarm32-0.4.0-bump-setup-SNAPSHOT.klib",
          "size": 105871,
          "sha512": "15f433215238fd539763e12c39180ba6d4467558426b2ec74efd46538eac53aaa2119c4dc7f532f6d67c40c587b8ca233303955a58b57b97ceffbd972d46905b",
          "sha256": "7bb24ab9548c98329cb067d45919be5b024b4d2bcc27c1963e6170be77237746",
          "sha1": "e4ba4d4b9033c5635955248aa46ca1ef9ca7c0fb",
          "md5": "88176f7c5deaa4609744a2c8e1a4ef20"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "url": "core-watchosarm32-0.4.0-bump-setup-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "320bde67be192dba9d24e8b4d45293bfdaa636eadfebd8c4bf5eceaccd2a81475bd6c9f420075bb97f63cd7c693e454bac3cce91d080864f5623f112654928de",
          "sha256": "5687c8f60e58aede8ba30907044c284219ced9994de8d78d4c73120d1b7b9492",
          "sha1": "17618080e44f26b371e5a2faa0cbbe023a18077d",
          "md5": "c0ec764ffd5694313ef2fbcd72ee98c8"
        }
      ]
    }
  ]
}
