{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "12ea545-fix-python-dependencies",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-custom-component-12ea545-fix-python-dependencies.jar",
          "size": 16172,
          "sha512": "a44e76b74e6e5411e8e77bd3dc0d7988162879b80b79aaba030a7c6f92950668166baf1bcd02a05f783bec4734173853d726f95e3a88e309f2f8fc5f49693cf3",
          "sha256": "c1c2b94e9aa91e1888963306c9bbed5d68d338a6b2e3f5dbbdc533097f28acd9",
          "sha1": "d209d92a4c308b5d2d67f2d46dab78c3af39ce8a",
          "md5": "2afb278abba36cada236b7ad045ccdd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-12ea545-fix-python-dependencies.jar",
          "url": "antibytes-custom-component-12ea545-fix-python-dependencies.jar",
          "size": 16172,
          "sha512": "a44e76b74e6e5411e8e77bd3dc0d7988162879b80b79aaba030a7c6f92950668166baf1bcd02a05f783bec4734173853d726f95e3a88e309f2f8fc5f49693cf3",
          "sha256": "c1c2b94e9aa91e1888963306c9bbed5d68d338a6b2e3f5dbbdc533097f28acd9",
          "sha1": "d209d92a4c308b5d2d67f2d46dab78c3af39ce8a",
          "md5": "2afb278abba36cada236b7ad045ccdd6"
        }
      ]
    }
  ]
}
