{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-fixture/b8215f8-add-ios-SNAPSHOT/test-utils-fixture-b8215f8-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-fixture",
    "version": "b8215f8-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture.klib",
          "url": "test-utils-fixture-iosx64-b8215f8-add-ios-SNAPSHOT.klib",
          "size": 31111,
          "sha512": "df6ff8cafd4f358f35f9b3134108ad74618620e4df33a7232890f075992e67538bd228574047eaf2d6a7c8d7ed2391988bc0b63b3a0f3a124601bb963a0d4ecb",
          "sha256": "70f16333efe33648f8f1fdbb0cd83227ca94c3ecf4f202d5cfd60b3c90fa3581",
          "sha1": "fdb657524b9d339cf85781f534f062679816fa80",
          "md5": "f2c442369ce0e0aa01f6b7977fc5c323"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-fixture-iosx64-b8215f8-add-ios-SNAPSHOT-metadata.jar",
          "url": "test-utils-fixture-iosx64-b8215f8-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0ba1c31a3b27e2ed50537677f01adb5d2098881d9f78ecad78ce88690f113cb6285807e55d89bec1bdc2f30b7ef5da1aefd2563248eb4ffd61cf0ce80c27d91d",
          "sha256": "bdbeead9ccb8bae2b503dc20ec51f7988e542c1800b0501009f6e8df97026565",
          "sha1": "ccde294c36a65dbc1144df145d1f6d2e4dfada67",
          "md5": "18aef5632f7b33ecc45da342228cb857"
        }
      ]
    }
  ]
}
