{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "a920e4b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-a920e4b.jar",
          "url": "antibytes-coverage-a920e4b.jar",
          "size": 118691,
          "sha512": "241923f87fdfe403edee476f747826c8bca922db94a2310d52a4887aa9e2eb968873af65f90c404357b13b2230e14eadd6c8ed019b5e339b2e0b12de062521ac",
          "sha256": "18ef31124313cbf83b6848ec33cc81fcda961f06136cc56c04c5b2aad537f259",
          "sha1": "6e170eaf5a2ceb3370771695cb022f9b88f986b8",
          "md5": "47ce7a9051916e9b1aeb64edf5626779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-a920e4b.jar",
          "url": "antibytes-coverage-a920e4b.jar",
          "size": 118691,
          "sha512": "241923f87fdfe403edee476f747826c8bca922db94a2310d52a4887aa9e2eb968873af65f90c404357b13b2230e14eadd6c8ed019b5e339b2e0b12de062521ac",
          "sha256": "18ef31124313cbf83b6848ec33cc81fcda961f06136cc56c04c5b2aad537f259",
          "sha1": "6e170eaf5a2ceb3370771695cb022f9b88f986b8",
          "md5": "47ce7a9051916e9b1aeb64edf5626779"
        }
      ]
    }
  ]
}
