{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "0.3.0-rc01-change-android-source-distribution-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "3de9ff5ef8c871af9a2cfb3e98b101026ecc568509ccc6955cfdc1e4badf55ae0ad2e7fb2e397d4e4262ee1dbe4aca367aee49c984a280aea788953cdb18a715",
          "sha256": "3d5785c06003937608f62845a0fbb6ba2e100a5e7f25e7364ee1b38b900542a5",
          "sha1": "f174d88378f851c02308e6aa12a013f6dfbd6cc6",
          "md5": "ccc714ba0c88114b0b4fa96ed61fe925"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "0.3.0-rc01-change-android-source-distribution-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.jar",
          "url": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT.jar",
          "size": 384124,
          "sha512": "3de9ff5ef8c871af9a2cfb3e98b101026ecc568509ccc6955cfdc1e4badf55ae0ad2e7fb2e397d4e4262ee1dbe4aca367aee49c984a280aea788953cdb18a715",
          "sha256": "3d5785c06003937608f62845a0fbb6ba2e100a5e7f25e7364ee1b38b900542a5",
          "sha1": "f174d88378f851c02308e6aa12a013f6dfbd6cc6",
          "md5": "ccc714ba0c88114b0b4fa96ed61fe925"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-javadoc.jar",
          "url": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "ec6d6dffe0d9694359fcc87c5668a5bc59506bb0490a3973064be409d09d41b37aaa80afed9e3a4da9e0cea110e8c741325eebac4df5d0aadd9f1d95638c5384",
          "sha256": "7828b9009a4ff4f8a0ce18764d1726e3de59bf29aa953fe9506be33aaebdc986",
          "sha1": "caf381b8f25a952df6a14078f027902ecc1dcc58",
          "md5": "a74498bb802b0ecf3782e354063e35dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-sources.jar",
          "url": "kmock-processor-0.3.0-rc01-change-android-source-distribution-SNAPSHOT-sources.jar",
          "size": 80445,
          "sha512": "4fda99b9dd3fd6074378261b442a742fa9353110a85661554ff5c9384f022d5a286b43191d8adcf4bcf719e4d6ef392cc6e8544f27295dfd7ccde9baa37dd6be",
          "sha256": "1e9bed8033f395b1e841a0592f012372ab9580fdc9f21c88f4e122ad46bde8fa",
          "sha1": "c40e8d579dba963489ed1ebbb21976328a252c8f",
          "md5": "1d8ad683f8cfb1622a946ba22977db2e"
        }
      ]
    }
  ]
}
