{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fixture/4588171-add-array-generators-SNAPSHOT/fixture-4588171-add-array-generators-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "fixture",
    "version": "4588171-add-array-generators-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture.klib",
          "url": "fixture-iosx64-4588171-add-array-generators-SNAPSHOT.klib",
          "size": 38535,
          "sha512": "e0ea9dfd944fe4c730c9bc39441fb2f14151d3d1388c187826ecc5bac0f81568b10c7eee3268e646f150f268dcc4f94fcc78a68b5933b8d06c5894df679c6918",
          "sha256": "d20c14d0eef8c44199f75949bbf321cec65a294b5e723785e439cee8f3fceac7",
          "sha1": "924d7b24b80f7aaff4eae8b048429e0ae0356a2c",
          "md5": "c2a6a3906c913b6e660cad4801afc550"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "fixture-iosx64-4588171-add-array-generators-SNAPSHOT-metadata.jar",
          "url": "fixture-iosx64-4588171-add-array-generators-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "058fe84b51c6a5e1f44f884c75d32b5724a6bb7d802cdd6e0d0a95d5ff9c96aaffd8f2e6f90efa237a8fad96079371d8311f592dbb92238f1e0bd07139568c8b",
          "sha256": "6f9a107fd0b4c3bb16484bd95f8470fd3ab5007ba0346402b1f98afb617f19fb",
          "sha1": "e6f542eb169d82b5eef256a9247e8c252cf9dfc2",
          "md5": "ef0be88381a274a51c85cf10c3bbdf6f"
        }
      ]
    }
  ]
}
