{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/ebcd7e9-bump-antibytes-SNAPSHOT/test-utils-ebcd7e9-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "ebcd7e9-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "size": 14297,
          "sha512": "b2a60f82d7d49e65182861281bac176425ea6cd314ea6d5734aaa89001fae3876106ae1b1d3fa36318b1cd60a2139736611e4bb12fecab89bdf692cdb8b541a5",
          "sha256": "c8d56e34fbef56e6e988e17cf2efe0223f8ab9966497b527415b25eb7924e0f3",
          "sha1": "71413c7535c784cd5c63450f6a50c7832aee5809",
          "md5": "53dbe616f8bc3fdb80fb577fac10a62c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-ebcd7e9-bump-antibytes-SNAPSHOT-metadata.jar",
          "url": "test-utils-iosx64-ebcd7e9-bump-antibytes-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "3b22f5dd11efef144979f9f54080e456b04a9eddef7cd7e8afc593f76d172cc1a40784465cac4f9aa5ab64b839dce864dfc0d76311ef4fd4be4003cb075812f5",
          "sha256": "6144695d880ae6a09ce5a166285de099689467d89e591a79a3022e187a5b7df7",
          "sha1": "f2db26ad8456b5a929849a9bc53c46bdc0c144c6",
          "md5": "73c49d31b92144365d9e17b7593a41eb"
        }
      ]
    }
  ]
}
