{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-coverage",
    "version": "3180b14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-coverage-3180b14.jar",
          "url": "antibytes-coverage-3180b14.jar",
          "size": 133706,
          "sha512": "4f8c07c457a03a78b92b53b640dc30d8e94ef5c74405d9ad3b479933af7ff55f26ae3a72baa4aafaa6d221013b1e0884f7fd50274292f5e3c0a36b3d2696fef3",
          "sha256": "4f9578be6e487c4bc46b1cadf9a6d9a180c2a7ffafe8f44a22f6a82d61235f75",
          "sha1": "a64ecc157388c22dcf6d2ab9866b40dc978fa675",
          "md5": "5e241f7171f5c9e9a7e7c4ca53a47048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jacoco",
          "module": "org.jacoco.core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "3180b14"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-coverage-3180b14.jar",
          "url": "antibytes-coverage-3180b14.jar",
          "size": 133706,
          "sha512": "4f8c07c457a03a78b92b53b640dc30d8e94ef5c74405d9ad3b479933af7ff55f26ae3a72baa4aafaa6d221013b1e0884f7fd50274292f5e3c0a36b3d2696fef3",
          "sha256": "4f9578be6e487c4bc46b1cadf9a6d9a180c2a7ffafe8f44a22f6a82d61235f75",
          "sha1": "a64ecc157388c22dcf6d2ab9866b40dc978fa675",
          "md5": "5e241f7171f5c9e9a7e7c4ca53a47048"
        }
      ]
    }
  ]
}
