{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-gradle-utils",
    "version": "fab1d15-add-quality-code-analysis-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-gradle-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "21ec2db4f8ee2602de6dc72b1b840125cb3c5b1caf3ff0191bfcaffe6c60f698d27f347e25c5caab83570b0add2cbfa956dcc77459643cd9ecc2efa411d5e5ef",
          "sha256": "1c9cc295397190fcd2f21461617f9337c2e2a2296170ca8500cc2840279e0bec",
          "sha1": "d7f4c3e267749a61e2a6f897bb01300ba8d81e7b",
          "md5": "32ede9c44366fabd2b1320e5c28b679d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-gradle-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "url": "antibytes-gradle-utils-fab1d15-add-quality-code-analysis-SNAPSHOT.jar",
          "size": 9568,
          "sha512": "21ec2db4f8ee2602de6dc72b1b840125cb3c5b1caf3ff0191bfcaffe6c60f698d27f347e25c5caab83570b0add2cbfa956dcc77459643cd9ecc2efa411d5e5ef",
          "sha256": "1c9cc295397190fcd2f21461617f9337c2e2a2296170ca8500cc2840279e0bec",
          "sha1": "d7f4c3e267749a61e2a6f897bb01300ba8d81e7b",
          "md5": "32ede9c44366fabd2b1320e5c28b679d"
        }
      ]
    }
  ]
}
