{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-processor",
    "version": "5a5166e-add-class-cracker-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 84829,
          "sha512": "719b1579443d635030136312a4822f12299d85df50125a124491be42f3010d95574d0bec9e1883642c5051b349aa32bd098de718d7d3df93ede1c09ac369ebc2",
          "sha256": "3577f416899d13765ca53e811eac33d8110018480d95c0c345e575d4b80d2b8f",
          "sha1": "4942cc12dc32d3059e10884bfa984749c86d6d16",
          "md5": "eebd460bffbf86f8a97f12df56a3d2c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "tech.antibytes.kmock",
          "module": "kmock",
          "version": {
            "requires": "5a5166e-add-class-cracker-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-processor-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "url": "kmock-processor-5a5166e-add-class-cracker-SNAPSHOT.jar",
          "size": 84829,
          "sha512": "719b1579443d635030136312a4822f12299d85df50125a124491be42f3010d95574d0bec9e1883642c5051b349aa32bd098de718d7d3df93ede1c09ac369ebc2",
          "sha256": "3577f416899d13765ca53e811eac33d8110018480d95c0c345e575d4b80d2b8f",
          "sha1": "4942cc12dc32d3059e10884bfa984749c86d6d16",
          "md5": "eebd460bffbf86f8a97f12df56a3d2c6"
        }
      ]
    }
  ]
}
