{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.1.1-add-default-freezing-flag-SNAPSHOT/kmock-0.1.1-add-default-freezing-flag-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.1.1-add-default-freezing-flag-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-default-freezing-flag-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-default-freezing-flag-SNAPSHOT.jar",
          "size": 308664,
          "sha512": "8662823c64614f18804da1ec8e6ae9db52db89a4bcf86daebb65f767c98fe45781ab853136a2dbc59a6f8b37f894883183e16b97c2ef10547d0e9715c208b169",
          "sha256": "86dc8d020900d90aeffc052229bb3a13ba5a60c4068c6e4e623c746e3f87bbc5",
          "sha1": "c6d7405fe4cbbaf0eab147aa4a538d60cd4908b0",
          "md5": "bb4ec2e6b986f674426a163ebaf48f29"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.1.1-add-default-freezing-flag-SNAPSHOT.jar",
          "url": "kmock-jvm-0.1.1-add-default-freezing-flag-SNAPSHOT.jar",
          "size": 308664,
          "sha512": "8662823c64614f18804da1ec8e6ae9db52db89a4bcf86daebb65f767c98fe45781ab853136a2dbc59a6f8b37f894883183e16b97c2ef10547d0e9715c208b169",
          "sha256": "86dc8d020900d90aeffc052229bb3a13ba5a60c4068c6e4e623c746e3f87bbc5",
          "sha1": "c6d7405fe4cbbaf0eab147aa4a538d60cd4908b0",
          "md5": "bb4ec2e6b986f674426a163ebaf48f29"
        }
      ]
    }
  ]
}
