{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/6050120-bump-antibytes-SNAPSHOT/test-utils-6050120-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "6050120-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-6050120-bump-antibytes-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "b87044f23e2e7ab6e6ffd3d45827311593943394bfdac68a502473292872df464676e8d6eb6cd0d0f00674713f7368b969c2a8ff427dbb200a7a7718abc2acbd",
          "sha256": "8bd595d9fcceb94e45785d9d7de15d1fcac191327661fe3bb9b7c1ec4e6b86cc",
          "sha1": "a129b52ccf620cdd1a06deb5eb446f18321dd42c",
          "md5": "546d47a46d2c5b378c1c8c7f2ab7ff7d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm.jar",
          "url": "test-utils-jvm-6050120-bump-antibytes-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "b87044f23e2e7ab6e6ffd3d45827311593943394bfdac68a502473292872df464676e8d6eb6cd0d0f00674713f7368b969c2a8ff427dbb200a7a7718abc2acbd",
          "sha256": "8bd595d9fcceb94e45785d9d7de15d1fcac191327661fe3bb9b7c1ec4e6b86cc",
          "sha1": "a129b52ccf620cdd1a06deb5eb446f18321dd42c",
          "md5": "546d47a46d2c5b378c1c8c7f2ab7ff7d"
        }
      ]
    }
  ]
}
