{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/653aadf/core-653aadf.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "653aadf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-653aadf.klib",
          "url": "core-js-653aadf.klib",
          "size": 61533,
          "sha512": "44bcee89e681f26ff66cc302ef166de41f5161f14962bfb8569d9c306cb9fd7287ebc560c5db49f30273cd07cd5fcddc3ec8f57133e656e84d177fa30b55a962",
          "sha256": "7ea3cbbf5ee7dad33aabd4b841f1e9ca93ba6121767f7f24235a9125a3c58149",
          "sha1": "e189515bf5e31f8d9a1c99e64595089f94ac1adf",
          "md5": "e39fd04b9451059bc9960c621f59387a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-653aadf.klib",
          "url": "core-js-653aadf.klib",
          "size": 61533,
          "sha512": "44bcee89e681f26ff66cc302ef166de41f5161f14962bfb8569d9c306cb9fd7287ebc560c5db49f30273cd07cd5fcddc3ec8f57133e656e84d177fa30b55a962",
          "sha256": "7ea3cbbf5ee7dad33aabd4b841f1e9ca93ba6121767f7f24235a9125a3c58149",
          "sha1": "e189515bf5e31f8d9a1c99e64595089f94ac1adf",
          "md5": "e39fd04b9451059bc9960c621f59387a"
        }
      ]
    }
  ]
}
