{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit4/ad28a6d-remove-dependency-plugin-SNAPSHOT/test-utils-annotations-junit4-ad28a6d-remove-dependency-plugin-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit4",
    "version": "ad28a6d-remove-dependency-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4.klib",
          "url": "test-utils-annotations-junit4-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT.klib",
          "size": 11351,
          "sha512": "eab01ccdc633125109f8844313c375f7821d74fd72713a110dcd21edadaadb67d0f9a4f42aea27872ff5873c6eca1367eabd6516f3e6f718c879785be3d3b229",
          "sha256": "ac318de8cc81066e0b59e7ee3b0d09e9f2fe1fa5288b0f460273a0d91e085660",
          "sha1": "8461e6ece21752696e7b9b24da62772ef6133a3b",
          "md5": "eb05bdc9218caeac1aafb0b1c4779775"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit4-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit4-iosarm64-ad28a6d-remove-dependency-plugin-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1b5723e4b061417cdc3b3ae931c7bbdb1bfb4d2700d33f1c9454269bffe064555ac69821b97a32cbca57e1f913eb6837a269c77c7b134b043d08967945c9f676",
          "sha256": "feb2ae68e485447e39a392541654eb350ee2484b49e08f9af1cc467775ea97f2",
          "sha1": "c23bb29311c27bb8912229da3638621b5c7f4db8",
          "md5": "4843a9a00b79bff60d74b803e6d0d91c"
        }
      ]
    }
  ]
}
