{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.4.0-add-more-sources-SNAPSHOT/core-0.4.0-add-more-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.4.0-add-more-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm32-0.4.0-add-more-sources-SNAPSHOT.klib",
          "size": 105834,
          "sha512": "c3d2dfc5a6702050657a03d5351391e4bdb26926a195154abbf6e85269578658faacc631b493fc9159a8d567e7d4ba34cc24380ceedc043f72a21968dfcbbdbc",
          "sha256": "2f9b59c1de4f75965ecb2465ab2ebbaed21d7d005fe1b8f58c7664df8a0b42fb",
          "sha1": "c362d854ad4aca10ad5550c7a67ef1e21ca491e5",
          "md5": "c3d62e1366cf8ee2f4116b9d562930fb"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "url": "core-iosarm32-0.4.0-add-more-sources-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "db0f163583b094b9550536732da8b3c010683374c40092626c2e94ffdd737854286ee7a339a1862274eec1c873842a904a286defdb8a9441911ec82f95774747",
          "sha256": "1018b1e89f6cba8a716f7eae25656fa8cf79665c51d119c416c18af94e19a34f",
          "sha1": "2807ea4cb310ffe4cab650171e1e119f1d0c4cb9",
          "md5": "e0289688bcd36c5aa8dcdc4f098a8e6e"
        }
      ]
    }
  ]
}
