{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "0303a32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-0303a32.jar",
          "url": "antibytes-grammar-tools-0303a32.jar",
          "size": 39373,
          "sha512": "24d8ba2c529076ef8bebbf1faee99325fb000069d18b3b9ccab7ddb37cb3d4c658f2a1258dd907bccdae5226f6d56b3bda99393cc459da6e3933056221b17525",
          "sha256": "020f2c0a705429f5c6f1f0a2c14b2aa07913a6ffb67ef838417be923767ed620",
          "sha1": "3d94f7e99cf298e9666c0ddb0de6f5d384bcbeba",
          "md5": "e8b8601dd963badb0d05a28c6cb42cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-0303a32.jar",
          "url": "antibytes-grammar-tools-0303a32.jar",
          "size": 39373,
          "sha512": "24d8ba2c529076ef8bebbf1faee99325fb000069d18b3b9ccab7ddb37cb3d4c658f2a1258dd907bccdae5226f6d56b3bda99393cc459da6e3933056221b17525",
          "sha256": "020f2c0a705429f5c6f1f0a2c14b2aa07913a6ffb67ef838417be923767ed620",
          "sha1": "3d94f7e99cf298e9666c0ddb0de6f5d384bcbeba",
          "md5": "e8b8601dd963badb0d05a28c6cb42cf3"
        }
      ]
    }
  ]
}
