{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kfixture",
    "module": "ktx-datetime",
    "version": "0.4.0-bump-settings-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "tech.antibytes.kfixture",
          "module": "core",
          "version": {
            "requires": "0.4.0-bump-settings-plugin-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ktx-datetime-metadata-0.4.0-bump-settings-plugin-SNAPSHOT-all.jar",
          "url": "ktx-datetime-0.4.0-bump-settings-plugin-SNAPSHOT-all.jar",
          "size": 9008,
          "sha512": "b395b2e39c5a8ab7a0dc5083866b405a0c380e7bf8960dd6fc27ee2b3cf340df80eeb049d9d5811420140bb46193e466f644f5afac755c9ee506abeac245b15c",
          "sha256": "bdbd65cb13a6bc7a50835563e3d2e8430d084755b534ad8de1dfe333d6c871fb",
          "sha1": "b4fafcb2983d5aedfe66239fe28769d62c9a86ac",
          "md5": "5e6f0ba233baf2a011c2ec10cdf406e2"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktx-datetime-0.4.0-bump-settings-plugin-SNAPSHOT.jar",
          "url": "ktx-datetime-0.4.0-bump-settings-plugin-SNAPSHOT.jar",
          "size": 13895,
          "sha512": "9ee3586a8bf652694bcbc21fadd53fc06cf0ce4e39eb471eff823481f65599093313857afd9b042ed5250bb431c1ab1e0a9f3cc2cde04e43782c10167455c6a4",
          "sha256": "d6788a5bca195b236edcca8c10e31b3950f341d37a60bdb628f85b1b0331592f",
          "sha1": "4fda9486911b4394a0b45c460485de6acdf081db",
          "md5": "07a2f16b6c8aa0eb6a489a37ad9f2994"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-android-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-android/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-android-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-android",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosarm64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iosarm64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosarm64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iossimulatorarm64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iossimulatorarm64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iossimulatorarm64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iosx64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-iosx64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-iosx64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-iosx64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-js-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktx-datetime-js/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-js-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-js",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-jvm-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktx-datetime-jvm/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-jvm-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-jvm",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktx-datetime-linuxx64/0.4.0-bump-settings-plugin-SNAPSHOT/ktx-datetime-linuxx64-0.4.0-bump-settings-plugin-SNAPSHOT.module",
        "group": "tech.antibytes.kfixture",
        "module": "ktx-datetime-linuxx64",
        "version": "0.4.0-bump-settings-plugin-SNAPSHOT"
      }
    }
  ]
}
