{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/aae41ae-add-agnostic-sources-SNAPSHOT/kmock-aae41ae-add-agnostic-sources-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "aae41ae-add-agnostic-sources-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-aae41ae-add-agnostic-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-aae41ae-add-agnostic-sources-SNAPSHOT.jar",
          "size": 195134,
          "sha512": "4a97af1948794b60355bf066d5bcd408b4cec835f0f2b6a6616d997d93537ea4ce578b5d287ffb9521bcecc8b03223297887ffa64e024f8c5eb5d5b4df2f21ed",
          "sha256": "b2fd3cc01dec0235b15535b056565a758e8b651d3843df1c460da04b4a0fe9b7",
          "sha1": "03b031ad6712e551b9be41428969de88a1bac624",
          "md5": "d594d068694448d07f49cfac7b900384"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "tech.antibytes.test-utils-kmp",
          "module": "test-utils",
          "version": {
            "requires": "c3e5acf"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-aae41ae-add-agnostic-sources-SNAPSHOT.jar",
          "url": "kmock-jvm-aae41ae-add-agnostic-sources-SNAPSHOT.jar",
          "size": 195134,
          "sha512": "4a97af1948794b60355bf066d5bcd408b4cec835f0f2b6a6616d997d93537ea4ce578b5d287ffb9521bcecc8b03223297887ffa64e024f8c5eb5d5b4df2f21ed",
          "sha256": "b2fd3cc01dec0235b15535b056565a758e8b651d3843df1c460da04b4a0fe9b7",
          "sha1": "03b031ad6712e551b9be41428969de88a1bac624",
          "md5": "d594d068694448d07f49cfac7b900384"
        }
      ]
    }
  ]
}
