{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-add-integration-tests-SNAPSHOT/kmock-0.3.0-rc04-add-integration-tests-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-add-integration-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "bf484a6b86fa4d7263991b3060d7fadc7362b629ade1f7c38f21afa5b1239327ca336eb0e8afa05a1b97f2bcac7a47e1c28d1560dc4d604ebd191f1566279c76",
          "sha256": "e44bedf808d2beb44467cdab9cb464a21e2938c8146d26b2a4845cdd6defbcf2",
          "sha1": "515a3240c1e5455bc390ca366283f30d7d8cc8c4",
          "md5": "4efb79521b981306efdf99f90bf7930b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-js-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "url": "kmock-js-0.3.0-rc04-add-integration-tests-SNAPSHOT.klib",
          "size": 216314,
          "sha512": "bf484a6b86fa4d7263991b3060d7fadc7362b629ade1f7c38f21afa5b1239327ca336eb0e8afa05a1b97f2bcac7a47e1c28d1560dc4d604ebd191f1566279c76",
          "sha256": "e44bedf808d2beb44467cdab9cb464a21e2938c8146d26b2a4845cdd6defbcf2",
          "sha1": "515a3240c1e5455bc390ca366283f30d7d8cc8c4",
          "md5": "4efb79521b981306efdf99f90bf7930b"
        }
      ]
    }
  ]
}
