{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations-junit5/db53051-change-workflows-SNAPSHOT/test-utils-annotations-junit5-db53051-change-workflows-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations-junit5",
    "version": "db53051-change-workflows-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5.klib",
          "url": "test-utils-annotations-junit5-iosx64-db53051-change-workflows-SNAPSHOT.klib",
          "size": 7032,
          "sha512": "9dd0601834b08678789019a64ee926de7304a3d9d65f4c7a4d2f3a5685f479e843c284e57b8f0e05292678f2eab6a8d9e246e2dd4dc012b9b24408b25f19e584",
          "sha256": "84cc965a8a9abd7548d780843d87b9c3287fc38b4328d2e2f32762eff2805f16",
          "sha1": "7f4df3c700d46b9ca39d41ac50d387e31387c948",
          "md5": "858fedcbae3c0eb53c407f60ed4c5cda"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-junit5-iosx64-db53051-change-workflows-SNAPSHOT-metadata.jar",
          "url": "test-utils-annotations-junit5-iosx64-db53051-change-workflows-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c161714e52109441798af7b4c0d790f3edecc282c4391f5872c46f09ccb58848516d5247a86d7fe4e5c61135eddbbc70aec2f521ce8aba91ff19da306aac4ef0",
          "sha256": "b5aba2d2b4b902f3c1ce9f003fbbeba4850586f10a837d47c3b42235d80f62fe",
          "sha1": "1b832d5cdee06919b26e591577bed09c42b31fbf",
          "md5": "b6c5b8136c122b1d83d07e6078e89469"
        }
      ]
    }
  ]
}
