{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/bfa7c15-change-publishing-SNAPSHOT/test-utils-coroutine-bfa7c15-change-publishing-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "bfa7c15-change-publishing-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "0e4322ce8e5e251a8d27a3477733494fe2ca55eea67cee7267c26bd7278eded1fb271121121cd4181ce871099b68eb4be003404142c977d29690286b0fbf281d",
          "sha256": "33bcf8dea1f605c520b9a20fb934d035b24302bbff4c7a3f9c93ca99175e3d9b",
          "sha1": "b49be386280a6e19f280c39ae5d5cc6092e16766",
          "md5": "b13b9c091ca361376903ea82139f1ce0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "url": "test-utils-coroutine-jvm-bfa7c15-change-publishing-SNAPSHOT.jar",
          "size": 11975,
          "sha512": "0e4322ce8e5e251a8d27a3477733494fe2ca55eea67cee7267c26bd7278eded1fb271121121cd4181ce871099b68eb4be003404142c977d29690286b0fbf281d",
          "sha256": "33bcf8dea1f605c520b9a20fb934d035b24302bbff4c7a3f9c93ca99175e3d9b",
          "sha1": "b49be386280a6e19f280c39ae5d5cc6092e16766",
          "md5": "b13b9c091ca361376903ea82139f1ce0"
        }
      ]
    }
  ]
}
