{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.3.0-rc05-bump-kotlin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT.jar",
          "size": 75452,
          "sha512": "8d11eda74590d4ae172c745960ea95116710ad84f1f204b70323ff6b3e38714dab3811fdf22b70d97908a381a8bdde58bad8d23728a49ac0514faaf7d8411c25",
          "sha256": "b0de1e751f9599032570cec42994d72f9ca994eca4d08138db909c1999f012af",
          "sha1": "9416d6bc6472a8aaba8525f6e395130bee4c6449",
          "md5": "f8c5f783dc2900466167e52756dbcd82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT.jar",
          "size": 75452,
          "sha512": "8d11eda74590d4ae172c745960ea95116710ad84f1f204b70323ff6b3e38714dab3811fdf22b70d97908a381a8bdde58bad8d23728a49ac0514faaf7d8411c25",
          "sha256": "b0de1e751f9599032570cec42994d72f9ca994eca4d08138db909c1999f012af",
          "sha1": "9416d6bc6472a8aaba8525f6e395130bee4c6449",
          "md5": "f8c5f783dc2900466167e52756dbcd82"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "9335f32a2c9517d2891276ecce61e92ce32ee94ed9c00e6e93b82b753a18463128a47bf2983a9950e2810032a038f4d8392dede3bc99cc3768d0b2828125b2bc",
          "sha256": "99c03af49351b0cd8290b29616f80341f573a325455275d94a3b7798bec0a5fd",
          "sha1": "574d866a5f13b4534c4903feb61dd8c499749f41",
          "md5": "220278b9017807739b7bb79ec06dfa64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.3.0-rc05-bump-kotlin-SNAPSHOT-sources.jar",
          "size": 14719,
          "sha512": "6cca5df3f5679fdb5ff1e5553ac29216812ed758c8007ff570ad119b6af6d6ba53818dd5c459b936625d93e4d9aa6399e3bfe24faa7af530c9198a1b86a78d40",
          "sha256": "105faba3299868b574b53c791372e27075852b34d3f563ca61fc95ea9a18e8ee",
          "sha1": "772f6e65d966d99604b32d284d73ccdfdda730dd",
          "md5": "8e9f1f78fec94ded437ff7fbdf40ffbc"
        }
      ]
    }
  ]
}
