{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "4a148c3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "4a148c3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4a148c3.jar",
          "url": "antibytes-publishing-4a148c3.jar",
          "size": 117676,
          "sha512": "99f6ab951a80db8b4bfc043d8690bb9ccf69c19bcf23a9e249c8c95f1b07bff563f157b7faa1d52d5f3fd17b96fbc7c9f4cc741da099613c1a776039c197f6ff",
          "sha256": "1851dd3bf1b836ca07127aa096798176ee943e5df6b4f79cd55dafa25f1678bc",
          "sha1": "d026a2569caefcf3c3c9c68b851005a34f0ab429",
          "md5": "7f94131e8be4214a18c1a31893171c6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.2.0.202206071550-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "4a148c3"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "4a148c3"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-4a148c3.jar",
          "url": "antibytes-publishing-4a148c3.jar",
          "size": 117676,
          "sha512": "99f6ab951a80db8b4bfc043d8690bb9ccf69c19bcf23a9e249c8c95f1b07bff563f157b7faa1d52d5f3fd17b96fbc7c9f4cc741da099613c1a776039c197f6ff",
          "sha256": "1851dd3bf1b836ca07127aa096798176ee943e5df6b4f79cd55dafa25f1678bc",
          "sha1": "d026a2569caefcf3c3c9c68b851005a34f0ab429",
          "md5": "7f94131e8be4214a18c1a31893171c6d"
        }
      ]
    }
  ]
}
