{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-instant-fixture-SNAPSHOT/core-0.3.1-add-instant-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-instant-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "size": 134503,
          "sha512": "dc98356931ed8613bbe596e49dd437800e5484ba944c685eb7beef869b0319ac111f4f2ee566cca33aa9369d40edf511c1eee3386834db3a0517b375a7f98796",
          "sha256": "d2042891440ff5b47caa0b17bbe9496e70e6418caaeaba01ab39a7a2929a9eb8",
          "sha1": "d76921e391738b2de7766dc0c159fe1f71c70393",
          "md5": "ddc3e8a70704e718492d2ca6625ff038"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "size": 134503,
          "sha512": "dc98356931ed8613bbe596e49dd437800e5484ba944c685eb7beef869b0319ac111f4f2ee566cca33aa9369d40edf511c1eee3386834db3a0517b375a7f98796",
          "sha256": "d2042891440ff5b47caa0b17bbe9496e70e6418caaeaba01ab39a7a2929a9eb8",
          "sha1": "d76921e391738b2de7766dc0c159fe1f71c70393",
          "md5": "ddc3e8a70704e718492d2ca6625ff038"
        }
      ]
    }
  ]
}
