{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-add-instant-fixture-SNAPSHOT/core-0.3.1-add-instant-fixture-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-add-instant-fixture-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "size": 134503,
          "sha512": "453a9bb235783ae31c483a8ea8b303e20719304d6029d5c02fd917975d693bb94535de5cadf4479cf4d8e7fcc54427077d2b1e19b8d50c7c1ec5bd68a0e8931f",
          "sha256": "5194a3cc0318cbabf404cb8bb8aa2bfd62257889aa6541286efe74013b77eec9",
          "sha1": "76805308df5a51c5f3efa53c6f6568fb0745e721",
          "md5": "d3925f0e9252788678e9d0bd852d58c5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "url": "core-js-0.3.1-add-instant-fixture-SNAPSHOT.klib",
          "size": 134503,
          "sha512": "453a9bb235783ae31c483a8ea8b303e20719304d6029d5c02fd917975d693bb94535de5cadf4479cf4d8e7fcc54427077d2b1e19b8d50c7c1ec5bd68a0e8931f",
          "sha256": "5194a3cc0318cbabf404cb8bb8aa2bfd62257889aa6541286efe74013b77eec9",
          "sha1": "76805308df5a51c5f3efa53c6f6568fb0745e721",
          "md5": "d3925f0e9252788678e9d0bd852d58c5"
        }
      ]
    }
  ]
}
