{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.custom-component",
    "module": "antibytes-custom-component",
    "version": "7c5b6aa-add-splash-screen",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-custom-component-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-custom-component-7c5b6aa-add-splash-screen.jar",
          "size": 16177,
          "sha512": "fd4f95c774d4a1b5c5c0bba64d3df6d65e237d9805492627c6813125ca3f625a7a13746b73126efe1e493e231779eb54625c1cab31f7348831e88cc6d656ac6a",
          "sha256": "3fcd5b7f23fffc8fb4539ce58a5ed5ab35b91204970e7327b26f87c3044e9e54",
          "sha1": "19329da1ccabd4a4d67f0a412d4e803aa72a698b",
          "md5": "ac2dc662622c135c3d082e84cf907620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-custom-component-7c5b6aa-add-splash-screen.jar",
          "url": "antibytes-custom-component-7c5b6aa-add-splash-screen.jar",
          "size": 16177,
          "sha512": "fd4f95c774d4a1b5c5c0bba64d3df6d65e237d9805492627c6813125ca3f625a7a13746b73126efe1e493e231779eb54625c1cab31f7348831e88cc6d656ac6a",
          "sha256": "3fcd5b7f23fffc8fb4539ce58a5ed5ab35b91204970e7327b26f87c3044e9e54",
          "sha1": "19329da1ccabd4a4d67f0a412d4e803aa72a698b",
          "md5": "ac2dc662622c135c3d082e84cf907620"
        }
      ]
    }
  ]
}
