{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "efcbef2-change-generics-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-efcbef2-change-generics-SNAPSHOT.jar",
          "url": "kmock-gradle-efcbef2-change-generics-SNAPSHOT.jar",
          "size": 56204,
          "sha512": "34d4e9c8596ee108f274f02477dd849d42e4ed7a099b331126e13295d1964f7e819ceeb18f536c6c8a4d2b662f2fe48f8d1d8460390f60ae1e15c0357b3e6c8f",
          "sha256": "cad66d12e7336854e0937a6bf9fca992b63303980b5cfed8b93d013fa29d47fd",
          "sha1": "2284fb1685a6e8f05dd88ee25bc3e627940bfbe6",
          "md5": "96acecc46af33e2e50e292a56c8967be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-efcbef2-change-generics-SNAPSHOT.jar",
          "url": "kmock-gradle-efcbef2-change-generics-SNAPSHOT.jar",
          "size": 56204,
          "sha512": "34d4e9c8596ee108f274f02477dd849d42e4ed7a099b331126e13295d1964f7e819ceeb18f536c6c8a4d2b662f2fe48f8d1d8460390f60ae1e15c0357b3e6c8f",
          "sha256": "cad66d12e7336854e0937a6bf9fca992b63303980b5cfed8b93d013fa29d47fd",
          "sha1": "2284fb1685a6e8f05dd88ee25bc3e627940bfbe6",
          "md5": "96acecc46af33e2e50e292a56c8967be"
        }
      ]
    }
  ]
}
