{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/ebcd7e9-bump-antibytes-SNAPSHOT/test-utils-ktor-ebcd7e9-bump-antibytes-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "ebcd7e9-bump-antibytes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "7cbf8f5327a6c38cdcb2c7fc6f335a67e97bd816972f062a94a745622d904b6beb4115160e24f8dbd6c7aef1ba01587db6e9938d72cb1ab4c3f0c482d55fb780",
          "sha256": "3d551b8825cf0081c85a59a3af7973e1985f3da4fbcfd72e8995b3c9890bd6c2",
          "sha1": "12e0bd82771dab54e06dceb7544bd516b6b5bdba",
          "md5": "62b427e256b4e08726b20fcd6bf85a91"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "url": "test-utils-ktor-js-ebcd7e9-bump-antibytes-SNAPSHOT.klib",
          "size": 11895,
          "sha512": "7cbf8f5327a6c38cdcb2c7fc6f335a67e97bd816972f062a94a745622d904b6beb4115160e24f8dbd6c7aef1ba01587db6e9938d72cb1ab4c3f0c482d55fb780",
          "sha256": "3d551b8825cf0081c85a59a3af7973e1985f3da4fbcfd72e8995b3c9890bd6c2",
          "sha1": "12e0bd82771dab54e06dceb7544bd516b6b5bdba",
          "md5": "62b427e256b4e08726b20fcd6bf85a91"
        }
      ]
    }
  ]
}
