{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/b452879-fix-docs-SNAPSHOT/test-utils-b452879-fix-docs-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "b452879-fix-docs-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-b452879-fix-docs-SNAPSHOT.klib",
          "size": 14405,
          "sha512": "a83f77382284dc34042a29118c65e364fda5f87b90e7f94435bec85fb1decc5cbdcf90700fdb923f9eaaf0b78b510c4e2829431f37750f322971fa5016bab1ab",
          "sha256": "df5c1c6e76e8d90512ebb6607b0347d4c076a929b5c9b1ebe1f919c5f52dbf82",
          "sha1": "bc592cbed3c070d337e93db635b8046bad950758",
          "md5": "764862a43813ad1f5f4681b9d1726518"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-b452879-fix-docs-SNAPSHOT-metadata.jar",
          "url": "test-utils-iossimulatorarm64-b452879-fix-docs-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9c87bcfff64474be1dedcf587b1efd3270f0dfa057560fff611466f9d816bee1ae7cd2ea2b545c8c6d5f6e3b266c9153e91d6c9431268d90af36fb46afbdd806",
          "sha256": "4a3e53e46462ccd42796bc4a79f2cc9c0699bc0b91d970444406261679f6f2a6",
          "sha1": "a1305b3bc952c41ce2fe96909f51f3a2d6441136",
          "md5": "56d65404c43406a5179eee5ff81aa25d"
        }
      ]
    }
  ]
}
