{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.kmock",
    "module": "kmock-gradle",
    "version": "0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 47595,
          "sha512": "bd2b06854036ed94f219e9844ef5d0abde32a0ce229f0be84b8d1070677e1485f9a773c15d7061937c5cbd40922893a3d13ed9ddbb3cb25a6321a66f59f1de53",
          "sha256": "a9155b43fca246d5bf8cd238141946b656af1e6009e8ff6426719a7fbc9869ba",
          "sha1": "773ec0d52c39c8d55e2b5952835e983a2937bcb4",
          "md5": "438df4b865ee911b95f689689ec5f4e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "url": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT.jar",
          "size": 47595,
          "sha512": "bd2b06854036ed94f219e9844ef5d0abde32a0ce229f0be84b8d1070677e1485f9a773c15d7061937c5cbd40922893a3d13ed9ddbb3cb25a6321a66f59f1de53",
          "sha256": "a9155b43fca246d5bf8cd238141946b656af1e6009e8ff6426719a7fbc9869ba",
          "sha1": "773ec0d52c39c8d55e2b5952835e983a2937bcb4",
          "md5": "438df4b865ee911b95f689689ec5f4e9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT-javadoc.jar",
          "url": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "9b69760b8a5dcfa479b4d3356c12782381216d96ae85eef44412fb2203a708c872c33b8a5bd3c2a0c2626180c7a0a6783e406d5e0e9a1aa87ec55090035eb6c6",
          "sha256": "08e145092b1186a422ca7af7471e7288424e614e2d65362879036d3b0b29d476",
          "sha1": "68eab30f33a3694fc06165769b7b229ed7cbef5e",
          "md5": "eb3cbe30abcc54d87f7548f36c870362"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT-sources.jar",
          "url": "kmock-gradle-0.1.1-fix-sonarcloud-codecoverage-SNAPSHOT-sources.jar",
          "size": 10937,
          "sha512": "5521f9721d264cc512fe2ee172d745215732dc7b02e78afdfe56c08d0a1eec48de1da73530997361af01179543ce27f60eaf8b68f0315b5e14fc74e06c07047e",
          "sha256": "b122b7013ce4fb9b1c0190adacafdb214f294ab2299da8fcb205a1ac1ec23ce8",
          "sha1": "0ac8d1494e7a9e8b4720e74b8921b73e2e8aa8c6",
          "md5": "bfbf3abda1acc5ad6fc0f12bf58f9a77"
        }
      ]
    }
  ]
}
