{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "54603a4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-54603a4.jar",
          "url": "antibytes-grammar-tools-54603a4.jar",
          "size": 39373,
          "sha512": "795ad8c18fd582c42639b7aeabee384206053c2e6e9870fc61c2aeeef5338fe23c2231f09a6484297f34803ea7e7ebe155dccffd047475e1d69b5c7af2069bf1",
          "sha256": "651c58d99411ab4b165cd360607da84d6d14d4f8c5200d4a9f533eb608947736",
          "sha1": "61f729f7a795b5ccc10ff8b39c21b70c65ffc92b",
          "md5": "a6834afcc4049710c8f13b2ca8c572da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-54603a4.jar",
          "url": "antibytes-grammar-tools-54603a4.jar",
          "size": 39373,
          "sha512": "795ad8c18fd582c42639b7aeabee384206053c2e6e9870fc61c2aeeef5338fe23c2231f09a6484297f34803ea7e7ebe155dccffd047475e1d69b5c7af2069bf1",
          "sha256": "651c58d99411ab4b165cd360607da84d6d14d4f8c5200d4a9f533eb608947736",
          "sha1": "61f729f7a795b5ccc10ff8b39c21b70c65ffc92b",
          "md5": "a6834afcc4049710c8f13b2ca8c572da"
        }
      ]
    }
  ]
}
