{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "632b88a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-632b88a.jar",
          "url": "antibytes-dependency-632b88a.jar",
          "size": 32373,
          "sha512": "5a85c57bff917c58714040893fa5f97aec4c5bd5c6261874a34b42409194c8bb261b9bc66957ffd226986b5721633621c149cdf9ede63c2e07772e9fabe7790b",
          "sha256": "a9ea5825bf02d626dc946f7a44eefd2fb17cc297260e9739b87023534f0dcc10",
          "sha1": "d79ab91805374d440b810389f4c59217619ebbf7",
          "md5": "a73df429686a90351d83f1533393eb7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.39.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "6.5.1"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.43.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "632b88a"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-632b88a.jar",
          "url": "antibytes-dependency-632b88a.jar",
          "size": 32373,
          "sha512": "5a85c57bff917c58714040893fa5f97aec4c5bd5c6261874a34b42409194c8bb261b9bc66957ffd226986b5721633621c149cdf9ede63c2e07772e9fabe7790b",
          "sha256": "a9ea5825bf02d626dc946f7a44eefd2fb17cc297260e9739b87023534f0dcc10",
          "sha1": "d79ab91805374d440b810389f4c59217619ebbf7",
          "md5": "a73df429686a90351d83f1533393eb7c"
        }
      ]
    }
  ]
}
