{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.3.1-bump-min-ios-version-SNAPSHOT/core-0.3.1-bump-min-ios-version-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.3.1-bump-min-ios-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-bump-min-ios-version-SNAPSHOT.klib",
          "url": "core-js-0.3.1-bump-min-ios-version-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "7bebbb96fe320e5e0948de57c97cba90a8b1c723b190e519a163985492b5282b33a6849b8cdd33d0d63a71c6ec27336ad98d6ced9c172b79770657a0018c9318",
          "sha256": "a38f8d06d36a3805e6eea37d25e177dc6f34354a3addb71ef9cf6e759c774203",
          "sha1": "67b92ee96e1742729e40e00bff2df1d3c52c3fe6",
          "md5": "0785ffc9a6e33f41be06783d312a5cbd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-js-0.3.1-bump-min-ios-version-SNAPSHOT.klib",
          "url": "core-js-0.3.1-bump-min-ios-version-SNAPSHOT.klib",
          "size": 134545,
          "sha512": "7bebbb96fe320e5e0948de57c97cba90a8b1c723b190e519a163985492b5282b33a6849b8cdd33d0d63a71c6ec27336ad98d6ced9c172b79770657a0018c9318",
          "sha256": "a38f8d06d36a3805e6eea37d25e177dc6f34354a3addb71ef9cf6e759c774203",
          "sha1": "67b92ee96e1742729e40e00bff2df1d3c52c3fe6",
          "md5": "0785ffc9a6e33f41be06783d312a5cbd"
        }
      ]
    }
  ]
}
