{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.2.0-change-intArray-generator-SNAPSHOT/core-0.2.0-change-intArray-generator-SNAPSHOT.module",
    "group": "tech.antibytes.kfixture",
    "module": "core",
    "version": "0.2.0-change-intArray-generator-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iossimulatorarm64-0.2.0-change-intArray-generator-SNAPSHOT.klib",
          "size": 75835,
          "sha512": "290b047a27467f481b1437f751649f74e87358a5a0ca1d13b5346bff600e87ecd614f12e452f26c7a5955cf39d6d23d9db1a0c7046afa964bf79d77d01441349",
          "sha256": "6113119530ce5a85423efed866777b305d4244864d5b10124e2428889d9075f2",
          "sha1": "617ee68dae79808b26536551b80387077494af2e",
          "md5": "c0034b03df2cc93dc0c859df59bd5d33"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-isolate",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.2.0-change-intArray-generator-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.2.0-change-intArray-generator-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c61c7ae57e4449b2759a6bf77f51b5ea4411c4051c50195a54febfe93cdc4585a05cf404dec025cb86a36045f791ddfefdbacc20718056f6f0660a6aeaa7c2b5",
          "sha256": "12ced84ed08cce1583dd0e70b267b8f1e2c36c35d43199c9fefb5efb2b2fda16",
          "sha1": "e899e11bf53f93522ecb717e105040026e35c6e5",
          "md5": "e4d20eb0df5d776a291b208bb1221a89"
        }
      ]
    }
  ]
}
