{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/3469f60-add-ios-SNAPSHOT/test-utils-coroutine-3469f60-add-ios-SNAPSHOT.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "3469f60-add-ios-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-3469f60-add-ios-SNAPSHOT.klib",
          "size": 9695,
          "sha512": "389ab876fa0e30248910a538b807eb8027cdbddb5981ba0d38a20b2ec086ee97de062e9e46f8f70a4cf606d438ced4ccb85a248647f1c2e10c56e4c127af8bea",
          "sha256": "e678571d059cc4a5dfb515375fdfe722bef0357d8e4e870638110638a214cdab",
          "sha1": "67aef98a30d3d0a7f01bbd890a495a95e91a84cd",
          "md5": "9f3d3a9c975b85ddbdd4fc68b9732b05"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-metadata.jar",
          "url": "test-utils-coroutine-iosx64-3469f60-add-ios-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2bbfc8f06c507dfa0edba73cc7c3c45c1aa930a787f6fbb3b7e349c055a3328c3808a0e1a34217115a4e239e3cb1c11532550fd87fd453e5ebb73ab8b1940e12",
          "sha256": "5a945a415e591ab8bf1fc22cd03f47ef8c20a8fde3f14d11089face642a27559",
          "sha1": "df1a5023844770cd48a593bf10278f77713013d3",
          "md5": "618c40f4116f033ff36868dc8356bbd3"
        }
      ]
    }
  ]
}
