{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmock/0.3.0-rc04-bump-setup-SNAPSHOT/kmock-0.3.0-rc04-bump-setup-SNAPSHOT.module",
    "group": "tech.antibytes.kmock",
    "module": "kmock",
    "version": "0.3.0-rc04-bump-setup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-bump-setup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-bump-setup-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "c1301345c94b1f234ab546f9bfd8dd581e1626066b9d85e54899afddec32fe17872c07a687a1ef9072ec2a0f9e10d114a66bf3eccf155fd411dd8cc46f15b73d",
          "sha256": "1e160e2797c96694809be87de16f858a7b5446e3dee141a4edccbcea5a3f2ef2",
          "sha1": "5a5ecefc224f6f3427236bcfd001f03d7618e804",
          "md5": "31eeb6c886aa6ba4e95fb6eca441006b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "kmock-jvm-0.3.0-rc04-bump-setup-SNAPSHOT.jar",
          "url": "kmock-jvm-0.3.0-rc04-bump-setup-SNAPSHOT.jar",
          "size": 401239,
          "sha512": "c1301345c94b1f234ab546f9bfd8dd581e1626066b9d85e54899afddec32fe17872c07a687a1ef9072ec2a0f9e10d114a66bf3eccf155fd411dd8cc46f15b73d",
          "sha256": "1e160e2797c96694809be87de16f858a7b5446e3dee141a4edccbcea5a3f2ef2",
          "sha1": "5a5ecefc224f6f3427236bcfd001f03d7618e804",
          "md5": "31eeb6c886aa6ba4e95fb6eca441006b"
        }
      ]
    }
  ]
}
