{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-test-utils",
    "version": "790b67f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-test-utils-790b67f.jar",
          "url": "antibytes-test-utils-790b67f.jar",
          "size": 15046,
          "sha512": "d1f7a7bb2a88587f2962ba5e61f49b6f84829a0251a42f448e3c652ab1f106c842b7ddd29fc847050b193a2cd71db768bc940fdf44af6971f7612a1fd80ec9d1",
          "sha256": "db733e197d4522816c3a016c32f1bae880c536ea63c23d7c5bd6614f36ef2805",
          "sha1": "1a88cf6f706885b1e4f6822a0c2f73d121f19124",
          "md5": "16e9cb304abd0dbef340ec4d9a19743b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-test-utils-790b67f.jar",
          "url": "antibytes-test-utils-790b67f.jar",
          "size": 15046,
          "sha512": "d1f7a7bb2a88587f2962ba5e61f49b6f84829a0251a42f448e3c652ab1f106c842b7ddd29fc847050b193a2cd71db768bc940fdf44af6971f7612a1fd80ec9d1",
          "sha256": "db733e197d4522816c3a016c32f1bae880c536ea63c23d7c5bd6614f36ef2805",
          "sha1": "1a88cf6f706885b1e4f6822a0c2f73d121f19124",
          "md5": "16e9cb304abd0dbef340ec4d9a19743b"
        }
      ]
    }
  ]
}
